### ISSUE TITLE
Make cancel curve tool on esc

### ISSUE THREAD

**Issue by Disinterpreter** [aseprite/aseprite#1002]
Please make cancel Curve Tool (or all tools) on press "Esc", i think it's comfortable ;)

**Comment by dacap** [comment]
Hi @Disinterpreter, the `Esc` key cancels the tool, but it looks like it doesn't refresh the editor. I'll mark this as a bug.

**Comment by dacap** [comment]
Just as a side note, you can cancel the curve tool (or any other tool) pressing the other mouse button (e.g. you start drawing pressing left mouse button, and you want to cancel, so you can press the right button, and then release both buttons).
