### ISSUE TITLE
Custom Brush Corruption Bug (?)

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1004]
1. Create a 50% dither pattern in 2x2 pixels
2. Select those 2x2 pixels with the marquee tool
3. Create a new brush using the 2x2 dither pattern.
4. Press X (swap foreground and ground color) twice.

You are now painting with a solid color block. It stays this way even if you reselect the brush, or reload the program after saving it.

![brushcorruption](https://cloud.githubusercontent.com/assets/8582123/13578147/2b193718-e464-11e5-9ce8-069c5d3cd008.gif)

You can also corrupt it by making both foreground and background color the same, seen above.

Aseprite 1.1.4-beta1 on Windows Vista 32 Bit

**Comment by dacap** [comment]
This is a known issue. When you click a color in the colorbar, the brush itself is modified, so if you select the same color, the brush is "destroyed" (because both colors were replaced with the same one).

A solution would be to keep the original brush and colors are replaced from there.

**Comment by dacap** [comment]
Fixed, this will be available on v1.1.5
