### ISSUE TITLE
Reset last drawn point after undo for draw line behavior

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1005]
1. Make a brush stroke with the pencil tool
2. Shift click a bit to the right to create a line from the last point of the brush stroke to to the current mouse position.
3. Undo with ctrl+z.
4. Shift click slightly above the current mouse's position. 

You will get a line from where the undone stroke ended, rather than where the stroke before it ended. I think it's a bug because it does reset the point when "cancelling" a stroke using the opposite mouse click button. The black stroke in the image below shows the undo with control+z not resetting the point, while the blue stroke shows the point getting reset.

![asepriteresetdrawpoint](https://cloud.githubusercontent.com/assets/8582123/13593961/6628c9f8-e4ce-11e5-80b7-388352e919fd.gif)

Aseprite 1.1.4-beta1

**Comment by dacap** [comment]
Hi @KasumiArai, quite complex to be fixed, but I'll see what we can do. (It looks like UI editor information should be saved in undo steps.)

**Comment by dacap** [comment]
I'm going to fix this one in the following way: The last painted color will be a data stored in the sprite (i.e. shared between all editors), so the undo information will save/restore that last point information.
