### ISSUE TITLE
Pressing "Open Folder" in pallet presets freezes the program

### ISSUE THREAD

**Issue by batmanasb** [aseprite/aseprite#1008]
When I press the "presets" button to choose a pallet preset and then press the "Open Folder" button, the entire program just freezes.

Aseprite version: Steam build for Linux (v1.1.3)
OS: Linux Mint 17.3

Before using this Steam build, I had been using a compiled build (v1.1.2-dev) and pressing Open Folder wouldn't freeze, instead it opened up a folder browser.

**Comment by dacap** [comment]
Hi @batmanasb, could you please check the latest release v1.1.5.1 to see if this issue is fixed?

**Comment by batmanasb** [comment]
Just checked on the latest version on steam (v1.1.5.1) and the issue is still there.

**Comment by dacap** [comment]
I'll try to create a Mint VM to reproduce this. On Ubuntu it works correctly. Does Mint include [xdg-open command line utility](https://wiki.archlinux.org/index.php/Xdg-open)?

**Comment by batmanasb** [comment]
It might have something to do with the different desktop environments and/or file managers, but I'm not experienced in this area. 

Also, yes, Mint does include the xdg-utiles package (which comes with xdg-open).
