### ISSUE TITLE
Strange dlfcn.h error

### ISSUE THREAD

**Issue by Jengamon** [aseprite/aseprite#1010]
I get a strange error where the CMake complains that I need "dlfcn.h or something that defines dlopen()/dlclose()". I checked the build cache (CMakeCache.txt) and it said I had dlfcn.h (HAS_DLFCN_H=1), but when I comment out the ifdef, it compiles as normal...

**Comment by dacap** [comment]
Hi @Bobhostern, in which Linux distribution you're compiling?
