### ISSUE TITLE
[website] Audio link for pronunciating "Aseprite" is broken.

### ISSUE THREAD

**Issue by mitchhentges** [aseprite/aseprite#1014]
On the [Pronunciation page](http://www.aseprite.org/pronunciation/), clicking "audio" brings up another page saying that "Video playback aborted due to a network error."
![2016-03-13-204627_1680x1021_scrot](https://cloud.githubusercontent.com/assets/7784737/13730894/ba36cc60-e95c-11e5-9265-0a9f8468cdfb.png)

**Comment by dacap** [comment]
Finally fixed: http://www.aseprite.org/pronunciation/ 😄
