### ISSUE TITLE
Can't find LX11 on Korora 23 (Fedora)

### ISSUE THREAD

**Issue by GizmoCodes** [aseprite/aseprite#1017]
I'm on [Korora](http://kororaproject.org) 23, which is a Fedora remix.
http://pastebin.com/waJmUdKY
I followed the instructions, so it appears it can't find LX11, even though its installed.
(Ignore how the title was 'clear,' user error.)

**Comment by dacap** [comment]
It's strange because it looks like you have `libx11-dev` installed, but it's incompatible in some way. Maybe it's a `x86_64` version of the library and the current compiler is `x86` arch (`i386`). Would you mind to share the `CMakeCache.txt` file inside the `build` directory?

**Comment by GizmoCodes** [comment]
Heres the cache: http://pastebin.com/w8du9246
And, I _do_ have both the x86 (i386) and x86_64 versions of `libX11-devel` installed.

**Comment by GizmoCodes** [comment]
Odd. I didn't even change anything in my environment, and I decided to try to compile again, just for funzies. For some reason, it compiled correctly without error. I'm just gonna roll with it.
