### ISSUE TITLE
Command line export .png nothing happened.

### ISSUE THREAD

**Issue by alivegames** [aseprite/aseprite#1018]
Export .png not working.
"D:\Aseprite 1.1.3\Aseprite.exe" --batch "c:\Test.ase" --save-as "Test.png"

But .gif is working.
"D:\Aseprite 1.1.3\Aseprite.exe" --batch "c:\Test.ase" --save-as "Test.gif"

The same code in 1.1.1 is fine.
"D:\Aseprite 1.1.1\Aseprite.exe" --batch "c:\Test.ase" --save-as "Test.png"

**Comment by alivegames** [comment]
If I change --save-as to --sheet, it works.
"D:\Aseprite 1.1.3\Aseprite.exe" --batch "c:\Test.ase" --sheet "Test.png"

**Comment by alivegames** [comment]
Please enable history version download. I can not back to v1.1.1, because it has been overridden by v1.1.3. Thanks!

**Comment by dacap** [comment]
Hi @alivegames, I'll review this bug today. Anyway, please contact me at support@aseprite.org in case you would like to download v1.1.1.

**Comment by dacap** [comment]
Note: this bug was introduced in 978145ba7a5ad0b1f2909a6cfa0d1406126985cf when #902 was fixed

**Comment by dacap** [comment]
This fix will be released in v1.1.4.
