### ISSUE TITLE
Feature request (Bug?): Cycle text fields with the Tab-key in palette editor and colour pickers when in-focus.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1019]
It would be great if we could cycle through the various text fields in the palette editor and colour picker panes (RGBA, HSBA, Grey/Alpha, ..., plus the hex input field) when we press Tab instead of toggling the Timeline Pane while we're entering channel values. Naturally, Shift-Tab would cycle the fields in reverse sequence.

**This behaviour only applies when a text field in a colour selection pane is active;** if no text input field has focus, then Tab toggles the Timeline as normal. Tab behaves this way until either no field is selected or the active pane is closed or hidden.

It's nice to be able to enter a series of values with one keystroke instead of having to click through every one, especially when we want to enter several colours in a row.

Thanks for considering it!

**Comment by oceanhahn** [comment]
Any progress on this low-impact bug? :D

**Comment by dacap** [comment]
I've fixed this one, but I'm still thinking, should the focus be kept in the sliders? E.g. we click the Red slider, then press tab and we focus the Red text field, pressing Tab again the focus goes to the Blue slider, and pressing Tab again we focus the Blue text field.

As you said, it would be better if only text fields keep the focus. Right?

**Comment by oceanhahn** [comment]
If it was me, I'd probably cycle through the sliders, then through the fields, rather than through colour channels. My reasoning being that when I tab through text fields, I usually expect to be able to enter a value, then enter the next immediately afterwards. Whether I'm using a slider or a text input, once I settle on a value, I usually move directly on to the next channel, rather than having to tab twice to get to the next data element. I would not consider this extra keystroke to be a nuisance mind you, but perhaps trivially less expectable.

It might be useful to let the sliders have focus since using arrow keys to make single-increment adjustments could  be useful to people sometimes. But since you're asking me, I'd cycle the fields through whatever channels you're using, then the sliders through those channels.

Thanks for the fix! :D

**Comment by dacap** [comment]
I've noticed that on Photoshop, Tab key cycles only through text fields, and sliders don't get focused. And the way to make single-increments/decrements is using up/down arrow keys. It looks like a nice solution (touching sliders don't affect keyboard focus, so we can still press Tab to switch timeline, and only when we are on text fields Tab key starts to behave differently, and we don't lost the capacity to make single digits adjustments).

Next week I'll make the final tweaks to this fix.

**Comment by oceanhahn** [comment]
I was wondering about which arrow keys would change values. up/down makes sense in terms of numbers, but left/right kind of seems more intuitive for the sliders themselves. If you want to get really sneaky, you could set it up so that up/down increments values when the fields have focus (since left/right ought to move the cursor) and left/right (or left-down/right-up) increment/decrement values when the sliders have focus.

I kind of like the idea of the sliders being able to have focus, and receiving it when you click them, but that's just me, and I'm sure there are a hell of other things you'd rather do than set up that kind of thing. XD

**Comment by dacap** [comment]
^_^ I'll see what I finally do. I was writing a blog post to unify color selectors + palette editor + color bar (#492 #1102) but I need to think more about it.

**Comment by oceanhahn** [comment]
It would be nice if the palette editor and colour selectors were maybe the same tool but I also use 8P images almost exclusively, so it's a bigger deal to me. 24b images are a different situation for that kind of thing. :y 

I look forward to reading about it once you get it sorted out! :D
