### ISSUE TITLE
Feature request: add the default vga mode 13h palette as a preset

### ISSUE THREAD

**Issue by BPaden** [aseprite/aseprite#1020]
I think that would fit right in. I found a list of hex values here: https://commons.wikimedia.org/wiki/User:Psychonaut/ipalette.sh

**Comment by dacap** [comment]
The default palette of old Aseprite versions was the VGA palette. I don't think it's a pixel-art related palette, but it'd be good to have it back again anyway.

**Comment by winterheart** [comment]
Like this?
[vga-13h.gpl.txt](https://github.com/aseprite/aseprite/files/196002/vga-13h.gpl.txt)

**Comment by dacap** [comment]
Yes, it looks good to me. Could you please check if the values are the same as in [the default Allegro palette](https://github.com/aseprite/aseprite/blob/master/src/allegro/src/allegro.c#L107)? (values in the Allegro palette are in `[0,63]` range, so they must be:

    vga-15h.gpl value = Allegro value * 255 / 63

**Comment by winterheart** [comment]
Looks good except last color in Allegro reference (63, 63, 63, 0), it should be (0, 0, 0 , 0) (black, as in original VGA).

**Comment by dacap** [comment]
We can keep it as black. Thanks for take time about this, would you like to create a PR? I can add the gpl file directly anyway.

**Comment by winterheart** [comment]
Added pr #1045.
