### ISSUE TITLE
Feature Request: New Color Picking Tools/Options

### ISSUE THREAD

**Issue by slick1015** [aseprite/aseprite#1025]
I love Aseprite, but I found some things in other tools that I really really want in Aseprite.

Firstly, this http://i.imgur.com/sq2LAJ9.png
This is from Pyxel Edit and I think it is really helpful for getting shades and such.

Secondly, this http://img-cache.cdn.gaiaonline.com/7d9aa3199b5b4407c0180b232336243a/http://i364.photobucket.com/albums/oo87/BlargElite/PDNcolorwheel.jpg
I think this would pair really nicely with that first request. It much easier that a line of colors in my opinion. This I think is from a GIMP.

**Comment by dacap** [comment]
Hi @slick1015, I think I can merge this issue with #707.

For the first color picker, you can use the [new Color tint/shade/tone selector](http://i.imgur.com/Mx2CsQD.gif). There are no discrete steps as in Pyxel Edit but you can create tints and shades in a similar way.

The [color wheel is already included](http://imgur.com/081lwYa) :smile:
