### ISSUE TITLE
[Compilation] DirectX SDK installed, CMake GUI still giving DirectX required error

### ISSUE THREAD

**Issue by sarcasmloading** [aseprite/aseprite#1026]
I'm trying to compile Aseprite 1.1.3 on Windows 10 x64.

I've got the DirectX SDK installed (http://ccm.net/download/download-889-directx-sdk)

I have Visual Studio 2015 CE installed, and CMake GUI (3.5.0).

CMake GUI is set to Visual Studio 14 2015.

CMake GUI throws this error:

```
DirectX required for Windows port.  You might need to add DirectX include
  and lib directories to your INCLUDE and LIB environment variables.
```

I know what the PATH is, but I don't know if I need to add any variables.

The only other DirectX-related thing it can't find is DXGUID. (DXGUID_LIBRARY). I have seen DXGUID_LIBRARY bought up before.

Possibly irrelevant edit: I have compiled it before on Mac OS X 10.11 with "Unix Makefiles" successfully.

**Comment by sirblackheart** [comment]
Set the DXGUID_LIBRARY to the path of dxguid.lib. In my case that is `C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Lib/x86/dxguid.lib` for example.
Click configure again and then generate.
Additionaly you probably have to add dxguid.lib in Linker -> Input ->  Additional Dependencies of the aseprite project.

**Comment by sarcasmloading** [comment]
I can't find DXGUID_LIBRARY in the Environment Variables list. Do I need to add it?

**Comment by sarcasmloading** [comment]
Installing a different DirectX SDK fixed the problem.
Thanks for your help!

**Comment by sarcasmloading** [comment]
#1087, dxguid_library not found, try this:
https://www.microsoft.com/en-us/download/confirmation.aspx?id=6812
