### ISSUE TITLE
Add hotkey customization for maintaining aspect ratio while MAKING a selection

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1028]
I was talking to someone today who wanted to unbind the aspect ratio lock while making a selection (shift) because the default hotkey for adding to a selection is also shift. You can unbind the ratio lock while scaling the selection once the selection is made, but not the lock while creating a selection.

**Comment by dacap** [comment]
Hi @KasumiArai, I'm not sure if I understood it correctly, but is missing some option to remove the "shift" modifier as a "ratio lock" to select? right?

For example, here we have the "ratio lock" when we scale the selection:
![ratiolock](https://cloud.githubusercontent.com/assets/39654/13985393/3b69bd26-f0db-11e5-9269-ef2ce4dc4102.png)
But we still need the `Selection Tool: Maintain Aspect Ratio` item.

**Comment by KasumiArai** [comment]
You are understanding correctly. 
![maintainaspectratio](https://cloud.githubusercontent.com/assets/8582123/13986055/977308f2-f0d6-11e5-9aca-21ccb2b2a487.gif)
This cannot be unbound from shift.

**Comment by dacap** [comment]
I'll try to release v1.1.4-beta2 this week on Steam with this feature.

**Comment by dacap** [comment]
![newkeys](https://cloud.githubusercontent.com/assets/39654/14264430/15822c64-fa96-11e5-9380-98936c662e13.png)
