### ISSUE TITLE
Add aseprite mimetype

### ISSUE THREAD

**Issue by sirblackheart** [aseprite/aseprite#1031]
This would be needed so aseprite can be associated with its own files in the aseprite.desktop file as well as with thumbnail-generators. Not sure if you want to have this in the main repo or rather just added to the distributed package as with the aseprite.desktop file itself like mentioned in #952 .

Attached is an example aseprite.xml (i had to make it a txt so i could drag and drop it) of what this mimetype file could look like. It would have to be installed into "$XDG_DATA_DIRS/mime/packages/aseprite.xml".  $XDG_DATA_DIRS normaly defaults to "/usr/share". As well as a call to update-mime-database usr/share/mime, but that has to be done by the packager.

[aseprite.txt](https://github.com/aseprite/aseprite/files/186937/aseprite.txt)

**Comment by dacap** [comment]
I was thinking and I'll add these files in the repository. Maybe in a `misc` or `installation` directory.
