### ISSUE TITLE
Custom Hotkeys

### ISSUE THREAD

**Issue by paulmuad-dib** [aseprite/aseprite#1032]
We should be able to customize hotkeys.

A list of all the hotkeys should be available under preferences and can be changed from there. Options for filtering to actions that have the same hotkeys, use specific keys or have no hotkeys associated with them should be available.

Every item in a menu should be able to have a hotkey associated with it.

The possible syntax is an optional ordering of control, alternate and shift keys before another key that is not control, alternate or shift.

**Comment by dacap** [comment]
Is `Edit > Keyboard Shortcuts...` what you are looking for?

**Comment by paulmuad-dib** [comment]
Ah, I didn't notice that. The filtering would be a nice addition though.

**Comment by dacap** [comment]
The filtering/searching field is available [since v1.1.2](http://www.aseprite.org/release-notes/#aseprite-v1-1-2). Closing this issue.
