### ISSUE TITLE
GUI permanently tiny after unchecking "apply zoom" in preferences->grid & background

### ISSUE THREAD

**Issue by jameswilddev** [aseprite/aseprite#1033]
Hello.

I slipped and unchecked "apply zoom" in preferences->grid & background, and all GUI elements have shrank to be 1:1 with screen pixels whereas before they were much larger.  Rechecking the box does not undo this.  Is this intentional and is there a way of reverting it?

Using 1.1.3 portable on Windows 10.

Thanks, James.

![ui](https://cloud.githubusercontent.com/assets/3138458/14044270/72a09e34-f286-11e5-9144-04942feea936.png)

**Comment by dacap** [comment]
Hi James, go back to *Edit > Preferences* and change the "Screen Scaling" option to 200%. I'll release a patch soon.

**Comment by jameswilddev** [comment]
Aha!  Thanks.

**Comment by dacap** [comment]
(Note for future reference: If I remember correctly, this bug was fixed in 1d7184dd37461d2cc163a0a87eb7593f26e68714)
