### ISSUE TITLE
LBM file format

### ISSUE THREAD

**Issue by Mailaender** [aseprite/aseprite#1036]
https://github.com/aseprite/aseprite/blob/master/src/allegro/include/allegro/datafile.h#L92 registers it, but still I get:

![image](https://cloud.githubusercontent.com/assets/756669/14061125/6c9790e0-f378-11e5-8d9e-ff2bdb905270.png)

http://www.shikadi.net/moddingwiki/LBM_Format has more information on the file format.

**Comment by dacap** [comment]
Hi @Mailaender, sorry but we don't use Allegro to load/save files. LBM is not supported and there are no plans to support it. I'll leave this open just in case more people want to load LBM files.

As an extra note, we use these decoder/encoders: https://github.com/aseprite/aseprite/tree/master/src/app/file
