### ISSUE TITLE
Non clickable GUI in some window managers

### ISSUE THREAD

**Issue by derlorenz** [aseprite/aseprite#1037]
I am using i3wm and openbox. In both window managers the GUI seems to be unclickable, although the GUI elements change their color when I hover over them (like they should). The Problem also appears when I change the setting **Use native mouse cursor** in experimental settings.

**Comment by coffee-lord** [comment]
Are you running Archlinux by any chance? The `aseprite` package in AUR is pulling tagged git sources which don't include a fix from #971 yet. You can use `aseprite-git` to get the latest (master) version.

If you're not running Archlinux make sure you're using aseprite built from sources that include the fix from #971.

**Comment by dacap** [comment]
It is as @coffee-lord said, if you've used the v1.1.3 tag (or v1.1.3 source file zip) it doesn't included the fix. I'll add a new tag for the commit used in the official Linux distribution to avoid confusion.

**Comment by derlorenz** [comment]
Nice! Yes I am using Arch Linux and this worked for me. Thanks!
