### ISSUE TITLE
Windows DPI scaling causes blurry graphics unless disabled

### ISSUE THREAD

**Issue by jameswilddev** [aseprite/aseprite#1041]
When Windows is set to use DPI scaling (in Windows 10: settings->system->display->change the size of text, apps and other items) Aseprite looks blurry.  (bilinear filtered?)

![broken](https://cloud.githubusercontent.com/assets/3138458/14075470/6bd20eba-f4d1-11e5-8e07-c4a66ef6dc4f.png)

I can fix this by changing the compatability settings not to apply DPI scaling:

![setting](https://cloud.githubusercontent.com/assets/3138458/14075547/0140dd50-f4d2-11e5-9aa9-770f03ea4870.png)

I then have to use the GUI scaling option to make the GUI the same scale as the surrounding OS, but it then looks great:

![fixed](https://cloud.githubusercontent.com/assets/3138458/14075548/07351ec4-f4d2-11e5-8c42-620e76c3e3b8.png)

I think the reliability of stylus input is improved by doing this too though it's somewhat subjective.

It might be possible to do this without requiring configuration by the user, as outlined in https://msdn.microsoft.com/en-gb/library/windows/desktop/dn469266(v=vs.85).aspx (modifying the application manifest)

**Comment by dacap** [comment]
Hi @jameswilddev, thanks for reporting this issue. I saw that you are (probably) using the Steam version, could you please try if this bug happens in the [beta version](http://imgur.com/sVCTgjE)?

**Comment by jameswilddev** [comment]
It does unfortunately.

![upload](https://cloud.githubusercontent.com/assets/3138458/14084106/2848ecb4-f511-11e5-8441-98923630677b.png)

**Comment by vncastanheira** [comment]
When I enable the "Disable display scaling on high DPI settings" option, it stopped freezing on close.

**Comment by dacap** [comment]
I've tested adding a manifest and it doesn't fix the issue. I'll be investigating what is missing yet.

**Comment by dacap** [comment]
@vncastanheira I didn't know that the application freezing on close. Can you reproduce the problem? debug it? Or do you have [a crash report](http://imgur.com/9MTYI9k)?

**Comment by dacap** [comment]
Done, the manifest really fixed this issue, but we need a specific value (`True/PM`) (that is compatible with Windows Vista, 7, 8, 8.1, and 10).

**Comment by vncastanheira** [comment]
@dacap Since you fixed the DPI scaling, I will be testing the application in the next release.
