### ISSUE TITLE
Cannot build with CMAKE_USE_OPENSSL

### ISSUE THREAD

**Issue by rcorre** [aseprite/aseprite#1043]
When `CMAKE_USE_OPENSSL=on` (the default setting in `third_party/curl/CMakeLists.txt`), I see:

```
../lib/libcurl.a(ssluse.c.o): In function `ossl_connect_step1':
/home/rcorre/projects/contrib/aseprite/third_party/curl/lib/ssluse.c:1473: undefined reference to `SSLv3_client_method'
collect2: error: ld returned 1 exit status
src/CMakeFiles/aseprite.dir/build.make:181: recipe for target 'bin/aseprite' failed
make[2]: *** [bin/aseprite] Error 1
CMakeFiles/Makefile2:170: recipe for target 'src/CMakeFiles/aseprite.dir/all' failed
make[1]: *** [src/CMakeFiles/aseprite.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

This could just be a weird environment on my part, but my `/usr/include/openssl/opensslconf.h` disables `SSLv3_client_method` with:

```
#ifndef OPENSSL_NO_SSL3
# define OPENSSL_NO_SSL3
#endif
```

**Comment by sirblackheart** [comment]
I can confirm this regression when building with -`DUSE_SHARED_CURL=OFF`
> my /usr/include/openssl/opensslconf.h
Your shared lib headers should not matter when building with shared curl offf.
Replacing current thirdparty/curl with [upstream](https://github.com/curl/curl/) curl and changing the include dirs line to `set(CURL_INCLUDE_DIRS ${CURL_DIR}/include/curl) `seems to fix this.

**Comment by rcorre** [comment]
would it make sense for thirdparty/curl to be a submodule?

**Comment by dacap** [comment]
I'll be converting some third_party libs into submodules (zlib and libpng are the next ones). The only problem with libcurl is that the official git repository is too big, so I think I'll create a small mirror of it (only uncompressed .zip content)

**Comment by rcorre** [comment]
What about a shallow submodule?

`man git-submodule`:

```
--depth
           This option is valid for add and update commands. Create a shallow clone with a history truncated
           to the specified number of revisions. See git-clone(1)
```

**Comment by rcorre** [comment]
Unless you're just talking abut the size of the content at any given revision. In that case there's sparse clone, but I think each user would have to configure that themselves.
