### ISSUE TITLE
Feature Request: copy & paste selection in an array.

### ISSUE THREAD

**Issue by SleepyEleven** [aseprite/aseprite#1047]
The ability to select a group of pixels, copy them, and then paste them with a dialog box that lets you select how many copies to make, and what value you would like to offset the copies on the x and y axis could be pretty handy. Though there may already be another way to do this. Just a thought.

**Comment by dacap** [comment]
Hi @SleepyEleven, you might try to use a custom brush (Edit > New Brush menu, or `Ctrl+B`), select the group of pixels you want to copy, then use the line tool (`L` key), and draw a straight line (`Shift` locks the X/Y axis). Demo about custom brushes: http://imgur.com/2ke4Xgw

**Comment by SleepyEleven** [comment]
Ahh. I didn't realize the custom brush could be used in conjunction with line tool. Just didn't occur to me to try. Thank you sir.
