### ISSUE TITLE
Support Command Line Globbing of Input Files

### ISSUE THREAD

**Issue by JosephMichels** [aseprite/aseprite#1049]
On Windows (I'm not sure about Linux/Mac) the CLI doesn't support something like *.ase.

If I execute the following command:

`aseprite.exe -b *.ase --sheet-pack --sheet atlas-bestfit.png --list-tags --data atlas-bestfit.json`

I will get an error saying: `File not found: *.ase`

This is probably a low priority issue, as it can be worked around easily, but it would be a nice feature to have.

**Comment by sirblackheart** [comment]
Power Shell should support globbing, could you try if it works with that. No problems with globbing on linux for me.

**Comment by JosephMichels** [comment]
Yeah, I've looked into this a bit further and on Linux and Mac this is natively supported by the shell and the application doesn't have to do anything. 

On windows it appears you need to link to setargv.obj to get it handled automatically. [Source](https://msdn.microsoft.com/en-us/library/8bch7bkk(v=vs.140).aspx)

I did try it on powershell and still got the error, so I'm not sure if it does it automatically either.

**Comment by dacap** [comment]
Actually we are using `WinMain`, and `GetCommandLineW` in the Alleg4 back-end and `CommandLineToArgvW` in the Skia side. It looks like `setargv.obj` works for `main()` (and I suppose `-ENTRY:"mainCRTStartup"` linking flag). We could try to change the entry point to `wmain()` and linking to `wsetargv.obj` to fix this issue.

**Comment by sirblackheart** [comment]
@JosephMichels if you feel comfortable using a unix shell on windows, you could use something like [MSYS2 ](https://sourceforge.net/p/msys2/wiki/MSYS2%20installation/) as a workaround for now. Just tested it and it seems to work without problems.

**Comment by dacap** [comment]
I'll try to get a look at this issue for v1.2 (as I'm refactoring the CLI processing)
