### ISSUE TITLE
Exported spritesheet

### ISSUE THREAD

**Issue by AndyGFX** [aseprite/aseprite#1050]
Hi,
when is animation exported as imagesheet, where is any layer with color blend and alpha <255, then is blending not exported to image.

Andy

![2016-04-08](https://cloud.githubusercontent.com/assets/507698/14397341/1822c862-fddd-11e5-9a99-9055c86ceac9.png)

**Comment by dacap** [comment]
Hi @AndyGFX. I guess that you are using an Indexed image with blend modes (as the ACDSee quick view status bar shows that the png has 8bpp, it means it's indexed). You might try to use RGB color mode instead (Sprite > Color Mode > RGB). More info about color modes here: http://www.aseprite.org/docs/color/

**Comment by AndyGFX** [comment]
Oops, sorry. Yes, that is true.

AndyGFX.
