### ISSUE TITLE
Flickering display when moving the mouse

### ISSUE THREAD

**Issue by geckojsc** [aseprite/aseprite#1051]
Hey, I've been having an issue with occasional flickering/tearing/offsetting of the entire Aseprite window, which occurs when the mouse moves. 

I'm guessing it's something to do with redrawing every time something changes on screen, and perhaps it's the kind of thing that might be fixed if #960 is implemented? It seems to happen more often when moving the mouse over tools or menu items, I guess because that also forces a redraw.

Video to demonstrate:
https://www.youtube.com/watch?v=sikjPuJl5Tk

Anyway, I love this program, it's doing a lot of things right compared to others! Keep up the good work :D

**Comment by dacap** [comment]
Hi @geckojsc, it looks quite strange. I've never saw something similar. I see that you are using the compiled version, do you compile with the Allegro back-end or Skia? I see that you have a lot of applications open, something else is using DirectX? Have you tried to restart Windows and test this issue having only Aseprite open?

**Comment by geckojsc** [comment]
I rebooted and tried with just Aseprite open, and also tried the official build, but the flickering still occurs.
I'll try out Skia and see if that fixes it :)

**Comment by geckojsc** [comment]
Looks like Skia updated quite heavily since it was last used here. I tried rewriting some parts of SHE but I'm feeling a bit out of my depth because I've never used either of those libraries before. Is there a particular version/commit of Skia that you would recommend using, or should I persevere and submit a PR?

**Comment by geckojsc** [comment]
Update: I set Aseprite to use integrated graphics instead of the GPU in my NVIDIA control panel, and this seems to have fixed the problem. I guess it's some kind of one-off driver or hardware issue.

CPU usage is high (around 10%) as long as anything changes on-screen, including moving the mouse cursor, but other than that it's all good.

**Comment by dacap** [comment]
I recommend the chrome/m50 branch of Skia. Anyway it's good to know that there is an option in the Nvidia panel to fix the issue. If you want to give a try to the Skia port (compiling it or using the beta branch in the Steam client) you can leave the issue open, if you aren't going to try the Skia branch, you can close it (the issue can be opened in a future if it re-appears).
