### ISSUE TITLE
Unable to build on windows 10 and VS2013

### ISSUE THREAD

**Issue by AyphixLLC** [aseprite/aseprite#1054]
I have mostly got it compiling EXCEPT for png-static which fails with this error, I have done googling upon googling and haven't come up with a solution.

Edit: for an updated error message

```
  CMake Error at scripts/gensrc.cmake:68 (message):
    Failed to generate pnglibconf.tf5


  Building Custom Rule C:/Users/Jinmuu/aseprite/third_party/libpng/CMakeLists.txt
  CMake does not need to re-run because C:\Users\Jinmuu\aseprite\build\third_party\libpng\CMakeFiles\generate.stamp is up-to-date.
  Generating pnglibconf.c
  options.awk: bad line (10): com

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
```

**Comment by dacap** [comment]
I think you will need awk to compile libpng. You can use the [MozillaBuild](https://wiki.mozilla.org/MozillaBuild) package.

**Comment by AyphixLLC** [comment]
Strange... I still get the same issue. I've tried restarting and everything.

**Comment by yuigoto** [comment]
I tried compiling with Skia, using the latest source (using `git clone --recursive`), had this same problem.

Downloaded the latest "release" zip, compiled, everything went fine. I'll test all possibilities in here to see which step I did wrong. :<

**Comment by AyphixLLC** [comment]
@yuigoto That's exactly how I fixed the issue. I've just been waiting for the release Zips.

**Comment by dacap** [comment]
Contacted again about this issue, this might be related because the repo clones/checkouts (mainly the libpng checkout) are using a Windows-like (CRLF) End Of Line (EOL) and the .zip contains Unix-like (LF) EOL.

A possible option that you might try is disabling the automatic-CRLF conversion before cloning:

    git config core.autocrlf

And then start again:

    git clone --recursive https://github.com/aseprite/aseprite.git

**Comment by Lyutria** [comment]
I can confirm the above, this actually seems to be the issue.
Compiling on windows with vs2017 and awk from mozilla-build fails normally, switching autocrlf off works.

Another option is to get the full msys installation (I did from [msys2.org](http://www.msys2.org)) and use the awk executable from there, that seemed to work without changing the git config.

**Comment by Displee** [comment]
I had the same error on Ubuntu, the solution above also worked on Ubuntu.
