### ISSUE TITLE
Double-click on folder item should navigate to (open) it

### ISSUE THREAD

**Issue by bitinn** [aseprite/aseprite#1061]
On OS X, I only seem to be able to open them by pressing `return/enter`.

![screen shot 2016-04-13 at 2 20 51 pm](https://cloud.githubusercontent.com/assets/1484279/14484451/2c658dce-0183-11e6-9e44-45f4bf9fd146.png)

**Comment by dacap** [comment]
Hi @bitinn, It's already fixed on #1057, it will released this week (there are other crash reports I'd like to see if I can fix before the new version)

**Comment by dacap** [comment]
The fix is already available in v1.1.4.1 (on Steam, Gumroad, itch.io, and Humble Bundle)
