### ISSUE TITLE
Opening files in the steam version.

### ISSUE THREAD

**Issue by Nsheppard01** [aseprite/aseprite#1069]
I have Aesprite set as the default editor for most image formats, but this does not seem to work for the steam version. Even if I set the file association to the steam version of aseprite, it just launches aesprite without opening the file.

**Comment by dacap** [comment]
Hi @Nsheppard01, how did you associated other file formats to Aseprite? What operating system are you using (Win, OSX, Linux)?

**Comment by Nsheppard01** [comment]
I was using linux and I see what the problem was now. The file manager was trying to open it with the seam command to launch Aesprite. but if I set the actual aseprite binary installed in ~/.steam/steam/steamapps/common/Aseprite it works as intended.
