### ISSUE TITLE
Opening files as a new tab in existing aseprite session.

### ISSUE THREAD

**Issue by Nsheppard01** [aseprite/aseprite#1070]
Related to but separate from my last issue. If aseprite is set as the default file association, clicking on a new file on the desktop will open a completely new instance of aseprite. This is undesirable because aseprite has tab functionality. It's even worse when you have a multiple workspace setup and might forget that aseprite is already running. It would be nice if new instances of Aseprite checked to see if another instance already existed, and if so, created a new tab in that instance instead.

**Comment by dacap** [comment]
This issue is already solved from v1.1.4 (#477) for Windows and OS X. What operating system you are using (Win, OS X, Linux)?

**Comment by Nsheppard01** [comment]
Linux and windows 10. In both cases using the latest steam version.

**Comment by dacap** [comment]
I've just reopen #477 to add Linux support

**Comment by Nsheppard01** [comment]
I'm using the steam beta version on windows and linux, and I've still never
seen this work. Opening a file in Aseprite always opens a new instance. In
both cases I have the association set to the binary in steamapps.

**Comment by dacap** [comment]
@Nsheppard01 did you set the file association by hand on Windows? On Windows there are special registry directives to open files through DDE instead of the command line:
```
HKEY_CLASSES_ROOT\.ase
  (Default) = "AsepriteFile"

HKEY_CLASSES_ROOT\.aseprite
  (Default) = "AsepriteFile"

"HKEY_CLASSES_ROOT\AsepriteFile
  (Default) = "Aseprite Sprite"

HKEY_CLASSES_ROOT\AsepriteFile\DefaultIcon
   (Default) = "%INSTALLDIR%\\Aseprite.EXE,2"

HKEY_CLASSES_ROOT\AsepriteFile\shell\open\command
  (Default) = "\"%INSTALLDIR%\\Aseprite.EXE\""

HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec
  (Default) = "[open(\"%1\")]"

HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\application
  (Default) = "Aseprite"

HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\topic
  (Default) = "system"
```

**Comment by Nsheppard01** [comment]
I right click the file, select open with from the context menu, and then
browse to the aseprite binary, thus setting aseprite as the default
application for that particular format of image file. This is the way I
understand most users set file associations on windows.

**Comment by dacap** [comment]
The default association that the Windows Explorer does is to open files through the command line. This prevents using the same Aseprite instance to open the file.

The file association that the Aseprite installer and Aseprite on Steam create is through the special DDE mechanism to detect existent instances. (E.g. this is the way which Microsoft Office opens documents in the running instance of Word or Excel.)

So this issue is solved (on Windows) through the installation process.

**Comment by Nsheppard01** [comment]
I'm not sure how that's solved then if I've never been able to open a file
properly.

**Comment by dacap** [comment]
Are we talking about `.ase` files? Or are we talking about other type of files (e.g. `.png` files)? Because it only applies for `.ase` (or `.aseprite` files). You might try the following:

1. Open the registry editor and delete the `AsepriteFile` folder inside `HKEY_CLASSES_ROOT``
2. Reinstall latest Aseprite (v1.1.7) from the installer (or uninstall/reinstall it from Steam)
3. Try to double click a `.ase` or `.aseprite` file from Windows explorer.

**Comment by dacap** [comment]
If this doesn't work, please try to export the content of `AsepriteFile` folder in `HKEY_CLASSES_ROOT` using the registry editor and send me a copy of the `.reg` file at `support@aseprite.org`.

**Comment by Nsheppard01** [comment]
Oh, I'm talking about PNGs and JPEGs. Because of my workflow, I only use
one ASE at a time as a multi-layer workspace, and keep everything else as
PNGs. If I'm trying to open a bunch of new files from explorer, it's
usually a png.

You might consider this an edge case, but it seems kind of half assed to
have this functonality only work for ase. Couldn't new instances of
Aseprite check to see if another instance is already running, regardless of
how they were called?

**Comment by dacap** [comment]
You can configure `.png` and `.jpg` extensions in the `HKEY_CLASSES_ROOT` like the `.ase` extension, setting the `(Default)` value to `AsepriteFile`. Anyway I think that there are some options to solve this in future versions:

1. The installer could have more check-boxes to associate other files with Aseprite
2. The *Edit > Preferences* dialog could contain check-boxes to associate files with Aseprite

**Comment by Nsheppard01** [comment]
Would that prevent me from opening files in a normal photo viewer though? I
know in windows there is an option to right click on a picture and select
edit, to open it in paint. Is there a way to change that association?

**Comment by dacap** [comment]
You're right, I'll investigate if there is an easy option to add an "Open with Aseprite" option in other file types (png, jpg, etc.), in that way there is no need to lost the photo viewer association.

**Comment by bilgekaan** [comment]
+1

**Comment by zoeesilcock** [comment]
I ran into this issue with Unity after switching to Windows. Setting the registry key for .png as described [above](https://github.com/aseprite/aseprite/issues/1070#issuecomment-237045274) solves the problem when opening .png files from windows explorer. Then telling Unity to "Open by file extension" instead of specifying Aseprite directly makes it work when opening .png files from Unity.

**Comment by Gnumaru** [comment]
Please, albeit this being a closed issue, allow me to let this reference for future googlers. Although the registry entries provided above are conceptually correct, they are not in a correct registry file syntax.

You should save the text bellow in a .reg file an run it, and all your multiple instance problems will be solved. Beware to replace the exe path with your actual aseprite installation directory.
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.ase]
@="AsepriteFile"

[HKEY_CLASSES_ROOT\.aseprite]
@="AsepriteFile"

[HKEY_CLASSES_ROOT\AsepriteFile]
@="Aseprite Sprite"

[HKEY_CLASSES_ROOT\AsepriteFile\DefaultIcon]
@="C:\\Program Files (x86)\\steam\\steamapps\\common\\Aseprite\\aseprite.exe,2"

[HKEY_CLASSES_ROOT\AsepriteFile\shell\open\command]
@="\"C:\\Program Files (x86)\\steam\\steamapps\\common\\Aseprite\\aseprite.exe\""

[HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec]
@="[open(\"%1\")]"

[HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\application]
@="Aseprite"

[HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\topic]
@="system"
```

**Comment by xinyu217** [comment]
> Please, albeit this being a closed issue, allow me to let this reference for future googlers. Although the registry entries provided above are conceptually correct, they are not in a correct registry file syntax.
> 
> You should save the text bellow in a .reg file an run it, and all your multiple instance problems will be solved. Beware to replace the exe path with your actual aseprite installation directory.
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_CLASSES_ROOT\.ase]
> @="AsepriteFile"
> 
> [HKEY_CLASSES_ROOT\.aseprite]
> @="AsepriteFile"
> 
> [HKEY_CLASSES_ROOT\AsepriteFile]
> @="Aseprite Sprite"
> 
> [HKEY_CLASSES_ROOT\AsepriteFile\DefaultIcon]
> @="C:\\Program Files (x86)\\steam\\steamapps\\common\\Aseprite\\aseprite.exe,2"
> 
> [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\command]
> @="\"C:\\Program Files (x86)\\steam\\steamapps\\common\\Aseprite\\aseprite.exe\""
> 
> [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec]
> @="[open(\"%1\")]"
> 
> [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\application]
> @="Aseprite"
> 
> [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\topic]
> @="system"
> ```

Solved my issue! Thank you!

**Comment by MattTheBanana** [comment]
> Please, albeit this being a closed issue, allow me to let this reference for future googlers. Although the registry entries provided above are conceptually correct, they are not in a correct registry file syntax.
> 
> You should save the text bellow in a .reg file an run it, and all your multiple instance problems will be solved. Beware to replace the exe path with your actual aseprite installation directory.
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_CLASSES_ROOT\.ase]
> @="AsepriteFile"
> 
> [HKEY_CLASSES_ROOT\.aseprite]
> @="AsepriteFile"
> 
> [HKEY_CLASSES_ROOT\AsepriteFile]
> @="Aseprite Sprite"
> 
> [HKEY_CLASSES_ROOT\AsepriteFile\DefaultIcon]
> @="C:\\Program Files (x86)\\steam\\steamapps\\common\\Aseprite\\aseprite.exe,2"
> 
> [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\command]
> @="\"C:\\Program Files (x86)\\steam\\steamapps\\common\\Aseprite\\aseprite.exe\""
> 
> [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec]
> @="[open(\"%1\")]"
> 
> [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\application]
> @="Aseprite"
> 
> [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\topic]
> @="system"
> ```

I am not a very advanced Windows user, could you give a more simple explanation of how to do this?

**Comment by Drakeyn** [comment]
> > ```
> > Windows Registry Editor Version 5.00
> > 
> > [HKEY_CLASSES_ROOT\.ase]
> > @="AsepriteFile"
> > 
> > [HKEY_CLASSES_ROOT\.aseprite]
> > @="AsepriteFile"
> > 
> > [HKEY_CLASSES_ROOT\AsepriteFile]
> > @="Aseprite Sprite"
> > 
> > [HKEY_CLASSES_ROOT\AsepriteFile\DefaultIcon]
> > @="C:\\Program Files (x86)\\steam\\steamapps\\common\\Aseprite\\aseprite.exe,2"
> > 
> > [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\command]
> > @="\"C:\\Program Files (x86)\\steam\\steamapps\\common\\Aseprite\\aseprite.exe\""
> > 
> > [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec]
> > @="[open(\"%1\")]"
> > 
> > [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\application]
> > @="Aseprite"
> > 
> > [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\topic]
> > @="system"
> > ```
> 
> I am not a very advanced Windows user, could you give a more simple explanation of how to do this?

Create a text file, copy-paste all that into it, save, change the file extension to .reg (You can do so by simply renaming the file. You may need to make sure the option View -> File Extensions is enabled)

**Comment by MattTheBanana** [comment]
> > > ```
> > > Windows Registry Editor Version 5.00
> > > 
> > > [HKEY_CLASSES_ROOT\.ase]
> > > @="AsepriteFile"
> > > 
> > > [HKEY_CLASSES_ROOT\.aseprite]
> > > @="AsepriteFile"
> > > 
> > > [HKEY_CLASSES_ROOT\AsepriteFile]
> > > @="Aseprite Sprite"
> > > 
> > > [HKEY_CLASSES_ROOT\AsepriteFile\DefaultIcon]
> > > @="C:\\Program Files (x86)\\steam\\steamapps\\common\\Aseprite\\aseprite.exe,2"
> > > 
> > > [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\command]
> > > @="\"C:\\Program Files (x86)\\steam\\steamapps\\common\\Aseprite\\aseprite.exe\""
> > > 
> > > [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec]
> > > @="[open(\"%1\")]"
> > > 
> > > [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\application]
> > > @="Aseprite"
> > > 
> > > [HKEY_CLASSES_ROOT\AsepriteFile\shell\open\ddeexec\topic]
> > > @="system"
> > > ```
> > 
> > 
> > I am not a very advanced Windows user, could you give a more simple explanation of how to do this?
> 
> Create a text file, copy-paste all that into it, save, change the file extension to .reg (You can do so by simply renaming the file. You may need to make sure the option View -> File Extensions is enabled), then double click the file to run it. You will then get a prompt asking whether you want to allow it to modify your registry.

I did this. My .pngs and jpgs still open in separate instances of Aseprite.

**Comment by JForceAdmin** [comment]
With Photoshop I could easily make my png's open in a new tab with the Windows "open with" option and then checking the "always open with this app" box. 

Doesn't work with Asesprite. I really want to switch to Asesprite for my pixel work but this and a couple other things are pretty annoying. Could this please get added?

**Comment by Drakeyn** [comment]
> With Photoshop I can easily make my png's open in a new tab with the Windows "open with" option and then checking the "always open with this app" box.
> 
> Doesn't work with Asesprite. I really want to switch to Asesprite for my pixel work but this and a couple other things are pretty annoying. Could this please get added?

I succeeded in making it function like that with the registry modifications listed above, which works as a sort-of workaround, though it still has the issue that opening new files does not focus aseprite - it opens a new tab in aseprite, but does not focus the aseprite window, which can be confusing at times. A proper implementation would be really nice though.

**Comment by JForceAdmin** [comment]
> > With Photoshop I can easily make my png's open in a new tab with the Windows "open with" option and then checking the "always open with this app" box.
> > Doesn't work with Asesprite. I really want to switch to Asesprite for my pixel work but this and a couple other things are pretty annoying. Could this please get added?
> 
> I succeeded in making it function like that with the registry modifications listed above, which works as a sort-of workaround, though it still has the issue that opening new files does not focus aseprite - it opens a new tab in aseprite, but does not focus the aseprite window, which can be confusing at times. A proper implementation would be really nice though.

I tried this for pngs and it didn't work. I did add the png extension to the .reg file. It's a pretty annoying issue when before I could just double-click a png from the Unity editor and have it open in a new Photoshop tab.

**Comment by dacap** [comment]
We'll try to fix this for a future version of Aseprite. It's a shame that Microsoft made this so hard to achieve in a regular basis for apps (using "registry tricks") while other platforms (macOS) made it almost something automatically handled.

**Comment by ThomasMoonKang** [comment]
The .aseprite files open properly if Aseprite is not installed in the "Program Files" folder. "Program Files (x86)" works fine. However, double clicking a file still takes an extra 30 seconds to open Aseprite, compared to double clicking Aseprite.exe itself
