### ISSUE TITLE
Massiv struggles with compile...

### ISSUE THREAD

**Issue by Senpai-Artorias** [aseprite/aseprite#1071]
Well First i preshate and love aseprite and when i had the money right now i would buy it but that isnt possibel currently. So i tryd to Compile it myself and sitting now over 3 Hours to get it to work :/
I understand things better with Screenshots or videos so i fight my way Throught the how to install instructions.

Right now i stuck on this error "CMake Error: Could not create named generator Visual" First Thing i noticed myself is that it only calls Visual but i wrote the command like this , "cmake -G Visual Studio 14 2015 Win64".
After a Hour Googel for this new issue i have i cant find any useful answers and onyl more confused as before after reading all this stuff. I Hope anyone can help me with it.

PS : Using Win7

Greetings and Nice day to all

**Comment by sirblackheart** [comment]
@Senpai-Artorias Maybe try cmakes gui if you have problems on the command line?

**Comment by Senpai-Artorias** [comment]
Thanks for the answer sirblackheart

Well i already Tryd that too but when i use the Gui i get This Error
[http://i.imgur.com/TaWkLYx.png](url)

I feel really Dumb because i never had this kind of massiv problems with something . -.

**Comment by dacap** [comment]
Hi @Senpai-Artorias, I think you are running:

    cmake -G Visual Studio 14 2015 Win64

When you should be running:

    cmake -G "Visual Studio 14 2015 Win64"

Anyway I recommend you "nmake", as you will not need to open Visual Studio. E.g.

    cmake -G "NMake Makefiles"

And then you can compile Aseprite using:

    nmake aseprite

**Comment by Senpai-Artorias** [comment]
Thanks for ur response David i will try it out give me some minutes . -.

**Comment by Senpai-Artorias** [comment]
@dacap Well for no reason cmd says now "The command "cmake" is either misspelled or
could not be found."
When i try to enter the Generate command

. _. now im frustrated

**Comment by dacap** [comment]
Do you have [cmake](http://cmake.org) installed?

**Comment by Senpai-Artorias** [comment]
@dacap yes i installed the windows install from the cmake.org site its installed in C:\cmake folder

**Comment by dacap** [comment]
I think you don't have cmake in the PATH environment variable. You can execute this:

    set PATH=C:\cmake\bin;%PATH%

And then run `cmake` to check that the command is available.

Anyway, before running cmake with all parameters, you must be sure that you are running the Visual Studio command line tools, you can execute:

    call "%VS140COMNTOOLS%\vsvars32.bat"

So you will have the Visual Studio compiler (and `nmake`) available in the command line. After all this, try again the cmake command with the parameters.

**Comment by Senpai-Artorias** [comment]
Well @dacap i run both commands and rerun the cmake with the parameters and now i stuck directly to this error.

C:\aseprite\build>cmake -G "NMake Makefiles"
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:31 (project):
  The CMAKE_C_COMPILER:

Greetings

**Comment by dacap** [comment]
Two things: 1) You have to execute `cmake -G "NMake Makefiles" ..` (the `..` is important as it indicates the directory where the source code is. 2) Please execute `cl` (just that and press enter) to know if the C compiler is in the command line.

If you have executed

    call "%VS140COMNTOOLS%\vsvars32.bat"

And the compiler (`cl`) is not in the command line, it's probable that you don't have Visual Studio 2015 installed.

Anyway I'll stop this issue here, as basically the source code is available for developers.
