### ISSUE TITLE
Allowing to export single or selected frames as png

### ISSUE THREAD

**Issue by undefdev** [aseprite/aseprite#1080]
When I save as a png I usually get this prompt:

![enhancement](https://cloud.githubusercontent.com/assets/13840966/14708559/568e0fe6-07fe-11e6-826f-8a76aecd388c.png)

Sometimes I only need frame 42, or frames tagged "jump", or an arbitrary numerical frame range.
This results in me having to export a lot of pngs only to delete most of them.

It would be nice to have a third button "Select Range" or something like that which would open another context window where you could either select a tag, or a starting and ending frame.
In case only one frame is selected that way (e.g. start: 1 end: 1) the image shouldn't be saved with the numerical suffix, otherwise the notice could be shown once more to make sure the user sees how many frames he's exporting, preventing possible accidental error.

**Comment by hepari** [comment]
I would like to suggest the following: 
If you check a **'Include Tags into file name'** option in the save dialogue, magic happens:

Frames are saved as **"Filename-Frametag-Number.png"**

Example:
![2016051300001](https://cloud.githubusercontent.com/assets/10383640/15232177/c1107faa-189f-11e6-9aea-7270f7b0b08e.png)

If you have these frametags, and you set the filename as 'Monster', You would get 
**"Monster-Idle-01.png", "Monster-Idle-02.png", "Monster-Idle-03.png"...
"Monster-AttackA-01.png", "Monster-AttackA-02.png", "Monster-AttackA-01.png"...**

This would make exporting frames really a lot easier.

**Comment by dacap** [comment]
Hi @hepari, actually that can be done but using the command line interface: http://www.aseprite.org/docs/cli/#filename-format

**Comment by hepari** [comment]
Oh thanks @dacap, but I have been trying using CLI with no luck so far. Nothing ever happens! The cli just runs without exporting anything.

This is the last code I've written up.

@set ASEPRITE="D:\Games\Steam\steamapps\common\Aseprite\aseprite.exe"
%ASEPRITE% -b EyeballB1.ase --save-as \output0\frame01.png
%ASEPRITE% -b --frame-tag "Idle" EyeballB1.ase --save-as EyeballB1-Idle01.png
%ASEPRITE% -b --frame-tag "AttackA" EyeballB1.ase --save-as EyeballB1-AttackA01.png

Could you look into this and see what I may be doing wrong? I know you have better things to do than babysit me, but I would appreciate your help very much.

**Comment by dacap** [comment]
Can you try:
```
%ASEPRITE% -b EyeballB1.ase --save-as output0\frame01.png
%ASEPRITE% -b EyeballB1.ase --filename-format "{title}-{tag}{tagframe01}.{extension}" --save-as EyeballB1.png
```

**Comment by hepari** [comment]
@dacap It worked! Thank you so much! I was about to export and rename them all by hand... 
![2016051300002](https://cloud.githubusercontent.com/assets/10383640/15232766/afb9f8b8-18a3-11e6-946b-7b2a964a6f53.png)

**Comment by dacap** [comment]
I'll be seeing this issue soon, I think some options like:

1. All frames
1. Selected frames
1. Active frame
1. Frame tag

**Comment by dacap** [comment]
The only problem I see with this issue is that there will be several alternatives (even more with the next v1.2-beta2 that will allow selection of non-adjacent frames), some examples:

1. Save all frames with names `filename1.png`, `filename2.png`, etc.
1. Save selected frames or frame tag with `filename1.png`, `filename2.png`, etc. or with the specific number (e.g. if we select frame 3, 6, and 9, then we would like to save `filename3.png`, `filename6.png`, `filename9.png`, instead of `filename1.png`, `filename2.png`, `filename3.png`).
1. Active frame should be saved with the specific given filename (or maybe we want to export just the current frame without worrying about the active frame number). So if we are in frame 3 and press "save active frame" it just update the `filename3.png`, and if we are in frame 5, it updates `filename5.png`, etc.

**Comment by dacap** [comment]
![save-options](https://cloud.githubusercontent.com/assets/39654/18605766/e5f00530-7c71-11e6-9f8c-674819537341.gif)

**Comment by dacap** [comment]
This will be available in the next v1.2-beta2

**Comment by Dairnon** [comment]
Has this been added yet? I'm on the newest version and don't see it. And I believe were on 1.2-beta9 or something now

**Comment by KasumiArai** [comment]
Yes, it's in save copy as.
![saveselectedframes](https://cloud.githubusercontent.com/assets/8582123/26542753/19b99c80-4429-11e7-80de-ead4e300bf46.gif)

**Comment by Dairnon** [comment]
It be nice to be able to export "all" tags so that it exports all tag related stuff separately.

**Comment by dacap** [comment]
@Dairnon actually that's possible [using the CLI](https://www.aseprite.org/docs/cli/#split-tags):

    aseprite.exe -b animations.ase --save-as animation-{tag}.gif
