### ISSUE TITLE
Can't assign "+"-Key as hotkey.

### ISSUE THREAD

**Issue by API-Beast** [aseprite/aseprite#1083]
- Edit->Keyboard Shortcuts
- Try to add or change the hotkey for any action to "+".
- Confirming the new hotkey by pressing "OK" won't actually do anything.

Using Windows 8.1, tested with both German and English keyboard layout.

Only a single "+" is affected, assigning it with a modifier like "Ctrl++" works.

**Comment by dacap** [comment]
Related to #139
