### ISSUE TITLE
CMake Big Endian Test fail on Windows

### ISSUE THREAD

**Issue by sarcasmloading** [aseprite/aseprite#1086]
Specs:
Windows 10 Pro 64bit
VS 2015 x64 (installed: common tools for visual c++ 2015 and windows 10 sdk)
CMake 3.5.2
The C/C++ compiler MSVC version is MSVC 19.0.23918.0
Compiling using the Allegro backend, because Skia is hell

I'm trying to compile Aseprite 1.1.4.1 on Windows, and I get this:
`
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/TestBigEndian.cmake:51 (message):
  no suitable type found
`

I've tried the GUI (admin and no admin), command prompt, VS Dev Command Prompt (vs2015), all to no avail.

I've googled it so many times and all of the answers I've found just say "oh, just empty the build dir". (I've done that every single time)

**Comment by dacap** [comment]
cc @winterheart

**Comment by winterheart** [comment]
Hello, can you please post CMakeError.log and CMakeOutput.log from BUILDDIR/CMakeFiles?

**Comment by sarcasmloading** [comment]
Yep.
CMakeError.log: http://pastebin.com/raw/wRvebWCD
CMakeOutput.log: http://pastebin.com/raw/vu2kLnbw

**Comment by winterheart** [comment]
OK, I think I found what's wrong. Unfortunately, I don't have full Windows build environment, @sarcasmloading, can you check it for me? Try to remove from 
https://github.com/aseprite/aseprite/blob/master/src/CMakeLists.txt#L33 "/SUBSYSTEM:WINDOWS,5.01" substring. It should look like:

```
  if (CMAKE_CL_64)
    # 64 bits
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MACHINE:X64")
  else()
    # Add support for Windows XP with 5.01 subsystem
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MACHINE:X86")
  endif()
```

@dacap, is Aseprite still supports Windows XP? If yes, then we need move all compilation checks from src/base/CMakeLists.txt to root CMakeLists.txt.

**Comment by sarcasmloading** [comment]
No, that didn't work, sadly. I'm running Windows 10.

**Comment by winterheart** [comment]
Did you cleared cache? Even in Win64 profile still no works?

**Comment by sarcasmloading** [comment]
Yes, I cleared the cache.

**Comment by sarcasmloading** [comment]
This must be a problem in (a) My Windows installation or (b) Aseprite 1.1.4.1. I compiled Aseprite 1.1.3 before (with a different Windows installation) successfully.

**Comment by sarcasmloading** [comment]
Maybe there is a way of disabling the big endian test?

**Comment by dacap** [comment]
@winterheart Yes, Aseprite supports WinXP (there are still a couple of WinXP users out there, and it wasn't quite easy to do it, I'm using [a modified Skia branch just to compile everything statically and support WinXP](https://github.com/aseprite/skia/commit/c86078f5a878507ea7014b74acb369b387480c70)).

I'll take a look to this issue, if I don't find a quick solution, I'll rollback the change.

**Comment by dacap** [comment]
I'm using cmake 3.5.0, I'll update to cmake 3.5.2 to see if I can reproduce this issue.

**Comment by winterheart** [comment]
Well, I got solution - to move headers and endianess checks to parent cmakelists. I deployed win 10 with vs 2015. Give me a couple hours, I'll send pr.

**Comment by sarcasmloading** [comment]
Thanks so much for your effort put into fixing this!

**Comment by dacap** [comment]
@winterheart I don't think that the test should be moved, I'll try to move the subsystem flag to the Aseprite target only, and that should fix the issue (at least that is what I think)

**Comment by dacap** [comment]
It's strange because I cannot reproduce the issue.

@sarcasmloading: did you try to create a completely new `build'  folder (removing all the content it contain before, not just the cache)? I'm asking this because on [this comment](https://github.com/aseprite/aseprite/issues/1086#issuecomment-214213741) you said that @winterheart solution didn't work, but it looks like the only cause this error might happen. :/

**Comment by sarcasmloading** [comment]
Yes, I can assure you I deleted all the contents of the /build/ folder. If
we can't find a solution I'll probably reinstall Windows (I was planning to
anyway).

**Comment by dacap** [comment]
> we can't find a solution I'll probably reinstall Windows

:smile: I don't think that would be necessary (at least for this issue)

**Comment by dacap** [comment]
I wasn't able to reproduce the issue (not even with x86 and x64 toolchains). I'll continue with other issues and leave this.

@winterheart if you can reproduce the issue, send a PR if you can fix it, but if you aren't able to reproduce the issue, I'm not sure if we should do a change. what do you think?

**Comment by dacap** [comment]
Meanwhile, @sarcasmloading, you can try to completely remove these lines:
```

  if (CMAKE_CL_64)
    # 64 bits
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MACHINE:X64")
  else()
    # Add support for Windows XP with 5.01 subsystem
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MACHINE:X86 /SUBSYSTEM:WINDOWS,5.01")
  endif()
```
From `src\CMakeLists.txt`, start from a clean `build`, and send us the logs files.

**Comment by winterheart** [comment]
@dacap, yes, it reproducible in Windows 7 and VS 2008 / VS 2015 and Windows 10 VS 2015 but **only on 32 bit** profile (Visual Studio 20XX). Win64 profile (Visual Studio 20XX Win64) runs fine. Maybe there also locale thing happen - my boxes runs Windows with Russian locale.

It seems, statement
```
  if (CMAKE_CL_64)
    # 64 bits
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MACHINE:X64")
  else()
    # Add support for Windows XP with 5.01 subsystem
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MACHINE:X86 /SUBSYSTEM:WINDOWS,5.01")
  endif()
```
is rendurant. I don't go deeper, but CMake (at least 3.5) seems is smart enough to add "/MACHINE:(X64|X86)" to linker flags themself. I only concern if we remove these "if() else()", it would break Windows XP compilation.

**Comment by dacap** [comment]
I add the SUBSYSTEM manually in my building scripts, so it's not needed in the CMakeLists.txt definitions. We can remove those lines. (Also VS2015 is the supported platform to compile Aseprite, and it doesn't run on WinXP, so I don't think that someone compiling Aseprite would need WinXP support anyway.)

**Comment by winterheart** [comment]
OK, I'll send PR with deletions.

**Comment by sarcasmloading** [comment]
Well, I thought that because apparently this has not happened to anyone
else, it might be a problem with my install. I'll try compiling 1.1.3

**Comment by dacap** [comment]
@sarcasmloading please try the master branch, because I've merged a fix from @winterheart for this issue

**Comment by sarcasmloading** [comment]
Alright, compiling with master branch.
Yes! It worked. It gave me a DirectX error but (#1026) will fix
Thanks for your help!
