### ISSUE TITLE
Help with compilation

### ISSUE THREAD

**Issue by mpolynskyi** [aseprite/aseprite#1087]
Can someone help me with compilation on windows 10? I followed this [https://github.com/aseprite/aseprite/blob/master/INSTALL.md](url) instructions, but ineffectually.
I using Windows 10, VS2015 Community Edition and Windows 10 SDK

**Here my steps:** http://i7.5cm.ru/i/3Skl.gif

**Here the output of CMake 3.5.2 GUI:**
The C compiler identification is MSVC 19.0.23506.0
The CXX compiler identification is MSVC 19.0.23506.0
Check for working C compiler using: Visual Studio 14 2015 Win64
Check for working C compiler using: Visual Studio 14 2015 Win64 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 14 2015 Win64
Check for working CXX compiler using: Visual Studio 14 2015 Win64 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
C:/aseprite/third_party/zlibC:/aseprite/build/third_party/zlib
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
Looking for include file stdint.h
Looking for include file stdint.h - found
Looking for include file stdint.h
Looking for include file stdint.h - found
Looking for include file dlfcn.h
Looking for include file dlfcn.h - not found
Looking for sched_yield
Looking for sched_yield - not found
Check if the system is big endian
Searching 16 bit integer
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of unsigned short
Check size of unsigned short - done
Using unsigned short
Check if the system is big endian - little endian
CMake Error at src/CMakeLists.txt:101 (add_subdirectory):
  The source directory

    C:/aseprite/src/flic

  does not contain a CMakeLists.txt file.

Could NOT find DXGUID (missing:  DXGUID_LIBRARY) 
CMake Error at src/she/CMakeLists.txt:16 (message):
  DirectX required for Windows port.  You might need to add DirectX include
  and lib directories to your INCLUDE and LIB environment variables.

Configuring incomplete, errors occurred!
See also "C:/aseprite/build/CMakeFiles/CMakeOutput.log".
See also "C:/aseprite/build/CMakeFiles/CMakeError.log".

What I did wrong and how to finish compilation?

**Comment by dacap** [comment]
Hi @mpolynskyi, as a first step, I think you didn't clone the repository recursively, see [this](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#get-the-source-code):

    git clone --recursive https://github.com/aseprite/aseprite.git

After that, I think you will have this same issue #1026, check the solution there and tell me if that works.

**Comment by mpolynskyi** [comment]
Big thanks for answer!
So I cloned project recursive, installed DirectX SDK and generated again with CMake-GUI
Here output: [google document link](https://docs.google.com/document/d/1UeJ-oiWfar_lJn70cUSpIYJgdWck-VlzLMp04gbzwIo/edit?usp=sharing)
After generating I opened aseprite.sln in build folder with Visual Studio, but in Solution Explorer everething is red, is it ok? [screenshot](http://i7.5cm.ru/i/NnDp.png)
Then I tried to build it, but after some time got error [screenshot](http://i7.5cm.ru/i/23kN.png) "can't open file libcurl.lib" How can I fix it?

**Comment by dacap** [comment]
You're welcome. Now you can try the solution in #788

**Comment by mpolynskyi** [comment]
Oh gosh, now I have "unresolved external symbol" error in alleg.lib [screenshot](http://i7.5cm.ru/i/aS1G.png) Is it some known issue too?

**Comment by sirblackheart** [comment]
Right click the aseprite project and select properties then add the dxguid.lib to the linker.
> Additionaly you probably have to add dxguid.lib in Linker -> Input -> Additional Dependencies to the aseprite project.

**Comment by mpolynskyi** [comment]
I can't find any "Linker" in properties. Here [screenshot ](http://i7.5cm.ru/i/Mzj0.gif)

**Comment by sirblackheart** [comment]
That is rather strange any project under the solution should have a full properties windows like this
![screenshot](https://cloud.githubusercontent.com/assets/1131371/14801031/7b8e2dda-0b46-11e6-91b0-b4b12ecec6a4.PNG)

**Comment by sarcasmloading** [comment]
Solution 'Aseprite' > aseprite > Properties > Linker > Input > Additional Dependencies (open dropdown) > Edit > Add dxguid.lib
That's my solution

**Comment by mpolynskyi** [comment]
Thanks, the problem was in english version of Visual studio while I have not english Windows 10. Also need to reinstall Windows 10 SDK standalone after installing visual studio. All builded good. Thanks for your help. I can write my all steps for build it on windows 10 as tutorial if need.
