### ISSUE TITLE
Help with compilation on OS X

### ISSUE THREAD

**Issue by zwik** [aseprite/aseprite#1089]
Greetings,

I read the install.md file but I'm getting compilation errors. When on master I get errors when running `cmake -G Ninja ..`

The error I get is:

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> SKIA_CONFIG_INCLUDE_DIR
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_CORE_INCLUDE_DIR
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_CORE_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_EFFECTS_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_IMAGES_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_OPTS_AVX2_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_OPTS_AVX_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_OPTS_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_OPTS_SSE41_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_OPTS_SSE42_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_OPTS_SSSE3_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_PORTS_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_SFNT_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_UTILS_INCLUDE_DIR
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
>    used as include directory in directory /Users/zwik/Documents/code/aseprite/src/she
> SKIA_UTILS_LIBRARY
>     linked by target "she" in directory /Users/zwik/Documents/code/aseprite/src/she
> 
> -- Configuring incomplete, errors occurred!

Even when adding the following flags or turning SKIA backend off I get the same error:
`cmake -G Ninja .. -DUSE_SKIA_ALLEG4=OFF -DUSE_SKIA_BACKEND=ON -DSKIA_DIR=/Users/zwik/Documents/Code/skia -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -DWITH_HarfBuzz=OFF`

When I branch the v1.1.4.1 tag I am able to generate the make/build files. However when I run Ninja I get the following compilation error:
```
Ninja
[148/1116] Building C object src/allegro/CMakeFiles/allegro.dir/src/poly3d.c.o
../src/allegro/src/poly3d.c:974:24: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
            width = -1 << 16;
                    ~~ ^
1 warning generated.
[190/1116] Building C object src/allegro/CMakeFiles/allegro.dir/src/macosx/drivers.m.o
FAILED: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DALLEGRO4_WITH_EXTRA_CURSORS -DALLEGRO4_WITH_RESIZE_PATCH -DALLEGRO_STATICLINK -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUSE_ALLEG4_BACKEND -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/loadpng -I../third_party/curl/include -I../third_party/simpleini -I../src/allegro/include -Iinclude -I../src/. -I../src/.. -I../src/../third_party -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -DALLEGRO_SRC -MMD -MT src/allegro/CMakeFiles/allegro.dir/src/macosx/drivers.m.o -MF src/allegro/CMakeFiles/allegro.dir/src/macosx/drivers.m.o.d -o src/allegro/CMakeFiles/allegro.dir/src/macosx/drivers.m.o   -c ../src/allegro/src/macosx/drivers.m
In file included from ../src/allegro/src/macosx/drivers.m:21:
../src/allegro/include/allegro/platform/aintosx.h:87:25: error: cannot find interface declaration for 'NSQuickDrawView', superclass of 'AllegroView'
@interface AllegroView: NSQuickDrawView
~~~~~~~~~~~~~~~~~~~~~~  ^
../src/allegro/include/allegro/platform/aintosx.h:178:8: error: unknown type name 'CGDirectPaletteRef'
AL_VAR(CGDirectPaletteRef, osx_palette);
       ^
2 errors generated.
[190/1116] Building C object src/allegro/CMakeFiles/allegro.dir/src/macosx/hidman.m.o
FAILED: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DALLEGRO4_WITH_EXTRA_CURSORS -DALLEGRO4_WITH_RESIZE_PATCH -DALLEGRO_STATICLINK -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUSE_ALLEG4_BACKEND -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/loadpng -I../third_party/curl/include -I../third_party/simpleini -I../src/allegro/include -Iinclude -I../src/. -I../src/.. -I../src/../third_party -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -DALLEGRO_SRC -MMD -MT src/allegro/CMakeFiles/allegro.dir/src/macosx/hidman.m.o -MF src/allegro/CMakeFiles/allegro.dir/src/macosx/hidman.m.o.d -o src/allegro/CMakeFiles/allegro.dir/src/macosx/hidman.m.o   -c ../src/allegro/src/macosx/hidman.m
In file included from ../src/allegro/src/macosx/hidman.m:21:
../src/allegro/include/allegro/platform/aintosx.h:87:25: error: cannot find interface declaration for 'NSQuickDrawView', superclass of 'AllegroView'
@interface AllegroView: NSQuickDrawView
~~~~~~~~~~~~~~~~~~~~~~  ^
../src/allegro/include/allegro/platform/aintosx.h:178:8: error: unknown type name 'CGDirectPaletteRef'
AL_VAR(CGDirectPaletteRef, osx_palette);
       ^
2 errors generated.
[190/1116] Building C object src/allegro/CMakeFiles/allegro.dir/src/macosx/keybd.m.o
FAILED: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DALLEGRO4_WITH_EXTRA_CURSORS -DALLEGRO4_WITH_RESIZE_PATCH -DALLEGRO_STATICLINK -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUSE_ALLEG4_BACKEND -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/loadpng -I../third_party/curl/include -I../third_party/simpleini -I../src/allegro/include -Iinclude -I../src/. -I../src/.. -I../src/../third_party -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -DALLEGRO_SRC -MMD -MT src/allegro/CMakeFiles/allegro.dir/src/macosx/keybd.m.o -MF src/allegro/CMakeFiles/allegro.dir/src/macosx/keybd.m.o.d -o src/allegro/CMakeFiles/allegro.dir/src/macosx/keybd.m.o   -c ../src/allegro/src/macosx/keybd.m
In file included from ../src/allegro/src/macosx/keybd.m:23:
../src/allegro/include/allegro/platform/aintosx.h:87:25: error: cannot find interface declaration for 'NSQuickDrawView', superclass of 'AllegroView'
@interface AllegroView: NSQuickDrawView
~~~~~~~~~~~~~~~~~~~~~~  ^
../src/allegro/include/allegro/platform/aintosx.h:178:8: error: unknown type name 'CGDirectPaletteRef'
AL_VAR(CGDirectPaletteRef, osx_palette);
       ^
../src/allegro/src/macosx/keybd.m:99:64: warning: 'lossyCString' is deprecated: first deprecated in OS X 10.4 [-Wdeprecated-declarations]
   const char character = [[event charactersIgnoringModifiers] lossyCString][0];
                                                               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:463:1: note: 'lossyCString' has been explicitly marked deprecated here
- (nullable const char *)lossyCString NS_RETURNS_INNER_POINTER NS_DEPRECATED(10_0, 10_4, 2_0, 2_0);
^
1 warning and 2 errors generated.
ninja: build stopped: subcommand failed.
```

Can somebody please help me? I'm using the following:
OS X 10.11.4
CMake 3.5.2
Ninja 1.6.0
XCode 7.3 and the command line tools

I also have the Skia library compiled somewhere but I'm confused how to use/add it...

Thanks!

**Comment by OrenjiAkira** [comment]
I get a similar error, also following every instruction in the INSTALL.md file. CMake cannot find Skia when building, despite it being there, compiled with gpu=0 and everything. Might it have something to do with properly reading or setting the SKIA_DIR argument for CMake? I also couldn't find where that argument is used in the CMakeLists.txt file in order to debug the error.

**Comment by dacap** [comment]
Hi @zwik and @OrenjiAkira, seeing this I've detected an error in `INSTALL.md`, the argument isn't `USE_SKIA_ALLEG4`, it's `USE_ALLEG4_BACKEND`. I've updated the instructions in 7c9b9eacea733ea79458937cab5a9e579d5b3cfd

I hope it helps

**Comment by tony** [comment]
@dacap I will follow up with a PR clarifying OS X instructions (https://github.com/aseprite/aseprite/issues/1081#issuecomment-214025653)

**Comment by zwik** [comment]
Where exactly do I pass these variables (-DUSE_ALLEG4_BACKEND=OFF, -DUSE_SKIA_BACKEND=ON, and -DSKIA_DIR=)? Do I pass these while generating the make files or when you start making/compiling the project and add them to the other list of parameters together with the CMAKE_OSX_ARCHITECTURES etc parameters?

**Comment by tony** [comment]
zwik:

```
git clone --recursive https://github.com/aseprite/aseprite.git
mkdir build
cd build
```

With Ninja:

```
cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64"  -DUSE_ALLEG4_BACKEND=OFF -DUSE_SKIA_BACKEND=ON -DSKIA_DIR=PATH/TO/SKIA -GNinja \
-D "CMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.7" \
-D "CMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk" \
-D "WITH_HarfBuzz:BOOL=OFF" ..

ninja
```

with normal make

```
cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64"  -DUSE_ALLEG4_BACKEND=OFF -DUSE_SKIA_BACKEND=ON -DSKIA_DIR=PATH/TO/SKIA \
-D "CMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.7" \
-D "CMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk" \
-D "WITH_HarfBuzz:BOOL=OFF" ..

make
```

run

`bin/aseprite`

**Comment by zwik** [comment]
Okay, so to answer my question, you just pass all params at once. Thanks!

I will try later tonight if it works out for me :) .

**Comment by dvlpstrcrispin** [comment]
I'm trying to run Tony's ninja build, but I'm getting the 'linked by target "she" in directory' error that zwik is. My shell history output is [here](https://gist.github.com/dvlpstrcrispin/615529faf53509f547dfd2793f52dbb0) (it's a bit verbose but I'm not sure what's needed and what isin't).
I installed Skia by 
```bash
git clone 'https://chromium.googlesource.com/chromium/tools/depot_tools.git'
export PATH="${PWD}/depot_tools:${PATH}"
git clone 'https://skia.googlesource.com/skia'
cd skia
GYP_DEFINES='skia_gpu=0' python bin/sync-and-gyp
ninja -C out/Debug
``` 
(that's more or less verbatim from their [OSX install instructions.](https://skia.org/user/quick/macos)) Maybe that's what's causing my problems?

**Comment by tony** [comment]
@dvlpstrcrispin 

Is skia built?

Can you try ``ninja -C out/Release dm`` for skia see if that helps?

I will take a closer look tomorrow AM

**Comment by dvlpstrcrispin** [comment]
The `cmake` step works fine, but I can't get it to go past that, with both `ninja` and `make`.
My (once again, probably overly verbose) logs are [here, for ninja](https://gist.github.com/dvlpstrcrispin/d2c4a7593a7c8fe425de0119d9583389) and [here, for make](https://gist.github.com/dvlpstrcrispin/72a5d573f200c34edde389a773532ea9).

**Comment by zwik** [comment]
For me it also fails on the exact same place.

**Comment by tony** [comment]
Hi, I made a PR clarifying OS X build instructions.  This is intended clear up ambiguity introduced in the current instructions.

See it in situ @ https://github.com/tony/aseprite/blob/install-rewrite/INSTALL.md

@dvlpstrcrispin

Can you double check skia was built from ``chrome/m50`` branch?

> Also the chrome/m50 branch for skia is no longer there it seems...

Its still there. Do you not see it in `git branch -la`?

The remote still has it, https://github.com/google/skia/tree/chrome/m50.

> SKIA_DIR to point to the checkout directory. However in the "Mac OS X" section he tells to point SKIA_DIR to a compiled version.

At the current time (7c9b9ea, April 2016) ``SKIA_DIR`` points to your skia checkout (the root of the project), not ``out/Debug`` or ``out/Release``. See the [src/she/CMakeLists.txt](https://github.com/aseprite/aseprite/blob/master/src/she/CMakeLists.txt). ``-DSKIA_DIR`` will end up being used to look for the built ``out/{Debug,Release}`` inside.

By "compiled version", its meant that skia should be compiled there before hand, since it'll be looking for the build files that end up in the ``out/`` of the skia project.

**Comment by OrenjiAkira** [comment]
With the new params I was successfully able to compile on my OSX. I ran `ninja -C out/Release dm` on top of [skia's building instructions](https://sites.google.com/site/skiadocs/user-documentation/quick-start-guides/mac), though. Is that part of building skia?

Anyway, thanks.

**Comment by zwik** [comment]
Thanks @tony ! I got it working by now. I was looking wrongly and only saw my local branches for Skia (I felt dumb). I checked out the chrome/m50 branch, built it and Asesprite is now almost succesfully compiled. Also thanks for clearing up the SKIA_DIR var!

I'm getting one more error while linking the final executable. The gist can be found here: https://gist.github.com/zwik/883c12874d76de1f7daa00e1ac11b365

**Comment by tony** [comment]
@zwik   When I had that same error, I ended up using a scratch repo to fix the problem, so I never isolated why that happened.

Try doing a ``ninja clean`` and rebuilding.  If that doesn't work, you may need to clean out the skia files (something like ``git clean -d -x -f`` if you wanted to be aggressive). Then rerun skia instructions from scratch.   Then after that, try to run ninja for aseprite.

**Comment by tony** [comment]
@OrenjiAkira Yes, the ``ninja -C out/Release dm`` inside of the skia checkout compiles the skia libs for you.

**Comment by zwik** [comment]
@tony I've tried to start all over again. Built both skia and aseprite again but aseprite keeps failing with the same error as posted in the gist earlier.

**Comment by tony** [comment]
When you look in your ``history``, did you use ``ninja -C out/Debug dm`` or ``ninja -C out/Release dm``?

I notice my instruction use ``ninja -C out/Debug dm``.

If you used ``ninja -C out/Debug dm``, can you try ``ninja -C out/Release dm``, then run ninja again for aseprite?

If you used ``ninja -C out/Release dm``, can you try ``ninja -C out/Debug dm``, then run ninja again for aseprite?

**Comment by dvlpstrcrispin** [comment]
Building skia with the `chrome/m50` branch was what fixed it. I think skia needs to be built with `ninja -C out/Release dm`, but I built both. Thanks for the help!

**Comment by zwik** [comment]
@tony I built with both release and debug but will try again.

@dvlpstrcrispin I also used the chrome/m50 branch.

**Comment by zwik** [comment]
Tried again, now with debug for skia and then rebuilding aseprite. Same error. Question, are you guys on the master branch for aseprite or did you checkout a tag?

**Comment by dvlpstrcrispin** [comment]
I built it from master.

**Comment by dacap** [comment]
@zwik don't use the Debug version of Skia, it will be really slow, use the Release one

**Comment by dacap** [comment]
From your last log @zwik, it looks like your Skia version was compiled with gpu support.

**Comment by dacap** [comment]
@zwik See if `echo $GYP_DEFINES` prints `skia_gpu=0`, if not, you should use `export GYP_DEFINES=skia_gpu=0` before `sync-and-gyp` command.

**Comment by tony** [comment]
@zwik what version of OS X are you on?  What version of ninja, cmake?

Can you get the ``git rev-parse HEAD`` for skia and aseprite?

Re: https://github.com/aseprite/aseprite/issues/1089#issuecomment-214908250

Are you sure you're doing the ``export GYP_DEFINES='skia_gpu=0'``?  Does the terminal you built skia have any output to ``echo $GPU_DEFINES``?

**Comment by zwik** [comment]
Alright clear, I used the release version before but that also doesn't seem to build aseprite for me.

**Comment by zwik** [comment]
@tony I just threw everything away and start all over again by checking out all the repositories so can't answer right now. But I will asume I will have all the latest when cloning the repositories ;) .

**Comment by zwik** [comment]
I just, again, completely started over and all seems to work now, finally ;) . Thanks for all the help guys!
