### ISSUE TITLE
Little visual glitch on OS X

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1091]
> So whenever I right-click something and move my cursor around, the cursor leaves behind this trail of black blobs that kinda resemble the cursor.

> Image: http://imgur.com/DOSSCpy (click on the image for a better resolution)

Reported here: http://steamcommunity.com/app/431730/discussions/2/357284131798312400/

**Comment by trollworkout** [comment]
I noticed that too. I am using 1.1.4.0 and not the latest. For me it leaves pieces of the cursor like a trail of little dots or lines. It goes away after a while , however. I am not sure how this is triggered or how it goes away.

**Comment by dacap** [comment]
This bug might be related to the fix included in fda9abce334501f71041d371683b0751c11afbdd

It only happen when the program is executed the very first time on OS X or if the window cannot be created with the configured size (e.g. if the window was closed in a second monitor, then the monitor is disconnected and the program is re-opened in the smaller monitor).

I'll close this issue but it might re-appear after v1.1.5.5.
