### ISSUE TITLE
Request: Reduce Palette.

### ISSUE THREAD

**Issue by Nsheppard01** [aseprite/aseprite#1099]
Sometimes I try to make palettes from pictures found on the internet. Unfortunately due to JPEG nonsense, getting a clean set of consistent colors can be difficult, even if it's a picture of colored bars, the bars will not be solid color due to JPEG artifacts.

It would be nice if there was a way to tell Aesprite to reduce the palette to crunch down the colors and create an indexed palette of arbitrary size based on the available colors. IE, if it has 5 shades of green, it will crunch it down into just one green that represents the average of all the green-ish pixels in the picture.

Right now I sort of do this by hand using the color replace and create new palette from this image button, but it's really tedious and I think it could be automated with a clever algorithm. Something to do with standard deviance. IE, if you tell it to make a 16 color palette, it sorts the palette, then breaks it down into 16 chunks using whatever algorithm the tolerance slider in the replace color dialogue uses.

**Comment by dacap** [comment]
Hi @Nsheppard01, actually there is a way to generate a reduced palette from this menu: http://imgur.com/IfrVyfd
