### ISSUE TITLE
Cannot copy and paste frames "sometimes"

### ISSUE THREAD

**Issue by kyrieru** [aseprite/aseprite#1101]
Let's say I have frame A, and I want to make a copy, and put it next to frame B.

Sometimes if you copy a frame A, and paste it at frame B (the intent being that they will be next to each other), it will instead make a copy of frame B right next to frame B.

Yet, when I moved frame A next to frame B, and then copied frame A and pasted it where it used to be, it makes another frame A like it should.

Kind of confusing, but the point is that copying and pasting frames has some kind of issue.

**Comment by dacap** [comment]
Hi @kyrieru, I'm not sure how are you copying frames, are you using Ctrl+C and Ctrl+V? I've to review the Ctrl+C and Ctrl+V in the same document. You might find a more accurate behavior using the drag-and-drop operation to copy frames. http://www.aseprite.org/docs/copy-frames/

**Comment by dacap** [comment]
There is a crash related to copy & paste frames in the same sprite. I'll see this issue. (There is no known issue at this moment about copying frames using drag-and-drop, only using copy & paste.)

**Comment by zendorx** [comment]
Problem still exists. Copy frames in one tab and pasting in another works half of the times
