### ISSUE TITLE
Aseprite crashed and deleted my pictures file.

### ISSUE THREAD

**Issue by SamanthaeG** [aseprite/aseprite#1106]
I've been working on a gif and picture for over 5 hours and aseprite would occasionally give me errors. I'd save my picture right after they'd happen. It eventually crashed and I couldn't find the file anywhere. Is there any where I can find it or get it back. I'm very upset.

**Comment by dacap** [comment]
Hi @SamanthaeG, are you on Windows using the official version? Could you please send me [the crash report](http://www.aseprite.org/assets/images/data-recovery.gif)?

Also, there is a 'data recovery' function you might use to recover your work:
![data-recovery](https://cloud.githubusercontent.com/assets/39654/14972808/7f5c47c4-10b6-11e6-8e66-fcb954ab3d6a.gif)
