### ISSUE TITLE
Cropping Data Outside the Canvas

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1111]
Aseprite allows cels to be larger than the document's visible dimensions. It... is impossible to get rid of the stuff outside the window without involved workarounds.

I understand the want to preserve the unseen pixels in certain cases. But one of the realities of this is that if you say... have a large animated image that you crop, your file (and the data it's consuming) will not get smaller, ever (that I've found), for the life of the file for those frames. What I've done in the past is saved as .gif and reloaded, but this gets rid of my layers and things.

Here is an example (gif) of a situation where this problem was created: 

![newlevelformatwhy2](https://cloud.githubusercontent.com/assets/8582123/15008090/c96573cc-11ab-11e6-8376-99ac064a81b2.gif)
I started by cropping a 3840x2304 level map. I just checked the .ase and all of the original image is still there.

For the above I was able to use linked cels for the huge cropped image so it only occupied memory once, but for other scrolling demonstrations I've made, a huge image is there even after cropping _in every frame._

I'm not sure adding a second option (called Crop Unseen(?)) is worth it. But maybe Crop with nothing selected could get rid of this unseen data instead of being grayed out?

Edit: Perhaps with a popup confirmation so the user can see what crop with nothing select is doing. If nothing is selected "Crop Non Visible Pixels? (Yes) (No)"

**Comment by dacap** [comment]
Known issue. Thanks for reporting this with so much details. Actually this issue will be even more visible in the next release where we can enable layer edges:
![layer-edges](https://cloud.githubusercontent.com/assets/39654/15013888/c35114be-11d8-11e6-981d-d8555ce4fd3f.gif)

**Comment by dacap** [comment]
This issue is related to #559, after we edit a layer, we should automatically trim pixels.

**Comment by dacap** [comment]
The commit 5d8af3ca36b996219b72d0313134612440755acb fixed the "buggy" part of this issue. Which means that now we can make files smaller manually erasing pixels (because cels will be get smaller and smaller). But there is no command to remove/crop all unseen areas automatically. That should be a new command.

**Comment by dacap** [comment]
This might be related to #804

**Comment by dacap** [comment]
I'll fix this issue adding a new option in the Canvas Size command:

![image](https://user-images.githubusercontent.com/39654/56519727-30deb400-6519-11e9-9a94-5e088e06b033.png)

So just using the Canvas Size with the same size, but with this option enabled, we will be able to remove the content outside the canvas.
