### ISSUE TITLE
Request: Make goto frame textfield only active on click like all the others

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1113]
This in the bottom right:
![framebox](https://cloud.githubusercontent.com/assets/8582123/15009042/2c188c9c-11b2-11e6-927e-1cf5b1079201.png)
I'm a tablet user. I take my pen from the tablet. My mouse will move to the corresponding location of the screen when I hover the pen back over, which is usually nowhere near where it was before.  

Occasionally, that location is over the frame box which activates it. And then you can't pan (space enters ' ' there), or use a hotkey (like 'm' for marquee tool or 'b' for the brush tool). Enter doesn't even defocus it. (A separate issue. Enter does succeed in changing to the entered frame, but the box doesn't lose its focus which is odd.)

What I usually do is press tab to toggle the timeline twice, but it's super annoying, and hard to avoid for tablet users. All of the other boxes my mouse might hover over as I reapply my hand to the tablet require a click to activate (brush size, zoom, etc).

Edit: This was mentioned in passing in issue #628, but really this is a different kind of issue. And maybe a simple one. More like a single UI element fix (since other similar UI elements have behavior that requires a click), rather than something that requires a lot of program design thought. 

Aseprite v1.1.4.1 on Windows Vista 32bit

**Comment by dacap** [comment]
I'll try to take a look at this issue right now.
