### ISSUE TITLE
Request: A visual indication for when the document is locked

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1114]
On some larger files, I frequently get the

"A problem has occurred.

Details:
Cannot modify the sprite.
It is being used by another command.
Try again."
Currently, I end up trying the operation, then closing this box every few seconds. A visual would at least let me know when the action will actually work rather than hoping. 

I understand that a visual that constantly flickers for shorter document locks may be annoying, but perhaps having something that appears when this warning is needed (so after the first popup of this box for a given lock), and goes away when the document is unlocked may work. This way it's only seen for longer document locks.

**Comment by dacap** [comment]
I was thinking about this too. Maybe a little floppy disk (like in Word or Excel) that appears when the background backup is being made (i.e. the document is locked). Also the dialog box could be replaced with a (less invasive) tooltip.
