### ISSUE TITLE
aseprite 1.1.5.0 crashes when mouse over tools OSX

### ISSUE THREAD

**Issue by trollworkout** [aseprite/aseprite#1116]
I have compiled the latest release and when I run it I notice when mouse goes over the tool bar the program crashes. I have temporarily reverted to 1.1.4.0 release .

I am currently trying to compile latest source directly from repo see if this is still an issue.

**Comment by dacap** [comment]
Hi @trollworkout, do you have a crash report? They contain a stack trace which are really helpful to fix this kind of problems.

**Comment by trollworkout** [comment]
@dacap It simply crashes to desktop without a crash report pretty odd. I am currently recompiling from repo code instead of last release + investigating why no crash report perhaps reporting was disabled on my system. I will post here when I find out more.

**Comment by trollworkout** [comment]
@dacap I have compiled the code from the repo and tried to run it and same issue. 

I had my crash reporting disabled . Re-enabled it and here is what it says
http://pastebin.com/3eJy2K77

**Comment by dacap** [comment]
Are you updating the `/data` directory inside `Aseprite.app` bundle? The compilation process correctly copies the `data/` directory in `build/bin/data`, but here I think you are doing a manual step, copying the `aseprite` binary inside the bundle, but not updating the `data`.

**Comment by trollworkout** [comment]
@dacap oh .. I think I know what the problem is

**Comment by dacap** [comment]
Ok, please close the issue if you find a solution.

**Comment by trollworkout** [comment]
@dacap  works ! You were right . I did not copy data correctly. Sorry about the trouble.
