### ISSUE TITLE
Problems with compiling

### ISSUE THREAD

**Issue by KarurosuBG** [aseprite/aseprite#1117]
I'm getting this compile error, don't which files I'm missing, I'm using the latest version of everything...

"C:/Users/Admin/Desktop/New folder/third_party/zlibD:/Aseprite/third_party/zlib
Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
Call Stack (most recent call first):
C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/FindPNG.cmake:157 (find_package_handle_standard_args)
CMakeLists.txt:189 (find_package)"

**Comment by dacap** [comment]
Hi @KarurosuBG, did you download the full source code? Instructions: https://github.com/aseprite/aseprite/blob/master/INSTALL.md#get-the-source-code

**Comment by KarurosuBG** [comment]
Of course, that's how I got the compile error to begin with. 

The reason of the issue could be a non working version of something, but I don't know where to start looking...

**Comment by winterheart** [comment]
Hello.
@KarurosuBG, it seems you trying to compile aseprite with shared libraries. Try to switch USE_SHARED_* to OFF in cmake-gui.

**Comment by KarurosuBG** [comment]
I'm still getting issues, I don't know what's the issue with dx libs

```
C:/Users/Carlos/Desktop/New folder/third_party/zlibD:/Aseprite/third_party/zlib
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
Could NOT find DXGUID (missing:  DXGUID_LIBRARY) 
CMake Error at src/she/CMakeLists.txt:16 (message):
 DirectX required for Windows port.  You might need to add DirectX include
 and lib directories to your INCLUDE and LIB environment variables.


Configuring incomplete, errors occurred!
See also "D:/Aseprite/CMakeFiles/CMakeOutput.log".
See also "D:/Aseprite/CMakeFiles/CMakeError.log".
```

**Comment by winterheart** [comment]
OK, you need last thing - dxguid.lib from DirectX SDK. Download SDK from Microsoft's site, rerun cmake and, if CMake will fail to find it, define location manually.

**Comment by KarurosuBG** [comment]
I don't know where dxguid.lib issupposed to be, and also I'm unable to install 2010 DX SDK even after uninstalling 2010 c++ res.

**Comment by sirblackheart** [comment]
#1026 #1087

**Comment by KarurosuBG** [comment]
Ok, so apparently even if I solve the dx issue, I would still be having to solve an extra  bunch of issues; - really don't have time for this now. Some caring soul could please give me a favour and link me a compiled dev build?  I'm really needing it.

**Comment by dacap** [comment]
Hi @KarurosuBG, contact me at support@aseprite.org
