### ISSUE TITLE
Add option to export one animation (tag) on each row

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1118]
Add an option to export each tags in one row (or column). Source: https://twitter.com/jtangc/status/727675034962038785/photo/1

![chk2rz4u4aacpld](https://user-images.githubusercontent.com/39654/29197889-bca7d60c-7e15-11e7-928e-6d69b7f27804.png)

Community: https://community.aseprite.org/t/sprite-sheet-export-with-layout-by-tags/276

--- 

*Implementation details:* This could be a new option for `SpriteSheetType::Rows`/`Columns` with a check box `[ ] One row/column for each tag` or a new `SpriteSheetType::TagsInRows`/`Columns`.

**Comment by dacap** [comment]
Dev Note: I'll leave this for v1.2-beta3, as it requires a `ExportSpriteSheetWindow` refactor to reuse the `DocumentExporter` to calculate the sprite sheet size, etc. Some work was already done.

**Comment by therocode** [comment]
Very useful feature, glad to see it on its way!  Some questions regarding it:

1. Would it support putting tags on the same row as another as long as they fit? i.e. the A and C tags of the example image could be put on the same row. I guess it would not strictly be "one animation on each row" but more like "make sure no animations are split across several rows" which at least for my use case would be what is actually useful. Could perhaps be a second option for this feature?

2. Any approx ETA when this feature will ship?

Thanks

**Comment by harrisonmonroe** [comment]
I hope this will get implemented this is awesome!

**Comment by 41Danny1** [comment]
I too, would like to see this feature!

**Comment by dacap** [comment]
This will be available in v1.2.16

**Comment by harrisonmonroe** [comment]
Wow thats great thank you!
