### ISSUE TITLE
Request: HSB and Grayscale support for the lower left color palette.

### ISSUE THREAD

**Issue by PixelScum** [aseprite/aseprite#1121]
Right now it's RGB only but being able to just permanently set it to HSB would be a life-saver for me, cutting down the amount of time I'd need to do shading & highlights.

**Comment by dacap** [comment]
Hi @PixelScum, do you mean that when you pick a color with eyedropper the color is given as RGB but you would prefer HSB? That is possible using this option in the context bar:

![eyedropper-options](https://cloud.githubusercontent.com/assets/39654/15115642/6513073e-15d6-11e6-8570-a5fe3045b292.png)

Anyway I'm not sure if that is exactly what you are looking for.

**Comment by PixelScum** [comment]
Specifically I mean replacing the color spectrum/color wheel portion of the UI with an HSB style option. 
![zodzq2y 1](https://cloud.githubusercontent.com/assets/5758446/15146236/180400b2-166f-11e6-9ba9-3fdb0773d788.png)

**Comment by KasumiArai** [comment]
There is a HSB style option: 

![colorpicker](https://cloud.githubusercontent.com/assets/8582123/15146854/81a64f22-168b-11e6-9fba-e85ceb06b3ce.gif)

**Comment by PixelScum** [comment]
Oh crud, it looks like my Aseprite wasn't actually up to date for some reason. Thank you so much. My apologies.

**Comment by dacap** [comment]
Thanks @KasumiArai for the help with this one

**Comment by KyokaNyx** [comment]
![image](https://github.com/user-attachments/assets/2fb37faa-6fe5-42dc-b3e6-ccfee3044d70)
Is it possible to enable HSB or add it using plugins?

**Comment by dacap** [comment]
> Is it possible to enable HSB or add it using plugins?

Hi @KyokaNyx, the HSV tab is already the HSB option (Value = Brightness).
