### ISSUE TITLE
Error creating directory (a component is a file name)

### ISSUE THREAD

**Issue by trollworkout** [aseprite/aseprite#1124]
Aseprite refuses to run giving this error

`Error creating directory (a component is a file name)`

**Comment by dacap** [comment]
Hi @trollworkout, are you on Windows, OS X, or Linux? where are you trying to create a folder and with what name?

**Comment by trollworkout** [comment]
@dacap What happened was my ~/.config folder was changed to a file by something. I have to figure it out. So aseprite was not able to create ~/.config/aseprite folder for it's settings. 

I am on OSX

**Comment by dacap** [comment]
Thanks for the hint @trollworkout, I'll write something about this in the FAQ.

**Comment by dacap** [comment]
I think I'll add a little check in the program to show an alert dialog if the ~/.config is not a directory.

**Comment by trollworkout** [comment]
Thank you @dacap .

**Comment by dacap** [comment]
Finally I've changed the configuration folder to `~/Library/Application Support/Aseprite` (#1165) so this issue is fixed in other way (I guess 😅 )
