### ISSUE TITLE
Alt-Tab Hotkey Lock?

### ISSUE THREAD

**Issue by Ashedragon** [aseprite/aseprite#1126]
I'm not even totally sure how to describe this one--it's just so strange, but I will give it my best. I'm on Windows 10, 32-bit on a laptop. Sometimes when switching from ASEPRITE to a window on another desktop and then switching back, ASEPRITE's commands/shortcuts seem to completely lock up. I can still use the tool I currently have selected and I can switch to other tools using the mouse, but **none** of the keyboard commands work at all. This includes combination commands like CTRL+Z and one-button shortcuts like D--I can't even use spacebar to scroll the window.
It's happened to me since 1.1.4 I believe (I'm currently using 1.1.6-dev). I hope any of this makes sense...

**Comment by dacap** [comment]
Hi @Ashedragon, are you using the Allegro back-end or skia back-end? Could you please give a try to the Skia back-end to see if this issue is fixed (the Allegro back-end is the default one in the compilation process because it makes it easier to compile Aseprite, but it will be removed in a near future because a lot of other issues are fixed with the Skia back-end)

**Comment by Ashedragon** [comment]
Okay, I attempted to build Skia via the instructions in the INSTALL file, but when I run the command "ninja -C out/Release dm" it gives me "This version of C:\deps\depot_tools\ninja.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher."
I Googled the issue and then tried running it in compatibility mode to no avail, although I didn't particularly expect them to work. Can Skia not be compiled on an x86 architecture?  Am I missing something? The documentation I read lead me to believe I may not be, but I could have completely misparsed it.

**Comment by dacap** [comment]
@Ashedragon it looks like depot_tools is prepared for x64 architectures, would you like to try replacing the ninja.exe executable with the x86 version? https://github.com/ninja-build/ninja/releases

**Comment by Ashedragon** [comment]
Okay, since ninja apparently does not come in a pre-built x86 package, I went ahead and built it. Skia built just fine once I did that and the rest of it was smooth sailing. I'll report back when I have time to test the new build extensively and see if the problem still occurs.

**Comment by dacap** [comment]
OK, I'll close this issue, we can reopen this in case that it appears with the Skia back-end. :+1:

**Comment by Ashedragon** [comment]
Okay, I can confirm that switching to Skia appears to have fixed the issue--as well as a couple of other issues I was having that I hadn't reported yet. This makes me curious, but I'm satisfied that my problems have been rectified.
