### ISSUE TITLE
Can't Update Within Aseprite

### ISSUE THREAD

**Issue by dylanaco** [aseprite/aseprite#1129]
When trying to update to the new Aseprite, read the documentation or reading the release notes; Aseprite gives out an error message about the file not having a program associated with it. I hope it will be fixed in the future!

**Comment by dacap** [comment]
Hi @dylanaco, are you on Windows, OS X, or Linux (a specific distribution)?

**Comment by dacap** [comment]
As a side note, Aseprite cannot be updated from Aseprite itself, you must download the new version manually. The only way to keep Aseprite automatically updated is using the Steam version or the itch.io app (which I've tested it yet anyway).

**Comment by dylanaco** [comment]
I am using Windows. Thank you @dacap what about the release notes or documentation? When clicking it says "Program not associated with it".

**Comment by dacap** [comment]
@dylanaco Aseprite uses the default web browser associated with http protocol (like running `start http://www.google.com/` on the command line)

**Comment by dacap** [comment]
Do you have a default web browser configured?

**Comment by dylanaco** [comment]
I believe I do not. Is that configured through the .ini file?

**Comment by dacap** [comment]
That is a system wide configuration. The default web browsers configured on Windows. You can test your default browser pressing `Windows key + R` and enter a URL like http://www.google.com

**Comment by dylanaco** [comment]
I got the same error message from doing that. I think you've found the problem, sir.

**Comment by dacap** [comment]
OK. I'll close this issue, we can re-open it if after you configure a default browser it still happens.

**Comment by dylanaco** [comment]
@dacap It works! Thanks for the quick response and help!
