### ISSUE TITLE
Preview window doesn't keep the scroll position for each sprite

### ISSUE THREAD

**Issue by dylanaco** [aseprite/aseprite#1131]
When switching to different tabs, the preview window changes it's view and I would need to position it back to it's correct view.

![kjrrsu](https://cloud.githubusercontent.com/assets/18191850/15195566/0a13f46a-178e-11e6-857b-c0c0ae344ce0.gif)

**Comment by dacap** [comment]
This issue looks like already fixed in v1.1.6.
