### ISSUE TITLE
Duplicate cel(s) option replaces existing cel

### ISSUE THREAD

**Issue by kinow** [aseprite/aseprite#1134]
Hi, 

If I have three cels, and duplicate the first frame, it will replace the second cel. Instead of replacing the cel, I'd prefer the program to duplicate the first cel and move the other cels to the right.

![duplicate_replacing](https://cloud.githubusercontent.com/assets/304786/15265077/5680b92a-19d0-11e6-8f9d-9d52c2fcee9f.gif)

**Comment by dacap** [comment]
Hi @kinow, actually this is an expected behavior, you can add frames to displace cels. The duplication is done just copying cels at the right side.
