### ISSUE TITLE
Windows compiling

### ISSUE THREAD

**Issue by JosefKuchar** [aseprite/aseprite#1143]
I'm trying to compile aseprite on windows(linux is ok), i'm getting this error:
`C:\Users\Josef\aseprite\aseprite\build>cmake -G Ninja ..
-- The C compiler identification is MSVC 19.0.23506.0
-- The CXX compiler identification is MSVC 19.0.23506.0
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- broken
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "C:/Program Files (x86)/Microsoft Visual Studio
  14.0/VC/bin/cl.exe" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/Users/Josef/aseprite/aseprite/build/CMakeFiles/CMakeTmp

  Run Build Command:"C:/Users/Josef/AppData/Roaming/Ninja/ninja.exe"
  "cmTC_dbb00"

  [1/2] Building C object CMakeFiles\cmTC_dbb00.dir\testCCompiler.c.obj

  [2/2] Linking C executable cmTC_dbb00.exe

  FAILED: cmTC_dbb00.exe

  cmd.exe /C "cd .  && "C:\Program Files (x86)\CMake\bin\cmake.exe" -E
  vs_link_exe --intdir=CMakeFiles\cmTC_dbb00.dir --manifests --
  C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo
  CMakeFiles\cmTC_dbb00.dir\testCCompiler.c.obj /out:cmTC_dbb00.exe
  /implib:cmTC_dbb00.lib /pdb:cmTC_dbb00.pdb /version:0.0 /machine:X86 /debug
  /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib
  winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib
  advapi32.lib && cd ."

  RC Pass 1 failed to run.

  ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:38 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Josef/aseprite/aseprite/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Josef/aseprite/aseprite/build/CMakeFiles/CMakeError.log".`
Can you help me?

**Comment by JosefKuchar** [comment]
I tryed to run vcvarsall.bat am64, and it works! :)

**Comment by flamendless** [comment]
Mine has the same error as yours. Trying amd64 still doesnt work. What did you do? Also, how did you install ninja?

**Comment by JosefKuchar** [comment]
This was old building method. In recent build, you must do everything same as in INSTALL.md (use skia). For ninja installation: I copyied ninja to %appdata% folder and add to windows PATH and it works :)
