### ISSUE TITLE
Build tries to use submodule pixman despite `-DUSE_SHARED_PIXMAN=ON` being set

### ISSUE THREAD

**Issue by shackra** [aseprite/aseprite#1146]
I'm packaging Aseprite for Parabola GNU/Linux-libre. For some reason the compiler will try to use the code in the submodule `pixman` thought the CMake option `-DUSE_SHARED_PIXMAN=ON` was set.

This is the command used for compiling the project:

```
mkdir -p build && cd build 
  
  cmake -DUSE_SHARED_PIXMAN=ON \
        -DWITH_WEBP_SUPPORT=ON \
        -DUSE_SHARED_LIBWEBP=ON \
        -DUSE_SHARED_CURL=ON \
        -DUSE_SHARED_GIFLIB=ON \
        -DUSE_SHARED_JPEGLIB=ON \
        -DUSE_SHARED_ZLIB=ON \
        -DUSE_SHARED_LIBPNG=ON \
        -DUSE_SHARED_LIBLOADPNG=OFF \
        -DUSE_SHARED_TINYXML=ON \
        -DENABLE_UPDATER=OFF \
        -DUSE_SHARED_FREETYPE=ON \
        -DFREETYPE_INCLUDE_DIR=/usr/include/freetype2 \
        -Wno-dev \
        -DCMAKE_INSTALL_PREFIX:STRING=/usr ..
  make aseprite
``` 

The details of the error:

```
 |  [ 35%] Building CXX object src/doc/CMakeFiles/doc-lib.dir/blend_funcs.cpp.o
 |  In file included from /build/aseprite/src/aseprite/src/doc/blend_funcs.cpp:23:0:
 |  /build/aseprite/src/aseprite/src/./doc/blend_internals.h:11:62: fatal error: ../../third_party/pixman/pixman/pixman-combine32.h: No such file or directory
 |   #include "../../third_party/pixman/pixman/pixman-combine32.h"
 |                                                                ^
 |  compilation terminated.
```

**Comment by shackra** [comment]
and the aforementioned file doesn't exists, at leas for pixman 0.34.0:

```
pixman /usr/
pixman /usr/include/
pixman /usr/include/pixman-1/
pixman /usr/include/pixman-1/pixman-version.h
pixman /usr/include/pixman-1/pixman.h
pixman /usr/lib/
pixman /usr/lib/libpixman-1.so
pixman /usr/lib/libpixman-1.so.0
pixman /usr/lib/libpixman-1.so.0.34.0
pixman /usr/lib/pkgconfig/
pixman /usr/lib/pkgconfig/pixman-1.pc
pixman /usr/share/
pixman /usr/share/licenses/
pixman /usr/share/licenses/pixman/
pixman /usr/share/licenses/pixman/COPYING
```

**Comment by sirblackheart** [comment]
@shackra take a look at [blend_internals.h](https://github.com/aseprite/aseprite/blob/master/src/doc/blend_internals.h)
it does indeed use the header from the third_party folder and you shared option in not relevant here.
I suspect you did not do a `git clone --recursive` and are missing the pixman-combine-32.h for that reason. You always can init the sub-modules with `git submodule --init --recursive`.

**Comment by shackra** [comment]
During packaging, internet connection is not available inside the chroot environment, so using such
git commands isn't useful.

However, we have an option to prepare the source code of a package before attempting any
packaging. In the end I just initiated just the necessary submodules for aseprite.

The build went just fine.

El jueves 26 de mayo del 2016 a las 0608 horas, Gabriel Rauter escribió:

> @shackra take a look at [blend_internals.h](https://github.com/aseprite/aseprite/blob/master/src/doc/blend_internals.h)
> it does indeed use the header from the third_party folder and you shared option in not relevant here.
> I suspect you did not do a `git clone --recursive` and are missing the pixman-combine-32.h for that reason. You always can init the sub-modules with `git submodule --init --recursive`.
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/aseprite/aseprite/issues/1146#issuecomment-221853310


-- 
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra
