### ISSUE TITLE
Import Spritesheet margin option

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1147]
> Any chance of getting an option in the Import Spritesheet options to specify and inter-row / inter-column margin? 
> 
> I have a couple of spritesheets created elsewhere that have, say, a 1-pixel margin between every row, and it's a pain to import them and then resize them all.

Source: http://steamcommunity.com/app/431730/discussions/1/357287304424761424/

**Comment by d3cka2d3pw00d** [comment]
Hi just bought this software! It's great so much easier than using photoshop!
Have you added this fix yet.. Import Spritesheet margin option #1147?

**Comment by adveres** [comment]
Hi, Any update on this? I downloaded v1.2.6 trial today to test out Aseprite and can't import sprite sheet I was using because there's no options for padding/margins.  Slightly disheartened the last comment on this was over a year ago 😢

**Comment by Gasparoken** [comment]
This is possible interactively since https://github.com/aseprite/aseprite/issues/78 was solved:
![ImportSpriteSheetPadding](https://user-images.githubusercontent.com/32165475/211308125-7f1989db-2f45-406b-88b2-c5076597aae3.gif)
I think this issue can be closed @dacap.
