### ISSUE TITLE
Suggestion: Increase Max. Brush Size

### ISSUE THREAD

**Issue by SolarLune** [aseprite/aseprite#1151]
Hey, there. 

The maximum brush size is 64px at the moment; I think it'd be nice to support larger increments, just in case you're pixeling something that requires a large spherical structure in it (like a background with a moon or planet in it).

Thanks.

**Comment by dacap** [comment]
Hi @SolarLune, I recommend you to use the Ellipses tool for bigger shapes:

![big-circle](https://cloud.githubusercontent.com/assets/39654/15894672/7de5a552-2d5d-11e6-9f64-45e2df76f637.gif)

**Comment by SolarLune** [comment]
Ah, I guess that'd work fine. Thanks! Should I close this, then?

**Comment by dacap** [comment]
I close it for you ;)
