### ISSUE TITLE
Using ALT+scroll wheel to manoeuvre the colour palette does not work after using the colour picker

### ISSUE THREAD

**Issue by alexander-b** [aseprite/aseprite#1153]
If I use the colour picker to obtain a colour on my palette, and then use ALT+scroll wheel, the first (topmost and leftmost) colour of my palette is chosen rather than the next colour on my palette. This happens despite the fact that Aseprite correctly identifies the colour in the palette from the colour picking action.

This is very frustrating as this is the scenario where the ALT+scroll wheel feature would be the most useful. E.g. if I want to apply light/shadow to my pixelart, I would like to select the colour that's already there, and then go one or two colours up/down my ramp to get a brighter/darker colour to represent light/shadow.

**Comment by dacap** [comment]
Hi @alexander-b, are you on Windows, OS X, or Linux?

**Comment by alexander-b** [comment]
I am on GNU+Linux, and I built HEAD today with default cmake options. I updated from the 1.1.3 tag today, which also had the same issue for me.

**Comment by dacap** [comment]
This problem happens on RGB images (not in Indexed images). I'll try to fix this for v1.1.
