### ISSUE TITLE
Environment Variable Trouble

### ISSUE THREAD

**Issue by DeVoePack** [aseprite/aseprite#1154]
I've been trying to adding aseprite as a PATH environment variable, but aseprite isn't being recognized. Any suggestions? I've already tried my aseprite path in quotes and made sure a copied the path word from word, but still no luck.

**Comment by dacap** [comment]
Hi @DeVoePack, are you on Windows or OS X?

On Windows you have to do something like this:

    @set PATH="C:\Program Files\Aseprite";%PATH%

Or

    @set PATH="C:\Program Files (x86)\Aseprite";%PATH%

On OS X:

    export PATH=/Applications/Aseprite.app/Contents/MacOS/:$PATH

In case that you've used the official installers. On Steam the locations are different:

    C:\Program Files\Steam\SteamApps\common\Aseprite
    ~/Library/Application Support/Steam/steamapps/common/Aseprite/Aseprite.app/Contents/MacOS
