### ISSUE TITLE
Opacity problem with click and shift click

### ISSUE THREAD

**Issue by kloworks** [aseprite/aseprite#1155]
I notice this problem when I click and shift click. 

click
http://imgur.com/ahbQgdb

shift+click
http://imgur.com/zIxHod4

is suppose to be like this
http://imgur.com/e0WDhML

**Comment by dacap** [comment]
Quite complex problem to solve (mainly for bigger brushes)

**Comment by kloworks** [comment]
if gonna take times to solve it no problem as long as in the future you can fix it :+1:

**Comment by kloworks** [comment]
I believe this should be close no more issue with the opacity and click 👍

**Comment by dacap** [comment]
👍 oky, I think the issue is solved for brushes with one pixel, we might close it (I'm not sure if we could solve this for bigger brushes anyway)

**Comment by kloworks** [comment]
yeah even with Photoshop with bigger brush can't. so its not like a problem from your software ... the main issue was in one pixel but now its fix 👍
