### ISSUE TITLE
Include tag's animation direction in output JSON

### ISSUE THREAD

**Issue by RussellSprouts** [aseprite/aseprite#1156]
I use the JSON output to output frames as a sprite sheet. I use the tags to separate different segments of animation. It would be helpful if the output JSON included the animation direction (forward, reverse, or ping pong).

**Comment by dacap** [comment]
Hi @RussellSprouts, you can already export tags information in JSON data using the CLI: http://www.aseprite.org/docs/cli/#list-tags

I hope it helps!

**Comment by RussellSprouts** [comment]
I know that the tag information is available, but it does not include the animation direction of the tag, as far as I can tell.

**Comment by dacap** [comment]
Hi @RussellSprouts, what version are you using? Here is an example of JSON output:
```
{ "frames": { ... },
 "meta": {
  ...,
  "frameTags": [
   { "name": "walk", "from": 0, "to": 2, "direction": "forward" },
   { "name": "run", "from": 3, "to": 4, "direction": "forward" }
  ]
 }
}
```

**Comment by RussellSprouts** [comment]
You're right. I had an outdated version from Ubuntu. I installed the latest from Humble Bundle, and it works great.

Thanks!

**Comment by dacap** [comment]
You're welcome! 😄
