### ISSUE TITLE
Select multiple layers by ctrl+clicking them

### ISSUE THREAD

**Issue by Kiloku** [aseprite/aseprite#1157]
This would be a useful feature for animation where you need to move certain layers by the same distance on the new frame

**Comment by dacap** [comment]
Hi @Kiloku, actually you can do something like that using the Move tool when several layers are selected in the Timeline: http://www.aseprite.org/docs/move-tool/#move-multiple-cels

**Comment by Kiloku** [comment]
The problem is that I can't select multiple layers that are not adjacent on the list of layers. The only way to select multiple layers (that I know of) is dragging the selection, which forces me to handle all layers in between the ones I want. 

[This is what I mean](http://i.imgur.com/LCWKspM.png) (I want to select the "Braco" and "Face" layers, but not any of the others)

**Comment by dacap** [comment]
Yeah, that's true and that's is why I didn't close the issue 😅  I'm just working in something (#454) that might enable this Ctrl+click behavior to select multiple non-adjacent layers (as layer groups needs new special ways to handle the layer selection).

**Comment by Kiloku** [comment]
Ah, got it. Thanks for the info and for the awesome software :smile:

**Comment by dacap** [comment]
Implemented, this will be included in the next v1.2-beta2

**Comment by dacap** [comment]
> It seems Ctrl+ LMB Click selects pixels of a clicked layer instead of selecting multiple layers. Is that correct?

That's right, you have to use Shift+click to pick another layer (and you can just press the LMB and drag the mouse to select a range of adjacent layers).

**Comment by F8ER** [comment]
> > It seems Ctrl+ LMB Click selects pixels of a clicked layer instead of selecting multiple layers. Is that correct?
> 
> That's right, you have to use Shift+click to pick another layer (and you can just press the LMB and drag the mouse to select a range of adjacent layers).

Thank you for the reply. Of course, this allows to select adjusted layers, but what if you have to select non-adjusted ones? For example "1 and 3"?

**Comment by dacap** [comment]
When you say "adjusted" you mean "adjacent" right? In the case that you want to select 1 and 3, you can click layer 1, and then press Shift+click in the 3 layer:

<img width="306" alt="Screen Shot 2022-03-31 at 11 30 14" src="https://user-images.githubusercontent.com/39654/161079664-a4699aee-7074-4d9a-8948-1410cffff5ed.png">

**Comment by F8ER** [comment]
> When you say "adjusted" you mean "adjacent" right? In the case that you want to select 1 and 3, you can click layer 1, and then press Shift+click in the 3 layer:
> 
> <img alt="Screen Shot 2022-03-31 at 11 30 14" width="306" src="https://user-images.githubusercontent.com/39654/161079664-a4699aee-7074-4d9a-8948-1410cffff5ed.png">

Oh! Thank you! I see. It seems the yellow box confused me, though I had to look at the layer line foreground and background colors.
Is it possible to deselect a particular selected layer while multiple are selected?

**Comment by Unknow0059** [comment]
>It seems the yellow box confused me
This also confused me with regards to how many layers I have selected.
