### ISSUE TITLE
The given example for --frame-tag on the CLI doesn't work.

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1160]
http://www.aseprite.org/docs/cli/#frame-tag

aseprite.exe -b --frame-tag "Run Cycle" several-animations.ase --save-as run-cycle.gif

To be really sure, I renamed my file to several-animations.ase and created a "Run Cycle" tag and I even did --list-tags to make sure the tag was recognized.

![clioutput](https://cloud.githubusercontent.com/assets/8582123/16174825/4d74384a-35a3-11e6-8a0d-c0dcccfa4686.png)
The output is run-cycle.gif that contains all the frames of several-animations.ase rather than just the frames that are tagged Run Cycle

Aseprite v1.1.5.7 on Windows Vista 32bit

Regardless of this issue, I recommend a --split-tags option like the --split-layers one.

**Comment by dacap** [comment]
Hi @KasumiArai, I think it's related to the whitespace in "Run Cycle", could you please try to use a RunCycle tag and see if it works?

As a side note, the `--split-tags` will be available in v1.2 first beta (already working in my local copy). Also there will be an automatic `--split-layer/tags` when `--save-as` is used with something like `--save-as my-file-{layer}-{tag}.gif`

**Comment by KasumiArai** [comment]
I had previously tried single word tags, which is what caused me to try the exact example. For completeness (both with and without quotes surrounding the tag): 

![clitest](https://cloud.githubusercontent.com/assets/8582123/16474633/4e6e0f9a-3e46-11e6-905f-fb196a5791bb.png)

run-cycle.gif and run-cycle2.gif are identical files that contain all the frames rather than just the ones with the tag specified.

**Comment by dacap** [comment]
Sorry @KasumiArai, my mistake. This will work on v1.2 beta1. I'm think that I'll release a beta on Steam without layer groups so I people can start testing this earlier.

**Comment by alexodden** [comment]
Issue seems to persist on 1.2.10 beta4, frame tag name has to be one word for it to work properly..
