### ISSUE TITLE
Import Sprite Sheet No Longer Captures the bottom/right row/column for uneven sheets

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1161]
This is a strange use case for sure, but the old behavior was to import them and surround them with transparency. 

The reason I discovered this is I was formatting a large image to be printed on a few separate pieces of paper. For this the pieces aren't necessarily going to go in evenly.
Aseprite 1.1.5.7
![importspritesheetrecent](https://cloud.githubusercontent.com/assets/8582123/16174878/888c0446-35a6-11e6-8c35-5587b692564c.gif)
Aseprite 0.9.5
![importspritesheetclassic](https://cloud.githubusercontent.com/assets/8582123/16174880/947b9c44-35a6-11e6-94dd-250beb7f4bd1.gif)

Aseprite 1.1.1 is the last build I have with the 0.9.5 behavior.

**Comment by dacap** [comment]
Hi @KasumiArai, I've included this checkbox:

![screen shot 2016-07-01 at 10 23 24 am](https://cloud.githubusercontent.com/assets/39654/16522725/e589a8f0-3f75-11e6-8fc0-9228187489f7.png)
