### ISSUE TITLE
INSTALL.md instructions inaccurate (for Windows, at least).

### ISSUE THREAD

**Issue by ranmaru90** [aseprite/aseprite#1162]
I have followed the instructions in that file to compile aseprite for Windows (Windows 10, VS 2015, skia and allegro backends).

Always failed to build the executable after following the instructions in INSTALL.md:

-- curl version=[7.21.6]
-- LDAP_H not found CURL_DISABLE_LDAP set ON
CMake Warning (dev) at third_party/curl/CMakeLists.txt:562 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "HAVE_FCNTL_O_NONBLOCK" will no longer be
  dereferenced when the policy is set to NEW.  Since the policy is not set
  the OLD behavior will be used.
Call Stack (most recent call first):
  third_party/curl/CMakeLists.txt:664 (curl_internal_test)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at third_party/curl/CMakeLists.txt:594 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "HAVE_GLIBC_STRERROR_R_COMPILE" will no longer be
  dereferenced when the policy is set to NEW.  Since the policy is not set
  the OLD behavior will be used.
Call Stack (most recent call first):
  third_party/curl/CMakeLists.txt:673 (curl_internal_test_run)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at third_party/curl/CMake/CurlCheckCSourceCompiles.cmake:16 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "curl_cv_recv" will no longer be dereferenced when
  the policy is set to NEW.  Since the policy is not set the OLD behavior
  will be used.
Call Stack (most recent call first):
  third_party/curl/CMake/OtherTests.cmake:31 (curl_check_c_source_compiles)
  third_party/curl/CMakeLists.txt:792 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at third_party/curl/CMake/CurlCheckCSourceRuns.cmake:16 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "HAVE_POLL_FINE" will no longer be dereferenced when
  the policy is set to NEW.  Since the policy is not set the OLD behavior
  will be used.
Call Stack (most recent call first):
  third_party/curl/CMake/OtherTests.cmake:202 (curl_check_c_source_runs)
  third_party/curl/CMakeLists.txt:792 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Building with ZLIB
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Creating directory D:/DevWorkFolder/aseprite/build/third_party/freetype2/include/freetype/config
-- Creating file D:/DevWorkFolder/aseprite/build/third_party/freetype2/include/freetype/config/ftconfig.h
-- Creating file D:/DevWorkFolder/aseprite/build/third_party/freetype2/include/freetype/config/ftoption.h
-- Configuring done
-- Generating done
-- Build files have been written to: D:/DevWorkFolder/aseprite/build

**Comment by ranmaru90** [comment]
executing `ninja aseprite` gives:
`[1/997] Building CXX object src/fixmath/CMakeFiles/fixmath-lib.dir/fixmath.cpp.obj
FAILED: src/fixmath/CMakeFiles/fixmath-lib.dir/fixmath.cpp.obj
D:\TDM-GCC-64\bin\c++.exe   -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_SKIA_BACKEND -DWINVER=0x0501 -D_UNICODE -D_WIN32_WINNT=0x0501 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src/. -I../src/.. -I../src/../third_party -Isrc/base -O2 -g -DNDEBUG -MMD -MT src/fixmath/CMakeFiles/fixmath-lib.dir/fixmath.cpp.obj -MF src/fixmath/CMakeFiles/fixmath-lib.dir/fixmath.cpp.obj.d -o src/fixmath/CMakeFiles/fixmath-lib.dir/fixmath.cpp.obj -c ../src/fixmath/fixmath.cpp
In file included from ../src/./config.h:40:0,
                 from ../src/fixmath/fixmath.cpp:7:
D:/TDM-GCC-64/x86_64-w64-mingw32/include/wchar.h: In function 'wchar_t* wmemchr(const wchar_t*, wchar_t, size_t)':
../src/./base/base.h:17:16: error: 'nullptr' was not declared in this scope
   #define NULL nullptr
                ^
[2/997] Building CXX object src/css/CMakeFiles/css-lib.dir/rule.cpp.obj
FAILED: src/css/CMakeFiles/css-lib.dir/rule.cpp.obj
D:\TDM-GCC-64\bin\c++.exe   -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_SKIA_BACKEND -DWINVER=0x0501 -D_UNICODE -D_WIN32_WINNT=0x0501 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src/. -I../src/.. -I../src/../third_party -Isrc/base -O2 -g -DNDEBUG -MMD -MT src/css/CMakeFiles/css-lib.dir/rule.cpp.obj -MF src/css/CMakeFiles/css-lib.dir/rule.cpp.obj.d -o src/css/CMakeFiles/css-lib.dir/rule.cpp.obj -c ../src/css/rule.cpp
In file included from ../src/./config.h:40:0,
                 from ../src/css/rule.cpp:8:
D:/TDM-GCC-64/x86_64-w64-mingw32/include/wchar.h: In function 'wchar_t* wmemchr(const wchar_t*, wchar_t, size_t)':
../src/./base/base.h:17:16: error: 'nullptr' was not declared in this scope
   #define NULL nullptr
                ^
[3/997] Building CXX object src/css/CMakeFiles/css-lib.dir/value.cpp.obj
FAILED: src/css/CMakeFiles/css-lib.dir/value.cpp.obj
D:\TDM-GCC-64\bin\c++.exe   -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_SKIA_BACKEND -DWINVER=0x0501 -D_UNICODE -D_WIN32_WINNT=0x0501 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src/. -I../src/.. -I../src/../third_party -Isrc/base -O2 -g -DNDEBUG -MMD -MT src/css/CMakeFiles/css-lib.dir/value.cpp.obj -MF src/css/CMakeFiles/css-lib.dir/value.cpp.obj.d -o src/css/CMakeFiles/css-lib.dir/value.cpp.obj -c ../src/css/value.cpp
In file included from ../src/./config.h:40:0,
                 from ../src/css/value.cpp:8:
D:/TDM-GCC-64/x86_64-w64-mingw32/include/wchar.h: In function 'wchar_t* wmemchr(const wchar_t*, wchar_t, size_t)':
../src/./base/base.h:17:16: error: 'nullptr' was not declared in this scope
   #define NULL nullptr
                ^
[4/997] Building CXX object src/css/CMakeFiles/css-lib.dir/style.cpp.obj
FAILED: src/css/CMakeFiles/css-lib.dir/style.cpp.obj
D:\TDM-GCC-64\bin\c++.exe   -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_SKIA_BACKEND -DWINVER=0x0501 -D_UNICODE -D_WIN32_WINNT=0x0501 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src/. -I../src/.. -I../src/../third_party -Isrc/base -O2 -g -DNDEBUG -MMD -MT src/css/CMakeFiles/css-lib.dir/style.cpp.obj -MF src/css/CMakeFiles/css-lib.dir/style.cpp.obj.d -o src/css/CMakeFiles/css-lib.dir/style.cpp.obj -c ../src/css/style.cpp
In file included from ../src/./config.h:40:0,
                 from ../src/css/style.cpp:8:
D:/TDM-GCC-64/x86_64-w64-mingw32/include/wchar.h: In function 'wchar_t* wmemchr(const wchar_t*, wchar_t, size_t)':
../src/./base/base.h:17:16: error: 'nullptr' was not declared in this scope
   #define NULL nullptr
                ^
[5/997] Building CXX object src/css/CMakeFiles/css-lib.dir/query.cpp.obj
FAILED: src/css/CMakeFiles/css-lib.dir/query.cpp.obj
D:\TDM-GCC-64\bin\c++.exe   -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_SKIA_BACKEND -DWINVER=0x0501 -D_UNICODE -D_WIN32_WINNT=0x0501 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src/. -I../src/.. -I../src/../third_party -Isrc/base -O2 -g -DNDEBUG -MMD -MT src/css/CMakeFiles/css-lib.dir/query.cpp.obj -MF src/css/CMakeFiles/css-lib.dir/query.cpp.obj.d -o src/css/CMakeFiles/css-lib.dir/query.cpp.obj -c ../src/css/query.cpp
In file included from ../src/./config.h:40:0,
                 from ../src/css/query.cpp:8:
D:/TDM-GCC-64/x86_64-w64-mingw32/include/wchar.h: In function 'wchar_t* wmemchr(const wchar_t*, wchar_t, size_t)':
../src/./base/base.h:17:16: error: 'nullptr' was not declared in this scope
   #define NULL nullptr
                ^
[6/997] Building CXX object src/clip/CMakeFiles/clip.dir/clip.cpp.obj
FAILED: src/clip/CMakeFiles/clip.dir/clip.cpp.obj
D:\TDM-GCC-64\bin\c++.exe   -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_SKIA_BACKEND -DWINVER=0x0501 -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0501 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src/. -I../src/.. -I../src/../third_party -Isrc/base -I../src/clip/. -O2 -g -DNDEBUG -MMD -MT src/clip/CMakeFiles/clip.dir/clip.cpp.obj -MF src/clip/CMakeFiles/clip.dir/clip.cpp.obj.d -o src/clip/CMakeFiles/clip.dir/clip.cpp.obj -c ../src/clip/clip.cpp
In file included from ../src/clip/clip.cpp:4:0:
../src/clip/clip.h:31:39: error: 'nullptr' was not declared in this scope
     lock(void* native_window_handle = nullptr);
                                       ^
../src/clip/clip.h:81:3: warning: scoped enums only available with -std=c++11 or -std=gnu++11
   enum class ErrorCode {
   ^
../src/clip/clip.h: In constructor 'clip::image::image()':
../src/clip/clip.h:122:41: error: 'nullptr' was not declared in this scope
     image() : m_own_data(false), m_data(nullptr) {
                                         ^
../src/clip/clip.h: In destructor 'clip::image::~image()':
../src/clip/clip.h:140:18: error: 'nullptr' was not declared in this scope
         m_data = nullptr;
                  ^
../src/clip/clip.cpp: In function 'bool clip::has(clip::format)':
../src/clip/clip.cpp:82:8: error: call to 'clip::lock::lock(void*)' uses the default argument for parameter 1, which is not yet defined
   lock l;
        ^
../src/clip/clip.cpp: In function 'bool clip::clear()':
../src/clip/clip.cpp:90:8: error: call to 'clip::lock::lock(void*)' uses the default argument for parameter 1, which is not yet defined
   lock l;
        ^
../src/clip/clip.cpp: In function 'bool clip::set_text(const string&)':
../src/clip/clip.cpp:98:8: error: call to 'clip::lock::lock(void*)' uses the default argument for parameter 1, which is not yet defined
   lock l;
        ^
../src/clip/clip.cpp: In function 'bool clip::get_text(std::__cxx11::string&)':
../src/clip/clip.cpp:108:8: error: call to 'clip::lock::lock(void*)' uses the default argument for parameter 1, which is not yet defined
   lock l;
        ^
../src/clip/clip.cpp: In function 'bool clip::set_image(const clip::image&)':
../src/clip/clip.cpp:130:8: error: call to 'clip::lock::lock(void*)' uses the default argument for parameter 1, which is not yet defined
   lock l;
        ^
../src/clip/clip.cpp: In function 'bool clip::get_image(clip::image&)':
../src/clip/clip.cpp:140:8: error: call to 'clip::lock::lock(void*)' uses the default argument for parameter 1, which is not yet defined
   lock l;
        ^
../src/clip/clip.cpp: In function 'bool clip::get_image_spec(clip::image_spec&)':
../src/clip/clip.cpp:152:8: error: call to 'clip::lock::lock(void*)' uses the default argument for parameter 1, which is not yet defined
   lock l;
        ^
[7/997] Building CXX object src/css/CMakeFiles/css-lib.dir/compound_style.cpp.obj
FAILED: src/css/CMakeFiles/css-lib.dir/compound_style.cpp.obj
D:\TDM-GCC-64\bin\c++.exe   -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_SKIA_BACKEND -DWINVER=0x0501 -D_UNICODE -D_WIN32_WINNT=0x0501 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src/. -I../src/.. -I../src/../third_party -Isrc/base -O2 -g -DNDEBUG -MMD -MT src/css/CMakeFiles/css-lib.dir/compound_style.cpp.obj -MF src/css/CMakeFiles/css-lib.dir/compound_style.cpp.obj.d -o src/css/CMakeFiles/css-lib.dir/compound_style.cpp.obj -c ../src/css/compound_style.cpp
In file included from ../src/./config.h:40:0,
                 from ../src/css/compound_style.cpp:8:
D:/TDM-GCC-64/x86_64-w64-mingw32/include/wchar.h: In function 'wchar_t* wmemchr(const wchar_t*, wchar_t, size_t)':
../src/./base/base.h:17:16: error: 'nullptr' was not declared in this scope
   #define NULL nullptr
                ^
[8/997] Building CXX object src/css/CMakeFiles/css-lib.dir/sheet.cpp.obj
FAILED: src/css/CMakeFiles/css-lib.dir/sheet.cpp.obj
D:\TDM-GCC-64\bin\c++.exe   -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_SKIA_BACKEND -DWINVER=0x0501 -D_UNICODE -D_WIN32_WINNT=0x0501 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src/. -I../src/.. -I../src/../third_party -Isrc/base -O2 -g -DNDEBUG -MMD -MT src/css/CMakeFiles/css-lib.dir/sheet.cpp.obj -MF src/css/CMakeFiles/css-lib.dir/sheet.cpp.obj.d -o src/css/CMakeFiles/css-lib.dir/sheet.cpp.obj -c ../src/css/sheet.cpp
In file included from ../src/./config.h:40:0,
                 from ../src/css/sheet.cpp:8:
D:/TDM-GCC-64/x86_64-w64-mingw32/include/wchar.h: In function 'wchar_t* wmemchr(const wchar_t*, wchar_t, size_t)':
../src/./base/base.h:17:16: error: 'nullptr' was not declared in this scope
   #define NULL nullptr
                ^
[9/997] Building CXX object src/clip/CMakeFiles/clip.dir/clip_win.cpp.obj
FAILED: src/clip/CMakeFiles/clip.dir/clip_win.cpp.obj
D:\TDM-GCC-64\bin\c++.exe   -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_SKIA_BACKEND -DWINVER=0x0501 -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0501 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src/. -I../src/.. -I../src/../third_party -Isrc/base -I../src/clip/. -O2 -g -DNDEBUG -MMD -MT src/clip/CMakeFiles/clip.dir/clip_win.cpp.obj -MF src/clip/CMakeFiles/clip.dir/clip_win.cpp.obj.d -o src/clip/CMakeFiles/clip.dir/clip_win.cpp.obj -c ../src/clip/clip_win.cpp
../src/clip/clip_win.cpp:294:19: warning: multi-character character constant [-Wmultichar]
   bi->bV5CSType = LCS_WINDOWS_COLOR_SPACE;
                   ^
In file included from ../src/clip/clip_win.cpp:4:0:
../src/clip/clip.h:31:39: error: 'nullptr' was not declared in this scope
     lock(void* native_window_handle = nullptr);
                                       ^
../src/clip/clip.h:81:3: warning: scoped enums only available with -std=c++11 or -std=gnu++11
   enum class ErrorCode {
   ^
../src/clip/clip.h: In constructor 'clip::image::image()':
../src/clip/clip.h:122:41: error: 'nullptr' was not declared in this scope
     image() : m_own_data(false), m_data(nullptr) {
                                         ^
../src/clip/clip.h: In destructor 'clip::image::~image()':
../src/clip/clip.h:140:18: error: 'nullptr' was not declared in this scope
         m_data = nullptr;
                  ^
../src/clip/clip_win.cpp: In constructor 'clip::{anonymous}::Hglobal::Hglobal()':
../src/clip/clip_win.cpp:33:24: error: 'nullptr' was not declared in this scope
   Hglobal() : m_handle(nullptr) {
                        ^
../src/clip/clip_win.cpp: In member function 'void clip::{anonymous}::Hglobal::release()':
../src/clip/clip_win.cpp:48:16: error: 'nullptr' was not declared in this scope
     m_handle = nullptr;
                ^
../src/clip/clip_win.cpp: In constructor 'clip::lock::impl::impl(void*)':
../src/clip/clip_win.cpp:73:9: error: 'ErrorCode' is not a class or namespace
       e(ErrorCode::CannotLock);
         ^
../src/clip/clip_win.cpp: In member function 'bool clip::lock::impl::set_image(const clip::image&)':
../src/clip/clip_win.cpp:305:15: error: 'uint32_t' does not name a type
         const uint32_t* src_x = (const uint32_t*)src;
               ^
../src/clip/clip_win.cpp:306:9: error: 'uint32_t' was not declared in this scope
         uint32_t* dst_x = (uint32_t*)dst;
         ^
../src/clip/clip_win.cpp:306:19: error: 'dst_x' was not declared in this scope
         uint32_t* dst_x = (uint32_t*)dst;
                   ^
../src/clip/clip_win.cpp:306:37: error: expected primary-expression before ')' token
         uint32_t* dst_x = (uint32_t*)dst;
                                     ^
../src/clip/clip_win.cpp:308:54: error: 'src_x' was not declared in this scope
         for (unsigned long x=0; x<spec.width; ++x, ++src_x, ++dst_x) {
                                                      ^
../src/clip/clip_win.cpp:309:20: error: expected ';' before 'c'
           uint32_t c = *src_x;
                    ^
../src/clip/clip_win.cpp:311:16: error: 'c' was not declared in this scope
             (((c & spec.red_mask  ) >> spec.red_shift  ) << out_spec.red_shift  ) |
                ^
../src/clip/clip_win.cpp:325:11: error: 'ErrorCode' is not a class or namespace
         e(ErrorCode::ImageNotSupported);
           ^
../src/clip/clip_win.cpp: In member function 'bool clip::lock::impl::get_image(clip::image&) const':
../src/clip/clip_win.cpp:347:9: error: 'ErrorCode' is not a class or namespace
       e(ErrorCode::ImageNotSupported);
         ^
../src/clip/clip_win.cpp:396:19: error: 'uint32_t' was not declared in this scope
       std::vector<uint32_t> palette(colors);
                   ^
../src/clip/clip_win.cpp:396:27: error: template argument 1 is invalid
       std::vector<uint32_t> palette(colors);
                           ^
../src/clip/clip_win.cpp:396:27: error: template argument 2 is invalid
../src/clip/clip_win.cpp:398:18: error: invalid types 'int[int]' for array subscript
         palette[c] =
                  ^
../src/clip/clip_win.cpp:417:23: error: expected primary-expression before ')' token
           *((uint32_t*)dst) = palette[idx];
                       ^
../src/clip/clip_win.cpp:417:24: error: expected ')' before 'dst'
           *((uint32_t*)dst) = palette[idx];
                        ^
../src/clip/clip_win.cpp: In member function 'bool clip::lock::impl::get_image_spec(clip::image_spec&) const':
../src/clip/clip_win.cpp:452:30: error: 'uint32_t' was not declared in this scope
         spec.red_mask   = *((uint32_t*)&bi->bmiColors[0]);
                              ^
../src/clip/clip_win.cpp:452:39: error: expected primary-expression before ')' token
         spec.red_mask   = *((uint32_t*)&bi->bmiColors[0]);
                                       ^
../src/clip/clip_win.cpp:453:39: error: expected primary-expression before ')' token
         spec.green_mask = *((uint32_t*)&bi->bmiColors[1]);
                                       ^
../src/clip/clip_win.cpp:454:39: error: expected primary-expression before ')' token
         spec.blue_mask  = *((uint32_t*)&bi->bmiColors[2]);
                                       ^
[10/997] Building CXX object src/cfg/CMakeFiles/cfg-lib.dir/cfg.cpp.obj
FAILED: src/cfg/CMakeFiles/cfg-lib.dir/cfg.cpp.obj
D:\TDM-GCC-64\bin\c++.exe   -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_SKIA_BACKEND -DWINVER=0x0501 -D_UNICODE -D_WIN32_WINNT=0x0501 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src/. -I../src/.. -I../src/../third_party -Isrc/base -O2 -g -DNDEBUG -MMD -MT src/cfg/CMakeFiles/cfg-lib.dir/cfg.cpp.obj -MF src/cfg/CMakeFiles/cfg-lib.dir/cfg.cpp.obj.d -o src/cfg/CMakeFiles/cfg-lib.dir/cfg.cpp.obj -c ../src/cfg/cfg.cpp
In file included from ../src/./config.h:40:0,
                 from ../src/cfg/cfg.cpp:8:
D:/TDM-GCC-64/x86_64-w64-mingw32/include/wchar.h: In function 'wchar_t* wmemchr(const wchar_t*, wchar_t, size_t)':
../src/./base/base.h:17:16: error: 'nullptr' was not declared in this scope
   #define NULL nullptr
                ^
In file included from ../src/./base/file_handle.h:11:0,
                 from ../src/cfg/cfg.cpp:13:
../src/./base/shared_ptr.h: At global scope:
../src/./base/shared_ptr.h:178:28: warning: explicit conversion operators only available with -std=c++11 or -std=gnu++11
   explicit operator bool() const { return (m_ptr != nullptr); }
                            ^
../src/./base/shared_ptr.h:121:23: error: 'nullptr' was not declared in this scope
   void reset(T* ptr = nullptr)
                       ^
../src/./base/shared_ptr.h: In constructor 'base::SharedPtr<T>::SharedPtr()':
../src/./base/shared_ptr.h:76:13: error: 'nullptr' was not declared in this scope
     : m_ptr(nullptr)
             ^
../src/./base/shared_ptr.h: In member function 'void base::SharedPtr<T>::reset(T*)':
../src/./base/shared_ptr.h:125:15: error: 'nullptr' was not declared in this scope
       m_ptr = nullptr;
               ^
../src/./base/shared_ptr.h: In member function 'void base::SharedPtr<T>::reset(T*, Deleter)':
../src/./base/shared_ptr.h:141:15: error: 'nullptr' was not declared in this scope
       m_ptr = nullptr;
               ^
../src/./base/shared_ptr.h: In member function 'base::SharedPtr<T>::operator bool() const':
../src/./base/shared_ptr.h:178:53: error: 'nullptr' was not declared in this scope
   explicit operator bool() const { return (m_ptr != nullptr); }
                                                     ^
../src/./base/shared_ptr.h: In member function 'void base::SharedPtr<T>::create_refcount(T*, Deleter)':
../src/./base/shared_ptr.h:198:20: error: 'nullptr' was not declared in this scope
       m_refCount = nullptr;
                    ^
ninja: build stopped: subcommand failed.`

**Comment by dacap** [comment]
It looks like the `cmake` command used your mingw installation instead of VS2015, you might try to remove mingw from the PATH or use `cmake -G "NMake Makefiles"` and then `nmake aseprite` instead of `ninja`

**Comment by ranmaru90** [comment]
Ahh I see. Alright. I've managed to compile. Thanks, sorry for the trouble.
