### ISSUE TITLE
Create config files in Library/Application Support on OS X

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1165]
Create configuration files in `~/Library/Application Support/Aseprite` instead of `~/.config` to avoid problems like [this one](http://steamcommunity.com/app/431730/discussions/2/405692224240874726/?ctp=2#c351660338681653738).

When the new folder is created for the very first time, we should migrate/copy the files inside `~/.config/aseprite/*.*`

**Comment by trollworkout** [comment]
@dacap  
![screen shot 2016-07-07 at 1 02 28 am](https://cloud.githubusercontent.com/assets/6987027/16643008/879a8a3a-43de-11e6-82e4-3804a7c6b911.png)

Open Folder from themes  still pointing to .config 😆 

Regardless thank you for this 👍

**Comment by dacap** [comment]
Ohh themes! your comment makes me remember that I've a patch for this UI that I forgot.

This UI requires a redesign. Themes should be separated between "official" and "user" themes, and the *Open Folder* button should be replaced with other buttons to open each theme folder, or official/user folders. Also we should be able to copy a theme to the "user" folder. I'll see if this can be available for v1.1.7.
