### ISSUE TITLE
Request: Vertically long layer panel

### ISSUE THREAD

**Issue by hepari** [aseprite/aseprite#1169]
Currently, it's not easy to work with many layers since the layers panel is fixed at the bottom of the screen and horizontally long.
Therefore I request a vertically long layer panel that could be positioned on the right end of the screen. (Much like the one found in Photoshop)
In conjunction with the much desired edition of a layer folder / group, this would improve the workflow immensely.

**Comment by dacap** [comment]
Related to #518 and #1052

**Comment by lrtvri** [comment]
it'd be great to see all the layers at the same time. (even with folder group enhancement) Maybe multiple screen layout definition, one for sprite editing - with long vertical layer panel on the right side - and another one for animation (as the current layout)

**Comment by dacap** [comment]
Hi @lrtvri! You gave me a simple idea for a first draft of this feature. I'll be try to add something really simple for next v1.1.

**Comment by dacap** [comment]
![timeline-position](https://cloud.githubusercontent.com/assets/39654/18552508/1517f358-7b33-11e6-85c1-538e77340c83.gif)

**Comment by lrtvri** [comment]
Looks amazing :)
