### ISSUE TITLE
Diagonal symmetry

### ISSUE THREAD

**Issue by panteleevnikita** [aseprite/aseprite#1171]
Just what the tittle says, it's pretty easy to make a matrix symmetrical (both 90° and 270°), and when the line is moved from the middle, simply reduce the working part of the matrix (without rotating the diagonal). Should be only aviable for NxN images(?)

Sorry if i said something stupid. Thanks for your attention.

**Comment by dacap** [comment]
Related: [this discussion](https://github.com/aseprite/aseprite/issues/874#issuecomment-159580476)

**Comment by oceanhahn** [comment]
Woah, why was this closed? o.o
Did it get put into a beta branch or something?

**Comment by dacap** [comment]
It shouldn't have been closed, but maybe @panteleevnikita wanted to close it.

**Comment by oceanhahn** [comment]
I guess so. :1 
I would still like to see diagonal/angular symmetry. Should I open a new issue, or just leave it be?

**Comment by dacap** [comment]
I'll reopen this one

**Comment by oceanhahn** [comment]
Cool, thanks!

I thought I had seen another post about angular symmetry, but it would be great to see at least ±45° mirroring, if a rotatable plane is too much to consider. :D

**Comment by marath007** [comment]
the 45 degrees would be really fun. And it should be easy enough to do, swap X and Y

**Comment by lagurtzky** [comment]
I see this is still open, but would really like to see this feature added. Looks like this issue was dropped dead in the water with no updates. Is there a way to get more attention on adding support for this? A 45 degree diagonal symmetry seems very doable, and would be incredibly value for making pixel art, as a ton of stuff is made with this symmetry in mind.

**Comment by Sergey5588** [comment]
still waiting

**Comment by dacap** [comment]
This will be available in the beta version with #4669
