### ISSUE TITLE
Add option to transform/scale/rotate several cels at the same time

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1172]
Requested in the Community site too: https://community.aseprite.org/t/scaling-multiple-frames-simultaneously/240

**Comment by leegrey** [comment]
Hello @dacap :) 

I too would really love to see this feature in a future version of Aseprite. It would be very beneficial to be able to move, cut and paste, or otherwise transform a selection across multiple layers. 

As an example, when designing a level with multiple layers, I often want to move a room or other area to another location. Say there is a background layer, a props layer, and a foreground layer, I need to repeat the work three times.  Being able to transform multi-layer selections would be an incredible productivity boost.

Thanks!

**Comment by zhengying** [comment]
Any update on this feature? Can't wait to see it in future release!

**Comment by dacap** [comment]
This will be available in the next version v1.2.14.

**Comment by josephernest** [comment]
Hi @dacap, I have seen you have implemented https://github.com/aseprite/aseprite/commit/3e478d3efa745789cbc054c767947bc9c2a6c3e7

how do you actually use this feature to resize all frames ?

Is there a key shortcut or menu item or something else?

What I've tried:

* Marquee tool (M), select all (CTRL+A)
* click on frame 1, keep SHIFT pressed, click on frame 10
* then the 10 frames are selected
* drag the corner of the marquee selection

Unfortunately this has effect only on the current sprite and not **all** frames.

Any idea? Thanks!

**Comment by dacap** [comment]
Hi there @josephernest, did you try:

1. selecting the whole canvas Ctrl+A
2. select all the frames (click first frame and drag the cursor to the last frame, without pressing shift, or other key)
3. transform the selection

Demo: https://twitter.com/aseprite/status/1170007034651172866

**Comment by josephernest** [comment]
Thank you very much!

My mistake was to hold SHIFT while selecting all the frames.

I did : click [1], hold SHIFT, click [10]. Then the transform did not work for all frames.

Now I realize I have to do: click [1] and *drag mouse* to [10].

Thanks @dacap !

**Comment by dyordan1** [comment]
> Hi there @josephernest, did you try:
> 
> 1. selecting the whole canvas Ctrl+A
> 2. select all the frames (click first frame and drag the cursor to the last frame, without pressing shift, or other key)
> 3. transform the selection
> 
> Demo: https://twitter.com/aseprite/status/1170007034651172866

Is it possible there's been a regression introduced to this functionality at some point? I'm following the demo steps exactly and I only move the bottommost layer by following those steps in 1.2.27-x64 (on Steam).

**Comment by Fyscuit** [comment]
> Is it possible there's been a regression introduced to this functionality at some point? I'm following the demo steps exactly and I only move the bottommost layer by following those steps in 1.2.27-x64 (on Steam).

I thought it wasn't working as well, but it seems the preview shows only your current selected layer and it applies to all layers after you confirm pressing Enter. That's how it worked for me also in version 1.2.27, give it a try
