### ISSUE TITLE
Can't cross compile Aseprite Linux -> Windows

### ISSUE THREAD

**Issue by xSke** [aseprite/aseprite#1173]
I'm trying to cross compile Aseprite from Linux to Windows. It always fails around 500 items in with a quite large error:

![Error](http://i.imgur.com/Yazbzx7.png)

I'm using the Toolchain-mingw.cmake from this repo with the paths switched out to match my install (i686-w64-mingw32-gcc). Is this a bug in your cmake setup or am I doing something wrong?

**Comment by dacap** [comment]
Hi @xSke, MinGW isn't supported. Only Visual Studio 2015 is used to compile the Windows version (I think MinGW isn't supported on Skia too).

**Comment by flamendless** [comment]
Whats the command @xSke ? How do you configure your linux cmake to output binaries for windows?
