### ISSUE TITLE
CLI multiple layers

### ISSUE THREAD

**Issue by davidtme** [aseprite/aseprite#1174]
Is there a way via the CLI to import multiple layer such as:

```aseprite.exe -b --layer "Post" --layer "Left" fence.ase --save-as fence-left.png```

or

```aseprite.exe -b --layer "Post,Left" fence.ase --save-as fence-left.png```

**Comment by dacap** [comment]
Hi @davidtme, not at this moment, but I'll try to add this to v1.2.

**Comment by dacap** [comment]
This will be released on v1.2-beta2
