### ISSUE TITLE
Feature request: change brush size with hotkey+mouse wheel

### ISSUE THREAD

**Issue by darthdeus** [aseprite/aseprite#1176]
Given that pixel art seems to be done with mouse a lot more than regular sketching, it would be nice to have a quick way to change brush size, much like graphical tablets sometimes have specialized circular buttons for this.

It would be nice if we could have something like shift/ctrl + mouse wheel change the brush size.

**Comment by trollworkout** [comment]
Usually [ and ] are used to change brush size on the fly in most programs. Sometimes even 1 ... 0

**Comment by darthdeus** [comment]
> Usually [ and ]are used to change brush size on the fly in most programs. Sometimes even 1 ... 0

You can do that by changing the keybindings. The reason why I created this issue is because you can't set a keybinding for the mouse wheel to do the same.

**Comment by dacap** [comment]
See #970
