### ISSUE TITLE
open .png as tab

### ISSUE THREAD

**Issue by alivegames** [aseprite/aseprite#1178]
i want to use aseprite as my default image editor, 
when i open .png file, it always open new instance window. open .ase file is fine.
how i can open .png as a tab?

**Comment by dacap** [comment]
Hi @alivegames, are you on Windows?

**Comment by alivegames** [comment]
yes, i am using windows. @dacap

**Comment by dacap** [comment]
You can use `regedit` and set `HKEY_CLASSES_ROOT\.png` default value to `AsepriteFile` (you can check `HKEY_CLASSES_ROOT\.ase` to see an example). I can record you a little video-tutorial in a couple of days in case you don't know how to edit the registry with `regedit`.

**Comment by alivegames** [comment]
@dacap Oh it works like magic, you are awesome! thanks!

**Comment by dacap** [comment]
You're welcome 😉
