### ISSUE TITLE
Linux preview window graphical tiling/repeating issue and low mouse FPS

### ISSUE THREAD

**Issue by whitephoenix0** [aseprite/aseprite#1181]
I compiled aseprite on my debian stretch desktop running xfce to try aseprite before I buy it from steam. It all seems to work  pretty well so far, except for two issues. 
1. Low mouse FPS, when I move my mouse over aseprite it seems to move at about 5 FPS, which seems really strange. Using native cursor setting did not help and actually caused weird jittering.
2. http://i.imgur.com/bhIu8zp.png When moving the preview window, it causes this tiling and repeating graphical glitch. This makes it very hard to position the preview window.

I'm not really sure what other information I can give that would be useful or relevant, so feel free to request more info if needed.

**Comment by dacap** [comment]
The second issue is duplicated from #1006. For the mouse lag you can check this issue #957

**Comment by whitephoenix0** [comment]
@dacap I actually had that mouse problem earlier, which is why I compiled it. Now it doesn't drift or slide but just has really low fps and looks choppy, so I think it's a different problem.

I'll have to wait for the skia-backend for Linux to fix the other one.

**Comment by dacap** [comment]
Please follow #1006
