### ISSUE TITLE
Aseprite CLI - Texture atlas from several files not working on windows

### ISSUE THREAD

**Issue by JosefKuchar** [aseprite/aseprite#1184]
Hello,
I'm trying to create texture atlas from serveral files on windows, but I'm console throw this error:```
 File not found: "C:\Users\Josef\Documents\Projects\Isogame\app\assets\img\*.ase"
No documents to export
``` my command is : `aseprite -b *.ase --data blocks.json --sheet blocks.png --sheet-width 42 --sheet-height 42`

**Comment by dacap** [comment]
Hi @JosefKuchar this problem was already reported here: #1049, I'll try to find a solution for next v1.1.6

**Comment by JosefKuchar** [comment]
How can i do it without this feature on windows?

**Comment by dacap** [comment]
There are some methods like this one: http://superuser.com/a/460648/85654

Anyway I'll release a new version soon with the fix.

**Comment by dacap** [comment]
@JosefKuchar please give a try to the new v1.1.6 to check if it fixes this issue

**Comment by JosefKuchar** [comment]
Ok, will compile it

**Comment by JosefKuchar** [comment]
@dacap Same problem, i'm using allegro backend, it's fixed only in skia? Btw.: I was compiled aseprite from master branch

**Comment by dacap** [comment]
@JosefKuchar it's only fixed on the skia back-end (as the fix needs a special `WinMain` function)

**Comment by JosefKuchar** [comment]
@dacap Ok, I will compile it with skia
