### ISSUE TITLE
Add quad symmetry (horizontal/vertical at the same time)

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1190]
Source: https://twitter.com/TheActualRiz/status/751393552924565508/photo/1

Related to #1171 to improve the symmetry selection UI.

**Comment by SolarLune** [comment]
Hey, I just popped up to ask this, too. You could just not have the existing symmetry buttons cancel each other out, rather than adding another button (in case that was how you were thinking of doing it).

**Comment by thezakman** [comment]
Will this be added?

**Comment by dacap** [comment]
@thezakman yes, this will be available on v1.2.
