### ISSUE TITLE
Future request / Fix - Export Layers to sprite sheet

### ISSUE THREAD

**Issue by HarrievG** [aseprite/aseprite#1192]
When exporting to a sprite sheet you have the ability to select specific layers or all. 
If you select Visible Layers, the layers will get merged and the sprite sheet will only create new entries for each frame.

But when you draw a character, and draw the eyes on a separate layer, and export it to a sprite sheet, there is now no possibility to have those eyes in a separate entry in the sprite sheet.

The only way to work around this is to export the eye-layer and then merge the sprite sheets by hand.. 

I would suggest to add an "**Unique entries for Discontinuous Layers"** checkbox whenever the "**Visible Layers" / "Selected Layers**" option is selected from the drop down .

With this you can create a sprite sheet with all the eyes as separate entries, you can for example pack different eyes within one sprite sheet, and using the frames just for different colors and layers for different shapes, without to have to export the WHOLE sprite just for a new set of eyes.
This allows for more versatile and optimized options when using the sprite assets in your game.

**Comment by dacap** [comment]
Hi @HarrievG, I think you are looking for [the `--split-layers` option from the CLI](http://www.aseprite.org/docs/cli/#split-layers) when a sprite sheet is generated with the [`--sheet`](http://www.aseprite.org/docs/cli/#sheet) option. There is no UI yet for this. And this might be related to #126 and #901
