### ISSUE TITLE
Auto-outline the current selection

### ISSUE THREAD

**Issue by astraldata** [aseprite/aseprite#1198]
Basically, a command that will put an outline of pixels of the currently selected color around all the non-transparent pixels in the current selection. 

The option would exist to put the outline around the perimeter of the opaque pixels, or inset them by 1 pixel on top of the opaque pixels, essentially drawing the outline over, say, a silhouette. 

One could then take the pen tool and fill in the line-art details inside the silhouette, taking one of the most tedious issues of drawing without lineart out of the equation for good, as most smaller sprites, even if they require outlines, must be drawn without them as flat colors first -- and then shaded. Having the lines generated for us that we'll inevitably put in ourselves would be a godsend!

**Comment by astraldata** [comment]
Allowing the auto-outline command to be applied automatically across all frames would make this perfect for animators who use the silhouette technique to animate with.

**Comment by KasumiArai** [comment]
You can do this using the convolution matrix's outlining with a few caveats. Mainly only RGB mode. (It's finicky in indexed) It uses black, not the current color and is put a pixel outside not inset. Still, check it out. 
![autooutline](https://cloud.githubusercontent.com/assets/8582123/16817714/1dad4cf0-4912-11e6-9120-aa471393bea3.gif)

**Comment by dacap** [comment]
See #371
