### ISSUE TITLE
Replace currently selected Palette index w/current pen color

### ISSUE THREAD

**Issue by astraldata** [aseprite/aseprite#1202]
Basically, I change colors on my pen, then select an index in the palette I want to replace, and click a button to replace that index with the newly selected color (that, or an HSL slider would be nice).

It would be awesome to be able to use the regular color picker to instantly preview the change to the index instantly though across the entire sprite. Graphics Gale does this automatically for indexed colors -- you just select the color entry in the sprite or palette, slide the color-picker to the one you want, and the sprite is updated in realtime with the new color. I know you can do this with the provided sliders in sort of a roundabout way, but there's no HSL slider (in which I work with), and why can't we just use the regular Asesprite Photoshop-like color-pickers for this anyhow? It's a lot more intuitive and works great, plus you don't have to click a button just to select a new color for the current palette index -- you just pick it...

**Comment by dacap** [comment]
See #1102

Actually we've a way to view real-time color changes on Indexed images using the palette editor (F4) with the HSB slider:

![realtime-update](https://cloud.githubusercontent.com/assets/39654/16839617/6d21841a-49a6-11e6-8f46-a513fb01fba0.gif)

But the problem as you said is that we cannot use the Photoshop-like color selector. On #1102 we should provide an unified way to select color *and* change palette color.
