### ISSUE TITLE
Grid Settings and Import Sprite Sheet are Inconsistently Aligned

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1207]
A small UI thing, but it got me earlier today. 
![pcuavtw](https://cloud.githubusercontent.com/assets/8582123/17048264/924dbea4-4fb2-11e6-89e8-2ba2350b6431.png)
The fields for X and Y are horizontally aligned on grid settings, and vertically aligned on Import Sprite Sheet.
The preferred way is the horizontal grid settings arrangement.

Slightly related, it'd be nice if import sprite sheet had a "use grid" button. I found this while manually keying grid values only to realize the locations of the fields didn't match.

**Comment by dacap** [comment]
> Slightly related, it'd be nice if import sprite sheet had a "use grid" button. I found this while manually keying grid values only to realize the locations of the fields didn't match.

The default values in Import Sprite Sheet might be the active grid values.
