### ISSUE TITLE
Some usability problems

### ISSUE THREAD

**Issue by paulguy** [aseprite/aseprite#1213]
Not specifically a bug but more of a series of events that made a task unnecessarily difficult.

I had an indexed PNG I wanted to edit, so I loaded it up which worked fine, but I wanted to enlarge the canvas and have transparency filling in the extra space.  However this program seems to really go against me at every point in trying to accomplish this.

I've tried filling with a transparent color and using the rectangle tool with a transparent color, but I guess colors are alpha blended, which is fair enough and generally the expected behavior for most graphics applications.  I tried using the eraser but the background layer is "special" for that so you can't just erase away opaque pixels to make them transparent.  I tried creating a transparent layer then moving it beneath the background so maybe it'd let me do something then but the background is special and can't have stuff moved under it (And moving layers versus selecting multiple layers isn't the most obvious thing.).  I then tried duplicating the background and removing the existing background which does work and removes the special background characteristics, but then for some reason color index 0 becomes transparent pixels, so I then need to fix that but overall it's just too much work that isn't actually doing any drawing.

Useful program otherwise, and I enjoy using it, but this particular situation was rather obnoxious and made me just have to use something else.  Maybe there was a way to do what I want, but I couldn't figure it out.

**Comment by KasumiArai** [comment]
A layer can be a background or a layer. "Layer" layers can be transparent, "Background" layers can't. Right click the background layer and select "Layer from B ackground"

**Comment by dacap** [comment]
Hi @paulguy, it's as @KasumiArai said.

On Aseprite (as on Photoshop) you can have a special "Background" layer (and just one) in the sprite, which doesn't allow transparent pixels. In case you want transparent pixels, you need to convert the background to a regular layer (using *Layer > Layer from Background* option, or right-clicking as @KasumiArai said).

You can find more information here: http://www.aseprite.org/docs/layers/#background-layer
