### ISSUE TITLE
Moving an entire linked layer by selection destroys it.

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1214]
Create a new linked, non background layer.
Change layer mode to continuous.
Draw something small in it.
Make some new frames. (alt+N, rather than alt+B)
Select all active pixels in the layer and move them.
The frame you are on is unlinked, and all linked frames are now blank.
Deselect.
GIF:
![layerdestroy](https://cloud.githubusercontent.com/assets/8582123/17275381/9e942c66-56d3-11e6-8758-817d96cea34e.gif)
Moving with the move tool is a workaround but it's still a bug, I think.
Aseprite v1.2-beta1 on Windows Vista 32bit

**Comment by dacap** [comment]
The same problem is present in the following cases too:

1. when we delete the cel using `Ctrl+A` and then `Delete` key.
1. or we select all `Ctrl+A` and cut the selection `Ctrl+X`
1. or if we flip an empty area and it delete the whole cel content. 

Internal note: everything that uses `cmd::TrimCel` might generate this bug.

**Comment by dacap** [comment]
The only "bad" side of fixing this issue is that deleting the whole content of a cel (i.e. when the cel is empty), all linked cels will be deleted with it. For example, if we use `Ctrl+A` and `Ctrl+X` to cut the whole cel content, all links will disappear.
