### ISSUE TITLE
Drawing on multiple frames at the same time

### ISSUE THREAD

**Issue by DaanHaaz** [aseprite/aseprite#1215]
I don't know if any other tools have such feature. I don't know if this would even be possible. But I thought I'd suggest it anyway.

Simply put, I would like to be able to edit my art in such way that it's as if I'm editing all frames at the same time. So if I put a red pixel on the left upper corner of my frame, a red pixel will appear on all frames of that animation. I think this would be useful for animations with stationary parts that you quickly want to edit. And maybe not only drawing but also moving selected parts.

I'm not sure how much work it would be to make this happen. So maybe the effort/benefit isn't worth it and in that case feel free to toss the idea.

**Comment by zed9h** [comment]
Take a look at [linked cels](http://www.aseprite.org/docs/linked-cels/), this with [layers](http://www.aseprite.org/docs/layers/) may do what you want.

**Comment by dacap** [comment]
Hi @DaanHaaz, as @zed9h, linked cels is the way to modify several pixels in several frames at the same time. Linked cels are created in [continuous layers](http://www.aseprite.org/docs/continuous-layers/), originally from #99
