### ISSUE TITLE
Request: Open Sprite In Existing Window

### ISSUE THREAD

**Issue by SolarLune** [aseprite/aseprite#1217]
It'd be nice to have Aseprite open a sprite in a currently opened window if one already exists, rather than opening a new instance of Aseprite when you open an image from the file manager with Aseprite.

**Comment by dacap** [comment]
Hi @SolarLune, actually Aseprite opens sprite in the current instance (at least on Windows and OS X). What OS are you using? what Aseprite version?

**Comment by SolarLune** [comment]
Linux Mint 17.3, Aseprite version 1.1.5.7. The file manager's the default - Nemo, 2.8.7.

**Comment by dacap** [comment]
I've just reopen #477 to add Linux support
