### ISSUE TITLE
Clicking dialog button after first time without moving mouse does nothing

### ISSUE THREAD

**Issue by numanair** [aseprite/aseprite#1221]
Repro:
1. Open and edit multiple files
2. Close first file with keyboard shortcut. Click "Don't save".
3. Without moving the mouse, repeat step 2 for the second file.

Expect:
Second file is not saved and is closed.

Actual:
No action.

This seems related to issue #826.

**Comment by dacap** [comment]
Hi @numanair, what OS are you using? Windows? Linux? or OS X?

**Comment by numanair** [comment]
I'm using Windows 10 with build 1.1.8-dev

**Comment by dacap** [comment]
Did you compile it with the Allegro back-end or Skia back-end?

**Comment by numanair** [comment]
With the Skia back-end.
