### ISSUE TITLE
Problems building aseprite

### ISSUE THREAD

**Issue by a00958821** [aseprite/aseprite#1227]
Describe your bug report or feature request here

after making directory build and running "`cmake -DCMAKE_INSTALL_PREFIX=~/software -G Ninja ..`" i get the following:

> mena@menaMachine:~/aseprite/build$ cmake -DCMAKE_INSTALL_PREFIX=~/software -G Ninja ..
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> CMake Error:
>   The detected version of Ninja () is less than the version of Ninja required
>   by CMake (1.3).
> 
> 
> CMake Error: Internal CMake error, TryCompile generation of cmake failed
> -- Check for working C compiler: /usr/bin/cc -- broken
> CMake Error at /usr/local/share/cmake-3.6/Modules/CMakeTestCCompiler.cmake:61 (message):
>   The C compiler "/usr/bin/cc" is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>    
> 
>   
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:38 (project)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/mena/aseprite/build/CMakeFiles/CMakeOutput.log".
> See also "/home/mena/aseprite/build/CMakeFiles/CMakeError.log".

my cmake version:

> mena@menaMachine:~/aseprite/build$ cmake -version
> cmake version 3.6.1
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> 

my ninja version:

> mena@menaMachine:~/aseprite/build$ ninja -h
> usage: ninja [options] [targets...]
> 
> if targets are unspecified, builds the 'default' target (see manual).
> 
> options:
>   --version  print ninja version ("1.5.1")
> 

im using ubuntu 16.04 btw

please help

### Aseprite and System version

* Aseprite (version number, installer/portable/Steam/beta/dev):
* System (Win/OSX/Linux, version, distribution):

**Comment by dacap** [comment]
It looks like cmake isn't detecting the ninja version, it says `The detected version of Ninja () is less than the version of Ninja required by CMake (1.3)`, the ninja version should be inside the parenthesis `()`.

**Comment by a00958821** [comment]
can i do something about it?

**Comment by dacap** [comment]
You might try to download the [latest ninja release](https://github.com/ninja-build/ninja/releases) and try compiling Aseprite again in a new/fresh/clean/empty `build` dir.

**Comment by dacap** [comment]
@a00958821 did the latest ninja version fix this issue?

**Comment by h0rdak** [comment]
I also ran into this, for posterity this was due to a bug in cmake

"if previously build dir already configured , but ninja executable is moved, cmake didn't report command not found ,but reports "The detected version of Ninja ("") is less than the version of Ninja required by CMake ("1.3") which is confused."

https://gitlab.kitware.com/cmake/cmake/issues/16378

**Comment by reveriel** [comment]
Thanks, I also ran into this.

I  used an out-dated ninja, and didn't clear the build dir after installed the new version.
Clear the build dir fix the problem.
