### ISSUE TITLE
Paste Buffer error from odd width screenshots

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1229]
On windows, if you press alt+printscreen it copies only that window to the buffer. Aseprite seems to fail with clips of an odd width when this is done. 

1. Press alt+printscreen.
2. Press ctrl+N on Aseprite. Make sure the width is odd. If even, resize the window and start from step 1.
3. Press enter.
4. Paste the image.

It will look like this:
![4w2xyb8](https://cloud.githubusercontent.com/assets/8582123/17562055/fa08be06-5ef6-11e6-9590-a9092735dad9.png)

### Aseprite and System version

* Aseprite v1.2-beta1 Steam
* Windows Vista 32Bit

**Comment by zed9h** [comment]
I could not reproduce on Windows 10 64-bit with a 32-bit color display, using the latest from git.

**Comment by dacap** [comment]
@KasumiArai Are you on a 16-bit screen resolution?

**Comment by KasumiArai** [comment]
Ah. Indeed I was on 16bit color, sorry. I use it less than before these days, didn't think I was.

**Comment by dacap** [comment]
I'll take a look at this issue tomorrow

**Comment by dacap** [comment]
I was able to reproduce the issue, I'll take this one.

**Comment by KasumiArai** [comment]
Thanks! It is not lost on me how much of an edge case this is, and I appreciate you taking the time to fix it.

**Comment by dacap** [comment]
@KasumiArai you're welcome! these bug reports related to clipboard issues are of great help to improve the [clip](https://github.com/aseprite/clip) open source project (which can be used by other developers, so it's nice to be able to test the code in different environments). So basically, thank you! 😄
