### ISSUE TITLE
Include alternate color picker (request)

### ISSUE THREAD

**Issue by kyrieru** [aseprite/aseprite#1231]
Would it be possible to add a color picker similar to this one?
https://i.gyazo.com/5948fc891c29dd12f005d91ee3d70d6f.mp4

Sounds like a small thing, but of all the color pickers I've used, that's the one that simplifies choosing colors the most, and without it I find my workflow slowing down a lot. The way it lays out colors makes it really easy to choose a color, and then find variations of hue and saturation visually, whereas with Aesprite's it always feels a bit more like trial and error, personally.

It's in Game Maker, but I think it was the one in MSpaint, as well. Again, sounds small, but it would make all the difference in the world to me.

Anyhow, keep up the great work.

**Comment by dacap** [comment]
Related to #707 and #1102

**Comment by dacap** [comment]
This will be available in the next release.
