### ISSUE TITLE
Invalid Selection After Removing Frames + Undo Error Due to Invalid Selection

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1235]
Describe your bug report or feature request here
(Edit: Greatly simplified steps after iterating different ways to try this)
Hah. This one took a bit to figure out. If you click and drag to select frames starting in a left to right motion (that is, selecting frames with a greater number than the one first clicked) and then reverse directions (that is, selecting frames with a smaller number than the one first clicked) while still holding the mouse button down, the selection will not be removed on delete. You can then delete again with an invalid range, and undoing sometimes resets the exposure time to 1ms (among other quirks.)

1. Open Aseprite
2. Open this gif:
![testframeselectiongif](https://cloud.githubusercontent.com/assets/8582123/17749854/838fea96-648d-11e6-9d13-04205b3849dc.gif)
3. Click and drag starting at frame 8, mouse your mouse to frame 9. DO NOT RELEASE CLICK
4. Move your mouse to frame 2.
5. Release click.
4. Remove frames. (Bug one, the selection stays active and is greater than the available frames.)
5. Remove frames. 
6. Undo. (Bug two, the previous action is not properly undone. There are now empty cels.) 
7. Undo again. (Continuation of bug two. The animation now has 15 frames instead of 9. Frame 9 now has 1ms delay instead of 200)
![frameselectionerror3](https://cloud.githubusercontent.com/assets/8582123/17749990/1c59f41a-648e-11e6-9513-8c3ab43f6c26.gif)

(It occasionally leaves the selection when selecting right to left without starting to go left to right first. I cannot get this happen to consistently, but I'm noting it to look out for while looking into the code)

### Aseprite and System version
Aseprite  v1.2-beta1-Steam on Windows Vista 32bit

**Comment by dacap** [comment]
Thanks for this bug report @KasumiArai, I'm just modifying these operations for v1.2 (with layers groups). I think it will need a special patch for v1.1 anyway.
