### ISSUE TITLE
paint bucket filling in everything

### ISSUE THREAD

**Issue by XninjauchihaX** [aseprite/aseprite#1237]
i have looked in a few places to try to see what button combination i might have hit or what i might have changed, but couldnt find anything about the bucket paint tool. 

whenever i try to use the paint bucket inside something i have drawn, it paints the entire canvas. the objects are closed and ive even tried filling in the rectangles from the rectangle tool. if there is a link someone can send me with the answer that will work.

thanks.

p.s. its driving me crazy and uninstalling and deleting all files did not reset it.

Aseprite current steam version no betas. and windows 7 64.

**Comment by dacap** [comment]
Hi there, you've to enable the "Contiguous" checkbox:
![fill](https://cloud.githubusercontent.com/assets/39654/17910129/f903334e-695d-11e6-8991-c22162b8e6a6.gif)

**Comment by KasumiArai** [comment]
It could also be tolerance: 
![tolerance](https://cloud.githubusercontent.com/assets/8582123/17910209/e2bfc956-6955-11e6-9fb1-032e2553a149.gif)

**Comment by XninjauchihaX** [comment]
Thank you so much for the help. I was going crazy.
