### ISSUE TITLE
move selection across multiple layers

### ISSUE THREAD

**Issue by Cerno-b** [aseprite/aseprite#1238]
When using the move tool, it is generally possible to move multiple selected layers at the same time.

It seems that this is not possible with selections (Lasso, Marquee). When trying to move the selection, Aseprite forgets that multiple layers had been selected. This is not only true for moving, but also selecting itself, scaling and rotating.

This would be a useful feature when modelling characters made out of body parts since usually when rotating an upper arm, you want the lower arm to be rotated along with it. Using the select-rotate function with an rotation center at the should joint across multiple layers would be immensely useful for this task.
### Aseprite and System version
- Aseprite (version number, installer/portable/Steam/beta/dev): 1.1.7 (Steam)
- System (Win/OSX/Linux, version, distribution): Win7 x64

**Comment by dacap** [comment]
Related to #1172
