### ISSUE TITLE
Save Palette As PNG Destroys First Palette Entry

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1239]
1. Copy some image.
2. Create a new Aseprite document.
3. Paste it in.
4. Create Palette from Current Sprite with 16 colors
5. Save palette. 
6. Open the save palette. 

The first color is replaced by transparency.

Edit: I suppose you can restore it by making the layer a background, changing the alpha for the first index back to 255. It still is not exporting as expected, of course.

Aseprite v1.2-beta1 Steam on Windows Vista 32bit.

**Comment by dacap** [comment]
I've found this error message too (maybe because the palette is too small):

![screen shot 2016-09-12 at 12 35 25 pm](https://cloud.githubusercontent.com/assets/39654/18442009/7ad49a48-78e5-11e6-988a-c3653bb7ee87.png)

I'll fix this right now.
