### ISSUE TITLE
Combining --trim and --sheet-pack with --border-padding, --shape-padding and/or --inner-padding

### ISSUE THREAD

**Issue by jameswilddev** [aseprite/aseprite#1240]
Hello.

Is it possible to combine --trim and --sheet-pack with --border-padding, --shape-padding or --inner-padding when invoking the CLI?

I am testing with the following .ase:

[player.zip](https://github.com/aseprite/aseprite/files/445523/player.zip)

Using the following to try and pack frames as nearly as possible but have 1px between each border:

aseprite --batch --trim --sheet-pack --shape-padding 1 --border-padding 1 --sheet player.png player.ase

![player](https://cloud.githubusercontent.com/assets/3138458/18100204/e30302ac-6ee1-11e6-82aa-cce844ccfe91.png)

As seen, this has dropped the --border-padding and --shape-padding options; we get bleed in-engine around the edges.

Dropping only the --sheet-pack option re-enables padding, but as the sheet isn't well packed on many sprites we lose a lot of texture memory and on some platforms brush up against texture size limits.

aseprite --batch --trim --shape-padding 1 --border-padding 1 --sheet player.png player.ase

![player](https://cloud.githubusercontent.com/assets/3138458/18100341/72663a36-6ee2-11e6-90e4-35dbf8699f76.png)

Is there a way to combine these behaviours, such as this?

![player](https://cloud.githubusercontent.com/assets/3138458/18100442/f757b206-6ee2-11e6-8583-a120843b6d26.png)

Thank you.

**Comment by dacap** [comment]
@jameswilddev at this moment padding doesn't work when we pack the sheet. I'll see if I can do something about this issue.

**Comment by jobtalle** [comment]
I'm currently in dire need of this feature. If it's not in the pipeline, can someone point me towards the class where this should be implemented? If I find the time I can try to fix it & submit a pull request.

**Comment by Nuuf** [comment]
I've written a little tool you can use in the meantime https://github.com/Nuuf/aseprite-packer
Basically you first export with aseprite and then if you need padding and/or border you can use this tool to add that. Has a CLI so you can combine the two.

Feel free to ask me any questions of you can't get it working.

**Comment by dacap** [comment]
Fixed by @kawa-yoiko with #2045
