### ISSUE TITLE
Using "hand" after selection merges selected area

### ISSUE THREAD

**Issue by saint11** [aseprite/aseprite#1241]
Here's an example:
![Example](http://i.imgur.com/QF1j6mW.gif)

### Aseprite and System version
* Aseprite: Steam/Beta
* System: Win

**Comment by dacap** [comment]
I'll try to take a look at this issue for next release (which I hope to release this week).

As a side note: I think this bug is a recurrent "regression" (a bug that re-appear time by time). I'll start preparing a testing suite to avoid this kind of regression. Thanks for reporting!
