### ISSUE TITLE
docs/files/ase.txt - Update documentation that CEL position is a 16-bit signed word

### ISSUE THREAD

**Issue by iamPHEN** [aseprite/aseprite#1246]
https://github.com/aseprite/aseprite/blob/master/docs/files/ase.txt

Currently, Cel position (x, and y) is documented as: `WORD - A 16-bit unsigned integer value`. This isn't quite 100% accurate as it should read as `SIGNED WORD - A 16-bit **signed** integer value`.

There was mention of this in Issue #582, but I don't quite see a follow up to it. (maybe I'm reading the wrong file spec?)

### Aseprite and System version

* Aseprite (version number, installer/portable/Steam/beta/dev): v1.1.7
* System (Win/OSX/Linux, version, distribution): any

**Comment by dacap** [comment]
Hi @iamPHEN, thanks for the comment, you're right! We need a new `SIGNED WORD` type for XY positions.

As a side note, I'd like to move the `.ase` encoder/decoder to the (right now empty) [iff](https://github.com/aseprite/aseprite/tree/master/src/iff) module, so people can start using the same code the Aseprite use to load/save sprites in their our projects. Anyway I've to design the API yet (I've several API models for this, but I've never start moving code), so it would be nice to know your specific use case so I can consider your needs in the API.

Thanks again!

**Comment by iamPHEN** [comment]
Thanks for the heads up and fast response!

 I actually hacked together something of my own [here](https://github.com/iamPHEN/aseprite-rgba-converter), but this is essentially what I imagine the (right now) empty iff will be!

> Anyway I've to design the API yet ... so it would be nice to know your specific use case so I can consider your needs in the API.

My current use case is I want to be able to load '.ase' files [directly into SFML](https://github.com/Bablawn3d5/AsepriteToSFMLImage), so I can transform an Aseprite file into a single sprite sheet image. This makes it a bit easier for us during game jams as we don't need to remember to export an intermediary file format. 

I also need information to pass animation metadata to game engine's animation system like: 
- Where in the imported SFML image is a frame found (some imageRect data)
- Where an animation begins/ends, and its durations (Frame-Tags)

Later down the road, read multiple Aseprite files and tightly pack them into one sprite sheet (with all the metadata) somehow there, but I haven't put much thought into this as it's a non-issue currently.
