### ISSUE TITLE
"Repeat Last Export" without previous export gives cryptic error message

### ISSUE THREAD

**Issue by blinry** [aseprite/aseprite#1247]
When using the "Repeat Last Export" function without a previous export having ever happened, it gives the message "Aseprite can't save "" files". Should be something more clear.

### Aseprite and System version

* Aseprite version: 1.1.7-dev
* System: Arch Linux

**Comment by dacap** [comment]
Hi @blinry, it's strange. It should show the Export Sprite Sheet by default when no previous export was made. Do you get that message when you create a new sprite and use Repeat Last Export?

**Comment by blinry** [comment]
Yep! I tried with a clean profile (by moving the `~/.config/aseprite`) – it works like you describe there. In my "dirty" profile, this is the `sprite_sheet` section of the `aesprite.ini`:

```
[sprite_sheet]
type = 1
columns = 2
width = 64
height = 32
texture_filename = **filename**
```

Any more information you could use?

**Comment by dacap** [comment]
I think I've the steps to reproduce this issue:

1. Create a new sprite with `Ctrl+N` and `Enter`
1. Then `Ctrl+Shift+X` to execute `Repeat Last Export` (this will open the export sprite sheet dialog)
1. Click the `Output file` checkbox and press `Export` (the first sprite `Sprite-0001-png.ini` file is created with `texture_filename = **filename**`)
1. Then we create a new sprite `Ctrl+N` and `Enter`
1. We press `Ctrl+Shift+X` to export and the error appears

Thanks for your help! I'll try to fix this issue.

**Comment by blinry** [comment]
That was fast! Thanks, David!
