### ISSUE TITLE
Symmetry Tools Interfering with Paint-Bucket Tool

### ISSUE THREAD

**Issue by SolarLune** [aseprite/aseprite#1251]
### Describe your bug report or feature request here

Basically, when you enable symmetry, sometimes (?) the paint-bucket tool goes "through" the pixels and fills in the background. Sometimes it also fills in non-transparent pixel clusters, as well. [Here's a video that shows the issue better](https://www.youtube.com/watch?v=dMxzbGB9rfQ&feature=youtu.be).

### Aseprite and System version

* Aseprite: Version 1.1.7, installed from .deb
* System: Linux, Ubuntu Gnome, 16.04:

[Here's the example .ase file, as well](https://www.dropbox.com/s/6btjh65lyu35bwx/TurbineProblem.ase?dl=0). To reproduce the issue, enable vertical symmetry, and then try to fill the dark red pixels toward the outer edges of the "scarf".

**Comment by dacap** [comment]
I think this is related to a "hidden brush size" used in the flood fill. E.g. If choose the paint bucket tool, and then you press the `-` key several times, this will reduce the brush size to 1 pixel (you cannot see the brush size when the paint bucket is selected, but it's a hidden parameter), and then it should start working correctly.

I'll fix this ASAP.
