### ISSUE TITLE
Help Needed. Error while compiling and running.

### ISSUE THREAD

**Issue by SanjithKanagavel** [aseprite/aseprite#1253]
Receiving following error while compiling please help : 

> [1023/1025] Linking CXX static library lib/libapp-lib.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/libapp-lib.a(webserver.cpp.o) has no symbols
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/libapp-lib.a(webserver.cpp.o) has no symbols
> [1025/1025] Linking CXX executable bin/aseprite
> FAILED: bin/aseprite 
> : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -std=c++11 -stdlib=libc++ -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  src/CMakeFiles/aseprite.dir/main/main.cpp.o  -o bin/aseprite  lib/libapp-lib.a -framework Cocoa -framework Carbon -framework IOKit lib/libcfg-lib.a lib/libcss-lib.a lib/libfilters-lib.a lib/libflic-lib.a lib/librender-lib.a lib/libdoc-lib.a lib/libfixmath-lib.a lib/libscript-lib.a lib/libduktape.a -lm lib/libui-lib.a lib/libclip.a -framework Cocoa lib/libshe.a lib/libbase-lib.a lib/libobs.a lib/libmodp_b64.a /usr/lib/libdl.dylib lib/libgfx-lib.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_core.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_images.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts_ssse3.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts_sse41.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts_sse42.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts_avx.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts_avx2.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_ports.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_effects.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_codec.a /Users/phil/Desktop/Aseprite/skia/out/Release/libraw_codec.a /Users/phil/Desktop/Aseprite/skia/out/Release/libpiex.a /Users/phil/Desktop/Aseprite/skia/out/Release/libdng_sdk.a /Users/phil/Desktop/Aseprite/skia/out/Release/libgiflib.a /Users/phil/Desktop/Aseprite/skia/out/Release/libjpeg-turbo.a /Users/phil/Desktop/Aseprite/skia/out/Release/libwebp_dec.a /Users/phil/Desktop/Aseprite/skia/out/Release/libwebp_dsp.a /Users/phil/Desktop/Aseprite/skia/out/Release/libwebp_utils.a /Users/phil/Desktop/Aseprite/skia/out/Release/libpng_static.a /Users/phil/Desktop/Aseprite/skia/out/Release/libzlib.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_core.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_images.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts_ssse3.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts_sse41.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts_sse42.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts_avx.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_opts_avx2.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_ports.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_effects.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_codec.a /Users/phil/Desktop/Aseprite/skia/out/Release/libraw_codec.a /Users/phil/Desktop/Aseprite/skia/out/Release/libpiex.a /Users/phil/Desktop/Aseprite/skia/out/Release/libdng_sdk.a /Users/phil/Desktop/Aseprite/skia/out/Release/libgiflib.a /Users/phil/Desktop/Aseprite/skia/out/Release/libjpeg-turbo.a /Users/phil/Desktop/Aseprite/skia/out/Release/libwebp_dec.a /Users/phil/Desktop/Aseprite/skia/out/Release/libwebp_dsp.a /Users/phil/Desktop/Aseprite/skia/out/Release/libwebp_utils.a /Users/phil/Desktop/Aseprite/skia/out/Release/libpng_static.a /Users/phil/Desktop/Aseprite/skia/out/Release/libzlib.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_utils.a /Users/phil/Desktop/Aseprite/skia/out/Release/libskia_sfnt.a /Users/phil/Desktop/Aseprite/skia/out/Release/libSkKTX.a /Users/phil/Desktop/Aseprite/skia/out/Release/libetc1.a /Users/phil/Desktop/Aseprite/skia/out/Release/libflags.a lib/libpixman.a lib/libundo.a lib/libjpeg.a lib/libgiflib.a lib/libpng16.a /usr/lib/libm.dylib lib/libfreetype.a /usr/lib/libbz2.dylib /usr/local/lib/libpng.dylib lib/libupdater-lib.a lib/libnet-lib.a lib/libcurl.a lib/libz.a -ldl -lldap lib/libtinyxml.a && :
> Undefined symbols for architecture x86_64:
>   "_WebPDemuxDelete", referenced from:
>       SkWebpCodec::NewFromStream(SkStream*) in libskia_codec.a(codec.SkWebpCodec.o)
>       SkWebpCodec::~SkWebpCodec() in libskia_codec.a(codec.SkWebpCodec.o)
>       SkWebpCodec::~SkWebpCodec() in libskia_codec.a(codec.SkWebpCodec.o)
>   "_WebPDemuxGetChunk", referenced from:
>       SkWebpCodec::NewFromStream(SkStream*) in libskia_codec.a(codec.SkWebpCodec.o)
>   "_WebPDemuxGetFrame", referenced from:
>       SkWebpCodec::NewFromStream(SkStream*) in libskia_codec.a(codec.SkWebpCodec.o)
>       SkWebpCodec::onGetPixels(SkImageInfo const&, void*, unsigned long, SkCodec::Options const&, unsigned int*, int*, int*) in libskia_codec.a(codec.SkWebpCodec.o)
>   "_WebPDemuxInternal", referenced from:
>       SkWebpCodec::NewFromStream(SkStream*) in libskia_codec.a(codec.SkWebpCodec.o)
>   "_WebPDemuxReleaseChunkIterator", referenced from:
>       SkWebpCodec::NewFromStream(SkStream*) in libskia_codec.a(codec.SkWebpCodec.o)
>   "_WebPDemuxReleaseIterator", referenced from:
>       SkWebpCodec::NewFromStream(SkStream*) in libskia_codec.a(codec.SkWebpCodec.o)
>       SkWebpCodec::onGetPixels(SkImageInfo const&, void*, unsigned long, SkCodec::Options const&, unsigned int*, int*, int*) in libskia_codec.a(codec.SkWebpCodec.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ninja: build stopped: subcommand failed.

**Comment by dacap** [comment]
Hi @SanjithKanagavel, what exact Skia version/commit are you using? (we compiling with the `chrome/m53` branch actually)

**Comment by SanjithKanagavel** [comment]
I have cloned it from ttps://skia.googlesource.com/skia. Should i use https://github.com/aseprite/skia this version?

**Comment by dacap** [comment]
You can use that one (our fork is exactly the same), but you have to switch to the `chrome/m53` branch in your local Skia clone.

**Comment by SanjithKanagavel** [comment]
Okay. I am sorry I don't know how to do that. Anyway i will find them out !

**Comment by dacap** [comment]
In the Skia directory, you should use `git checkout chrome/m53` and then resync (`python bin/sync-and-gyp`). I hope it helps!

**Comment by SanjithKanagavel** [comment]
I am still facing the same error. Please help.

**Comment by dacap** [comment]
You might try to clone Skia again, checkout the branch, and then regenerate the configuration files. I remember one time that I tried to reconfigure the directory changing the branch after a previous compilation with the invalid branch and I wasn't able to do it (I don't remember if it was exactly the same error, but you might give it a shot).

**Comment by SanjithKanagavel** [comment]
I will try them now. Thanks.

**Comment by SanjithKanagavel** [comment]
Does v1.1.7 use skia 53 branch ??

**Comment by dacap** [comment]
> Does v1.1.7 use skia 53 branch ??

Yes, v1.1.7 is the first version using skia 53.

**Comment by SanjithKanagavel** [comment]
Xcode 7.4 is what i am using but i also have Xcode 7.3. Will Xcode 7.4 work ? I am still not able to compile.

**Comment by SanjithKanagavel** [comment]
Got the latest version. Thanks dude @dacap . I will contribute once i publish my game in steam. I will let you know. This tool is great. Loved it a lot.
