### ISSUE TITLE
Extras > Layer Edges Reenabling Constantly

### ISSUE THREAD

**Issue by Ashedragon** [aseprite/aseprite#1255]
I never had a problem with Layer Edges before I turned it on once to see what it did. Now it seems like no matter how many times I disable it, it always turns itself back on. It's... rather annoying to be quite honest.

### Aseprite and System version

* Aseprite version 1.1.8-dev
* System Windows 10 32-bit and Windows 10 64-bit.

**Comment by dacap** [comment]
Hi @Ashedragon, you can turn off the default setting closing all files (or going to the "Home" tab) and selecting View > Show > Layer Edges.

**Comment by Ashedragon** [comment]
Ahh. Seems like something that should just be in preferences so it's more clear, but thanks!

**Comment by dacap** [comment]
Yes, the default settings from View menu are really hidden. I think the View menu could be disabled when there is no document, and default settings should be in the Preferences.
