### ISSUE TITLE
Graphical Glitches (Usually line artifacts) While Painting

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1262]
Not any specific steps, get a size 31 brush, paint a bit and eventually I see some lines.
GIF:
![lineartifacts](https://cloud.githubusercontent.com/assets/8582123/18733584/3a213478-803a-11e6-9abf-0ffa2ff5bebf.gif)
At the end near the bottom right one appears. I mouse over it in a circular fashion without clicking to make it disappear.

If you have layer edges displayed, when the blue bounds are drawn again it forces them all to disappear. I mainly noticed because I killed preferences to test something else.
### Aseprite and System version
Aseprite v1.1.8-Portable
and
Aseprite v1.2-beta2-Steam
Windows Vista 32 bit

**Comment by dacap** [comment]
With "snap to grid" enabled, this is really noticeable/reproducible.
