### ISSUE TITLE
Bug with the MOVE tool

### ISSUE THREAD

**Issue by Timer00** [aseprite/aseprite#1263]
### Problem

When I was animating my sprite by moving it's layer pixels with the "MOVE TOOL" the MOVE tool kept dragging even when I was not holding the mouse button. I wasn't able to do most actions and when I tried to do any a "error console" appeared.

The bug is shown in the GIF below.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/19307482/18734554/0c0135fe-804c-11e6-980d-e20e40340ba6.gif)
**NOTE:** The mouse button was not held down in any moment of the video, only clicked.
### Aseprite and System version
- Aseprite (v1.2-beta2-Steam):
- System (Windows 10 Education 64bits v1607 BUILD(14393.105)):

**Comment by Timer00** [comment]
I was experimenting with this and realized that it may have happened when I was using the (ALT+N) command to create new frames while moving the sprite. 
Possible solution is to disable all key inputs and actions while the object is being moved, except of course the ones being used to move.

**Comment by dacap** [comment]
This bug is the same as #1315, already fixed for next v1.1.10.
