### ISSUE TITLE
[Feature Request] Add an option --ignore-layer <name> to the CLI

### ISSUE THREAD

**Issue by talecrafter** [aseprite/aseprite#1264]
Would be great for my personal workflow to have an option of ignoring a specific layer when exporting to PNG+JSON.

My use case is this:
I use one Layer with meta informations where neon colored pixels mark offsets. (The image is analyzed later in the pipeline.) I need this layer to be visible while working in Aseprite but the automated processing needs that layer separated from the other layers. My plan would be to call the CLI once with  --import-layer to just get the meta layer, and then once with --ignore-layer to get the rest of the image.

I can think of workarounds (including the nuisance of toggling it manually before exporting), but if it's not much work it would be great to have it in there. Maybe it's also useful for other people building their automated workflows.

**Comment by dacap** [comment]
Hi @talecrafter, I think it's a good idea. I'll try to include this in the next beta.

At the moment, in v1.2-beta2, you might try to use two groups, one for mark/guides, and other group for the sprite itself, then you can ignore marks using `--layer groupname` (or `--layer groupname/*` to make visible all children in that group and hide all other groups).

**Comment by talecrafter** [comment]
Excellent. Thank you.

**Comment by dacap** [comment]
This is already available in the new Aseprite v1.2-beta3

**Comment by talecrafter** [comment]
When using this command line option, hidden layers get exported too. They get not exported when not using this option. I assume that's a bug and not intended behaviour.

**Comment by dacap** [comment]
It is a bug :( I've created some unit tests for this but I need to test it more with files with a mix of hidden/visible layers. Reopening the issue.

Anyway, I'm thinking that I might give more priority to [batch export](https://github.com/aseprite/aseprite/issues/901#issuecomment-164523283) using projects #126 or post-save hooks #138
