### ISSUE TITLE
Fails to compile with clang

### ISSUE THREAD

**Issue by yurivict** [aseprite/aseprite#1270]
WIth version 1.1.9, getting this error with clang-36 and clang-38:
```
In file included from /usr/ports/graphics/aseprite/work/aseprite-1.1.9/src/app/app_menus.cpp:11:
In file included from /usr/ports/graphics/aseprite/work/aseprite-1.1.9/src/./app/app_menus.h:15:
In file included from /usr/ports/graphics/aseprite/work/aseprite-1.1.9/src/./ui/menu.h:12:
In file included from /usr/ports/graphics/aseprite/work/aseprite-1.1.9/src/observable/obs/signal.h:13:
/usr/ports/graphics/aseprite/work/aseprite-1.1.9/src/observable/obs/slot.h:51:17: error: no matching constructor for initialization of 'std::function<void ()>'
  slot(F&& f) : f(std::forward<F>(f)) { }
                ^ ~~~~~~~~~~~~~~~~~~
```

The failing command:
```
cd /usr/ports/graphics/aseprite/work/.build/src/app && clang++ \
  -DASEPRITE_WITH_WEBP_SUPPORT -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUSE_ALLEG4_BACKEND -isystem /usr/local/include -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/ports/graphics/aseprite/work/aseprite-1.1.9/third_party/loadpng -I/usr/ports/graphics/aseprite/work/aseprite-1.1.9/third_party/simpleini -I/usr/ports/graphics/aseprite/work/aseprite-1.1.9/src/. -I/usr/ports/graphics/aseprite/work/aseprite-1.1.9/src/.. -I/usr/ports/graphics/aseprite/work/aseprite-1.1.9/src/../third_party -I/usr/ports/graphics/aseprite/work/aseprite-1.1.9/src/observable -I/usr/ports/graphics/aseprite/work/.build/src/base -I/usr/ports/graphics/aseprite/work/.build/src/app -O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer  -I/usr/local/include -I/usr/local/include/freetype2 -I/usr/local/include/freetype2/freetype -Wall -Wno-switch -std=gnu++11 -O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer  -I/usr/local/include -I/usr/local/include/freetype2 -I/usr/local/include/freetype2/freetype -o CMakeFiles/app-lib.dir/app_menus.cpp.o -c /usr/ports/graphics/aseprite/work/aseprite-1.1.9/src/app/app_menus.cpp
```

**Comment by dacap** [comment]
Hi @yurivict, I think you have an old clang version. Here I'm using Xcode 8.0, Mac OS X SDK 10.12 and my `clang --version`:
```
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Before this I was compiling Aseprite with the clang version in Xcode 7.0 and SDK 10.11, that one should work too.

**Comment by yurivict** [comment]
It fails for me with clang38-3.8_1:
```
# /usr/local/bin/clang++38 --version
clang version 3.8.0 (tags/RELEASE_380/final)
Target: x86_64-unknown-freebsd10.1
Thread model: posix
InstalledDir: /usr/local/llvm38/bin
```
which is the latest version according to clang's wiki page.
Something is wrong.

**Comment by dacap** [comment]
Oh you are on FreeBSD, it might be related to the libc++ version, but I'm not sure. Are you using libstdc++ or libc++?

**Comment by yurivict** [comment]
I get the same error with both: -std=gnu++11 and -std=c++14.

**Comment by dacap** [comment]
Next week I'll take a look to this issue running a FreeBSD VM.

**Comment by yurivict** [comment]
Thanks!

The easiest way is to first install all dependencies with the package:
```
# pkg install aseprite
```

**Comment by yurivict** [comment]
This is a regression in 1.1.9.

**Comment by yurivict** [comment]
Any chance to have this fixed? I can't update the port. You can probably reproduce this with clang-3.8.0  linux too.

**Comment by dacap** [comment]
I'll take a look at this issue today.

**Comment by dacap** [comment]
Hi @yurivict, I was just able to compile the master branch from Aseprite on FreeBSD 11.0 with clang 3.8, I've used the steps from [INSTALL.md](https://github.com/aseprite/aseprite/blob/master/INSTALL.md):

![screen shot 2016-10-24 at 3 05 54 pm](https://cloud.githubusercontent.com/assets/39654/19657641/6962bb0a-99fb-11e6-939f-b36c896574bd.png)

I recommend you to clone the master branch, and follow the steps on INSTALL.md to compile Aseprite (don't use ports or nothing extra). And you can install dependencies using `pkg install`.

**Comment by yurivict** [comment]
Thanks for looking into this. This turned out to be a bug in FreeBSD 10 clang compiler that fails to compile this. I will work with them to fix it. Thanks!
