### ISSUE TITLE
[FEATURE REQUEST] have size options on export spritesheet

### ISSUE THREAD

**Issue by lewislepton** [aseprite/aseprite#1272]
Describe your bug report or feature request here
ive only just started with aseprite. but i have seen something missing which i think would be a great addition.
ive seen it in a few editors. and think its a great addition to them.

so we have `sprite > sprite size` which obviously resizes the sprite. many use this to export. so they resize, then export. but instead of affecting your sprite size just to get a bigger export. how about adding an export option which allows you to create a larger sprite without having to go to `sprite > sprite size`

so in `export spritesheet` you could have it in that, so have options to scale the size by whatever you want.
this can also apply to exported animations etc.

it just saves having people go to `sprite > sprite size` and then switch it back once they have exported. plus to save any troubles that may happen 

### Aseprite and System version
version 1.1.9
osx el crapitan

**Comment by dacap** [comment]
Hi @lewislepton, I'm marking this issue as duplicated of #493. The automatic resize on Save Copy As is already possible, but it's not yet possible in Export Sprite Sheet. As a temporary workaround you can use the [CLI (command line interface)](http://www.aseprite.org/docs/cli/) to load your sprite, [scale it](http://www.aseprite.org/docs/cli/#scale), and [export it](http://www.aseprite.org/docs/cli/#sheet) automatically from a `.bat`:

    aseprite -b player.ase --scale 2 --sheet player-sheet.png --data player-sheet.json

Some [platform-specific details here](http://www.aseprite.org/docs/cli/#platform-specific-details).

**Comment by lewislepton** [comment]
ok cool. cheers
