### ISSUE TITLE
Add option to disable move-view-when-cursor-at-edge

### ISSUE THREAD

**Issue by kyrieru** [aseprite/aseprite#1277]
Sometimes when doing something near the edges of the screen, I momentarily go outside the view which causes the view to move quickly in that direction.

There should be an option to disable this behavior, or an option to limit the speed. (With a speed of 0 stopping it from moving). Personally I never use this sort of camera movement, but it seems like it goes too fast for most people to use conveniently (it goes faster with a tablet) if they do.

**Comment by dacap** [comment]
This will be available in the next version:

![autoscroll](https://cloud.githubusercontent.com/assets/39654/20854172/54b70b36-b8d0-11e6-818d-d2a61dc94cc5.png)

Unchecking the option will disable the move-view-when-cursor-at-edge (aka auto-scroll)
