### ISSUE TITLE
100% preview

### ISSUE THREAD

**Issue by tareifz** [aseprite/aseprite#1278]
Hello Aseprite team,

The image is not zoomed at 100% in the preview window, consider to add a button in the preview window to zoom the image at 100%.

thanks.

**Comment by dacap** [comment]
Hi @tareif, you can reset the zoom in the preview moving the mouse inside the preview window and pressing `1` key.

Anyway the screen is scaled 200% by default, so you will see everything at x2 when the zoom is 100%. You can change the screen scaling to 100% from Edit > Preferences > General > Screen Scaling.

**Comment by VicTycoon** [comment]
Shortcut 1 worked, thanks! But I still think there could be a button in the window to make things easier, if possible
