### ISSUE TITLE
Aseprite only CLI

### ISSUE THREAD

**Issue by JosefKuchar** [aseprite/aseprite#1279]
Hello,
Can I compile aseprite without GUI, only CLI tools ? 
Thx

**Comment by dacap** [comment]
Hi @JosefKuchar, that's not possible at this moment but I'd like to make that possible in a near future. Related to #139

**Comment by jacksarick** [comment]
What needs to change to make this happen? I'm happy to help

**Comment by dacap** [comment]
@jacksarick I think it's a pretty big change for someone that want to contribute for the very first time. I would prefer smaller bug fixes first and then trying to contribute to something big.

Anyway, for some reference, the basic idea is that [this statement](https://github.com/aseprite/aseprite/blob/master/src/app/app.cpp#L231) must be completely ignored from the compilation process (and all the dependencies should be ignored too/not linked, i.e. UI library isn't needed, etc.)

**Comment by dacap** [comment]
New `cmake -DENABLE_UI=OFF` flag added. Another discussion in [t/1351](https://community.aseprite.org/t/integrating-aseprite-with-travis-ci/1351)
