### ISSUE TITLE
shading problem.

### ISSUE THREAD

**Issue by flashice2030** [aseprite/aseprite#1291]
Describe your bug report or feature request here
...When I use shading mode,​ can draw any color on my sprite,I really want to know that is this a bug or not ? 
...
...
### Aseprite and System version
- Aseprite (version number, installer/portable/Steam/beta/dev):
- System (Win/OSX/Linux, version, distribution):

**Comment by dacap** [comment]
I've seen your email, please refer to [shading documentation](www.aseprite.org/docs/shading/) to know how it works. You first have to paint an area of a solid color with the Simple Ink, and then use the Shading Ink to displace that color into other colors in the selected gradient/color shades.

**Comment by flashice2030** [comment]
thanks for your reply , shading documentation link is broken.

At 2016-10-18 09:30:28, "David Capello" <notifications@github.com> wrote:


I've seen your email, please refer to shading documentation to know how it works. You first have to paint an area of a solid color with the Simple Ink, and then use the Shading Ink to displace that color into other colors in the selected gradient/color shades.

**Comment by dacap** [comment]
Fixed, it's https://www.aseprite.org/docs/shading/
