### ISSUE TITLE
Pixel Grid no longer showing up

### ISSUE THREAD

**Issue by SOMA1990** [aseprite/aseprite#1292]
Describe your bug report or feature request here
... Using Shortcut button or window its not showing up
...
...

### Aseprite and System version v1.1.9

* Aseprite (version number, installer/portable/Steam/beta/dev):
* System (Win/OSX/Linux, version, distribution):

**Comment by dacap** [comment]
Hi @SOMA1990, you should zoom in to view the pixel grid (from 400% or more), you can check if the pixel grid is enabled seeing a checkbox in the *View > Show > Pixel Grid* menu option.

Also you can check your pixel grid color settings from *Edit > Preferences > Grid & Background*. The pixel grid opacity is adjusted automatically depending on the zoom level too.

**Comment by dacap** [comment]
I'll close this issue but we can re-open if my solution didn't work.
