### ISSUE TITLE
Very slow rendering on Debian Stretch

### ISSUE THREAD

**Issue by troutsneeze** [aseprite/aseprite#1297]
On Debian Stretch performance is very bad, not sure why. On the same machine an hour ago on Debian Jessie it works fine. The machine is a 4 GHz i7 so should be plenty fast. Aseprite 1.1.9 64 bit.

Moving the mouse in the window shows 100% cpu usage in Xorg. It could just be a bug in Xorg or something.

**Comment by goobliata** [comment]
Some more information: if you swap screen and UI element scaling (screen scaling: 100%, ui scaling: 200%) it runs fast again.

**Comment by dacap** [comment]
Hi @goobliata, I've to rewrite the whole Linux back-end in the near future (related to #139), so I'll be reviewing all Linux issues.

**Comment by grena** [comment]
I've got the same issue, but thank you very much for the workaround @goobliata :)

**Comment by troutsneeze** [comment]
I haven't used it much but it seems fast with the beta.
