### ISSUE TITLE
Feature request: Add an option to start counting frames from zero (and possibly other values).

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1300]
Normally, the timeline begins counting at 1, which makes sense at a glance but becomes troublesome since the software I'm using expects the first frame to be numbered zero. Because I have to list frame sequences fairly often, I find myself tabbing back and forth between ASEprite and other documents and having to mentally add or subtract one from frame numbers as I go, and it's turning out to be rather cumbersome.

Being able to set the initial number to something _other_ than one or zero would also simplify upkeep and management for multipart .ase files, for however often that comes up.

The frame enumeration would primarily be a UI customization feature, changing the values shown on the timeline, but would also effect serialized file names when multiple frames saved in sequence (saving a multiframe .ase as .pngs, for instance). Similarly, loaded/imported files with sequential filenames would be shown on the timeline under frame numbers corresponding to the number in their filename, presumably as an option.
If you want to get really involved, missing frames could be skipped on the timeline using a "~" or "..." timeline marker with no active cels, which would also allow us to skip frame numbers. These are completely tertiary ideas, though.

**What I'm really after here is the ability to set the number of the first frame on the time line to 0, rather than 1.** Besides everything else, what I really need is this.

Thanks for considering these ideas! :D

**Comment by dacap** [comment]
At this moment I'll include only the possibility to change the initial frame number from the UI to avoid delaying the next release.

**Comment by oceanhahn** [comment]
Cool, thanks! If you find the time in the future to consider the other options, that would be great, but the UI enumeration really is the important thing. :D

**Comment by oceanhahn** [comment]
Looks good, but it doesn't play nice with Tag Properties just yet~ :0
