### ISSUE TITLE
LAYERS on Right Side of window?

### ISSUE THREAD

**Issue by SOMA1990** [aseprite/aseprite#1310]
Describe your bug report or feature request here
... Is it possible to have the layer window on the right side of the window? It currently blocks the bottom and then you try to fit everything on screen on 256 x 256 it zooms very small.
...
...

### Aseprite and System version

* Aseprite (version number, installer/portable/Steam/beta/dev):
* System (Win/OSX/Linux, version, distribution):

**Comment by dacap** [comment]
Duplicate #1169, see [this comment](https://github.com/aseprite/aseprite/issues/1169#issuecomment-247335292)

**Comment by SOMA1990** [comment]
THANK YOU

I APPRECIATE IT!
