### ISSUE TITLE
Tag Names Shouldn't Extend Past Tag End

### ISSUE THREAD

**Issue by SolarLune** [aseprite/aseprite#1311]
So this is a pretty minor "deal", but I wonder if tag names should extend past the name of the tag? It seems like it might be cleaner to always display at least one letter from the name, but cut the name off if the tag's range ends. This would become more important as tags group up nearby.
### Aseprite and System version
- Aseprite v1.2-beta3 (Steam)
- Linux, Solus OS, v1.2.1 64-bit

**Comment by oceanhahn** [comment]
Related to [Issue 920.](https://github.com/aseprite/aseprite/issues/920)

**Comment by dacap** [comment]
Closing this one because #920 already fixed it.

**Comment by SolarLune** [comment]
Cool. Thanks!
