### ISSUE TITLE
[BUG]UI Elements Scaling to 200%, UI mess up

### ISSUE THREAD

**Issue by zmox** [aseprite/aseprite#1312]
Describe your bug report or feature request here
when I set UI Elements Scaling to 200% ,  the Tab text didn't scale, the UI look like mess up
### Aseprite and System version
- Aseprite (version number, installer/portable/Steam/beta/dev): 1.1.10-dev
- System (Win/OSX/Linux, version, distribution): OSX

**Comment by zmox** [comment]
fix this problem by modify skin.xml

**Comment by dacap** [comment]
Hi @zmox, sorry I didn't reply here. You can change the UI/Screen scaling from Edit > Preferences > General in case you want this kind of customization (there shouldn't be need to change the `skin.xml` file).

**Comment by zmox** [comment]
@dacap this problem is appear when I set the UI/Screen scaling from Edit > Preferences > General 
to 200%

Maybe Because the Tab UI don't scaling 200% as well. 
so I change the tab width and height to make it right
    <dim id="tabs_width" value="120" />
    <dim id="tabs_height" value="28" /> 

I'm using macbook pro  and my screen is Retina.
maybe it's reason?

**Comment by Bigmacbook** [comment]
Yeah tabs mess up on 200% UI Scaling.

Version: 1.1.10-dev

![GitHub Logo](http://i.imgur.com/IokWPtL.png)
