### ISSUE TITLE
Mouse stuck with pixel. [PIC included]

### ISSUE THREAD

**Issue by SOMA1990** [aseprite/aseprite#1315]
Describe your bug report or feature request here
...Idk what was happening but at some point during drawings. The mouse would get stuck with the pixel selected and I wouldnt be able to save my progress or access any of the option tabs. and this dialog box would come up.
![screen shot 2016-11-03 at 10 42 24 pm](https://cloud.githubusercontent.com/assets/22850064/19992786/2149f850-a217-11e6-89fa-79dcda83d938.png)

BTW love your app. I hope folders comes soon!
...

### Aseprite and System version

* Aseprite (version number, installer/portable/Steam/beta/dev):
* System (Win/OSX/Linux, version, distribution):

**Comment by dacap** [comment]
Hi @SOMA1990, actually working on #532 I can replicate this problem quite often if we use a whole animation as reference.

Aseprite has a data recovery feature that tries to save all your work using a background task ([details about this here](http://dev.aseprite.org/post/121527538727/data-recovery)), I'm trying to improve this situation implementing:

1. A visual indication that a background task is doing some work in the background (#1114)
2. Trying to unlock the sprite (i.e. stop the background task) in case the user wants to draw on the sprite (so the user has more priority that the background task).

At the moment you can disable the data recovery feature to avoid this dialog if this is too annoying going to Edit > Preferences > General and unchecking this option:

![data](https://cloud.githubusercontent.com/assets/39654/20022000/3e69a1e2-a2b7-11e6-81e7-59a4429b3a99.png)
