### ISSUE TITLE
Reduce duplicate frames into one 

### ISSUE THREAD

**Issue by buckle2000** [aseprite/aseprite#1316]
Feature request:
Reduce duplicate frames into one frame in output and reference them in sheet data file.
This saves memory.

### Aseprite and System version

* Aseprite 1.1.7:

**Comment by oceanhahn** [comment]
I'd actually like to see something like this as a way to link duplicate _cels_ (frame-layer elements) on the timeline, if they're independent of each other. That way, duplicate frames (frames with complete sets of duplicate cels) would be optimized, but individual layers could still be modified my making specific cels unique later.

It would also make cel copying a bit more powerful, potentially. ASEprite already has cel instantiation between nonadjacent frames (!) so being able to have the software automatically find and link duplicate frames could be a really useful compliment to it.

Linked cels is not the same thing as linked _frames_, but I think it might be a more useful option.
I don't want to change this suggestion, though; it's just something it made me think of. ^^

**Comment by buckle2000** [comment]
@oceanhahn you should open a new issue for your idea.

---
By the way, do your mean that linked frames = multiple linked cells?

**Comment by oceanhahn** [comment]
I'd interpreted "duplicate frames" as any pair of frames with perfectly identical pixel data between them when their layers are merged, but I may be misunderstanding you. ^^;

**Comment by amkk** [comment]
hi @dacap
I want bump this because not yet labeled.

**Comment by dacap** [comment]
There are two things to improve:

1. If we split layers, linked cels must be exported just once in the sprite sheet and JSON data should point to the same region
2. If we don't split layers, and two (merged) frames are exactly the same, the data must be reused.

I guess this behavior should be optional (and on by default)

**Comment by dacap** [comment]
In next version (v1.2.16) `-sheet-pack` will merge duplicated images.
