### ISSUE TITLE
Ninja build infinite loops on Windows

### ISSUE THREAD

**Issue by fredgirl77** [aseprite/aseprite#1319]
The below appears over and over again in the logs, until it reaches 100 tries and gives up: `ninja: error: manifest 'build.ninja' still dirty after 100 tries`

        -- Building with ZLIB
        -- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
        -- Creating directory C:/Users/Fred/Documents/aseprite/build/third_party/freetype2/include/freetype/config
        -- Creating file C:/Users/Fred/Documents/aseprite/build/third_party/freetype2/include/freetype/config/ftconfig.h
        -- Creating file C:/Users/Fred/Documents/aseprite/build/third_party/freetype2/include/freetype/config/ftoption.h
        -- Configuring done
        -- Generating done
        -- Build files have been written to: C:/Users/Fred/Documents/aseprite/build
[0/1] Re-running CMake...
        -- curl version=[7.21.6]
        -- LDAP_H not found CURL_DISABLE_LDAP set ON
        [0/1] Re-running CMake...
        -- curl version=[7.21.6]
        -- LDAP_H not found CURL_DISABLE_LDAP set ON
### Aseprite and System version

* Aseprite (version number, installer/portable/Steam/beta/dev): Dev, latest master as of 6/11/2016
* System (Win/OSX/Linux, version, distribution): Windows 10

**Comment by dacap** [comment]
Hi @fredgirl77, I've just try a fresh clone/compilation. Could you give a try cloning Aseprite again into other directory? (remember the `--recursive` parameter)

**Comment by fredgirl77** [comment]
Turns out that my Skia build had failed and I didn't notice. Late night compiling = not a good idea.
