### ISSUE TITLE
list-layers on a spite with groups doesn't export hidden layers (1.2-beta3)

### ISSUE THREAD

**Issue by davidtme** [aseprite/aseprite#1323]
Using the beta cli with the arguments `--list-layers --format json-array --data` doesn't lists hidden layers when the spite has groups.

### Aseprite and System version

* Aseprite 1.2-beta3
* Windows 10

**Comment by dacap** [comment]
You can [use `--all-layers` option](https://www.aseprite.org/docs/cli/#all-layers).
