### ISSUE TITLE
CLI --save-as adds single quotes to filename

### ISSUE THREAD

**Issue by AdamDrobotij** [aseprite/aseprite#1325]
Should not include single-quotes in filename. Finder ignores them, but they are an issue if doing anything via the shell.

To reproduce:
1. Create file `Test.ase` with multiple layers
2. `aseprite -b --split-layers Test.ase --save-as out_.png`
3. Observe filenames listed in shell (via `ls`)  as:
`'out_ (Layer1).png'`
`'out_ (Layer2).png'`

(I would also prefer the space between the output name and layer name not be there.)

### Aseprite and System version

* Aseprite (v1.1.9, Steam):
* System (OSX Sierra, 10.12.1):

**Comment by dacap** [comment]
You can use `--save-as out_{layer}.png` (and in this case the `--split-layers` is done implicitly because `{layer}` was used in the filename.
