### ISSUE TITLE
Symmetry to center of a pixel

### ISSUE THREAD

**Issue by Uhkam** [aseprite/aseprite#1332]
The request is kind of difficult to describe, but simply put:

The symmetry tool works really fine when it's stuff like this:
![Symmetry fine](http://puu.sh/sjFFY/39cd2c3c1a.png)

However what I'd like to also do is if the thing is symmetric but with odd-numbered width. Kind of like this:
![Symmetry problem](http://puu.sh/sjFN7/2eefe4cbc8.png)

In short because I can't put the symmetry line in the center of a pixel I can't make this symmetrical without either doing both sides manually or something like it.

As of currently I can't figure out as someone with soon 20 hours of usage of this program how to make the latter symmetric work how I'd like it if there is a way to do it. I also don't know if this request is possible to do but I do want to throw it out here at least to hear out how others cope with odd-numbered symmetry

### Aseprite and System version

* Aseprite (version number, installer/portable/Steam/beta/dev): 1.1.9, Steam
* System (Win/OSX/Linux, version, distribution): Windows 10 Professional 64-bit

**Comment by dacap** [comment]
Hi @Uhkam, something like #853?

**Comment by Uhkam** [comment]
Yup, exactly like that @dacap.

Sorry for making a thread about the same suggestion then.

**Comment by dacap** [comment]
No problem about the duplicate post (it's common, sometimes I post a duplicates 😄 )
