### ISSUE TITLE
[Suggestion] Live animation editing

### ISSUE THREAD

**Issue by trollworkout** [aseprite/aseprite#1335]
Pretty much you set up a number of frames hit play and start editing. Every brush stroke is recorded on the current frame and will loop around. You can add or erase brush strokes like normal but while animation is in motion.

Also similarly you can make new layers, modify layers ALL and most of the other stuff while animation still running. 

In aseprite once you click play you can no longer edit. I suggest you keep editing ON while animating for this effect. 

For example in Game Maker 2 you can do this 

Is edited while animating giving the impression of repetitive motion like that. 

![source](https://cloud.githubusercontent.com/assets/6987027/20672451/5a837c5e-b54f-11e6-9125-a5e767d0f626.gif)

Loopable exportable as an anim .

**Comment by dacap** [comment]
Please refer to #1320
