### ISSUE TITLE
Bug: Brush size text (int) input does not accept Backspace, Delete, arrow key inputs; loses focus.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1339]
![textfieldbug cap](https://cloud.githubusercontent.com/assets/11544843/20802934/9b21fcf4-b7bb-11e6-8b87-11cc6f9f1203.png)

The Text Size text field does not behave predictably when it has focus (a cursor is active in the text field) and the Delete, Backspace, or Arrow keys are invoked:

 * Delete and Backspace both clear _pixels in the workspace_ instead of clearing selected characters in the text field, or deleting single characters after or before the cursor, respectively.

 * Arrow keys trigger their normal functions in the Timeline instead of moving the cursor in the text field.

Letter keys also invoke their normal assigned hotkey functions, which is not a problem since letters have no predictable behaviour in a numerals-only text field. I would have expected the text field to override the normal function of deletion and arrow keys, though, for any text field, numerals-only or otherwise, and I suspect that these keys were meant to have overrides but that it maybe just got forgotten, [I think somewhere around here?](https://github.com/aseprite/aseprite/blob/bc3e4ba3db204767599460d884b39714fe6749c1/src/ui/int_entry.cpp#L117-L126) Just a guess! :D

Anyway, it would be pretty convenient to have this fixed sometime soon, if you can squeeze it in. I'd do it myself but I don't have much confidence in my C++ and I wouldn't even know if it worked if I did. :v 

Thanks for the help; looking forward to 1.2!

..using ASEprite 1.1.9 on Win7 SP1.

**Comment by oceanhahn** [comment]
Cool, thanks!

**Comment by dacap** [comment]
You're welcome! 😄
