### ISSUE TITLE
Type conversion compile error on Windows

### ISSUE THREAD

**Issue by OriginalAdric** [aseprite/aseprite#1340]
Following the Windows build instructions, I ran into this build error:
`E:\dev\aseprite\src\she\win\window_dde.cpp(138): error C2664: 'BOOL UnpackDDElParam(UINT,LPARAM,PUINT_PTR,PUINT_PTR)': cannot convert argument 3 from 'UINT' to 'PUINT_PTR'`

The original code is (lines 121-132):
```
      case WM_DDE_INITIATE: {
      HWND clienthwnd = (HWND)wparam;
      UINT appAtom = 0, topicAtom = 0;
      if (!UnpackDDElParam(msg, lparam,
                           &appAtom,
                           &topicAtom))
            return false;

      bool useUnicode = (IsWindowUnicode(clienthwnd) ? true: false);
      std::string app = get_atom_string((ATOM)appAtom, useUnicode);
      std::string topic = get_atom_string((ATOM)topicAtom, useUnicode);
```

I hacked it to
```
      PUINT_PTR puiLo = 0, puiHi = 0;
      if (!UnpackDDElParam(msg, lparam, puiLo, puiHi))
      {
		  return false;
      }
      
      UINT appAtom = 0, topicAtom = 0;
      bool useUnicode = (IsWindowUnicode(clienthwnd) ? true: false);
      std::string app = get_atom_string((ATOM)appAtom, useUnicode);
      std::string topic = get_atom_string((ATOM)topicAtom, useUnicode);
```
which worked, but I don't know enough about what all that's doing to know if it's a good solution.

### Aseprite and System version

* Aseprite (77a9fd0ae600ced7f8b27d3e95e2a8cb06afb7ab, dev)
* System (Win10 Pro x64)

**Comment by dacap** [comment]
Hi @OriginalAdric, it's because you are using the x64 compiler. I generally compile with the x86 (32bit) compiler but this issue must be fixed.
