### ISSUE TITLE
Reset double click when selecting folder

### ISSUE THREAD

**Issue by DaanHaaz** [aseprite/aseprite#1346]
In the file navigator with Save as or Open file, etc. when double clicking on a folder, it doesn't reset the double-click. Meaning that when you click on another folder once, it acts as if you double click on it and it goes to that folder. This also happens when you click on empty space in the navigator.

**Current behavior**
Inside folder A is a folder called B.
Double click on A.
Click once on folder B (within 0.? seconds of the inital double click).
It goes to folder B instead of only selecting folder B.

**Expected behavior**
It should only select folder B.

### Aseprite and System version

* Aseprite (1.1.9):
* System (Linux):

**Comment by dacap** [comment]
Related to #139
