### ISSUE TITLE
How do I know in JSON file that a tag is a loop?

### ISSUE THREAD

**Issue by qbart** [aseprite/aseprite#1348]
Hello,

I've created few frames just for a test and two tags: idle & run. "Run" was created using loop (Set loop section). Then I exported everything to JSON here is what I can see:

```json
{  
   "frames":[  
      /* some frames here */
   ],
   "meta":{  
      "format":"I8",
      "size":{  
         "w":256,
         "h":32
      },
      "scale":"1",
      "frameTags":[  
         {  
            "name":"idle",
            "from":0,
            "to":3,
            "direction":"forward"
         },
         {  
            "name":"run",
            "from":4,
            "to":7,
            "direction":"forward"
         }
      ]
   }
}
```

Should "run" frame contain an information about a loop? (maybe loop: true?).
I am new user so I may have misunderstood what loop means in terms of Aseprite.

v1.1.10 via Steam
Windows 10

**Comment by Bobhostern** [comment]
"Set loop section" is an alias for creating a tag named "Loop" by default over the set of frames selected. Your loop is encoded under "frameTags" as "run":

    {  
      "name":"run",
      "from":4,
      "to":7,
      "direction":"forward"
    }

This is your loop. It's just that the software takes a loop and stores it as a "tag".

**Comment by dacap** [comment]
Hi @qbart, as @Bobhostern said, the "Set Loop Section" doesn't have nothing special about it. It's just a shortcut to create a tag named "Loop". From the Aseprite point of view, all tags are loops. (Although you can change the playback method to "Play Once" right-clicking the play button, it's just an UI option, this property is not related to the sprite/tag itself.)

So basically, each animation is handled as a loop or not in your game.

**Comment by qbart** [comment]
@Bobhostern @dacap Thank you for your answers. Just wanted to understood this better, I can change tags naming (i.e. "run" -> "run_loop") and during the import I will determine whether it is a loop or not.
