### ISSUE TITLE
Apply Zoom setting creates artifacts

### ISSUE THREAD

**Issue by TheSilvus** [aseprite/aseprite#1349]
When disabling the `Apply Zoom` background setting zooming in and out creates weird artifacts:
![image](https://cloud.githubusercontent.com/assets/18658672/21063654/0df27456-be57-11e6-8e54-706c182c624c.png)
They seem to be fixed after you draw above them, but I'm not sure about that

 
* Aseprite: v1.2-dev
* System (Win/OSX/Linux, version, distribution): Linux Arch

**Comment by HolyBlackCat** [comment]
There is a related bug: With zooming close enough the background cells eventually start to become larger even if `apply zoom` is disabled.

**Comment by dacap** [comment]
Fixed the problem described by @HolyBlackCat in dfa90d15c8e7cf49dc2ecfd9b57feac064999a20. Now I'll work on the main bug.

**Comment by dacap** [comment]
It looks like 0a68c4626db4a8f1b26a2d1fd10ff0c07b165d1c doesn't fix the rendering issues when "apply zoom" is disabled on 16x16 or other sizes. Still reviewing this issue.
