### ISSUE TITLE
Aseprite.exe fails to link using VS2015

### ISSUE THREAD

**Issue by fredgirl77** [aseprite/aseprite#1351]
After generating a VS solution with cmake, everything compiles and links nicely except the final aseprite executable.

**The workaround is to add "..\lib\cmark.lib"  to the linker flags in the project settings pane** (I noticed that the lib file was in the libs directory but not being linked).

The errors that VS spat out are below:

        37>------ Build started: Project: aseprite, Configuration: RelWithDebInfo Win32 ------
        37>  Building Custom Rule C:/build/aseprite/src/CMakeLists.txt
        37>  CMake does not need to re-run because C:\build\aseprite\build\src\CMakeFiles\generate.stamp is up-to-date.
        37>  main.cpp
        37>LINK : warning LNK4044: unrecognized option '/LINK'; ignored
        37>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_node_free
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_iter_new
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_iter_free
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_iter_next
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_iter_get_node
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_node_get_type
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_node_get_literal
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_node_get_url
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_parser_new
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_parser_free
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_parser_feed
        37>app-lib.lib(browser_view.obj) : error LNK2001: unresolved external symbol __imp__cmark_parser_finish
        37>C:\build\aseprite\build\bin\aseprite.exe : fatal error LNK1120: 12 unresolved externals`

### Aseprite and System version

* Aseprite (version number, installer/portable/Steam/beta/dev): repo clone as of 10/12/2016
* System (Win/OSX/Linux, version, distribution): Windows 10

**Comment by dacap** [comment]
Hi @fredgirl77, I had this issue in some intermediate commits, but the latest master should have this issue fixed (mainly by this commit 763c9ce9578676f25310621cdbec55d8ca40a52c)
