### ISSUE TITLE
"New version available" button is too small

### ISSUE THREAD

**Issue by Bobhostern** [aseprite/aseprite#1354]
This is a repeat of issue #1352 because it was closed prejudicially.
The same error appears in version 4fada3aa00c9b35425913a5b318472d802030835 if the version number is pushed back by one point ("1.2" -> "1.1"), emulating the creation of a new version.

<img src="http://i.imgur.com/4eXz6UA.png"/>

What is running here is version 6dc2b5284ec3ebd8066f0e1cfb5ec53b1290c6db, which is exactly 2 patches after 4fada3aa00c9b35425913a5b318472d802030835, which was purported to fix this issue.

git log output:

<img src="http://i.imgur.com/ohTuqjp.png"/>

### Steps to reproduce:
1. Checkout 6dc2b5284ec3ebd8066f0e1cfb5ec53b1290c6db on the beta branch.
2. Open src/config.h, find the VERSION define, and change it from "1.2-dev" to "1.1-dev".
3. Build and run.

### Aseprite and System version

* Aseprite (dev): 4fada3aa00c9b35425913a5b318472d802030835 to 6dc2b5284ec3ebd8066f0e1cfb5ec53b1290c6db
* System (Linux): Ubuntu Studio 16.04.1 LTS (Should be system-independent)

**Comment by Bobhostern** [comment]
This may call for a reopening of #1345, or something, but I felt that #1352 was thrown out too quickly, and I couldn't signify that, other than by doing this.

**Comment by dacap** [comment]
I'll take a look at this issue tomorrow. Anyway I generally reopen issues when I can reproduce the problem.

**Comment by Bobhostern** [comment]
Ok. Thank you.
