### ISSUE TITLE
Cannot Link in Windows 10

### ISSUE THREAD

**Issue by meatballcoder** [aseprite/aseprite#1358]
I was able to get it done.  Don't know what happened.  But I couldn't delete this message.

Describe your bug report or feature request here

Is this because I am using Visual Studio 2015?  Is this a 32bit vs 64bit problem?

I used this before I called cmake:

call "%VS140COMNTOOLS%\vsvars32.bat"

I cannot link everything with Ninja.  When I run Ninja I get tons of mismatch errors:

c:\aseprite\build>ninja aseprite
[1/1] Linking CXX executable bin\aseprite.exe
FAILED: bin/aseprite.exe
cmd.exe /C "cd . && C:\cmake-3.7.1-win64-x64\bin\cmake.exe -E vs_link_exe --intdir=src\CMakeFiles\aseprite.dir --manifests ..\src\main\settings.manifest -- C:\PROGRA~2\MICROS~2.0\VC\bin\link.exe /nologo src\CMakeFiles\aseprite.dir\main\main.cpp.obj src\CMakeFiles\aseprite.dir\main\resources_win32.rc.res  /out:bin\aseprite.exe /implib:lib\aseprite.lib /pdb:bin\aseprite.pdb /version:0.0  /LTCG  /subsystem:windows -LINK wsetargv.obj -ENTRY:"wWinMainCRTStartup" .............

finally,

bin\aseprite.exe : fatal error LNK1120: 14 unresolved externals
LINK failed. with 1120
ninja: build stopped: subcommand failed.

Here are some examples:

skia_skgpu.lib(skgpu.GrDrawPathBatch.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
skia_skgpu.lib(skgpu.GrTessellator.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
skia_skgpu.lib(skgpu.GrAtlasTextBlob_regenInBatch.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
skia_skgpu.lib(skgpu.GrBitmapTextGeoProc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
skia_skgpu.lib(skgpu.GrPathRange.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
skia_skgpu.lib(skgpu.GrPrimitiveProcessor.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
skia_skgpu.lib(skgpu.GrDrawPathBatch.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
skia_skgpu.lib(skgpu.GrTessellator.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
skia_skgpu.lib(skgpu.GrAtlasTextBlob_regenInBatch.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
skia_skgpu.lib(skgpu.GrBitmapTextGeoProc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
skia_skgpu.lib(skgpu.GrPathRange.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
skia_skgpu.lib(skgpu.GrPrimitiveProcessor.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.cpp.obj
....lots more like this above then lastly:

skia_ports.lib(ports.SkOSFile_stdio.obj) : error LNK2001: unresolved external symbol __imp___mkdir
skia_ports.lib(ports.SkOSFile_win.obj) : error LNK2001: unresolved external symbol __imp___access
skia_effects.lib(effects.Sk4fLinearGradient.obj) : error LNK2001: unresolved external symbol __imp___fdsign
dng_sdk.lib(dng_sdk.dng_date_time.obj) : error LNK2001: unresolved external symbol __imp___localtime64
giflib.lib(giflib.dgif_lib.obj) : error LNK2001: unresolved external symbol __imp__fdopen
OLDNAMES.lib(fdopen.obi) : error LNK2001: unresolved external symbol __imp__fdopen
giflib.lib(giflib.dgif_lib.obj) : error LNK2001: unresolved external symbol __imp__close
OLDNAMES.lib(close.obi) : error LNK2001: unresolved external symbol __imp__close
giflib.lib(giflib.dgif_lib.obj) : error LNK2001: unresolved external symbol __imp__open
OLDNAMES.lib(open.obi) : error LNK2001: unresolved external symbol __imp__open
MSVCRT.lib(_chandler4gs_.obj) : error LNK2001: unresolved external symbol __except_handler4_common
bin\aseprite.exe : fatal error LNK1120: 14 unresolved externals
LINK failed. with 1120
ninja: build stopped: subcommand failed.

### Aseprite and System version

This:

git clone --recursive https://github.com/aseprite/aseprite.git
cd aseprite
git pull
git submodule update --init --recursive

* Aseprite (version number, installer/portable/Steam/beta/dev):
* System (Win/OSX/Linux, version, distribution):

Windows 10.

**Comment by meatballcoder** [comment]
I was able to get it done.  Don't know what happened.  But I couldn't delete this message.

**Comment by Gaspa79** [comment]
If you don't mind: how exactly did you do it? I'm having the same problem

**Comment by meatballcoder** [comment]
I wish I could remember.  Sorry.

**Comment by fabiowallner** [comment]
Stuck at the same problem. Anybody?

**Comment by Gaspa79** [comment]
Search in reddit there are windows binaries already no need to compile new
ones

**Comment by useraccessdenied** [comment]
I had this similar Linking error (LNK2038) and I solved this by using Skia-m81's March 2nd release rather than the March 11th release.

**Comment by alexhenrie** [comment]
I got the same "value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease'" error and was able to fix it by using an older version of Skia-m81 and deleting my build directory before compiling again.
