### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by piratesephiroth** [aseprite/aseprite#1363]
It seems there are some new issues when we try to build it on Windows.

I guess awk doesn't like the CRLF breaks in libpng's source so we must disable that when cloning the repository, with "git config --global core.autocrlf false"

I could not build it with Ninja because CMake always insists on using the GNU compiler for Ninja instead of Visual Studio, even when running from a VS tools command prompt.
And if we go on trying to use GCC it will complain about the missing winsock libs...

Works fine if we generate project files for Visual Studio though.

* Windows 8.1 x64

**Comment by dacap** [comment]
Hi @piratesephiroth, about the Ninja issue, you might try: 1) removing gcc path from the `PATH` environment variable or, 2) using:

    set CC=cl
    set CXX=cl

Source: https://cmake.org/pipermail/cmake/2012-September/051986.html
