### ISSUE TITLE
gui.xml was not found

### ISSUE THREAD

**Issue by StigOlavsen** [aseprite/aseprite#1366]
After building from the repo, rev 4fada3a, on OSX 10.11.5, everything works fine when running aseprite from the build directory.

However after doing ninja install, and trying to run aseprite from the installed location in /usr/local/bin/aseprite, it gives the error gui.xml was not found.

The data folder was installed to /usr/local/share/aseprite/data, but aseprite seems unable to locate it?

**Comment by dacap** [comment]
Hi @h0rdak, actually I'm not sure how the "ninja install" command might work as CMakeLists.txt files are not prepared to do so (I never use "ninja install", the executable is on the `build/bin` directory).

**Comment by h0rdak** [comment]
I've attached the build manifest, showing what gets installed where. 

[install_manifest.txt](https://github.com/aseprite/aseprite/files/653332/install_manifest.txt)

As I said, it works fine if I run it from the build directory, but that's an inconvenient location to execute from every time. 

I was able to make an app bundle instead, so I regard the problem as solved on my part, but I would expect this to be an issue on linux as well, as it would install in a similar manner.

**Comment by kasbert** [comment]
This helped for me:

`diff --git a/src/app/resource_finder.cpp b/src/app/resource_finder.cpp
index 4ba8cf567..10ae69f80 100644
--- a/src/app/resource_finder.cpp
+++ b/src/app/resource_finder.cpp
@@ -100,6 +100,9 @@ void ResourceFinder::includeDataDir(const char* filename)
   sprintf(buf, "../Resources/data/%s", filename);
   includeBinDir(buf);  // $BINDIR/../Resources/data/filename (inside a bundle)
 
+  // $BINDIR/../share/aseprite/data/filename (installed in /usr/ or /usr/local/)
+  sprintf(buf, "../share/aseprite/data/%s", filename);
+  includeBinDir(buf);
 #else
 
   // $HOME/.config/aseprite/filename
`
