### ISSUE TITLE
Turn off automatic opening of home tab

### ISSUE THREAD

**Issue by goobliata** [aseprite/aseprite#1368]
I would like a setting to disable the home tab from opening when I open aseprite.

**Comment by dacap** [comment]
![screen shot 2016-12-18 at 2 45 14 pm](https://cloud.githubusercontent.com/assets/39654/21295302/ac385bb4-c530-11e6-88e6-dc20d14184f5.png)

**Comment by goobliata** [comment]
Thanks!
