### ISSUE TITLE
Paint Bucket Can't Fill Outside Original Area in Tiled Mode

### ISSUE THREAD

**Issue by anonnyj** [aseprite/aseprite#1369]
You can draw with other tools (pencil, line, spray) outside the normal drawing area when in tiled mode, but with the paint bucket tool you can't. 

### Aseprite and System version

* Aseprite 1.1.11 installer
* Win 7

**Comment by HolyBlackCat** [comment]
Related:
Brush preview doesn't work outside of the original area.
You can't move selected objects outside of the original area (parts which are outside disappear).

**Comment by dacap** [comment]
Fixed in 7dbff3daa65a69ee1a0ac73a5e75d805c6a14bee and fb2ee91c92ff227a72ae6e4f697bfeb9e06f8005 (#348)
