### ISSUE TITLE
Make "save" and "export" separate options, controlling target file.

### ISSUE THREAD

**Issue by kyrieru** [aseprite/aseprite#1371]
I think there should be a "save" and "export" option. Each would have all the file type options.

Let's say you have a .ase open;
If you "save" as a .gif, the currently opened file would be the new gif.
If you "export" as a gif, then the target file would still be the .ase file.

This prevents situations where you export, and then have to open the previous file again.

**Comment by dacap** [comment]
Hi @kyrieru, actually the File > Save Copy As works like an export option.

**Comment by kyrieru** [comment]
Ah, my bad. Thanks for the help then.
