### ISSUE TITLE
Grid preferences not persisting after program shutdown

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1380]
The settings for the grid in "Preferences" do not persist after you turn Aseprite off. It works from file to file and for the active file if you change the settings, and both the new and active document settings work, but like I said, they get reset after a restart.

Using Aseprite v1.2-beta6 on Steam
Windows 10 x64

**Comment by KashouC** [comment]
Actually now that I posted the bug report it got saved... I'll get back to you. It might just be the settings saved from before, but it's weird that the "new document" settings get reset.

**Comment by KashouC** [comment]
Yeah, I dunno. It works fine now even after a reboot. All I know is that I've had to re-set the settings in the new tab like 8 times the last 3 days.

**Comment by dacap** [comment]
It might be related to using two different instances of Aseprite opened. E.g. you changes settings in one Aseprite instance and close it, then you close other Aseprite instance, this one might overwrite the former instance preferences.

**Comment by KashouC** [comment]
This isn't something I tend to do as Steam doesn't even launch a new window if you accidentally launch Aseprite again, and this bug keeps reappearing over and over again. I'll try to delete all the file settings in Roaming and see if it stops. Maybe there was something residual from an older version or something.

**Comment by dacap** [comment]
Thanks to the help of https://twitter.com/legacydev_ we've found this bug. The fix will be released in the final v1.2.
