### ISSUE TITLE
Current Frame Only option when saving multiframe files as pngs

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1381]
When I use Save Copy As in a format that doesn't support individual frames, on a file that has multiple frames, it displays a layer data "Warning" prompt (which is fine), then a frame iteration "Notice" prompt (which is where the problem is).

Agreeing to save out a series of png files (for instance), one for each frame, works properly and makes good sense, but I would have expected to be able to save the **current frame only** as an alternative to cancelling the save outright, and it might be nice to have this function added to the Notice prompt.

Functionally, what I'm expecting is something the same as Export Sprite Sheet with the 'Current Frame Only' and 'Visible Layers Only' options selected, but as a third option in Save Copy As (in addition to the current 'sequence of frames' and 'do nothing' choices) instead. This, in order to preserve more complicated Export options, and because it seems like a natural option to have in this situation.

This is kind of a low-priority thing, but it would make things a bit easier here and there, I think, if it can be done without crowding the Notice pane over-much.

Anyway, thanks for considering it!

..using ASEprite 1.1.11 on Win7SP1.

**Comment by dacap** [comment]
Hi @oceanhahn, did you try the new Save Copy As dialog on the beta version? http://imgur.com/HqUWr50 it contains the possibility to save/export selected frames only.

**Comment by oceanhahn** [comment]
Ah, no I haven't. I'm using the Gumroad version, so I don't have quick access to the beta branch.
The screencap you linked looks like what I'm after, though!

Thanks!

**Comment by dacap** [comment]
@oceanhahn please send me an email at support@aseprite.org in case you want a Steam key, your Gumroad purchase gives you access to a Steam key too :wink:

**Comment by dacap** [comment]
I think this one is already fixed.
