### ISSUE TITLE
Fill All Pixels Tool 

### ISSUE THREAD

**Issue by jackno** [aseprite/aseprite#1390]
Feature Request:

A paint bucket tool to fill all pixels of same color. This feature would make it easier to change the color of an outline, or separated areas without having to click the paint bucket on all of the areas.

This would be similar to the Piskel "Paint all pixels the same color" tool:
![piskel-fill-paint](https://cloud.githubusercontent.com/assets/8162609/21876178/1d2c9d88-d83e-11e6-9f5b-7aeaad9a21b8.png)

Here is an example of the tool in action (using Piskel):
![piskel example](https://cloud.githubusercontent.com/assets/8162609/21876279/e434354e-d83e-11e6-8fa3-7a7aa5cb5593.gif)

### Aseprite v1.1.13 and Win10

**Comment by Eiyeron** [comment]
Unchecking "Contiguous" when selecting the bucket does the same thing. (Can't upload a screenshot right now.)
