### ISSUE TITLE
.ase and .aseprite file format specification

### ISSUE THREAD

**Issue by Sarseo** [aseprite/aseprite#1391]
Hi, 

Could someone provide am .ase and .aseprite file format reference?  I'm looking to build a tool that will read directly from .ase and .aseprite files (importing).

### Aseprite and System version

* Aseprite version: v1.1.11
* System: Windows 10

**Comment by KasumiArai** [comment]
https://github.com/aseprite/aseprite/blob/master/docs/ase-file-specs.md

It's also included with some distrubutions in docs/files/ase.txt.

**Comment by dacap** [comment]
Hi @Sarseo, I recommend you to see the beta branch .ase file referece: https://github.com/aseprite/aseprite/blob/beta/docs/ase-file-specs.md (which include more information about Groups, Reference Layers, etc.)
