### ISSUE TITLE
Feature request: Video export

### ISSUE THREAD

**Issue by kyrieru** [aseprite/aseprite#1392]
Gifs have inconsistent frame speeds depending on the browser/device, and most video editing software will not properly detect fast frame speeds.

In these cases, it would be nice to have some sort of video format.

**Comment by zed9h** [comment]
Not sure if it would pay off to have a dependency like ffmpeg on aseprite, specially since you could easily convert the gif to video, with `ffmpeg -i exported.gif exported.mp4`, or even online on https://cloudconvert.com/gif-to-webm

**Comment by kyrieru** [comment]
I also thought an online tool for displaying frame speeds was fine until my internet went down and I couldn't use it for 3 days :/

As for the code I'm not aware of where it would be used.

**Comment by zed9h** [comment]
The ffmpeg for windows are here: https://ffmpeg.zeranoe.com/builds/ ...you could use that line on the cmd prompt, but you are probably better off with something like http://shedworx.com/smartconverter

**Comment by dacap** [comment]
I'd love to add video export support in a future, mainly on platforms that have a native API to export to video (related to #629).
