### ISSUE TITLE
Error Message when opening file?

### ISSUE THREAD

**Issue by Bohjo** [aseprite/aseprite#1393]
### Problem Description
When I try to load my Aseprite file it comes up this error message. There is nothing wrong with my aseprite because ALL other aseprite files work. I belive that my file is corrupted somehow.

### Links
http://prntscr.com/dwn5du (Error Message)
[File.zip](https://github.com/aseprite/aseprite/files/710248/File.zip) (Aseprite file not working)

### Aseprite and System version

* Aseprite version: 1.1.6,dev
* System: Windows 10

**Comment by SagePtr** [comment]
This file consists of 0x00 bytes only. It's definitely broken.

**Comment by Bohjo** [comment]
For me it says http://prntscr.com/dwrka5

**Comment by SagePtr** [comment]
For me: 
![image](https://cloud.githubusercontent.com/assets/3179266/22023355/817d27be-dcce-11e6-833d-06e5873885a6.png)

**Comment by Bohjo** [comment]
I double checked now, it's definetly broken. Thanks for the enlightment.

**Comment by Bobhostern** [comment]
If this issue has been resolved, could you please close this issue, @Bohjo? It's just a bit of housekeeping, and helps clear out resolved issues from the open list.

**Comment by dacap** [comment]
Hi @Bohjo, I've just close this issue. You can reopen it again if you came with another corrupted file (it might be related to an Aseprite bug).
