### ISSUE TITLE
feature request: pixel-perfect line mode

### ISSUE THREAD

**Issue by pixeljetstream** [aseprite/aseprite#1395]
Currently lines snap to some fixed angles via shift, with pixel perfect mode you would always get the closest line that has a "regular" stepping pattern (increment every N pixels / increment N every pixel).

**Comment by pixeljetstream** [comment]
I've played with a little code myself
https://github.com/pixeljetstream/luajit_gfx_sandbox/blob/master/samples/gl_pixelperfect_line.lua

![image](https://cloud.githubusercontent.com/assets/640162/22175005/c01be142-dfec-11e6-84a5-ee8a3c977c41.png)


you can run the sample from the "runtime" directory of the repository via "luajit ../samples/gl_pixelperfect_line.lua"

**Comment by pixeljetstream** [comment]
could it be what was implemented is not what this feature request is about? At least 1.2.6 still only allows a few directions with angle snapping, instead of many more

**Comment by dacap** [comment]
Yeah, the line algorithm was fixed but it still needs more angle snapping (new issue #1641 same as this I guess)
