### ISSUE TITLE
Export a single frame of an animation

### ISSUE THREAD

**Issue by Xeyler** [aseprite/aseprite#1397]
Hey, when I export an animation as a png, a notice pops up:

![image](https://cloud.githubusercontent.com/assets/11788703/22170698/a27c65ca-df3e-11e6-9f83-d798a72ade50.png)

Perhaps there should be the option to export just the frame you're currently on instead of exporting all of them as pngs or not exporting at all. 

### Aseprite and System version

* Aseprite version: v1.1.13
* System: Windows

**Comment by dacap** [comment]
Hi @Xeyler, actually the [beta version](https://www.aseprite.org/beta/) does have an option to [save the active/selected frame(s).](http://imgur.com/fDyDtnm)
