### ISSUE TITLE
Zoom takes two clicks

### ISSUE THREAD

**Issue by goobliata** [aseprite/aseprite#1398]
Zooming with the zoom tools ('z' hotkey) requires two clicks the first time it's used including when you change tools and go back to it. For example if I press 'b'rush then 'z'oom and left or right click it does nothing until I click again. After the initial two clicks, additional clicks work as expected. Not sure if this is intended behaviour or not.

Aseprite 1.1.12 on Windows 10 installed from installer.

May not be relevant but the system has a touchscreen (it's a small laptop) (sometimes touchscreens cause strange issues so I mention it here, but may be irrelevant.) I've had no issues with the touchpad besides this.

**Comment by Bobhostern** [comment]
This issue doesn't appear in v.1.2-beta7 (the latest beta).

**Comment by goobliata** [comment]
I don't believe it affects all systems. At least on my desktop with a mouse it's not affected. I don't have beta access to test though. Has there been fixes relevant to this issue recently?

**Comment by Bobhostern** [comment]
v.1.1.13 recently came out, so update, and try it again, unless you *really* want to use v.1.1.12.

**Comment by goobliata** [comment]
I'll try 1.1.13. Another note: seems to be not only the zoom tool. Also the bucket fill ('g') and possibly others, but not the brush ('b').

**Comment by goobliata** [comment]
Same result with 1.1.13.

**Comment by dacap** [comment]
Hi @goobliata, I'll take a look at this issue soon. I've to see if I can reproduce it first with my own touchpad. Do you know the touchpad driver which you are using? Or the specific notebook model, I could try to find something similar.

**Comment by goobliata** [comment]
1st please do not buy a notebook on account of this issue, as I've been living with it for a few weeks and it's not worth it. Here are the details though: it's a Dell Inspiron 11 inch system using a Dell touchpad driver. I don't have any other Windows laptops to test with but seems likely it would have been reported before if it was common.

**Comment by goobliata** [comment]
I've found the old backend executable and the issue persists with that as well, in case that information is helpful.

**Comment by dacap** [comment]
This might be the same issue as in #1401, for example, when I press the Z key, the touchpad is disabled for (I guess) a second, so I can click (on touchpad) several times and the Zoom tool doesn't work. Just after one second the touchpad starts responding again.

**Comment by goobliata** [comment]
Looks like that is it. If I wait a couple seconds it works. Maybe disabling settings related to "ignore touchpad movement while typing" would fix it (in touchpad settings). I'll close this. Thanks.
