### ISSUE TITLE
Space to pan is locked

### ISSUE THREAD

**Issue by goobliata** [aseprite/aseprite#1401]
Pressing space to pan on one of my systems locks the cursor from moving so it doesn't work. The cursor just doesn't move while space is pressed. Other systems work fine though.

Aseprite 1.1.13 for Windows from installer. System is a Dell Inspiron 11" notebook with touchscreen. I reported another issue (#1398) with the touchpad so it could be related.

**Comment by dacap** [comment]
Hi @goobliata, same problem here. It's related to the touchpad driver. The driver disables the touchpad when non-modifiers keys are pressed (and Space bar is not a modifier key, just Alt, Shift, Ctrl, Windows key and Menu key). It happens system-wide.

Here a screenshot of my driver: (Synaptics TouchPad V7.5):
![screenshot 2017-02-02 10 38 01](https://cloud.githubusercontent.com/assets/39654/22551509/c7a22d22-e933-11e6-859a-c3c81423e426.png)

This is a general Windows issue:
http://superuser.com/questions/399341/touchpad-does-not-respond-when-i-am-holding-key-on-the-keyboard and I don't think it can be fixed (e.g. Photoshop has the same issue).

**Comment by dacap** [comment]
This might be a solution for Dell: http://en.community.dell.com/support-forums/laptop/f/3518/t/19461214

**Comment by goobliata** [comment]
OK I thought that might be the case. Thanks.

**Comment by goobliata** [comment]
As for the solutions, neither of the two provided in that thread are for what I have, which might be actual Dell hardware rather than Alps or Elantech. Oh well, 'h'and hotkey works well enough!
