### ISSUE TITLE
Mouse lag when using certain tools

### ISSUE THREAD

**Issue by lonesurvivor** [aseprite/aseprite#1404]
In both the beta version and the stable one, the mouse gets really laggy whenever you use certain tools and move the cursor around a bit while holding down the left mouse button / pen. It is is smooth at the beginning, but depending on the distance the cursor travelled it gets more and more laggy until the button is released. Then, after 0.5 seconds or so the lag is gone. It seems to affect tools that have a preview of something that is not drawn immediately, e.g. line, rectangle, circle, polygon tool and additionally  the blur tool. The pencil, eraser, spray, jumble, contour and movement tool are not affected.

* Aseprite version: 1.1.10 (from AUR) / 1.2 beta 7 (self compiled)
* System: Arch Linux 64

**Comment by dacap** [comment]
For devs: please review this issue after #139

**Comment by dacap** [comment]
@lonesurvivor can you check if this is still reproducible in the [beta version](https://community.aseprite.org/t/get-aseprite-beta-version/22)?
