### ISSUE TITLE
Can't drag and drop files into Aseprite on Linux

### ISSUE THREAD

**Issue by eevee** [aseprite/aseprite#1410]
Dragging a file from my file manager (Dolphin) into an Aseprite window doesn't work.  It so aggressively doesn't work that the window _below_ Aseprite receives the drop instead, which I didn't know was even possible.  :)

A Windows-using friend tells me this works fine for them, but it never has for me.

### Aseprite and System version

* Aseprite version: v1.1.10-dev according to Aseprite, but built from an [AUR package](https://aur.archlinux.org/packages/aseprite/) that claims to be 1.1.11-3 and uses the v1.1.11 tag.  Last built on Dec 25.
* System: Arch Linux x64 w/ KDE

**Comment by dacap** [comment]
Hi @eevee, known issue related to #139

**Comment by h0lley** [comment]
there may not be as many people using Aseprite on Linux, but for those that do, I'd consider this a major issue or blocker for certain workflows. is there no chance of a workaround before #139 is finally ready?

**Comment by AleMunin** [comment]
Hey, I think I accidentally fixed this issue!

At least an work around!!

Edit: Right now after I was proofreading my markdown, I just noticed that this was closed 3 days ago. I am not sure if this is or will be an issue on steam for a lot longer. So here are my two cents just in case, my most profound apologies if I'm embarrassing myself.

I recently am using a new machine decided to tackle the problem that **Steam Aseprite does not integrate to the system**. I remember being on a conversation with David about it a year ago just to figure if it was a problem with my OS (I'm using Zorin, previously 15.2, now 16.2).

## Short Explanation

To sum up, steam IS NOT making a .desktop file on linux.

So this makes Aseprite not being listed ANYWHERE within the Desktop Environment. Your OS simply does not know it exists more than it would know an Appimage on its own.

**Drag and Drop on linux is working perfectly as it should. There is no need to patch that.** The main issue is that Linux has no idea aseprite can open ANY file, including .png and .jpg. or .gif.

## Step 1:

Open a text file, rename it to **aseprite.desktop**

## Step 2:

Paste the code bellow, but make adjustments to your system.

**Note: The paths listed on the file are done by me using steam's flatpak.
You can either replace the name "munin" there, or you can right click Aseprite on steam, and go to its own files, and find their equivalent there.**

I tried to replace /home/munin/ as a variable there, but it didn't work for me. Sorry for the inconvenience.

```
[Desktop Entry]
Name=Aseprite
Icon=/home/munin/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Aseprite/data/icons/ase256.png
Exec=/home/munin/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Aseprite/aseprite
Path=/home/munin/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Aseprite
Type=Application
Categories=Graphics;2DGraphics;GTK;
Terminal=false
MimeType=application/octet-stream;image/png;image/jpg;image/jpeg;image/gif;

```

## Step 3 

Save the file, and go to `/usr/share/applications/`.

Paste the file there.

Note: You can paste this file on `~/.local/share/applications`, this is what I did to integrate Aseprite on the system originally. However Nautilus was BEYOND ANNOYING to letting me find Aseprite to open .aseprite using the "pick an application" thing. usr/share solves it.

The solution to open .aseprite

## Step 4

Either log off and log-in again. Reboot or open the terminal and run `sudo update-desktop-database` to update the 

## Longer explanation

On my machines until now, apparently it was not just the lack of integration to the system, but specifically that the DE did not know that it could open `application/octet-stream` (aseprite files) and others.

This workaround makes aseprite open on search systems, being able to stay on plank, pinned, and will be listed if you right click a file.

This will not alter icons for .aseprite files, though.
