### ISSUE TITLE
Can't view layers

### ISSUE THREAD

**Issue by Snky** [aseprite/aseprite#1417]
Hello,
I am trying to run Aseprite on my Windows 10 x64 Surface Pro (tablet?), everything seems okay, just that I can't see the layers window (http://i.imgur.com/a0VABPE.png). I now notice if I log into my Steam account on another computer (Windows 10 x64 still), I can drag and hide the layers window completely, and there is then the option to make it appear again by *dragging up* just under the white line: http://i.imgur.com/oKEq207.png

Unfortunately, I cannot *drag up* on my tablet (assuming the layers window is just hidden, not turned off some how), so is there any other way to make the layers window appear? Shouldn't there be an option under 'view' to turn the layers on and off, and also, when turning on, to make it expand automatically to a certain extent, so this issue never occurs.

Aseprite version: v1.2-beta7 (Steam)
System: Windows 10 x64 (Microsoft Surface Pro)

I've tried compatibility modes, tried dragging (with mouse plugged in), to no avail.
The tablet isn't an excuse for there to be this issue, it can run AAA games and other software just fine.

**Comment by dacap** [comment]
Hi @Snky, did you try the View > Timeline menu option?

**Comment by Snky** [comment]
Oh... thank you, I didn't even notice it on the list, guess I was looking for a different wording. Damn.
