### ISSUE TITLE
Undo History disappears when closed using keyboard shortcut

### ISSUE THREAD

**Issue by cebolan** [aseprite/aseprite#1423]
For some reason, every time I close the Undo History window using the keyboard shortcut, I become unable to open it again, while this visual bug persists where it used to show up. Closing it with the X button seems OK though.

<img width="298" alt="screenshot 2017-02-24 18 11 15" src="https://cloud.githubusercontent.com/assets/2458684/23322998/ec6712fe-fabc-11e6-9960-6787b2b9088d.png">

### Aseprite and System version

* Aseprite version: 1.1.13 Steam version
* System: macOS 10.12.3, MacBook Pro, Early 2015

**Comment by dacap** [comment]
Thanks @tyllerj, I was able to reproduce it. I'll fix it for the next version.
