### ISSUE TITLE
Zoom with scroll wheel does not work for MX Master

### ISSUE THREAD

**Issue by frarees** [aseprite/aseprite#1426]
Seems Logitech's MX Master does not properly send mouse wheel events.

When `Zoom sliding two fingers up or down` is enabled, it does work, but it is impossible to handle due to _high sensitivity_.

Note that mouse wheel movements on this screencast are quite subtle (1-3 scroll notches)

![](http://i.imgur.com/JimxiLy.gif)

### Aseprite and System version

* Aseprite version: 1.1.13 (gumroad binary)
* System: macOS Sierra

**Comment by dacap** [comment]
Hi @frarees, it's strange that you have to check the `Zoom sliding two fingers up or down` option to zoom with the wheel. Definitely it looks like Logitech's driver (?) is converting mouse wheel into trackpad event to scroll (slide two fingers).

Does Logitech give you some settings for the mouse? E.g. like Wacom:

![screen shot 2017-03-03 at 10 20 13 am](https://cloud.githubusercontent.com/assets/39654/23552498/0796e728-fffb-11e6-9e61-844c6db80618.png)

**Comment by frarees** [comment]
It does indeed, [Logitech Options](http://support.logitech.com/es_es/software/options). It offers a quite reduced and simplistic interface, which looks like this

![](http://www.randomreviews.biz/wp-content/uploads/2015/07/Logitech-Options.jpg)

I've seen no option related to how the scroll wheel should behave (I guess it always should behave.. like.. a scroll wheel?)

But certainly, _looks like_ the drivers are generating trackpad events instead of mouse wheel events.

**Comment by dacap** [comment]
Did you try enabling/disabling "smooth scrolling" option?

**Comment by frarees** [comment]
Yeah... mainly tried every option. Don't have my MX Master with me now, but when I'm home I'll try uninstalling Logitech Options

**Comment by rauldeavila** [comment]
Same issue here. MX Master 3.

**Comment by snave2** [comment]
I think I might have fixed it, but only on a mac though. The problem is with the Logitech options app for customizing their mouse. If you go to activity monitor and kill the Logitech Options Daemon and go into system preferences->security & privacy->accessibility and uncheck the Logitech Options Daemon, it should work after you turn the mouse off and on again.

**Comment by Odaym** [comment]
> I think I might have fixed it, but only on a mac though. The problem is with the Logitech options app for customizing their mouse. If you go to activity monitor and kill the Logitech Options Daemon and go into system preferences->security & privacy->accessibility and uncheck the Logitech Options Daemon, it should work after you turn the mouse off and on again.

hmm, doing that did nothing here, Mac, I even tried to restore defaults before quitting.

By the way, **it works in Firefox**. Does not work in `Chrome` or `Brave` or `Safari`

**Comment by Gasparoken** [comment]
Same issue as https://github.com/aseprite/aseprite/issues/2695.

**Comment by Yaidier** [comment]
Same issue!
