### ISSUE TITLE
macOS compile error

### ISSUE THREAD

**Issue by kyle-mathis** [aseprite/aseprite#1435]
So I have been trying to figure this out for a the better part of a day no with no luck. I have Aseprite working on my laptop at the moment which is Windows 10 but no luck on my desktop. I did everything exactly as the INSTALL.md said as well.
It is macOS 10.12.3
Using the current version of Aseprite

--------------------------------------------------------------------------
Not really sure which of these you want/need.
This is the output of the cmake command(used command in INSTALL.md):
http://pastebin.com/xqyMQatf

CMakeError.log
http://pastebin.com/srEiPNYX

CMakeOutput.log
http://pastebin.com/RifGAz68

**Comment by dacap** [comment]
Hi @kyle-mathis, did you try to run `ninja aseprite` after that. It looks like the cmake command worked (from what I can see in the cmake output).

**Comment by kyle-mathis** [comment]
Well I have no idea what happened.
I had deleted the previous files and when I just went to redo it to get the ninja output everything worked perfectly. As much as I would love to know why I was failing so hard I won't argue with a good things. Sorry for wasting our time man, this is probably one of my favorite programs.
