### ISSUE TITLE
Problems with compilation on macOS

### ISSUE THREAD

**Issue by pretzelhands** [aseprite/aseprite#1440]
Hello dear Aseprite developers!

I seem to have encountered some trouble with compiling the master branch of this repository.
The CMake build seems to work fine, however upon trying to build the aseprite executable with ninja it fails about halfway through.

The full output can be found [on PasteBin here.](http://pastebin.com/x359srGc)

Any idea as to what might cause this? Harfbuzz and Freetype2 are both installed through Homebrew. If you need any additional information, I'll be happy to supply it. Thank you in advance!

### Aseprite and System version

* Aseprite version: 60970b8
* System: macOS 10.12

**Comment by dacap** [comment]
Hi @pretzelhands, did you update your repo with `git submodule update --init --recursive`?

**Comment by pretzelhands** [comment]
Hi @dacap! I did and just retried to do it just now. The chain of commands was:

```
$ git submodule --init --recursive
$ cd build
$ cmake \
  -DCMAKE_OSX_ARCHITECTURES=x86_64 \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 \
  -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk \
  -DUSE_ALLEG4_BACKEND=OFF \
  -DUSE_SKIA_BACKEND=ON \
  -DSKIA_DIR=$HOME/deps/skia \
  -DWITH_HarfBuzz=OFF \
  -G Ninja \
  ..
$ ninja aseprite
```

The `git submodule` had no output whatsoever; There's a big chunk of the CMake output and all of the ninja output here: http://pastebin.com/GCJZYWAD

Thanks for the help! :)

**Comment by mako** [comment]
Hi,

I got exactly the same issues.

Aseprite: [293f14c](https://github.com/aseprite/aseprite/commit/293f14cf4219e4042e70429cd42135a74d03675c)
System: macOS 10.12

**Comment by dacap** [comment]
Hi @mako and @pretzelhands, I've just committed [a change](9f594e8aa3f23e456f2c059fc20d9fdbea291443) that might fix this issue.

**Comment by zoltanmiko** [comment]
Hi @dacap,
It works for me!
Thanks!

**Comment by mako** [comment]
Hi @dacap ,
It works for me!
Thanks!

**Comment by dacap** [comment]
@mako you're welcome, thanks for testing, I'll close this issue but if the problem re-appears you can still comment and I can reopen it.

**Comment by pretzelhands** [comment]
Bit late to the party, but I just tried it again and it works for me too!
Thanks for the help and cheers! 👍
