### ISSUE TITLE
Bug: Can't change theme

### ISSUE THREAD

**Issue by michidk** [aseprite/aseprite#1441]
For some reason Aseprite won't let me apply my theme. No error appears. I updated all files to Aseprite v1.1.13 (inserted missing icons and lines of the sheet and skin file).

The newest version of the theme can be found here:
https://github.com/michidk/Aseprite-DarkFlat-Theme/

Read more:
https://github.com/michidk/Aseprite-DarkFlat-Theme/issues/1

### Aseprite and System version

* Aseprite version: v1.1.13, Steam
* System: Windows 10

**Comment by dacap** [comment]
Hi @michidk, I was able to load the theme on macOS:

![screen shot 2017-03-27 at 3 38 10 pm](https://cloud.githubusercontent.com/assets/39654/24372218/9d74ef86-1303-11e7-9acd-5a20c412b2fb.png)

Maybe this is a problem related to the Windows version, I'll test it on Windows later.

**Comment by iElektron** [comment]
Maybe you deleted deafault skin?

**Comment by michidk** [comment]
Nope, didn't delete the default skin.

**Comment by michidk** [comment]
Just tried it again and now it works. Didn't change anything to my theme. Did you release an Steam update to fix this, @dacap?

**Comment by dacap** [comment]
@michidk no, v1.1.13 is the latest (stable) one
