### ISSUE TITLE
Mac OS Sierra: Low performance in some areas (video demo)

### ISSUE THREAD

**Issue by oliver-ruehl** [aseprite/aseprite#1445]
Hello!

I'm having performance issues on my Mac with Aseprite.
The program works good in most parts, but i get a serious slowdown even on small projects when I replace color or drag windows.
I will investigate more and contribute here.

**It is best to look at this video to get an idea:**
* [https://www.youtube.com/watch?v=tAcgnq0c_xk](https://www.youtube.com/watch?v=tAcgnq0c_xk)

### Aseprite and System version

* Aseprite version: v1.2-beta7, Steam
* System: Mac OS Sierra 10.12.4, iMac 2009, 256MB Video Ram, 16GB RAM

**Comment by dacap** [comment]
Related to #1400

**Comment by dacap** [comment]
This should be fixed since v1.2-beta8 (f381cb972cdc83db9b19c10ede0af6f8fc3d7336)
