### ISSUE TITLE
Paste Location Altered When Copy Location Off Canvas

### ISSUE THREAD

**Issue by SolarLune** [aseprite/aseprite#1447]
When you copy and paste, the pasted item appears where you copied it, but if the item is off-canvas when you copy, the paste location becomes the center of the canvas (which can be disorienting if you were just expecting it to copy anyway, or copy just the portion of the sprite that's visible on the canvas).

### Aseprite and System version

Aseprite version: 1.2-beta7, Steam
System: Linux, Solus OS, 2017.1.1.0, 64-bit

**Comment by dacap** [comment]
Actually that is an expected behavior 🤔  If the center of the copied area is outside the canvas, when we paste it will be pasted in the center of the canvas instead of the original position (just to show to the user some feedback that the paste operation worked)

**Comment by SolarLune** [comment]
Hmm, still feels like a bug to me, as it's disorienting (to me, anyway) to have the copied sprite suddenly move to the center of the image / view. The user should know where the copy happened because they initiated it. I don't think there's a need to change the copy and paste location of an image just because it's off canvas.

**Comment by dacap** [comment]
> I don't think there's a need to change the copy and paste location of an image just because it's off canvas.

The problem here is that if we don't paste the clipboard content in the center of the editor's viewport, the user might never notice that he/she paste something (and that might be a problem for pixels with 0 < alpha < 255).

I'm not sure that pasting content outside the viewport would be a nice solution because the user would lost any kind of feedback about the Ctrl+V operation.

**Comment by SolarLune** [comment]
The pasted item has the floating box surrounding it, though - that shows that they pasted something. If you wanted to, you could just add an additional indicator that shows that something was pasted.

**Comment by dacap** [comment]
I'll show you my case with a gif where the original copied are is not visible anymore:

![original-position-is-not-visible](https://cloud.githubusercontent.com/assets/39654/26656146/45a8e3fc-4634-11e7-9ed2-c9dc1899ea82.gif)

You copy, scroll to other area, and paste. If the clipboard is pasted in the original position it would be not visible to the user.

**Comment by SolarLune** [comment]
OK, that makes sense - I'm talking about copying something that's off canvas, not off-screen. Here's an example of what I'm talking about:

![peek 2017-06-01 14-41](https://cloud.githubusercontent.com/assets/4733521/26702149/8cc33446-46d8-11e7-91f6-37e3f574474e.gif)

**Comment by dacap** [comment]
Oh ok! I'll take a look at this issue soon.

**Comment by KasumiArai** [comment]
Maybe only related, but it'd be cool to keep at least one axis if off screen (if possible) as well. Here's a case where that would have been nice:
![pastekeepaxis](https://user-images.githubusercontent.com/8582123/27468844-3e9970d0-57ba-11e7-80e5-c1dca6c6e150.gif)

**Comment by dacap** [comment]
This fix introduced a regression. Please [read this discussion](https://community.aseprite.org/t/problem-with-beta-10/108).
