### ISSUE TITLE
Aseprite uses internal headers of Freetype

### ISSUE THREAD

**Issue by winterheart** [aseprite/aseprite#1453]
Since last git additions aseprite uses internal functions of freetype that prevent to use and link external shared library:
```
[ 19%] Building CXX object src/ft/CMakeFiles/ft-lib.dir/stream.cpp.o
/home/winterheart/playground/aseprite/src/ft/stream.cpp:13:40: fatal error: freetype/internal/internal.h: No such file or directory
 #include <freetype/internal/internal.h>
                                        ^
compilation terminated.
```
Can we externalize this?

**Comment by dacap** [comment]
Hi @winterheart, I tried to do that but failed. Anyway I think in a near future I will remove the shared configuration (it makes maintenance unnecessarily more complex) and take a more google chrome-like approach.

**Comment by skrat** [comment]
Is there any solution to this? It fails to build.

**Comment by dacap** [comment]
@skrat you need to[ clone the repository with submodules](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#get-the-source-code)

**Comment by yurivict** [comment]
`USE_SHARED_FREETYPE=ON` is meaningless when internal parts are used. They aren't installed with the shared packages. You should stop using internal parts.
