### ISSUE TITLE
Aseprite Beta 1.2-beta8 UI Scaling Issues

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1456]
Lots of visual issues with the UI scaling again. 
Screen Scaling 100%
UI Scaling 200%
No buttons on don't save:
![image](https://cloud.githubusercontent.com/assets/8582123/25060492/b9b09890-216c-11e7-8a6a-8ca9fd9b8d87.png)
Huge checkmarks above text, no OK, Apply, Cancel buttons on preferences. Loading screen has no cancel:
![image](https://cloud.githubusercontent.com/assets/8582123/25060508/e591f896-216c-11e7-9d5f-6bf3ef413d11.png)
Small UI buttons on preview window (Note, the Aseprite beta window is inside the preview window):
![image](https://cloud.githubusercontent.com/assets/8582123/25060511/ff4d869c-216c-11e7-840d-72ff5016771a.png)
Tooltips pretty unreadable, don't erase properly:
![image](https://cloud.githubusercontent.com/assets/8582123/25060513/18279c98-216d-11e7-8717-26a60e0a8cb0.png)
Radio buttons on onion skin preferences:
![image](https://cloud.githubusercontent.com/assets/8582123/25060516/3d51f716-216d-11e7-910b-531ac5d863a1.png)
File menus aren't scaled, things like the the underlined letter for alt is bit, as are the arrows for more menu. (No screenshot, sorry)
Text isn't scaled in general:
![image](https://cloud.githubusercontent.com/assets/8582123/25060568/653ebdd0-216e-11e7-9810-ce29851d3afb.png)
Affects the hex color code being written on colors, context sensitive info in the bottom left.
Home Menu Gray Bars above the separated areas:
![image](https://cloud.githubusercontent.com/assets/8582123/25060583/b513cc92-216e-11e7-8c18-7c04ec654c19.png)

I'll update this if I find others? I guess the primary problem is that a fair amount of menus don't display buttons to click.

Aseprite 1.2-Beta8 (Steam/Portable)
Windows Vista 32 Bit

**Comment by KashouC** [comment]
Yeah, I got this as well.

**Comment by dacap** [comment]
Hi there! Yeah, sorry for this bug. I've already fixed it and I'm planning to upload an update on Monday (I want to wait just a couple of days just in case if another big issue appears). If you set UI scaling to 100% it should work ok, here some info: http://steamcommunity.com/app/431730/discussions/2/133262487499613719/
