### ISSUE TITLE
Bug: Can't change transparent color for gifs

### ISSUE THREAD

**Issue by josephan** [aseprite/aseprite#1462]
Can't change transparent color for gifs

### Aseprite and System version

* Aseprite version: v 1.1.13
* System: macOS Sierra

**Comment by josephan** [comment]
![screen shot 2017-04-19 at 4 01 53 pm 2](https://cloud.githubusercontent.com/assets/8878596/25199862/3f583178-251a-11e7-83a3-17c86b2942a3.png)
![screen shot 2017-04-19 at 4 01 42 pm 2](https://cloud.githubusercontent.com/assets/8878596/25199861/3f570f5a-251a-11e7-9643-e2c2c6eea1c5.png)
![screen shot 2017-04-19 at 4 01 46 pm 2](https://cloud.githubusercontent.com/assets/8878596/25199858/3f539ef6-251a-11e7-890f-7da3ddea26de.png)
![screen shot 2017-04-19 at 4 01 47 pm 2](https://cloud.githubusercontent.com/assets/8878596/25199860/3f56e282-251a-11e7-9ae5-eb70f143af8b.png)
![screen shot 2017-04-19 at 4 01 31 pm 2](https://cloud.githubusercontent.com/assets/8878596/25199859/3f56ac36-251a-11e7-9538-51b9bcc8e1af.png)

**Comment by josephan** [comment]
In the screenshots I change the transparent color from the dark grey to mask color and once I press ok it doesnt save

**Comment by dacap** [comment]
Hi @josephan, could you please try converting the Background layer into a transparent layer first (Layer > Background from Layer menu option).

**Comment by josephan** [comment]
@dacap That worked. Thank you!
