### ISSUE TITLE
 Suggestion: Add cursor move according to Grid instead of Pixel Grid

### ISSUE THREAD

**Issue by balalaXD** [aseprite/aseprite#1465]
# ▼now we at this point, next we will move cursor right a little.▼
![1](https://cloud.githubusercontent.com/assets/16096559/25265354/30d34bf2-269f-11e7-9cb5-02d32326269b.png)

# ▼ what we get instead.▼
![2](https://cloud.githubusercontent.com/assets/16096559/25265357/34c8dcf4-269f-11e7-9de9-f81c0c7b5568.png)

# ▼but i wanna this.▼
![qq 20170421142705](https://cloud.githubusercontent.com/assets/16096559/25265360/37c34d54-269f-11e7-8e5e-8d694689a45d.png)

**Comment by balalaXD** [comment]
Thanks you for your effort !

**Comment by dacap** [comment]
I think it's related to #723

**Comment by balalaXD** [comment]
so how to specify the center of the Grid?
i can't found the options.
I mean if 【Pixel Grid】 width = 1, height = 1,
                       【Grid】 width = 3, height = 3, 
then how to take Grid as Pixel Grid?
![0](https://cloud.githubusercontent.com/assets/16096559/25279564/69390240-26d9-11e7-9502-8004adbedb0e.png)
![1](https://cloud.githubusercontent.com/assets/16096559/25279565/6a98b234-26d9-11e7-85f4-d8f7e752f75f.png)

**Comment by dacap** [comment]
The option is not available yet. The issue #723 is still open.

**Comment by DanielJenkyn** [comment]
Couldn't agree more.

As a new user I was disappointed as I wanted to have the brush snap to the corner of the grid not the centre.

**Comment by dacap** [comment]
I'll fix the snap to the corner of the each grid cell for the next version.

**Comment by DanielJenkyn** [comment]
@dacap Really appreciate it. I know as a dev myself its hard when you have users screaming at you for features and fixes. (504 in this case!)

**Comment by DanielJenkyn** [comment]
Tested on latest beta on macOS Sierra, works like a charm. Can probably close the issue

**Comment by dacap** [comment]
I'll close this issue and if someone thinks it needs further discussion can comment (I think people can comment on closed issue 🤔 )

**Comment by DanielJenkyn** [comment]
They can for future reference ;)

**Comment by Doidera-FaiveZirou** [comment]
How to do this?
My cursor still move regardless of the grid :(
