### ISSUE TITLE
Unable to remove tag on a certain case

### ISSUE THREAD

**Issue by flamendless** [aseprite/aseprite#1467]
Im unable to remove a tag if its frames start and end at the same number (e.g start = 25, end = 25)

### Aseprite and System version
v.1.2-dev
Xubuntu 17.04

**Comment by dacap** [comment]
Hi there, did you try right-clicking the tag and selecting "remove tag"?

![remove-tag-with-right-click gi](https://cloud.githubusercontent.com/assets/39654/25278398/2a691a74-2679-11e7-952b-42e854f82d85.gif)

**Comment by flamendless** [comment]
Yes, but it's not actually removing it

**Comment by dacap** [comment]
@flamendless was you able to reproduce this bug in the latest beta (v1.2-beta9?) or in a more recent commit?
