### ISSUE TITLE
Blurry TrueType Fonts

### ISSUE THREAD

**Issue by 2dchaos** [aseprite/aseprite#1468]
When using Arial for example, the UI gets all blurry if you use Screen Scale at 200% and UI Scale at 100%.
![image](https://cloud.githubusercontent.com/assets/966426/25304667/e21effd6-277c-11e7-88ad-44d5cffeddd4.png)

Aseprite 1.2beta9 | Steam version | Win 10 64bit | 720p monitor

**Comment by 2dchaos** [comment]
This may actually do with ClearType and Windows. ;/ Not sure how to investigate this.

**Comment by dacap** [comment]
It's the antialias algorithm in the FreeType lib, try using antialias="false" in the <font> declaration, anyway the result might be worse (several TrueType fonts aren't prepared for tiny resolutions)

**Comment by dacap** [comment]
Maybe the font is too small, please feel free to send me a copy of the font that you are trying to use to support@aseprite.org
