### ISSUE TITLE
typo in the Aseprite specification (Layer Chunk)

### ISSUE THREAD

**Issue by benmoran56** [aseprite/aseprite#1471]
I've written a decoder for the Aseprite binary file format, and found a typo (I think). At the end of the **Layer Chunk** specification in the documentation: 
>   ...
>   BYTE          Opacity        Note: valid only if file header flags field has bit 1 set
>   BYTE[3]       For future (set to zero)
>   STRING        Layer name

I believe the "For future" should be BYTE[4], not BYTE[3].

**Comment by dacap** [comment]
Hmmm I think it's right, [here is the code that writes a layer chunk](https://github.com/aseprite/aseprite/blob/02b225868d76bdf69fd24c90de1ba1719c08abb9/src/app/file/ase_format.cpp#L956). Remember that a `STRING` fields has a header of 2 bytes (WORD) with the length of the string ([code that write the layer name](https://github.com/aseprite/aseprite/blob/02b225868d76bdf69fd24c90de1ba1719c08abb9/src/app/file/ase_format.cpp#L736)).

**Comment by benmoran56** [comment]
Thanks for the reply. I've pasted an example of what I get when I decode a layer:
```
flags:      3
type:       0
child lvl:  0
(ignored):  WORD * 2
blend mode: 0
opacity:    255
(zero)      BYTE * 3
name:       b'\x00Layer'
```
I was expecting just "Layer", without the extra bytes. Is this correct?

**Comment by dacap** [comment]
The first two bytes in the layer name is a WORD indicating the string length (in this case should be 5)

**Comment by benmoran56** [comment]
Thanks for the reply. When I look at the raw bytes, and I can see the "5":
> \x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x05\x00Layer

After the "Opacity" field, there are only 4 bytes remaining before the name:
> '\x00\x00\x05\x00Layer'

The ase-file-specs.md file says this:
> ...
> BYTE[**3**]       For future (set to zero)
> STRING        Layer name

Should the spec file be changed to this?:
> BYTE          Opacity
> BYTE[**2**]       For future (set to zero)
> WORD          Layer name length
> STRING        Layer name

**Comment by dacap** [comment]
I see 5 bytes between the opacity and the layer name:

    \xff \x00\x00\x00\x05\x00 Layer
           1   2   3   4   5

So opacity is 0xff, then three 0x00 bytes and then the string length. (Which is not just one byte, it's a WORD (2 bytes), so in your file you have `\x05\x00Layer` it is `\x05\x00` (`0x0005`) the length of the string `Layer`.)

**Comment by benmoran56** [comment]
You're right, the issue was that I had opacity = WORD in my code, not a BYTE! Sorry for wasting your time on this.

**Comment by dacap** [comment]
There's no problem @benmoran56!
