### ISSUE TITLE
Aseprite keeps soft-locking in Windows 7

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1475]
Talked with David about this a bit on Twitter, but since formatting my computer and reverting back to Windows 7 Professional x64, Aseprite keeps locking up randomly. (Did it around beta8 release)

It only partially freezes and you can still see the mouse in some cases, like when you hover over the timeline or palette instead of the drawing area, and it can all be fixed just by resizing the window and then restoring it.

I thought the issue was me running out of memory because Opera was devouring all my RAM, but it still happens after switching to Chrome, and I don't even go over 50% memory usage.

I'm going to try using the non-beta version for a little while and see if it still locks up, because I didn't have this issue in the past with Windows 7 with the same computer setup.

I'll leave some more detailed details this time:
Windows 7 x64
Aseprite v1,2-beta9

i5-3570k
Radeon HD 7950
16GB Corsair Vengeance DDR3 Ram
ASRock z77 Extreme4 motherboard

I'm not running any anti-virus programs, and barely anything outside of Steam, Discord, Slack, Skype, and Dropbox. It may very well be something up with my computer but I don't know what in that case.

**Comment by dacap** [comment]
You can temporally try to disable the auto-save of recovery data just in case to check if it's related to that: 

![screen shot 2017-04-26 at 8 12 03 am](https://cloud.githubusercontent.com/assets/39654/25431715/158cd356-2a58-11e7-8dbb-a49cb661a06b.png)

**Comment by KashouC** [comment]
I'll try that. I'm sure the power won't go out in my apartment while it's off or anything.

Gonna take a few days to test.

**Comment by dacap** [comment]
> I'll try that. I'm sure the power won't go out in my apartment while it's off or anything.

I hope so 😄  (make backups of everything and use Dropbox 😅 )

**Comment by KashouC** [comment]
I'm still not any closer to understanding this bug, but I can tell you that it's not because of the auto-save at the very least. I have also since re-formatted my computer AGAIN so it's definitely not some weird virus in the background.

**Comment by dacap** [comment]
@KashouC 👍  I'll be testing beta9 on windows in these days (crash reports + this issue) to see if I can reproduce the freeze

**Comment by KashouC** [comment]
I'm convinced this bug isn't Aseprite related. It happens in GIMP as well. I can't figure it out though.
