### ISSUE TITLE
'&' character in Select, Color Range Dialog

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1479]
![image](https://cloud.githubusercontent.com/assets/8582123/25552345/bc40b164-2c64-11e7-8905-53415017a271.png)
Note the '&' before Preview, OK, and Cancel. It doesn't affect how the program works, but it trips me out sometimes, I guess...

Aseprite v1.2-beta9 Steam on Windows Vista 32 Bit
* System: Windows/macOS/Linux, version, distribution

**Comment by dacap** [comment]
Already reported by other user by email too. I'll fix this for beta10.
