### ISSUE TITLE
Feature request: Save and recover edit histories.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1483]
Hey there!

This is kind of a C-list request, but I was hoping there might be some way to save out .ase files along with their histories, so that when we reopen them, their entire history stack is restored as well.

_I do not expect this to be on by default!_ I imagine that saving extended history tracks would become cumbersome after a while and maybe not many people would make good use of it. But if there were some way to preserve my edit histories between sessions for specific documents as an option, it would be a real boon to me. It would also be a useful thing to have for post-crash file recovery, maybe?

Probably it would be harder to implement than that..

Thanks for considering it! :D

..using ASEprite 1.1.13 on Win7SP1.

**Comment by dacap** [comment]
Duplicate #1324
