### ISSUE TITLE
feature request: support custom brush while picking color in canvas

### ISSUE THREAD

**Issue by kloworks** [aseprite/aseprite#1484]
hi, 
if you using a custom brush and you want to pick a color by pressing alt, the custom brush will return to normal brush.
example:
http://imgur.com/KigVPPb

it will be nice if I can pick a color without returning my custom brush to normal. :)

**Comment by kloworks** [comment]
> This is solved now isn't it?

yup it's solved : )

**Comment by KashouC** [comment]
Just found it when searching if my bug was already submitted. ^^ Figured I'd bump this thread so it could be closed.

**Comment by dacap** [comment]
👍 going to close this one right now, thanks for testing! ❤️
