### ISSUE TITLE
Bad compressed image.Warning

### ISSUE THREAD

**Issue by ShiaTheMLGPro** [aseprite/aseprite#1486]
I have recently lost work due to the following error///

Bad Compressed Image.Warning: Unsupported Chunk Type -1 (skipping)
Warning: Unsupported Chunk Type -1 (skipping)
Warning: Unsupported Chunk Type -1 (skipping)
Warning: Unsupported Chunk Type -1 (skipping)
Warning: Unsupported Chunk Type -1 (skipping)
Warning: Unsupported Chunk Type -1 (skipping)
Warning: Unsupported Chunk Type -1 (skipping)
Warning: Unsupported Chunk Type -1 (skipping)
Warning: Unsupported Chunk Type -1 (skipping)
Warning: Unsupported Chunk Type -1 (skipping)
Warning: Unsupported Chunk Type -1 (skipping)
Warning: Unsupported Chunk Type -1 (skipping)

v1.1.13 Aseprite and Windows 10

**Comment by dacap** [comment]
Hi @ShiaTheMLGPro, could you please send me your file at support@aseprite.org?

**Comment by ShiaTheMLGPro** [comment]
> Hi @ShiaTheMLGPro, could you please send me your file at support@aseprite.org?

I just sent over the file.

-S

**Comment by ShiaTheMLGPro** [comment]
It's happened AGAIN... This time with the following error.

ZLIb error -3 in inflater().Warning: Unsupported chunk type 154 (skipping)
Warning: Unsupported chunk type -1 (skipping).

Fix this shit or I want a refund.

**Comment by dacap** [comment]
@ShiaTheMLGPro I was not able to view your broken file yet. What kind of image (RGB or indexed, width, height, number of layers and frames) are you trying to edit? can you send me a previous version (working files) of your sprites?

**Comment by dacap** [comment]
@ShiaTheMLGPro Another thing, could you please try if it's reproducible in the v1.2-beta9 version?

**Comment by ShiaTheMLGPro** [comment]
@dacap The file was RGB, 640x360, 15 layers and no frames, just solid artwork. I tested it in the beta9 version and the problem is still there...

**Comment by dacap** [comment]
Just trying to figure out what could be go wrong in this situation (I'm testing loading/saving similar images right now), are you saving your images on an external disk? Do you have enough space on that disk? Did the program crash when saving the file? Do you have a red flag on the top-right corner ( http://imgur.com/9MTYI9k )?

**Comment by ShiaTheMLGPro** [comment]
Yes I backup all my work to an external HDD plugged in via USB; no the cable or drive is not faulty in the slightest and it currently has a remaining 900GB left, so space isnt the issue. No red flags or crashes as I am aware.

**Comment by dacap** [comment]
I've been testing/stressing the compression/decompression algorithm with thousand of random images, different patterns, several layers, etc. and wasn't able to reproduce a zlib problem (anyway might be a problem in the algorithm it self for a specific pattern, so I don't discard this possibility).

On the other side, could you please do a full scan disk to your external HDD? I suspect a couple of things: 1) the disk might contain corrupt sectors, or 2) the file wasn't completely flushed/synced on disk before it was disconnected (in case you connect/disconnect it regularly).

**Comment by ShiaTheMLGPro** [comment]
I disk a disk scan and repaired "something" on the HDD however the problem persists.

**Comment by dacap** [comment]
When you say that the "problem persist" does it means that if you create a new image, save it, and then load it you see the same error?

**Comment by ShiaTheMLGPro** [comment]
I mean I am unable to recover my previous artwork, despite the revival of the HDD, I can still save and load images with no issue, I will be a matter of time before this error springs up again.

I perhaps should have stated that I created my initial work on my desktop PC and used the HDD to transfer the work to my laptop when I'm not at home.

**Comment by dacap** [comment]
The problem is that if the file got corrupted on the HDD, there is no way to recover it. If you "moved" the file from your desktop PC to your HDD, the original file might still exists on your desktop PC as a hidden/deleted file, there are some programs to restore deleted files from your disk. Anyway I'm not 100% sure if this is related to a bad sector in your HDD or a bug on Aseprite.
