### ISSUE TITLE
Frame Increase/Decrease

### ISSUE THREAD

**Issue by JBoyAdvance** [aseprite/aseprite#1487]
I think you should make a frame increase/decrease option. In the Linux version from the software manager, you can only do it in the terminal. But this way us unfortunate Linux users don't have to worry, if there is, please tell me. Thanks and you're welcome!! 

### Aseprite and Xubuntu 17.04

* Aseprite version: 1.1.6, dev
* System: Linux, Xubuntu, 17.04

**Comment by dacap** [comment]
Hi @JBoyAdvance, are you talking about the window size? This is a problem of the version distributed by Debian (and Ubuntu, etc.), already fixed several years ago (related to #192)

You can try the official demo version: https://www.aseprite.org/trial/

Anyway I'm not 100% if we are talking about the same thing here 😅
