### ISSUE TITLE
Exporting to folders and creating them if not existing.

### ISSUE THREAD

**Issue by Dairnon** [aseprite/aseprite#1492]
Describe your bug report or feature request here

I'm using the Cli to export sprites from aseprite trying to export sprites into specific folders. I've found if the folder doesn't exist, the system would crash telling me it doesn't exist.  I'd have to manually create the folder for it to work. I'd like for if my destined path doesn't exist, it could make the folder for me. 
I've also a lot of the commands dont work like they did in older versions... 

Also stuff like --filename-format doesn't work the normal way anymore it seems... your forced to do it the --save-as way. If this is intentional it doesn't appear to be in the docs (still says you can use both)

Also ignore-layer isn't in the docs either

* Aseprite version:  v1.1.13-dev. I plan to buy the steam release soon rather then using the builds.
* System: Windows 7 Ultimate x64

**Comment by dacap** [comment]
Hi @Dairnon, do you have some examples of command lines that doesn't work as in older versions? (I try to keep backward compatibility with some automated tests, but it's probable that something is missing)

I'll add ignore-layer in docs too.

**Comment by dacap** [comment]
I forgot about the feature itself, I'm not sure if folders should be automatically created (maybe a special `--mkdirs` parameter or something like that).

**Comment by Dairnon** [comment]
So I've had to resort to using the in editor save-as and then writing
custom commands within the name section
issue with this that it works, however commands like {group} or {layer}
doesn't work...

As for the Cli... it seems like after the newer versions, anything beyond
like 1.1.9 broke many of the commands like using --layer
<https://www.aseprite.org/docs/cli/#layer>  --filename-format
<https://www.aseprite.org/docs/cli/#filename-format> or --split-layers
<https://www.aseprite.org/docs/cli/#split-layers>
(so in the image above, only the bottom command works, the top one was
working in 1.1.9, but now not in 1.2-beta9)

I could only ever get anything in the --save-as commands to work... and
then that wouldn't let me get things like (exclude layer) or (group)


I also noticed that it seems like a lot of the documentation on how to do
this isn't updated for the cli. ​


I basically wanna export ALL my groups I create, name the sprite the
{group}_{tag}_{tagframe0}.png

Id preferably like the ability to automatically export them out into
folders automatically creating using the whatever variable I'd want.
Ex: {path}\{group}\{group}_{tag}_{tagframe0}.png

So it export into path + a folder named after the group, with the settings
here

So if the sprite was named "Ayumi" and the pose was move2(down)

It be in folder ayumi, named ayumi_move2_0.png

As it stands I can't do much of this... and have to manually do this (since
again a lot of these commands wont work anymore for some reason and I can't
automatically generate folders). I must stress that the
 --layer <https://www.aseprite.org/docs/cli/#layer>  --filename-format
<https://www.aseprite.org/docs/cli/#filename-format> or --split-layers
<https://www.aseprite.org/docs/cli/#split-layers> do not work the intended
way And if its change, the documentation doesn't reflect that.

Also a --mkdirs could be neat

**Comment by Dairnon** [comment]
So I've had to resort to using the in editor save-as and then writing
custom commands within the name section
issue with this that it works, however commands like {group} or {layer}
doesn't work...

As for the Cli... it seems like after the newer versions, anything beyond
like 1.1.9 broke many of the commands like using
--layer
--filename-format
 --split-layers

![ss 2017-05-29 at 03 58 47](https://cloud.githubusercontent.com/assets/17523069/26563716/5175e478-448b-11e7-9d30-775f9c0852df.png)

(so in the image above, only the bottom command works, the top one was
working in 1.1.9, but now not in 1.2-beta9)

I could only ever get anything in the --save-as commands to work... and
then that wouldn't let me get things like (exclude layer) or (group)

![ss 2017-05-29 at 04 03 30](https://cloud.githubusercontent.com/assets/17523069/26563717/5ccab218-448b-11e7-9fd1-fc1d4b628843.png)


I also noticed that it seems like a lot of the documentation on how to do
this isn't updated for the cli. ​


I basically wanna export ALL my groups I create, name the sprite the
{group}_{tag}_{tagframe0}.png

Id preferably like the ability to automatically export them out into
folders automatically creating using the whatever variable I'd want.
Ex: {path}\{group}\{group}_{tag}_{tagframe0}.png

So it export into path + a folder named after the group, with the settings
here

So if the sprite was named "Ayumi" and the pose was move2(down)

It be in folder ayumi, named ayumi_move2_0.png

As it stands I can't do much of this... and have to manually do this (since
again a lot of these commands wont work anymore for some reason and I can't
automatically generate folders). I must stress that the
--layer
--filename-format
 --split-layers

Also a --mkdirs could be neat

**Comment by Dairnon** [comment]
What would also be nice is if you export a group, you could ignore layers within that group... 

I saw you posted some things about implementing that... or working that out... however I've yet to see any documentation or examples of how to get it work if it is in.

I recently bought the program and steam and love it so far, however I'd like to make exporting a bit easier. For my workflow. I export my sprites separately based on a specific naming scheme, then import into texturepacker, and pack them with a custom exporter+format.

**Comment by Dairnon** [comment]
I just wanted to check in and see if this was fixed? Being able to write out quick auto batch commands is very important for development.

**Comment by Ianuario** [comment]
Having groups in the command lines work just like layers/tags/slices do, for separation purposes, would be neato.

**Comment by dacap** [comment]
This was requested a couple of extra times:
* https://twitter.com/hepari00/status/976166817583509504
* https://community.aseprite.org/t/generate-folder-by-command-line/1540

I'll try to add this feature/fix in v1.2.9.
