### ISSUE TITLE
Please Add Alpha Channel in Bitmap Exports 

### ISSUE THREAD

**Issue by Nightro** [aseprite/aseprite#1495]
32-bit BMPs support an alpha channel. I've attached one I exported with pre-multiplied alpha from Pixel Former 
[SkeletonAttack.zip](https://github.com/aseprite/aseprite/files/1049408/SkeletonAttack.zip)

Ideally it would be using pre-multiplied alpha as in PixelFormer but I'd be happy with even just the alpha channel - here's a video of how it works in PS
https://www.youtube.com/watch?v=3LJCss690vs

These bitmaps can be loaded and displayed with transparency in SDL2 without any additonal libs. 

### Aseprite and System version

* Aseprite version: v1.1.13, Steam
* System: Win 10 x64

**Comment by Josh-Thompson** [comment]
Hello - is there any update on this issue? I would love to be able to do this.

**Comment by dacap** [comment]
I'll try to fix this soon for the next version.
