### ISSUE TITLE
Include frame duration warnings exporting/saving files as animated GIF

### ISSUE THREAD

**Issue by dxu** [aseprite/aseprite#1504]
Hi, I'm new to aseprite, just started using it yesterday. I was playing around with exporting gifs, but when I tried setting the frame durations on some frames of one of the files I was creating, after exporting the gif, the frames with <20ms looked much longer for some reason (possibly up to 100-200 ms if not more. Is this expected? I tried every duration from 15-19, but got the same results. 

Thank you for the lovely tool, and for your continued development and support for it!

### Aseprite and System version

* Aseprite version: v1.1.3, Steam
* System: macOS Sierra, 10.12.5

**Comment by dacap** [comment]
Hi @dxu, actually GIF files support a minimal frame duration of 10ms. It cannot contain less than that (well, it can be 0ms which Aseprite loads as 1ms). It's strange that a frame with less than 20ms has a longer duration after exporting the animation into a GIF. If you can share with me the .ase file and the resulting .gif file you can send them at support@aseprite.org, I'll be the only one seeing the files.

A possible problem is that Aseprite is saving frames with duration <10ms with 0ms but the player that you are using (maybe a specific browser) is loading the file with a bigger duration (e.g. converting 0ms into 100ms).

**Comment by thkwznk** [comment]
The same issue persists in versions 1.2.39-x64 and 1.3-beta20-x64.

**Comment by Gasparoken** [comment]
The GIF format has some limitations that aren't advised in Aseprite during Save As/Export command:
- The minimum frame rate will be 20ms (as this seems to be the 'standard' minimum frame rate supported by most browsers).
- The duration of each frame will be rounded to 10ms multiples.

I'll change the title to 'Include frame duration warnings exporting/saving files as animated GIF'

**Comment by dacap** [comment]
Yeah, there are some missing warnings saving GIF files, those are limitations that cannot be avoided so should be

**Comment by dacap** [comment]
There is another problem with all warnings but I'll create a new issue.
