### ISSUE TITLE
Layer Selection Feature!

### ISSUE THREAD

**Issue by hepari** [aseprite/aseprite#1509]
I'd like to have a functionality that enables me to make a selection from everything that's on the target layer. For example, in Photoshop, you would ctrl+click on the layer name in the layers list to select the contents of the target layer.
Could you add this functionality? :)

Aseprite version: Aseprite v1.2-beta9, Steam, beta
System: Windows 10

**Comment by dacap** [comment]
I think someone else ask me for the same think but I wasn't able to find the issue. It might be related to #1308 (so `Ctrl+T` keyboard shortcut could select the extension of all layers).

**Comment by chrleon** [comment]
Just wanted to chime in and say that I love this feature in the beta.

**Comment by hepari** [comment]
Thank you Dacap, the thing is that I need this to select the exact pixels that are on a layer, and not a rectangle that includes those pixels. They are two different functionalities.

Well, I know you have your own list of priorities, so I won't annoy you about this! :)

**Comment by dacap** [comment]
This will be available in v1.2.7

**Comment by dacap** [comment]
Some comments about this:

* On Windows/Linux will be Ctrl+click, on macOS this will be Command+click
* Ctrl+click = Replace selection
* Ctrl+Shift+click = Add/union selection
* Ctrl+Alt+click = Subtract selection
* Ctrl+Shift+Alt+click = Intersect selection

**Comment by hepari** [comment]
Thank you so much :D
