### ISSUE TITLE
RGBA/HSBA alpha channel slider preview is flipped?

### ISSUE THREAD

**Issue by dxu** [aseprite/aseprite#1511]
I believe that the alpha channel slider preview is flipped on the RGBA/HSBA color picker, see screenshot:

![screen shot 2017-06-06 at 9 47 34 pm](https://user-images.githubusercontent.com/718423/26862730-686a5880-4b02-11e7-8533-72f11ceb104c.png)

I would expect the slider to go from white to black from left to right with the alpha channel value from 0-255. Both the color well preview and the actual output of the color when I place it is correct.

### Aseprite and System version

* Aseprite version: steam version, 1.1.13
* System: macOS sierra

**Comment by dacap** [comment]
Hi @dxu, actually this is already fixed for the next release:

![screen shot 2017-06-07 at 10 40 51 am](https://user-images.githubusercontent.com/39654/26881456-d2f78f4a-4b6d-11e7-828d-5ea51735f6f7.png)
