### ISSUE TITLE
can't remove animation thumbnails

### ISSUE THREAD

**Issue by roguelion** [aseprite/aseprite#1518]
After checking the "force" option in the "thumbnails" setting of the animation timeline, the thumbnails  persist after clearing the "thumbnails" checkbox UNLESS I clear the "force" checkbox as well as the "thumbnails" checkbox. Just clearing "thumbnails" leaves the actual thumbnails visible in the timeline.

**Comment by dacap** [comment]
I think the "Thumbnails" checkbox is confusing. It was expected to be used only to hide/show thumbnails options, but I think that as you said, the user would expect to completely disable thumbnails unchecking this checkbox. I'll take a look to this issue.

**Comment by roguelion** [comment]
Thanks!
