### ISSUE TITLE
"BCryptDeriveKeyPBKDF2 could not be located" when starting Aseprite 1.2 beta10

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1520]
1. Double click Aseprite.exe.
2. See this error message:
![image](https://user-images.githubusercontent.com/8582123/27513021-d694caea-5924-11e7-8369-6d4b609c6197.png)

If it is launched from Steam, it just crashes (but does not give the above popup box)

Edit: Hmm, research seems to suggest this might be a corrupt dll on my end. A bit curious what changed that requires it for Aseprite, though. 

Edit2: Maybe not corrupt. Looking through the .dll itself, I've got BCryptDeriveKey, but not BCryptDeriveKeyPBKDF2. Seems that's Windows 7 minimum, heh. Gotta get off this Vista box. >_>

### Aseprite and System version
Affects Aseprite-v1.2-beta10-Portable and Aseprite-v1.2-beta10-Steam
Windows Vista 32bit

**Comment by dacap** [comment]
It looks like a dependency introduced by [libarchive](https://github.com/aseprite/libarchive/blob/master/libarchive/archive_cryptor.c#L62). We use this library now to uncompress `.zip` files. I think I might compile it without `Bcrypt.dll` dependency as I'd like to maintain compatibility with Vista (and XP if it's possible). Taking note about this issue.
