### ISSUE TITLE
trying to compile aseprite latest master branch

### ISSUE THREAD

**Issue by ninja542** [aseprite/aseprite#1521]
Describe your bug report or feature request here

I've compiled aseprite before, and I was successful in doing so, however, I'm trying to compile it again, and it is not working. I double-checked that everything was the latest possible, git pull master and the submodules are up to date. I did all the steps of compiling skia, and then cmake works (except it shows a lot of tests failing). 

I try to use the command "ninja aseprite", but then it gives a lot of errors.

I think the most important part of the error message is:
"FAILED: src/clip/CMakeFiles/clip.dir/clip.cpp.obj"

I recently installed another C++ compiler, so maybe that's it? I'm not sure. 

### Aseprite and System version

* Aseprite version: latest master branch
* System: Windows

**Comment by ninja542** [comment]
sorry for bothering you, I think it's because of MinGW

**Comment by dacap** [comment]
OK, please give a try with Visual Studio and see if you can compile it.

**Comment by ninja542** [comment]
yes it works, I just deleted MinGW and compilation works now. Thank you for responding!
