### ISSUE TITLE
can't click overlapping tags

### ISSUE THREAD

**Issue by daisyowl** [aseprite/aseprite#1523]
when a tag label overlaps (visually it appears underneath) the tag to it's right, you can't click on the second tag

<img width="81" alt="tagoverlap" src="https://user-images.githubusercontent.com/27868711/27757898-3635ad2e-5dbd-11e7-9a47-667e6ab120be.PNG">

i can't capture it with the screencap tool, but if i hover over the tag on frame 80, it selects the tag on frame 79

in this particular case i can hover further to the right and actually get the correct tag, but in some circumstances (lots of short tags) it makes tags completely unselectable

aseprite version 1.1.13 from humblebundle
windows 10

**Comment by dacap** [comment]
Hi @daisyowl , [this issue is already solved](https://github.com/aseprite/aseprite/issues/920#issuecomment-289330287) in the beta version.

[Try the beta version](https://community.aseprite.org/t/get-aseprite-beta-version/22)

Duplicated #920

**Comment by daisyowl** [comment]
oh sweet, i search but didn't find that. thanks!
