### ISSUE TITLE
Feature Request: Make the colour picker toggleable via hotkey again.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1527]
Hey there,

In beta9, F4 used to toggle the palette editor on and off, and I found that it saved a lot of time compared with having to hunt around with the sidebar version. I only recently updated to beta11 and discovered it had been changed to the unified colour selector, which, though very nice for a number of things, slows things down a bit for others.

It'd love to have the option of toggling the colour selector pane on and off back, even if doesn't have a key assigned to it by default. Dragging it away from its initial position does cause it to stick around, but once it's vanished, I have to go and tear off a new one the next time I need it which is a hassle compared to beta9. It was a huge help to be able to call up the pane with a keystroke instead of two or three mouse-clicks.

Thanks for considering it!
* It's possible that this still exists and I just missed the hotkey assignment, and if that's the case, please let me know!

Using ASEprite v1.2 b11 on Win10

**Comment by dacap** [comment]
Hi @oceanhahn, yeah I've to put it back, [here a discussion about it](https://community.aseprite.org/t/locked-unlocked-mode-in-color-bar/94/6?u=dacap). The idea is key `A` should switch the edit mode, `F4` should switch edit mode+show/hide popup (anyway it will be configurable, you should be able to configure keys to just show/hide the popup or/and switch edit mode). Also related to the new feature requested here #1526
