### ISSUE TITLE
Show animation length in the status bar

### ISSUE THREAD

**Issue by talecrafter** [aseprite/aseprite#1528]
The Status Bar could be used to show the complete length of an animation/tag when hovering it.
Similar to how the duration of a frame is shown when a single frame is hovered

It would also be useful to see the complete duration of the current selection of multiple frames, but I'm not sure when that should be displayed in the status bar as it's otherwise used to show information about singular elements.

**Comment by dacap** [comment]
Working on this one:

For one frame:
![screen shot 2017-07-28 at 2 20 58 pm](https://user-images.githubusercontent.com/39654/28728705-ff2e26d2-739f-11e7-90bf-494a88a1f9c4.png)

When several frames are selected (same when the focus is above a Tag):
![screen shot 2017-07-28 at 2 19 41 pm](https://user-images.githubusercontent.com/39654/28728650-d6514db6-739f-11e7-9ac7-752d7666b2a1.png)
Reference: frame [firstFrame...lastFrame] frameDuration [selectedRangeDuration]/totalDuration

**Comment by talecrafter** [comment]
Nice. :)

**Comment by dacap** [comment]
I'll cherry pick this change for v1.2.9, it is almost lost in a beta branch that I've already delayed a lot.

**Comment by dacap** [comment]
Already available in v1.2.9-beta2 in [Steam beta branch](https://www.aseprite.org/beta/)
