### ISSUE TITLE
Request: Preview Current Tag Only

### ISSUE THREAD

**Issue by hepari** [aseprite/aseprite#1529]
I noticed that the preview goes through all the animations in the current file.
But most of the time, I need to repeat just the range of frames under one single tag.
It could be a simple button on the preview window which we can toggle between two options:
Current Tag / All Tags

### Aseprite v1.2-beta11 , Win 10 64 bit

**Comment by hepari** [comment]
Well, this is awkward. I just went back to the program, and it's repeating the animation I'm working on right now. It must have been some glitch, else I can't explain it. Please remove this issue!!

**Comment by dacap** [comment]
Hi @hepari, I'll close this issue but if you see that it happens again or you can reproduce it, please fell free to comment this issue again.
