### ISSUE TITLE
Quantised colour channel values

### ISSUE THREAD

**Issue by grauw** [aseprite/aseprite#1535]
The MSX2 VDP has a 9-bit RGB range with 3 bits per channel. Several other systems like Mega Drive, TurboGrafx, etc. also use this colour range.

The MSX2+ VDP has a 15-bit RGB range with 5 bits per channel. Other systems like the SNES and GBA also have this colour range.

It would be nice if all the colour pickers could be restricted to these quantised values.

p.s. Previously (before edit) I mentioned the values weren’t linear, but this was a mistake on my part.

**Comment by dacap** [comment]
Duplicate #974

**Comment by grauw** [comment]
Hi dacap,

I had seen that issue actually, but since I figured it was about another topic, attribute clash (like only 2 colours on every 8 pixel line, or only 4 colours in an 8x8 block), albeit also a retro-oriented one, I opened this separate issue.

Anyway if you feel it’s more appropriate to log it there, I’m fine with that of course :).
