### ISSUE TITLE
CPU maxes out when you Ctrl-C a cel, and does not go back down again

### ISSUE THREAD

**Issue by brokenbeta** [aseprite/aseprite#1537]
Open this file: [filled.zip](https://github.com/aseprite/aseprite/files/1156228/filled.zip)  
(it's quite large, but not a contrived example -- the project I'm working on is the same size)

CPU and aseprite performance should be good.

Click any filled cel in the timeline and press Ctrl-C to copy.

CPU starts going crazy, performance drops, and it becomes very hard to draw well because performance is so bad. Even when you sit there and do nothing and just wait, aseprite just spins the CPU like crazy and never stops.

I hope to God you can reproduce this, because it's been driving me mad for ages.

### Aseprite and System version

* Aseprite version: v1.2-beta12, Steam
* System: Windows 10 Home

**Comment by dacap** [comment]
I was able to reproduce it in some way (it doesn't use 100% CPU, but it uses 1% to 2% constantly). It's because the [marching ants effect](https://en.wikipedia.org/wiki/Marching_ants), it constantly redraw the timeline. I'll see how I can improve this situation.

**Comment by brokenbeta** [comment]
Awesome. Even knowing that has helped me out. Now I see that if I make the marching ants go away by pressing Alt+N then CPU returns to normal, which is a great workaround for now, thank you.

**Comment by dacap** [comment]
You can also use the `Escape` key too to just remove the marching ants.
