### ISSUE TITLE
Custom Brush Causing Selection Box Glitch

### ISSUE THREAD

**Issue by hepari** [aseprite/aseprite#1540]
For the recording of the glitch in action, please watch this video: https://youtu.be/yUIjfwmLQj0

Having created a new brush causes the selection box to go crazy instead of snapping to grid.
Is this intended, or am I doing something wrong?

**Comment by dacap** [comment]
Thanks for reporting this @hepari! I hope to have the fix ready for the final v1.2.

**Comment by hepari** [comment]
@dacap You are welcome! :D

**Comment by Gasparoken** [comment]
It looks like it's already fixed in v1.2.9
