### ISSUE TITLE
Allow brush patterns for fill tool

### ISSUE THREAD

**Issue by jeroenjacobs1205** [aseprite/aseprite#1542]
I can only use a solid color when filling a selection made with the lasso tool.

I wanted to fill this area with a dithered pattern, so I created a brush like this:

FB
BF

(F = foreground color, B = background color).

But like I said, I can't select a brush when the fill tool is active.

How can I create a dithered fill patterns in a selection? This seems such a straightforward task for a pixelart drawing program, but I can't find a way to do this in an intuitive manner.

**Comment by jeroenjacobs1205** [comment]
Could be some kind of bug. When I switch to the pencil tool, and then back to the fill-tool, I have the option to select a brush.

This is version 1.1.13 on OSX (bought in the Steam store).

**Comment by dacap** [comment]
Maybe a bug on v1.1.13, in v1.2-beta12 seems already fixed.
