### ISSUE TITLE
Bug / Feature Request: Restore relative-value colour picker.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1549]
Could you restore the relative-value mode to the colour-picker? It was very useful for making minor adjustments to large segments of a palette and for making alternate palette sets and I'm finding it hard to operate without it. As it is now, trying to alter a range of palette indices only makes _all of the index values absolutely equal to the new colour,_ which is not really the behaviour I would expect (and not one I can find a use for).

It would be great to have a relative mode back alongside the absolute mode in the colour picker, as soon as possible.
Thanks!

Using ASEprite 1.2-beta12 on Win10.

**Comment by dacap** [comment]
Hi @oceanhahn, the relative mode was replaced with the new Hue/Saturation command (*Edit > Adjust Hue/Saturation* or `Ctrl+U`). You can select several color palette entries and then Adjust Hue/Saturation.

**Comment by oceanhahn** [comment]
Aa. That's a little harder to reach but I can just fiddle my hotkeys.
Thanks for letting me know! :D
