### ISSUE TITLE
Shading at a later time not working?

### ISSUE THREAD

**Issue by bloggy** [aseprite/aseprite#1556]
Hi there,

I wonder if that is a feature or a bug: I draw something. Then I use shader effect (spray tool) on it. Then I work on another layer, paint something etc. Then I switch back to the layer and try to use shader effect again, but this time nothing happens. Why is that?

**Comment by dacap** [comment]
Hi @bloggy, do you have more details about this? Actually I don't understand if you call "shader effect" to the spray tool or to the "[shading ink](https://www.aseprite.org/docs/inks/)"
