### ISSUE TITLE
Grid visibility, sometimes unchangeable via hotkey

### ISSUE THREAD

**Issue by kyrieru** [aseprite/aseprite#1558]
If I set either "show extra" or "show grid" to a hotkey (in my case, G), pressing the button will toggle it as expected, but then after a while of having the grid deactivated, it will not reactivate with the hotkey unless I enable it through the menu.

**Comment by dacap** [comment]
I wasn't able to reproduce this issue, but I'll need more time to test and see if the `G` key just stop working.
