### ISSUE TITLE
Unable to access clipboard data between windows on Linux

### ISSUE THREAD

**Issue by KelvinShadewing** [aseprite/aseprite#1561]
When I copy something in Aseprite, I'm unable to paste it into anything other than the window I copied it from, even when copying between instances of Aseprite. I don't have problems copying things between other programs, just copying from Aseprite to anything else. Also, dragging images onto the window from Thunar doesn't open it.

Running Aseprite version 1.1.13 on Linux Mint with XFCE.

**Comment by dacap** [comment]
Duplicate #1100
