### ISSUE TITLE
Rectangular Marquee Tool + Snap to Grid - Inaccurate

### ISSUE THREAD

**Issue by hepari** [aseprite/aseprite#1562]
As the title says, the marquee tool doesn't work properly, always leaving 1 pixel at the top and on the left side. It was fine a few days ago, and I don't know what is causing this. It's a pretty urgent issue, since this makes working with tilesets very tiresome.

![capture-20170825005](https://user-images.githubusercontent.com/10383640/29714016-70bf4d32-89a1-11e7-97d7-88005a166565.png)

**Comment by dacap** [comment]
Known issue, it's because the brush size is set to 2px for the selection tool (but you cannot see the brush size in the context bar, it's a bug). Press the - (minus) key to reduce the brush size to 1px and you will see that this should be fixed. (This bug is already fixed for the next release.)

**Comment by hepari** [comment]
Thank you very much for your help! I was dying inside because of this
issue. It really fixed the problem :D
