### ISSUE TITLE
New layer from selection

### ISSUE THREAD

**Issue by Kizu0** [aseprite/aseprite#1567]
Hello is it possible de create a new layer from the selection on another layer? (Like decomposing a character on different layers without dupplicating everything, selection, inverting the selection and erasing as I do now) 
Thank you

Asesprite version beta
Windows

**Comment by KashouC** [comment]
Wouldn't just cutting (Ctrl+X) and creating a new layer (Shift+N) then pasting work?

**Comment by fluffbirb** [comment]
It's quite tedious when working with multiple frames, like in my current doc with 32 frames.
Also every time you paste, it deselects, so the process becomes:
- select
- 
-

**Comment by dacap** [comment]
Related to #996 and #475 in some way (e.g. we should be able to record the steps and reproduce them).
