### ISSUE TITLE
Bug: "Rewind on Stop" incrementing start frame randomly

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1569]
"Rewind on Stop" keeps incrementing the starting frame by one randomly. I don't know what causes this or how to recreate it, but I made a video of it happening:

https://www.youtube.com/watch?v=v8nuVRj2Tgk

Aseprite 1.2-beta12
Windows 7 x64

**Comment by dacap** [comment]
Thanks @KashouC, I'll take a look at this. For me the "Rewind on Stop" should go back to the exact frame where the animation was started/play button was pressed.
