### ISSUE TITLE
Please allow indexed pngs to NOT store transparent bit

### ISSUE THREAD

**Issue by bfloch** [aseprite/aseprite#1572]
**Describe your bug report or feature request here**
I have not found a way in aseprite to not have transparency in palette images, therefore I think at least an option to **not** write the tRNS bit in pngs should be given. Possibly other formats, too.

Basically I think this guy should be optional:
https://github.com/aseprite/aseprite/blob/master/src/app/file/png_format.cpp#L458

This command line tool called `pngcrush` does pretty much fixes it for me as workaround:
```
pngcrush -rem tRNS input.png output.png
``` 

### Aseprite and System version

* Aseprite version: 1.1.13, Steam
* System: Linux, 4.12.8-300.fc26.x86_64, Fedora 26

**Comment by dacap** [comment]
I forgot about this one, will fix this for v1.2.1
