### ISSUE TITLE
Add support for Color profiles (ICC)

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1576]
There were an issue about this but I cannot find it. Anyway I'll start writing the list of task to do this here:

- [x] Libraries: [Skia SkColorSpace](https://github.com/google/skia/blob/master/include/core/SkColorSpace.h), ~~[LittleCMS](https://github.com/mm2/Little-CMS), etc.~~
- [x] Check https://skia.org/user/sample/color
- [x] Use a test suite like: https://kornel.ski/en/color
- [ ] Add color management options (load/save embedded profiles, options to assign/convert color profile in a sprite)

----

Review these issues:
* https://community.aseprite.org/t/colors-displaying-differently/413
* https://community.aseprite.org/t/export-color-loss/1421
* https://community.aseprite.org/t/color-display-wrong-on-mac/1970

**Comment by dacap** [comment]
Thanks for the tip @mysterycoconut, I'll take a look to this issue in these weeks.

**Comment by cloewen8** [comment]
I recently ran into an issue with Affinity Designer improperly displaying a gif from Aseprite. It reported that a color profile was missing. Having Aseprite export with a color profile would help me out a lot!

**Comment by dacap** [comment]
I'm already making some progress on this issue:

![screen shot 2018-10-15 at 17 28 53](https://user-images.githubusercontent.com/39654/46976417-d5ca9100-d09f-11e8-82e7-4e897295ea32.png)
