### ISSUE TITLE
Can't rename layers using the letter t

### ISSUE THREAD

**Issue by catherineomega** [aseprite/aseprite#1577]
I can't rename layers consistently, because if I type the letter T, the text tool starts up. Additionally, copying and pasting text into a new layer name seems not to work either, it pastes it as text using the text tool.

Is this possibly related to #1103 ?

### Aseprite and System version

* Aseprite version: 1.2/installer
* System: OSX El Capitan 10.11.6

**Comment by dacap** [comment]
Known issue, this will be fixed with a patch today.
https://community.aseprite.org/t/i-cant-input-f-when-renaming-layer/480
