### ISSUE TITLE
2 Icons on Ubuntu

### ISSUE THREAD

**Issue by goobliata** [aseprite/aseprite#1578]
![screenshot from 2017-09-27 23-27-39](https://user-images.githubusercontent.com/766383/30950738-0e79a67c-a3dc-11e7-9aff-99e6e47d5133.png)

As seen in the screenshot on Ubuntu 16.04 with Unity WM there are 2 icons, the regular one (which I have docked) and the question mark that appears after launching it.

Might not be in newer Ubuntu but I think this is a regression in Aseprite as it didn't always do this.

Aseprite 1.2.1. Ubuntu 16.04 from amd64 .deb.

**Comment by dacap** [comment]
The Linux version needs some love, I'm taking note about this one.

**Comment by goobliata** [comment]
Oddly I just opened aseprite a few times today and this doesn't happen. Fixed itself I guess.
