### ISSUE TITLE
--list-splices --split-layers --sheet creates duplicate data in meta.slices

### ISSUE THREAD

**Issue by nphyx** [aseprite/aseprite#1582]
Possibly related to #1234.

When --list-slices is combined with --split-layers --sheet to create a combined atlas (as per https://www.aseprite.org/docs/cli/#export-each-layer-as-a-different-animation-in-the-same-sprite-sheet), the `meta.slices` array contains duplicate entries, one per slice per layer. The entries are completely redundant - they don't contain different keys entries per layer.

For example, with two layers "layer-1", "layer-2" and one slice, "my-slice", output would be:

```javascript
{ 
"frames": { "mysprite (layer-1).ase":{...},"mysprite (layer-2).ase":{...}},
"meta":{ ...
    "slices":[
        {"name":"my-slice", ... "keys":[{/* key data for layer-1 */}]}
        {"name":"my-slice", ... "keys":[{/* key data for layer-1 */}]}
    ]}
```
}
Note that both slices contain key info for *layer-1*.
The two entries are completely redundant, and present the bounds data for the base layer. A desirable alternative would be something like:

```javascript
{ ...
"meta":{ ...
    "slices": [
        {"name":"my-slice", ... "keys":[
            {"frame":0, bounds: {/* bounds for layer-1 */}},
            {"frame":1, bounds: {/* bounds for layer-2 */}}
        ]},
    ]
}
```
Example input/output: [bugged.zip](https://github.com/aseprite/aseprite/files/1347116/bugged.zip)

To reproduce, use:
```bash
aseprite -b --list-slices --split-layers aseprite/bugged.ase --data bugged.json --sheet bugged.png
```

### Aseprite and System version

* Aseprite version: 1.2.2 Steam / Beta
* System: Linux 4.12.8 / Arch

**Comment by johanwendin** [comment]
same thing with --list-tags when combined with --split-layers, the tags will repeat (in order) once per layer.
