### ISSUE TITLE
Occasionally Cannot Move Selections

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1584]
Sometimes when I make a selection, I cannot move it by clicking and dragging. In old versions, the mouse used to change to a different when you moused over a selection. Now, it never changes.

Sometimes I can move the selection and sometimes I cannot. I can't tell what makes the difference if I can or can't, since the icon doesn't change. I can click and it'll work, and I can click and it can not.

![cannotmoveselection](https://user-images.githubusercontent.com/8582123/31138336-18b94962-a83c-11e7-9f4f-faa9ff12aeba.gif)
I am holding down no keys when I do this, and as can be seen the Marquee Tool is active. 

Here is me moving a selection without the icon changing until after I click:
![movingwithouticonchange](https://user-images.githubusercontent.com/8582123/31138291-f04c7b0c-a83b-11e7-83c8-2e84cfa0e28d.gif)

My keyboard shortcuts file, which may be related. I disabled shift to add selection because I liked being able to press shift _before_ I clicked to drag. Everything used to work in latest beta, and I have changed nothing that I am aware of.

[asepritekeyboardshortcuts.zip](https://github.com/aseprite/aseprite/files/1353231/asepritekeyboardshortcuts.zip)

Edit: Ah. I am on "Add to selection mode". In previous versions I used this so I could add/move with left click, and subtract with right click. No keyboard keys needed to add, subtract OR move the selection. Perhaps it is this mode that has changed. I very, very much prefer how it was in 1.2-beta12 if it has changed.

Aseprite v1.2.2 Steam, Windows Vista 32 Bit

**Comment by dacap** [comment]
Hi @KasumiArai, this is related to this bug fixing:
https://community.aseprite.org/t/marquee-tool-add-subtract-to-selection/470/9

I'll revert part of the behavior and add a new option in Edit > Preferences > Selection to switch to the new behavior (at least for the Add selection mode).

**Comment by dacap** [comment]
The new option (checked by default):

![screen shot 2017-10-03 at 15 00 18](https://user-images.githubusercontent.com/39654/31140729-ad12ec3a-a84b-11e7-8d05-0c9d4cecad61.png)
