### ISSUE TITLE
Black screen on Linux (Steam release, Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by DivineOmega** [aseprite/aseprite#1590]
When starting Aseprite via the 'Launch' button in Steam, or via the terminal, a windows opens maximized with the title 'Aseprite v1.2.3', but with no content. The window content is blank (just black). Unfortunately, no debug information is output to the terminal.

Here's a screenshot: https://i.imgur.com/3issvUL.png

### Aseprite and System version

* Aseprite version: v1.2.3 (latest on Steam at time of typing)
* System: Linux 64-bit (Ubuntu 16.04 LTS)
* Graphics card: GeForce GTX 1060 6GB, using NVIDIA driver version: 375.66

**Comment by DivineOmega** [comment]
Extra note, this black window is completely unresponsive, and can not even be closed. The process needs to be forced close.

**Comment by DivineOmega** [comment]
I have attempted fully removing Aseprite via Steam and re-downloading it. Unfortunately, this had no effect.

**Comment by dacap** [comment]
Sorry the late response in this one. Is this still not working on v1.2.4? Did you try resizing the window?

**Comment by Siilwyn** [comment]
I'm having the same problem on Ubuntu 16.04 with version 1.2.6.

**Comment by Siilwyn** [comment]
Tried download older versions from the Steam depot but the older versions won't launch because of a different data structure. :(

**Comment by DivineOmega** [comment]
Sorry, I should have got back to this issue earlier.

I found that a simple restart of my system fixed the issue.

**Comment by Siilwyn** [comment]
Oh weird, that solved it for me as well. So after updating the app there needs to be a reboot.

Thank you for your reply!

**Comment by dacap** [comment]
Thanks for the feedback both of you! That's sound strange, something to check in a future when the new back-end for Linux is ready #139 too

**Comment by grimmy** [comment]
Clean install, same issue.  If i have to reboot to play your game on a clean install, there's something seriously wrong here.  I don't even reboot for video driver updates.

At any rate, it does seem like the game is playing, as by clicking/hitting spacebar, I'll get some text.  It mentions some connection window on the right, which isn't visible, and then after it says "hit the HACK_IT button" there's no button visible.  I found it in the bottom left corner by brute force.

Here's what I'm seeing.  ![hack_it](https://user-images.githubusercontent.com/1396385/34470937-d67fb57e-ef01-11e7-8350-19ebafdb8e71.png)

**Comment by tiskolin** [comment]
I'm still having this issue with Aseprite v1.2.9 through Steam on Ubuntu 18.04.1 LTS. As @DivineOmega said, it is completely unresponsive. However, after a couple of minutes, it does close after being asked to do so. I haven't tried rebooting yet, however.

**Comment by tiskolin** [comment]
Ok, rebooting fixed the issue.
