### ISSUE TITLE
Buttons act strange.

### ISSUE THREAD

**Issue by Miroware8** [aseprite/aseprite#1592]
Buttons activate when the mouse was only released on them, even though it was pressed somewhere else. This can actually be confusing in some cases. For example, I tried to duplicate a frame by clicking and dragging while holding `ctrl`, and it took me a whole minute to realize that the reason my entire image was transparent was that I released my mouse while it was over the hide button. It would be better in my opinion if you had to press _and_ release on the same button to activate it.

### Aseprite and System version

* Aseprite version: 1.2.3, installer
* System: Windows 10

**Comment by dacap** [comment]
This will be available in the first v1.3 beta
