### ISSUE TITLE
Pen no longer works in Aseprite with Windows 10 Fall Creators Update

### ISSUE THREAD

**Issue by amzeratul** [aseprite/aseprite#1595]
We've had an issue this morning on multiple machines, after they received the Windows 10 Fall Creators Update. Pen input, which worked fine before, stopped working in Aseprite.

To be more specific, attempting to use the pen would sometimes have no effect, or sometimes scroll instead of using the selected tool. Very rarely (about 1 in 15 times, they report) it would behave correctly, using the selected tool as expected. The artists affected also reported that while trying to use it on the scroll bar, the scroll bar would react visually as if the mouse was hovering it, but attempting to drag it would have no effect.

Pen input still works correctly on other programs, such as Adobe Photoshop. Reverting the Windows update makes Aseprite work again (and is our temporary workaround), but is not a long-term workable solution. We would really appreciate a fix for this, as we have a lot of people here using Windows 10 and Aseprite. :(

### Aseprite and System version

* Aseprite version: Aseprite v1.2.3-x64
* System: Windows 10 Pro, x64, Version 1709, OS Build 16299.19
* Computer: Microsoft Surface Studio

**Comment by dacap** [comment]
Hi @amzeratul, I'll be working on this issue today as it was already reported by a couple of other users. I have a Surface Pro to test it so a fix might appears next week ASAP.
