### ISSUE TITLE
Bitdefender blocks the linking process of Aseprite with skia backend

### ISSUE THREAD

**Issue by yvanc** [aseprite/aseprite#1597]
Whenever I try to compile aseprite with skia backend, during the linking process, bitdefender blocks it like it's some kind of virus. Here's a screenshot.

https://imgur.com/a/6PyW0

Log is as follows;

[1/1] Linking CXX executable bin\aseprite.exe
FAILED: bin/aseprite.exe
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=src\CMakeFiles\aseprite.dir --manifests ..\src\main\settings.manifest -- C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo src\CMakeFiles\aseprite.dir\main\main.cpp.obj src\CMakeFiles\aseprite.dir\main\resources_win32.rc.res  /out:bin\aseprite.exe /implib:lib\aseprite.lib /pdb:bin\aseprite.pdb /version:0.0  /LTCG  /subsystem:windows -LINK wsetargv.obj -ENTRY:"wWinMainCRTStartup"  lib\app-lib.lib kernel32.lib user32.lib gdi32.lib comdlg32.lib ole32.lib winmm.lib shlwapi.lib psapi.lib wininet.lib comctl32.lib dbghelp.lib lib\dio-lib.lib lib\filters-lib.lib lib\flic-lib.lib lib\render-lib.lib lib\doc-lib.lib lib\fixmath-lib.lib lib\ui-lib.lib lib\clip.lib lib\she.lib lib\gfx-lib.lib lib\ft-lib.lib C:\deps\skia\out\Release\skia.lib "C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x86\OpenGL32.Lib" lib\pixman.lib lib\obs.lib lib\undo.lib lib\cmark_static.lib lib\jpeg.lib lib\giflib.lib lib\libpng16_static.lib lib\freetype.lib lib\harfbuzz.lib lib\freetype.lib lib\harfbuzz.lib lib\ucdn.lib lib\json11.lib lib\archive_static.lib lib\zlibstatic.lib lib\script-lib.lib lib\mujs.lib lib\updater-lib.lib lib\cfg-lib.lib lib\net-lib.lib lib\laf-base.lib lib\modpbase64.lib lib\..\libcurl.lib ws2_32.lib lib\tinyxml.lib winmm.lib shlwapi.lib dbghelp.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK : warning LNK4044: unrecognized option '/LINK'; ignored
LINK : /LTCG specified but no code generation required; remove /LTCG from the link command line to improve linker performance

C:/Program Files (x86)/Windows Kits/8.1/bin/x86/mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "bin\aseprite.exe". Access is denied.
ninja: build stopped: subcommand failed.

**Comment by dacap** [comment]
@yvanc did you was able to compile it? anyway I've no plans to deal with antiviruses exceptions in the compilation process, generally you should disable the antivirus in building folders (mainly to accelerate the building process)

**Comment by dacap** [comment]
(I'll close this issue but you can continue writing comments about how you solve this issue)
