### ISSUE TITLE
I can not build Skia (Windows10, VS2017)

### ISSUE THREAD

**Issue by dortsenal** [aseprite/aseprite#1598]
Whenever I try build Skia I failed to finish it. 

I've followed below steps
1. use Windows10 home
2. Installed Visual Studio community 2017 
3. Installed Windows 10 SDK on Visual Studio installer
4. Installed MozillaBuild in C:\mozilla-build
5. Downloaded Google depot tools and uncompress it in C:\deps\depot_tools
6. Installed cmake-3.9.4-win64-x64 in C:\Program Files\CMake
7. Set ninja.exe in C:\
8. Opened a command line and followed 'Building Skia on Windows for VS2017' steps

I've  tried above steps so many times but CMD always show me failed message.
Could you help me fix problems and build Skia? Thanks for reading it. Have a good day :)

CMD log is like below.

==============================================================

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.4.1
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Windows\System32>call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.4.1
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Windows\System32>**set PATH=C:\deps\depot_tools;%PATH%**

C:\Windows\System32>**cd C:\deps\depot_tools**

C:\deps\depot_tools>**gclient sync**
Bootstrapping cipd client for windows-amd64 from https://chrome-infra-packages.appspot.com/client?platform=windows-amd64&version=git_revision:d2677a4477e59cb7de00f1fb8a00e96b1aaeb927...
Error: client not configured; see 'gclient config'
C:\deps\depot_tools>**cd C:\deps**

C:\deps>**git clone https://github.com/aseprite/skia.git**
Cloning into 'skia'...
remote: Counting objects: 310222, done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 310222 (delta 60), reused 28 (delta 28), pack-reused 310106
Receiving objects: 100% (310222/310222), 247.46 MiB | 70.00 KiB/s, done.
Resolving deltas: 100% (252122/252122), done.
Checking out files: 100% (4417/4417), done.

C:\deps>**cd skia**

C:\deps\skia>**git checkout aseprite-m62**
Switched to a new branch 'aseprite-m62'
Branch aseprite-m62 set up to track remote branch aseprite-m62 from origin.

C:\deps\skia>**python tools/git-sync-deps**
common                               @ 9737551d7a52c3db3262db5856e6bcd62c462b92
buildtools                           @ e6b510a9daf822bbe9f922c200c58150803d2fd8
third_party/externals/expat          @ android-6.0.1_r55
third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
third_party/externals/piex           @ 8f540f64b6c170a16fb7e6e52d61819705c1522a
third_party/externals/dng_sdk        @ 96443b262250c390b0caefbf3eed8463ba35ecae
third_party/externals/zlib           @ 4576304a4b9835aa8646c9735b079e1d96858633
third_party/externals/spirv-headers  @ 661ad91124e6af2272afd00f804d8aa276e17107
third_party/externals/jsoncpp        @ 1.0.0
third_party/externals/libjpeg-turbo  @ 6de58e0d28014caf2fc1370145f22fd6d65f63e3
third_party/externals/libwebp        @ v0.6.0
third_party/externals/harfbuzz       @ 1.4.2
third_party/externals/sfntly         @ b18b09b6114b9b7fe6fc2f96d8b15e8a72f66916
third_party/externals/freetype       @ 447a0b62634802d8acdb56008cff5ff4e50be244
third_party/externals/sdl            @ 5d7cfcca344034aff9327f77fc181ae3754e7a90
third_party/externals/angle2         @ ced5c86c3a48ec9934e447e91f78120bb0ae5ee1
third_party/externals/spirv-tools    @ e9e4393b1c5aad7553c05782acefbe32b42644bd
third_party/externals/icu            @ ec9c1133693148470ffe2e5e53576998e3650c1d
third_party/externals/imgui          @ 6384eee34f08cb7eab8d835043e1738e4adcdf75
C:\deps\skia>**gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false target_cpu=""x86"" msvc=2017"**
Done. Made 33 targets from 20 files in 43ms
C:\deps\skia>**ninja -C out/Release**
ninja: Entering directory `out/Release'
[1/872] compile ../../src/effects/Sk1DPathEffect.cpp
FAILED: obj/src/effects/effects.Sk1DPathEffect.obj
cl.exe /nologo /showIncludes /FC @obj/src/effects/effects.Sk1DPathEffect.obj.rsp /c ../../src/effects/Sk1DPathEffect.cpp /Foobj/src/effects/effects.Sk1DPathEffect.obj /Fd"obj/effects_c.pdb"
CreateProcess failed: The system cannot find the file specified.
[2/872] compile ../../src/effects/Sk2DPathEffect.cpp
FAILED: obj/src/effects/effects.Sk2DPathEffect.obj
cl.exe /nologo /showIncludes /FC @obj/src/effects/effects.Sk2DPathEffect.obj.rsp /c ../../src/effects/Sk2DPathEffect.cpp /Foobj/src/effects/effects.Sk2DPathEffect.obj /Fd"obj/effects_c.pdb"
CreateProcess failed: The system cannot find the file specified.
[3/872] compile ../../src/effects/SkBlurMask.cpp
FAILED: obj/src/effects/effects.SkBlurMask.obj
cl.exe /nologo /showIncludes /FC @obj/src/effects/effects.SkBlurMask.obj.rsp /c ../../src/effects/SkBlurMask.cpp /Foobj/src/effects/effects.SkBlurMask.obj /Fd"obj/effects_c.pdb"
CreateProcess failed: The system cannot find the file specified.
[4/872] compile ../../src/effects/SkAlphaThresholdFilter.cpp
FAILED: obj/src/effects/effects.SkAlphaThresholdFilter.obj
cl.exe /nologo /showIncludes /FC @obj/src/effects/effects.SkAlphaThresholdFilter.obj.rsp /c ../../src/effects/SkAlphaThresholdFilter.cpp /Foobj/src/effects/effects.SkAlphaThresholdFilter.obj /Fd"obj/effects_c.pdb"
CreateProcess failed: The system cannot find the file specified.
[6/872] stamp obj/arm64.stamp
ninja: build stopped: subcommand failed.

**Comment by tony** [comment]
(@dacap I'm begging for an alternative to skia. >_< Something that can just work with CMake. It really is a nightmare to building from source and patching. I never got a single build working since the Skia switch happened. I can't imagine Skia's benefits helping more than the headaches it brings to the build process, but then maybe it's me. I don't know :smile:)

**Comment by dacap** [comment]
@tony I know the Skia situation is not ideal, but seeing all the work Google is doing on Skia (which is used on Chrome) I don't think in a better library with more maintenance than Skia at the moment.

**Comment by rubenvb** [comment]
I would just like to comment that I have a quite robust and very efficient CMakeLists.txt for Skia, which I am attempting to use to write a GUI framework (there's some overlap with what you have wrt windowing etc.).

It's located here:
https://github.com/skui-org/skia/

It's currently the m58 branch, I'm almost finished moving to the m63 branch.

I hope you find it useful. I use it to build Skia in-tree on Windows and Linux, with almost any compiler combination that is somewhat freely available.

**Comment by shindakun** [comment]
@dortsenal Just ran into this issue today while trying to build. In my case cl.exe was not found.

```bash
e:\deps\skia>ninja -C out/Release
ninja: Entering directory `out/Release'
[1/872] compile ../../src/opts/SkOpts_avx.cpp
FAILED: obj/src/opts/avx.SkOpts_avx.obj
cl.exe /nologo /showIncludes /FC @obj/src/opts/avx.SkOpts_avx.obj.rsp /c ../../src/opts/SkOpts_avx.cpp /Foobj/src/opts/avx.SkOpts_avx.obj /Fd"obj/avx_c.pdb"
CreateProcess failed: The system cannot find the file specified.
etc...
```
I resolved it by installing the standalone C++ build tools from https://go.microsoft.com/fwlink/?linkid=840931

```
e:\deps\skia>cl
'cl' is not recognized as an internal or external command,
operable program or batch file.

e:\deps\skia>cl.exe
'cl.exe' is not recognized as an internal or external command,
operable program or batch file.

e:\deps\skia>"C:\Program Files (x86)\Microsoft Visual C++ Build Tools\vcbuildtools.bat"

e:\deps\skia>cl.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23506 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

e:\deps\skia>ninja -C out/Release
ninja: Entering directory `out/Release'
[1/872] compile ../../src/opts/SkOpts_avx.cpp
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
[2/872] compile ../../src/c/sk_effects.cpp
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
[7/872] compile ../../src/effects/Sk2DPathEffect.cpp
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
[9/872] compile ../../src/effects/Sk1DPathEffect.cpp
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
[10/872] compile ../../src/effects/SkBlurMask.cpp
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
[11/872] compile ../../src/effects/SkColorFilterImageFilter.cpp
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
[12/872] compile ../../src/effects/SkAlphaThresholdFilter.cpp
etc...
```

Of course for me now everything builds but `skia\src\gpu\effects\grporterduffxferprocessor.cpp`

```bash
e:\deps\skia>ninja -C out/Release
ninja: Entering directory `out/Release'
[1/3] compile ../../src/gpu/effects/GrPorterDuffXferProcessor.cpp
FAILED: obj/src/gpu/effects/gpu.GrPorterDuffXferProcessor.obj
cl.exe /nologo /showIncludes /FC @obj/src/gpu/effects/gpu.GrPorterDuffXferProcessor.obj.rsp /c ../../src/gpu/effects/GrPorterDuffXferProcessor.cpp /Foobj/src/gpu/effects/gpu.GrPorterDuffXferProcessor.obj /Fd"obj/gpu_c.pdb"
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
e:\deps\skia\src\gpu\effects\grporterduffxferprocessor.cpp(52): error C2134: 'BlendFormula::GetProperties': call does not result in a constant expression
e:\deps\skia\src\gpu\effects\grporterduffxferprocessor.cpp(52): note: failure was caused by call of undefined function or one not declared 'constexpr'
e:\deps\skia\src\gpu\effects\grporterduffxferprocessor.cpp(142): note: see declaration of 'BlendFormula::GetProperties'
ninja: build stopped: subcommand failed.

e:\deps\skia>git branch
* aseprite-m62
```

**Comment by sk8yuck** [comment]
Same issue but I'm using VS2015 enterprise.
@rubenvb the m63 branch you're talking about must be missing, I cannot find it in aseprite/skia branches.
if I check from https://github.com/skui-org/skia.git directly, errorrs were everywhere, how can I fix this.
A lot THX.
And by the way, I am a Chinese developer and I cannot reach any google site without proxy or vpn, it cost me a lot of time to get to this step, and it drives me nuts!

**Comment by Schittini** [comment]
@shindakun i was getting the same error as @dortsenal but after what you've said i could compile skia, problem is now when i use the cmake -DUSE_ALLEG4_BACKEND=OFF -DUSE_SKIA_BACKEND=ON -DSKIA_DIR=C:\deps\skia -G Ninja .. command I just get a large failed, and not found while performing the tests, so when I type ninja aseprite it fails to compile

**Comment by numanair** [comment]
I had this issue before and it seemed to be that I had not selected the required components during the installation of VS. Same applies to the standalone build tools. I think this issue can be closed.

**Comment by olivier-grech** [comment]
I am facing this issue, but I am not sure I fully understand the solution that was mentionned here. What components are required for VS 2017, in order to build skia?

**Comment by dacap** [comment]
We've [updated the compilation instructions](https://github.com/aseprite/aseprite/blob/master/INSTALL.md) to compile the `master` branch of Aseprite. There are [pre-built binaries of the Skia library available](https://github.com/aseprite/skia/releases).
