### ISSUE TITLE
Remove unused palette entries for PNG file format

### ISSUE THREAD

**Issue by RandyGaul** [aseprite/aseprite#1599]
### Request

Please remove all unused palette entries when saving a png image, such that the palette inside of the .png image itself (when saved with Aseprites Indexed Color Mode) would match the palette when manually saving a palette through Aseprites "Save Palette" function.

### Context - What I'm trying to achieve

I've been working on a palette swapping system for a group of .png images. To uniquely identify palettes a hash can be computed using RGBA pixels from the palette in an array as the hash input. The unique palettes are stored in an artist-accessible database. When one of these palettes is modified, I am automatically updating all .png files using the palette by performing a palette swap operation.

Unfortunately Aseprite saves png images using palettes with many unused entries. The assumption was to compute a hash of a palette where all entries of the palette appear in the image. However, since Aseprite is leaving unused entries in an unpredictable manner inside of saved .png images, hashes are randomized and palettes cannot be uniquely identified.

### Aseprite and System version

* Aseprite version: 1.2.3-x64, installer
* System: Windows 10

---

For example this image:

![image](https://user-images.githubusercontent.com/1919825/32205771-72e2e164-bdae-11e7-9574-e6368652b2db.png)

If I click on "Save Palette" I create a nice looking palette:

![image](https://user-images.githubusercontent.com/1919825/32205789-954b4f48-bdae-11e7-8765-13bafb39969b.png)

However, when I load the original image and look at the palette inside the .png file itself, the palette contains 15 entries, only 5 of which are used by the image. The next image shows 15 pixels corresponding to the 15 palette entries of the original image. I created the next image with my own tools. Interestingly, the Aseprite palette on the left-hand side of the image only shows 13 palette entries; I'm assuming duplicate entries from the png file are removed from this view:

![image](https://user-images.githubusercontent.com/1919825/32205832-beb6371c-bdae-11e7-9f53-0ef0cfbb7303.png)

Here is original image uploaded to my own personal website inside of a .zip to make sure no processing was on done to the image while uploading. I'm posting it here so someone can load it up in a debugger and verify the 15 palette entries, and how they do *not* match the output from Aseprite's "Save Palette" feature: http://www.randygaul.net/wp-content/uploads/2017/10/bgroup1.zip

**Comment by dacap** [comment]
Aseprite loads/saves the palette only for Indexed images, and for RGB images it auto-generates the palette. I guess you are saving a palette inside a RGB png, I'm not sure if that is correct, I have to do some testing (e.g. how an RGB png + palette inside is shown in the browser when the RGB image contains more colors than the palette).

My recommendation at the moment: save your files as 8-bit indexed files (`PNG_COLOR_TYPE_PALETTE` color type) to preserve the palette.

**Comment by RandyGaul** [comment]
I'm saving with Color Mode as Indexed. They are saved as 8-bit index files already. I tried to explain this in my first sentence of the request :)

Problem is Aseprite includes unused entries inside of the PLTE chunk of the PNG. I am currently using this code to post-process a PNG saved via Color Mode->Indexed through Aseprite:

```cpp
uint64_t HashAndRemoveUnusedPaletteEntries(tdIndexedImage* img)
{
	int inidices[256] = { 0 };
	int size = img->w * img->h;
	for (int i = 0; i < size; ++i) inidices[img->pix[i]] = 1;

	int index_map[256];
	tdPixel used_pixels[256];
	int count = 0;
	for (int i = 0; i < 256; ++i)
	{
		if (inidices[i])
		{
			index_map[i] = count;
			used_pixels[count++] = img->palette[i];
		}
	}

	for (int i = 0; i < size; ++i) img->pix[i] = index_map[img->pix[i]];
	img->palette_len = count;
	for (int i = 0; i < count; ++i) img->palette[i] = used_pixels[i];
	assert(!memcmp(img->palette, used_pixels, count * sizeof(tdPixel)));

	return FNV1a(used_pixels, count * sizeof(tdPixel));
}
```

**Comment by dacap** [comment]
> I'm saving with Color Mode as Indexed via Aseprite. They are saved as 8-bit index files already.

From what I can see in [this image](https://user-images.githubusercontent.com/1919825/32205832-beb6371c-bdae-11e7-9f53-0ef0cfbb7303.png) it's an RGB image, not an indexed one. I'm saying that you should save the png file as an indexed image from your tool (not from Aseprite).

Anyway I'm not sure if I understood correctly what you want to achieve with Aseprite. If you are saving indexed images and you expect that Aseprite should optimize/remove unused palette entries, that will not happen: Aseprite will keep the original palette (because gamedevs expect to use the original indexes, not an optimized indexed version with remapped indexes).

**Comment by RandyGaul** [comment]
> From what I can see in this image it's an RGB image, not an indexed one.

Ooh, gotcha! That one was an indexed image, but yes, was saved as an RGBA image. Maybe this is where some confusion came from.

I definitely don't want to remove palette entries that appear in Aseprite's palette editor from the PLTE chunk, just extra ones that do not appear in the editor at all. To be clear in this image, the left-hand side circled is what I would expect to exist inside of the PLTE chunk.

![image](https://user-images.githubusercontent.com/1919825/32244710-b0f42a48-be36-11e7-9327-c2c17abfac0b.png)

However, when I load up this indexed PNG the PLTE chunk contains 15 palette entries, even though in the editor only 5 were showing up. If an artist adds a 6th color the palette, like this:

![image](https://user-images.githubusercontent.com/1919825/32244894-38f8d182-be37-11e7-8b41-aea0176dd805.png)

The PLTE chunk in the PNG now contains 18 entries, and not 6. I am asking for the PLTE chunk to contain all 6 colors from the Aseprite palette editor, and no extra ones.

It seems like the extra colors in the PLTE chunk were colors I had selected here:

![image](https://user-images.githubusercontent.com/1919825/32244931-5a009acc-be37-11e7-85d3-0e49152b1303.png)

But never actually placed them in the palette editor.

Unfortunately my current workaround code *will* remove this 6th blue color, even though I would love to keep it around. I have no way to figure out how to keep this 6th color entry just by loading the indexed PNG.

**Comment by dacap** [comment]
Could you please compare your code with Aseprite code?

Load: https://github.com/aseprite/aseprite/blob/master/src/app/file/png_format.cpp#L62
Save: https://github.com/aseprite/aseprite/blob/master/src/app/file/png_format.cpp#L345

It's using libpng so you might find what is the exact problem.

**Comment by RandyGaul** [comment]
Ah, I figured it out after looking around in libpng source. Thanks for taking the time to respond! Turns out when I read in the PLTE chunk, the size of the PLTE chunk is number of bytes, which must be divided by 3 to get the number of RGB triplets.

Since you're using libpng when you use `png_get_PLTE` [here](https://github.com/aseprite/aseprite/blob/master/src/app/file/png_format.cpp#L196), the value is "PLTE byte length" / 3. Tracing the call stack from `png_get_PLTE` I found [this line](https://github.com/winlibs/libpng/blob/3ec4237518a4cb30b2f25950b065a9420766a268/pngrutil.c#L975). That `num` variable eventually gets used in `png_set_PLTE` [here](https://github.com/winlibs/libpng/blob/3ec4237518a4cb30b2f25950b065a9420766a268/pngrutil.c#L1060) and set to `num_palette` [here](https://github.com/winlibs/libpng/blob/3ec4237518a4cb30b2f25950b065a9420766a268/pngset.c#L629). Eventually it gets handed back to Aseprite through `png_get_PLTE`.

**Comment by dacap** [comment]
Glad it was useful to fix your code!
