### ISSUE TITLE
Several issues with shift+number shortcuts

### ISSUE THREAD

**Issue by andyhall** [aseprite/aseprite#1604]
Hi, I noticed several issues with the default "Shift + [1..4]" shortcuts for setting layer opacity. The details vary between Windows and OSX (both current versions). This is with keyboard shortcuts set to the defaults.

 * On Mac only: the default "Shift+2" shortcut doesn't work at all. If I open the keyboard shortcuts UI and manually remove/recreate it, then it subsequently works (but shows up in the UI as `Shift+@` rather than `Shift+2`.

 * On both Mac and Win: all "Shift + 1..4" shortcuts behave strangely when the currently selected tool has an alternate shift behavior (e.g. the brush tool, after having made an edit, so that the shift key enables line drawing). The odd behavior happens only if you press more than one shortcut without releasing the shift key.

To reproduce the latter issue: 
 1. New file, select brush tool, and draw something so that shift-drawing lines is enabled
 2. Press and hold `Shift` (a shift-line appears)
 3. Press and release `3` (layer opacity changes, the shift-line disappears)
 4. Press and release `4` (layer opacity doesn't change, shift-line reappears)
 5. Press and release `4` (layer opacity changes, the shift-line disappears)

And so on. This only happens when the shift key is held down through multiple shortcuts - if you release shift between each shortcut things work normally (except for Shift+2 on Mac).

Thanks and regards!

### Version: 

 * current via Steam beta channel (v1.2.3)

**Comment by dacap** [comment]
Both fixes to be released on v1.2.5

**Comment by andyhall** [comment]
Hi, I confirmed the the second bug mentioned - thanks for the fix!

The first one - "Shift + 2" shortcut not working on OSX - is unchanged for me. 

Since it's separate from the issue that was fixed I'll re-file it separately. No idea why I filed two different bugs in the same issue in the first place - apologies for that.
