### ISSUE TITLE
Master does not build on linux?

### ISSUE THREAD

**Issue by cyraid** [aseprite/aseprite#1607]
Does not build (as per build instructions).

### Aseprite and System version

* Aseprite version: git src, latest commit today (ceb9cb3abd2eb91284642f49139be0dfbd7f362a)
* System: Linux, 17.10, Ubuntu

**Comment by dacap** [comment]
Do you have some log file? Travis is building on Linux and it looks like it's working.

**Comment by cyraid** [comment]
Sure.
[CMakeError.log](https://github.com/aseprite/aseprite/files/1457302/CMakeError.log)

**Comment by winterheart** [comment]
Hello. It seems you don't have some *-dev packages on your system. For pthread.h you need to install libpthread-stubs0-dev (just guess, it may named different). Number of required packages may vary.

**Comment by cyraid** [comment]
I have libpthread-stubs0-dev installed already. I have pthread.h already in /usr/include. :)

**Comment by cyraid** [comment]
Funny how this was building before I upgraded to Ubuntu 17.10 from Ubuntu 17.04 ..

**Comment by dacap** [comment]
@cyraid did you try creating a new build folder from scratch?

**Comment by cyraid** [comment]
Yep, each time. :)

**Comment by dacap** [comment]
do you have some console output? that would be really helpful

**Comment by cyraid** [comment]
For sure! [ConsoleLog.txt](https://github.com/aseprite/aseprite/files/1553597/ConsoleLog.txt)

**Comment by dacap** [comment]
Did you update the submodules?

    git submodule update --recursive

**Comment by cyraid** [comment]
Gives no console output when I did. So I just cloned the repository again and did:

`git submodule update --init --recursive`

Seemed to have worked? Very odd.. But thank you for the point in the right direction!

**Comment by dacap** [comment]
The important part in the console output was this:
```
CMake Error at third_party/CMakeLists.txt:43 (add_subdirectory):
  The source directory

    /home/******/Development/aseprite-src/third_party/giflib

  does not contain a CMakeLists.txt file.
```
Which means that the giflib directory inside third_party didn't contain a CMakeLists.txt file (so maybe the giflib dir was outdated or need to be removed, because it was replaced with a submodule "recently")
