### ISSUE TITLE
Custom brushes + Pen + Shading Ink breaks pattern alignment

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1615]
If you create a pattern you can draw with it as a pattern (repeating properly) unless you select the shading ink, which causes the pattern to behave like Paint Brush mode in both "Aligned to Source" and "Aligned to Destination" modes.

Aseprite 1.2.4-x64
Windows 7 x64

**Comment by KashouC** [comment]
Thank you! This fix is a big deal.

**Comment by dacap** [comment]
Thanks to @Gasparoken :heart: :blush:
