### ISSUE TITLE
Add function "Paste as new sprite"

### ISSUE THREAD

**Issue by NikolajPagh** [aseprite/aseprite#1618]
This is an idea for a new function. If I select a cell, I would like the possibility to paste it as a new sprite with the dimensions of my selection.

**Comment by dacap** [comment]
I guess this is the same as the one discussed here #1024

**Comment by buckle2000** [comment]
I don't think the feature is necessary. @NikolajPagh You can select a cell, **Select > All** then **Edit > New Sprite from Selection**.
