### ISSUE TITLE
Can only undo once

### ISSUE THREAD

**Issue by someusernameforgithub** [aseprite/aseprite#1620]
Sometime i'm only able to undo once, after that undo is greyed out and i loose all my history states and all my work. Not sure how to recreate, happens randomly and then i have to close and reopen my sprite to fix it or else i'm stuck with one undo state only for that sprite.

### Aseprite and System version

* Aseprite version: 1.2.4
* System: Windows 10

**Comment by dacap** [comment]
Do you have some kind of undo limit? Check Edit > Preferences > Undo > Undo Limit (uncheck the option to have "infinite" undo)

**Comment by dacap** [comment]
When you say "lost all my work", do you mean the program crashes?

Right now I'm investigating about a issue using the selection tool and the Undo Limit, and the program does crashes in certain situations. Please confirm me if you have the Undo Limit option enabled with some specific value.
