### ISSUE TITLE
Cannot compile with internal Curl headers

### ISSUE THREAD

**Issue by sabexx** [aseprite/aseprite#1624]
Aseprite does not compile on Slackware64 14.2 using the Aseprite bundled Curl headers.

Compiling with -DUSE_SHARED_CURL=ON works like a charm.

Version: Git pull as of the date and time of the post, version 1.3-dev

* System: Windows/macOS/Linux, version, distribution

**Comment by cyraid** [comment]
Are you using Ubuntu 17.10?
