### ISSUE TITLE
"Shift + 2" key shortcut not functioning on OSX

### ISSUE THREAD

**Issue by andyhall** [aseprite/aseprite#1627]
With default key shortcuts, the "Shift + 2" shortcut (for opacity 50%) doesn't seem to function on OSX.

If I go to the menu and re-create the shortcut, it changes to "Shift + @", and afterwards it works correctly. If I then reset shortcuts to the defaults, the shortcut stops working again.

Thanks!

* Aseprite version: 1.2.5 via Steam
* System: OSX 10.11.6, macbook pro 2014

**Comment by dacap** [comment]
It looks like it doesn't work with the English keyboard layout (I use the Spanish keyboard layout, and it's working with that layout). A fix for v1.2.6 planned.
