### ISSUE TITLE
Error on Git Submodule Update

### ISSUE THREAD

**Issue by flamendless** [aseprite/aseprite#1628]
When doing `git submodule update --init --recursive` after `git pull` on an existing aseprite cloned directory (already compiled before and working)
prints this error:
`
fatal: Not a git repository: /mnt/d/aseprite/.git/modules/laf/modules/third_party/googletest
Unable to find current revision in submodule path 'laf/third_party/googletest'
Failed to recurse into submodule path 'laf'
`
### Aseprite and System version

* Aseprite version: 1.2-dev
* System: Windows 10

**Comment by dacap** [comment]
Were you able to update the submodule? or do a new clone from scratch?

**Comment by flamendless** [comment]
Updating submodules doesnt work. ive just cloned it and it works. Please fix that for future builds

**Comment by dacap** [comment]
🤔  it looks more like a Git issue than an Aseprite issue, if it happens other time, you can add more information (you can use this same issue, even if it's closed).

**Comment by flamendless** [comment]
I've tried doing it with git in windows and in linux, both errors
