### ISSUE TITLE
Hex color value corruption when editing number with palette unlocked

### ISSUE THREAD

**Issue by jdeeny** [aseprite/aseprite#1636]
While editing the hex color value, zeros are unexpectedly added to the value, making it very difficult to enter a number.

This only occurs when the palette is unlocked. When the palette is locked, the value can be edited as expected.

![wtf](https://user-images.githubusercontent.com/409859/34324662-03fbfdda-e838-11e7-8b3b-5e170737de3b.gif)

### Aseprite and System version

Two reports of this issue:
User 1:
* Aseprite version: v1.2-dev git
* System: Linux, Fedora 27

User 2:
* Aseprite version: 1.2.6, 1.2.5
* System: Windows 10

**Comment by oceanhahn** [comment]
This issue is related to the bug described in #1632.

**Comment by jdeeny** [comment]
Thanks, I tried searching for an existing issue but missed yours.
