### ISSUE TITLE
Exporting tags; multible collums in sprite sheet and/or putting multible images in seperated fodlers 

### ISSUE THREAD

**Issue by codedcosmos** [aseprite/aseprite#1642]
Recently descovered tagging, I found it rather useful for organising my short animations. Exporting tags however isn't really utilised well in my opinion. I have two ideas (although the second one is a bit better) that could make the tags more useful.

1) When exporting the images into a sprite sheet, export each of the tags on their own collum within the sprite sheet, this would make it easier for animations that I have to implement, as I can work on a similar image with adjustments in one ase file and export the animations at separate rows and in the code account for the seperate rows and make rendering sprite sheets a lot easier.

2) This one would be way more useful for me personally, but im sure both would be useful. When exporting a ase file into multible images, for example foobar1.png, foobar2.png... etc. They all go into one folder. 
If would be a lot more useful if the images exported into a folder named the tag they come from. For example you have two tags; dog and dogJump. Images 1-4 are in dog so they go in the dog folder as dog1.png ... dog4.png. There are also Images 5-6 for dogJump that go in folder dogJump as dog1.png dog2.png. Both folders go where all the images would have gone previously. 

These features would make my life as a programmer a lot easier as it would involve a lot less hard coding, unfortunately I don't know C++ otherwise I would have sent a pull request myself. Although I don't think these features should be very difficult to implement. 

### Aseprite and System version ###
v1.2.6
Im using arch, but obviously I would like this feature to be avaliable for all platforms.

Cheers

**Comment by dacap** [comment]
Hi @codedcosmos,

1. you can see #1118,
2. you can use [the CLI](https://www.aseprite.org/docs/cli/) with the `--save-as dog{tag}/dog{tagframe1}.png`

More info:
https://www.aseprite.org/docs/cli/#save-as
https://www.aseprite.org/docs/cli/#filename-format
https://www.aseprite.org/docs/cli/#split-tags

**Comment by codedcosmos** [comment]
Thank you for your responce @dacap, I managed to get the sort of functionality I wanted via the json export, but I might implement a system with the tiling spritesheets as well. Cheers
