### ISSUE TITLE
Application crashes when moving layers

### ISSUE THREAD

**Issue by noqqe** [aseprite/aseprite#1643]
just had a great time playing with aseprite doing my first pixel pieces
After an hour or two I tried moving layers which is repeatably crashing. 

So I click on a layer, focus and move it one layer up or down. The application is instantly crashing.

See the crash log attached. 

### Aseprite and System version

* Aseprite version: 1.2.6, installer
* System: macOS, 10.13.2

[crash.log](https://github.com/aseprite/aseprite/files/1596095/crash.log)

**Comment by dacap** [comment]
Hi @noqqe, could you please send me the .ase file to [support@aseprite.org](mailto:support@aseprite.org)? did the file contained a lot of files or layer folders? or just a plain list of layers?

**Comment by noqqe** [comment]
Yesterday, when I was opening this bug I was just creating a new empty file, created a new layer (shift+n), moved it and it crashed. I did this quite a couple of times. 

Today, sadly (or luckily?) I'm not able to reproduce it anymore :(
