### ISSUE TITLE
Broken ellipse sizes

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1649]
The ellipse tool produces broken circles at very specific sizes. A 118x17 circle is not fully enclosed and missing pixels at the edges.

Aseprite v1.2.6-x64
Windows 7 x64

**Comment by Chaduke** [comment]
Confirmed it occurs at 115 x 18 thru 126 x 18

**Comment by yuxshao** [comment]
@dacap If you haven't already started working on this, I'd be interested in trying to tackle this!

**Comment by dacap** [comment]
@yuxshao I've been working in a new algorithm but never finished it. I'll try your PR in these days, it looks good for me (maybe in a future I'll replace all algorithms, but that's a long term solution).
