### ISSUE TITLE
Names of exported pngs for animations

### ISSUE THREAD

**Issue by luizcarlos1405** [aseprite/aseprite#1650]
It would be better if, when exporting more than 10 frames, they be named like name01, name02, name03, ..., name10, name11 and so on. And if there is more than 100 frames name001, name002...

The files get ordered by name so name11 is lower than name2 in the filesystem.

### Aseprite and System version

* System: Linux

**Comment by dacap** [comment]
Actually this can be done but you have to File > Save As, or File > Export with a filename like `name01.png`, or `name001.png`, etc.
