### ISSUE TITLE
Compiling on raspberry pi 3.

### ISSUE THREAD

**Issue by Greenfoot5** [aseprite/aseprite#1652]
So I am trying to install aseprite on a raspberry pi 3 with raspian stretch. 
I get stuck on the compiling.
```
cd aseprite
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=~/software -G Ninja ..
ninja aseprite
```
This all works apart from `ninja aseprite` where I get `ninja: build stopped: subcommand failed`. This is the console upon running the command.

[console log](https://pastebin.com/pY77FtZU)

I have had a 1.1.6 version previously but would like to update.

### Aseprite and System version

* Aseprite version: 1.2, compiled according to INSTALL.md
* System: Linux, Don't know how to find out, stretch

**Comment by SigSec** [comment]
Confirmed it occurs when following the INSTALL.md on a Raspberry Pi 3 with raspbian stretch

**Comment by DustinVFP** [comment]
try installing libcurl. (if i remember correctly libcurl4-gnutls-dev was the package i installed so assuming you are using raspbian you can use `apt-get install libcurl4-gnutls-dev` )

if that doesn't work then try this
1. go through all the steps except `ninja aseprite`
2. install cmake gui (not needed but i don't remember the command so it will be easier this way)
3. open the gui and set the source and build folders
4. find the setting `USE_SHARED_CURL` and check that
5. then hit configure
6. now try running `ninja aseprite`

this was what worked for me (not sure which of the 2 things fixes it)

off topic but small warning if you are compiling on the raspberry pi gcc uses more ram then the Pi3 has when compiling aseprite so you may need to make a swapfile on an external drive
