### ISSUE TITLE
Moving frames when tags are in use

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1656]
Imo tags are way too "greedy" with putting frames into themselves. It would be nice if you could treat tags more like layer groups when it comes to dragging and dropping. If you have two tags that touch each other (for example: tag 1 is frame 1-10 and tag 2 is frame 11-20) it's impossible to place a frame in the middle of them without it being swallowed by one of the tags.

There's plenty of space to make an indication for where it will be put when you drop (like a line or something) and to let us choose where it will end up.

For example: 
![sprite-0002](https://user-images.githubusercontent.com/17066488/35972649-0524ad78-0cd3-11e8-95ea-7f9250929dcd.png)

I hope this makes sense, but colors are just seperate mouse positions. Blue in middle, Green slightly to the right within the same cel before we get to the next one, red same but the other direction. Colors are just for the image to make more sense, not a suggestion.

Thanks.

**Comment by dacap** [comment]
Hi @KashouC, yeah, some time ago I though about it and some possible UI indicator should be added to see where the frame could be drop (+ some text in the status bar like layers group). I'll see what I can do.

**Comment by KashouC** [comment]
Oh, and maybe this should be it's own post but being able to just drag the tag edges to set start and end position would also be absolutely amazing.

**Comment by KasumiArai** [comment]
Yeah, dragging tag edges actually sounds excellent.

**Comment by dacap** [comment]
Dragging tag edges was an idea from the very beginning (just like dragging onion skin edges) but never had time to implement 😅  Also mentioned in #1275
