### ISSUE TITLE
Compilation fails at build Skia section. Win10 VS2017

### ISSUE THREAD

**Issue by Yanda1** [aseprite/aseprite#1658]
My system :
    Windows10
    Visual Studio community 2017
    Windows 10 SDK on Visual Studio installer
    awk.exe (Installed MozillaBuild in C:\mozilla-build)
    Downloaded Google depot tools and uncompress it in C:\deps\depot_tools
    Installed cmake-3.10.2-win64-x64

I followed Building Skia on Windows for VS2017' steps.
At this line I fail to compile.
`gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false target_cpu=""x86"" msvc=2017"`
`ninja -C out/Release`

And error message is this.

> C:\deps\skia>gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false target_cpu=""x86"" msvc=2017"
Done. Made 33 targets from 20 files in 27ms
C:\deps\skia>ninja -C out/Release
ninja: Entering directory `out/Release'
[1/872] compile ../../src/effects/SkBlurMaskFilter.cpp
FAILED: obj/src/effects/effects.SkBlurMaskFilter.obj
cl.exe /nologo /showIncludes /FC @obj/src/effects/effects.SkBlurMaskFilter.obj.rsp /c ../../src/effects/SkBlurMaskFilter.cpp /Foobj/src/effects/effects.SkBlurMaskFilter.obj /Fd"obj/effects_c.pdb"
CreateProcess failed: The system cannot find the file specified.
[2/872] compile ../../src/c/sk_effects.cpp
FAILED: obj/src/c/effects.sk_effects.obj
cl.exe /nologo /showIncludes /FC @obj/src/c/effects.sk_effects.obj.rsp /c ../../src/c/sk_effects.cpp /Foobj/src/c/effects.sk_effects.obj /Fd"obj/effects_c.pdb"
CreateProcess failed: The system cannot find the file specified.
[3/872] compile ../../src/effects/GrAlphaThresholdFragmentProcessor.cpp
FAILED: obj/src/effects/effects.GrAlphaThresholdFragmentProcessor.obj
cl.exe /nologo /showIncludes /FC @obj/src/effects/effects.GrAlphaThresholdFragmentProcessor.obj.rsp /c ../../src/effects/GrAlphaThresholdFragmentProcessor.cpp /Foobj/src/effects/effects.GrAlphaThresholdFragmentProcessor.obj /Fd"obj/effects_c.pdb"
CreateProcess failed: The system cannot find the file specified.
ninja fatal read file the handle is invalid.

Could you help me fix problems and build Skia?
note: cl.exe is not in the deps folder.

**Comment by narender059** [comment]
Facing similar issue, any solution to this?
