### ISSUE TITLE
Trim doesn't do anything if there's a pixel in the top left corner

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1659]
Any canvas size, empty transparent background, place one pixel in the top left corner and trim does nothing, but it works if you place a pixel in any other corner, or if you move the pixel out from the corner it works perfectly.

Aseprite 1.2.6-x64
Windows 7 x64

**Comment by dacap** [comment]
Known issue. The "key" color (border/bg color) is read from the top-left corder. A possible solution would be to identify if there are two or three corners with the same color, and reduce the edge/corner from that side. I've to think in the details about this, but should not be too hard to make it looks like it works correctly.

**Comment by dacap** [comment]
Also recently reported in the community site too: https://community.aseprite.org/t/trim-does-not-work-if-top-left-pixel-filled/3535
