### ISSUE TITLE
Multibyte characters truncated in widget strings

### ISSUE THREAD

**Issue by yuxshao** [aseprite/aseprite#1660]
Essentially [this](https://community.aseprite.org/t/adaptation-to-multibyte-characters/988):
> I’m trying to make Japanese strings file.
> (Make from en.ini ja.ini)
> 
> But multi-byte string wasn’t read multi-byte string correctly.
> 
> [for example]
> (Characters in the ini file -> Characters on the screen)
> “あいうえお” -> “BDFHJ”
> 
> “あ”(code:3042) -> “B”(code:0042)
> “い”(code:3044) -> “D”(code:0044)
> “う”(code:3046) -> “F”(code:0046)
> “え”(code:3048) -> “H”(code:0048)
> “お”(code:304A) -> “J”(code:004A)
> 
> Is it solvable?

In `file.ini` changing `file = &File` to `file = &あいえうお` causes the following output:
![image](https://user-images.githubusercontent.com/9067601/36135606-3e1d01c2-105a-11e8-9e0c-29a7a8c2cee8.png)

### Aseprite and System version

* Aseprite version: 1.3-dev, c3a0c00a623ea748aa091fb4517769a8bdc5deb7
* System: Arch Linux

**Comment by dacap** [comment]
Fixed with #1661
