### ISSUE TITLE
Crash when trying to move layers

### ISSUE THREAD

**Issue by Shiroifuyu** [aseprite/aseprite#1662]
Aseprite keeps crashing when I try moving layers.
![2018-02-14_01-39-14](https://user-images.githubusercontent.com/9444716/36182089-304cde2c-1128-11e8-8f61-a1133dad6b33.png)

* Aseprite version: 1.3-dev
* System: Windows 10

**Comment by dacap** [comment]
It looks like you've compiled Aseprite, you can debug the problem pressing the "debug with Native Only" or send me a screenshot after pressing that link, it should show the exact code line where the program crashes.

**Comment by Shiroifuyu** [comment]
![devenv_2018-02-14_02-23-48](https://user-images.githubusercontent.com/9444716/36183397-5fc91d40-112e-11e8-9e42-9686452e5b44.png)

**Comment by dacap** [comment]
Do you have some exact steps to reproduce this crash? What is the structure of your sprite (layers/groups)? Did you move a layer inside/outside a group or something like that?

**Comment by Shiroifuyu** [comment]
In the process of trying to reproduce the crash I also noticed that it crashes whith only one layer for some reason.
Here is a little video reproducing it: https://ame.s-ul.eu/y3FUyI5q

**Comment by dacap** [comment]
I was able to reproduce it! thanks for the video and help. At the moment it looks like a problem in v1.3-dev, because I wasn't able to reproduce the problem on v1.2.6.

**Comment by dacap** [comment]
Pretty sure this regression was introduced in d59fd204892b193a72d374053c22b522ac151f7e (where now `Timeline::hitTest()` can return a `Timeline::Hit::layer = -1`) trying to fix [other bug](https://community.aseprite.org/t/play-animation-changes-selected-layer/989)

Soon I'll commit a patch for this.

**Comment by dacap** [comment]
Hi @Shiroifuyu, please check the latest commit 6012f2389f1c9903dca7f5ad35738e5f8ce6186f which should fix this issue.

**Comment by Shiroifuyu** [comment]
Tried to reproduce the error and it seems to be fixed now, good job @dacap !
