### ISSUE TITLE
Aseprite file spec for Slice chunks (0x2022) doesn't match actual format

### ISSUE THREAD

**Issue by RabbitB** [aseprite/aseprite#1663]
I'm writing an Aseprite file importer for the Godot engine, and when I implemented the Slice chunk loader, I found it wasn't loading all the chunk data, and the values weren't correct once I started reading the slice keys.

I verified that my loading code matched the file spec, so I started digging around in `ase_format.cpp` and found that the way it saves slices, doesn't match the spec. The spec calls for the positional and size data to be a variety of `short` and `word` values, while `ase_file_write_slice_chunk` saves them all as `dword`.

```C++
for (auto key : range) {
    if (frame == fromFrame || key != oldKey) {
      fputl(frame, f);
      fputl(key ? key->bounds().x: 0, f);
      fputl(key ? key->bounds().y: 0, f);
      fputl(key ? key->bounds().w: 0, f);
      fputl(key ? key->bounds().h: 0, f);

      if (flags & ASE_SLICE_FLAG_HAS_CENTER_BOUNDS) {
        if (key && key->hasCenter()) {
          fputl(key->center().x, f);
          fputl(key->center().y, f);
          fputl(key->center().w, f);
          fputl(key->center().h, f);
        }
        else {
          fputl(0, f);
          fputl(0, f);
          fputl(0, f);
          fputl(0, f);
        }
      }

      if (flags & ASE_SLICE_FLAG_HAS_PIVOT_POINT) {
        if (key && key->hasPivot()) {
          fputl(key->pivot().x, f);
          fputl(key->pivot().y, f);
        }
```

Changing my code to match allows it to load the slices correctly.

### Aseprite and System version

_Aseprite v1.2.6-x64 (installed through HumbleBundle)
Windows 10 x64 - Build 15063.909_

**Comment by dacap** [comment]
Thanks for reporting this! Just in case, there is a MIT licensed `.ase` decoder in the [dio](https://github.com/aseprite/aseprite/tree/master/src/dio) module.
