### ISSUE TITLE
Cannot see marquee while dragging to select

### ISSUE THREAD

**Issue by viniciuscsg** [aseprite/aseprite#1667]
Suddenly - apparently after disabling snap to grid (shift+s) - I wasn't able to see the marquee from any of the selection tools anymore while it I am dragging with the left mouse button pressed to select an area. As soon as I release the button I can see the marquee around the area I just selected blindly, but not during the actual selection, so I have to guess when to release the button, not being able to see the marquee dynamically resizing anymore. Closing aseprite and lauching again did not solved it, nor restarting the computer.

### Aseprite and System version

* Aseprite version: 1,2,6x64, Steam
* System: Windows 10

**Comment by dacap** [comment]
I'm not sure if this is related to Snap to Grid or is the same issue that #1412

**Comment by viniciuscsg** [comment]
Conditions were a bit different, index 0 wasn't #000000. However, I think this can be closed because it turned out the issue was limited to a single file being opened, it probably got corrupted somehow. Copying the canvas into a fresh document solved the issue. Still weird but not worth much time I think :)

**Comment by oceanhahn** [comment]
This is a weird problem that occurs when the following conditions are true:

 * The current file is in the **Indexed colour mode.**
 * The **Mask colour is set to Index 0** in Sprite properties.
 * **Index 0 has its alpha value set to exactly zero.**

If Index 0's alpha level is anything _other_ than zero, or the Mask is set to an index value other than zero, or the graphic is _not_ in indexed mode, the bug does not occur.

It took a lot of fiddling to discover why, too, I will have you know! XD
