### ISSUE TITLE
Grant GPLv3 license on pre-EULA version of Aseprite

### ISSUE THREAD

**Issue by yegortimoshenko** [aseprite/aseprite#1668]
I've previously sent this as an email, but I would like a public answer that I can link to, so...

I see you've locked #1666, so I won't bother you anymore on that token.

I would like to ask you to release the last GPL'd version of Aseprite (https://github.com/aseprite/aseprite/commit/03be4aa23db465219962f4c62410f628e7392545) under GPLv2 *or later*. Currently it's GPLv2 *only*. Could you do that?

Given that other contributors signed a CLA, just an informal "yes" will do.

**Comment by dacap** [comment]
I must say "no" because 1) I don't know what is the rationale behind this, and 2) the "or later" clause gives a lot of control/power to the FSF which is the institution that creates/writes new GPLs. So the answer is no.

**Comment by yegortimoshenko** [comment]
I see. Perhaps you could grant GPLv3 as well? The main changes to the license are tivoization clause (i.e. can't run GPLv3-only code on locked down hardware), grace period (if GPLv2 is violated, rights granted by the license are revoked until all copyright holders regrant them, while with GPLv3 there is a period where, if violation is fixed, rights are regranted automatically), and software patent clause (any contributors irrevocably allow to use any patents they might possess to any users of the software).

The intent is to try to integrate some GPLv3-only code into the Aseprite, and make it easier to use LGPLv3 dependencies as well. Granting GPLv3 on that code would allow me to use GTK (or Qt) clipboard code for aseprite/clip, so that I can have clipboard support on Linux (X11) for my use.

**Comment by dacap** [comment]
I think that you can integrate GPLv3 code in GPLv2 code. I don't remember where I read this but I think the normal way to continue working on GPLv2 code with GPLv3 code is just integrating the GPLv3 code. Basically the new written source code is licensed in GPLv3, so it contains the new clauses.

Anyway, [I'll be working](https://github.com/dacap/clip/issues/3) on the clip library to add support for Linux in these days, so stay tuned.

**Comment by yegortimoshenko** [comment]
> I think that you can integrate GPLv3 code in GPLv2 code.

Unfortunately, that's only possible if code is under GPLv2-or-later. GPL requires that all source code is available under the same license (which includes license version). See: https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility

> Anyway, I'll be working on the clip library to add support for Linux in these days, so stay tuned.

I see, thanks!

However, it would still be great to have this code available under GPLv3: X11 clipboard is only one use case (for example, I might also need Wayland clipboard support, which can be mostly copied from Qt or such), and not all code that I might want to change resides in one of your MIT-licensed libraries that I can build GPL'd version with. So, if releasing the old code under GPLv3 is possible, that would be great.
