### ISSUE TITLE
Aseprite can't render small dots correctly

### ISSUE THREAD

**Issue by pazon12** [aseprite/aseprite#1671]
So a friend sent me a photo thats just a bunch of tiny red and green dots, so for fun I threw it in to aseprite which caused it to
a. render it correctly at some zoom level
b. not render the red dots at other zoom levels.
which meant it either was olive-green or bright green.
I can't easily record the video, so here is the picture to try it
https://imgur.com/dqDquIX
Throw it into aseprite and zoom in and out.

### Aseprite and System version

* Aseprite version: Latest master.
* System: Windows 10

**Comment by dacap** [comment]
I guess the problem appears when the zoom is 50% or less. This is because Aseprite doesn't use some kind of interpolation to render pixels on lower zoom levels. I'll see to add some kind of interpolation when the zoom is reduced.

**Comment by dacap** [comment]
I've been working in a new method to render the editor canvas using some antialiasing when zoom < 100% (and fix #1489 + should work with any level of zoom, i.e. smooth zoom). More news about this soon.

**Comment by dacap** [comment]
![render](https://user-images.githubusercontent.com/39654/41790742-e8e7357a-7629-11e8-93b1-af12ca1d5c5c.gif)
