### ISSUE TITLE
AND selection mode for marquee tools

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1674]
It would be fantastic to have a selection mode for the **Marquee Selection Tools** that would produce a selection area including only pixels that are currently selected AND inside a new selection area. This way, we can select large areas with (for instance) the **Magic Wand** and then limit or crop the selection area using this new mode to a specific smaller area, using (for instance) the **Rectangular Selection Marquee.**

Photoshop, among others, already has this behaviour in its selection tools, activated by holding [Alt] + [Shift] while making a selection over previously selected pixels.

The new mode would join the existing "Replace Selection," "Add to Selection," and "Subtract from Selection" marquee tool modes.
It is possible that this mode already exists and that I have somehow overlooked it. :s 

Thanks for considering it! :D 

..currently using ASEprite 1.2.6-x64 on Win10.

**Comment by dacap** [comment]
This is already implemented in v1.2.10-beta4: https://community.aseprite.org/t/feature-request-intersect-with-selection-tool/1797/12
