### ISSUE TITLE
Please add USE_SHARED_LIBARCHIVE, USE_SHARED_FMT, USE_SHARED_STRINGENCODERS, USE_SHARED_MUJS

### ISSUE THREAD

**Issue by yurivict** [aseprite/aseprite#1681]
These packages exist as standalone packages and can be used as shared.

**Comment by dacap** [comment]
Sorry but the idea of the official distribution is to have almost no dependencies so Aseprite can be used in most distributions.

**Comment by dacap** [comment]
Oh sorry again 😄, I guess you are talking about adding these options in the CMakeLists.txt!

**Comment by yurivict** [comment]
Yes, to CMakeLists.txt -)

**Comment by merwok** [comment]
Would this be a simple change to do?  I don’t know cmake, but I could see how USE_SHARED_LIBPNG is used and adapt it for libarchive at least, unless there are more places to change that can't be found by searching for USE_SHARED_

**Comment by yurivict** [comment]
I am very reluctant to update a FreeBSD package because excessive bundling causes a lot of extra-work.

**Comment by dacap** [comment]
At the moment there are no plans to include these flags, patches will be accepted but those patches will need to keep things working on all platforms (Windows, macOS, Linux).
