### ISSUE TITLE
Build breaks with ENABLE_WEBSERVER=on

### ISSUE THREAD

**Issue by yurivict** [aseprite/aseprite#1682]
Version 1.2.7, FreeBSD port.

```
In file included from /usr/ports/graphics/aseprite/work/aseprite-1.2.7/src/webserver/webserver.cpp:8:
/usr/ports/graphics/aseprite/work/aseprite-1.2.7/src/config.h:43:10: fatal error: 'base/base.h' file not found
#include "base/base.h"
         ^~~~~~~~~~~~~
```

**Comment by dacap** [comment]
Yeah, I guess this option should be removed. There were plans to create a mini webserver to request information about sprites directly to Aseprite, but then I abandoned the idea. Maybe for a future.

**Comment by dacap** [comment]
Webserver was removed in f8cb1db917a18a9ed7c94eea16672a51b913338a
