### ISSUE TITLE
Replace Color: Select layers and frame disappeared

### ISSUE THREAD

**Issue by vasholino** [aseprite/aseprite#1688]
Since last update 1.2.7.3, in the replace coloro window, the select layers and frames box is missing.
Replace color now works only con current selected layer and frame

### Aseprite and System version

* Aseprite version: 1.2.7.3, Steam
* System: Windows 10 x64

**Comment by dacap** [comment]
There is a change in 1.2.7 where we can replace color (or apply any filter) in the selected cels in the timeline:

https://twitter.com/davidcapello/status/976053554552164352

Anyway it is not an optimal solution and there are some bugs, so the button will come back (next week 1.2.7.4)

**Comment by vasholino** [comment]
Thank you very much Dave! You are really an awesome developer :)
couldn't find any reference to the change anywhere ^^
maybe the button can come back with some macro to shift between the options
