### ISSUE TITLE
Successive undo-ing has become sluggish

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1695]
I've seen people mention Aseprite being slow on other operating systems, but I've never noticed it until now on Windows. Recently I've started noticing that the undo function has become very slow when holding down Ctrl+Z to undo multiple actions. Maybe this is an intentional change, maybe not, but it's still a new thing.

It's still not THAT slow, but it's a noticeable difference from 1.2.6.

Windows 7 x64
Aseprite v1.2.7.3-x64

**Comment by dacap** [comment]
Hi @KashouC, no intentional change on this. I'll take a look.

**Comment by dacap** [comment]
Just in case, are there some special cases where the undo is slower? e.g. undoing changes in the timeline (new frames/delete frames/layers, etc.) or the canvas, etc.

**Comment by KashouC** [comment]
No, if I just make a new file in both 1.2.6 and in 1.2.7.3 and draw a bunch of lines with the pen, it's definitely slower in 1.2.7.3.

But like I said, it's not THAT much slower, but in bigger files I think it starts showing even more. The reason I'm making an issue out of it is that I thought that there's a chance it might be related to the other performance related issues, or just to nip it in the bud in case the issue snowballs for future versions.

**Comment by KashouC** [comment]
Actually this isn't version related at all, but the speed of undoing is related to how big the palette side panel is. If you make it bigger the re-draw or whatever takes much longer, making it sluggish.

**Comment by dacap** [comment]
I guess it's related to the "color selector" area (and worse if it's a color wheel):

![screen shot 2018-03-28 at 12 16 16](https://user-images.githubusercontent.com/39654/38038671-e28d614a-3281-11e8-96c4-976df508d659.png)

**Comment by KashouC** [comment]
Oh wow, yeah, changing from the color wheel to the color spectrum was a huuuge boost in speed.

**Comment by dacap** [comment]
I'm going to fix this implementing the idea of this issue #1516

**Comment by dacap** [comment]
@KashouC please check the v1.2.8 version, the color wheel shouldn't be an issue now on undo/redo

**Comment by KashouC** [comment]
Yup, fast as lightning now! Good job.
