### ISSUE TITLE
New File Size changes aren't reflected

### ISSUE THREAD

**Issue by jonathanhirz** [aseprite/aseprite#1697]
I just bought/downloaded Aseprite from itch.io. When I change the size of a new file to something smaller than 1024x1024 (default?), then start another new file, that new smaller size isn't saved. I can see the size being saved in the [new_file] section of aseprite.ini in [~/Library/Application Support/Aseprite/aseprite.ini], but every new file starts with 1024x1024

Aseprite 1.2.7.3
macOS 10.13.3

**Comment by jonathanhirz** [comment]
:eyeroll: rebooting my computer fixed this...

**Comment by jonathanhirz** [comment]
I saw this bug again today. I'm wondering if it's because I installed it through the itch.io app, and that's messing with the settings file somehow?

**Comment by dacap** [comment]
The New File dialog displays the clipboard image width/height by default if the clipboard contains an image. If the clipboard doesn't contain an image, the dialog will display the latest used size. If you want to create several images of the same time, my personal recommendation are:

1. Create several sprites with the same size from the very beginning
1. Or just create a `template.aseprite` file, so each time you need to create a new sprite, just open your template (or drag and drop it to Aseprite) and you will start with your preferred size.

**Comment by jonathanhirz** [comment]
Thank you, this makes sense and it exactly the behavior I'm seeing. Sorry to bother, love Aseprite!
