### ISSUE TITLE
Why did you delete USE_SHARED_LIBWEBP?

### ISSUE THREAD

**Issue by yurivict** [aseprite/aseprite#1699]
Shared webp worked very well. Webp can't be just built on FreeBSD, it needs patches. And rebuilding is undesirable, since the package exists. Now I can't update the port because of this.

**Comment by yurivict** [comment]
> If webpdemux and webpmux libraries are distributed with webp, we can add the flag back.

They are distributed with ```webp```:
```
$ pkg info -l webp | grep lib
	/usr/local/lib/libwebp.a
	/usr/local/lib/libwebp.so
	/usr/local/lib/libwebp.so.7
	/usr/local/lib/libwebp.so.7.0.1
	/usr/local/lib/libwebpdecoder.a
	/usr/local/lib/libwebpdecoder.so
	/usr/local/lib/libwebpdecoder.so.3
	/usr/local/lib/libwebpdecoder.so.3.0.1
	/usr/local/lib/libwebpdemux.a
	/usr/local/lib/libwebpdemux.so
	/usr/local/lib/libwebpdemux.so.2
	/usr/local/lib/libwebpdemux.so.2.0.3
	/usr/local/lib/libwebpmux.a
	/usr/local/lib/libwebpmux.so
	/usr/local/lib/libwebpmux.so.3
	/usr/local/lib/libwebpmux.so.3.0.1
```

**Comment by dacap** [comment]
I'll give a try to `find_library` for each individual library.

**Comment by dacap** [comment]
@yurivict I've tested using the shared webp included in Ubuntu 14.04 but [it failed](https://travis-ci.org/aseprite/aseprite/builds/368198450). You can give a try to the [shared-webp](https://github.com/aseprite/aseprite/tree/shared-webp) branch.

**Comment by winterheart** [comment]
aseprite requires >=webp-0.5.2, but Ubuntu 14.04 has only 0.4.4. Appropriate version can be found in Ubuntu 17.10.

**Comment by yurivict** [comment]
Please consider bringing back ```USE_SHARED_WEBP```.
I patched cmake files to use the external ```webp```, and it builds with it fine.

**Comment by cata0309** [comment]
libwebpmux cannot be found on Solus Linux but it is installed on the system both regular and dev versions of package(with headers and libs). What to do ?

**Comment by Xtendera** [comment]
Based on the mentioned issue, it seems like this issue can be closed for the moment. @dacap
