### ISSUE TITLE
Feature request: Add support for animated PNG format.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1702]
Apparently, there is an animated .png format, and there has been since 2004. It would be great if ASEprite could open all of the frames in these files, rather than just the first. Being able to save in this format would also be pretty keen!
It seems that these .png/.apng files can also handle 8P and 24b palettes better than .gifs can, although I do not know whether this is still true.

[Here are some details, I think.](https://en.wikipedia.org/wiki/APNG)

Thanks for considering it! :D 
..using ASEprite 1.2.7.3-x86 on Win10.

**Comment by dacap** [comment]
Known about it, never give a try (mainly because it wasn't widely adopted by web browsers 😢). It looks like since last year Chrome supports APNG too.

**Comment by oceanhahn** [comment]
Aa, I thought that that might have been the case.
Maybe someday, then. ;3

Thanks for considering it, though! :D

**Comment by theTreadlight** [comment]
[Here](https://wiki.mozilla.org/APNG_Specification)'s the specification for the aPNG extension.  While this is in the citations of that Wikipedia page, I felt it would be good to make sure you know it's there.  And if it helps, the page for [APNG Assembler](http://apngasm.sourceforge.net/) has some other information that may be of value, or may end up being redundant to you.
It would be wonderful to have something graphical I can actually load these into without having to view them in my web browser.

**Comment by amirringo** [comment]
Super

**Comment by west74rz** [comment]
Если честно,я не знаю чего делать дальше.!! ((((

чт, 10 мая 2018 г., 8:41 amir abbas karimi <notifications@github.com>:

**Comment by cyraid** [comment]
This would be really good, especially for working on games, and not cluttering with so many separate files.

**Comment by marCOmics** [comment]
Yes! I'm waiting for this feature as well, would help out much! :)

**Comment by KashouC** [comment]
Animated PNGs seem to be making the rounds on Twitter at the moment, and what's interesting is that they seem to be retained as .png if the canvas is small enough (not sure what the cutoff is, but at least 500x500px) instead of being converted to .mp4s. Would be very interested in native animated PNG support in Aseprite because of this.

**Comment by oceanhahn** [comment]
Was about to come and give this a bump myself for the same reason as Kashou.
Twitter handling .apngs now does not really make this issue more urgent, but perhaps the added reach might make it a bit shinier? :y 

Besides supporting a new animated image format, it is also interesting to note that Twitter also supports [i]multiple animated images per post.[/i]
It does not reliably show these images as animated in miniature, but clicking and/or cycling the enlarged graphics display animated .pngs correctly.
Example: https://twitter.com/windfallapples/status/1207433267898732546

I mention this because it would relate directly to the "Export for Twitter" feature if a .apng option is added. Furthermore, besides having recently revised its ideal display dimensions, placing multiple images in a single tweet also means the ideal image geometry will vary depending on the number of images (animated or not) present.

In any extent, thank you again for keeping this suggestion alive, and I look forward to more! :D

**Comment by dacap** [comment]
Closing this to keep a reduced number of issues, #246 for .apng support
