### ISSUE TITLE
Move Selection, not Contents

### ISSUE THREAD

**Issue by netherchef** [aseprite/aseprite#1708]
There doesn't seem to be a way to move selections?

Example: https://media.giphy.com/media/eu3yA6xBgJlrnMmZ8n/giphy.gif

**Comment by dacap** [comment]
You can drag-and-drop the selection edges (you just have to put the mouse in the edge):

![move-selection-edges](https://user-images.githubusercontent.com/39654/38768772-e9a879b0-3fce-11e8-8220-0732ca452829.gif)

**Comment by netherchef** [comment]
There it is! Thank you so much!

**Comment by IArnaut2** [comment]
> You can drag-and-drop the selection edges (you just have to put the mouse in the edge):
> 
> ![move-selection-edges](https://user-images.githubusercontent.com/39654/38768772-e9a879b0-3fce-11e8-8220-0732ca452829.gif)

Can you make it be done with arrow keys and with modifiers too?
