### ISSUE TITLE
Frames duration of the last frame ignored when exporting to animated gif

### ISSUE THREAD

**Issue by mchiasson** [aseprite/aseprite#1712]
Describe your bug report or feature request here
I created a quick animation using 4 frames to demonstrate: Every frame duration is set to 200ms. Exporting it to a gif file created this:

![sheep8x8_walk](https://user-images.githubusercontent.com/961637/39097238-9d245e24-4627-11e8-9237-d7bef3557286.gif)

The problem goes away if I leave the last frame to the default 100ms, and duplicate the last frame instead.

### Aseprite and System version

* Aseprite version: 3ddb3d054b2d7957acfedb475b3a5fdd19f4066e
* System: Xubuntu 16.04.4 LTS

**Comment by dacap** [comment]
HI @mchiasson, are you using File > Export with the "Export for Twitter" option enabled?
