### ISSUE TITLE
Exported JSON Frame Number Is Not Printed for Single Frame File

### ISSUE THREAD

**Issue by niedzielski** [aseprite/aseprite#1713]
When an Aseprite file has a single frame, the frame number is not exported. This makes the default hashed JSON export less useful since the key values cannot be known unless the number of frames for the value of interest is known.

These are the options I tried:

- `aseprite -b *.aseprite --filename-format '{frame}' --data /dev/stdout`
- `aseprite -b *.aseprite --filename-format '{frame0}' --data /dev/stdout`
- `aseprite -b *.aseprite --filename-format '{frame1}' --data /dev/stdout`
- `aseprite -b *.aseprite --filename-format '{tagframe}' --data /dev/stdout`

With [this file](https://github.com/rndmem/nature-elsewhere/blob/a351e03/src/assets/textures/flag.aseprite) but they each produce:

**Actual**
```json
{ "frames": {
   "": {
    "frame": { "x": 0, "y": 0, "w": 16, "h": 16 },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": { "x": 0, "y": 0, "w": 16, "h": 16 },
    "sourceSize": { "w": 16, "h": 16 },
    "duration": 65535
   }
 },
 "meta": {
  "app": "http://www.aseprite.org/",
  "version": "1.2.8.1",
  "format": "I8",
  "size": { "w": 16, "h": 16 },
  "scale": "1"
 }
}
```

**Expected**
```json
{ "frames": {
   "0": {
    "frame": { "x": 0, "y": 0, "w": 16, "h": 16 },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": { "x": 0, "y": 0, "w": 16, "h": 16 },
    "sourceSize": { "w": 16, "h": 16 },
    "duration": 65535
   }
 },
 "meta": {
  "app": "http://www.aseprite.org/",
  "version": "1.2.8.1",
  "format": "I8",
  "size": { "w": 16, "h": 16 },
  "scale": "1"
 }
}
```

Note the `"0"` key in the expected snippet. It's not a big deal for the single file case but I'm trying to build a mapping of many files packed into a sprite sheet. I think that, for the case that the frame wanted is index 0, I have to try with the number omitted when using the number fails.

Thanks for reading :+1: 

### Aseprite and System version

* Aseprite version: v1.2.8.1, v1.2.9 (all 64b Debian)
* System: Ubuntu v17.10

### Testing
1. `wget https://github.com/rndmem/nature-elsewhere/raw/a351e03e9dc5919a6269db710d265d5cfb142ccb/src/assets/textures/flag.aseprite`
1. `aseprite -b *.aseprite --filename-format '{frame}' --data /dev/stdout`
1. Check the keys of frames are nonempty.

**Comment by dacap** [comment]
We have to check if this is still reproducible.

**Comment by niedzielski** [comment]
Revised for v1.2.9.

**Comment by dacap** [comment]
@niedzielski we've tried to reproduce this issue but it looks like it doesn't exist anymore in the beta version, could you give a try [to Aseprite v1.2.10-beta4](https://community.aseprite.org/t/get-aseprite-beta-version/22)?
