### ISSUE TITLE
Can't enable the "Use native cursor" option

### ISSUE THREAD

**Issue by michaelpittino** [aseprite/aseprite#1714]
I'd like to use the native cursor function because the software-cursor has some short delays which make working in Aseprite tiring after some time.
The problem is, that the regarding UI option is unclickable for me.

Here is a screenshot of the issue: https://i.imgur.com/yTqFGHp.png

### Aseprite 1.3-dev, Windows 10 x64

* Aseprite version: 1.3, dev
* System: Windows 10 x64

**Comment by dacap** [comment]
This is possible using the Skia backend.
