### ISSUE TITLE
Opening multiple images of different size

### ISSUE THREAD

**Issue by KelvinShadewing** [aseprite/aseprite#1719]
When you open a series of images, if they're different sizes, it only uses the size of the first image. The problem is, some sprites are exported with each frame not only being separate, but optimized by only including the sprite itself and not the extra space needed to fit every frame in (think MUGEN sprites). I think there needs to be an option to use the maximum size instead of just the size of the first so that sprites exported like this can be imported into Aseprite.

**Comment by KasumiArai** [comment]
As a temporary workaround:  Sprite->Canvas Size set to some arbitrarily large value (that you know is larger than all the frames), then use Sprite->Trim. This works because Aseprite still loads the "offcanvas" parts of the images if you load in a sequence.

**Comment by KelvinShadewing** [comment]
Ohhhh, I forgot about that little quirk! Thank you!

**Comment by toporelo** [comment]
Cool
