### ISSUE TITLE
Windows 10 compiling - Include directories are set to NOTFOUND

### ISSUE THREAD

**Issue by devvoid** [aseprite/aseprite#1723]
I've been trying to compile Aseprite for Windows 10, but I've hit a snag while trying to generate the project files. Everything goes fine, but then it gives me a large number of complaints about include directories being set to NOTFOUND.

This is the command used:

cmake -DUSE_ALLEG4_BACKEND=OFF -DUSE_SKIA_BACKEND=ON -DSKIA_DIR=C:\deps=skia -G Ninja ..

Full error:

SKIA_ANGLE_INCLUDE_DIR
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
SKIA_CODEC_INCLUDE_DIR
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
SKIA_CONFIG_INCLUDE_DIR
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
SKIA_CORE_INCLUDE_DIR
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
SKIA_GPU2_INCLUDE_DIR
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
SKIA_GPU_INCLUDE_DIR
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
SKIA_LIBRARY
    linked by target "she" in directory C:/Users/owner/Desktop/aseprite/src/she
SKIA_UTILS_INCLUDE_DIR
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she
   used as include directory in directory C:/Users/owner/Desktop/aseprite/src/she

Any help would be much appreciated.

### Aseprite and System version

* Aseprite version: Master
* System: Windows 10

**Comment by devvoid** [comment]
Turns out the issue was that I had an older version of Cmake on my path that it was finding for some reason, deleted it and the configuration went fine, sorry for the trouble.

**Comment by dacap** [comment]
For a moment I thought it was related to an invalid SKIA_DIR (SKIA_DIR=`C:\deps=skia`)
