### ISSUE TITLE
Cursor Glitch

### ISSUE THREAD

**Issue by DoktorOe** [aseprite/aseprite#1732]
If you have select a part with the Rectangular Marquee Tool, press ctrl and go with the cursor over the select part, the cursor duplicate himself while you are at the select part. But only with the Rectangular Marquee Tool.

Aseprite v.1.2.8-x64
Windows 10 Pro Version 1803

**Comment by KashouC** [comment]
If this is what you are referring to, it's likely not a bug, and instead indicates that we're currently in copy mode for the move tool. If you hold Ctrl and then click and drag a selection, you will copy the contents of the selection and paste it where you let go of the mouse button.

![duplicate](https://user-images.githubusercontent.com/17066488/40271930-ee33bcd2-5ba4-11e8-8461-e5edebc9245e.png)

**Comment by dacap** [comment]
As @KashouC said, it's the expected behavior (or maybe I'm not aware of something else)
