### ISSUE TITLE
Windows 10 + Skia + VS2015. Undeclared identifiers, maybe Skia changes and broke?

### ISSUE THREAD

**Issue by GrapeJamMan** [aseprite/aseprite#1733]
This is for Aseprite v1.2.8 from the source releases page, building on Windows 10 with Skia and Visual Studio 2015.

I'm pretty sure I followed the directions to the letter, but I got some undeclared identifiers during the final build. I was able to "hack" it to get it to finish building (described below) but I'm 98.6% sure it's the wrong solution to this problem. The final exe runs and seems to work ok (I didn't mess around with it too much) so hopefully nothing important is broken.

The errors I was getting during the final steps:
    gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false target_cpu=""x86"""
    ninja -C out/Release

And the partial output:
    [99/595] Building CXX object src\she\CMakeFiles\she.dir\skia\skia_surface.cpp.obj
    FAILED: src/she/CMakeFiles/she.dir/skia/skia_surface.cpp.obj
    C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe  /nologo /TP -DCMARK_STATIC_DEFINE -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_SAVE -DENABLE_UPDATER -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_WIN32 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -DUNICODE -DUSE_SKIA_BACKEND -DWINVER=0x0A00 -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0A00 -I..\third_party\zlib -Ithird_party\zlib -I..\third_party\libpng -Ithird_party\libpng -I..\third_party\libwebp\src -I..\third_party\tinyxml -I..\third_party\pixman\pixman -I. -I..\third_party\freetype2\include -I..\third_party\harfbuzz\src -I..\third_party\giflib\lib -I..\third_party\jpeg -Ithird_party\cmark -I..\third_party\curl\include -I..\third_party\simpleini -I..\src -I..\src\.. -I..\src\observable -IC:\deps\skia\include\config -IC:\deps\skia\include\core -IC:\deps\skia\include\utils -IC:\deps\skia\include\codec -IC:\deps\skia\include\gpu -IC:\deps\skia\src\gpu -IC:\deps\skia\third_party\externals\angle2\include -I..\laf -Ilaf -I..\laf\third_party\stringencoders\src /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MT /Zi /O2 /Ob1 /D NDEBUG /showIncludes /Fosrc\she\CMakeFiles\she.dir\skia\skia_surface.cpp.obj /Fdsrc\she\CMakeFiles\she.dir\she.pdb /FS -c ..\src\she\skia\skia_surface.cpp
    C:\aseprite\src\she/skia/skia_surface.h(253): error C2065: 'SK_R16_SHIFT': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(254): error C2065: 'SK_G16_SHIFT': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(255): error C2065: 'SK_B16_SHIFT': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(257): error C2065: 'SK_R16_MASK': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(258): error C2065: 'SK_G16_MASK': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(259): error C2065: 'SK_B16_MASK': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(273): error C2065: 'SK_RGBA_R32_SHIFT': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(274): error C2065: 'SK_RGBA_G32_SHIFT': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(275): error C2065: 'SK_RGBA_B32_SHIFT': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(276): error C2065: 'SK_RGBA_A32_SHIFT': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(277): error C2065: 'SK_RGBA_R32_SHIFT': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(278): error C2065: 'SK_RGBA_G32_SHIFT': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(279): error C2065: 'SK_RGBA_B32_SHIFT': undeclared identifier
    C:\aseprite\src\she/skia/skia_surface.h(280): error C2065: 'SK_RGBA_A32_SHIFT': undeclared identifier

So I don't really know anything about Skia or SHE, so I don't know why these identifiers are not defined. I'm not a practiced C++ person either. But I was able to finish the build by finding by looking at this header https://github.com/google/skia/blob/master/include/core/SkColorPriv.h and copying the definitions directly into the top of C:\aseprite\src\she\skia\skia_surface.h :

    #define SK_R16_BITS     5
    #define SK_G16_BITS     6
    #define SK_B16_BITS     5
    
    #define SK_R16_SHIFT    (SK_B16_BITS + SK_G16_BITS)
    #define SK_G16_SHIFT    (SK_B16_BITS)
    #define SK_B16_SHIFT    0
    
    #define SK_R16_MASK     ((1 << SK_R16_BITS) - 1)
    #define SK_G16_MASK     ((1 << SK_G16_BITS) - 1)
    #define SK_B16_MASK     ((1 << SK_B16_BITS) - 1)

and the following modification:

    //#ifndef SK_BGRA_B32_SHIFT
      #ifdef SK_CPU_BENDIAN
        #define SK_BGRA_B32_SHIFT   24
        #define SK_BGRA_G32_SHIFT   16
        #define SK_BGRA_R32_SHIFT   8
        #define SK_BGRA_A32_SHIFT   0
      #else
        #define SK_BGRA_B32_SHIFT   0
        #define SK_BGRA_G32_SHIFT   8
        #define SK_BGRA_R32_SHIFT   16
        #define SK_BGRA_A32_SHIFT   24
      #endif
    //#endif

Left this in to help anyone over the hump, but something seems to have changed somewhere along the dependencies.

**Comment by dacap** [comment]
I think the INSTALL.md in v1.2.8 is out dated. In the latest INSTALL.md (master branch), the branch to compile Skia is `aseprite-m67` (instead of `aseprite-m62` as in v1.2.8). I think with Skia in branch `aseprite-m67`, Aseprite should compile directly without this workaround.

**Comment by xkisu** [comment]
I'm having the same problem with Visual Studio 2017, I had to make a slightly bigger modification then @GrapeJamMan 

```c
//#ifndef SK_BGRA_B32_SHIFT
  #ifdef SK_CPU_BENDIAN
    #define SK_BGRA_B32_SHIFT   24
    #define SK_BGRA_G32_SHIFT   16
    #define SK_BGRA_R32_SHIFT   8
    #define SK_BGRA_A32_SHIFT   0
    #define SK_RGBA_R32_SHIFT   24
    #define SK_RGBA_G32_SHIFT   16
    #define SK_RGBA_B32_SHIFT   8
    #define SK_RGBA_A32_SHIFT   0
  #else
    #define SK_BGRA_B32_SHIFT   0
    #define SK_BGRA_G32_SHIFT   8
    #define SK_BGRA_R32_SHIFT   16
    #define SK_BGRA_A32_SHIFT   24
    #define SK_RGBA_R32_SHIFT   0
    #define SK_RGBA_G32_SHIFT   8
    #define SK_RGBA_B32_SHIFT   16
    #define SK_RGBA_A32_SHIFT   24
  #endif
//#endif
```
