### ISSUE TITLE
Random occurrence of being unable to replace color until making a selection

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1737]
So this happens now and then, it's an easy fix to get around it but I have no idea what's happening when it happens, so I recorded a video of it so you might be able to figure it out.

In short just in case the video goes missing; sometimes, seemingly completely at random, I become unable to use Replace Color on a layer until I make a selection and remove it by pressing Esc. The error I get is:
"
A problem has occured.

Details:
The current mask/area to apply the effect is completelly invalid.
"

https://www.youtube.com/watch?v=nmSBH5vW1ac

Aseprite 1.2.8 x64
Windows 7 x64

**Comment by dacap** [comment]
I always make that mistake (completelly instead of completely). I'll take a look to this.

**Comment by dacap** [comment]
I can reproduce it:

1. Select a rectangle with the Rectangular Marquee
2. Move the selection outside the sprite canvas (you can move just the selection edges dragging the edges)
3. Deselect (Ctrl+D)
4. Replace Color shows the given error

In your video, after selecting other area (inside the canvas), and deselecting it, the Replace Color started to work again. (Ctrl+A, then Ctrl+D is a workaround too.) I'm going to fix it right now.

**Comment by KashouC** [comment]
Hmm, strange. Doesn't feel like something I would do, seeing as it seems you have to move the box completely outside of the canvas. But maybe it happens that I do, who knows.

Either way, we'll just have to see if this was it, or if there's still something else lurking. Good job until further notice either way! :+1:
