### ISSUE TITLE
Add finite looping to frame tags.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1740]
It be nice to have the option to add a number of repeats to frame tags, so that if you want a set of tagged frames to cycle only a certain number of times, you can give it a loop count. If the count is blank or negative, the tagged loops repeat continuously (as presently). If the count is set to zero, the frames are skipped entirely when the tag is encountered during playback.

If a finite number of loops is set, there could be an option to either play the next frame after the tag or stop the animation once the loop count is exhausted. The loop direction option in the frame tag would be respected for each loop.

If the tag is included when exporting an animated format, tagged frames would be duplicated in the output file as defined.

If two or more tags overlap on the Timeline, the lowermost one (closest to the cel grid) would take precedent (perhaps). Loops are ignored in playback if "Play All Frames (Ignore Tags)" is selected.

The primary function of this feature is to make it easier to create looping animations with intro/lead-in and outro/cooldown frames, in a way that does not require direct duplication of the looping set. It would make it much easier to adjust the number of loops as it would remove the need to duplicate or remove blocks of frames, as well as sparing the complexities of linked frames in those repeated cycles.
I am imagining that, if it were included, it would be included in the "Frame Tag Properties" pane.

It is not exactly an earth-shaking idea but thanks for considering it! :D 

..using ASEprite 1.2.8-x64 on Win10.

**Comment by dacap** [comment]
https://community.aseprite.org/t/loop-counter-needed/3964
https://community.aseprite.org/t/loop-through-tag-frames/4227

**Comment by Hestichan** [comment]
Please prioritize repeat x times tag for loops! (and please make the functionality apply to tag sections within a larger loop section, so the tag sections can repeat small parts x times before continuing on in the larger loop section). Thank you!

**Comment by Hestichan** [comment]
I noticed a repeat field is present in current beta, but it doesn't seem to do anything.

**Comment by mainmango** [comment]
> Hi @Hestichan, could you please check this option:
> 
> https://community.aseprite.org/t/aseprite-v1-3-rc1/17224/6?u=dacap

The repeat feature still doesn't work with that option for me.
