### ISSUE TITLE
"Reference Layer from Clipboard"

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1748]
I love the Reference Layer feature, but could it be expanded to import images directly from the clipboard, as well as from files?

Thanks for considering it! :D
Related to #1321.

..using ASEprite 1.2.8-x64 on Win10.

**Comment by KashouC** [comment]
I don't know how exactly the reference layer works now, but I think it should basically just be another project underlayed (is that a word?) under the current one. So you get to pick the size of the reference layer when you create it, and can move it around and resize and zoom it freely etc while you've got the ref layer selected.

But I realize this is a lot of groundwork to ask for, so yeah, maybe this is a good start. ^^

**Comment by oceanhahn** [comment]
Mainly, I just wanted to tack this small feature into the longer list on #1321 without dredging up a thing from seven months ago directly (although, looking back on it, that is probably what I ought to have done <_<;;;).

In the context of the changes there, this is probably just a matter of adding a function to the **Layer** menu and three lines of code (create a blank Reference Layer+Paste from clipboard), but on its own it could represent a lot more than that, yes.

It would probably be most useful if it came after some revision that allowed Reference Layers to operate in their own colour mode instead of being coerced into an Indexed palette (if the Workspace is in 8P mode).

But yeah, pasting into an extant Reference Layer works.
It would also probably do to have an option (perhaps RMB on Layer in the Timeline?) that converts normal or background layers to reference layers (and vice-versa, colour quanitization and all)...
