### ISSUE TITLE
[FIX] in the compilation for windows using VC 2017 there is error 

### ISSUE THREAD

**Issue by meiry** [aseprite/aseprite#1751]
Describe your bug report or feature request here
In 
https://github.com/aseprite/aseprite/blob/master/INSTALL.md#windows-details
msvc=2017 
should be 
cc=2017

as it show this error:
```
is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false target_cpu="x86" msvc=2017
                                                                                                                                                                                                   ^---
Did you mean "cc"?

The variable "msvc" was set as a build argument
but never appeared in a declare_args() block in any buildfile.
```

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by dacap** [comment]
I've to take a look to this issue. I don't remember compiling the latest version of Skia, so it might be something of the `m67` version.

**Comment by meiry** [comment]
@dacap 
Try it as you suggest in your documentation to compile it . any way this is the fix after changing it , every thing is working fine
