### ISSUE TITLE
Win10: CMake selects incorrect compiler OR CMake incorrectly escapes compiler path

### ISSUE THREAD

**Issue by burito** [aseprite/aseprite#1753]
With VS2017 Community Edition + MinGW installed, following the documentation...

    git clone --recursive git@github.com:aseprite/aseprite.git
    mkdir aseprite/build
    cd aseprite/build
    cmake -G Ninja ..
    ninja

Will result in the following error message...

    [42/1697] Generating zlib1rc.obj
    FAILED: third_party/zlib/zlib1rc.obj
    cmd.exe /C "cd /D C:\Users\username\github\aseprite\build\third_party\zlib && "C:\Program 
    Files\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev0\mingw64\bin\windres.exe" -D GCC_WINDRES -I **snip**
    'C:\Program' is not recognized as an internal or external command, operable program or batch file.
    C:\Program Files\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev0\mingw64\bin\windres.exe: preprocessing failed.
    [51/1697] Building C object third_party/zlib/CMakeFiles/zlibstatic.dir/inflate.obj
    ninja: build stopped: subcommand failed.

When executed from within the "x64 Native Tools Command Prompt for VS 2017".

Renaming the default install directory of MinGW outside of the path allows it to work. Although the fix in #1752 must be applied for it to actually compile.

### Aseprite and System version

* Aseprite version: a4d1833a9c37aa95c67185ee8632bd4b9f8d84fc
* System: Windows 10
VS2017 Community Edition
Any recent MinGW in your path.

Fortunately, the CMake setup isn't aware of Clang (which is also installed, correctly).

**Comment by dacap** [comment]
You should not compile Aseprite with MinGW in your PATH. We support MSVC only.

**Comment by burito** [comment]
It's supposed to detect that it is in the MSVC build environment, and use that. Blindly grabbing the first copy of GCC in the path should be considered a bug. Also it *is* incorrectly escaped.

**Comment by dacap** [comment]
I guess that we could consider this a cmake bug or a zlib. In the zlib CMakeLists.txt there is this code:
```
if(MINGW)
    # This gets us DLL resource information when compiling on MinGW.
    if(NOT CMAKE_RC_COMPILER)
        set(CMAKE_RC_COMPILER windres.exe)
    endif()
...
```
I don't know why cmake puts `MINGW = true` in this case, but as I said, I don't have plans to support a mixed compilation (MinGW shouldn't be in the PATH). Sorry.
