### ISSUE TITLE
Aesprite crashes if you Lock Windows

### ISSUE THREAD

**Issue by burito** [aseprite/aseprite#1754]
* Load Aseprite
* Lock Windows (Windows Key + L)
* Enter your password to unlock windows.
* Aesprite has locked up.

### Aseprite and System version

* Aseprite version: a4d1833a9c37aa95c67185ee8632bd4b9f8d84fc
* System: Windows 10

**Comment by dacap** [comment]
Did you compile Aseprite with the Allegro backend or Skia backend?

**Comment by burito** [comment]
Allegro, all built according to the docs. #1753 has the exact commands I used.

**Comment by dacap** [comment]
Actually the Allegro port on Windows is not maintained anymore (the official version is the Skia one), so I'm not sure if it does work correctly. I should remove it directly from Windows (after I move the Linux port to Skia, the Allegro code will be finally completely removed, #139).

**Comment by dacap** [comment]
You can give a try to the Skia port and see if it crashes when you lock/unlock your session.

**Comment by dacap** [comment]
I'll close this issue but tell me if the problem continues with the Skia version.
