### ISSUE TITLE
Go to next/previous frame within tag jumps to loop tag when used outside of it

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1756]
So it doesn't always do this, it only does it when you try to move "away" from the loop tag. So if you have a tag on frames 10-20, and you're currently on frame 5, and use go to previous frame within tag, it will jump to frame 20, while using go to next frame within tag at frame 5 will simply go to frame 6.

In my opinion it shouldn't jump to the loop tag this way since I'm outside of the tag, and I assume this is a bug. Video example below.

https://www.youtube.com/watch?v=ISkE_eKMFUY

Aseprite v1.2.9-beta2-x64
Windows 7 x64

**Comment by dacap** [comment]
This problem happens only with the "Loop" tag. Going to fix for v1.2.9
