### ISSUE TITLE
Cannot build on Linux

### ISSUE THREAD

**Issue by irakliy01** [aseprite/aseprite#1757]
Cannot build on Linux. After command `ninja aseprite` it shows 

> [988/1531] Building CXX object src/net...keFiles/net-lib.dir/http_headers.cpp.o
ninja: build stopped: subcommand failed.

### Aseprite and System version

* Aseprite version: [v1.2.8](https://github.com/aseprite/aseprite/releases/tag/v1.2.8)
* System: Ubuntu 18.04

**Comment by dacap** [comment]
Hi there, is there any other output/compilation error?
