### ISSUE TITLE
Opening the export interface at the same time as you click with the move tool locks you to moving

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1759]
Not sure how to title this bug but I did my best. 

So this works with both the pen tool and with the move tool, as holding CTRL down with the pen switches over to move.

Basically all you have to do is have a cel with something drawn in it, you hold down CTRL with the pen tool and click at the exact same time as you open up the export sprite sheet interface (it's a little tricky), and it will lock the cel to being moved around even when you're not holding down CTRL or the mouse button at all, and clicking with the pen will result in an error. (For reference I use CTRL+E as the export sprite sheet keybind).

Video example:
https://www.youtube.com/watch?v=LK7f7fk4hgM

I need a better microphone.

**Comment by dacap** [comment]
Nice catch. The worst thing is that we cannot exit from that state, the sprite is locked forever.

**Comment by Gasparoken** [comment]
I can no longer reproduce this bug in version 1.3.2
