### ISSUE TITLE
I have some Issue with Wacom Tablet

### ISSUE THREAD

**Issue by ppfoot** [aseprite/aseprite#1760]
Hi, I'm using Aseprite 1.3.0 version. I'm usually use a mice for drawing and I bring my old tablet at my parent's home yesterday.

But turns out it has some problems while I' m trying to using it. When the tip of a pen touches tablet, its pointers got stuck and can't recognize the movement

My tablet is a kinda old model (Bamboo Fun CTH-661) but it works fine in the Photoshop or other softwares.

I have found a way to using it somehow, however it requires me to use it very delicately, by merely touches the tablet and move very slowly. which is almost impossible to work with it.

If any one has same or similar issue as I am and knows how to fix it, please help me to solve this problem.  Thank you.

### Aseprite and System version

* Aseprite version: 1.3.0 / commit-hash:c3e233f34de633255fee4586ded942920a1a3b8f
* System: Windows 10

**Comment by dacap** [comment]
Hi @ppfoot, did you compile with the Allegro back-end? Because these kind of problems shouldn't be an issue with the Skia back-end (the Wacom driver should work just fine in the Skia back-end).

**Comment by ppfoot** [comment]
thanks for solution answer. i'll compile with Skia back-end and check again.

**Comment by dacap** [comment]
I'll close this issue at the moment but you can just comment here in case that you find some problems with the Skia version too.

**Comment by masa1995** [comment]
Hallo
