### ISSUE TITLE
Using simple math for number textboxes

### ISSUE THREAD

**Issue by Jengamon** [aseprite/aseprite#1762]
I was wondering if there are plans to support math expressions in textboxes that should take a number, esp. the new document creation dialog. Something like Krita, where instead of calculating what 32 * 22 for 22 side by side sprites of width 32, you can simply type it into the box, and the program automatically parses the statement and puts the value into the entry for you, once it loses focus. An error (math expression isn't complete; expecting an integer, but got a float, etc.) could show something like "MATH ERROR", or it could just default to 0, whichever is simpler.

**Comment by dacap** [comment]
I think someone asked for this same feature before. It might be easy to implement for the next version.

Note for developer: we can use this library https://github.com/codeplea/tinyexpr

**Comment by moti5565** [comment]
#1762

**Comment by dacap** [comment]
A simple version will be available in the next release! 👍

**Comment by Jengamon** [comment]
yey!

**Comment by dante8300** [comment]
Hi, can anyone provide a good example of this or how is this practical?

**Comment by dacap** [comment]
You can write `30*2` and you will get `60` (e.g. if you want to resize x2), or `1000/60` and you will get `33` (e.g. if you want to use `Frame > Constant Frame Rate` and use 60 fps)

**Comment by KasumiArai** [comment]
If you have 16x16 tiles, you can make an image that's that many tiles long more easily. 16*200 for width 16*40 for height.

**Comment by ElderlyGlek** [comment]
@dacap, can you add the ability to use simple math in the palette popup? I thought simple math works everywhere, so I was surprised when I couldn't divide the red value in the palette popup by 2.

**Comment by Gasparoken** [comment]
> @dacap, can you add the ability to use simple math in the palette popup? I thought simple math works everywhere, so I was surprised when I couldn't divide the red value in the palette popup by 2.

Good idea, issue created: https://github.com/aseprite/aseprite/issues/3900
