### ISSUE TITLE
Window resizing bug(?)

### ISSUE THREAD

**Issue by jayrhic** [aseprite/aseprite#1763]
It appears that resizing the window of aseprite seemed to be rough.
![image](https://user-images.githubusercontent.com/40538422/41818374-27c899b6-77e0-11e8-82b4-247c9ee5eac8.png)

### Aseprite and System version

* Aseprite version: v1.2.8, Steam
* System: Windows 10, 64-bit

**Comment by dacap** [comment]
Yeah, never had the time to really fixed it. I'll give a try.

**Comment by jayrhic** [comment]
I see, keep up the good work then! Fighto!!

**Comment by dacap** [comment]
Already some work in progress for v1.2.10-beta.

Patch for macOS 30481c99dcd37a1abf2f098c49a3822f4c5c6153, we still need to work on Windows and Linux ports.
