### ISSUE TITLE
A hotkey for toggling preview playback

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1774]
The preview is nice for seeing the animation while drawing, but when it's paused it also lets me look at my animation frame by frame in two sizes simultaneously. (You can have multiple views of different sizes, but changing the frame on one does not change it on the other.)

It'd be nice to switch between these two benefits without having to mouse the cursor from the canvas to click the preview's play button.

**Comment by KashouC** [comment]
Could probably just skip figuring out a default hotkey for it as well and just implement the bind itself.

**Comment by dacap** [comment]
Maybe Shift+Enter could be the default hotkey?

**Comment by KashouC** [comment]
Probably.

**Comment by KasumiArai** [comment]
This is the quick support that makes Aseprite great! Yeah, I wasn't married to the idea of any particular hotkey or even needing a default one, but ctrl+enter is a fabulous choice.
