### ISSUE TITLE
Status bar data display bug on selected colour palette swatch mouseover.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1777]
When the cursor passes over palette swatches, it normally displays their index and colour values in the status bar. It does not do this when the cursor passes over the currently-selected swatch, and does not show data for the subsequent swatch either. The problem goes away on the third mouseover swatch (as long as it is not the current color), whose data reappears on the status bar as normal.

This is what it looks like:
![statusbar rgb](https://user-images.githubusercontent.com/11544843/42173525-554ebd1c-7ded-11e8-8ecb-1bac68a180ca.gif)

Thanks for taking a look! :D

..using ASEprite 1.2.8-x64 on Win10.

**Comment by masa1995** [comment]
Hallo
