### ISSUE TITLE
Timeline does not scroll when frames or cels are dragged to its margins.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1780]
![timeline scroll](https://user-images.githubusercontent.com/11544843/42339064-dc71a6e2-8059-11e8-83df-4192b3117a81.gif)

The Timeline scrolls during selection for frames, cels, and layers when the cursor is dragged to its outer bounds, but selections cannot be _moved_ this way when they are dragged. This makes it easy to collect many cels, frames, _et cetera_ over large ranges (which is fantastic!), but difficult to _move them long distances_ (not so great).

It would be great if the Timeline could be revised to allow scolling on drag.

Thanks for considering it! :D 
_(Somewhat related to #1344 and possibly related to #1744.)_

..using ASEprite 1.2.8-x64 on Win10.

**Comment by dacap** [comment]
Yeah, known issue. At the moment, on macOS you can use the trackpad to scroll, or on other platforms the mouse wheel, but it's just a workaround.

**Comment by Gasparoken** [comment]
Gracias! Mañana me ocupo.

Saludos,
