### ISSUE TITLE
Add "Reverse Frames" to the Timeline RMB context menu.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1781]
This might be a trivial issue but I found myself wondering for the third time today why the "Reverse Frames" command (Frame/Reverse Frames; [ALT-i] ) is not in the Timeline RMB context menu, and do you think it ought to be added? 
As in the Menu Bar, the function would be inactive when only a single frame is selected.

Normally, I would be against making click-menus larger than they need to be, but it seems to me that this one sort of _belongs_ there.

Looking forward to your thoughts! :D 

..using ASEprite 1.2.8-x64 on Win10.

**Comment by dacap** [comment]
This one was easy 😄

**Comment by oceanhahn** [comment]
I have to throw you an easy one _sometimes._
I guess. 😒
