### ISSUE TITLE
Color palette does not scroll

### ISSUE THREAD

**Issue by chongx1an** [aseprite/aseprite#1796]
The color palette does not scroll while moving the color toward up or down.

![aspritebug](https://user-images.githubusercontent.com/40559684/43083111-52ad9d76-8ec8-11e8-9903-5a3c7f2ea3ea.gif)

### Aseprite and System version

* Aseprite version: v1.3-dev
* System: Windows 10

**Comment by dacap** [comment]
Related to #772, some scroll issues to solve

**Comment by chongx1an** [comment]
Thx

**Comment by Vcoder89** [comment]
Working on a fix.

**Comment by chongx1an** [comment]
One question:
The "palette entry" refers to the first color in the palette?

**Comment by Vcoder89** [comment]
My change doesn't affect anything named "palette entry" so I'm assuming you're talking about "dragPicks.firstPick()" which the name itself should help out, it's purely the first slot you pick from the drag & drop action, so if you selected 7 and start dragging them around, it will use the first one you clicked on to correctly pan the scroll. Hope this helps. I'm still working on this based on dacap's review.

**Comment by chongx1an** [comment]
Ok, thanks for your answer
