### ISSUE TITLE
Im getting an error when compiling aseprite

### ISSUE THREAD

**Issue by Rotekoppen** [aseprite/aseprite#1799]
Im getting an error when "compiling ninja?"

The command "cmake -DUSE_ALLEG4_BACKEND=OFF -DUSE_SKIA_BACKEND=ON -DSKIA_DIR=C:\deps\skia -G Ninja .." returns an error:

[https://pastebin.com/czU48sy1](url)

**Comment by dacap** [comment]
Hi @Rotekoppen, can you paste the output in the console/terminal?

**Comment by Rotekoppen** [comment]
C:\aseprite\build>cmake -DUSE_ALLEG4_BACKEND=OFF -DUSE_SKIA_BACKEND=ON -DSKIA_DIR=C:\deps\skia -G Ninja ..
CMake Deprecation Warning at CMakeLists.txt:20 (cmake_policy):
  The OLD behavior for policy CMP0046 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:39 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:39 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/aseprite/build/CMakeFiles/CMakeOutput.log".
See also "C:/aseprite/build/CMakeFiles/CMakeError.log".

C:\aseprite\build>

**Comment by dacap** [comment]
It looks like the compiler (MSVC) is not set in your command line, you have to start the Visual Studio command line so the `cl.exe` and `link.exe` programs are available from the command line. You can check this trying to execute `cl` or `link` in the command line, if the command is not found, you are not using the Visual studio command line.

**Comment by Rotekoppen** [comment]
Ran it with the dev command line, still no luck:
[https://pastebin.com/p0PRzMfu](url)

**Comment by dacap** [comment]
Do you have the Skia library compiled in `C:\deps\skia` directory? From the log it looks like the library wasn't found in that directory.

**Comment by Rotekoppen** [comment]
Well, most of the folders are inside of C:\deps\skia\skia\ should they be there?

**Comment by dacap** [comment]
They should be in :\deps\skia, but don't worry, you can run cmake ... with -DSKIA_DIR=C:\deps\skia\skia and see if it works

**Comment by Rotekoppen** [comment]
I moved everything out of the folder, but ninja will now not compile it.
[Paste.txt](https://github.com/aseprite/aseprite/files/2229000/Paste.txt)
