### ISSUE TITLE
Being able to click to select a pixel with marquee tool

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1811]
I seem to remember this being possible many many versions ago, but now to select a single pixel with the marquee tool you have to drag at least 1 on-screen pixel for it to get selected, instead of being able to just click. I think the marquee tool is just selecting a 0,0 width when you click so it doesn't grab anything, but imo it should be 1,1 so you always get what you click on, unless there's a reason for this.

Aseprite v1.2.9-x64
Windows 7 x64

**Comment by dacap** [comment]
Maybe introduced in v1.0.3 (year 2014, 877d498160576a3563c634f78b6bfe986bf1108e), basically some users were asking to have the possibility to deselect with one click (like some other programs).

**Comment by KashouC** [comment]
Ooh it works like that in replace mode. I always use it in add to selection mode, maybe it could be changed only there since it doesn't deselect with a click there anyway?

**Comment by KashouC** [comment]
Haha, sounds great!
