### ISSUE TITLE
Not Able To Change Palette Colors

### ISSUE THREAD

**Issue by mariosonic500** [aseprite/aseprite#1814]
I think this is a recent issue, and it probably has something to do with a setting I didn't realize I changed or something like that. So I select a color in my palette by clicking on it:
![image](https://user-images.githubusercontent.com/37677607/43503314-a3c2ad04-9513-11e8-8392-703b535d8da1.png)
And then I use the color picker box  to change the color: 
![image](https://user-images.githubusercontent.com/37677607/43503353-d176c10e-9513-11e8-8669-f1fa238df543.png) 
The color in the palette just gets unselected, and if I want to save my new color, I have to manually add it to the palette.

* Aseprite version: version 1.2.9 on Steam
* System: Windows 8

**Comment by dacap** [comment]
@mariosonic500 you can use the A key to switch the palette editing function. Basically if this padlock is unlocked, it means that the palette can be edited:

![screen shot 2018-08-01 at 14 10 29](https://user-images.githubusercontent.com/39654/43537087-b8208858-9594-11e8-8381-99c2807ec5e9.png)
