### ISSUE TITLE
Add option to hide/disable undo/redo tooltips

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1827]
Add an option to hide these tooltips:

![cs-0f9bp](https://user-images.githubusercontent.com/39654/43839208-ede2fffc-9af3-11e8-8671-df1e0aa617ae.jpg)

We might have three different options:
- Show undo/redo tooltip
- Show undo/redo info in status bar
- Don't show undo/redo action

**Comment by andrygreen777** [comment]
Tgg
