### ISSUE TITLE
"Add Foreground/Background Colour to Palette" does not work in RGB mode.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1838]
...and I feel like it ought to?
Even if the pixels are not indexed, it is still really handy to keep all those great palette options open! ;3

Thanks for looking into it! :D 

..using ASEprite 1.2.9-x86 (installer) on Win10.

**Comment by KashouC** [comment]
How exactly are you trying to add it to palette? It works just fine for me, with or without it as a keybind or clicking the ! box next to the color.

**Comment by oceanhahn** [comment]
Keyboard shortcut.
I actually had forgotten about the "!" button entirely.
Seems to work now, but I cannot figure out what the problem might have been.
Maybe the colour was already in the palette somehow??

Hm. I guess this is a non-issue after all.
I will reopen it if I can narrow down what happened.

Thanks! :D
