### ISSUE TITLE
Shift+Click to erase a line with the Eraser does not work

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1843]
Shift+Click to "draw" a line from the last point does not work with the eraser. Generally forces you to use the line tool as an eraser as well, with mask as color. As an uneducated suggestion for a solution, perhaps the Eraser could simply be a Pencil ink in disguise as a tool, to make it maintain Pen functionality properly? 

Aseprite 1.2.9-x64
Windows 7 x64

**Comment by dacap** [comment]
This is strange but I'm testing on macOS and Shift+click does works for the Eraser. I'll give a try to this on Windows next week.

**Comment by KashouC** [comment]
Oh, false alarm. I'm the one who removed the shift command from the keybinds because I kept accidentally making lines lmao. Never mind. ^^
