### ISSUE TITLE
File path and name are garbled (like this, □)

### ISSUE THREAD

**Issue by Torgue945** [aseprite/aseprite#1846]
After I reinstall my laptop's system and Aseprite, _Open_ or _Save_ file path and name can't show correctly. The chinese characters in the file name  become □ as you see in following screenshot.
![image](https://user-images.githubusercontent.com/26424753/44506738-52617480-a6da-11e8-99c9-5c337247a0a7.png)

### Aseprite and System version

* Aseprite version: v1.2.9-x64, Steam, No Extensions
* System: Windows 7 Ultimate SP1
* System Language: Simplified Chinese

**Comment by dacap** [comment]
Hi @Torgue945, do you know the name of the font (.ttf file) in your system that contains Chinese characters? By default Aseprite tries to use Arial Unicode (arialuni.ttf) for Chinese, but might be good to know an alternative that is installed by default on Windows 7.

**Comment by Torgue945** [comment]
After I install Arial Unicode, file path and name show correctly. @dacap Thank you so much!!!!
