### ISSUE TITLE
Compilation fail on Windows 10 with TDM-GCC-64 mingw64 toolchain

### ISSUE THREAD

**Issue by danvim** [aseprite/aseprite#1862]
Compilation failed due to redefinitions, presumably conflicts between `../third_party/curl/*` and `TDM-GCC-64/x86_64-w64-mingw32/include/winsock2.h`

### Relating issue

#1690

### Console dump:

https://gist.github.com/danvim/2055eca4d225749dc5c2716ec9e00972

### Aseprite and System version

* Aseprite version: 1.2.9
* System: Windows 10
* Toolchain: tdm64 bundled with mingw-w64 (http://tdm-gcc.tdragon.net/download)

**Comment by dacap** [comment]
Actually we don't support MinGW toolchain (mainly because we don't use the Allegro back-end anymore, and was finally removed for the next v1.2.10 version), and I think Skia cannot be compiled with MinGW (but I'm not sure about this).

**Comment by danvim** [comment]
@dacap Is the supported toolchain mentioned anywhere? Because I'm not aware of it?

**Comment by dacap** [comment]
Actually in the [INSTALL.md](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#windows-dependencies) Visual Studio is named as a dependency, anyway it's true that cmake does some crazy things like getting the first compiler that it wants.

I'm not sure how we could solve this, maybe some extra parameter in the cmake command line that avoid using mingw, or some extra instructions to remove mingw from the PATH.

**Comment by danvim** [comment]
@dacap I actually temporarily removed MinGW from PATH just now, and attempting compilation. Thanks for the help. May I suggest warning users this particular problem in the install instructions?
