### ISSUE TITLE
gn (depot-tools) command is broken?

### ISSUE THREAD

**Issue by DuendeInexistente** [aseprite/aseprite#1863]
I got depot-tools and skia following the instructions in INSTALL.MD to build a new version, but gn seems to be broken: if ran outside it's own folder (Wether or not $path is set as instructed) it fails to find its .py file, and if ran inside its own folder it has a python error. Not that I think this would work anyway, as if probably requires being ran in skia's folder to do its thing.

These are the errors I get:

````
~/deps/depot_tools                                                                                                                                                                                        17h43m  
▶ gn gen ../skia/out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false extra_cflags_cc=[\"-frtti\"]"

Traceback (most recent call last):
  File "/home/cammera/deps/depot_tools/gn.py", line 71, in <module>
    sys.exit(main(sys.argv))
  File "/home/cammera/deps/depot_tools/gn.py", line 49, in main
    'gn', 'gn' + gclient_utils.GetExeSuffix())
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

~/deps/depot_tools                                                                                                                                                                                       17h43m  ⍉
▶ cd ../skia

~/deps/skia                                                                                                                                                                                                   2d  
▶ gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false extra_cflags_cc=[\"-frtti\"]"                                  

gn.py: Could not find gn executable at: /home/cammera/deps/skia/buildtools/linux64/gn
````

### Aseprite and System version

* Aseprite version: f292b4b96
* System: Ubuntu 17.10

**Comment by dacap** [comment]
The `gn` command must be executed in the Skia directory. Remember to include `depot_tools` dir in the PATH (you must follow the exact steps as in [the INSTALL.md guide](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#skia-on-linux))

**Comment by DuendeInexistente** [comment]
As I said, I added depot_tools to the path properly.

Upon executing gn in skia's directory the program will freeze until I use CTRL+C. [I am linking the whole error](http://paste.ubuntu.com/p/f9dfbV24Br/) rather than posting it here because it's just that long.

**Comment by DuendeInexistente** [comment]
'kay, this must be an issue in my own system.
No idea why, but the command actually finished... after about two hours of doing nothing. I had forgotten it was even in one of my terminal tabs.
