### ISSUE TITLE
Keep layers for conversion between spritesheets and framed animations

### ISSUE THREAD

**Issue by Diarandor** [aseprite/aseprite#1869]
Keep layers for conversion between spritesheets and animations.

1) When exporting an ase file with an animation (several frames) to a spritesheet in ase format, the layers are lost, which is too bad. And viceversa, if we want to recover back an animation from a spritesheet, layers are lost too. So the layers should be kept in both directions "spritesheet <-> framed animation".

Remark: the conversion "spritesheet -> framed animation" would be applied to one frame of the spritesheet.

2) Maybe this would be better in another issue: in the conversion "framed  animation -> spritesheet ", it would be nice to add an option to put each tag in a different row (or column), so that we can recover the same multilayered spritesheet if we use the conversions "spritesheet -> framed animation -> spritesheet". This is very useful if you work with layered spritesheets (which make it easier to copy-paste things and see all globally) and framed animations (which are better to see the animation when drawing) at the same time). In the conversion "spritesheet -> framed animation", you could add an option to create automatically a tag for each row (or column), so that we do not need to create them to create the last spritesheet in the conversions.

@dacap I like to work in multilayered spritesheets, but they do not allow to see the animation, and the conversion destroys the layers, making that feature completely useless for me. I need these features a lot. Could it be done for the next version, or at least soon? Thanks a lot for your hard work! Aseprite is awesome.

**Comment by Diarandor** [comment]
-I've been thinking and better to forget (2), it is unnecessary. We can create a "framed animation" with the same frame of all different animations in the same column, so no need to do that mess.

But still feature (1) is almost a must do.

**Comment by Diarandor** [comment]
It seems that I should have been using layered frames during these last years instead of layered spritesheets. I can put all NPC (or enemy) directions on each frame, one below the other, and then generate the png spritesheet from there in 1 second. From now on I will always work on framed files, so I won't really need this feature anymore (and therefore it's not urgent for the next version of aseprite).

**Comment by dacap** [comment]
OK @Diarandor, I'll close this issue. There is one missing part which is the "export each tag in a row", there is an issue about that too #1118
