### ISSUE TITLE
Can't find RGB sliders!

### ISSUE THREAD

**Issue by FautenicOfficial** [aseprite/aseprite#1870]
In a previous version, I could click on a button to edit a color's RGB values with sliders. Now that button seems to be replaced with some kind of lock. Where was this menu moved to?

### Aseprite and System version
* Aseprite version: 1.2.9
* System: Windows 10

**Comment by KashouC** [comment]
When the lock is "unhinged" the color of the selected index is edited via the palette editor (F4). Clicking the foreground or background colors in the bottom left will open the same interface.
