### ISSUE TITLE
Edit > Flip then Edit > Shift throws error

### ISSUE THREAD

**Issue by andyhall** [aseprite/aseprite#1873]
## Steps:

 1. New empty file
 2. Select an area (e.g. with `ctrl+A`)
 3. `Edit > Flip Horizontal` (or vertical)
 4. `Edit > Shift > Left`  (or any direction)

## Throws:

> Cannot modify the sprite.
> It is being used by another command.

### Aseprite and System version

* Aseprite version: **1.2.9-64 (Steam)**
* System: **win 10**

**Comment by MJJBennett** [comment]
Same error.

- Aseprite version: **1.3-dev** 

- System: **Ubuntu 18.04**

Looks to be an issue with the **Shift** command (and not **Flip**) as I was able to reproduce the bug by selecting `Edit > Rotate > *` and then `Edit > Shift > *` as well.
