### ISSUE TITLE
Caps lock is ignored when typing in text fields

### ISSUE THREAD

**Issue by jfro** [aseprite/aseprite#1876]
I've noticed that typing in text fields ignores caps lock. I can use shift OK so it's not like it was forcing all lowercase.  Didn't notice if there was a reason or alternate use given to the caps lock so figure I'd file it.

### Aseprite and System version

* Aseprite version: 1.2.9, portable(dmg)
* System: macOS, 10.13.6

**Comment by jfro** [comment]
Just tested on Windows 10, caps lock seems to function just fine there.

**Comment by dacap** [comment]
:open_mouth: Never noticed that, you're right!

**Comment by oceanhahn** [comment]
Works in Win10 confirmed.

(Those are some very Belgian tags you have there. 😜 )
