### ISSUE TITLE
Timeline does not scroll while dragging (moving) Cels beyond its edges.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1878]
The Timeline scrolls when a range of Cels is being selected, but _not_ if they are being moved in a similar way. It would be very, very useful if the Timeline would scroll in a similar way during Cel moves as well as range selection drags.

![timeline-move-cel-scroll](https://user-images.githubusercontent.com/11544843/45235752-e705ce00-b2a7-11e8-9851-dcdc62141509.gif)

Thanks for considering it! :D 
..possibly related to #1344.

..using ASEprite 1.2.9-x86 (installer) on Win10.

**Comment by dacap** [comment]
Hi @oceanhahn, I think you've already reported this here #1780, it's fixed for the next release v1.2.10-beta1 to be released soon (hope next week)

**Comment by oceanhahn** [comment]
Goddamnit, I did not know Git did not search my closed tickets too, so I missed the old report entirely.
Ha ha. Embarrassing. Sorry for the duplicate! 😓
