### ISSUE TITLE
Display bug with Linked Cels at left edge of Timeline.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1879]
![timeline-group-leftedge-display](https://user-images.githubusercontent.com/11544843/45236895-34d00580-b2ab-11e8-9396-2693637f6e85.gif)
🔼 <sub>_(All I am doing here is scrolling left and right.)_</sub>

This is a really trivial bug, but when a consecutive block of Linked Cels move off the left edge of the Timeline, the leftmost _visible_ one appears as the _initial_ Linked Cel when it is actually not the first in that block. This only happens when the Timeline is aligned perfectly to the left edge. The bug does not occur at the right edge.

It is a minor issue but maybe it would be an easy fix?
Anyway, thought you ought to know. :y 

..using ASEprite 1.2.9-x86 (installer) on Win10.

**Comment by dacap** [comment]
Known issue, anyway it's nice to have this reported here.
