### ISSUE TITLE
Option to clear excluded pixels during Crop.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1880]
Currently, the Crop command only resizes and aligns the canvas bounds to a Marquee selection, leaving excluded pixels concealed but untouched. I would like to have an option to delete these pixels entirely on Crop.

This is useful for isolating sprites in a larger animated document, so that the isolated Cels may be copied from the Timeline without bringing the excess pixels over. Currently, all of the Cels' data is copied, even the pixels outside of the canvas area.

Retaining excluded pixels post-Crop is useful is many _other_ situations, however, and so I would like to have the new out-of-bounds-pixel-purging Crop option listed _in addition to_ the current out-of-bounds-pixel-preserving Crop command.

Thank you for considering it! :D 

..using ASEprite 1.2.9-x86 (installer) on Win10.

**Comment by dacap** [comment]
Related to #1111

**Comment by dacap** [comment]
I think the option in Canvas Size would be enough for this: https://github.com/aseprite/aseprite/issues/1111#issuecomment-485517978

**Comment by PacketLauncher** [comment]
Seems an old request. I have just now found this annoying and reported it with a GIF example here:
https://community.aseprite.org/t/cropping-doesnt-discard-non-selected-pixels/22170/1

![Cropping_Issue](https://github.com/aseprite/aseprite/assets/36102054/cd70d636-6340-49ee-b41a-07c8a666515d)

Cropping / trimming should clear excluded pixels from the canvas, just like in other image editing programs such as Photoshop. If it was intended to behave as it currently does in Aseprite, then I think that there should either be an option to change this behavior in the Preferences, or to have an additional crop option under the Sprite menu which actually clears the excluded pixels.

**Comment by dacap** [comment]
Hi @PacketLauncher, just answered your post in https://community.aseprite.org/t/cropping-doesnt-discard-non-selected-pixels/22170/2?u=dacap 👍
