### ISSUE TITLE
"Unable to create a user-interface display. Details: Unknown error Error initializing module: gui"

### ISSUE THREAD

**Issue by tosho** [aseprite/aseprite#1883]
I was following INSTALL.md with exact steps:

    sudo apt-get update -qq
    sudo apt-get install -y g++ libx11-dev libxcursor-dev cmake ninja-build
    git clone --recursive https://github.com/aseprite/aseprite.git
    cd aseprite
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=~/apps/aseprite -G Ninja ..
    ninja aseprite
    ninja install

then cd bin/ (or cd ~/apps/aseprite/bin/) ./aseprite gives me this error in terminal: 
   
     Unable to create a user-interface display.
     Details: Unknown error
     Error initializing module: gui
     Error initializing module: gui
 
### Aseprite and System version

* Aseprite version: 1.3dev (also  Aseprite v1.2.9 )
* System: Ubuntu 18.04
* gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
* cmake version 3.10.2
* ninja 1.8.2

**Comment by dacap** [comment]
Did you try to compile a specific commit (which one) AND v1.2.9? what was the full console output of the cmake command on each case?

**Comment by tosho** [comment]
> Did you try to compile a specific commit (which one) AND v1.2.9? what was the full console output of the cmake command on each case?


Ok. that's really  strange.
So the first was with `git clone --recursive https://github.com/aseprite/aseprite.git` and after that I tried with https://github.com/aseprite/aseprite/releases/download/v1.2.9/Aseprite-v1.2.9-Source.zip (both leading to that error when I try to run ./aseprite) 
After that I installed gcc-4.8 (I had only 7.3 installed)  and download the Aseprite-v1.2.8-Source.zip and repeat the same steps. And now instead to have aseprite v1.2.8 I have the v.1.3-dev. Again tried to build from v.1.2.9 in different folder and it works! but again it's the v1.3-dev not the v1.2.9.
Why is that happening? downloading and building v1.2.8/9 installs v1.3-dev?

**Comment by tosho** [comment]
[aseprite-1.2.9.txt](https://github.com/aseprite/aseprite/files/2380099/aseprite-1.2.9.txt)
That doesn't make sense to me. I've uninstall gcc-4.8* and again try to compile v1.2.9-Source and again the version is v1.3-dev (working)

**Comment by dacap** [comment]
The version number in the source.zip doesn't matches the version number in the config.h. This is because we zip the source code as it is and update the version before we compile. So basically you have the equivalent to the v1.2.9 version (but compiled from source code).

**Comment by tosho** [comment]
I think have found what's the problem on my side. I might forgot/skip to compile Skia the first time. 
So now I tried first to compile Skia for Linux following ` https://github.com/aseprite/aseprite/blob/master/INSTALL.md#skia-on-linux ` but I'm stuck on the line: 
` gn gen out/Release --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"  `
which gave me : ` gn: command not found `
so installed GN via NPM (npm i -g gn) which this time gave me: ` Done. Made 43 targets from 26 files in 55ms `
but running ` ninja -C out/Release skia ` again doesn't work - 
[ninja-out-Release.txt](https://github.com/aseprite/aseprite/files/2380664/ninja-out-Release.txt)

**Comment by dacap** [comment]
If you are going to compile the master branch (not the v1.2.9 zip), then yes, you need to compile Skia first. Please check the steps correctly from the INSTALL.md file, you need the `depot_tools` first (where is the gn tool). Also there are other steps to sync dependencies for skia.

**Comment by tosho** [comment]
> If you are going to compile the master branch (not the v1.2.9 zip), then yes, you need to compile Skia first. Please check the steps correctly from the INSTALL.md file, you need the `depot_tools` first (where is the gn tool). Also there are other steps to sync dependencies for skia.

tosho@T440:~/deps/skia(aseprite-m67)$ gn gen out/Release --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"

`    Done. Made 43 targets from 26 files in 266ms `
tosho@T440:~/deps/skia(aseprite-m67)$ ninja -C out/Release skia
```
ninja: Entering directory `out/Release'
[64/1210] compile ../../src/ports/SkFontConfigInterface_direct.cpp
FAILED: obj/src/ports/fontmgr_fontconfig.SkFontConfigInterface_direct.o 
c++ -MMD -MF obj/src/ports/fontmgr_fontconfig.SkFontConfigInterface_direct.o.d -DNDEBUG -DSK_SAMPLES_FOR_X -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_ENABLE_DISCRETE_GPU -DSKIA_IMPLEMENTATION=1 -I../../include/android -I../../include/c -I../../include/codec -I../../include/config -I../../include/core -I../../include/effects -I../../include/encode -I../../include/gpu -I../../include/gpu/gl -I../../include/atlastext -I../../include/pathops -I../../include/ports -I../../include/svg -I../../include/utils -I../../include/utils/mac -I../../include/private -I../../src/c -I../../src/codec -I../../src/core -I../../src/effects -I../../src/fonts -I../../src/image -I../../src/images -I../../src/lazy -I../../src/opts -I../../src/pathops -I../../src/pdf -I../../src/ports -I../../src/sfnt -I../../src/shaders -I../../src/shaders/gradients -I../../src/sksl -I../../src/utils -I../../src/utils/win -I../../src/xml -I../../third_party/gif -I../../src/gpu -fstrict-aliasing -fPIC -w -Wall -Wextra -Winit-self -Wpointer-arith -Wsign-compare -Wvla -Wno-deprecated-declarations -Wno-maybe-uninitialized -Wno-implicit-fallthrough -Wno-unused-parameter -O3 -fdata-sections -ffunction-sections -std=c++11 -fno-exceptions -fno-rtti -c ../../src/ports/SkFontConfigInterface_direct.cpp -o obj/src/ports/fontmgr_fontconfig.SkFontConfigInterface_direct.o
In file included from ../../src/ports/SkFontConfigInterface_direct.cpp:13:0:
../../src/ports/SkFontConfigInterface_direct.h:14:10: fatal error: fontconfig/fontconfig.h: No such file or directory
 #include <fontconfig/fontconfig.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[69/1210] compile ../../src/ports/SkFontMgr_android.cpp
ninja: build stopped: subcommand failed.
```

**Comment by tosho** [comment]
> > > If you are going to compile the master branch (not the v1.2.9 zip), then yes, you need to compile Skia first. Please check the steps correctly from the INSTALL.md file, you need the `depot_tools` first (where is the gn tool). Also there are other steps to sync dependencies for skia.
> > 
> > 
> > tosho@T440:~/deps/skia(aseprite-m67)$ gn gen out/Release --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"
> > `Done. Made 43 targets from 26 files in 266ms`
> > tosho@T440:~/deps/skia(aseprite-m67)$ ninja -C out/Release skia
> > ```
> > ninja: Entering directory `out/Release'
> > [64/1210] compile ../../src/ports/SkFontConfigInterface_direct.cpp
> > FAILED: obj/src/ports/fontmgr_fontconfig.SkFontConfigInterface_direct.o 
> > c++ -MMD -MF obj/src/ports/fontmgr_fontconfig.SkFontConfigInterface_direct.o.d -DNDEBUG -DSK_SAMPLES_FOR_X -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_ENABLE_DISCRETE_GPU -DSKIA_IMPLEMENTATION=1 -I../../include/android -I../../include/c -I../../include/codec -I../../include/config -I../../include/core -I../../include/effects -I../../include/encode -I../../include/gpu -I../../include/gpu/gl -I../../include/atlastext -I../../include/pathops -I../../include/ports -I../../include/svg -I../../include/utils -I../../include/utils/mac -I../../include/private -I../../src/c -I../../src/codec -I../../src/core -I../../src/effects -I../../src/fonts -I../../src/image -I../../src/images -I../../src/lazy -I../../src/opts -I../../src/pathops -I../../src/pdf -I../../src/ports -I../../src/sfnt -I../../src/shaders -I../../src/shaders/gradients -I../../src/sksl -I../../src/utils -I../../src/utils/win -I../../src/xml -I../../third_party/gif -I../../src/gpu -fstrict-aliasing -fPIC -w -Wall -Wextra -Winit-self -Wpointer-arith -Wsign-compare -Wvla -Wno-deprecated-declarations -Wno-maybe-uninitialized -Wno-implicit-fallthrough -Wno-unused-parameter -O3 -fdata-sections -ffunction-sections -std=c++11 -fno-exceptions -fno-rtti -c ../../src/ports/SkFontConfigInterface_direct.cpp -o obj/src/ports/fontmgr_fontconfig.SkFontConfigInterface_direct.o
> > In file included from ../../src/ports/SkFontConfigInterface_direct.cpp:13:0:
> > ../../src/ports/SkFontConfigInterface_direct.h:14:10: fatal error: fontconfig/fontconfig.h: No such file or directory
> >  #include <fontconfig/fontconfig.h>
> >           ^~~~~~~~~~~~~~~~~~~~~~~~~
> > compilation terminated.
> > [69/1210] compile ../../src/ports/SkFontMgr_android.cpp
> > ninja: build stopped: subcommand failed.
> > ```
> 
> hey im trying to compile skia and im getting this exact error. have you found a fix for this?

No. Not 1.3 Dev. 
But I compiled the 1.2.9. Source

**Comment by KyleGuthery** [comment]
> > > If you are going to compile the master branch (not the v1.2.9 zip), then yes, you need to compile Skia first. Please check the steps correctly from the INSTALL.md file, you need the `depot_tools` first (where is the gn tool). Also there are other steps to sync dependencies for skia.
> > 
> > 
> > tosho@T440:~/deps/skia(aseprite-m67)$ gn gen out/Release --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"
> > `Done. Made 43 targets from 26 files in 266ms`
> > tosho@T440:~/deps/skia(aseprite-m67)$ ninja -C out/Release skia
> > ```
> > ninja: Entering directory `out/Release'
> > [64/1210] compile ../../src/ports/SkFontConfigInterface_direct.cpp
> > FAILED: obj/src/ports/fontmgr_fontconfig.SkFontConfigInterface_direct.o 
> > c++ -MMD -MF obj/src/ports/fontmgr_fontconfig.SkFontConfigInterface_direct.o.d -DNDEBUG -DSK_SAMPLES_FOR_X -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_ENABLE_DISCRETE_GPU -DSKIA_IMPLEMENTATION=1 -I../../include/android -I../../include/c -I../../include/codec -I../../include/config -I../../include/core -I../../include/effects -I../../include/encode -I../../include/gpu -I../../include/gpu/gl -I../../include/atlastext -I../../include/pathops -I../../include/ports -I../../include/svg -I../../include/utils -I../../include/utils/mac -I../../include/private -I../../src/c -I../../src/codec -I../../src/core -I../../src/effects -I../../src/fonts -I../../src/image -I../../src/images -I../../src/lazy -I../../src/opts -I../../src/pathops -I../../src/pdf -I../../src/ports -I../../src/sfnt -I../../src/shaders -I../../src/shaders/gradients -I../../src/sksl -I../../src/utils -I../../src/utils/win -I../../src/xml -I../../third_party/gif -I../../src/gpu -fstrict-aliasing -fPIC -w -Wall -Wextra -Winit-self -Wpointer-arith -Wsign-compare -Wvla -Wno-deprecated-declarations -Wno-maybe-uninitialized -Wno-implicit-fallthrough -Wno-unused-parameter -O3 -fdata-sections -ffunction-sections -std=c++11 -fno-exceptions -fno-rtti -c ../../src/ports/SkFontConfigInterface_direct.cpp -o obj/src/ports/fontmgr_fontconfig.SkFontConfigInterface_direct.o
> > In file included from ../../src/ports/SkFontConfigInterface_direct.cpp:13:0:
> > ../../src/ports/SkFontConfigInterface_direct.h:14:10: fatal error: fontconfig/fontconfig.h: No such file or directory
> >  #include <fontconfig/fontconfig.h>
> >           ^~~~~~~~~~~~~~~~~~~~~~~~~
> > compilation terminated.
> > [69/1210] compile ../../src/ports/SkFontMgr_android.cpp
> > ninja: build stopped: subcommand failed.
> > ```
> 
> hey im trying to compile skia and im getting this exact error. have you found a fix for this?

I ran into the same issue (on Ubuntu 18.04). It's caused by a missing package. Installing the libfontconfig1-dev package fixed that for me.

Then there was another error because gl/glx.h was missing, and I fixed that by installing libgl1-mesa-dev.

**Comment by dacap** [comment]
I'll add libfontconfig1-dev and libgl1-mesa-dev in the INSTALL.md dependencies for Ubuntu (never had the time to find the exact package names)

**Comment by flamendless** [comment]
I get the same error. Does this mean that aseprite require Skia ?

**Comment by KyleGuthery** [comment]
> I get the same error. Does this mean that aseprite require Skia ?

Yes, as the installation instructions say, "You will need a compiled version of the Skia library."
