### ISSUE TITLE
Won't execute on Linux

### ISSUE THREAD

**Issue by shedya** [aseprite/aseprite#1886]
build/bin/aseprite weighs 162.3 MiB, is listed as a "shared library" in pcmanfm and will not execute: 
![image](https://user-images.githubusercontent.com/17379794/45949644-39175500-c005-11e8-848d-482db5ad0b79.png)
Compiled exactly as per install.md. 

### Aseprite and System version

* Aseprite version: commit a13385a081ff53c47f44237e2e19ca0879034da9
* System: Ubuntu 18.04

**Comment by fanick1** [comment]
you must execute it as **./**aseprite  not **.** aseprite
