### ISSUE TITLE
can't install theme on macos 

### ISSUE THREAD

**Issue by dafong** [aseprite/aseprite#1891]
I am on mac ,I install JMSWRNR's Aseprite Themes follow the instructions, when I select theme,it says
"There is no default font", but I have installed the font "RobotoMono-Bold.ttf ", I am on macos

theme link is [here](https://github.com/jmswrnr/aseprite-themes)

### Aseprite and System version

* Aseprite version: 12.9 , Steam
* System: macOS 10.13.6

**Comment by dacap** [comment]
I think this should be fixed for Aseprite v1.2.10 with this commit 6b7ba57ba2ecbbd0b38bffc7d0ab752bbdce49b4 (this problem might be because the fonts is installed in the user Library/Fonts directory and not in the system, and Aseprite v1.2.9 is not loading the user fonts correctly)

**Comment by dafong** [comment]
thanks, and what the plan of release time of v1.2.10 ?

**Comment by dacap** [comment]
Soon, in the best case, today I might release a beta version [on Steam](https://www.aseprite.org/beta/). Basically the issue that is blocking everything is #1576, but I think it's already in a releasable state for a first version.
