### ISSUE TITLE
Line tool begins to angle at the wrong point of the line

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1894]
Not sure what to title this as. But if you make a completely diagonal line everything is fine.

![image](https://user-images.githubusercontent.com/17066488/46594651-c615e000-cad4-11e8-8c6a-ebceaa47bc75.png)

You know, there's just a bunch of pixels in a line. But if you angle it by even 1 pixel, it does this at the bottom.
![image](https://user-images.githubusercontent.com/17066488/46594663-d928b000-cad4-11e8-9157-8c1c5d5d5322.png)
It gets angled at the first break from starting position. This is a really big deal when trying to make proper lines and I always end up having to move the lines down 1 step to get the correct angle.

![image](https://user-images.githubusercontent.com/17066488/46594705-04ab9a80-cad5-11e8-862f-22affee7ecfe.png)
This is what the first break on the line SHOULD look like.

Aseprite 1.2.10-Beta1-x64
Windows 7

**Comment by dacap** [comment]
This is a known issue and working in this way by-design, check this post:

https://community.aseprite.org/t/straight-line-with-line-tool-or-pencil-tool-is-a-bit-off/1045/2?u=dacap

Anyway I might revert this to make Aseprite works more like other programs work. The commit 88e059669229eea4be8f9c425617cca904d25f4d was made to fix #1395, but I think only a line with some specific steps were fixed (and not all cases).

**Comment by dacap** [comment]
I think I'll restore the old behavior and add an experimental option to keep the old line behavior just in case.
