### ISSUE TITLE
Another compile failure

### ISSUE THREAD

**Issue by NitroCipher** [aseprite/aseprite#1897]
```
FAILED: src/app/CMakeFiles/app-lib.dir/app.cpp.o 
/usr/bin/c++  -DASEPRITE_WITH_WEBP_SUPPORT -DCMARK_STATIC_DEFINE -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_NEWS -DENABLE_SAVE -DENABLE_SCRIPTING -DENABLE_UI -DENABLE_UPDATER -DHAVE_CONFIG_H -DLIBARCHIVE_STATIC -DNDEBUG -DPNG_NO_MMX_CODE -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../src -I../src/observable -Isrc/app -I../laf -Ilaf -I../laf/third_party/stringencoders/src -Ithird_party/freetype2/include -I../third_party/fmt/include -I../third_party/json11 -I../third_party/libarchive/libarchive -I../third_party/tinyexpr -I../third_party/lua -Wall -Wno-switch -O2 -g -DNDEBUG   -std=c++11 -MD -MT src/app/CMakeFiles/app-lib.dir/app.cpp.o -MF src/app/CMakeFiles/app-lib.dir/app.cpp.o.d -o src/app/CMakeFiles/app-lib.dir/app.cpp.o -c ../src/app/app.cpp
c++: internal compiler error: Killed (program cc1plus)
```

**Comment by NitroCipher** [comment]
This is during the final ```ninja aseprite``` part of the installation

**Comment by NitroCipher** [comment]
what more info do you need?

**Comment by riswand** [comment]
Thanks

Pada tanggal Rab, 10 Okt 2018 23.32, Bill Shoener <notifications@github.com>
menulis:

**Comment by dacap** [comment]
Actually as this is an internal compiler error, I cannot do much about it. You can try to free some memory, or restart the computer, and run again the command, but if the problem persists, the only solution could be to use another compiler or other version of the same compiler.

**Comment by NitroCipher** [comment]
> The only solution could be to use another compiler or other version of the same compiler.

I'm limited to a vm with 1GB ram. Any suggestions for how else to compile?

**Comment by NitroCipher** [comment]
can i use cmake instead?

**Comment by NitroCipher** [comment]
I love how the question was never actually answered, it was just ignored for over a year, and closed. :/

**Comment by NitroCipher** [comment]
I've already bought the program on steam at this point, so it doesn't matter anyways. It is just still annoying

**Comment by dacap** [comment]
@NitroCipher sorry about that, I'm closing several compilation-related issues because the instructions have changed a lot in these days, please ask in case that you need some kind of help with the latest instructions.
