### ISSUE TITLE
Option to disable double-clicking to select grid

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1901]
Haven't had much of an issue with this before, but double clicking happens too easily with a tablet and I accidentally select the grid all the time now and it's not something that I use a lot.

Aseprite 1.2.10-beta1
Windows 7

**Comment by dacap** [comment]
Some other users find the double-click hard to execute: https://twitter.com/deepnightfr/status/1049644157722071045

I think the issues is this: it's hard to trigger when one want to execute it, and too easy to trigger when one doesn't want, basically, it has an erratic behavior.

I'm not sure if we need a way to disable the double-click to select a grid cell, or a way to disable it completely in the editor, and create an alternative way to trigger the double-click action (e.g. with a key or an on-screen button)

**Comment by KashouC** [comment]
It's strange. I think I'm getting better at it now but for a long time I had severe issues double clicking in menu's in Aseprite with the pen, it just wouldn't register, but getting the double click to work for the grid selection thing is way too easy (like an entire seconds window almost).

**Comment by KashouC** [comment]
Could you perhaps link the timeout to the OS double click timeout so it's the same timing as opening files and such? Not sure how much of a hassle that is cross platform (I assume it is, usually is).
