### ISSUE TITLE
Request: ability to pin high rez images to the background of pixel art (low rez images)

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [aseprite/aseprite#1904]
This is not a bug but a request. 

I am proposing that images can be pinned to the background as high rez independent of the resolution of the image

Here is a mockup. The image in the foreground that is pixelated is my actual work and is 64 x 64 pixels. The image in the background is just pinned and used as an example I can trace over and is actually around 600 x 600 pixels.. 
![image](https://user-images.githubusercontent.com/36826319/47261081-e1e69200-d495-11e8-9ef1-512dc2953c24.png)

### Aseprite and System version 1.2.10?

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by KashouC** [comment]
Hi there!

The Reference Layer currently implemented should work like what you're looking for.
You can even move and resize the reference layer using the move tool, which is kind of tricky to find on your own. But if you click and drag the bottom right corner of the reference layer you can resize it, but only with the move tool selected.

Hope it helps!

![image](https://user-images.githubusercontent.com/17066488/47261112-1758a300-d4c9-11e8-9480-3973b52841d5.png)

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@KashouC  oh wow that's crazy. I just noticed this after you told me. Add Reference Layer
