### ISSUE TITLE
Cannot Cmake Aseprite MacOS

### ISSUE THREAD

**Issue by Aphrodites1995** [aseprite/aseprite#1906]
Aseprite Latest Version
System: MacOS 10.14

I encountered a problem on running cmake on build:

CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
  The OLD behavior for policy CMP0046 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.13/Modules/Platform/Darwin-Initialize.cmake:125 (message):
  Ignoring CMAKE_OSX_SYSROOT value:

   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk

  because the directory does not exist.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.13/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:34 (project)

CMake Error at CMakeLists.txt:44 (message):
  Your Aseprite repository is incomplete, initialize submodules using:

    git submodule update --init --recursive

-- Configuring incomplete, errors occurred!
See also "/users/john/Downloads/aseprite/build/CMakeFiles/CMakeOutput.log".

This is problematic, and should be fixed. Please tell me how to fix this problem, thank you.

**Comment by dacap** [comment]
As the message says, it looks like you have to update all submodules:

    git submodule update --init --recursive

**Comment by Aphrodites1995** [comment]
Then it still gives the same thing.

**Comment by Aphrodites1995** [comment]
This is all I know. I have all the dependencies, and on my path.

**Comment by dacap** [comment]
Check if you have the `laf/CMakeLists.txt` directory inside the Aseprite cloned folder. If not, I recommend you to download the [latest release of the source code](https://github.com/aseprite/aseprite/releases/download/v1.2.9/Aseprite-v1.2.9-Source.zip), and follow the instructions (INSTALL.md file) of that specific version to compile Aseprite.

**Comment by Aphrodites1995** [comment]
Yes it works. The problem seems to be an empty laf when I download directly the Aseprite files. There is another problem, but I'll open another issue.
