### ISSUE TITLE
Cli exports are missing frame tags

### ISSUE THREAD

**Issue by josh-perry** [aseprite/aseprite#1908]
Exporting through the cli doesn't seem to be outputting frameTags, layers or slices anymore.

I don't know if I'm missing something but I used to be able to run: `aseprite -b wirecutter.aseprite --data wirecutter.json --format json-array` or equivilant and get a json file with frameTags in the meta section.

This still works properly if I export it through the UI but the CLI seems to just omit it.

### Aseprite and System version

* Aseprite version: v1.2.9-x64
* System: Windows

**Comment by dacap** [comment]
Hi @josh-perry, did you try using [`--list-tags`](https://www.aseprite.org/docs/cli/#list-tags) option?

**Comment by josh-perry** [comment]
Ahh, nevermind, it works fine with --list-tags. I guess I changed something in my script and took that out by mistake or something.

Sorry for wasting your time. 👍

**Comment by dacap** [comment]
No problem @josh-perry 👍 glad it continues working 🐱
