### ISSUE TITLE
Compiling skia: getting AssertionError with git-sync-deps and/or SyntaxError missing parentheses

### ISSUE THREAD

**Issue by arvz** [aseprite/aseprite#1910]
My default python versions seems to be python 2.7.6. When I use this on git-sync-deps, I get this: 

> E:\deps\skia\tools>python git-sync-deps Traceback (most recent call last):   
> File "git-sync-deps", line 253, in <module>     
> exit(main(sys.argv[1:]))   
> File "git-sync-deps", line 245, in main     
> git_sync_deps(deps_file_path, argv, verbose)   
> File "git-sync-deps", line 187, in git_sync_deps    
> assert git 
> AssertionError

Then I tried Python 3.6.5 which is what comes with the mozilla-build, and I get this instead:

> E:\deps\skia\tools>E:\mozilla-build\python3\python.exe git-sync-deps
>   File "git-sync-deps", line 209
>     print 'Skipping "%s".' % directory
>                                      ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Skipping "%s".' % directory)?

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows 10

**Comment by timei5** [comment]
J

**Comment by Enosade** [comment]
I am getting an identical error, so this isn't a singular occurrence. Would really appreciate a solution to this.

**Comment by dacap** [comment]
Hi @Enosade, before the v1.2.10-beta2 release a couple of days ago, I tried to compile `aseprite-m71` branch and got the same program, after executing `git-sync-deps --help` I saw that we can specify [the git executable in the GIT_EXECUTABLE environment variable](https://github.com/google/skia/blob/6d546b5cd1b64c85d2ecda468829d8f0028d3f55/tools/git-sync-deps#L14), so don't remember what value I put on GIT_EXECUTABLE, but you can try:
```
set GIT_EXECUTABLE=git.bat
python git-sync-deps
```
Or try the full path to a `set GIT_EXECUTABLE=C:\...fullpath...\git.bat` (I remember that I've used the full path to a `git.bat` file in my file system, but maybe just `git.bat` without path might work)

**Comment by Enosade** [comment]
@dacap 
`C:\Deps>cd skia

C:\Deps\skia>set GIT_EXECUTABLE=C:\Deps\depot_tools\git.bat

C:\Deps\skia>python git-sync-deps
C:\Deps\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe: can't open file 'git-sync-deps': [Errno 2] No such file or directory
C:\Deps\skia>`
Now I am getting this issue, both with `set GIT_EXECUTABLE=git.bat` as well as inputting the full path.

**Comment by dacap** [comment]
Sorry, it's `python tools/git-sync-deps` like in the original INSTALL.md instructions.

**Comment by dacap** [comment]
@Enosade you can put the ninja.exe in any location you prefer on Windows (e.g. I have my own bin directory where I put all the .exe, but then you have to modify the PATH env var to point to that dir, so the easiest way is to put the .exe where it's used)
