### ISSUE TITLE
Palette Preset list wont update after restart

### ISSUE THREAD

**Issue by viniciuscsg** [aseprite/aseprite#1915]
I might be wrong but until recently the only way for new palettes saved on the palettes data folder to appear on the preset list was to save new palettes as .gpl and restart. Palettes saved as png, ase or pal, never appeared on the preset list for me. Recently I had to reinstall aseprite directly from steam, backed up my palette list, saved them all on the right folder and they showed up on the preset list alright. However, new palettes saved directly from within aseprite as gpl on the folder arent showing on preset list at all, regardless of restarting the application. I couldn't find an open issue about it on the list.

Edit: yup, just confirmed that gpl files are not being saved on the steam folder, although they seem to be saved on the saving dialog within aseprite. Weird.

Aseprite 1.2.9-x64, Steam

Windows 10

**Comment by KashouC** [comment]
Are you certain you haven't saved them in C:\Users\<Username>\AppData\Roaming\Aseprite instead of in the steam folder? It worked for me when I saved them into Aseprite\data\palettes in install folder in the steam folder.

**Comment by KashouC** [comment]
Might there be overlapping file names with different extensions?

**Comment by viniciuscsg** [comment]
Oh, so the User Roaming should be the target? I have always done it on the steam folder with no problems, will try ASAP

**Comment by viniciuscsg** [comment]
It worked by saving from explorer, outside aseprite, thanks. Still, there must be some inconsistency here, and devs might be interested. Perhaps also enforcing saving of palettes to the right folder?
