### ISSUE TITLE
Failed to compile Skia

### ISSUE THREAD

**Issue by Delta456** [aseprite/aseprite#1916]
Describe your bug report or feature request here

Followed all instructions from the ```Install.md```

When I write the 2nd last command 

``` gn gen out/Release --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"```

It gives the following error
```

Traceback (most recent call last):
  File "/home/delta/deps/depot_tools/gn.py", line 71, in <module>
    sys.exit(main(sys.argv))
  File "/home/delta/deps/depot_tools/gn.py", line 49, in main
    'gn', 'gn' + gclient_utils.GetExeSuffix())
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

### Aseprite and System version

* Aseprite version: Github master branch last commit from 4 days ago
* System: Elementary OS based on Ubuntu 16.04

**Comment by Delta456** [comment]
Would anyone seek to help?

**Comment by dacap** [comment]
did you download the depot_tools?

**Comment by Delta456** [comment]
Yes, I downloaded the Dependencies.

**Comment by Delta456** [comment]
Could help?

**Comment by flamendless** [comment]
I get similar error when running that command:
```
Traceback (most recent call last):
  File "/home/brbl/Softwares/deps/depot_tools/gn.py", line 15, in <module>
    import gclient_utils
  File "/home/brbl/Softwares/deps/depot_tools/gclient_utils.py", line 271
    except OSError, e:
                  ^
SyntaxError: invalid syntax

```

**Comment by Delta456** [comment]
Tried doing everything again and it worked.

**Comment by flamendless** [comment]
Hmm what python version did you use when running the `gn` command?

**Comment by Delta456** [comment]
I have Ubuntu 16.04 which has Python 2.7 as default.

**Comment by flamendless** [comment]
The default python version in my system is 3+, that's what's causing the issue

**Comment by Delta456** [comment]
I think someone should make an issue about it or open a Pull Request for changes.

**Comment by flamendless** [comment]
The problem is with skia build script (gn). Changing it to be compatible with python3 would take a long time and would break with python2. 

This issue should be closed now

**Comment by Delta456** [comment]
I will try to make it compatible with python 3 and send a PR as soon as possible.

Closing this issue!

**Comment by dacap** [comment]
@Delta456 if you're thinking to add support python 3 support to skia, please contact Skia developers; our branch contains minimal patches for skia (in a perfect world I would like to avoid patching Skia, but that's not possible yet 😢)

**Comment by Delta456** [comment]
You should add to `INSTALL.MD` that you need only Python 2.7 for compiling Skia.

**Comment by flamendless** [comment]
I agree with @Delta456 , Skia doc does not specify or mention that crucial info

**Comment by flamendless** [comment]
@dacap skia does not use the python they provide. It still uses the python the system have.

_Sent from my Liquid Zest 4G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
