### ISSUE TITLE
Aseprite hangs when opening "quick references"

### ISSUE THREAD

**Issue by flamendless** [aseprite/aseprite#1919]
When I click "quick reference" in the toolbar, a browser opens with the link to the quick reference, but the main aseprite window is stuck/hanged. Closing the tab or the browser didn't help either.

* Aseprite version: 1.3-dev
* System: Manjaro v17.1.12 x64 - i3wm - Linux Kernel v4.14

**Comment by dacap** [comment]
I think this could be fixed adding a simple `&` at the end of [this line](https://github.com/aseprite/laf/blob/be9d4a949b80febda46410d32378b4c4cbe4439f/base/launcher.cpp#L85):

This:

      ret = std::system(("xdg-open \"" + file + "\"").c_str());

To:

      ret = std::system(("xdg-open \"" + file + "\" &").c_str());

**Comment by flamendless** [comment]
Finally, I contributed something good :)
