### ISSUE TITLE
Mouse scrolling effects are doubled

### ISSUE THREAD

**Issue by markopolojorgensen** [aseprite/aseprite#1921]
If I scroll the mouse wheel a single 'tick' the thing I am scrolling changes as if I had scrolled two ticks.
* Zoom levels go from 100% to 300% to 500%, etc.
* palette indexing (alt-scroll) goes from idx-1 to idx-3 to idx-5, etc.
* brush size (ctrl-scroll) goes from 1 to 3 to 5, etc.
* scrolling over sliders in pop-up dialogs is also affected

It's not limited to odd numbers, if I pick an even brush size and then ctrl-scroll I get only even numbers.

This is a regression for me: before I switched to the beta, scrolling by a single tick changed things by one.

I should note that I have been playing around a lot with the scripting api. Restarting aseprite does not fix the issue, though, so I'm assuming it's not possible to screw up my installation by being bad at lua :)

### Aseprite and System version

* Aseprite version: v1.2.10-beta2-x64, Steam beta: "beta - Beta version - Preview features"
* System: Linux Ubuntu 16.04 LTS
```
$uname -a
Linux 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dacap** [comment]
Thanks for reporting this @markopolojorgensen. The new beta contains a complete new backend that handles all the keyboard/mouse/display events, so this kind of issues can arise, taking note to fix this ASAP for the next beta.
