### ISSUE TITLE
SKIA_LIBRARY Not Set Compileation Error

### ISSUE THREAD

**Issue by Aphrodites1995** [aseprite/aseprite#1935]
On MacOS 10.14.2 Beta I am compiling Aseprite 1.2.9. I have got all dependencies set up and the cmake step is not working.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SKIA_LIBRARY
    linked by target "she" in directory /Users/john/Downloads/Aseprite-v1.2.9-Source/src/she

This is the error I get when I am running the cmake according to INSTALL.md. Is it so that I must manually change /src/she?

**Comment by dacap** [comment]
After compiling Skia, when you run `cmake` for Aseprite, you've to provide the SKIA_DIR, check the [macOS details](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#macos-details) section from your INSTALL.md file.

**Comment by Aphrodites1995** [comment]
In this case I have compiled Skia directly in $HOME/deps/skia, so SKIA_DIR is correct. Is it that I must link depot_tools?

**Comment by Aphrodites1995** [comment]
I tried editing CmakeLists to set the SKIA_LIBRARY to my Skia home, cmake works now.

**Comment by jameydeorio** [comment]
This should be included in the INSTALL.md OS X section.
