### ISSUE TITLE
CLI -sheet only uses files in folder

### ISSUE THREAD

**Issue by poi33** [aseprite/aseprite#1936]
Using the -sheet from cli uses all files in current folder.
Not the specified files before the argument.

Command: `Aseprite ./example1.png ./example2.png -sheet sheet.png -b `
Will read all files in current folder and try creating a spriteheet out of them.

Expected out:
Just the files given before the -sheet argument. (as mentioned in [docs](https://www.aseprite.org/docs/cli/#sheet))

### Aseprite and System version

* Aseprite version: v1.2.9-x64
* System: Windows 10

**Comment by dacap** [comment]
I think here the problem is that using `example1.png` will load the whole sequence of files (`example2.png`, `example3.png`, `example4.png`, etc.). You try using the `-oneframe` argument to avoid this or `frame-range 0,0`
