### ISSUE TITLE
Symbol Not Found For Architecture x86_64 In "ninja aseprite" Error

### ISSUE THREAD

**Issue by Aphrodites1995** [aseprite/aseprite#1940]
I am compiling a Aseprite 1.2.9 on MacOS 10.14. I encounter this problem in the last subcommand in step "ninja aseprite":

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

There's a lot of these before the error:

  "SkPixmap::getColor(int, int) const", referenced from:
      she::SkiaSurface::getPixel(int, int) const in libshe.a(she.cpp.o)
      she::SkiaSurface::getPixel(int, int) const in libshe.a(skia_display.cpp.o)
      she::SkiaSurface::getPixel(int, int) const in libshe.a(skia_surface.cpp.o)

What do I have to do? I searched the error in issues, and issues 1253 and 1081 came up. I tried git checkout chrome/m53, but that just led to another error. I am using m65 now.

**Comment by Aphrodites1995** [comment]
Is there any solution to this problem?

**Comment by dacap** [comment]
From [INSTALL.md file in v1.2.9](https://github.com/aseprite/aseprite/blob/v1.2.9/INSTALL.md#building-skia-dependency) you need `aseprite-m67` branch from https://github.com/aseprite/skia, anyway, I would recommend you to use the latest version of Aseprite (1.2.10-beta3, or the master branch) and use Skia `aseprite-m71` branch

**Comment by Aphrodites1995** [comment]
Thank you, it works. Though, I would recommend putting a default Skia branch for every Aseprite branch though.
