### ISSUE TITLE
WM_CLASS should be 'aseprite', not 'allegro'

### ISSUE THREAD

**Issue by heyitsmeuralex** [aseprite/aseprite#1942]
Because WM_CLASS is unset on the Aseprite window, it's impossible to reliably find and position Aseprite in window managers such as i3 and awesomewm (e.g. place aseprite at a specific screen position). This is really annoying, and it should be a simple fix in whatever code you have talking to liballegro.

```sh
$ xprop | grep "WM_CLASS"
```

Executing the above and clicking on the aseprite window nets `WM_CLASS(STRING) = "allegro", "Allegro"`. This should be `aseprite` or `Aseprite`.

#846 suggested this but gave a workaround (look for WM_CLASS=allegro instead), but this is unreliable and really bad practice :tada: 

### Aseprite and System version

* Aseprite version: v1.3dev
* System: Arch Linux

**Comment by dacap** [comment]
Hi @heyitsmeuralex. Actually a couple of issues: 1) the WM_CLASS = allegro should not appear anymore (as the Allegro back-end was removed from the master branch, it looks like you are running an old version compiled with allegro), and 2) Anyway I've tested the latest version and it doesn't provide a WM_CLASS.

So I'll try to fix the .desktop file distributed in .deb packages and the WM_CLASS property so all windows are grouped/handled correctly in some window managers.
