### ISSUE TITLE
Line algorithm

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1944]
We have two different issues that we want to solve with a line algorithm:

A. Pixel-perfect line mode (#1395, #1641), and
B. [Straight lines are a bit off](https://community.aseprite.org/t/1045) (#1894)

The first bug is related to the possibility to create straight lines with perfect angles for pixel-art, and the second bug is related to that the new line algorithm doesn't work to make continue lines (which is the most common case to be fixed).

A possible line algorithm that merges both approaches shows some undesirable results too:

![lines](https://user-images.githubusercontent.com/39654/49532926-60f42600-f89c-11e8-80d6-aac33fe916ee.gif)

The bad thing is that when we switches the common algorithm (for continuous lines) to a perfect pixel block lines algorithm, the line is too different.

---

One possible solution would be to use the perfect pixel line algorithm only in some special cases:

1. When the snap angle modifier is pressed: `Shift` key in Line tool, and `Ctrl` modifier when Pencil+`Shift` key is used to draw straight lines
2. When the snap to grid is enabled (which it makes sense to create perfect lines that match the grid tiles)

In other case we'll use the regular algorithm that fits continuous lines as in https://community.aseprite.org/t/1045

**Comment by oceanhahn** [comment]
I'm not sure what I need to do to get the pixel-perfect-blocks mode, Can you explain how this fix works? ^^;
Specifically, I want to activate the algorithm that produces equal incline segments, rather than the half-ended version active by default.
Thanks!
