### ISSUE TITLE
Pixel-perfect mode with the pen is broken in beta3

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1945]
Drawing with the pen with pixel perfect mode on or off functions the same in the 1.2.10-beta3. You get stairway lines no matter what.

![image](https://user-images.githubusercontent.com/17066488/49667768-51234000-fa5c-11e8-93b9-f277371df567.png)

However, the 1.3-dev version I compiled the other day using the h/2 line algorithm works just fine in regards to the pixel-perfect mode.

**Comment by dacap** [comment]
😢oh thanks for reporting this, I'll prepare a fix next week

**Comment by hepari** [comment]
![_2018_12_09_13_41_08_429](https://user-images.githubusercontent.com/10383640/49697506-8e9ce000-fbb8-11e8-900d-d8d061f582be.gif)

This might be related to the issue.
The pen goes batcrap crazy in the pixel perfect mode no matter in which size. Hope the GIF helps!
