### ISSUE TITLE
unsupported chunk type 8199 Error on Linux (Ubuntu 16.04)

### ISSUE THREAD

**Issue by ericoporto** [aseprite/aseprite#1951]
![image](https://user-images.githubusercontent.com/2244442/50033642-8261ba00-ffe0-11e8-961d-1896a03ef38d.png)

I get the error Unsupported chunk type 8199 when loading a .ase file made on Windows Aseprite from Steam.

### Aseprite and System version

![image](https://user-images.githubusercontent.com/2244442/50033595-4af30d80-ffe0-11e8-88cf-f124d8b6e159.png)
![image](https://user-images.githubusercontent.com/2244442/50033808-3a8f6280-ffe1-11e8-84ed-d146e363c900.png)

* Aseprite version: 1.2.9
* System: Ubuntu 16.04 + Steam

### Comment on probable diagnostics

I saw the [commit on docs/ase-file-specs.md](https://github.com/aseprite/aseprite/commit/a4d8fc52bfe949f61038945999cd2a1779ecd67f#diff-c6b066617622385776b5ac74822527b3) so I am unsure if this is some new feature that arrived from the Windows build but not yet the Linux build.

**Comment by dacap** [comment]
It's probable that you have saved a file on Windows with Aseprite v1.2.10-beta4, which creates the chunk 8199 (0x2007, the color profile chunk), and then opened the file with v1.2.9.
