### ISSUE TITLE
Undo Does Not Instantly Enact While Command Is Pressed

### ISSUE THREAD

**Issue by Aphrodites1995** [aseprite/aseprite#1952]
I am on MacOS 10.14 and just compiled Aseprite 1.2.10 Beta 3. I have been drawing random things to pass the time, and realized that when you press Command-Z, if you hold command it wouldn't show the edit. It is not a big problem, but can be annoying sometimes when you think the undo isn't working. This problem seems to be on every compiled Aseprite.

**Comment by KashouC** [comment]
I came to report this. This is a new problem that I just noticed today. Undo has always refreshed the display after each undo step while holding down the hotkey before.

![testgif](https://user-images.githubusercontent.com/17066488/50338464-ae1afd80-0514-11e9-8ede-67b4ce0832d3.gif)

The 1.3dev version I compiled on the 5th of December works as it should.

**Comment by dacap** [comment]
Known issue on the latest beta, already fixed as @KashouC said, I think it was fixed with 53f2b4a121fa0ee1b8023e3515399ae9721ae252
