### ISSUE TITLE
Experimental > Native File Dialog does nothing on Ubuntu Linux

### ISSUE THREAD

**Issue by ericoporto** [aseprite/aseprite#1953]
When I select Native File Dialog I expect the application to use a file opener from my system. It instead opens a file open dialog rendered in aseprite instead of a Gtk3+ Window or something more native to Linux.

### Aseprite and System version

* Aseprite version: 1.2.9
* System: Ubuntu 16.04 .5 LTS + Steam

**Comment by dacap** [comment]
At the moment the gtk+ file selector is disabled because it creates a hard dependency with gtk+ and gdk libraries. A possible solution in the future would be load gtk+ functions dynamically.

**Comment by ericoporto** [comment]
I haven't tested and the commit dates scare me, but [have you seem this project](https://github.com/mlabbe/nativefiledialog) ?

**Comment by ericoporto** [comment]
I [looked](https://github.com/chromium/chromium/blob/master/chrome/browser/ui/libgtkui/select_file_dialog_impl.h) [on](https://github.com/chromium/chromium/blob/master/base/nix/xdg_util.h) [how](https://github.com/chromium/chromium/blob/master/base/nix/OWNERS) [chromium](https://github.com/chromium/chromium/blob/master/chrome/browser/ui/libgtkui/select_file_dialog_impl.cc) did it. But it's too complicated... [Steam](https://github.com/ValveSoftware/steam-for-linux/issues/4003) apparently has the same issue... The easiest way I can think of, but it would still be a lot of work, would be decoupling this in your own lib, and have that built separately and dynamically link that... I didn't knew the difficult of the task.

**Comment by buckle2000** [comment]
Maybe it is possible to use an external command?

**Comment by buckle2000** [comment]
I found a solution some applications use. https://gitlab.gnome.org/GNOME/zenity

**Comment by Anuken** [comment]
Could using the same approach as [tinyfiledialogs](https://github.com/native-toolkit/tinyfiledialogs/blob/master/tinyfiledialogs.c#L4992) be an option? It appears to use `zenity / matedialog / kdialog` for the file chooser - these are run from the command-line and don't require any additional dependencies.

**Comment by ericoporto** [comment]
there is also https://github.com/samhocevar/portable-file-dialogs

**Comment by ericoporto** [comment]
Great work! Thank you!

**Comment by dacap** [comment]
You're welcome @ericoporto! not the best implementation (which would be loading GTK dynamically or something like that), but it's the best we can do right now to support most Linux distributions. It uses the zenity command line utility, there are a couple of issues I'd like to see if I can implemented for zenity:

* https://gitlab.gnome.org/GNOME/zenity/-/issues/13 (so we can get the ID of the window and make the dialog a child of the main window)
* https://gitlab.gnome.org/GNOME/zenity/-/issues/27 (to improve the usability when another filter/file format is selected, the extension should be changed in the filename field)
