### ISSUE TITLE
Overeager "# of Rows/Columns" Input Field Autocompletion in Export Sprite Sheet

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1958]
The text field for the number of rows or columns in the Export Sprite Sheet pane immediately inserts a "1" into itself whenever the last character is deleted or backspaced, making completely replacing values in it awkward and cumbersome. Naturally, the bug is only relevant when Sheet Type is set to "By Columns" or "By Rows."

The problem may be worked-around by selecting the previous value and typing a new one over it, or by leaving one character in the box, inputting part of a new one, then deleting the old character. Neither are particularly elegant.

This problem likely reproduces the now-resolved bug in issue #1632.

Thanks for looking into it! :D

..using ASEprite 1.2.9-x86 on Win10.

**Comment by dacap** [comment]
Also reported on Steam recently: https://steamcommunity.com/app/431730/discussions/0/1639789306557163544/

**Comment by KashouC** [comment]
And on Discord this morning. ^^ Good luck!

**Comment by Gasparoken** [comment]
It seems it was fixed. I was unable to reproduce the error.
