### ISSUE TITLE
Can't build skia with Clang (Windows 10)

### ISSUE THREAD

**Issue by tkmilbaugh** [aseprite/aseprite#1961]
I installed all of the required components, then I get to the part that says:

Finally, if you've downloaded Clang, use this command:
```
set PATH=C:\deps\llvm\bin;%PATH%
gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false target_cpu=""x64"" cc=""clang"" cxx=""clang++"" clang_win=""c:\deps\llvm"""
ninja -C out/Release skia
```

The "gn gen" line generates this error:
```
Traceback (most recent call last):
  File "K:/devl/skia/gn/highest_version_dir.py", line 15, in <module>
    print sorted(filter(regex.match, os.listdir(dirpath)))[-1]
WindowsError: [Error 3] The system cannot find the path specified: 'C:/Program Files (x86)/Windows Kits/10/Include/*.*'
ERROR at //gn/BUILDCONFIG.gn:193:23: Script returned non-zero exit code.
    win_sdk_version = exec_script("//gn/highest_version_dir.py",
                      ^----------
Current dir: K:/devl/skia/out/Release/
Command: K:/devl/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe -- K:/devl/skia/gn/highest_version_dir.py "C:/Program Files (x86)/Windows Kits/10/Include" "[0-9]{2}\.[0-9]\.[0-9]{5}\.[0-9]"
Returned 1.
```
Sure enough, there is no "Includes" directory inside "C:/Program Files (x86)/Windows Kits/10/". I selected all of the Windows 10 options during the installation of VS2017, and all of the C++ options. When I go look at the "Individual components" tab in the installer for VS2017, everything is selected for Windows 10.

### Aseprite and System version
Unknown aseprite version, repository cloned 2018-12-23
Windows 10 Home version 1803

**Comment by Logopher** [comment]
I'm going through the same process, and I don't think I will encounter this problem. I do see the "Include" folder on my system, with VS 2015, 2017, and 2019, and the Windows 10 SDK installed. I suspect the SDK is most relevant here.

**Comment by CiriousJoker** [comment]
Same issue here, but I do have VS 2019 as well as the Windows 10 SDK installed. However, not even the "C:/Program Files (x86)/Windows Kits/10" exists. Also, when i manually download the Windows 10 SDK without the VS Installer (as a standalone basically), the downloaded folder doesn't contain any "Include" folder and only contains "WindowsSDK"...

**Comment by dacap** [comment]
We've [updated the compilation instructions](https://github.com/aseprite/aseprite/blob/master/INSTALL.md) to compile the `master` branch of Aseprite. There are [pre-built binaries of the Skia library available](https://github.com/aseprite/skia/releases).
