### ISSUE TITLE
Recent version of Aseprite crashes after a while (XInitThreads has not been called?)

### ISSUE THREAD

**Issue by paramono** [aseprite/aseprite#1962]
I've successfully built aseprite on LInux from source using the INSTALL.md guide. However, after I use it for a short while, it crashes with one of the following messages:

```
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
aseprite: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
[1]  + 2063 abort (core dumped)  ./aseprite
```

Or:

```
fatal IO error 0 (Success) on X server ":0" 
after 183141 requests (183117 known processed) with 1 events remaining.
terminate called without an active exception
[1]  + 3727 abort (core dumped)  ./aseprite
```

This looks very similar to this issue from a completely unrelated project:
https://stackoverflow.com/questions/31952711/threading-pyqt-crashes-with-unknown-request-in-queue-while-dequeuing

A few times, aseprite just stopped working during some seemingly random moments. I've also noticed that if I switch back and forth between my programs with alt+tab, it crashes significantly faster and in a more predictable manner. Currently, I did not find a guaranteed way to reproduce this problem.

I would like to help fixing this issue, but I am new to aseprite source code and not sure where to begin. I started from here: https://github.com/aseprite/aseprite/tree/master/src/#aseprite-source-code

And I assume it's a level 4 issue, but I am not sure how to proceed from there. How can I help identify the issue and debug it?

### Aseprite and System version

* Aseprite version: v1.3-dev, commit f5c0d667c
* System: Linux Mint 19 Tara

**Comment by RoyBeer** [comment]
Chiming in, having the same issue.

Same commit, Debian GNU/Linux 9.6 (stretch)

**Comment by dacap** [comment]
Can someone check if disabling the native clipboard fix this issue?

<img width="819" alt="screen shot 2018-12-28 at 16 05 41" src="https://user-images.githubusercontent.com/39654/50525502-7f73c880-0aba-11e9-89a5-1ee4541e5e4f.png">

**Comment by RoyBeer** [comment]
@dacap for me, disabling the native clipboard option did not fix the issue.

**Comment by paramono** [comment]
@dacap tried clipboard option, too, but it didn't help. After a minute of drawing with a pencil, got the same error in console:

```
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
aseprite: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
[1]  + 2063 abort (core dumped)  ./aseprite
```

**Comment by RoyBeer** [comment]
@dacap Didn't update, but rather installed from newly-cloned sources and having no crash so far.

**Comment by KernelPainc** [comment]
Fixed for me after updating the submodules

**Comment by paramono** [comment]
Built from the latest master commit (https://github.com/aseprite/aseprite/commit/0c7af381a28c7aaaec8b6b141435cdc06fd2e71f).

So far I am not experiencing any crashes. Thank you!
I am closing the issue.
