### ISSUE TITLE
Export name same as file name by default

### ISSUE THREAD

**Issue by direstatus** [aseprite/aseprite#1964]
This is a small quality of life issue, but I'd like the ability to make it so that when I go to export a project, it always uses the name of the project by default for the exported file.

Currently, if I make a new project, call it "project1.ase" and then go to export it as png, the default file name will be "project1.png."

If I then save project1.ase as project2.ase, and then go to export project2.ase as a png, the default file name will still be "project1.png." Often I don't notice, and accidentally save over the original file.

I think it'd make more sense that the default file name would be "project2.png" to avoid this issue.

Lots of people have probably gotten used to this quirk, but I use so many different programs that make the default export name the same as the current project name that it's hard to remember to check. I often don't notice the issue until I've overwritten several files, and have to go back and re-export a bunch of sprites. So, if we could have an option to decide which way file names are set when exporting, that would be awesome.

**Comment by oceanhahn** [comment]
If there was time, it might be nice to have an option in Preferences or somesuch where we might be able to specify default nomenclature for serial saves or New Sprite From Selection documents, too. :D
