### ISSUE TITLE
Skia fail to compile

### ISSUE THREAD

**Issue by triko88** [aseprite/aseprite#1965]
I was compiling Skia to use the dev version, I found a syntax error
```
$ python tools/git-sync-deps
  File "tools/git-sync-deps", line 209
    print 'Skipping "%s".' % directory
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Skipping "%s".' % directory)?
 
```

After correcting the line by adding parentheses, I encountered a new set of issues.
```
$ python tools/git-sync-deps
Traceback (most recent call last):
  File "tools/git-sync-deps", line 253, in <module>
    exit(main(sys.argv[1:]))
  File "tools/git-sync-deps", line 245, in main
    git_sync_deps(deps_file_path, argv, verbose)
  File "tools/git-sync-deps", line 190, in git_sync_deps
    deps_file = parse_file_to_dict(deps_file_path)
  File "tools/git-sync-deps", line 170, in parse_file_to_dict
    execfile(path, dictionary)
NameError: name 'execfile' is not defined
```
Can anyone help me with this one? I'm not experienced in Python.

### Aseprite and System version

* Aseprite version: 1.2.9 dev
* System: Manjaro Linux (18.0.1)

**Comment by Aphrodites1995** [comment]
I'm pretty sure you have python3, while the Skia you downloaded thinks you're in python 2, or the Skia you got is for python2, so just re-get Skia, and also download then install python again (be sure to grant admin privileges so python would get into PATH, and see what will happen.

**Comment by triko88** [comment]
Thanks, it is working now. I was using python 3.7, after installing python 2, I simply used 
`python2 tools/git-sync-deps`
instead of
`python tools/git-sync-deps`
Now it is working as intended.
I re-downloaded Skia and had the exact issue. I guess it is still using python2 right now.
I'm closing this issue since my problem has been solved.
