### ISSUE TITLE
order in which you press alt+shift as modifier keys matters

### ISSUE THREAD

**Issue by increpare** [aseprite/aseprite#1972]
### Describe your bug report or feature request here:

Have the "Rectangular Marquee" tool selected (with the default "replace selection mode").
Press and hold shift (note now that the "add to selection" option is selected in the toolbar)
Press and hold alt (note that now the "subtract from selection" option is selected)

Now try it the other way :

Have the "Rectangular Marquee" tool selected (with the default "replace selection mode").
Press and hold alt (note that now the color picker is active)
Press and hold shift (note that there's no different, still in color picker mode).

I would have always assumed that order of pressing of modifier keys shouldn't matter...

### Aseprite and System version

* Aseprite version: 1.2.9 (downloaded, IIRC)
* System: macOS 10.14.1 (18B75)

**Comment by dacap** [comment]
Known issue, something to be fixed soon

**Comment by dacap** [comment]
Check this:
https://github.com/aseprite/aseprite/issues/1626#issuecomment-360795100
