### ISSUE TITLE
can't use cmd+blah commands in the save as input text field

### ISSUE THREAD

**Issue by increpare** [aseprite/aseprite#1973]
launch program, create new image or open existing on
go to file -> save as
click on the "save as" text input field and try press cmd+a - note that you don't select all.

Similarly -  cmd+c/v/x for copy/paste/cut don't work.  

As comparison, all these work in the "Save As..." modal dialog in Photoshop, safari and Chrome.

### Aseprite and System version

* Aseprite version: 1.2.9 downloaded from site
* System: macOS 10.14.1 (18B75)

**Comment by dacap** [comment]
I cannot reproduce this issue either. How are you launching/starting Aseprite? Do you have some special keyboard? what Mac hardware are you using? (MacBook, iMac, etc.)

**Comment by increpare** [comment]
> I cannot reproduce this issue either.

spooky shizzle


> How are you launching/starting Aseprite? 

I normally launch it from finder.  Let's try the steam version launched from steam....same behaviour as launching the standalone version.


>Do you have some special keyboard? 

I normally used the ABC-extended keyboard on osx, but this also happens with the German one and the English qwerty layout (I tried, restarting the app in between each attempt).


>what Mac hardware are you using? (MacBook, iMac, etc.)

I have a MacBook Pro (Retina, 13", End 2013).

---

checking  Console.app, I'm reminded that I do hear the error bing when I try to do this, because I see the following in the when I try do cmd+blah commands in the safe-as dialog and filter by "aseprite"

standard	16:36:05.973937 +0100	systemsoundserverd	687: -> Incoming Request : actionID 4096, inClientPID 53677(aseprite), inBehavior 1, customVibeDataProvided 0, loop 0, loopPeriod 0.000000, inFlags 0, inClientCompletionToken 47
standard	16:36:05.975772 +0100	systemsoundserverd	90: token 1033, mActionID 4096, process 53677(aseprite), mClientConnection -524096704, mPlayerSynchronizer 0x0, mPlayFlags->ShouldPlayAudio 1, mPlayFlags->ShouldVibe 0, mAudioFinishedPlaying 0, mVibeFinishedPlaying 0, mIsLoopedSound 0, mClientCompletionToken 47, timeSinceClientRequestedStopInMS 0, elapsedTimeInMS 1

**Comment by dacap** [comment]
Same issue as the other one, I didn't know that it was about the native file dialog, I was able to reproduce it in the native dialog 👍
