### ISSUE TITLE
"About Aseprite" menu option disabled on macos in the "Aseprite" menu.

### ISSUE THREAD

**Issue by increpare** [aseprite/aseprite#1974]
Using the system menu (not the one in aseprite), note that "Help - > About" is enabled and works, but the system-native "Aseprite -> About Aseprite" is disabled

<img width="195" alt="bildschirmfoto 2019-01-07 um 15 45 11" src="https://user-images.githubusercontent.com/465632/50774296-5827b300-1293-11e9-83d2-c6bb14350fb3.png">
<img width="385" alt="bildschirmfoto 2019-01-07 um 15 45 08" src="https://user-images.githubusercontent.com/465632/50774298-58c04980-1293-11e9-97e6-14005708929e.png">

(was very slightly confusing when I was looking up the version number)

(It's also not idiomatic that the other options in this menu are also disabled)

###Aseprite and System version

Aseprite version: 1.2.9 (downloaded, IIRC)
System: macOS 10.14.1 (18B75)

**Comment by dacap** [comment]
I'm trying to reproduce this but I'm not able, do you know in what state the program should be to see the disabled system menu?

**Comment by increpare** [comment]
Oh right, it's working for me now as well.  Huh.  Ok, found a repro:

Open a file.

Note that in the MacOS "Aseprite" menu everything is enabled (ok behaviour).

<img width="236" alt="bildschirmfoto 2019-01-07 um 16 41 34" src="https://user-images.githubusercontent.com/465632/50777204-42b68700-129b-11e9-8501-45241282e4fa.png">

go to save as
Open the MacOS "Aseprite" menu, note that the options are disabled (ok behaviour).

<img width="938" alt="bildschirmfoto 2019-01-07 um 16 41 46" src="https://user-images.githubusercontent.com/465632/50777217-48ac6800-129b-11e9-8acc-427c75335627.png">

click the cancel button (or press esc)

Open the MacOS "Aseprite" menu, note that it's still disabled (bug).

(I notice that all dropdown menus are disabled when the "save as" dialog is open, but only the "Aseprite" one remains disabled after this procedure).

**Comment by dacap** [comment]
Oh if it's related to the native file dialog it can have problems (because the feature is still experimental, it's not working correctly on macOS).

**Comment by tominek** [comment]
For anyone else still encountering this issue. Go to Aseprite -> Settings and check option "Show Aseprite menu bar". This will show the in app menu bar with working menus.
