### ISSUE TITLE
Skia build fails on Mojave

### ISSUE THREAD

**Issue by Briix** [aseprite/aseprite#1981]
Followed the instructions [here](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#skia-on-macos) for building Skia for mac, but ran into the following errors:

```
~/deps/skia aseprite-m71
❯ gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false ski
a_use_system_zlib=false extra_cflags_cc=[\"-frtti\"]"
Done. Made 42 targets from 26 files in 53ms

~/deps/skia aseprite-m71
❯ ninja -C out/Release skia
ninja: Entering directory `out/Release'
[13/1218] compile ../../src/codec/SkJpegUtility.cpp
FAILED: obj/src/codec/jpeg.SkJpegUtility.o
c++ -MMD -MF obj/src/codec/jpeg.SkJpegUtility.o.d -DNDEBUG -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_ENABLE_DISCRETE_GPU -DSKIA_IMPLEMENTATION=1 -DSK_HAS_JPEG_LIBRARY -I../../inc
lude/android -I../../include/c -I../../include/codec -I../../include/config -I../../include/core -I../../include/docs -I../../include/effects -I../../include/encode -I../../include/gpu -I../../include/atl
astext -I../../include/pathops -I../../include/ports -I../../include/svg -I../../include/utils -I../../include/utils/mac -I../../include/private -I../../src/c -I../../src/codec -I../../src/core -I../../sr
c/effects -I../../src/fonts -I../../src/image -I../../src/images -I../../src/lazy -I../../src/opts -I../../src/pathops -I../../src/pdf -I../../src/ports -I../../src/sfnt -I../../src/shaders -I../../src/sh
aders/gradients -I../../src/sksl -I../../src/utils -I../../src/utils/win -I../../src/xml -I../../third_party/gif -I../../src/gpu -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-
sections -Wno-unused-parameter -isystem /Users/simonbrix/deps/skia/third_party/libjpeg-turbo -isystem /Users/simonbrix/deps/skia/third_party/externals/libjpeg-turbo -std=c++14 -fvisibility-inlines-hidden
-fno-exceptions -fno-rtti -frtti -c ../../src/codec/SkJpegUtility.cpp -o obj/src/codec/jpeg.SkJpegUtility.o
../../src/codec/SkJpegUtility.cpp:49:16: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
        return false;
               ^~~~~
../../src/codec/SkJpegUtility.cpp:54:12: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
    return true;
           ^~~~
../../src/codec/SkJpegUtility.cpp:117:12: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
    return false;
           ^~~~~
3 errors generated.
[18/1218] compile ../../src/core/SkBitmapDevice.cpp
ninja: build stopped: subcommand failed.
```

Not sure where to go from here, would greatly appreciate any pointers.

### System version

* System: macOS, 10.14.2, Mojave

**Comment by adennen** [comment]
I have this same issue, I'm running MacOS 10.14.2 with command line tools version "xcode-select version 2354" (should be latest) getting the same error:
`$ ninja -C out/Release skia
ninja: Entering directory `out/Release'
[323/1218] compile ../../src/codec/SkJpegUtility.cpp
FAILED: obj/src/codec/jpeg.SkJpegUtility.o 
c++ -MMD -MF obj/src/codec/jpeg.SkJpegUtility.o.d -DNDEBUG -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_ENABLE_DISCRETE_GPU -DSKIA_IMPLEMENTATION=1 -DSK_HAS_JPEG_LIBRARY -I../../include/android -I../../include/c -I../../include/codec -I../../include/config -I../../include/core -I../../include/docs -I../../include/effects -I../../include/encode -I../../include/gpu -I../../include/atlastext -I../../include/pathops -I../../include/ports -I../../include/svg -I../../include/utils -I../../include/utils/mac -I../../include/private -I../../src/c -I../../src/codec -I../../src/core -I../../src/effects -I../../src/fonts -I../../src/image -I../../src/images -I../../src/lazy -I../../src/opts -I../../src/pathops -I../../src/pdf -I../../src/ports -I../../src/sfnt -I../../src/shaders -I../../src/shaders/gradients -I../../src/sksl -I../../src/utils -I../../src/utils/win -I../../src/xml -I../../third_party/gif -I../../src/gpu -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -Wno-unused-parameter -isystem /Users/arond/deps/skia/third_party/libjpeg-turbo -isystem /Users/arond/deps/skia/third_party/externals/libjpeg-turbo -std=c++14 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -frtti -c ../../src/codec/SkJpegUtility.cpp -o obj/src/codec/jpeg.SkJpegUtility.o
../../src/codec/SkJpegUtility.cpp:49:16: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
        return false;
               ^~~~~
../../src/codec/SkJpegUtility.cpp:54:12: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
    return true;
           ^~~~
../../src/codec/SkJpegUtility.cpp:117:12: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
    return false;
           ^~~~~
3 errors generated.
[324/1218] compile ../../src/codec/SkJpegCodec.cpp
FAILED: obj/src/codec/jpeg.SkJpegCodec.o 
c++ -MMD -MF obj/src/codec/jpeg.SkJpegCodec.o.d -DNDEBUG -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_ENABLE_DISCRETE_GPU -DSKIA_IMPLEMENTATION=1 -DSK_HAS_JPEG_LIBRARY -I../../include/android -I../../include/c -I../../include/codec -I../../include/config -I../../include/core -I../../include/docs -I../../include/effects -I../../include/encode -I../../include/gpu -I../../include/atlastext -I../../include/pathops -I../../include/ports -I../../include/svg -I../../include/utils -I../../include/utils/mac -I../../include/private -I../../src/c -I../../src/codec -I../../src/core -I../../src/effects -I../../src/fonts -I../../src/image -I../../src/images -I../../src/lazy -I../../src/opts -I../../src/pathops -I../../src/pdf -I../../src/ports -I../../src/sfnt -I../../src/shaders -I../../src/shaders/gradients -I../../src/sksl -I../../src/utils -I../../src/utils/win -I../../src/xml -I../../third_party/gif -I../../src/gpu -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -Wno-unused-parameter -isystem /Users/arond/deps/skia/third_party/libjpeg-turbo -isystem /Users/arond/deps/skia/third_party/externals/libjpeg-turbo -std=c++14 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -frtti -c ../../src/codec/SkJpegCodec.cpp -o obj/src/codec/jpeg.SkJpegCodec.o
../../src/codec/SkJpegCodec.cpp:224:13: error: no matching function for call to 'jpeg_read_header'
    switch (jpeg_read_header(dinfo, true)) {
            ^~~~~~~~~~~~~~~~
/usr/local/include/jpeglib.h:1039:13: note: candidate function not viable: no known conversion from 'bool' to 'boolean' for 2nd argument
EXTERN(int) jpeg_read_header JPP((j_decompress_ptr cinfo,
            ^
../../src/codec/SkJpegCodec.cpp:315:58: error: use of undeclared identifier 'JCS_RGB565'; did you mean 'JCS_RGB'?
    const size_t colorBytes = (dinfo->out_color_space == JCS_RGB565) ? 2 :
                                                         ^~~~~~~~~~
                                                         JCS_RGB
/usr/local/include/jpeglib.h:223:2: note: 'JCS_RGB' declared here
        JCS_RGB,                /* red/green/blue, standard RGB (sRGB) */
        ^
../../src/codec/SkJpegCodec.cpp:406:53: error: use of undeclared identifier 'JCS_EXT_RGBA'; did you mean 'JCS_BG_RGB'?
            fDecoderMgr->dinfo()->out_color_space = JCS_EXT_RGBA;
                                                    ^~~~~~~~~~~~
                                                    JCS_BG_RGB
/usr/local/include/jpeglib.h:227:2: note: 'JCS_BG_RGB' declared here
        JCS_BG_RGB,             /* big gamut red/green/blue, bg-sRGB */
        ^
../../src/codec/SkJpegCodec.cpp:412:57: error: use of undeclared identifier 'JCS_EXT_RGBA'; did you mean 'JCS_BG_RGB'?
                fDecoderMgr->dinfo()->out_color_space = JCS_EXT_RGBA;
                                                        ^~~~~~~~~~~~
                                                        JCS_BG_RGB
/usr/local/include/jpeglib.h:227:2: note: 'JCS_BG_RGB' declared here
        JCS_BG_RGB,             /* big gamut red/green/blue, bg-sRGB */
        ^
../../src/codec/SkJpegCodec.cpp:414:57: error: use of undeclared identifier 'JCS_EXT_BGRA'
                fDecoderMgr->dinfo()->out_color_space = JCS_EXT_BGRA;
                                                        ^
../../src/codec/SkJpegCodec.cpp:419:57: error: use of undeclared identifier 'JCS_EXT_RGBA'; did you mean 'JCS_BG_RGB'?
                fDecoderMgr->dinfo()->out_color_space = JCS_EXT_RGBA;
                                                        ^~~~~~~~~~~~
                                                        JCS_BG_RGB
/usr/local/include/jpeglib.h:227:2: note: 'JCS_BG_RGB' declared here
        JCS_BG_RGB,             /* big gamut red/green/blue, bg-sRGB */
        ^
../../src/codec/SkJpegCodec.cpp:422:57: error: use of undeclared identifier 'JCS_RGB565'; did you mean 'JCS_RGB'?
                fDecoderMgr->dinfo()->out_color_space = JCS_RGB565;
                                                        ^~~~~~~~~~
                                                        JCS_RGB
/usr/local/include/jpeglib.h:223:2: note: 'JCS_RGB' declared here
        JCS_RGB,                /* red/green/blue, standard RGB (sRGB) */
        ^
../../src/codec/SkJpegCodec.cpp:431:57: error: use of undeclared identifier 'JCS_EXT_RGBA'; did you mean 'JCS_BG_RGB'?
                fDecoderMgr->dinfo()->out_color_space = JCS_EXT_RGBA;
                                                        ^~~~~~~~~~~~
                                                        JCS_BG_RGB
/usr/local/include/jpeglib.h:227:2: note: 'JCS_BG_RGB' declared here
        JCS_BG_RGB,             /* big gamut red/green/blue, bg-sRGB */
        ^
../../src/codec/SkJpegCodec.cpp:438:53: error: use of undeclared identifier 'JCS_EXT_RGBA'; did you mean 'JCS_BG_RGB'?
            fDecoderMgr->dinfo()->out_color_space = JCS_EXT_RGBA;
                                                    ^~~~~~~~~~~~
                                                    JCS_BG_RGB
/usr/local/include/jpeglib.h:227:2: note: 'JCS_BG_RGB' declared here
        JCS_BG_RGB,             /* big gamut red/green/blue, bg-sRGB */
        ^
../../src/codec/SkJpegCodec.cpp:714:9: error: use of undeclared identifier 'jpeg_crop_scanline'
        jpeg_crop_scanline(fDecoderMgr->dinfo(), &startX, &width);
        ^
../../src/codec/SkJpegCodec.cpp:769:32: error: use of undeclared identifier 'jpeg_skip_scanlines'
    return (uint32_t) count == jpeg_skip_scanlines(fDecoderMgr->dinfo(), count);
                               ^
../../src/codec/SkJpegCodec.cpp:987:27: error: no matching function for call to 'jpeg_read_header'
    if (JPEG_HEADER_OK != jpeg_read_header(dinfo, true)) {
                          ^~~~~~~~~~~~~~~~
/usr/local/include/jpeglib.h:1039:13: note: candidate function not viable: no known conversion from 'bool' to 'boolean' for 2nd argument
EXTERN(int) jpeg_read_header JPP((j_decompress_ptr cinfo,
            ^
12 errors generated.`

**Comment by adennen** [comment]
I have this same issue, I'm running MacOS 10.14.2 with command line tools version "xcode-select version 2354" (latest release) getting the same error compiling SkJpegUtility.cpp (also errors with SkJpegCodec.cpp, SkJPEGWriteUtility.cpp, SkJpegEncoder.cpp):
```shell
$ ninja -C out/Release skia
ninja: Entering directory `out/Release'
[323/1218] compile ../../src/codec/SkJpegUtility.cpp
FAILED: obj/src/codec/jpeg.SkJpegUtility.o 
c++ -MMD -MF obj/src/codec/jpeg.SkJpegUtility.o.d -DNDEBUG -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_ENABLE_DISCRETE_GPU -DSKIA_IMPLEMENTATION=1 -DSK_HAS_JPEG_LIBRARY -I../../include/android -I../../include/c -I../../include/codec -I../../include/config -I../../include/core -I../../include/docs -I../../include/effects -I../../include/encode -I../../include/gpu -I../../include/atlastext -I../../include/pathops -I../../include/ports -I../../include/svg -I../../include/utils -I../../include/utils/mac -I../../include/private -I../../src/c -I../../src/codec -I../../src/core -I../../src/effects -I../../src/fonts -I../../src/image -I../../src/images -I../../src/lazy -I../../src/opts -I../../src/pathops -I../../src/pdf -I../../src/ports -I../../src/sfnt -I../../src/shaders -I../../src/shaders/gradients -I../../src/sksl -I../../src/utils -I../../src/utils/win -I../../src/xml -I../../third_party/gif -I../../src/gpu -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -Wno-unused-parameter -isystem /Users/arond/deps/skia/third_party/libjpeg-turbo -isystem /Users/arond/deps/skia/third_party/externals/libjpeg-turbo -std=c++14 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -frtti -c ../../src/codec/SkJpegUtility.cpp -o obj/src/codec/jpeg.SkJpegUtility.o
../../src/codec/SkJpegUtility.cpp:49:16: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
        return false;
               ^~~~~
../../src/codec/SkJpegUtility.cpp:54:12: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
    return true;
           ^~~~
../../src/codec/SkJpegUtility.cpp:117:12: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
    return false;
           ^~~~~
3 errors generated.
```

**Comment by roman01la** [comment]
Same issue on macOS 10.13.6

**Comment by dacap** [comment]
I wasn't able to reproduce the issue yet, here macOS 10.14.2, and `xcode-select -v` = 2354

**Comment by yeepZhang** [comment]
> I have this same issue, I'm running MacOS 10.14.2 with command line tools version "xcode-select version 2354" (latest release) getting the same error compiling SkJpegUtility.cpp (also errors with SkJpegCodec.cpp, SkJPEGWriteUtility.cpp, SkJpegEncoder.cpp):
> 
> ```shell
> $ ninja -C out/Release skia
> ninja: Entering directory `out/Release'
> [323/1218] compile ../../src/codec/SkJpegUtility.cpp
> FAILED: obj/src/codec/jpeg.SkJpegUtility.o 
> c++ -MMD -MF obj/src/codec/jpeg.SkJpegUtility.o.d -DNDEBUG -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_ENABLE_DISCRETE_GPU -DSKIA_IMPLEMENTATION=1 -DSK_HAS_JPEG_LIBRARY -I../../include/android -I../../include/c -I../../include/codec -I../../include/config -I../../include/core -I../../include/docs -I../../include/effects -I../../include/encode -I../../include/gpu -I../../include/atlastext -I../../include/pathops -I../../include/ports -I../../include/svg -I../../include/utils -I../../include/utils/mac -I../../include/private -I../../src/c -I../../src/codec -I../../src/core -I../../src/effects -I../../src/fonts -I../../src/image -I../../src/images -I../../src/lazy -I../../src/opts -I../../src/pathops -I../../src/pdf -I../../src/ports -I../../src/sfnt -I../../src/shaders -I../../src/shaders/gradients -I../../src/sksl -I../../src/utils -I../../src/utils/win -I../../src/xml -I../../third_party/gif -I../../src/gpu -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -Wno-unused-parameter -isystem /Users/arond/deps/skia/third_party/libjpeg-turbo -isystem /Users/arond/deps/skia/third_party/externals/libjpeg-turbo -std=c++14 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -frtti -c ../../src/codec/SkJpegUtility.cpp -o obj/src/codec/jpeg.SkJpegUtility.o
> ../../src/codec/SkJpegUtility.cpp:49:16: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
>         return false;
>                ^~~~~
> ../../src/codec/SkJpegUtility.cpp:54:12: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
>     return true;
>            ^~~~
> ../../src/codec/SkJpegUtility.cpp:117:12: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
>     return false;
>            ^~~~~
> 3 errors generated.
> ```

 have the same issue . macOS 10.14.3 and xcode-select -v = 2354

**Comment by yeepZhang** [comment]
> Excluding libjpeg-turbo from the build seemed to help

thanks, i fixed this problem by editing this line 
 ` skia_use_libjpeg_turbo = false`
in **BUILD.gn**

**Comment by dacap** [comment]
@yeepZhang I'll add that option in the INSTALL.md when `gn` is executed. (Maybe this issue might appear if libturbo is installed in the system, but I'm not sure.)

**Comment by dacap** [comment]
Oh I see that `skia_use_system_libjpeg_turbo=false` is already there, so not sure why `skia_use_libjpeg_turbo=false` is needed.

**Comment by adennen** [comment]
> Oh I see that `skia_use_system_libjpeg_turbo=false` is already there, so not sure why `skia_use_libjpeg_turbo=false` is needed.

I just tested replacing `skia_use_system_libjpeg_turbo=false` with `skia_use_libjpeg_turbo=false` in the gn gen build command and it seems to fix the build problem for me, they appear to be two different build options

**Comment by haxpor** [comment]
For me I have to use @adennen 's solution and also disable webp via `skia_use_libwebp=false` due to I cannot get pass the following error at the very last step

```
Undefined symbols for architecture x86_64:
  "is_orientation_marker(unsigned char const*, unsigned long, SkEncodedOrigin*)", referenced from:
      SkWebpCodec::MakeFromStream(std::__1::unique_ptr<SkStream, std::__1::default_delete<SkStream> >, SkCodec::Result*) in libskia.a(webp.SkWebpCodec.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
I'm able to build it completely now. Thanks for author's hard work, and workaround solutions suggesed here.

Will we miss anything from disabling webp option although I'm not aware of webp export?

**Comment by pablinos** [comment]
Changing the option to `gn` like @adennen mentions, fixed the build for me too!

**Comment by Hrithvik-Alex** [comment]
changing `skia_use_system_libjpeg_turbo=false` to `skia_use_libjpeg_turbo = false` worked for me as well
