### ISSUE TITLE
Extrude Tileset option

### ISSUE THREAD

**Issue by lrasomattos** [aseprite/aseprite#1982]
Hi! I just got notified that Extrude Sprite Sheet option (for bleeding sprites) was added like asked in:
#1890 

Unfortunately it still doesn't cover the case for editing and making Tile Sheets / Tilesets. So here I would like to request that feature, as it would for sure be of great value for me and many people who use Aseprite for creating tile sheets.

I imagine an option would be cool, on export or save as, to extrude, one or more pixels "per tile"/"per grid", not only "per sprite".

**Comment by dacap** [comment]
Hi @lrasomattos, so instead of extruding each frame, we should extrude each grid tile, right? Sounds like a nice option. I think it can be useful to combine with other option (e.g. adding padding to grid tiles, etc.).

With this option I guess that each grid tile and each frame of the animation counts like a different item to extrude in the final sprite sheet.

**Comment by lrasomattos** [comment]
Yes!!

Remembering that both extrudes/bleed, in between tiles AND in the margins would be really important for seamless tiles.

Also I believe it's much better as "export feature" instead of an "edit feature", but could work as both. Unless you can de-extrude as well, the main idea is to be able to work on tilesets and easily export them extruded, not to keep them extruded which makes it much harder to edit.

About how it would work with animations, I guess what you said is ok. I imagine people won't be making animations when working with tiles, I don't see how it could be useful now... Or if they did, might prefer each frame in a different file.. (Like using one .ase file for many tilesets).

Also, I don't know how you handle this normally, but if the preference on how to export the extruded files could be saved per file it would be perfect!

By the way, thanks for considering!
