### ISSUE TITLE
What is going on with the jumble tool?

### ISSUE THREAD

**Issue by tiskolin** [aseprite/aseprite#1985]
The jumble tool isn't working like it used to. It seems to jumble _and_ blur at the same time. Is this intentional? I miss the old jumble tool.

### Aseprite and System version

* Aseprite version: v1.2.9, Steam
* System: Linux, 18.04.1 LTS, Ubuntu

**Comment by tiskolin** [comment]
Figured out the problem. Put the "opacity" parameter of the jumble tool to its maximum, 255. This removes all blurring!

**Comment by dacap** [comment]
Glad you figured out, at the moment this behavior is intentional as you saw when the opacity is < 255.
