### ISSUE TITLE
Split layers not working

### ISSUE THREAD

**Issue by snarlynarwhal** [aseprite/aseprite#1986]
[Split layers](https://www.aseprite.org/docs/cli/#split-layers) not working. It only exports one layer.

### Aseprite and System version

* Aseprite version: v1.2.9 x64 Steam
* System: Windows

**Comment by dacap** [comment]
Hi @snarlynarwhal, are you using `--split-layers` with `--save-as`? or with `--sheet`? Could you please copy the exact command line that you are using?

**Comment by snarlynarwhal** [comment]
I went back to try a again to re-confirm and it looks like it **does** work, but only on visible layers. I think this makes complete sense, but should be mentioned in the documentation. I assumed it did all layers irregardless and did not think twice about this.

**Comment by dacap** [comment]
I'll add something about it in the docs, also, if I remember correctly, I think that you can combine `--split-layers` with [`-all-layers`](https://www.aseprite.org/docs/cli/#all-layers) in case that you want to export all layers.

**Comment by snarlynarwhal** [comment]
Okay awesome, I'll try that out too. Thanks for the help David!
