### ISSUE TITLE
Select several tiles with double-click + dragging mouse

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1988]
Feature requested via email:

> You know how double clicking while using the selection tool selects the whole tile you clicked on? It reminded me of the way double clicking on a word selects the whole world. But after double clicking to select a word, you can drag to expand your selection word by word (try it in your browser!). 
It would be awesome if after double clicking to select a tile, you could drag the cursor around to select other whole tiles. So if you wanted to select a row of tiles, you double click a tile, hold the mouse button, and then drag it over the tiles you want to select.

**Comment by lawrence-laz** [comment]
Almost made a duplicate issue. I also made some visuals so I'll just leave them here in case someone want to visualize what is being requested:

Here I double-click and drag without releasing the single click, I expect all four squares be selected perfectly based on my mouse movement.
![2019-05-15_22-23-02](https://user-images.githubusercontent.com/8823448/57803025-0c64a900-7760-11e9-9c7b-3c666233ad91.gif)

This is sort of how it works with text selection.
![2019-05-15_22-25-48](https://user-images.githubusercontent.com/8823448/57803169-6ebda980-7760-11e9-8a3d-14edc75b633b.gif)

**Comment by dacap** [comment]
This will be available in the next release v1.2.17

**Comment by lawrence-laz** [comment]
@dacap would it be difficult to port this feature to slice tool as well?
