### ISSUE TITLE
Program Title Bar Version Incorrect

### ISSUE THREAD

**Issue by Shrubhog** [aseprite/aseprite#1991]
I have freshly compiled my own binaries for aseprite, after a bit of trouble with Ninja guzzling every core on my CPU possible, and now the title bar is wrong.

My complaint is purely aesthetic, and not really important, but it does bug me a bit. I am sure I installed 1.2.9, but the title bar says "Aseprite v.1.3-dev".

On the other hand, it could be intentional and you are rounding off the version number.

### Aseprite and System version

* Aseprite version: v.1.2.9, compiled from source
* System: Windows 10

**Comment by KashouC** [comment]
If you pulled the master branch, 1.3-dev is correct. I guess it's because it's the in development version of 1.3 or something? I don't know the logic lol. 

You have to go into the 1.2.9 tag to get that version I'd assume.

**Comment by Shrubhog** [comment]
I hope I remember correctly. I am (moderately) sure that I took v.1.2.9 from the "Releases: tab.

**Comment by KashouC** [comment]
Mm well in that case I dunno. ^^ Maybe it shows 1.3 anyway, never tried it.

**Comment by dacap** [comment]
Compiled versions should always have `-dev` suffix to avoid confusion when we give support. So if the title bar says `-dev`, I have to ask for the commit number, if it says `v1.2.9` I know that I can test the issue with my copy of `v1.2.9`.

**Comment by Shrubhog** [comment]
Okay, thank you!
