### ISSUE TITLE
Ugee tablet pen tip is locked to the Eraser tool.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#2000]
For some reason, input from the nib of this Ugee M708 pen tablet is locked to the Eraser tool. Even if a different tool is selected (by hotkey or cursor click), ASEprite immediately switches the tool back to the Eraser at the beginning of the first stroke in the editor Workspace.

Is there any way to reassign the default tools for tablet inputs? It would not have to be sophisticated-- being able to rebind whatever input is set to the Eraser tool to the Pencil tool instead would do the trick, probably.

Thanks for looking into it! :D

..using ASEprite 1.2.9 on Win10.

**Comment by oceanhahn** [comment]
Or, actually, failing that kind of solution, are there any quick workarounds, maybe?
If I knew what connected the pen tablet input to the Eraser tool (or any tool, I suppose), I might be able to fix it locally.

Thanks again! :D

**Comment by dacap** [comment]
Hi @oceanhahn! You could give a [try disabling the wintab dll](https://www.aseprite.org/docs/wintab/), just in case that the Ugee driver is a little buggy or not working properly.

**Comment by dacap** [comment]
I'm closing this issue because this [looks fixed](https://github.com/aseprite/aseprite/issues/2417#issuecomment-636370591).
