### ISSUE TITLE
Add support extra pixel connectivity for Paint Bucket tool

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#2009]
We should be able to use [8-connected](https://en.wikipedia.org/wiki/Pixel_connectivity#8-connected) pixels with the paint bucket tool, useful to recoloring outlines.

Requested here: https://steamcommunity.com/app/431730/discussions/1/1776010325128300149/

**Comment by rscotchmer** [comment]
Hi!  I'd like to work on this if that's alright!

**Comment by dacap** [comment]
Hi @rscotchmer, in case you want to make a contribution, please check the [CLA signing process](https://github.com/aseprite/opensource/blob/master/sign-cla.md#sign-the-cla) first.

About this specific issue, my idea is to have a button set (*) with a couple of buttons in this menu:

<img width="270" alt="Screen Shot 2019-03-16 at 11 35 53" src="https://user-images.githubusercontent.com/39654/54476753-bca94600-47df-11e9-84ad-cfb16848f6c1.png">

to switch between both options (4-connected pixels, 8-connected pixels). 

(*) The button set must be something similar to the ones in the brush options menu:

<img width="278" alt="Screen Shot 2019-03-16 at 11 37 38" src="https://user-images.githubusercontent.com/39654/54476771-f2e6c580-47df-11e9-82df-9b17f9ecf6fb.png">

but it can have a couple of icons to show the connection of pixels (+ tooltips).

**Comment by dacap** [comment]
Closed with #2038 (a08cfa9e13f21fb2f9b1b1a20e874c2307168403)

**Comment by dacap** [comment]
![image](https://user-images.githubusercontent.com/39654/56938335-ad543280-6ad7-11e9-8aa0-d086ef6a70e9.png)
