### ISSUE TITLE
Create a C library to load .aseprite files

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#2015]
We could create a C library (or C++ library + C wrapper, header-only maybe?) to load (and save?) `.aseprite` files (similar to the [stb libraries](https://github.com/nothings/stb/blob/master/stb_image.h)).

Pros:
* Easy to use by developers that want to load `.aseprite` files from the games or third-party tools

Cons:
* We should maintain two libraries to load/save files 😢 

A possible solution would be to create a C wrapper (`.dll`) to wrap the `dio` module (#379)

**Comment by rickyhan** [comment]
There is a Rust crate for the file format: https://github.com/rickyhan/ase-rs

**Comment by louisgjohnson** [comment]
@dacap https://github.com/RandyGaul/cute_headers/blob/master/cute_aseprite.h

**Comment by dacap** [comment]
Hi @louisgjohnson, yes we've seen that library recently (RTed from the Aseprite account). I'm closing this issue as I think this is already solved by other users.
