### ISSUE TITLE
Can't build on windows

### ISSUE THREAD

**Issue by Portrucci** [aseprite/aseprite#2017]
basically everything works great until I reach the final step of using ninja to build aseprite.
then, I get this:

[386/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/krb5.c.obj
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
[387/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/strequal.c.obj
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
[389/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/security.c.obj
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
[390/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/krb4.c.obj
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
[391/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/easy.c.obj
FAILED: third_party/curl/lib/CMakeFiles/libcurl.dir/easy.c.obj
C:\PROGRA~1\HASKEL~1\847A5C~1.3\mingw\bin\cc.exe -DALLEGRO4_WITH_EXTRA_CURSORS -DALLEGRO4_WITH_RESIZE_PATCH -DALLEGRO_STATICLINK -DBUILDING_LIBCURL -DCMARK_STATIC_DEFINE -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_ALLEG4_BACKEND -DWINVER=0x0A00 -D_UNICODE -D_USRDLL -D_WIN32_WINNT=0x0501 -D_WIN32_WINNT=0x0A00 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/loadpng -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../src/allegro/include -Iinclude -I../third_party/. -Ithird_party/curl/include/curl -Ithird_party/curl/lib/../include -I../third_party/curl/lib/.. -I../third_party/curl/lib/../include -Ithird_party/curl/lib/.. -I../third_party/curl/lib -Ithird_party/curl/lib -O2 -g -DNDEBUG -MD -MT third_party/curl/lib/CMakeFiles/libcurl.dir/easy.c.obj -MF third_party\curl\lib\CMakeFiles\libcurl.dir\easy.c.obj.d -o third_party/curl/lib/CMakeFiles/libcurl.dir/easy.c.obj   -c ../third_party/curl/lib/easy.c
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
In file included from ../third_party/curl/lib/easy.c:82:0:
../third_party/curl/lib/select.h:59:0: warning: "POLLIN" redefined
 #define POLLIN      0x01

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/easy.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1144:0: note: this is the location of the previous definition
 #define POLLIN    (POLLRDNORM | POLLRDBAND)

In file included from ../third_party/curl/lib/easy.c:82:0:
../third_party/curl/lib/select.h:60:0: warning: "POLLPRI" redefined
 #define POLLPRI     0x02

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/easy.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1145:0: note: this is the location of the previous definition
 #define POLLPRI    0x0400

In file included from ../third_party/curl/lib/easy.c:82:0:
../third_party/curl/lib/select.h:61:0: warning: "POLLOUT" redefined
 #define POLLOUT     0x04

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/easy.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1148:0: note: this is the location of the previous definition
 #define POLLOUT   (POLLWRNORM)

In file included from ../third_party/curl/lib/easy.c:82:0:
../third_party/curl/lib/select.h:62:0: warning: "POLLERR" redefined
 #define POLLERR     0x08

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/easy.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1151:0: note: this is the location of the previous definition
 #define POLLERR    0x0001

In file included from ../third_party/curl/lib/easy.c:82:0:
../third_party/curl/lib/select.h:63:0: warning: "POLLHUP" redefined
 #define POLLHUP     0x10

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/easy.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1152:0: note: this is the location of the previous definition
 #define POLLHUP    0x0002

In file included from ../third_party/curl/lib/easy.c:82:0:
../third_party/curl/lib/select.h:64:0: warning: "POLLNVAL" redefined
 #define POLLNVAL    0x20

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/easy.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1153:0: note: this is the location of the previous definition
 #define POLLNVAL   0x0004

In file included from ../third_party/curl/lib/easy.c:82:0:
../third_party/curl/lib/select.h:66:8: error: redefinition of 'struct pollfd'
 struct pollfd
        ^~~~~~
In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/easy.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1155:16: note: originally defined here
 typedef struct pollfd {
                ^~~~~~
[392/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/transfer.c.obj
FAILED: third_party/curl/lib/CMakeFiles/libcurl.dir/transfer.c.obj
C:\PROGRA~1\HASKEL~1\847A5C~1.3\mingw\bin\cc.exe -DALLEGRO4_WITH_EXTRA_CURSORS -DALLEGRO4_WITH_RESIZE_PATCH -DALLEGRO_STATICLINK -DBUILDING_LIBCURL -DCMARK_STATIC_DEFINE -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -DUNICODE -DUSE_ALLEG4_BACKEND -DWINVER=0x0A00 -D_UNICODE -D_USRDLL -D_WIN32_WINNT=0x0501 -D_WIN32_WINNT=0x0A00 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -I../third_party/loadpng -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../src/allegro/include -Iinclude -I../third_party/. -Ithird_party/curl/include/curl -Ithird_party/curl/lib/../include -I../third_party/curl/lib/.. -I../third_party/curl/lib/../include -Ithird_party/curl/lib/.. -I../third_party/curl/lib -Ithird_party/curl/lib -O2 -g -DNDEBUG -MD -MT third_party/curl/lib/CMakeFiles/libcurl.dir/transfer.c.obj -MF third_party\curl\lib\CMakeFiles\libcurl.dir\transfer.c.obj.d -o third_party/curl/lib/CMakeFiles/libcurl.dir/transfer.c.obj   -c ../third_party/curl/lib/transfer.c
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
In file included from ../third_party/curl/lib/transfer.c:102:0:
../third_party/curl/lib/select.h:59:0: warning: "POLLIN" redefined
 #define POLLIN      0x01

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/transfer.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1144:0: note: this is the location of the previous definition
 #define POLLIN    (POLLRDNORM | POLLRDBAND)

In file included from ../third_party/curl/lib/transfer.c:102:0:
../third_party/curl/lib/select.h:60:0: warning: "POLLPRI" redefined
 #define POLLPRI     0x02

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/transfer.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1145:0: note: this is the location of the previous definition
 #define POLLPRI    0x0400

In file included from ../third_party/curl/lib/transfer.c:102:0:
../third_party/curl/lib/select.h:61:0: warning: "POLLOUT" redefined
 #define POLLOUT     0x04

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/transfer.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1148:0: note: this is the location of the previous definition
 #define POLLOUT   (POLLWRNORM)

In file included from ../third_party/curl/lib/transfer.c:102:0:
../third_party/curl/lib/select.h:62:0: warning: "POLLERR" redefined
 #define POLLERR     0x08

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/transfer.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1151:0: note: this is the location of the previous definition
 #define POLLERR    0x0001

In file included from ../third_party/curl/lib/transfer.c:102:0:
../third_party/curl/lib/select.h:63:0: warning: "POLLHUP" redefined
 #define POLLHUP     0x10

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/transfer.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1152:0: note: this is the location of the previous definition
 #define POLLHUP    0x0002

In file included from ../third_party/curl/lib/transfer.c:102:0:
../third_party/curl/lib/select.h:64:0: warning: "POLLNVAL" redefined
 #define POLLNVAL    0x20

In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/transfer.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1153:0: note: this is the location of the previous definition
 #define POLLNVAL   0x0004

In file included from ../third_party/curl/lib/transfer.c:102:0:
../third_party/curl/lib/select.h:66:8: error: redefinition of 'struct pollfd'
 struct pollfd
        ^~~~~~
In file included from ../third_party/curl/lib/setup.h:226:0,
                 from ../third_party/curl/lib/transfer.c:23:
C:/PROGRA~1/HASKEL~1/847A5C~1.3/mingw/x86_64-w64-mingw32/include/winsock2.h:1155:16: note: originally defined here
 typedef struct pollfd {
                ^~~~~~
[395/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/wildcard.c.obj
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
[396/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/curl_fnmatch.c.obj
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
[397/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/fileinfo.c.obj
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
[398/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/memdebug.c.obj
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
[399/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/llist.c.obj
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
[400/1556] Building C object third_party/curl/lib/CMakeFiles/libcurl.dir/ftplistparser.c.obj
<command-line>:0:0: warning: "_WIN32_WINNT" redefined
<command-line>:0:0: note: this is the location of the previous definition
ninja: build stopped: subcommand failed.

### Aseprite and System version

* Aseprite version: 1.2.9
* System: Windows

thanks in advance

**Comment by dacap** [comment]
Just in case, we don't support MinGW, on Windows you have to use Visual Studio 2017.

**Comment by Portrucci** [comment]
I did use Visual Studio, but I have MinGW somewhere in my path. Maybe that's the problem?

**Comment by dacap** [comment]
Oh yeah, that should be the issue, because there are some MinGW-related paths in the error console (e.g. `C:\PROGRA1\HASKEL1\847A5C~1.3\mingw\bin\cc.exe`).

**Comment by Portrucci** [comment]
Thanks, it worked!
I'll be sure to buy this amazing program as soon as I be able to
