### ISSUE TITLE
Merge selected

### ISSUE THREAD

**Issue by golddotasksquestions** [aseprite/aseprite#2018]
Feature Request:
Merge Selected

Selecting a layer plus shift-select (consecutive) or (individually) Ctrl-select multiple other layers, then right click or Layer -> merge selected. Just as it works with "duplicate" already.

![mergeslected](https://user-images.githubusercontent.com/47016402/53176064-92ec6d00-35ed-11e9-8ef8-9a717578c2c5.png)

### Aseprite and System version

* Aseprite version: 1.2.9
* System: Windows

**Comment by dacap** [comment]
Actually this is already available in [Aseprite v1.2.10-beta4](https://community.aseprite.org/t/get-aseprite-beta-version/22)

**Comment by golddotasksquestions** [comment]
Is "delete" already implemented like that? I mean can I delete multiple Layers at once?

**Comment by dacap** [comment]
Yes, it's.
