### ISSUE TITLE
Combining --trim and --sheet-pack causes sprite overlap

### ISSUE THREAD

**Issue by DragonDePlatino** [aseprite/aseprite#2020]
I'm storing all of my sprites in separate .ase files and I'm pulling them onto an atlas whenever I compile. I'm already using `--sheet-pack` but I'd like to save more space with `--trim`. The problem is that when I enable both at once, sprites aren't being packed properly.

When I use just `--sheet-pack`, my atlas looks like this:

![sprite_notrim](https://user-images.githubusercontent.com/9517192/53203380-ab10bc00-35ee-11e9-9f0d-940c4715b45a.png)

This is fine, but there's a lot of wasted space. Especially with large sprites like the flash at the top. If I enable `--trim --sheet-pack`, now my atlas looks like:

![sprite_trim](https://user-images.githubusercontent.com/9517192/53203381-ab10bc00-35ee-11e9-88bf-e1f2eef9b10c.png)

The sprites are being trimmed but they're covering each other up and hanging off the sides of the texture. As an experiment, I tried just `--trim` to see if it worked by itself:

![sprite_nopack](https://user-images.githubusercontent.com/9517192/53203379-ab10bc00-35ee-11e9-811b-558ba7e0ede2.png)

So I can get just `--sheet-pack` or just `--trim` to work, but not both at once. Here is my sprite makefile for reference:

```
ASEPRITE = "C:/Program Files/Aseprite/Aseprite.exe"
ATLAS = sprite.bmp
DATA = $(ATLAS:.bmp=.json)

ASE = $(wildcard *.ase)
SIZE = 512

sprite:$(ATLAS)

$(ATLAS):$(ASE)
	$(ASEPRITE) -b $(ASE) --sheet $@ --trim --sheet-pack --sheet-width=$(SIZE) --sheet-height=$(SIZE) --data $(DATA) --list-tags --list-slices

.PHONY: clean
clean:
	@rm -f $(ATLAS) $(DATA)
```

**Comment by dacap** [comment]
Fixed with 5d5aae73115a36e2eeb0fdf6fb373ce7b61418eb
