### ISSUE TITLE
Skia compiling- failed gclient sync?

### ISSUE THREAD

**Issue by Laeyein** [aseprite/aseprite#2021]
Can't even get past the first set of commands to build Skia. I've downloaded and installed everything else in it's correct path, some of them more than once, and I still cannot figure out the issue.

It lets me use 

> set PATH=C:\deps\depot_tools;%PATH%
> cd C:\deps\depot_tools

But when I try to run "gclient sync" it returns the following error message:

> Downloading CIPD client for windows-amd64 from https://chrome-infra-packages.appspot.com/client?platform=windows-amd64&version=git_revision:cc015d8903532826f4430b87501a3c542ef468ce...
> Failed to download the file, check your network connection
> At C:\deps\depot_tools\cipd.ps1:116 char:5
> +     throw "Failed to download the file, check your network connection ...
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Failed to downl...work connection:String) [], RuntimeException
>     + FullyQualifiedErrorId : Failed to download the file, check your network connection
> 
> Failed to bootstrap or update CIPD client
> 'python' is not recognized as an internal or external command,
> operable program or batch file.

My internet is perfectly fine for everything else. Anyone know what the problem could be?

### Aseprite and System version

* Aseprite version: most recent, self compiled (eventually)
* System: Windows 10

**Comment by micaelr95** [comment]
Did you tried to run CMD in admin mode. When i tried to compile i was having a lot of errors and when i run cmd in admin mode just worked.

**Comment by dacap** [comment]
We've [updated the compilation instructions](https://github.com/aseprite/aseprite/blob/master/INSTALL.md) to compile the `master` branch of Aseprite. There are [pre-built binaries of the Skia library available](https://github.com/aseprite/skia/releases).
