### ISSUE TITLE
Spanish Translation (1.2.10-beta4) + GUI problems

### ISSUE THREAD

**Issue by franzrogar** [aseprite/aseprite#2022]
Attached is the full Spanish translation of the current tree. There are some issues with the GUI that would need to be addressed but it's usable.

**EDITED**: I missed one line to translate. It's fixed now. Re-download if required.
[aseprite-language-extension-es.zip](https://github.com/aseprite/aseprite/files/2904635/aseprite-language-extension-es.zip)

Also, here's attached an image showing two problems: untranslatable strings (nowhere to be found in the .ini file) and problems with extended chars (it seems in-panels only uses basic ANSI chars).

![aseprite-gui-issues](https://user-images.githubusercontent.com/34715012/53364257-b6d9e680-393e-11e9-9dbc-f700390ab31b.png)

**EDITED**: New GUI issue: bottom down info untranslatable. See next pic.

![aseprite-gui-issues-2](https://user-images.githubusercontent.com/34715012/53401472-2936df00-39b0-11e9-8495-c0fa41952f3c.png)

**Comment by dacap** [comment]
Hi @franzrogar, thanks for this! as you see there are some missing characters in the minifont. I was planning to create this translation as an external package but never had enough time 😭 Could you please send a PR to https://github.com/aseprite/spanish-extension and check the contributing guide to [sign the CLA](https://github.com/aseprite/opensource/blob/master/sign-cla.md#sign-the-cla).

And I'll check these issues (no promises for next release)

**Comment by franzrogar** [comment]
You're welcome. As regarding as the translation I state it is public domain, so do with it as you please.

About the PR/CLA/etc. No thanks. I already wasted enough time with other projects doing stupid things just to send a mere plain text file (for example Blender, where they didn't even include it at the end because they didn't care at all to i18n). So, as it is public domain, you can do it by yourself.

Waiting for the rest of the missing strings.

Sincerely,
   Franz

**Comment by dacap** [comment]
Without signing the CLA the translation cannot be accepted. We're closing this issue by now.

**Comment by franzrogar** [comment]
WOW, it's stunning how you despise your Spanish users by not accepting a public domain work. Great work kiddo.

Next time you want to use a public domain let me know if you're able to get Darwin or Beethoven to sign your CLA.

**Comment by dacap** [comment]
@franzrogar please refer to these documents:

* http://www.rosenlaw.com/lj16.htm
* https://en.wikipedia.org/wiki/Public-domain-equivalent_license
