### ISSUE TITLE
Issue building aseprite on windows

### ISSUE THREAD

**Issue by Entoarox** [aseprite/aseprite#2035]
Following the build instructions I get stuck at the step just before `ninja aseprite` is to be called, with the following output happening:

```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.9
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cd C:\deps\aseprite\build

C:\deps\aseprite\build>cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_OS_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_OUT_DIR=C:\deps\skia\out\Release -G Ninja ..
CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
  The OLD behavior for policy CMP0046 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is Clang 7.0.0
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/CMakeDetermineCompilerId.cmake:793 (message):
  The Clang compiler tool

    "C:/deps/llvm/bin/clang.exe"

  targets the MSVC ABI but has a GNU-like command-line interface.  This is
  not supported.  Use 'clang-cl' instead, e.g.  by setting 'CC=clang-cl' in
  the environment.
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/CMakeDetermineCCompiler.cmake:113 (CMAKE_DIAGNOSE_UNSUPPORTED_CLANG)
  CMakeLists.txt:34 (project)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/deps/aseprite/build/CMakeFiles/CMakeOutput.log".
See also "C:/deps/aseprite/build/CMakeFiles/CMakeError.log".

C:\deps\aseprite\build>
```

I've tried googling and figuring things out if possible, but none of the solutions I've found seem to match this exact issue.

**Comment by cucsijuan** [comment]
This is happening to me too!

**Comment by MattDurajka** [comment]
Any updates ? I'm getting the same error while attempting to build Aseprite.

**Comment by dacap** [comment]
I think the issue in this case is that clang compiler is in the PATH. The only compiler in the PATH to compile Aseprite should be MSVC.

**Comment by Entoarox** [comment]
Simply removing clang dep folder (llvm) as was needed to compile skia simply results in it trying to build aseprite failing because it cant find the clang.exe in that folder anymore.

So please explain how I would remove clang compiler from the PATH, as the compile instructions do not even mention a need to do so, let alone a means.

**Comment by dacap** [comment]
@Entoarox Aseprite is not compiled with clang on Windows (only Skia). Anyway I'm not 100% sure if that could be done.

We use Clang to compile Skia (because Skia requires it to give better performance) but then Aseprite is compiled with Visual Studio. Check the Windows details of the INSTALL instructions:

https://github.com/aseprite/aseprite/blob/master/INSTALL.md#windows-details

The `VsDevCmd.bat` command sets the MSVC compiler in the PATH env variable.

**Comment by Entoarox** [comment]
@dacap If you checked my original log, you'd see it is direct output of the developer command prompt without any mention of skia, essentially a "clean copy", and yet it still references the clang.exe in the folder used for the skia compile.

**Comment by MattDurajka** [comment]
Even after running VsDevCmd.bat I still get missing compiler error even though it even found Visual Studio.
`C:\deps\aseprite\build>call "D:\Programs/Microsoft Visual Studio/2019/Community/Common7/Tools/VsDevCmd.bat" -arch=x64
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.0.2
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
C:\deps\aseprite\build>cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_OS_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_OUT_DIR=C:\deps\skia\out\Release -G Ninja ..
CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
  The OLD behavior for policy CMP0046 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is unknown
-- The CXX compiler identification is MSVC 19.20.27508.1
CMake Error at CMakeLists.txt:34 (project):
  The CMAKE_C_COMPILER:

    C:/deps/llvm/bin/clang.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Check for working CXX compiler: D:/Programs/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: D:/Programs/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "C:/deps/aseprite/build/CMakeFiles/CMakeOutput.log".
See also "C:/deps/aseprite/build/CMakeFiles/CMakeError.log".`

**Comment by MattDurajka** [comment]
Seems like I got futher by directly specifying the location of the MSVC C compiler using -DCMAKE_C_COMPILER="[path to C compiler]"

**Comment by Entoarox** [comment]
Executing `set CMAKE_C_COMPILER=<path to compiler>` before running the aseprite build command seems to have initiated the build, it is still going on my end, so no clue if it'll finish without errors.

**Comment by Entoarox** [comment]
Ok, now it fails due to a mismatch in target machine type and module machine type, I will just in case delete everything and start over, in case the previous build failures damaged something.
