### ISSUE TITLE
gn.py: Could not find checkout in any parent of the current path. This must be run inside a checkout.

### ISSUE THREAD

**Issue by raysichic** [aseprite/aseprite#2040]
https://github.com/raysichic/aseprite/blob/master/INSTALL.md#skia-on-windows

C:\deps\skia\tools>gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false target_cpu=""x64"" msvc=2015"
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.

C:\deps\skia\tools>gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false target_cpu=""x64"" cc=""clang"" cxx=""clang++"" clang_win=""c:\deps\llvm"""
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.
C:\deps\skia\tools>

**Comment by DrHighlen** [comment]
I'm having the same issue.

**Comment by dacap** [comment]
It looks like you are trying to execute the `gn` command from `C:\deps\skia\tools` when `gn` should be executed from `C:\deps\skia`.

**Comment by DrHighlen** [comment]
ok,  I think I was in tools because of C:\deps\skia    python tools/git-sync-deps command would get an error
