### ISSUE TITLE
Please remove skia as a dependency

### ISSUE THREAD

**Issue by dagostinelli** [aseprite/aseprite#2048]
I've installed/uninstalled aseprite on and off over the years. It's a nice tool.  Now it has skia and this has made life bad.  Does this tool really need to have that?  

In my case, I'm using Fedora.  So I have to compile aseprite.  But skia is a huge and painful. I want to learn and use aseprite.  I want to spend my precsious hours on earth learning the tool that will make my life better. I do not want to learn skia.  

Also... as a good Linux user, I try to avoid downloading random (huge) things like Skia and just blindly compiling/installing them becuase some random github repo says to.  Skia is the sort of thing that really should be in the Fedora official repo, or EPEL or RPMFusion or at least a COPR PPA.  But it isn't. So we have to go through this big thing to figure out how to compile it.

Please find a way to eliminate this as a dependency.  

Alternatively, maybe you can work with them to get their stuff into an official repo, so that we can just dnf/apt/yum install it.

**Comment by dagostinelli** [comment]
There was a suggestion to make it a submodule.  https://github.com/aseprite/aseprite/issues/1185

It was rejected.  So I'm raising the issue again for full removal.  

I think between the two, a dependency makes more sense.  You can use the Cmake directive `ExternalProject_Add` to compile a gyp project, specify or grab the place that skia gets compiled into and use it the path in aseprite's cmake file.

**Comment by dacap** [comment]
This was discussed in #139 too, there are no plans to remove Skia, and now we use it to handle color spaces/profiles and make conversions between them, so that possibility is even more remote.
