### ISSUE TITLE
Merge Down distorts destination layer somehow.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#2060]
I am not entirely certain why this happens, but when I merged these two layers together, it distorts _certain_ Cels on the target layer. I cannot figure out any parameters that might differentiate the affected Cels from unaffected ones.

I have recorded this .gif of the problem.
In this case, the pixels on only the destination layer are affected, and they are translated up two rows. Other Cels seemed to be transformed as well, though I have not recorded these effects here.
![mergedown](https://user-images.githubusercontent.com/11544843/56916638-5d4d7f80-6a87-11e9-9435-74a8f67b6476.gif)

Thanks for looking into it! :D 

..using ASEprite 1.2.9-x86 on Win10.

**Comment by dacap** [comment]
I think this could be related a bug fixed recently for v1.2.10:

https://community.aseprite.org/t/merging-down-layers-has-problem-with-linked-cells/2894

**Comment by oceanhahn** [comment]
Aa, I see! I hope that did it, then!
I presume 1.2.10 has not been released yet, though?

**Comment by dacap** [comment]
Yeah, 1.2.10 wasn't released yet, but maybe in this week.

**Comment by oceanhahn** [comment]
Cool, thanks! :D

**Comment by dacap** [comment]
It was some time ago with 11c8ba3605515035520c322d4f6a773e3367d1af
