### ISSUE TITLE
Can't generate skia files

### ISSUE THREAD

**Issue by patrykf04** [aseprite/aseprite#2061]
I tried to create skia files with ninja but I get the error 'C:/Program' is not recognized as an internal or external command, operable program or batch file.
here's a fragment from cmd:
C:\deps\skia>gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_libjpeg_turbo=false skia_use_libpng=false skia_use_libwebp=false skia_use_system_zlib=false target_cpu=""x86"" cc=""clang"" cxx=""clang++"" clang_win=""c:\deps\llvm"""
Done. Made 47 targets from 33 files in 2338ms
C:\deps\skia>ninja -C out/Release skia
ninja: Entering directory `out/Release'
[11/787] compile ../../src/opts/SkOpts_avx.cpp
FAILED: obj/src/opts/avx.SkOpts_avx.obj
cmd /c C:/Program Files (x86)/Windows Kits/10/bin/SetEnv.cmd /x86 &&   "c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_ENABLE_DISCRETE_GPU -DSKIA_IMPLEMENTATION=1 -I../../include/android -I../../include/c -I../../include/codec -I../../include/config -I../../include/core -I../../include/docs -I../../include/effects -I../../include/encode -I../../include/gpu -I../../include/atlastext -I../../include/pathops -I../../include/ports -I../../include/svg -I../../include/utils -I../../include/utils/mac -I../../include/private -I../../src/c -I../../src/codec -I../../src/core -I../../src/effects -I../../src/fonts -I../../src/image -I../../src/images -I../../src/lazy -I../../src/opts -I../../src/pathops -I../../src/pdf -I../../src/ports -I../../src/sfnt -I../../src/shaders -I../../src/shaders/gradients -I../../src/sksl -I../../src/utils -I../../src/utils/win -I../../src/xml -I../../third_party/etc1 -I../../third_party/gif -I../../src/gpu /arch:AVX /bigobj /WX /utf-8 -fms-compatibility-version=19 -imsvc "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC/Tools/MSVC/14.16.27023/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.17763.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.17763.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.17763.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.17763.0/winrt" /O2 /Zc:inline -Wno-unused-parameter -m32 /GR- /c ../../src/opts/SkOpts_avx.cpp /Foobj/src/opts/avx.SkOpts_avx.obj /Fd"obj/avx_c.pdb"
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.

C:\deps\skia>`
### Aseprite and System version
* System: Windows 10
* unknown Aseprite version

**Comment by peanutbuuter** [comment]
You said "C:**/**Program"
I think you should try \

**Comment by peanutbuuter** [comment]
Try: "C:\Program Files"
With the quotation marks

**Comment by patrykf04** [comment]
> Try: "C:\Program Files"
> With the quotation marks

but i only use the ninja -C out/Release skia. The rest is automatical

**Comment by dacap** [comment]
@patrykf04 did you use the `master` branch of skia? try to compile Skia with the [aseprite-m71 branch](https://github.com/aseprite/skia/tree/aseprite-m71) (which contains [this commit](https://github.com/aseprite/skia/commit/46855b81965d7521699b3ac10a2a84056deca32b) which I guess that could fix your problem)

**Comment by patrykf04** [comment]
It turns out that my Windows 10 SDK was broken. I reinstalled it and it now goes like it should but thanks for the help
PS: I did use the master branch of skia.

**Comment by patrykf04** [comment]
It crashed at very end: 
>[731/787] compile ../../third_party/externals/sfntly/cpp/src/sample/chromium/subsetter_impl.cc
>FAILED: obj/third_party/externals/sfntly/cpp/src/sample/chromium/sfntly.subsetter_impl.obj
>"c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -DSFNTLY_NO_EXCEPTION -DWIN32 ->D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX ->DNDEBUG -DU_USING_ICU_NAMESPACE=0  /w /bigobj /WX /utf-8 -fms-compatibility-version=19 ->imsvc "C:\Microsoft Visual Studio\2017\Community/include" -imsvc "C:/Program Files (x86)/Windows >Kits/10/Include/10.0.17763.0/shared" -imsvc "C:/Program Files (x86)/Windows >Kits/10/Include/10.0.17763.0/ucrt" -imsvc "C:/Program Files (x86)/Windows >Kits/10/Include/10.0.17763.0/um" -imsvc "C:/Program Files (x86)/Windows >Kits/10/Include/10.0.17763.0/winrt" /O2 /Zc:inline -Wno-unused-parameter /imsvc >C:/deps/skia/third_party/externals/sfntly/cpp/src  /GR- /c >../../third_party/externals/sfntly/cpp/src/sample/chromium/subsetter_impl.cc >/Foobj/third_party/externals/sfntly/cpp/src/sample/chromium/sfntly.subsetter_impl.obj >/Fd"obj/third_party/sfntly/sfntly_c.pdb"
>../../third_party/externals/sfntly/cpp/src/sample/chromium/subsetter_impl.cc(27,10):  fatal error: >'unicode/unistr.h' file not found
>#include <unicode/unistr.h>
         ^~~~~~~~~~~~~~~~~~
>1 error generated.
>[736/787] compile ../../third_party/externals/sfntly/cpp/src/sfntly/table/bitmap/eblc_table.cc
>ninja: build stopped: subcommand failed.
what is unistr.h?

**Comment by patrykf04** [comment]
changed skia and it worked!

**Comment by doubleaa93** [comment]
> changed skia and it worked!

What did you do. I'm having the same problem 
`>'unicode/unistr.h' file not found
#include <unicode/unistr.h>
^~~~~~~~~~~~~~~~~~
1 error generated.`
