### ISSUE TITLE
Failed linking aseprite.exe on windows

### ISSUE THREAD

**Issue by HyunnoH** [aseprite/aseprite#2063]
I did the process described in install.md on Windows 10. The command "cmake -DCMAKE_BUILD_TYPE = RelWithDebInfo .." has been completed but the "ninja aseprite" command has caused an error. The file "modp_b64_gen.exe" can not find wsock32.lib and ws2_32.lib.

```
C:\aseprite\build>ninja aseprite
[1/998] Linking C executable bin\modp_b64_gen.exe
FAILED: bin/modp_b64_gen.exe
cmd.exe /C "cd . && C:\TDM-GCC-64\bin\gcc.exe -O2 -g -DNDEBUG   laf/third_party/
CMakeFiles/modp_b64_gen.dir/stringencoders/src/arraytoc.c.obj laf/third_party/CM
akeFiles/modp_b64_gen.dir/stringencoders/src/modp_b64_gen.c.obj  -o bin\modp_b64
_gen.exe -Wl,--out-implib,lib\libmodp_b64_gen.dll.a -Wl,--major-image-version,0,
--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole3
2 -loleaut32 -luuid -lcomdlg32 -ladvapi32 wsock32.lib ws2_32.lib && cd ."
gcc.exe: error: wsock32.lib: No such file or directory
gcc.exe: error: ws2_32.lib: No such file or directory
[6/998] Building C object third_party/.../CMakeFiles/libcurl.dir/formdata.c.obj
ninja: build stopped: subcommand failed.

C:\aseprite\build>
```

### Aseprite and System version

* Aseprite version: master branch
* System: Windows 10 64-bit

**Comment by HyunnoH** [comment]
Well, I found the default compiler was set to gcc. I removed all available gcc on the Windows, and Cmake works as MSVC! Just it. Anybody who have an issue like me, remove all gcc and try again.

**Comment by reedjones** [comment]
Could you explain your solution?

**Comment by piratesephiroth** [comment]
You don't need to uninstall anything though. Just add the command line argument that makes CMake ignore the path where it's detecting GCC, like:

`-DCMAKE_IGNORE_PATH=D:/devkitPro/msys2/usr/bin/`

**Comment by frogstair** [comment]
@reedjones I fixed this by setting environment variable CC to cl and clearing CMake cache
