### ISSUE TITLE
Help » README Document Not Found

### ISSUE THREAD

**Issue by tajmone** [aseprite/aseprite#2066]
Trying to open the README file via Help shows error:

    File not found:
    README.md

There doesn't seem to be a markdown README file in the installation folder, only the `README.html` file in the root.

### Aseprite and System version

* Aseprite version: 1.2.10-x64, installer
* System: Windows 10 x64

**Comment by dacap** [comment]
Thanks @tajmone for reporting this issue. Will be fixed today with v1.2.11
