### ISSUE TITLE
Trouble compiling Aseprite on macOS

### ISSUE THREAD

**Issue by tetsuzanko** [aseprite/aseprite#2067]
Hello everyone

I've been trying (and failing) to compile Aseprite on my MacBook Pro for the past few hours and it's driving me insane. I followed the instructions found [here](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#macos-details) closely and got the source code via this command 
`git clone --recursive https://github.com/aseprite/aseprite.git`

However, everything gives me a ton of warnings and in the end the build fails. Since it is so much and I don't really know what information is relevant (I never compiled an application like this myself), I posted the entire output here:
[This](https://pastebin.com/aDarudE3) is what I got after running cmake (as explained in the step ["macOS details"](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#macos-details))
And [this](https://pastebin.com/kb56G83C) is the output after trying to build Aseprite via the Ninja command. I hope someone will be able to help me out.

I'm on macOS version 10.14.4

Thanks in advance

**Comment by tetsuzanko** [comment]
Thank you, I will try that! 🙏

**Comment by MJJBennett** [comment]
I had the same error (on macOS 10.15.2) and fixed it as suggested by @mrspeaker by putting `skia_use_libwebp=false` into the Skia arguments:

`gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_libwebp=false extra_cflags_cc=[\"-frtti\"]"`

And then `ninja -C out/Release skia`, and then just relinking it with `ninja aseprite` (a full rebuild was not necessary for Skia or Aseprite)

**Comment by dacap** [comment]
We've [updated the compilation instructions](https://github.com/aseprite/aseprite/blob/master/INSTALL.md) to compile the `master` branch of Aseprite. There are [pre-built binaries of the Skia library available](https://github.com/aseprite/skia/releases).
