### ISSUE TITLE
Aseprite instantly closes

### ISSUE THREAD

**Issue by patrykf04** [aseprite/aseprite#2070]
Aseprite instantly closes

[Aseprite-v1.3-dev-DebugOutput.txt](https://github.com/aseprite/aseprite/files/3170083/Aseprite-v1.3-dev-DebugOutput.txt)

### Aseprite and System version

* Aseprite version: 1.2,10-beta4
* System: Windows 10 Pro x64

**Comment by dacap** [comment]
@patrykf04 did you compile Aseprite with the Skia backend?

**Comment by patrykf04** [comment]
Yes

**Comment by dacap** [comment]
Ok, you can try the steps of this guide: https://www.aseprite.org/docs/troubleshooting/

**Comment by patrykf04** [comment]
Tried this on the start. It didn't do anything

**Comment by devvoid** [comment]
Are you able to open Aseprite from the command line?

**Comment by patrykf04** [comment]
how to open Aseprite from the command line?

**Comment by devvoid** [comment]
Open the folder where you have Aseprite installed in File Explorer. On the top bar of file explorer, type in "cmd", and then type in "aseprite" in the command line that pops up.

Running from terminal usually gives some extra debug info, which could help us figure out what the problem is.
