### ISSUE TITLE
Using the paint bucket tool outside the canvas will fill the region in line with the mouse cursor

### ISSUE THREAD

**Issue by sporeball** [aseprite/aseprite#2071]
If the paint bucket tool is used outside the canvas, it will fill whatever region on the canvas is immediately in line with the mouse cursor, i.e.:
* If the cursor is above the canvas, the region directly below the cursor will be filled.
* If the cursor is below the canvas, the region directly above the cursor will be filled.
* If the cursor is to the left of the canvas, the region directly to the right of the cursor will be filled.
* If the cursor is to the right of the canvas, the region directly to the left of the cursor will be filled.

This behavior persists regardless of zoom level.

### Aseprite and system version

* Aseprite version: Steam, v1.2.11-x64
* System version: Windows 10 v10.0.17763

**Comment by Gasparoken** [comment]
Hi @sporeball. Yes, that is normal behavior. I think this is fine as is, it gives the artist more tolerance if he wants to paint a region close to the canvas boundaries.

**Comment by sporeball** [comment]
wow, i thought this issue might stay unseen forever!

to be honest, because i thought this was a bug way back when, i don't think i *have* an idea of how it should behave instead.\
if it's normal, this issue can be safely closed.

**Comment by Gasparoken** [comment]
Thank you for your report in first place!
