### ISSUE TITLE
Support for extruded spritesheet exporting in --sheet-pack

### ISSUE THREAD

**Issue by jobtalle** [aseprite/aseprite#2072]
Issue #1890 implemented spritesheet extrusion, but it can currently only be used from the GUI as far as I'm aware; it would be great if one could export extruded spritesheets in combination with --sheet-pack through the CLI.

**Comment by jobtalle** [comment]
I've created a workaround until this issue is resolved: https://github.com/jobtalle/AtlasExtruder

It's just a simple python script that one can use during the build process. `sheet-pack` with `--border-padding 1 --shape-padding 2` creates sheets with two pixel borders between frames; this script can be run after exporting to extrude the frames.

**Comment by Bunderant** [comment]
I'm having issues with border-padding from the CLI, too, unfortunately. 

The padding is only applied to the top and left sides of the sprite sheet, but this is only an issue when using the "trim" option. Shape padding is unaffected, thankfully. Anyone else having this problem? I'm on v1.2.16.3-x64, the Steam distribution. Here are the arguments I'm passing in:

`-b --filename-format {title}_{tag}-{frame} --sheet-type packed --border-padding 1 --shape-padding 2 --sheet [...].png --format json-array --data [...].json`
