### ISSUE TITLE
macOS compile done wrong, no application.

### ISSUE THREAD

**Issue by ashshaosh** [aseprite/aseprite#2076]
Trying to build Aseprite on macOS and after successful(?) build I have many notifications about deprecation like this: 

`
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Gestalt.h:123:1: note: 'Gestalt' has been explicitly marked deprecated here
Gestalt(
^
8 warnings generated.
[1510/1510] Linking CXX executable bin/aseprite
` 

After that in build folder I haven't aseprite.app, only "data" folder and files: aseprite, gen and modp_b64_gen.

Skia is successfully compiled and linked with arguments: 
`bin/gn gen out/Release  --args='is_debug=false extra_cflags_cc=["-frtti"] is_official_build=false skia_use_system_expat=false skia_use_libjpeg_turbo=false skia_use_libpng=false skia_use_libwebp=false skia_use_system_zlib=false '`

### Aseprite and System version

* Aseprite version: release Aseprite-v1.2.11-Source, clone master branch - same result.
* System: macOS, 10.14.5

**Comment by mrspeaker** [comment]
@ashshaosh - `aseprite` is the application. You can launch it by double-clicking it, or running from the console `./bin/aseprite`.

**Comment by ashshaosh** [comment]
OMG, how this stupid :) this works fine now. Thank you so much :)
