### ISSUE TITLE
Pixel box for Paint Bucket and Gradient Tool are off center

### ISSUE THREAD

**Issue by Zapskam** [aseprite/aseprite#2078]
When the "Foreground Color" is set to "Mask," the pixel-sized box around the Paint Bucket isn't in the same place as the cursor. The box for the Gradient tool is also off regardless of color.

![Bug](https://user-images.githubusercontent.com/12706151/58745096-51543500-841a-11e9-8182-f354040ea05d.gif)

* Aseprite version: v1.2.11-x64, Steam
* System: Windows, 64-bit

**Comment by Gasparoken** [comment]
I couldn't reproduce it. I think it's solved (current version 1.2.40).
