### ISSUE TITLE
Problem occured when I try to build skia on Linux

### ISSUE THREAD

**Issue by orakless** [aseprite/aseprite#2083]
When I try to build skia, I need to do this command :
```
gn gen out/Release --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"
ninja -C out/Release skia
```
But I get that error :
```
ERROR at //gn/BUILDCONFIG.gn:85:14: Script returned non-zero exit code.
  is_clang = exec_script("gn/is_clang.py",
             ^----------
Current dir: /home/orakle/git/aseprite/deps/skia/out/Release/
Command: python -- /home/orakle/git/aseprite/deps/skia/gn/is_clang.py cc c++
Returned 1.
stderr:

  File "/home/orakle/git/aseprite/deps/skia/gn/is_clang.py", line 14
    print 'true'
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('true')?
```

I don't know why it's like that (maybe because the `python` command use the third version of python instead of the second?) but it's a bit annoying

### Aseprite and System version

* Aseprite version: NaN
* System: Linux, ArchLinux, kernel 5.0.13-zen1-1-zen

**Comment by devvoid** [comment]
What output do you get from `python --version`?

**Comment by orakless** [comment]
``Python 3.7.3``

**Comment by devvoid** [comment]
If you have Python 2.7 installed, you could try running `alias python=/usr/local/bin/python2.7`. That'll make `python` point to 2.7 for that shell.

**Comment by dacap** [comment]
@orakless I think depot_tools include python 2.7, did you include the depot_tools in the PATH?

**Comment by orakless** [comment]
@devvoid I tried but I still get that error (when I use ``python --version`` I get ``Python 2.7.16`` so I guess that's good?)

@dacap Yes, I include the depot_tools in the PATH variable with the command ``export PATH="${PWD}/depot_tools:${PATH}"``

**Comment by VOID404** [comment]
I'm pretty sure order in `PATH` decides what gets overwritten. Also, I've compiled today and there was no python2.7 in depot_tools. Alias may not work because it's called in scripts. Copying python2.7 binary to depot_tools, renaming it to `python` and moving it to the end of the `PATH` worked for me (on Manjaro).

**Comment by orakless** [comment]
I fixed it too but with another solution, I'll post this solution after my exams

**Comment by drachehavoc** [comment]
Same error here! please tell me what you do to resolve it.

**Comment by drachehavoc** [comment]
I re-install g++ and gcc and it works

**Comment by CBiX** [comment]
I'm still running into this issue on Arch Linux. Maybe you have to change parts of the code that expect python2 implicitly as on Arch Linux /usr/bin/python is always a link to python3 by default!

Or is this a bug in gn?

**Comment by orakless** [comment]
Hi. No, I just launched a shell where I added a directory with python2 renamed to python in my $PATH. It's one of my friend who helped me to fix that.
If you want, here is the script
```sh
#!/bin/bash

DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"

export PATH=${DIR}/bin_patch:${PATH}

echo "Starting a new shell."
bash
echo "Bye!"
```
You just have to add a directory called `bin_patch`, where you run this command to make a symbolic link to python2 called python: 
```sh
ln -s "$(which python2)" python
```
And after you just have to run the script, and enjoy.

**Comment by jovoni** [comment]
@orakless Hi. I have your same issue but unfortunately I don't really understand your solution. Can you please rephrase it explaining me the various passages? Would be so appreciated.

Thanks in advance.

**Comment by samsvp** [comment]
I had the same problem on Ubuntu 20.04 and the error persisted. If anyone is having this problem, this is what worked for me:
```bash
sudo apt install python2
echo script_executable = \"python2\" >> .gn
```
Got the answer from [here](https://githubmemory.com/repo/aseprite/skia/issues/5)

**Comment by aasierra** [comment]
If anyone is curious, I fixed this by adding to the root .gn file `script_executable = "python2"`

**Comment by Clemapfel** [comment]
For me this was fixed by aliasing python to python2.7, reinstalling generate-ninja and then calling `bin/gn gen (...)` as opposed to `gn gen (...)`
