### ISSUE TITLE
Jumble tool sometimes undoes last jumble step

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#2086]
Jumble tool sometimes undoes last jumble step after a tool change (it is a regression bug, version 1.2.10 works ok).

![Jun-10-2019 15-05-39](https://user-images.githubusercontent.com/32165475/59216086-42dfe900-8b91-11e9-97d8-e360c9be6082.gif)

* Aseprite version: post 1.2.11 (dev)
* System: macOS, Mojave, version 10.14.3

**Comment by dacap** [comment]
This should be fixed with 07f64b7682e91c3fa77f07ee0e6f29e7c4eb7e22, isn't it?

**Comment by Gasparoken** [comment]
Yes, is it!. Closed.
