### ISSUE TITLE
Error while compiling skia

### ISSUE THREAD

**Issue by alexeybobrovich** [aseprite/aseprite#2100]
When I run command: `ninja -C out/Release skia`, I get the error: `[4/7] compile ../../third_party/externals/sfntly/cpp/src/sample/chromium/subsetter_impl.cc
FAILED: obj/third_party/externals/sfntly/cpp/src/sample/chromium/sfntly.subsetter_impl.obj
"c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -DSFNTLY_NO_EXCEPTION -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DU_USING_ICU_NAMESPACE=0 -I../../third_party/externals/sfntly/cpp/src /w /bigobj /utf-8 -fms-compatibility-version=19 -imsvc "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC/Tools/MSVC/14.21.27702/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/winrt" /O2 /Zc:inline -Wno-unused-parameter /imsvc C:/deps/skia/third_party/externals/sfntly/cpp/src  /GR- /c ../../third_party/externals/sfntly/cpp/src/sample/chromium/subsetter_impl.cc /Foobj/third_party/externals/sfntly/cpp/src/sample/chromium/sfntly.subsetter_impl.obj /Fd"obj/third_party/sfntly/sfntly_c.pdb"
../../third_party/externals/sfntly/cpp/src/sample/chromium/subsetter_impl.cc(27,10):  fatal error: 'unicode/unistr.h' file not found
#include <unicode/unistr.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.`

### Aseprite and System version

* Aseprite version: 1.2.12
* System: Windows 10

**Comment by Krantz-XRF** [comment]
I had the same issue when compiling `skia` alone. I added the following line to `args.gn`, instructing `skia` to use the bundled ICU, and the errors disappeared:

```
use_system_icu = false
```

**Comment by alexeybobrovich** [comment]
> I had the same issue when compiling `skia` alone. I added the following line to `args.gn`, instructing `skia` to use the bundled ICU, and the errors disappeared:
> 
> ```
> use_system_icu = false
> ```

Thanks, Krantz-XRF. But I have long been solve it but forget close this issue. I just reinstall all tools on C drive. Now I share compiled version on my github.

**Comment by dacap** [comment]
I'll close this issue but put a link to it from `INSTALL.md` in a new Troubleshooting section.

**Comment by dacap** [comment]
I read your comment @alexeybobrovich, and actually it's [against the EULA](https://github.com/aseprite/aseprite/blob/master/EULA.txt) to shared compiled versions of Aseprite.

**Comment by juliopcrj** [comment]
He is already sharing, since at least 3 months ago: https://github.com/alexeybobrovich/Aseprite-compiled

**Comment by dacap** [comment]
Yeah, that is what I saw. @alexeybobrovich, would you mind to delete the repository? or do I have to contact GitHub to take it down?

**Comment by alexeybobrovich** [comment]
@decap, Ok I will delete the repository later.

**Comment by juliopcrj** [comment]
So far, the repository still exists.
