### ISSUE TITLE
Fails to start with Nettle 3.5 or higher (ABI break)

### ISSUE THREAD

**Issue by hollunder** [aseprite/aseprite#2105]
Aseprite seems to depend on libnettle.so.6 even if built with libnettle.so.7.
It fails to start due to that starting with Nettle 3.5.0 https://git.lysator.liu.se/nettle/nettle/blob/master/NEWS

### Aseprite and System version
* Aseprite version: gaf4fd54c2
* System: Arch Linux

**Comment by dacap** [comment]
Sorry but we don't give support to the unofficial Arch Linux version. You should contact them. Also they are doing something that is against our EULA.

**Comment by hollunder** [comment]
It was my mistake anyway, I didn't properly install the rebuilt package, sorry.

Arch Linux itself is not doing anything, the AUR package is a script created by a user and asks whether the user who builds using that script accepts the EULA, see: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aseprite

Anyway, for me it's more convenient to use this version rather than going through Steam. The humble version is of no use to me as it's a .deb.
