### ISSUE TITLE
Alpha Compositing does not work with pattern Brushes.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#2106]
Alpha Compositing mode only seems to work with regular geometry brushes, and not with pattern brushes, regardless of the brush opacity or any of the Pattern Brush's current parameters or settings.

![alphacomp+patternbrush](https://user-images.githubusercontent.com/11544843/61008322-32ac5c80-a33d-11e9-93c9-9b88d2d2d4aa.gif)

In this example, I was using a 1-bit pattern set to use the foreground colour. I would have expected it to act the same way a regular geometry brush (circle, line, etc.) would in Alpha Compositing mode, but instead it behaves as though it is set to Simple Ink mode.

Thanks for looking into it! :D 
..using ASEprite 1.2.13-x86 on Win10.

**Comment by dacap** [comment]
Related to #2016 and #945

**Comment by dacap** [comment]
@Gasparoken saw that this now is working, anyway the context bar doesn't work as we would like. For example, all inks are showing the opacity slider (e.g. simple ink, or shading) when they shouldn't, but we'll left this "broken context bar" issue assigned to #945.
