### ISSUE TITLE
Respect symmetry when moving selection

### ISSUE THREAD

**Issue by l-Marty-l** [aseprite/aseprite#2111]
When I have horizontal and vertical symmetry enabled and I use the selection tool to move something in the quarter of the sprite, the movement will not be mirrored across the symmetry axis.

It would be great it would respect my movement, as long as I don't cross the symmetry axis on whose things get mirrored.

### Aseprite and System version

* Aseprite version: v1.3-dev
* System: macOS 10.14.5

**Comment by dacap** [comment]
Duplicate #874

**Comment by l-Marty-l** [comment]
> Duplicate #874

Thanks, I failed on searching, apparently.

**Comment by dacap** [comment]
No problem 👍
