### ISSUE TITLE
Crash when holding dragging button, pasting and then pressing undo

### ISSUE THREAD

**Issue by FacePlace** [aseprite/aseprite#2115]
When I holding down the dragging button, pasting sprite and pressing undo, aseprite is crashing.

**Comment by Gasparoken** [comment]
Hi @FacePlace , thank you for write us.
Could you give us more detail from this issue?
- Aseprite version
- OS (Windows, MacOS, Linux)
- What you was dragging? (cel, layer, color, image, etc)
- What content had the clipboard when you pasted? (cel, layer, color, image, etc)

**Comment by FacePlace** [comment]
- The version is 1.2.13.0
- Windows
- Layer
- Image

**Comment by Gasparoken** [comment]
Sorry @FacePlace , we couldn't reproduce this crash.
Could you be so kind to send us the exact sequence of commands to reproduce the issue?

**Comment by FacePlace** [comment]
Here you are!
![crash](https://user-images.githubusercontent.com/43105109/61737160-571e2500-ad90-11e9-926c-9da7408cfeb7.png)

**Comment by dacap** [comment]
Oh thanks for the steps! We were confused (trying to dragging the selection in the canvas or the layers in the timeline), but in this case you are just scrolling/panning the canvas and pressing Ctrl+V and then Ctrl+Z, I was able to reproduce the bug 👍
