### ISSUE TITLE
Duplicate data with --sheet CLI

### ISSUE THREAD

**Issue by MasterfulMonkey** [aseprite/aseprite#2128]
I'm attempting to use the CLI to split a sprite by it's slices, then combine that into a horizontal sheet pack. Here's the batch commands I'm using:

`%ASEPRITE% -b "%~1" --save-as "%~2/%aspTempFolder%/sprite-{slice}.png"`

`%ASEPRITE% -b "%~2/%aspTempFolder%/sprite-*.png" --sheet "%~2/sheet.png" --data 
"%~2/%aspTempFolder%/data.json"`

where the first parameter is the source file and the second is the output destination.

The slicing works well, and each appears in a separate .png file in my temp folder. However, the sprite sheet has duplicate entries:

Sprite: 
![original sprite](https://i.imgur.com/5Gujhh5.png)
Expected result:
 ![expectation](https://i.imgur.com/DzhRXke.png)

Actual result: 
![reality](https://i.imgur.com/oihLsw2.png)

---------

Looking at the JSON data shows that each slice (i.e. each .png file in the temp folder) is processed as many times as there are slices:

`"sprite-slice0 0.png": { },`
`   "sprite-slice0 1.png": { },`
`   "sprite-slice0 2.png": { },`
`   "sprite-slice0 3.png": { },`
`   "sprite-slice0 4.png": { },`
`   "sprite-slice0 5.png": { },`

I'm not sure if the problem lies with Aseprite's CLI or with my own (cobbled-together) batch commands.

---------

Edit: I can get this to work by slicing the .ase file with the first command, and then opening all of the generated .png files as a single animation in Aseprite. From there, I can use the "Export Sprite Sheet" dialog to get what I want. However, I'd like to be able to do this without that extra hassle.

### Aseprite and System version

* Aseprite version: v1.2.11-x64, Steam
* System: Windows

**Comment by mrspeaker** [comment]
I'm having trouble recreating this issue, as on my machine (mac) it doesn't let me specify multiple files with `sprite-*.png`. It tells me `File not found: "*.png". No documents to export`. Is that batch format (with the %1, %2...) special? I have to list the files individually: `aseprite -b sprite-01.png sprite-02-png --sheet sheet.png`.

Doing this I get a correct output: though vertically, not horizontally stacked!

**Comment by dacap** [comment]
I think the problem here is that `".../sprite-*.png"` is listing all frames of the slice, so `"sprite-slice0 0.png"`,  "sprite-slice0 1.png",  "sprite-slice0 2.png",  "sprite-slice0 3.png", etc. are specified in the command line. Each file loads the whole sequence of frames creating its own animation. Similar to the problem from: https://github.com/aseprite/aseprite/issues/1936#issuecomment-451565903
