### ISSUE TITLE
Lock Alpha and Copy Alpha doesn't work with custom brushes

### ISSUE THREAD

**Issue by huwpascoe** [aseprite/aseprite#2133]
![Capture](https://user-images.githubusercontent.com/1812087/63059314-fd200380-bee6-11e9-87a1-862ec42f4604.JPG)

### Aseprite and System version
Aseprite 1.2.13-x64, Steam, Windows 10

**Comment by oceanhahn** [comment]
Possibly related to #2106.

**Comment by dacap** [comment]
Along with 7fd1c7e0e760eaaa5fffd4fbe9ac4f416f6e0c17 this issue should be fixed.
