### ISSUE TITLE
cling based C++ as scripting language / hot code reload

### ISSUE THREAD

**Issue by blockspacer** [aseprite/aseprite#2136]
cling based C++ as scripting language / hot code reload
Why? Able to run C++ script in runtime or compile it for max speed ( as in example https://github.com/derofim/cling-cmake )
Also: May be used to improve modules compile time 

> **HOT code reload**
> possible approaches:
> 
> store app state
> fix cling undo for files
> https://root-forum.cern.ch/t/loading-unloading-class-as-interpreted-macro-in-cling-multiple-times/32976/2
> 
> execute cling code to change callbacks & variables
> nested cling::Interpreter with multiple cling::MetaProcessor
> IDK how to do it, but you can create child cling::Interpreter

**Comment by dacap** [comment]
There are no plans to use C++ as a scripting language (maybe C++ plugins in the future with a C ABI)
