### ISSUE TITLE
Dead link in the README.

### ISSUE THREAD

**Issue by carlsmith** [aseprite/aseprite#2138]
The [project README][1] file links to a couple of pixel-art algorithms (towards the end of the Credits section). The first link (RotSprite) is fine, but the second (Pixel-Perfect Drawing) is broken. The domain (`deepnight.net`) is still active, but responds with [a custom a 404 at that path][2].

[1]: https://github.com/aseprite/aseprite
[2]: https://deepnight.net/pixel-perfect-drawing

**Comment by mast4461** [comment]
It looks like the PR that was merged fixed the problem so I think this issue can be closed.

**Comment by DeadlyDad** [comment]
Nope.  Still an issue.  I believe that the proper link should be 

https://deepnight.net/blog/tools/pixel-perfect-drawing/

not 

http://deepnight.net/pixel-perfect-drawing/

**Comment by MrCodeize** [comment]
Yea the link still gives a 404 error. Needs to be updated.

**Comment by dacap** [comment]
👍  fixed, thanks for reporting

**Comment by MrCodeize** [comment]
Thanks, dacap. Have a good one. :)
