### ISSUE TITLE
`Sprite.close()` issue

### ISSUE THREAD

**Issue by sumibi-yakitori** [aseprite/aseprite#2142]
I am creating a script that classifies and exports layers.

Clone the current sprite,
Make changes to the cloned sprite.

Aseprite will crash after closing the sprite for a while.

#### Example.
```lua
local newSprite = Sprite(app.activeSprite)

-- Some method to make changes to this sprite
app.command.BackgroundFromLayer(newSprite.layers[0])

-- app.refresh() -- No effect

newSprite:close()
-- app.command.CloseFile() -- OK
```

### Aseprite and System version

* Aseprite version: 1.2.13 portable
* System: Mac OS X 10.14.6 (18G87)

![Sprite_close_issue mov](https://user-images.githubusercontent.com/1794232/63964727-af082400-cad2-11e9-84ce-dad6453a22ce.gif)

**Comment by dacap** [comment]
Thanks for reporting this bug @sumibi-yakitori! there will be a fix for v1.2.14
