### ISSUE TITLE
Option for --list-slices to output to JSON silently

### ISSUE THREAD

**Issue by lawrence-laz** [aseprite/aseprite#2143]
When `--list-slices` is combined with `--data` we get slices listed in shell output as well as in JSON output.

I would like to avoid flooding shell output with slice names, because this command is part of a build pipeline, but I still want them in JSON output.

I quickly looked through the docs and didn't find any way to do this. Perhaps something like `--silent` could be introduced so as to not print stuff to shell output?

**Comment by dacap** [comment]
Hi @lawrence-laz, I think that we can do this: If `-data` is given, we can avoid printing slices with `-list-slices` to the terminal (so `-list-slices` behaves silently when it's used with `-data`, and prints output in the terminal if `-data` is not specified).
