### ISSUE TITLE
libnettle not found after system upgrade

### ISSUE THREAD

**Issue by flamendless** [aseprite/aseprite#2148]
After updating my system, it says
`aseprite: error while loading shared libraries: libnettle.so.6: cannot open shared object file: No such file or directory`

### Aseprite and System version

* Aseprite version: Compiled from source
* System: ManjaroLinux 18.0.4 x86_64  (Kernel: Linux 4.19.24-1-MANJARO)

**Comment by dacap** [comment]
Hi there, sorry but I'm not sure what libnettle, did you try recompiling Aseprite?

**Comment by flamendless** [comment]
Libnettle is from the nettle package. It's weird that aseprite depends on it though.

I'll try to recompile

**Comment by flamendless** [comment]
@dacap hmm i recompiled after pulling latest changes.

I did simple cmake .. and then ninja. It built successfully. But when i run the file in the bin folder, i get this `unable to create a user-interface display `

I'll try to recompile with skia backend for now

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flamendless** [comment]
Okay it works now with skia.
