### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by char1es10** [aseprite/aseprite#2154]
I am new to coding and these compiling mechanics, and I am trying to compile Aseprite. However, after I input 
`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_OS_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_OUT_DIR=C:\deps\skia\out\Release -G Ninja ..`

It concludes with a fail and says Configuring Incomplete, errors occured!
Could anyone help me?

**Comment by juliopcrj** [comment]
Based solely on the information you provided, no, no one can help you. "error" can be anything from missing library, to compiling agains the wrong architecture.

Provide more information regadring the error, and maybe someone can help.
