### ISSUE TITLE
CMake compiler error: "laf-os" linked by target

### ISSUE THREAD

**Issue by Martovvi** [aseprite/aseprite#2161]
After finally having arrived at the step:

cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_OS_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_OUT_DIR=C:\deps\skia\out\Release -G Ninja ..

I get this error:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SKIA_LIBRARY
    linked by target "laf-os" in directory C:/aseprite/laf/os

-- Configuring incomplete, errors occurred!

###

Downloaded version:
Visual Studio 2019 
CMake 3.15.3
Ninja 1.9.0  
LLVM 8.0
Aseprite 1.2.15-Source

System:
Windows 10 Enterprise 10.0.18362 Build 18362

**Comment by 3n-k1** [comment]
Currently fighting this issue myself. What was the solution?
