### ISSUE TITLE
'gn' is not recognised as an internal or external command

### ISSUE THREAD

**Issue by KPrzeczek** [aseprite/aseprite#2163]
So I'm at the step of compiling Aseprite where I use the following command:
__*gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false target_cpu=""x64"" cc=""clang"" cxx=""clang++"" clang_win=""c:\deps\llvm"""*__

However I am greeted with this error:
__*'gn' is not recognized as an internal or external command,
operable program or batch file.*__

Nobody else appears to be having the same error.
I have tried re-booting the PC, I've tried using different variations of the command called in different directories but none of them seem to work. When I call it in the 'bin' folder of 'skia' then it just responds with:
*__ERROR Need exactly one build directory to generate.
I expected something more like "gn gen out/foo"
You can also see "gn help gen".__*

Help would be appreciated 👍 

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by KashouC** [comment]
And you have installed depot_tools, and you added it to your system %path%?

**Comment by KPrzeczek** [comment]
> And you have installed depot_tools, and you added it to your system %path%?

yep, I have got the depot_tools in the deps directory along with llvm and skia
And by path do you mean something like this? : set PATH=C:\deps\skia\bin;%PATH%
I just did that now - It no longer has the error where it doesn't know what the command is but
ERROR Need exactly one build directory to generate.
I expected something more like "gn gen out/foo"
You can also see "gn help gen".
still persists.

**Comment by KashouC** [comment]
No I mean 

set PATH=C:\deps\depot_tools;%PATH%
cd C:\deps\depot_tools
gclient sync

without this path set, gn doesn't do anything.
