### ISSUE TITLE
Cannot open aseperite.exe after compilation

### ISSUE THREAD

**Issue by EastArctica** [aseprite/aseprite#2168]
Describe your bug report or feature request here
Cannot open Aseprite.exe after compilation, after following the written instructions to compile aseperite the exe will not open the exe "C:/aseperite/build/bin/aseperite.exe" I do have a file stored in this directly and cannot open it from the command line or graphical interface. the exe does have data in it as of the fact that it is 13 MB (13257 KB) and has the aseprite icon.

### Aseprite and System version

* Aseprite version: Aseprite v1.2.15
* System: Window, Version 10.0.18990.1

**Comment by dacap** [comment]
Hi @EastArctica, did you compile Aseprite with the Skia back-end? do you have some output of the compilation?

**Comment by EastArctica** [comment]
I was following this https://github.com/aseprite/aseprite/blob/master/INSTALL.md using LLVM 9.0.0 and CMAKE 3.15.4 I do not have the output of the compilation, sorry, I can recompile it and send it to you if you would like though. (I have already recompiled Skia and all of aseprite with a fresh source download)
