### ISSUE TITLE
Palette gradient based on HSV

### ISSUE THREAD

**Issue by neutron9** [aseprite/aseprite#2171]
Currently Aseprite is using RGB to create gradient for palettes.

For example, I want to make a gradient from (255,0,0) to (0,0,255), it will look like this:
![图片](https://user-images.githubusercontent.com/20411588/66563657-d69de200-eb90-11e9-9802-fba0a716b6dd.png)
The generated middle one looks a bit darker, since it's (128,0,128) which only has 50% value, while the original ones have 100%.
RGB: (255,0,0)→(128,0,128)→(0,0,255)
HSV: (0,100%,100%)→(300,100%,50%)→(240,100%,100%)

If it's based on HSV, then it will look like:
![图片](https://user-images.githubusercontent.com/20411588/66565023-00a4d380-eb94-11e9-839e-dcf7092871bb.png)
Look more natural.
RGB: (255,0,0)→(255,0,255)→(0,0,255)
HSV: (0,100%,100%)→(300,100%,100%)→(240,100%,100%)

An option could be added for users to choose.

**Comment by juliopcrj** [comment]
Isn't it possible to do this on a plugin?

**Comment by neutron9** [comment]
> 
> 
> Isn't it possible to do this on a plugin?

Maybe yes, but I'm not familiar with related API.
It would be more convenient if it's integrated into GUI.

**Comment by dacap** [comment]
For this feature we have to think with @Gasparoken the UI about how to offer this option of RGB/HSV/HSL gradients.
