### ISSUE TITLE
Move Selected Slices Together with Selected Layers

### ISSUE THREAD

**Issue by lawrence-laz** [aseprite/aseprite#2173]
Currently we can select multiple slices and move them, then select relevant part of the image and move that, like so:
![aseprite-slice-request-example](https://user-images.githubusercontent.com/8823448/66669927-35cb2780-ec61-11e9-831e-0de9541b4e97.gif)

I would like to be able to do this in a single action. This would particularly be useful for organizing big sprite sheets. 

Maybe we could have some modifier key to move an image together with selected slices?

**Comment by dacap** [comment]
Hi @lawrence-laz, yeah it would great to have that implemented, there were plans to add this functionality in the last slice improvements, but we need to implement the animation support first #721
