### ISSUE TITLE
Locked layer not completely locked

### ISSUE THREAD

**Issue by basile-laderchi** [aseprite/aseprite#2181]
If a layer is locked every operation should be disabled.

If I make a selection I can move it around using the arrow keys.
Moving with the mouse is disabled as it should.

### Aseprite and System version
* Aseprite version: v1.2.15 compiled
* System: Windows 10 x64

**Comment by KashouC** [comment]
![testt](https://user-images.githubusercontent.com/17066488/67013322-30ebf500-f0f3-11e9-914c-87d4399b7954.gif)
