### ISSUE TITLE
Allow me to use standard OS filebrowser

### ISSUE THREAD

**Issue by golddotasksquestions** [aseprite/aseprite#2196]
Describe your bug report or feature request here:

The more files there are in a folder, the harder it is to find the one I am looking for then I want to open a file in Aseprite.

- Browsing folders, selecting which file to open has a different expected flow depending on the OS the user is used to. Whatever file dialog Aseprite uses, it will therefore always break the flow or at least irritate some users.
- Aseprite users work with images. My standard OS lets me view files as preview thumbnails. As a visual person I much rather click on the image, not type in the name of a file (a name I would first have to memorize, or copy from somewhere else).
- Often I just want to open the last file I changed (not necessarily in Aseprite) or put in that folder, but Aseprite won't allow me to sort by "last modified", my OS does.

### Aseprite and System version

* Aseprite version: 1.2.9 (need to update, but lost my email and account on humble bundle)
* System: Windows 7

**Comment by dacap** [comment]
Actually the options is already available from Edit > Preferences > Experimental > Use native file dialog

**Comment by dacap** [comment]
On Windows you can use the Aseprite Thumbnails to get the preview of .aseprite files too: https://www.aseprite.org/thumbnails/

**Comment by golddotasksquestions** [comment]
@dacap Thanks! I acutally checked the preferences before writing the issue, but apparently missed this option in the Experimental subsection. Thanks again!

**Comment by dacap** [comment]
You're welcome! Don't worry, the option is *really* hidden, mainly because the Linux port is not ready and the macOS version of the native file selector wasn't ready until recent versions. I might move the option to the same file selector as soon as the option is available on all platforms (like a way to switch between both dialogs from the same dialog would be nice).
