### ISSUE TITLE
1.2.16.2 frame numbering bug

### ISSUE THREAD

**Issue by muldjord** [aseprite/aseprite#2198]
Aseprite 1.2.16.2

With this version the "Default first frame" number is ignored. I always have the first frame as "0". After updating it is always "1" even though I've set it to "0". This used to work so it seems to be a regression in the newer versions.

Running on Windows 10 x64 through Steam version

**Comment by muldjord** [comment]
Did a bit more digging. It works when starting a new project, but not when I load a week old project. Seems to be no way to align the frames of loaded projects so it matches with the "Default first frame" number of "0" I've set.

**Comment by dacap** [comment]
Thanks for reporting this @muldjord, I was going to put [this bug report](https://steamcommunity.com/app/431730/discussions/2/1657817111845334892/) too but you are the same author. We'll try to fix it ASAP.

**Comment by muldjord** [comment]
Thank you! I appreciate it
