### ISSUE TITLE
CLI doesn't export collapsed folder contents.

### ISSUE THREAD

**Issue by witlock** [aseprite/aseprite#2201]
Any layers grouped inside a folder that's collapsed wont be exported.
I first noticed this in April.

%ASEPRITE% -b --trim --frame-tag "%animationId% : %animation% : %heading%" --all-layers --list-layers %split% %file% --data "..\Aseprite Output\%animationId%-%animation%-%heading%.json" --format json-array --sheet "..\Aseprite Output\Spritesheets\%animationId%-%animation%-%heading%.png" --split-layers

### Aseprite and System version

* Aseprite version: 1.12.15
* System: Windows 10 64bit

**Comment by dacap** [comment]
Hi @witlock! could you please try this in Aseprite v1.2.16.2 (the latest version)? I've just tested and this issue seems to be fixed. Also in case that you want to export each layer separately in the sprite sheet, use the `-split-layers` parameter before the `%file%` argument.

**Comment by witlock** [comment]
@dacap seems to be working! I'm not sure why my Aseprite wasn't updated on either of my machines. Guess Steam update was paused. The worst thing is that this patch also includes another fix (-ignore-empty) which I spent hours on trying to bypass in game code :'(.
