### ISSUE TITLE
Export Sprite Sheet doesn't trigger Recent Folders

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#2202]
If you export a file using Export Sprite Sheet, the folder you save into will not get added to the Recent Folders list. It does get added using "Export" so I assume it's a bug with the Export Sprite Sheet dialogue.

**Comment by dacap** [comment]
Interesting, I'm thinking about it and I'm not sure if it should be added or not (the exported file and/or the exported folder). What do you think?

**Comment by KashouC** [comment]
I would want it to be added at least. I don't think it's any different from the other save functions. I was saving stuff into an export folder earlier but I kept having to scroll through all my folders to save it there just cause it didn't get put into the recent folders.
