### ISSUE TITLE
Can't compile in MacOS Catalina

### ISSUE THREAD

**Issue by felixcarmona** [aseprite/aseprite#2204]
Compiling with `-DCMAKE_OSX_ARCHITECTURES=x86_64`

Will throw the following error:
```
Undefined symbols for architecture x86_64:
  "is_orientation_marker(unsigned char const*, unsigned long, SkEncodedOrigin*)", referenced from:
      SkWebpCodec::MakeFromStream(std::__1::unique_ptr<SkStream, std::__1::default_delete<SkStream> >, SkCodec::Result*) in libskia.a(webp.SkWebpCodec.o)
ld: symbol(s) not found for architecture x86_64
```

AFAIK from now on (Catalina) Apple requires to use arm64 architecture  and we can't use x32 libraries anymore

**Comment by eon704** [comment]
Can't compile either... By any chance, have you found a solution for that?

**Comment by strobel1ght** [comment]
I need to know as well. Been trying for a week!

**Comment by dacap** [comment]
Please check the latest instruction from the `master` branch to compile Aseprite, there are pre-built Skia packages now.
