### ISSUE TITLE
The ability to solo a layer

### ISSUE THREAD

**Issue by PropFeds** [aseprite/aseprite#2207]
ie. to view only one layer by itself (hide everything else). Would be a really neat feature.

### Aseprite and System version

* Aseprite version: 1.2.16.2
* System: Windows

**Comment by KashouC** [comment]
You can alt+click the eye icon next to a layer to hide all other layers, then alt+click it again to show them again.

Alternatively you can go into the preferences and reduce the opacity of non-active layers but it's a bit of an heavier option.

![image](https://user-images.githubusercontent.com/17066488/69872197-12ae1300-12b5-11ea-83f1-2025b3f39efe.png)

**Comment by dacap** [comment]
I've closed this issue, but not sure if the alt+click is enough or maybe we could add a command (+keyboard shortcut) to do such thing.
