### ISSUE TITLE
Failure to open gif due to out of bounds image

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#2211]
Kind of a second hand report, but someone made a .gif out of some particles generated with pixel fx designer, and while out of bounds image information generated by pixel fx designer isn't exactly an Aseprite issue, handling how to open such cases might be.

The .gif in question works to open in GIMP but not in Aseprite.

The gif in question:

![result3](https://user-images.githubusercontent.com/17066488/70001611-08fb0880-155e-11ea-868b-d5da62266e5d.gif)

To be exact, the error says:

Error loading file:
Image 5 is out of sprite bounds.

**Comment by dacap** [comment]
Thanks for reporting this @KashouC, I've just added some information to [this post](https://itch.io/t/504089/gif-export-errors) in the Pixel FX Designer forum. Anyway I'll try to fix the GIF decoder to read this kind of files.
