### ISSUE TITLE
Previews for effects dialogs do not include pixels which are clipped by the bottom or right edge of the sprite editor

### ISSUE THREAD

**Issue by hiddenhare** [aseprite/aseprite#2216]
Aseprite v1.2.16.2-x64, Windows 10.

To reproduce: Open a sprite. Increase the zoom level to maximum and position the sprite so that its bottom and right edges are not on-screen. Open one of the modal dialogs for special effects ("Invert", "Replace Color", "Brightness/Contrast", etc.)

Expected behaviour: The entire sprite editor should display the preview.

Observed behaviour: If a magnified pixel is clipped by the bottom or right edge of the sprite editor, it is not affected by the preview.

**Comment by dacap** [comment]
This was fixed with #2884
