### ISSUE TITLE
Ellipses for 16x16 were better with the previous algorithm

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#2217]
![image](https://user-images.githubusercontent.com/39654/70434204-58f83480-1a62-11ea-8e4e-48ec142a8e8e.png)

The main difference of the previous algorithm is that it used the shape of the ellipse with odd radius for even radiuses (e.g. the circle 16x16 looked like the 15x15 but with an extra pixel in the axes).

**Comment by GAZ082** [comment]
Jesus, circles were actually lookable in older versions? Would be nice to have an option to revert to the old algorithm!

**Comment by dacap** [comment]
I tried to get them back but the old algorithm had a bug with certain ellipse sizes that crashes the program (or create an infinite loop), so I'll try to fix the current algorithm to create the older look in someway. It's top priority but it would be nice to have in the final v1.2.26.

**Comment by GAZ082** [comment]
Hey @dacap David, how is the dev going for this? Cheers.

**Comment by dacap** [comment]
Hi @GAZ082, we'll see if we can finish this change for the 2nd v1.3 beta (v1.3-beta2).
