### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by eksdims** [aseprite/aseprite#2219]
Entering `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_OS_BACKEND=skia -DSKIA_DIR=../../skia -DSKIA_OUT_DIR=../../skia/out/Release -G Ninja ..` while compiling aseprite, an error such as `Skia dir: C:/deps/skia
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SKIA_LIBRARY
    linked by target "laf-os" in directory C:/deps/aseprite/laf/os

-- Configuring incomplete, errors occurred!
See also "C:/deps/aseprite/build/CMakeFiles/CMakeOutput.log".
See also "C:/deps/aseprite/build/CMakeFiles/CMakeError.log".` occurs. What should I do?
...
...
...

The tools used to compile are:
Windows 10
Visual Studio Community 2019
CMake 3.16.1
Aseprite-1.2.16.2-Source.zip
depot_tools.zip

**Comment by idbrii** [comment]
If your error really contains `C:/deps/skia`, then it looks like a copy-paste error (unless you actually put stuff in that directory).

You're using relative paths. I used absolute paths to skia and got it working. See my steps here: https://gist.github.com/idbrii/9e1e56818ba99fc4403724f33acb4305
