### ISSUE TITLE
can't drag and drop in Linux

### ISSUE THREAD

**Issue by OneProngBent** [aseprite/aseprite#2220]
Hi, i've found i'm not able to drag and drop in linux , which is a huge problem for me when i want to speed up workflow. I've tried using multiple file managers, being Nemo, Dolphin and SpaceFM. I've found that whilst SpaceFM and Nemo just ignore Aseprite Dolphin thinks it doesn't exist and attempts to move/copy the files i have onto the application below, whether it be desktop or something else.
### Aseprite and System version

* Aseprite version: v1.2.16.3-x64, Steam

* System version: Arch Linux, Manjaro, Kernel version 5.4.2-1, Manjaro version 18.1.4, codename Juhraya

**Comment by dacap** [comment]
Hi @OneProngBent, known issue, duplicate #1410
