### ISSUE TITLE
Unable to build Skia on Windows 10.

### ISSUE THREAD

**Issue by StrawberryMahjong** [aseprite/aseprite#2225]
When trying to run:
`ninja -C out/Release skia`
It always ends prematurely with:
`FAILED: obj/third_party/externals/sfntly/cpp/src/sfntly/table/sfntly.table.obj
"c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -DSFNTLY_NO_EXCEPTION -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DU_USING_ICU_NAMESPACE=0  /w /bigobj /utf-8 -fms-compatibility-version=19 -imsvc "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC/Tools/MSVC/14.22.27905/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/winrt" /O2 /Zc:inline -Wno-unused-parameter /imsvc C:/deps/skia/third_party/externals/sfntly/cpp/src  /GR- /c ../../third_party/externals/sfntly/cpp/src/sfntly/table/table.cc /Foobj/third_party/externals/sfntly/cpp/src/sfntly/table/sfntly.table.obj /Fd"obj/third_party/sfntly/sfntly_c.pdb"
In file included from ../../third_party/externals/sfntly/cpp/src/sfntly/table/table.cc:34:
C:/deps/skia/third_party/externals/sfntly/cpp/src\sfntly/table/core/name_table.h(23,10): fatal error: 'unicode/ucnv.h' file not found
#include <unicode/ucnv.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
[601/983] compile ../../third_party/externals/sfntly/cpp/src/sfntly/table/truetype/glyph_table.cc
ninja: build stopped: subcommand failed.`

Any reason as to why this might be happening? I've followed the instructions correctly and everything worked fine until I tried to run the last command.

* System: Windows 10 Home 1909

**Comment by StrawberryMahjong** [comment]
After completely reinstalling VS2019, I ended up getting slightly further.
`ninja: Entering directory `out/Release'
[737/983] compile ../../third_party/externals/sfntly/cpp/src/sample/chromium/subsetter_impl.cc
FAILED: obj/third_party/externals/sfntly/cpp/src/sample/chromium/sfntly.subsetter_impl.obj
"c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -DSFNTLY_NO_EXCEPTION -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DU_USING_ICU_NAMESPACE=0  /w /bigobj /utf-8 -fms-compatibility-version=19 -imsvc "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC/Tools/MSVC/14.24.28314/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/winrt" /O2 /Zc:inline -Wno-unused-parameter /imsvc C:/deps/skia/third_party/externals/sfntly/cpp/src  /GR- /c ../../third_party/externals/sfntly/cpp/src/sample/chromium/subsetter_impl.cc /Foobj/third_party/externals/sfntly/cpp/src/sample/chromium/sfntly.subsetter_impl.obj /Fd"obj/third_party/sfntly/sfntly_c.pdb"
../../third_party/externals/sfntly/cpp/src/sample/chromium/subsetter_impl.cc(27,10): fatal error: 'unicode/unistr.h' file not found
#include <unicode/unistr.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
[739/983] compile ../../third_party/externals/sfntly/cpp/src/sfntly/table/core/cmap_table.cc
FAILED: obj/third_party/externals/sfntly/cpp/src/sfntly/table/core/sfntly.cmap_table.obj
"c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -DSFNTLY_NO_EXCEPTION -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DU_USING_ICU_NAMESPACE=0  /w /bigobj /utf-8 -fms-compatibility-version=19 -imsvc "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC/Tools/MSVC/14.24.28314/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/winrt" /O2 /Zc:inline -Wno-unused-parameter /imsvc C:/deps/skia/third_party/externals/sfntly/cpp/src  /GR- /c ../../third_party/externals/sfntly/cpp/src/sfntly/table/core/cmap_table.cc /Foobj/third_party/externals/sfntly/cpp/src/sfntly/table/core/sfntly.cmap_table.obj /Fd"obj/third_party/sfntly/sfntly_c.pdb"
In file included from ../../third_party/externals/sfntly/cpp/src/sfntly/table/core/cmap_table.cc:32:
C:/deps/skia/third_party/externals/sfntly/cpp/src\sfntly/table/core/name_table.h(23,10): fatal error: 'unicode/ucnv.h' file not found
#include <unicode/ucnv.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
[746/983] compile ../../third_party/externals/sfntly/cpp/src/sfntly/font.cc
ninja: build stopped: subcommand failed.`
Still getting the subcommand failed issue though.

**Comment by kakhlaghi** [comment]
I had an error at this point as well but it is indicating that my clang version is wrong. I used the one in the instructions which gives LLVM 8.0.0 but it says expecting 8.0.1

**Comment by dacap** [comment]
We've [updated the compilation instructions](https://github.com/aseprite/aseprite/blob/master/INSTALL.md) to compile the `master` branch of Aseprite. There are [pre-built binaries of the Skia library available](https://github.com/aseprite/skia/releases).

**Comment by dacap** [comment]
We've [updated the compilation instructions](https://github.com/aseprite/aseprite/blob/master/INSTALL.md) to compile the `master` branch of Aseprite. There are [pre-built binaries of the Skia library available](https://github.com/aseprite/skia/releases).
