### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [aseprite/aseprite#2248]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Extension::DitheringMatrixInfo::destroyMatrix](https://github.com/aseprite/aseprite/blob/e516d26fa801063fd05516e7576121c1769aaceb/src/app/extensions.cpp#L193 "Extension::DitheringMatrixInfo::destroyMatrix function")
- [Job](https://github.com/aseprite/aseprite/blob/b015fee8e0b221342f6bb68250b5aec635c6cc1a/src/app/job.cpp#L68 "Destructor for Job")

**Comment by dacap** [comment]
Thanks @elfring, I'm aware that `delete` already check if the pointer is null. Not sure why sometimes I add the `if` and sometimes no (or even just using `std::unique_ptr` in some cases), but a general refactor is needed (the same for `NULL` -> `nullptr`).
