### ISSUE TITLE
Building error: Missing parenthesis in call to 'print'

### ISSUE THREAD

**Issue by mikwee** [aseprite/aseprite#2252]
I tried to build Aseprite. Everything seemed to work fine, until I executed `python tools/git-sync-deps`. Then, it gave the following error:
`  File "tools/git-sync-deps", line 209
    print 'Skipping "%s".' % directory
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Skipping "%s".' % directory)?`
I have executed all of the previous commands as I was told in INSTALL.md and the video guide I watched. I don't know what went wrong. Thanks for any help that'll come.

### Aseprite and System version

* Aseprite version: 1.2.16.2, dev (Since I downloaded the source code, I guess? Correct me if I'm wrong)
* System: Windows 10, 1809, Pro

**Comment by brangor** [comment]
Hey - That's probably an error of running the command with Python 3. My Python 2 install is version  2.7.17 and it worked for me.

**Comment by mikwee** [comment]
So install Python 2 alongside my Python 3 installation.

**Comment by dacap** [comment]
@mikwee actually the `depot_tools` of Google should include Python 2, anyway I'm not sure if the latest version include it (as Skia is evolving, maybe they will migrate to Python 3)

Did you include the depot_tools path to the the PATH env variable?

**Comment by mikwee** [comment]
It worked! Thank you!
