### ISSUE TITLE
Does aseprite support MacOS 10.15?

### ISSUE THREAD

**Issue by Fehniix** [aseprite/aseprite#2254]
I hope this question pertains here. 
I have been attempting to compile aseprite on MacOS 10.15 with no success.

I have installed the latest version of CMake and am running MacOS 10.15 and Xcode 11.3.1. 
I have installed an successfully compiled all the possible builds for Skia, trying one at a time (Release, Debug, Clang etc.) and with the most recent aseprite-skia branches (currently compiled from the m71 branch, Release build). 

CMake is run using the following options:
`-DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_OSX_ARCHITECTURES=x86_64 \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
  -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk \
  -DLAF_OS_BACKEND=skia \
  -DSKIA_DIR=$HOME/deps/skia \
  -DSKIA_OUT_DIR=$HOME/deps/skia/out/Release \
  -G Ninja \
  ../`

Compiling the latest aseprite version, Skia m71 Release with Ninja, the following errors are printed out to the terminal:
`[1529/1529] Linking CXX executable bin/aseprite
FAILED: bin/aseprite 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -stdlib=libc++ -Wall -Wno-switch -O2 -g -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  src/CMakeFiles/aseprite.dir/main/main.cpp.o  -o bin/aseprite  lib/libapp-lib.a  lib/libclip.a  lib/libdio-lib.a  lib/libfilters-lib.a  lib/libflic-lib.a  lib/librender-lib.a  lib/libdoc-lib.a  lib/libfixmath-lib.a  lib/libui-lib.a  lib/liblaf-os.a  lib/liblaf-gfx.a  lib/libpixman.a  lib/liblaf-ft.a  -framework  Cocoa  -framework  Carbon  /Users/johnnybueti/deps/skia/out/Release/libskia.a  -framework  opengl  lib/libobs.a  lib/libundo.a  lib/libcmark.a  lib/libjpeg.a  lib/libgiflib.a  lib/libwebpdemux.a  lib/libwebpmux.a  lib/libwebp.a  /usr/lib/libm.dylib  lib/libfreetype.a  lib/libharfbuzz.a  lib/libfreetype.a  lib/libharfbuzz.a  lib/libpng16.a  /usr/lib/libbz2.dylib  lib/libjson11.a  lib/libarchive.a  /usr/lib/libiconv.dylib  /usr/lib/libcharset.dylib  /usr/lib/libexpat.dylib  lib/libfmt.a  lib/libtinyexpr.a  lib/liblauxlib.a  lib/liblua.a  lib/liblualib.a  lib/libupdater-lib.a  lib/libcfg-lib.a  lib/libtinyxml.a  lib/libnet-lib.a  lib/liblaf-base.a  lib/libmodpbase64.a  /usr/lib/libdl.dylib  lib/libcurl.a  lib/libz.a  -ldl  -lldap && :
Undefined symbols for architecture x86_64:
  "is_orientation_marker(unsigned char const*, unsigned long, SkEncodedOrigin*)", referenced from:
      SkWebpCodec::MakeFromStream(std::__1::unique_ptr<SkStream, std::__1::default_delete<SkStream> >, SkCodec::Result*) in libskia.a(webp.SkWebpCodec.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.`

This would lead me to think it is not possible to compile aseprite for the latest version of MacOS. Is this effectively the case? Thank you.

**Comment by gcmartijn** [comment]
I don't know about compiling, but running the latest app binaries works.

**Comment by brucecantarim** [comment]
I was able to reproduce this error while compiling.

**Comment by dacap** [comment]
We've [updated the compilation instructions](https://github.com/aseprite/aseprite/blob/master/INSTALL.md) to compile the `master` branch of Aseprite. There are [pre-built binaries of the Skia library available](https://github.com/aseprite/skia/releases).
