### ISSUE TITLE
Are public Github forks license violations?

### ISSUE THREAD

**Issue by sparr** [aseprite/aseprite#2266]
I have recently signed the CLA and plan to contribute some code to this project. My concern here is not the sort that would prevent me from contributing.

In reading the README and FAQ, I have either missed something or there is a gap in the intended licensing provisions.

> (b) Distribution.
> You may not distribute copies of the SOFTWARE PRODUCT to third parties.
> (g) Source code.
> You may only compile and modify the source code of the SOFTWARE PRODUCT for your own personal purpose or to propose a contribution to the SOFTWARE PRODUCT.

It feels like a violation of this license to have a fork of the project on Github. I am allowed to compile and modify the source to propose a contribution, and I do plan to PR my changes, so that's great. What's missing is permission for me to distribute the unmodified or modified source, which I, and 800 other people, are doing by having our own public forks on Github.

I don't expect to inspire a change to the text of the license; a simple "a public fork on github where all changes are intended to be part of pull requests to the main project will not be considered a license violation" comment would be excellent.

**Comment by PureAsbestos** [comment]
I think the important thing to notice here is the distinction between `SOFTWARE PRODUCT` and `source code of the SOFTWARE PRODUCT`. It says 
> "You may not distribute copies of the SOFTWARE PRODUCT to third parties."

but it does not say
> "You may not distribute copies of *the source code of* the SOFTWARE PRODUCT to third parties."

In part g, it explicitly mentions `source code of the SOFTWARE PRODUCT` and implies it is separate from the `SOFTWARE PRODUCT`. 
Since proposing a contribution implies the distribution of source as a part of the proposition process, and isn't explicitly disallowed, I think you are in the clear. Nevertheless, a clarification somewhere couldn't hurt.

(Obligatory: I am not a lawyer and this is not legal advice)

**Comment by sparr** [comment]
It not saying we may not distribute the source code is not equivalent to it saying we may distribute the source code. The provision for proposing contributions allows compiling and modifying, not distributing. As written, it would seem to want PRs to come from private repos. Of course, I also suspect that isn't the intention.

**Comment by PureAsbestos** [comment]
My argument holds only so long as it is implied that distribution of source code is a part of the contribution process. I think this is what disagree on. More clarity would of course be welcome.

**Comment by dacap** [comment]
The answer to *"Are public Github forks license violations?"* is no, because we considerer that the source code can be distributed (even modified copies). And only binaries cannot be distributed. We might modify the EULA soon to clarify these aspects (separation between Binary vs. Source Code).
