### ISSUE TITLE
Option to default zoom to "fit" or similar?

### ISSUE THREAD

**Issue by sparr** [aseprite/aseprite#2267]
I am working on 4x4, 8x8, and 16x16px sprites. Because they are so small and I have trouble seeing them, I need to zoom in pretty far to work on them. But I zoom in a different amount for each one, so they end up the same visible size.

It would be really helpful to me if I could set a default zoom level something like "fit" or "width" that would zoom a newly loaded/created image based on its size.

**Comment by dacap** [comment]
Some years ago (not sure if in another issue, email, a chat, a forum, etc.) I've talked with other user asking for the same thing.

The conclusion I reach is that it would be good idea to have a default "fit to screen" behavior for new files/open files, the only problem is that this default zoom might be confusing to check the sprite size (e.g. when there is no pixel grid enabled, etc.). A possible option would be to show an animation zooming in the canvas and showing the pixel grid temporarily (and make it invisible after a couple of seconds).

Not sure about sprites that are bigger than the canvas, maybe a "fit to screen" would be a good idea too.

**Comment by dacap** [comment]
For the next version, we could just add a simple checkbox/option to enable this "fit to screen" by default (without animation/feedback, etc. just an option.)

**Comment by dacap** [comment]
I've found the issue where this was talked before #789

**Comment by dacap** [comment]
New comment about the implementation here: https://github.com/aseprite/aseprite/issues/789#issuecomment-606021699

**Comment by Liquidream** [comment]
While having this when opening/creating docs is great - I'm quite often wanting to reset zoom to "fit" window after doing some work, and constantly faffing to get it centred correctly.

Would be great to have this "fit to window" (or closest exact multiple) option all the time, either by button or keystroke.

Perhaps it could be small button next to Zoom % input (maybe even with a preset of 100% zoom?) - just a thought.
Many thanks.

**Comment by dacap** [comment]
Hi @Liquidream, actually there is an option in the context bar when we have the Zoom tool selected:

![image](https://user-images.githubusercontent.com/39654/125803204-3f3a34af-5e87-41bd-9f37-70b3e021a13e.png)

Also activated with <kbd>Ctrl+0</kbd> or <kbd>⌘0</kbd>

**Comment by Liquidream** [comment]
Perfect - thank you! 👍
(Google failed me on this occasion)
