### ISSUE TITLE
Issue with compiling: 'CMake Generate step failed. Build files cannot be regenerated correctly.'

### ISSUE THREAD

**Issue by Chrisd313** [aseprite/aseprite#2273]
Hey everyone, just having an issue when trying to compile Aseprite, can anyone help me out with the below please? Its occuring when I get to the end of compiling.

` Skia dir: C:/deps/skia
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SKIA_LIBRARY
    linked by target "laf-os" in directory C:/Aseprite/laf/os

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

C:\Aseprite\build>`

**Comment by dacap** [comment]
We've [updated the compilation instructions](https://github.com/aseprite/aseprite/blob/master/INSTALL.md) to compile the `master` branch of Aseprite. There are [pre-built binaries of the Skia library available](https://github.com/aseprite/skia/releases).
