### ISSUE TITLE
CLI: --split-layers ignored when --sheet is used

### ISSUE THREAD

**Issue by rainerdeyke** [aseprite/aseprite#2278]
Like the title says, --split-layers does not work in conjunction with --sheet, neither for "grid" sheets nor for packed sheets.  The resulting sprite sheet is exactly as if --split-layers had not been passed as a command-line argument, with individual frames flattened into single cels.

### Aseprite and System version

* Aseprite version: 54bb39a9d39812bf0eaedcb3734fa83dea97e5e7
* System: Lubuntu 18.04 LTS on amd64

**Comment by dacap** [comment]
Hi @rainerdeyke, just in case, are you using `-split-layers` before opening the file? what is the specific command line that you are using?

E.g. this should work:
```
aseprite -b -split-layers player.aseprite -sheet player.png
```

**Comment by rainerdeyke** [comment]
That was my problem.  If I put --split-layers before the file, it works.  It would be nice if this were mentioned in the documentation for --split-layers.

**Comment by dacap** [comment]
Glad it worked. I'll add that information right now in the docs 👍

**Comment by dacap** [comment]
Actually [it says](https://www.aseprite.org/docs/cli/#split-layers): `Splits the visible layers of the next document [...]` but the "next document" might be ignored easily, I'll add some warning about it.
