### ISSUE TITLE
Ninja failing to find build.ninja on Windows 10

### ISSUE THREAD

**Issue by Nekolist** [aseprite/aseprite#2279]
Describe your bug report or feature request here
Ninja doesn't want to compile after running ninja aseprite. It fails to find a file called build.ninja

Aseprite 1.2.16.2 and Windows 10

**Comment by dacap** [comment]
@Nekolist are you located in the `build` directory? did you execute `cmake`? did `cmake` fail? do you have some output in the console?

**Comment by Nekolist** [comment]
I fixed the issue it's fine. I wasn't using the VS Command Prompt
