### ISSUE TITLE
Ninja build failing on macOS Catalina

### ISSUE THREAD

**Issue by retrobit** [aseprite/aseprite#2293]
First, I want to say that I looked at the README.md and INSTALL.md instructions for Asperite and Skia, the previously submitted issues regarding building problems, the Skia website, and the Ninja website before I got to this point.

As far as I can tell from the output, I have successfully built Skia.

I feel that I'm close... I had to add

```
  -DSKIA_LIBRARY=$HOME/Dev/asepriteDeps/deps/skia \
```
in addition to the existing
```
  -DSKIA_DIR=$HOME/deps/skia \
  -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
```
or rather, specifically, in my case
```
cmake \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_OSX_ARCHITECTURES=x86_64 \
-DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
-DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk \
-DLAF_BACKEND=skia \
-DSKIA_DIR=$HOME/Dev/asepriteDeps/skia \
-DSKIA_LIBRARY=$HOME/Dev/asepriteDeps/skia \
-DSKIA_LIBRARY_DIR=$HOME/Dev/asepriteDeps/skia/out/Release-x64 \
-G Ninja \
.. 
```
in order to get this far. Now, when I try `ninja aseprite`, I get
```
ninja: error: '/Users/user/dev/asepriteDeps/deps/skia/out/Release-x64/libskshaper.a', needed by 'bin/aseprite', missing and no known rule to make it
```
Not sure where to go from here. If you haven't noticed, I changed it so that I'm using my development directory to store the Skia dependencies, not just `$HOME/deps/skia`. Honestly, I think this might be the wrench in the build process, but I would really like agency over where I have Skia installed, so any help would be greatly appreciated... I used [Homebrew](https://brew.sh/) to install CMake and Ninja.

Also, as a side note: where in the build process can I configure CMake/Ninja so that I can choose my own target directory instead of `deps/skia`? I'd like to remove the redundant `deps` directory from my building since I'm trying to put Skia in `$HOME/Dev/asperiteDeps`.
### Aseprite and System version

* Aseprite version: latest code on master as of 3/7/2019. Last release at the time of writing this is **v1.2.16.3**.
* System: macOS Catalina 10.15.3, Xcode 11.3.1, macOS 10.15 SDK

**Comment by dacap** [comment]
Hi @retrobit, just in case, when you built Skia, did you call `ninja -C out/Release-x64 skia modules`? (the important part is the `modules`, which will build `skshaper`)

**Comment by retrobit** [comment]
Thank you for your attention and patience!

Odd. I looked through my terminal/shell command history and it looks like I did. I don't think I would ignore it if it failed, but just in case I deleted the Skia directory and tried rebuilding Skia from these steps:
```
git clone -b aseprite-m81 https://github.com/aseprite/skia.git
export PATH="${PWD}/depot_tools:${PATH}"
cd skia
python tools/git-sync-deps
gn gen out/Release-x64 --args="is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false extra_cflags_cc=[\"-frtti\"]"
ninja -C out/Release-x64 skia modules
```
It is only when I do
```
ninja -C out/Release-x64 skia modules
```
that I get
```
ninja: Entering directory `out/Release-x64'
[245/1459] ACTION //third_party/icu:make_data_assembly(//gn/toolchain:gcc_like)
Generated gen/third_party/icu/icudtl_dat.S
[725/1459] compile ../../modules/skshaper/src/SkShaper_harfbuzz.cpp
FAILED: obj/modules/skshaper/src/libskshaper.SkShaper_harfbuzz.o 
c++ -MD -MF obj/modules/skshaper/src/libskshaper.SkShaper_harfbuzz.o.d -DSKSHAPER_IMPLEMENTATION=1 -DNDEBUG -DSK_GAMMA_APPLY_TO_A8 -DSK_SHAPER_HARFBUZZ_AVAILABLE -DSK_GL -DSK_SUPPORT_PDF -DSK_USE_LIBGIFCODEC -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_XML -DSK_ASSUME_GL=1 -DU_USING_ICU_NAMESPACE=0 -DSK_USING_THIRD_PARTY_ICU -I../../modules/skshaper/include -I../.. -I../../third_party/externals/libgifcodec -I../.. -I/usr/include/harfbuzz -fstrict-aliasing -fPIC -fvisibility=hidden -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -O3 -Wno-unused-parameter -I /Users/ghost/Dev/asepriteDeps/skia/third_party/externals/icu/source/common -I /Users/ghost/Dev/asepriteDeps/skia/third_party/externals/icu/source/i18n -I /Users/ghost/Dev/asepriteDeps/skia/third_party/icu -std=c++17 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -frtti -c ../../modules/skshaper/src/SkShaper_harfbuzz.cpp -o obj/modules/skshaper/src/libskshaper.SkShaper_harfbuzz.o
../../modules/skshaper/src/SkShaper_harfbuzz.cpp:32:10: fatal error: 'hb.h' file not found
#include <hb.h>
         ^~~~~~
1 error generated.
[730/1459] compile ../../modules/skshaper/src/SkShaper_coretext.cpp
ninja: build stopped: subcommand failed.
```
After this, I decided to test building Aseprite using the [pre-compiled binary of Skia that is provided](https://github.com/aseprite/skia/releases), in the originally suggested location of `$HOME/deps/skia` and it worked.

So the real issue seems to be compiling of Skia on my end...

I noticed that the given set of commands for building Skia manaully don't specify `clang` or `-stdlib=libc++` anywhere, but it is mentions on the pre-compiled binaries page that they were built that way. Maybe this is my issue? Am I not using `clang` or `-stdlib=libc++`? How do I check or remedy this?

**Comment by dacap** [comment]
Glad to hear that you was able to compile it @retrobit. About the Skia instructions, as you said, it looks like the command line for macOS specifically is out dated, I'll update it right now.
