### ISSUE TITLE
Canvas Workspace border out of alignment.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#2294]
Somehow, the black line surrounding the Workspace managed to slip exactly one pixel down from the bottom edge and one pixel to the right of the right edge, and it has become incredibly distracting, especially when I am zoomed out a great deal. ,_,
This bug is present no matter the Canvas size or Zoom level, and the gap is always exactly 1px. on the lower and righthand sides.

Probably not a complex fix but I thought you ought to know.
![image](https://user-images.githubusercontent.com/11544843/76543700-43c5e400-645d-11ea-94d9-b69d84a83815.png)
🔼 _Screencapture of the relevant space on a blank 32px.sq. workspace. 1xzoom in the top left; scaled up and marked at center._

Thanks for taking a look at it! :D

..using ASEprite 1.2.17-x86 on Windoze 10.

**Comment by dacap** [comment]
We'll fix for v1.2.18 + some other fixes that appear in these days.

**Comment by oceanhahn** [comment]
Nice, thank you! :D 🎉

**Comment by dacap** [comment]
You're welcome and thank you to reporting this issue ^–^
