### ISSUE TITLE
Invalid `.desktop` file in the `.deb` package.

### ISSUE THREAD

**Issue by nlordell** [aseprite/aseprite#2295]
Just a minor issue: the `aseprite.desktop` file in the `.deb` package contains some invalid values and keys:
1. `Version` key is misused, it should be the `.desktop` file version and not the version of the application ([reference](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html#recognized-keys)). It should be omitted or be `1.0` or `1.1`.
2. `Encoding` key is deprecated ([reference](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html#deprecated-items))

### Aseprite and System version

* Aseprite version: Aseprite_1.2.17-1_amd64.deb (from Humble Bundle)
* System: Linux

**Comment by dacap** [comment]
Thanks for the info @nlordell, we'll fix it ASAP for v1.2.18.

**Comment by nlordell** [comment]
Thanks! And just FYI, its a pretty benign issue - I think most desktop launchers just ignore those invalid values. I just ran into this as I generate an AppImage from the `.deb` (since I don't use Ubuntu) and the tool I use verifies the `.desktop` file and complains about those issues.
