### ISSUE TITLE
 fatal error: skcms.h: No such file or directory on compiling Aseprite

### ISSUE THREAD

**Issue by mirandazellnik** [aseprite/aseprite#2296]
After following all other instructions [here](https://alexgonzalezc.dev/posts/how-to-build-aseprite-from-source.html) I was initially unable to compile Skia on my computer, but I downloaded the pre-compiled Linux x64 version from [here](https://github.com/aseprite/skia/releases) and placed all the files into `deps/skia`. After that, the cmake command worked. However, upon running `ninja aseprite`, all seemed well until it ran into this error, the tail end of which is:
```
../laf/os/skia/skia_color_space.cpp:17:10: fatal error: skcms.h: No such file or directory
 #include "skcms.h"
          ^~~~~~~~~
compilation terminated.
[658/1494] Building CXX object laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o
ninja: build stopped: subcommand failed.
```
What am I missing here? How do I fix this?

### Aseprite and System version

* Aseprite version: Not sure, whatever the version which is cloned from `git clone --recursive https://github.com/aseprite/aseprite.git`
* System: Linux, Ubuntu 18:04

**Comment by merwok** [comment]
The file exists in `path/to/deps/skia-lib-clone/skia/include/third_party/skcms/skcms.h`, but I don’t know how to make ninja see that.  Maybe time to delete build dir and restart?

**Comment by dacap** [comment]
@mirandazellnik please try deleting the `SKIA_SKCMS_INCLUDE_DIR` variable from you `CMakeCache.txt` file and run cmake again (pretty sure the `SKIA_SKCMS_INCLUDE_DIR` is pointing to the old location where the skcms.h file was located, but the new skia version moved the file to other location).

**Comment by merwok** [comment]
This works!  (as does rebuilding aseprite from scratch).

Now the build fails at the link step:
```
/usr/bin/ld : can't find -lSKSHAPER_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
which makes me think I should rebuild laf/skia from scratch.

**Comment by mirandazellnik** [comment]
This fixed it! However, when I start it up it says that there is a new version (v1.2.17). I can't even tell what version I have, as it just says "1.x-dev" in the "About" section, but assuming I am on an old version, then why? I thought that running 
> git clone --recursive https://github.com/aseprite/aseprite.git
would give the newest version... If not, how do I get the newest verdsion?

**Comment by merwok** [comment]
For what it’s worth, the deb version you can get from itch.io (or presumably the same one from steam) is labelled for Ubuntu but works on Debian.  I can stop building my own!

**Comment by JuanjoSalvador** [comment]
Got the same issue but compiling on Windows 10. @dacap solution works fine for me, no errors after that.

**Comment by JoshBot-Debug** [comment]
Why are you deleting/commenting out the variable? Just change the variable's path to where your skcms.h file is. Don't remove or comment out the variable, set it to the new path.

**Comment by juseus03** [comment]
I was facing a similar problem in Windows: "Cannot open include file: 'include/core/SkPaint.h': No such file or directory". The problem was that the SKIA_DIR variable was internally set to "C:/deps/skia". The solution was to add -DSKIA_DIR=real/path/to/skia to the cmake command. Leaving this comment just for help.
