### ISSUE TITLE
After building, says "Newer Version Availible"

### ISSUE THREAD

**Issue by mirandazellnik** [aseprite/aseprite#2297]
When I open Aseprite, it says there is a new version which I don't have (1.2.17). I can't even tell what version I have, as it just says "1.x-dev" in the "About" section, but assuming I am on an old version, then why? I thought that running 
`git clone --recursive https://github.com/aseprite/aseprite.git`
would give the newest version... If not, how do I get the newest version?

### Aseprite and System version
* Aseprite version: 1.x-dev
* System: Linux, Ubuntu 18:04

**Comment by dacap** [comment]
Hi there, there is no newer version, but this is a check done for the official version. This is related to #2175 I'll close this issue as duplicate. We'll remove the "new version" check for compiled versions.

**Comment by mirandazellnik** [comment]
So just to be clear, the version I have is the 1.2.17 newest version?

**Comment by dacap** [comment]
Yes, you have even a newer version than 1.2.17, because when you compile Aseprite, you compile a specific commit, and as you have compiled the latest master and your version said `1.x-dev`, I'm pretty sure that you have compiled at least a0882ba4435afc6707e780282cc3c5a676d307a1.
