### ISSUE TITLE
Retain "Export File" dialogue window size

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#2300]
If you resize the Export File dialogue and hit export, it will revert back to the default size instead of remembering what you did. This is not in line with how the other windows operate, like the export sprite sheet window, or the file browser.

**Comment by dacap** [comment]
Nice catch! Don't know why it doesn't work in that way from the very beginning.

**Comment by KashouC** [comment]
Credit goes to the discord help channel :D
