### ISSUE TITLE
Can't compile on windows 10

### ISSUE THREAD

**Issue by RealCyGuy** [aseprite/aseprite#2312]
This is the `CMakeError.log` file: https://hastebin.com/iniqoticod.shell
### Aseprite and System version

* Aseprite version: most recent
* System: Windows 10

**Comment by spec-chum** [comment]
Try now, last commit fixed it for me.  I nuked the repo and started again, just in case, compiled fine.

**Comment by RealCyGuy** [comment]
still when i do it there is a lot of `not found` or `failed`

**Comment by RealCyGuy** [comment]
i am still getting `not found` and `failed`
