### ISSUE TITLE
Building Curl fails while compiling 319c89c2ada8776ebba12b5c67aa59eb33fd3d2e

### ISSUE THREAD

**Issue by oatmealine** [aseprite/aseprite#2313]
While building Aseprite, this error occurs:

```
../third_party/curl/lib/hostip.c: In function ‘Curl_printable_address’:
../third_party/curl/lib/hostip.c:191:21: error: dereferencing pointer to incomplete type ‘const struct sockaddr_in’
  191 |       ipaddr4 = &sa4->sin_addr;
      |              
```

It seems to be happening because of Curl, and not any other libraries. If it helps, I have Curl 7.69.1 and libcurl 7.69.1 installed on the same system. 

### Aseprite and System version

* Aseprite version: 319c89c2ada8776ebba12b5c67aa59eb33fd3d2e
* System: Linux 5.5.7-150.current, Solus 4.1 x86_64

**Comment by oatmealine** [comment]
Forgot to mention, there are also a few warnings while compiling it aswell, such as:
```
../third_party/curl/lib/curl_addrinfo.h:78:25: warning: ‘struct hostent’ declared inside parameter list will not be visible outside of this definition or declaration
   78 | Curl_he2ai(const struct hostent *he, int port);
      |         
```

```
/usr/include/features.h:185:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
  185 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
```

**Comment by Xtendera** [comment]
Curl has been updated, this can be closed

**Comment by dacap** [comment]
Yes, the curl version was updated to curl-v7.79.1, this issue might be solved. I'm closing this but we can re-open it by any further problem.
