### ISSUE TITLE
"ninja aseprite" command does not work

### ISSUE THREAD

**Issue by Jijiyaki** [aseprite/aseprite#2322]
I am following the INSTALL.md file in order to compile aseprite, however, when running the command "ninja aseprite", I get errors and it terminates.

[170/1504] Building CXX object third_party/harfbuzz/CMakeFiles/harfbuzz.dir/src/hb-ot-shape-complex-khmer.cc.obj
FAILED: third_party/harfbuzz/CMakeFiles/harfbuzz.dir/src/hb-ot-shape-complex-khmer.cc.obj
C:\MinGW\bin\c++.exe  -DCMARK_STATIC_DEFINE -DHAVE_ATEXIT -DHAVE_FALLBACK -DHAVE_FREETYPE=1 -DHAVE_GETPAGESIZE -DHAVE_INTEL_ATOMIC_PRIMITIVES -DHAVE_ISATTY -DHAVE_MPROTECT -DHAVE_OT -DHAVE_UCDN -DHAVE_UNISTD_H -DNDEBUG -DPNG_NO_MMX_CODE -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../third_party/. -Ithird_party/harfbuzz/src -I../third_party/harfbuzz/src/hb-ucdn -Ithird_party/freetype2/include -fno-rtti -fno-exceptions -fno-threadsafe-statics -O2 -g -DNDEBUG   -std=c++11 -MD -MT third_party/harfbuzz/CMakeFiles/harfbuzz.dir/src/hb-ot-shape-complex-khmer.cc.obj -MF third_party\harfbuzz\CMakeFiles\harfbuzz.dir\src\hb-ot-shape-complex-khmer.cc.obj.d -o third_party/harfbuzz/CMakeFiles/harfbuzz.dir/src/hb-ot-shape-complex-khmer.cc.obj -c ../third_party/harfbuzz/src/hb-ot-shape-complex-khmer.cc
In file included from ../third_party/harfbuzz/src/hb-ot-shape-complex-khmer-private.hh:30:0,
                 from ../third_party/harfbuzz/src/hb-ot-shape-complex-khmer.cc:27:
../third_party/harfbuzz/src/hb-private.hh:55:20: fatal error: intrin.h: No such file or directory
 #include <intrin.h>
                             ^

I copied one error from the terminal, the others are the same but the first number goes up to 174. 

Then it ends with this: 
[175/1504] Building C object third_party/libwebp/CMakeFiles/webpencode.dir/src/enc/picture_csp_enc.c.obj
ninja: build stopped: subcommand failed.

I believe I have everything properly installed, and the only thing I'm a bit hazy about is where I place the ninja.exe file. I currently have it in the CMake bin folder.

I am quite new to this, just to let you know, so expect some silly mistake on my part.

* Aseprite-v1.2.17-Source
* Windows 10

**Comment by Jijiyaki** [comment]
I reinstalled the source code and skia, and I got this new error:
C:\aseprite\build>ninja aseprite
[71/1514] Generating scripts/pnglibconf.c
FAILED: third_party/libpng/scripts/pnglibconf.c
cmd.exe /C "cd /D C:\aseprite\build\third_party\libpng && "C:\Program Files\CMake\bin\cmake.exe" -DOUTPUT=scripts/pnglibconf.c -P C:/aseprite/build/third_party/libpng/scripts/gensrc.cmake"
options.awk: bad line (11): com
CMake Error at scripts/gensrc.cmake:41 (message):
  Failed to generate pnglibconf.tf7


[72/1514] Generating pnglibconf.c
FAILED: third_party/libpng/pnglibconf.c
cmd.exe /C "cd /D C:\aseprite\build\third_party\libpng && "C:\Program Files\CMake\bin\cmake.exe" -DOUTPUT=pnglibconf.c -P C:/aseprite/build/third_party/libpng/scripts/gensrc.cmake"
options.awk: bad line (10): com
CMake Error at scripts/gensrc.cmake:68 (message):
  Failed to generate pnglibconf.tf5


[76/1514] Building C object third_party/libwebp/CMakeFiles/webpdecode.dir/src/dec/idec_dec.c.obj
ninja: build stopped: subcommand failed.

**Comment by jandreski** [comment]
Try following this tutorial: https://www.youtube.com/watch?v=si7N0GeqOH8
Ended up working fine for me. As it is for a slightly older aseprite version, you won't have to do all the steps.

**Comment by Jijiyaki** [comment]
I did use this video as a guide, and I even tried to compile skia by myself like he did in the video. However, both compling skia and aseprite fail at ninja with the same error. ninja: build stopped: subcommand failed.

**Comment by Jijiyaki** [comment]
Out of curriosity, what is pnglibconf.tf5 and pnglibconf.tf7, because those are the fail points for most of my attempts on this.

**Comment by Jijiyaki** [comment]
Depending on which download method I use, the error messages differ.

**Comment by Jijiyaki** [comment]
I saw that it was MinGW that was messing up the cmake compilation or something. I just deleted it, compiled aseprite, it worked, then I restored MinGW.
