### ISSUE TITLE
Add F2 as a shortcut to rename layers

### ISSUE THREAD

**Issue by ElnuDev** [aseprite/aseprite#2326]
F2 is a universal shortcut in my experience for renaming, so it would be really nice if it would work in Aseprite as well.

**Comment by Unknow0059** [comment]
Edit → Keyboard Shortcuts → Search Bar → Result List → Rebind 'Layer Properties' command to 'F2'.

**Comment by ElnuDev** [comment]
@Unknow0059 True, but this should be bound by default.
