### ISSUE TITLE
Aseprite won't open after compiling successfully on mac

### ISSUE THREAD

**Issue by Alex25820** [aseprite/aseprite#2330]
I have succesfully compiled aseprite on my MacBook but when I try to launch it by opening the "aseprite" file found in /Applications/aseprite/build/bin the program crashes. A popup saying "aseprite quit unexpectedly" comes up.

This is what is shown in the console once I run the program:
`USER$ /Applications/aseprite/build/bin/aseprite ; exit;`
`Segmentation fault: 11`
`logout`
`Saving session...`
`...copying shared history...`
`...saving history...truncating history files...`
`...completed.`
` `
`[Process complete]`

I followed the steps in INSTALL.md when downloading and compiling aseprite.

### Aseprite and System version

* Aseprite version: 1.2.17, downloaded using `git clone --recursive https://github.com/aseprite/aseprite.git`
* System: macOS, 10.15.3

**Comment by andreapastorp** [comment]
I am also getting the same error on macOS 10.15.4
I followed the process to compile Skia and Aseprite with no errors whatsoever.

In my case the terminal shows
`zsh: segmentation fault  ./aseprite
`
`[Process completed]`

If it's any help, I am attaching the crash report that shows up in my mac. 
[aseprite-error-log.txt](https://github.com/aseprite/aseprite/files/4434184/aseprite-error-log.txt)


The console shows the following also:
`Sandbox: logd(107) System Policy: deny(1) file-read-data
`

**Comment by dacap** [comment]
Hi there, yes, the `master` branch has a problem when running Aseprite for the first time. We'll try to fix it this week.

**Comment by Alex25820** [comment]
Thanks for the info, please notify me when the fix has been implemented.

**Comment by dacap** [comment]
Hello everybody, it's fixed in master branch (commit 3cd97c982263ebd10c99f6188e4c82269034ca0d). Thanks for the bug report!
