### ISSUE TITLE
Aseprite doesn't follow XDG Base Directory specifications

### ISSUE THREAD

**Issue by BanchouBoo** [aseprite/aseprite#2332]
Rather than checking the `XDG_CONFIG_HOME` environment variable, Aseprite hardcodes the path for configuration to the `~/.config` directory. You can read about the XDG Base Directory specs here: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

**Comment by LunarLambda** [comment]
Still not fixed :/

**Comment by dacap** [comment]
I'll take a look to this one, shouldn't that hard to fix 😅
