### ISSUE TITLE
.pal palettes refuse to load

### ISSUE THREAD

**Issue by vrbandwagon** [aseprite/aseprite#2337]
Describe your bug report or feature request here
I have downloaded several .pal palettes, and none of them work when clicking on Options > Load Palette.

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
1.2.17-x64, portable?
* System: Windows/macOS/Linux, version, distribution
Linux Mint Cinnamon 17.3 64-bit

**Comment by KashouC** [comment]
Can you share these palettes and where you got them from?

**Comment by vrbandwagon** [comment]
Thank you for your answer.
One of them is this one: [https://rgbsource.blogspot.com/2016/11/nes-hybrid-palette-striking-balance.html](https://rgbsource.blogspot.com/2016/11/nes-hybrid-palette-striking-balance.html)
Another one is NES Classic (FBX).pal (I can't seem to find the website's address at this moment).
I've just tried one on [https://lospec.com/palette-list/nintendo-entertainment-system](https://lospec.com/palette-list/nintendo-entertainment-system) and it works. What makes some work and others not?

**Comment by KashouC** [comment]
Generally a .pal file is basically just a renamed text file. The contents look like this when you load them with notepad/wordpad.

![image](https://user-images.githubusercontent.com/17066488/79454636-de30be80-7feb-11ea-8301-bc4e23ef4ffc.png)

The ones from RGB Source don't work this way for some reason and the site seems to have some posts about flashing your NES with different palettes so it might be something a bit more specialized, but that's just my guess.

**Comment by dacap** [comment]
Yeah, the issue is that Aseprite doesn't support that kind of .pal files (only the JASC pal format as described by @KashouC ).
