### ISSUE TITLE
Problems for compiling

### ISSUE THREAD

**Issue by Vanane** [aseprite/aseprite#2338]
Describe your bug report or feature request here
Hi, I'm trying to compile the repository. I installed a fresh visual studio community 2019 version, with CMake tools from the Visual studio Installer yesterday. I downloaded, created folders exactly as told in the INSTALL.md, downloaded the Skia build for Windows x64, but it doesn't work.

The CMake command specific to Windows (with all the options) doesn't work. When CMake verifies if Visual Studio's C++ compiler CL is valid, it just tells that it can't compile a simple program. (I tried to manually compile the said simple program, it works)

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
Latest commit hash in history : ae9c37e90 (cloned this morning)
Version of CMake : 3.16.19112601-MSCV_2
Version of Ninja : 1.8.2
Version of Windows SDK : 10.0.18363.720
* System: Windows/macOS/Linux, version, distribution
Windows 10 Family version 1909 (OS Version : 18363.720)

**Comment by Vanane** [comment]
Hi again,
I am using this command : 
`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x64 -G Ninja ..`

The Skia binary is in the right folder. 

As I said, CMake was using the compiler installed with Visual Studio, CL.exe, and it wasn't working. So I installed MinGW's compilers gcc and g++, those two work with CMake. 
[CMakeCache.txt](https://github.com/aseprite/aseprite/files/4487211/CMakeCache.txt)

Now, I'm trying to compile using `ninja aseprite`, and I'm gettings errors on the compilation :
```
[177/1502] Building CXX object third_party/fmt/CMakeFiles/fmt.dir/src/format.cc.obj
FAILED: third_party/fmt/CMakeFiles/fmt.dir/src/format.cc.obj
C:\MinGW\bin\c++.exe  -DCMARK_STATIC_DEFINE -DNDEBUG -DPNG_NO_MMX_CODE -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../third_party/. -I../third_party/fmt/include -O2 -g -DNDEBUG   -std=c++11 -MD -MT third_party/fmt/CMakeFiles/fmt.dir/src/format.cc.obj -MF third_party\fmt\CMakeFiles\fmt.dir\src\format.cc.obj.d -o third_party/fmt/CMakeFiles/fmt.dir/src/format.cc.obj -c ../third_party/fmt/src/format.cc
In file included from ../third_party/fmt/src/format.cc:8:0:
../third_party/fmt/include/fmt/format-inl.h: In function 'void fmt::v6::vprint(FILE*, fmt::v6::string_view, fmt::v6::format_args)':
../third_party/fmt/include/fmt/format-inl.h:1367:22: error: '_fileno' was not declared in this scope
   auto fd = _fileno(f);
                      ^
[182/1502] Building CXX object third_party/fmt/CMakeFiles/fmt.dir/src/os.cc.obj
ninja: build stopped: subcommand failed.

```

**Comment by Vanane** [comment]
I also used Visual Studio's compiler instad of MinGW, and I get those errors instead : 
```
[1/1312] Linking CXX static library lib\libfmt.a
FAILED: lib/libfmt.a
cmd.exe /C "cd . && C:\MinGW\bin\ld.exe /lib /nologo  /out:lib\libfmt.a third_party/fmt/CMakeFiles/fmt.dir/src/format.cc.obj third_party/fmt/CMakeFiles/fmt.dir/src/os.cc.obj  && cd ."
C:\MinGW\bin\ld.exe: cannot find /lib: No such file or directory
C:\MinGW\bin\ld.exe: cannot find /nologo: No such file or directory
C:\MinGW\bin\ld.exe: cannot find /out:lib\libfmt.a: Invalid argument
third_party/fmt/CMakeFiles/fmt.dir/src/format.cc.obj: file not recognized: File format not recognized
[2/1312] Linking CXX static library lib\libjson11.a
FAILED: lib/libjson11.a
cmd.exe /C "cd . && C:\MinGW\bin\ld.exe /lib /nologo  /out:lib\libjson11.a third_party/json11/CMakeFiles/json11.dir/json11.cpp.obj  && cd ."
C:\MinGW\bin\ld.exe: cannot find /lib: No such file or directory
C:\MinGW\bin\ld.exe: cannot find /nologo: No such file or directory
C:\MinGW\bin\ld.exe: cannot find /out:lib\libjson11.a: Invalid argument
third_party/json11/CMakeFiles/json11.dir/json11.cpp.obj: file not recognized: File format not recognized
[6/1312] Building C object third_party/CMakeFiles/lua.dir/lua/ldebug.c.obj
ninja: build stopped: subcommand failed.
```
Using this cache instead : 
[CMakeCache.txt](https://github.com/aseprite/aseprite/files/4487762/CMakeCache.txt)

**Comment by Vanane** [comment]
It was DEFINITELY an issue with MinGW being chosen in place of Visual Studio's folders.

Now I've go another problem with specific header files, in which the compiler detects syntax errors :
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19748): error C2085: 'PSLIST_ENTRY' : ne figure pas dans la liste de paramètres formels
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19748): error C2143: erreur de syntaxe : absence de ';' avant '__cdecl'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19755): error C2143: erreur de syntaxe : absence de '{' avant '__cdecl'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19757): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'ListHead'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19757): error C2061: erreur de syntaxe : identificateur 'ListHead'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19757): error C2059: erreur de syntaxe : ';'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19758): error C2059: erreur de syntaxe : ')'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19762): error C2143: erreur de syntaxe : absence de '{' avant '__cdecl'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19764): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'ListHead'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19764): error C2061: erreur de syntaxe : identificateur 'ListHead'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19764): error C2059: erreur de syntaxe : ';'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19764): error C2059: erreur de syntaxe : ','
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19766): error C2059: erreur de syntaxe : ')'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19770): error C2143: erreur de syntaxe : absence de '{' avant '__cdecl'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19772): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'ListHead'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19772): error C2061: erreur de syntaxe : identificateur 'ListHead'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19772): error C2059: erreur de syntaxe : ';'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19772): error C2059: erreur de syntaxe : ','
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19776): error C2059: erreur de syntaxe : ')'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19780): error C2143: erreur de syntaxe : absence de '{' avant '__cdecl'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19782): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'ListHead'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19782): error C2061: erreur de syntaxe : identificateur 'ListHead'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19782): error C2059: erreur de syntaxe : ';'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19783): error C2059: erreur de syntaxe : ')'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19789): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'ListHead'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19789): error C2061: erreur de syntaxe : identificateur 'ListHead'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19789): error C2059: erreur de syntaxe : ';'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19790): error C2059: erreur de syntaxe : ')'
```

Sorry the messages are in french, but basically there is an error at every line, for misplaced semicolons, parenthesis or missing arguments.
Is there a way to resolve it ? Or maybe downloading a newer version of the file.

**Comment by Vanane** [comment]
Apparently it was only iconv.h that was missing from visual studio, and taking it from MinGW made the whole thing to have a bad syntax. Solution : take a random version of iconv.h on github !

**Comment by Jijiyaki** [comment]
Since I've been having similar issues, can you please tell me the path to where inconv.h is supposed to be? I want to check whether or not I have that file or not.

**Comment by Vanane** [comment]
I didn't hve this file in my Windows SDK nor visual studio folders, so I cloned it from a github repository, I think it was this one : https://github.com/LuaDist/libiconv/blob/master/include/iconv.h.in

**Comment by Jijiyaki** [comment]
So you git cloned that file, and you put it in the C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0 folder, and the compilation worked? What else did you do to solve the problem?

**Comment by ilnerdchuck** [comment]
> It was DEFINITELY an issue with MinGW being chosen in place of Visual Studio's folders.
> 
> Now I've go another problem with specific header files, in which the compiler detects syntax errors :
> 
> ```
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19748): error C2085: 'PSLIST_ENTRY' : ne figure pas dans la liste de paramètres formels
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19748): error C2143: erreur de syntaxe : absence de ';' avant '__cdecl'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19755): error C2143: erreur de syntaxe : absence de '{' avant '__cdecl'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19757): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'ListHead'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19757): error C2061: erreur de syntaxe : identificateur 'ListHead'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19757): error C2059: erreur de syntaxe : ';'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19758): error C2059: erreur de syntaxe : ')'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19762): error C2143: erreur de syntaxe : absence de '{' avant '__cdecl'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19764): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'ListHead'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19764): error C2061: erreur de syntaxe : identificateur 'ListHead'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19764): error C2059: erreur de syntaxe : ';'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19764): error C2059: erreur de syntaxe : ','
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19766): error C2059: erreur de syntaxe : ')'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19770): error C2143: erreur de syntaxe : absence de '{' avant '__cdecl'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19772): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'ListHead'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19772): error C2061: erreur de syntaxe : identificateur 'ListHead'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19772): error C2059: erreur de syntaxe : ';'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19772): error C2059: erreur de syntaxe : ','
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19776): error C2059: erreur de syntaxe : ')'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19780): error C2143: erreur de syntaxe : absence de '{' avant '__cdecl'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19782): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'ListHead'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19782): error C2061: erreur de syntaxe : identificateur 'ListHead'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19782): error C2059: erreur de syntaxe : ';'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19783): error C2059: erreur de syntaxe : ')'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19789): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'ListHead'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19789): error C2061: erreur de syntaxe : identificateur 'ListHead'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19789): error C2059: erreur de syntaxe : ';'
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(19790): error C2059: erreur de syntaxe : ')'
> ```
> 
> Sorry the messages are in french, but basically there is an error at every line, for misplaced semicolons, parenthesis or missing arguments.
> 
> This is probably the fault of MinGW, again. The problem is : I haven't got all the headers required on Visual Studio. There are some missing :x

How did you switch to the visual studio linker?

**Comment by ilnerdchuck** [comment]
> Update : I think there is an issue with my MinGW installation. CMake detects MinGW as the linker to use, instead of using Visual Studio's linker. I'm trying to compile again, with the right cache this time.

How did you switch linker? i have the same error of the upper message

`[185/1506] Building CXX object third_party/fmt/CMakeFiles/fmt.dir/src/format.cc.obj
FAILED: third_party/fmt/CMakeFiles/fmt.dir/src/format.cc.obj
C:\MinGW\bin\c++.exe  -DCMARK_STATIC_DEFINE -DNDEBUG -DPNG_NO_MMX_CODE -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/harfbuzz/src -I../third_party/giflib/lib -I../third_party/jpeg -Ithird_party/cmark -I../third_party/curl/include -I../third_party/simpleini -I../third_party/. -I../third_party/fmt/include -O2 -g -DNDEBUG   -std=c++11 -MD -MT third_party/fmt/CMakeFiles/fmt.dir/src/format.cc.obj -MF third_party\fmt\CMakeFiles\fmt.dir\src\format.cc.obj.d -o third_party/fmt/CMakeFiles/fmt.dir/src/format.cc.obj -c ../third_party/fmt/src/format.cc
In file included from ../third_party/fmt/src/format.cc:8:
../third_party/fmt/include/fmt/format-inl.h: In function 'void fmt::v6::vprint(FILE*, fmt::v6::string_view, fmt::v6::format_args)':
../third_party/fmt/include/fmt/format-inl.h:1367:13: error: '_fileno' was not declared in this scope
 1367 |   auto fd = _fileno(f);
      |             ^~~~~~~
[194/1506] Building CXX object third_party/fmt/CMakeFiles/fmt.dir/src/os.cc.obj
ninja: build stopped: subcommand failed.`

**Comment by ZackGabri** [comment]
The iconv.h file provided above, didn't really accomplish much progress for me, it still gave me the same errors, switching it with this one seems to have solved the issue
https://github.com/pffang/libiconv-for-Windows/blob/master/include/iconv.h

**Comment by Gokkul-Sigma-007** [comment]
> \10.0.18362.0

bro you git cloned and put it in which directory ? you mean this directory "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0" ????

**Comment by Gokkul-Sigma-007** [comment]
> The iconv.h file provided above, didn't really accomplish much progress for me, it still gave me the same errors, switching it with this one seems to have solved the issue https://github.com/pffang/libiconv-for-Windows/blob/master/include/iconv.h

bro you git cloned and put it in which directory ? you mean this directory "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0" ????

**Comment by odduck41** [comment]
I've tried all methods. They don't work for me. Finally, I downloaded it from torrent in 2 minutes💀

**Comment by Vanane** [comment]
My solution : 
Buy Aseprite for like 20 bucks, and never touch that damn Ninja build system ever again.

**Comment by odduck41** [comment]
> My solution : Buy Aseprite for like 20 bucks, and never touch that damn Ninja build system ever again.
I would like to. But in my country.. In general, I can't =(
