### ISSUE TITLE
Ninja.build doesn't load

### ISSUE THREAD

**Issue by MintStudios** [aseprite/aseprite#2340]
Can't compile skia, because it can't find build.ninja.

`C:\Users\mints\deps\skia>ninja -C out/Release-x64 skia modules
ninja: error: loading 'build.ninja': The system cannot find the file specified.

ninja: Entering directory `out/Release-x64'`

I have no idea how to fix this. 

### Aseprite and System version
* System: Windows 10

**Comment by dacap** [comment]
Hi there, it looks like the previous `gn` step failed.

**Comment by MintStudios** [comment]
Do you might know why?

**Comment by dacap** [comment]
We cannot know why because we need the output of the command. Check the Skia guide: https://github.com/aseprite/skia#skia-on-windows

After running `gn`:
```
gn gen out/Release-x64 --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false target_cpu=""x64"" cc=""clang"" cxx=""clang++"" clang_win=""c:\deps\llvm"" win_vc=""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC"" extra_cflags=[""-MT""]"
```

What is the output?

**Comment by MintStudios** [comment]
https://cdn.discordapp.com/attachments/527442700115509252/700697703390249080/unknown.png
Nothing

**Comment by ReddDevv** [comment]
im having this exact issue rn did you ever find a solution?

**Comment by haniissa** [comment]
for me it give this:
C:\deps\skia>gn gen out/Release-x64 --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false target_cpu=""x64"" cc=""clang"" cxx=""clang++"" clang_win=""c:\deps\llvm"" win_vc=""C:\Program Files\Microsoft Visual Studio\2022\Community\VC"" extra_cflags=[""-MT""]"
Done. Made 98 targets from 54 files in 1225ms

**Comment by haniissa** [comment]
and this is the error:
C:\deps\skia>ninja -C out/Release-x64 skia modules
ninja: error: '../../third_party/externals/harfbuzz/src/hb-aat-layout.cc', needed by 'obj/third_party/externals/harfbuzz/src/harfbuzz.hb-aat-layout.obj', missing and no known rule to make it
ninja: Entering directory `out/Release-x64'
