### ISSUE TITLE
Error when trying to compile Aseprite

### ISSUE THREAD

**Issue by Yolwoocle** [aseprite/aseprite#2352]
Hi, 
When trying to run the following command :
`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x64 -G Ninja ..`

I get this error message:

https://pastebin.com/Jh9Caqbx

Could someone help me with this? thanks.

* System: Windows 10.

**Comment by mistressonyx** [comment]
@Yolwoocle did you figure this out? I ran into the same issue and am stuck.

**Comment by Yolwoocle** [comment]
@mistressonyx I actually didn't, sorry
