### ISSUE TITLE
Crash creating a new sprite while there is a open sprite with shading tool

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#2372]
To reproduce this error:
1- create sprite (first sprite)
2- add more colors to the palette (2 or 3)
3- select _Pencil_ tool with _Shading Ink_
4- define a color range between the colors which you added in 2-
5- go to _File > New.._ and create a new sprite (second sprite)
6- It will crash

Reason:
Somehow, when we create the new sprite, the color palette range in _Shading Ink_ still has the indexes from the first sprite, so the _Shading Ink_ in the second sprite has an invalid color range (it has indexes out of bounds).

* Aseprite version: developer, post 1.2.18
* System: macOS Catalina

**Comment by dacap** [comment]
Hi @Gasparoken, actually it's fixed, but I'm not sure if I've uploaded the changes. Or I think it should be fixed. Let me upload the latest changes and give it a try again.

**Comment by dacap** [comment]
Check 6294ac74e0318d1de421c4b91e85ae315d4726cc, might be a possible fix for this issue.

**Comment by Gasparoken** [comment]
Thank you! I just update the master. You did fix it two days ago. Now, it works OK!

**Comment by dacap** [comment]
🙌
