### ISSUE TITLE
Recovered sprites don't contain user data

### ISSUE THREAD

**Issue by buckle2000** [aseprite/aseprite#2373]
**Bug Description***
Recovered sprites don't contain user data (on layers).

Also, once in a while handling large images (1024x1024) for a long time, the program will crash. How do I submit the crash logs?

### Aseprite and System version

* Aseprite version: 1.2.18
* System: Linux 5.6.10-arch1-1

**Comment by KashouC** [comment]
You can e-mail the crash logs to support@aseprite.org with a description with what happened or what you were doing during the crash (if you can).

If you don't know where to find them open Aseprite and click Edit -> Preferences -> Locate Crash Folder and send the latest Aseprite-Crash file.

**Comment by dacap** [comment]
Thanks for reporting this bug, we'll release a fix in the next release!

**Comment by buckle2000** [comment]
It is fixed
