### ISSUE TITLE
Newly built installation crashes when user interacts with anything else

### ISSUE THREAD

**Issue by pizzaforfree** [aseprite/aseprite#2374]
Aseprite v. 1.x dev, Win10, x64 build

Just cloned and built, today. The program seems to work fine until I interact with anything else on my computer, then it'll just silently crash. Crash dump gives exception error 0xC0000005. Dump is included here, as a zip file, as I don't actually know anything about software debugging.

[Aseprite-crash-1.x-dev.zip](https://github.com/aseprite/aseprite/files/4597036/Aseprite-crash-1.x-dev.zip)

**Comment by dacap** [comment]
Hi @pizzaforfree, unfortunately .dmp files from custom builds are useless for us, but if you double-click the file in your computer, and then click "Debug with Native only" on Visual Studio:

![debug](https://user-images.githubusercontent.com/39654/81409530-a6fa8c80-9115-11ea-92a0-0ec3b3d726bc.png)

Then a screenshot of the callstack could be useful for us:

![callstack](https://user-images.githubusercontent.com/39654/81409538-a9f57d00-9115-11ea-845c-4afb5f2db1fe.png)

![image](https://user-images.githubusercontent.com/39654/81409569-b8dc2f80-9115-11ea-96e3-a808b5b3f6e2.png)

Anyway generally we need more information (specific thread that crashes, maybe some values in the context of the crash). It's way too complex for people without programming/debugging experience.

**Comment by pizzaforfree** [comment]
I didn't actually do anything custom with the build, not that I wouldn't want to try to, though. Thanks for the info!
![call stack](https://user-images.githubusercontent.com/34205285/81418072-b972c700-9111-11ea-8d26-410e0b8f7b5b.png)
The crash seems to happen at line 677 in window .cpp, This is what VS says about it: 

> Unhandled exception at 0x0000000000000000 in Aseprite-crash-1.x-dev.dmp: 0xC0000005: Access violation executing location 0x0000000000000000.

**Comment by dacap** [comment]
> I didn't actually do anything custom with the build

Actually it doesn't depend on any change, it's something related to that a .dmp file is related to the exact .exe, its related .pdb, and the source code used in the build (each build is a unique build and all these files are needed to use the .dmp).

Anyway the stacktrace was useful. It looks like the `api.overlap(m_hpenctx, ...)` call is failing, but it might be related to that `m_hpenctx = nullptr` maybe checking that will fix the issue. If I upload a fix to `master`, could you give it a try?

**Comment by dacap** [comment]
I've uploaded a possible fix in master branch (6e4b96f548cc30b9c77b59b48d7659eaa4fe48a6) you will need to update submodules after pulling that commit:
```
git pull
git submodule update --init --recursive
```

**Comment by pizzaforfree** [comment]
Yeah, I can try it. I'll need to rebuild, I assume? I'm not too experienced with github and software dev and testing.

**Comment by pizzaforfree** [comment]
It works!

**Comment by dacap** [comment]
I'm so glad to hear that! Thank you for reporting this issue and for your help finding the bug! 🥳

**Comment by pizzaforfree** [comment]
No problem, I'm glad to help!
