### ISSUE TITLE
tcc build fails

### ISSUE THREAD

**Issue by theamazingwaffle** [aseprite/aseprite#2377]
Apparently, tiny c compiler isn't able to build a "simple program".  
Gosh okay, no need to be so dense, CMake.

```
  The C compiler

    "/usr/bin/tcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/pavel/.cache/yay/aseprite/src/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/ninja cmTC_fd131 && [1/2] Building C object CMakeFiles/cmTC_fd131.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_fd131
    FAILED: cmTC_fd131
    : && /usr/bin/tcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now CMakeFiles/cmTC_fd131.dir/testCCompiler.c.o  -o cmTC_fd131   && :
    tcc: error: unsupported linker option '-O1,--sort-common,--as-needed,-z,relro,-z,now'
    ninja: build stopped: subcommand failed.
```
### Aseprite and System version

* Aseprite version: error while loading shared libnettle library, hence recompiling
* System: Arch linux, kernel version: 5.6.11-arch1-1

Unrelated: why not statically link aseprite? Is there a build option to do that?

**Comment by dacap** [comment]
Actually we support gcc, clang, and msvc only. Also I'm not sure, but I think tiny c is just a c compiler (not a C++ compiler).
