### ISSUE TITLE
Cant compile aseprite

### ISSUE THREAD

**Issue by Hashtop** [aseprite/aseprite#2378]
I'm trying to do the last command: `ninja aseprite` in the `C:\aseprite\build` folder, but it gives this 
error `ninja: error: unknown target 'aseprite'`

I have successfully executed the cmake line and everything went well when i was installing the skia library.

I have all the aseprite deps installed and the latest version of Visual Studio 2017.

**Comment by enderger** [comment]
Did you remember to use cmake first?
