### ISSUE TITLE
Make different CLI documentations up to date

### ISSUE THREAD

**Issue by buckle2000** [aseprite/aseprite#2384]
man page, --help, webpage should be up to date with each other. Ideally, they should be automatically generated from one source.

For example, #2367 is documented [here](https://www.aseprite.org/docs/cli/#filename-format) but not in `aseprite --help`.

Also, there is no man page right now. I want one.

### Aseprite and System version

* Aseprite version: 1.2.18-dev

**Comment by buckle2000** [comment]
You may make https://github.com/aseprite/docs/ a git submodule on `docs/` and use something like [ronn](https://rtomayko.github.io/ronn/ronn.1) to generate man pages from markdown files.

**Comment by dacap** [comment]
Just in case, there are no plans to distribute a man page.

**Comment by buckle2000** [comment]
Can I add a man page?

**Comment by dacap** [comment]
Sorry, but if you add a man page then it will have to be continuously maintained and kept in sync with the -help and docs pages (which already are hard to kept updated and on sync).

Also you have to think that a man page would benefit a small portion of user (Linux users represent 1% of our users, and actually you are the first user asking for a man page), we are not planning to add another point of maintenance. Sorry.

**Comment by buckle2000** [comment]
I already made a man page generator. https://github.com/buckle2000/aseprite
