### ISSUE TITLE
null bytes in DebugOutput.txt 

### ISSUE THREAD

**Issue by buckle2000** [aseprite/aseprite#2385]
There are many null bytes in this text file produced from `aseprite --debug`. (It is the same crash file from #2382 .)
[Aseprite-v1.2.18-dev-DebugOutput.txt](https://github.com/aseprite/aseprite/files/4629287/Aseprite-v1.2.18-dev-DebugOutput.txt)

Only some lines are terminated with `\n\0`. Weird.

### Aseprite and System version

-    Aseprite version: 1.2.18-dev
-    System: Arch Linux 5.6.8-arch1-1

**Comment by dacap** [comment]
Actually this should be fixed with this `laf` commit:
https://github.com/aseprite/laf/commit/c2129cf5d67cbc8e031f2c394b0664f4423ad41e

Please give a try to the `master` branch.

**Comment by buckle2000** [comment]
It's fixed!
