### ISSUE TITLE
ninja: error: unknown target 'modules'

### ISSUE THREAD

**Issue by spazmantiz** [aseprite/aseprite#2400]
i following the instruction carefuly and using all dependencies but still get error
when i run in my **~/deps/skia/**

```terminal
~/deps/skia$ 'ninja -C out/Release-x64 skia modules'
ninja: Entering directory `out/Release-x64'
ninja: error: unknown target 'modules
```

* Ninja version : 1.8.2
* System: Xubuntu 20.04

**Comment by spazmantiz** [comment]
nevermind i was using the wrong skia branch

**Comment by SmashBoii** [comment]
> nevermind i was using the wrong skia branch

What do you mean by wrong skia branch? I'm stuck on the same part :((

**Comment by spazmantiz** [comment]
> > nevermind i was using the wrong skia branch
> 
> What do you mean by wrong skia branch? I'm stuck on the same part :((

are you using skia aseprite-m81 ??
