### ISSUE TITLE
Movable Timeline window

### ISSUE THREAD

**Issue by flamendless** [aseprite/aseprite#2412]
Hi, it would be useful for small monitor to be able to move the position of the timeline window to the left or to the right.

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KashouC** [comment]
This is already possible if you click this button in the timeline.

![image](https://user-images.githubusercontent.com/17066488/83237499-4b13a880-a195-11ea-8e62-392607e2720e.png)

**Comment by flamendless** [comment]
Oh. I didn't know about that. Thanks!
