### ISSUE TITLE
Why does the EULA prohibit reverse engineering/decompilation/disassembly?

### ISSUE THREAD

**Issue by flarn2006** [aseprite/aseprite#2413]
I mean, usually that provision is there because the company doesn't want people modifying the software or discovering how it works. But publishing the source code means you have no problem with that, and in fact the license explicitly permits source modifications for personal use. Why do you care if someone examines your pre-compiled binaries? What would anyone even accomplish by doing that, that they couldn't accomplish much more efficiently using the source code?

Don't get me wrong, I think it's great that you've decided to share the source code, and I don't mean to imply that's not good enough or anything of the sort. It just seems silly to me to have that provision there, and I'm curious what the reason is for its existence. I'm clearly missing something, and I'm simply wondering what that missing piece is.

**Comment by dacap** [comment]
Hi @flarn2006, as you know this is a generic clause in EULAs, at the moment it doesn't make too much sense, but it has some benefits:

1. As binaries for Windows and macOS are signed by us, this clause is a way to say "modifying the binary code that was released and signed by us is against the EULA" (e.g. modifications to the binary between you and us, e.g. an extreme case would be if some platform that we use to distribute binaries decide to start patching binaries in the middle)
2. In the future we might include some private information in the code (e.g. a way to encrypt a key to automatic update the program, or a way to communicate with the #1928)
3. Possible parts of the code (mainly for touch devices) might be closed (e.g. we've to start working on the design of the iPad port, that will not be open sourced, so some of those parts might be in the desktop version in the long run)
