### ISSUE TITLE
Maximum size being previewed for pressure sensitivity causes visibility issues

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#2419]
If you have the maximum brush size set to like 10 or 20, while the minimum is at 1, it causes large visibility problems because the preview will cover so much space, since it's now determined by maximum brush size, also making it impossible to tell where the stroke will begin.

**Comment by dacap** [comment]
Hi @KashouC, yes, it's a problem I've noticed too. A workaround is using the "brush edges":

![image](https://user-images.githubusercontent.com/39654/83436880-13b32f00-a415-11ea-97d5-a2e4bd84d1e0.png)

I think we could easily fix this issue using the minimum brush size when the dynamics for brush size is on.
