### ISSUE TITLE
Linux Compilation Failure on Recent Versions

### ISSUE THREAD

**Issue by dpacbach** [aseprite/aseprite#2420]
Hi,
I build my own Aseprite and Skia-Aseprite on linux and that has always worked for me.  However, when updating to the most recent version, I am now getting a compilation error:

```
In file included from ../laf/os/skia/resize_surface.h:12,
                 from ../laf/os/skia/skia_window_x11.h:14,
                 from ../laf/os/skia/skia_window.h:16,
                 from ../laf/os/skia/skia_display.h:15,
                 from ../laf/os/skia/skia_system.h:16,
                 from ../laf/os/skia/os.cpp:11:
../laf/os/skia/skia_surface.h:28:10: fatal error: include/private/SkColorData.h: No such file or directory
   28 | #include "include/private/SkColorData.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I updated my build commands with the latest ones from the `INSTALL.md` file but same error.  The skia that I built actually contains `include/private/SkColorData.h` in it but it is in `src/core` folder instead of `include/private`.  Moving the file to `include/private` then just seems to yield other errors, so I figure that is not the right fix.  Can someone help?  If you need any other info about my setup/system let me know.

**Comment by dacap** [comment]
Hi there @dpacbach check if your skia compilation isn't out dated, because we have moved on Skia m81.

**Comment by dpacbach** [comment]
@dacap Ok thanks I have updated to Skia m81 which built successfully.   But then when I build Aseprite the CMake finishes successfully, and it gets about half way through the build, then I get this error:

```
/usr/bin/c++  -O2 -g -DNDEBUG  -rdynamic laf/examples/CMakeFiles/panviewport.dir/panviewport.cpp.o  -o bin/panviewport  lib/liblaf-os.a  lib/liblaf-gfx.a  lib/liblaf-ft.a  lib/liblaf-base.a  lib/libmodpbase64.a  -ldl  lib/libfreetype.a  lib/libharfbuzz.a  lib/libfreetype.a  lib/libharfbuzz.a  lib/libpng16.a  lib/libz.a  -lm  -lpthread  -lSM  -lICE  -lX11  -lXext  -lXcursor  /home/dsicilia/dev/tools/skia-aseprite-m81/out/Release/libskia.a  -lGL  -lfontconfig  -lSKSHAPER_LIBRARY-NOTFOUND && :
/usr/bin/ld: cannot find -lSKSHAPER_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
```

So it looks like it is trying to link against the `skshaper` library but CMake did not find it.  Actually, I cannot find it myself either.  I checked in the Skia m81 build area and I don't see any SkShaper libraries.  I do see some source files:

```
~/de/to/skia-aseprite-m81: find | ag skshaper
./src/utils/SkShaperJSONWriter.cpp
./src/utils/SkShaperJSONWriter.h
./modules/skshaper
./modules/skshaper/BUILD.gn
./modules/skshaper/skshaper.gni
./modules/skshaper/src
./modules/skshaper/src/SkShaper_primitive.cpp
./modules/skshaper/src/SkShaper_harfbuzz.cpp
./modules/skshaper/src/SkShaper_coretext.cpp
./modules/skshaper/src/SkShaper.cpp
./modules/skshaper/include
./modules/skshaper/include/SkShaper.h
./out/Release/obj/src/utils/libskia.SkShaperJSONWriter.o
./out/Release/obj/modules/skshaper
./out/Release/obj/modules/skshaper/skshaper.ninja
./tests/SkShaperJSONWriterTest.cpp
```

By the way, here is my CMake command that I'm using:

```sh
cmake .. -DSKIA_DIR=$skia_m81                          \
         -DSKIA_LIBRARY_DIR=$skia_m81/out/Release      \
         -DCMAKE_INSTALL_PREFIX="$prefix"              \
         -DLAF_BACKEND=skia                            \
         -DCMAKE_BUILD_TYPE=RelWithDebInfo             \
         -DSKIA_OUT_DIR=$skia_m81/out/Release          \
         -G Ninja
```

Can you tell me if there is something wrong with my Skia build and/or my CMake build?  I am basically using the same procedure to build Skia and Aseprite that I've been using for a while... has anything changed in the build procedures for either of those?  Thanks

**Comment by dpacbach** [comment]
Ok so after some more debugger I have fixed the issue with `libskshaper.a`.  The problem was that, when building Skia, I was using `ninja -C out/Release skia` when it should be `ninja -C out/Release all`.

So now the Aseprite build progresses past that point, but now I am getting a bunch of (linker) errors later in the process that all look like the following:

```
FAILED: bin/helloworld
: && /usr/bin/c++  -O2 -g -DNDEBUG  -rdynamic laf/examples/CMakeFiles/helloworld.dir/helloworld.cpp.o  -o bin/helloworld  lib/liblaf-os.a  lib/liblaf-gfx.a  lib/liblaf-ft.a  lib/liblaf-base.a  lib/libmodpbase64.a  -ldl  lib/libfreetype.a  lib/libharfbuzz.a  lib/libfreetype.a  lib/libharfbuzz.a  lib/libpng16.a  lib/libz.a  -lm  -lpthread  -lSM  -lICE  -lX11  -lXext  -lXcursor  /home/dsicilia/dev/tools/skia-aseprite-m81/out/Release/libskia.a  -lGL  -lfontconfig  /home/dsicilia/dev/tools/skia-aseprite-m81/out/Release/libskshaper.a && :
/usr/bin/ld: /home/dsicilia/dev/tools/skia-aseprite-m81/out/Release/libskia.a(typeface_freetype.SkFontHost_FreeType.o): undefined reference to symbol 'FT_Get_MM_Var'
/usr/bin/ld: /lib/x86_64-linux-gnu/libfreetype.so.6: error adding symbols: DSO missing from command line
```

I believe this means that the libraries are not in the right order on the linker command line.  Specifically, in this case, `libskia.a` needs symbols from freetype, but `lib/libfreetype.a` comes before it in the command line.  I reran the above linker command adding an additional `lib/libfreetype.a` at the end of the linker line, and then the command succeeded, so it looks like there is a problem with how CMake is generating linker commands.  Any idea on how to fix this?

**Comment by dpacbach** [comment]
I was able to work around the above issue by adding the following to my Aseprite command line:

```cmake
  -DLAF_WITH_EXAMPLES=OFF
  -DLAF_WITH_TESTS=OFF
```

and that finally allows me to build Aseprite.  So I will close this for now, but perhaps there is a Linux build issue with `laf` that should be looked at?

**Comment by spaderthomas** [comment]
I was building on Arch Linux, and I encountered the same DSO error. Indeed, it's an error with how CMake generates the command line. CMake had detected my `libfreetype` install at `/usr/local/lib/libfreetype.a`. I'm not sure where this came from, but adding an additional one before skia didn't help. What did help was pointing it to my official freetype installation (from pacman) in /usr/lib/libfreetype.so. I'm not sure why it wouldn't work with a static library, or if the problem was that the one in `local` was out of date somehow. But it fixed it.

The joys of Linux.

Juts going to signal boost this for searchers in the future, since this symbol is what is failed at: FT_Get_Color_Glyph_Layer. DSO missing from command line.
