### ISSUE TITLE
The timeline layer/frame separator can be dragged off screen

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#2436]
The width of the layer name should probably be limited to the size of the window so that we can always fix it without too much hassle.

![timeline separator outside screen fix](https://user-images.githubusercontent.com/17066488/84396655-b2eada00-abfe-11ea-991f-82c69bda54e4.gif)

**Comment by dacap** [comment]
Thanks @KashouC, noticed something similar in these days, going to fix it ASAP 👍
