### ISSUE TITLE
{title} and {name} not working properly

### ISSUE THREAD

**Issue by atiupin** [aseprite/aseprite#2442]
I'm trying to use Aseprite CLI like this:
```
ASEPRITE_PATH -b ASSETS_SRC_PATH/*.* --save-as ASSETS_OUT_PATH/{title}.png`
```

Expected result: `asset.aseprite -> asset.png`

Actual result: `asset.aseprite -> {title}.png`

Also, it seems like it duplicates parts of filename. For example, I've tried this format: `a-{title}-b.png`

Expected result: `asset.aseprite -> a-asset-b.png`

Actual result: `asset.aseprite -> a-a-{title}-b-b.png`

### Aseprite and System version

* Aseprite version: 1.2.20 / Steam
* System: macOS Catalina 10.15.4

**Comment by dacap** [comment]
Hi @alextewpin, please check this post:

https://community.aseprite.org/t/1-2-21-x64-cli-title-does-not-export-correctly/6231
