### ISSUE TITLE
[Suggestion] Warn users that MinGW can interfere with the build process

### ISSUE THREAD

**Issue by CaptainKraft** [aseprite/aseprite#2449]
After many failed attempts, and quite a bit of searching for an answer, I finally discovered that MinGW was interfering with CMake and/or Ninja during the build process. Removing C:\MinGW resolved the issue, but it took a lot of headaches to get to that conclusion.

It would be nice if there were a small note in INSTALL.md to let people know that this might be the cause of their building issues. Here is an example of others with the same problem: https://community.aseprite.org/t/compilation-problem-on-windows/5803

Otherwise, it would be helpful to add some instructions on how we can avoid this problem while also leaving MinGW on our machines.

**Comment by dacap** [comment]
I've pushed a note about this and a link to this issue, any extra information can be added to this same issue as a comment.

**Comment by PureAsbestos** [comment]
@dacap It's not just that it's not supported, just having it installed can cause the build to fail. The solution is to add the cmake option to ignore it, `-DCMAKE_IGNORE_PATH=YourPathHere` (replacing YourPathHere with your mingw install location, e.g. `D:\msys64\mingw64\bin\`). This happens because cmake will use gcc by default if it is on path.

**Comment by dacap** [comment]
Yeah, I know. But I didn't know about the `-DCMAKE_IGNORE_PATH` option, which can make it easier to ignore MinGW. Will add this info in the INSTALL.md

**Comment by Gokkul-Sigma-007** [comment]
i removed the mingw completely and yet its showing me this error when i run this in cmd "C:\aseprite\build>cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x64 -DSKIA_LIBRARY=C:\deps\skia\out\Release-x64\skia.lib -G Ninja .." it gives me this error inspite of removing mingw completely . the error message :"-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:23 (project):
  The CMAKE_C_COMPILER:

    C:/MinGW/bin/gcc.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:23 (project):
  The CMAKE_CXX_COMPILER:

    C:/MinGW/bin/c++.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH."
