### ISSUE TITLE
ARM Macs

### ISSUE THREAD

**Issue by theParadox42** [aseprite/aseprite#2451]
Apple is moving to ARM MacBooks. Will Rosetta 2 take care of this, will skia or some other dependency need to update, or is it just a simple “recompile for Universal 2.”

**Comment by dacap** [comment]
Hi there, as the announcement was today -and ARM MacBooks are not available yet to the public- we have no idea. I think this will be completely transparent and future version of Aseprite will be compiled as Universal 2.

**Comment by theParadox42** [comment]
Awesome! I know this isn’t really needed to worry about yet but glad to see it will eventually be supported. I myself am quite curious how developers will do the transitioning.

**Comment by dacap** [comment]
It looks like [Apple will send patches](https://twitter.com/MarkVillacampa/status/1275200446764912643) some open source projects (including Skia, which makes really intensive use of clang/llvm/x86_64 optimizations). We'll see what are those changes but it's highly probable that we'll need to upgrade the Skia branch to a new version this same year.

**Comment by ryandesign** [comment]
Good news: Aseprite 1.2.25 builds fine for me on the Apple Silicon developer test kit machine. But I am using my own copies of many of the dependencies rather than the ones you bundle. You may need to update the dependencies you bundle, for example curl (see https://community.aseprite.org/t/compile-on-macos-catalina-does-not-go-past-the-cmake-stage/6527). A good first step toward being Apple Silicon compatible is being Xcode 12 compatible on an Intel Mac.

**Comment by dacap** [comment]
@ryandesign nice to hear that, we weren't able to get one of those Kits (we're living in Argentina, and it wasn't available for our country). I'll try to update all submodules/third-party dependencies as much as I can for the next release.

**Comment by godknowsiamgood** [comment]
> I was already able to compile a M1 version of Aseprite, we have to investigate how to bundle both binaries in the same .dmg in the whole building pipeline, but it's going something quite similar to the .exe installer (which includes 32-bit and 64-bit versions of Aseprite).

Why not provide two separate dmg files? As any other software do.

**Comment by dacap** [comment]
> Why not provide two separate dmg files? As any other software do.

Oh yeah, it's not a bad idea and a lot easier. I'll check if I can cross-compile from Intel -> M1 to automate the build process and maybe upload a version this same week.

**Comment by heitzes** [comment]
When it will be available on M1 mac? Hard to wait 😂

**Comment by ryandesign** [comment]
> Why not provide two separate dmg files? As any other software do.

While that would be possible, it is certainly not what "any other software do". On the contrary, most software for macOS that can run on several different platforms is distributed as a "universal binary" which contains multiple architectures within a single application bundle. This is what Mac users expect and what software developers should strive to provide.

**Comment by godknowsiamgood** [comment]
> > Why not provide two separate dmg files? As any other software do.
> 
> While that would be possible, it is certainly not what "any other software do". On the contrary, most software for macOS that can run on several different platforms is distributed as a "universal binary" which contains multiple architectures within a single application bundle. This is what Mac users expect and what software developers should strive to provide.

Agree, that would be convenient, but from personal user experience more often I see this :)
![image](https://user-images.githubusercontent.com/5710885/140474853-28e6b845-fe76-41df-b91f-90483585f9bf.png)

**Comment by dacap** [comment]
I think both methods are ok: a universal dmg would be better for the user so there is no possibility to be wrong, but having two dmg bundles is a good alternative (and I saw the same solution offered as in Chrome).

**Comment by DuelPyro** [comment]
Out of curiosity, are the install.md instructions up to date for building on M1 then? And if not, what do you do differently compared to the x86 builds?

**Comment by dacap** [comment]
@DuelPyro it looks like we cannot use the m81 Skia version as arm64 is not compiling the arm64 version for M1 actually. I'm giving a try to update Skia to the latest version and see if we can compile the native M1 version from there.

**Comment by dacap** [comment]
If you have a native M1 machine, you can compile the arm64 version, compiling Skia for arm64, with something like:

```
gn gen out/Release-arm64 --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false target_cpu=\"arm64\" extra_cflags=[\"-stdlib=libc++\", \"-mmacosx-version-min=11.0\"] extra_cflags_cc=[\"-frtti\"]"
ninja -C out/Release-arm64 skia modules
```

And then Aseprite with:

```
      -DCMAKE_OSX_ARCHITECTURES=arm64 \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
      ...
      -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-arm64 \
      -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-arm64/libskia.a \
```

As far as I know, it doesn't work for cross-compiling (e.g. compiling the arm64 from x86_64 native), which is something I'm trying to achieve.

**Comment by kevinfaveri** [comment]
hey @dacap tried a lot building from source or using macport and everything throws random errors one after another lol 
is there a ETA for having the Macos build for Apple Silicon on the paid version? So I can organize myself to buy it when ready

**Comment by ryandesign** [comment]
@kevinfaveri It has been building fine for me on Apple Silicon in MacPorts for over a year. If it doesn't build for you in MacPorts, please [file a bug report](https://trac.macports.org/newticket) and I'll investigate.

**Comment by kevinfaveri** [comment]
Done https://trac.macports.org/ticket/64103

**Comment by dacap** [comment]
Just as a side note, Steam doesn't offer different packages between x64 and arm64 architectures, and their `libsteam_api.dylib` is an [universal binary since 1.52](https://store.steampowered.com/news/?emclan=103582791433666425&emgid=2984186817523157398:

> Added i386/x86_64/arm64 universal builds of libsdkencryptedappticket.dylib and libsteam_api.dylib

So maybe they don't have plans to make available different packages for x64 and arm64 (as they do on Windows for x86 vs x64). So the arm64 version of Aseprite on Steam/macOS must be published as a universal binary.

**Comment by dacap** [comment]
Next version will include an universal binary with both (x86_64 + arm64) versions in the .app bundle.
