### ISSUE TITLE
Add information about necessary Visual Studio components that need to be installed.

### ISSUE THREAD

**Issue by pedrozaalex** [aseprite/aseprite#2455]
When I was building, I had to download Visual Studio, but it didn't occur to me that I needed to select the C++ components during installation. Or maybe add some information about needing to have gcc installed. Just a minor improvement to the building tutorial.

**Comment by dacap** [comment]
Hi @pedrozaalex, actually the INSTALL.md includes a comment about that in the [Windows dependencies section](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#windows-dependencies):

> * Windows 10 (we don't support cross-compiling)
> * [Visual Studio Community 2019](https://visualstudio.microsoft.com/downloads/) (we don't support [MinGW](#mingw))
> * The [Desktop development with C++ item + Windows 10.0.18362.0 SDK](https://imgur.com/a/7zs51IT)
  from the Visual Studio installer

**Comment by pedrozaalex** [comment]
Oh right, I missed that lol. Thanks for the correction and also thank you so so much for releasing this, I'm loving aseprite and will be buying it as soon as I get some money.
