### ISSUE TITLE
[Aseprite Compiling] Cmake/skia problem

### ISSUE THREAD

**Issue by MakeGamer** [aseprite/aseprite#2466]
**I followed a [tutorial ](https://www.youtube.com/watch?v=WKeNJh_gIJU)how to compile Aseprite. And I had following error typing:** 
`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x64 -G Ninja ..`

**And the error was:**
```
CMake Error at laf/CMakeLists.txt:84 (message):
  set SKIA_DIR/SKIA_LIBRARY/SKIA_LIBRARY_DIR to compile w/skia backend


-- Configuring incomplete, errors occurred!
See also "C:/aseprite/build/CMakeFiles/CMakeOutput.log".
See also "C:/aseprite/build/CMakeFiles/CMakeError.log".
```
**I also attached the Output and Error log!**
[CMakeError.log](https://github.com/aseprite/aseprite/files/4944949/CMakeError.log)
[CMakeOutput.log](https://github.com/aseprite/aseprite/files/4944950/CMakeOutput.log)

### Aseprite and System version

* Aseprite version: 1.2.21, Source
* System: Windows 10, Version 1909 (OS Build 18363.959)

**Comment by kinnngg** [comment]
I also got a similar error? Any process if you made?

**Comment by eddex** [comment]
Same issue here, have you found a solution @kinnngg?
