### ISSUE TITLE
How to IMPORT spritesheets that have a the same structure with the same animation tags?

### ISSUE THREAD

**Issue by jestarray** [aseprite/aseprite#2487]
RPG maker sprites have the exact same structure for every sprite: 
![image](https://user-images.githubusercontent.com/34615798/90193751-75c7d300-dd7a-11ea-8c64-c8badd70243e.png)

I want thinking that I set up the tag animations for just 1 of them, export the data as json, and IMPORT that into aseprite for all the other ones since the structure of all of these spritesheets are the same.

I am assuming this is just not documented since the readme says:
* Export/import animations to/from sprite sheets, GIF files, or sequence of PNG files (and FLC, FLI, JPG, BMP, PCX, TGA).

I couldn't figure from the docs how to use the CLI to import settings from the json data file. Do I have to write a lua script for this?! It should be baked into the CLI imho

**Comment by jestarray** [comment]
so I'm trying to write a lua script for import functionality and it seems that the command:
```app.command.NewFrameTag{}```
does not take any parameters...

here is the gui.xml file:
```
   <menu text="@.frame_tags">
          <item command="FrameTagProperties" text="@.frame_tags_tag_properties" />
          <separator />
          <item command="NewFrameTag" text="@.frame_tags_new_tag" />
          <item command="RemoveFrameTag" text="@.frame_tags_delete_tag" />
        </menu>
```
and the source code doesn't seem to use ```params.get()``` anywhere.

https://github.com/aseprite/aseprite/blob/master/src/app/commands/cmd_new_frame_tag.cpp

**Comment by dacap** [comment]
Hi @jestarray, you can use [Sprite:newTag()](https://github.com/aseprite/api/blob/master/api/sprite.md#spritenewtag) to create a new tag.

**Comment by jestarray** [comment]
@dacap thanks it works! one last question, this keeps popping up:
![image](https://user-images.githubusercontent.com/34615798/90448667-af5e4e00-e09a-11ea-95f2-e44d7a471ecb.png)

I'm never going to be writing to the json file but it keeps nagging me that it exists and overwriting it. Is there a way to turn this off? Here is my code:
```
local dlg = Dialog()
dlg:file{ id="picker",
          label="select animation data file(json)",
          title="animimation",
          load=true,
          open=false,
          save=false,
          filename="",
          filetypes={ "json" },
          onchange=function() end
}:show()
```
I tried every combination of turning open/save to true and false but no luck.

**Comment by jestarray** [comment]
Closing! thanks for the help, managed to write a script to import tags and durations: https://github.com/jestarray/aseprite-scripts
