### ISSUE TITLE
Compiling aseprite on mac but getting it as a unix executable instead.

### ISSUE THREAD

**Issue by c-21-android** [aseprite/aseprite#2492]
I've been following the instructions to compile aseprite on macOS. However, what I get is a unix executable instead of an app/dmg. this unix executable does work but it seems weird to have a unix executable instead of a app/dmg file. I wonder if this is normal or not?

**Comment by sirpanino** [comment]
I've deal with this issue myself when compiling another open source project. It only makes the binary, not the folder structure of a macOS .app
You can create one yourself by just making the correct folder structure like so:
aseprite.app
    - Contents
        - MacOS
                - <aseprite binary goes here (make sure the binary is only called "aseprite"!)>

**Comment by c-21-android** [comment]
Thank you it works! Do you have any tips on how to make the aseprite icon appear instead of the default .app icon?

**Comment by dacap** [comment]
Hi @c-21-android and @sirpanino, the best way to obtain a similar Aseprite.app is downloading the trial Aseprite.app from the website https://www.aseprite.org/trial/ for macOS an replace the aseprite binary in `Aseprite.app/Contents/MacOS/aseprite`

**Comment by c-21-android** [comment]
Thank you @dacap it works!

**Comment by D-T-666** [comment]
tried that but it gives me this error. I think it might be related to relative importing from `data/`?

<img width="292" alt="image" src="https://user-images.githubusercontent.com/35934791/167300786-e2de18e9-e0e9-476b-a045-9cf735d3b728.png">

**Comment by srolfe** [comment]
> I get this error when opening the app bundle
> 
> `“Aseprite” is damaged and can’t be opened. You should move it to the Trash.`
> 
> Might be related to code signature?
> 
> Edit: It is due to the location of the executable file. It seems to work only from the `build/bin/` folder. If anybody know a work around, I would appreciate it

I think it has to do with one of the extended attributes on the .app. I was able to workaround this with:

`xattr -d com.apple.quarantine Aseprite.app 
xattr -d com.apple.provenance Aseprite.app`

**Comment by srolfe** [comment]
> I get this error when opening the app bundle
> 
> `“Aseprite” is damaged and can’t be opened. You should move it to the Trash.`
> 
> Might be related to code signature?
> 
> Edit: It is due to the location of the executable file. It seems to work only from the `build/bin/` folder. If anybody know a work around, I would appreciate it

You'll also need to remove the quarantine extended attribute on the .app after replacing the binary:

`xattr -d com.apple.quarantine Aseprite.app`

**Comment by srolfe** [comment]
> I get this error when opening the app bundle
> 
> `“Aseprite” is damaged and can’t be opened. You should move it to the Trash.`
> 
> Might be related to code signature?
> 
> Edit: It is due to the location of the executable file. It seems to work only from the `build/bin/` folder. If anybody know a work around, I would appreciate it

You'll also need to remove the quarantine extended attribute on the .app after replacing the binary:

`xattr -d com.apple.quarantine /Applications/Aseprite.app`

**Comment by srolfe** [comment]
> I get this error when opening the app bundle
> 
> `“Aseprite” is damaged and can’t be opened. You should move it to the Trash.`
> 
> Might be related to code signature?
> 
> Edit: It is due to the location of the executable file. It seems to work only from the `build/bin/` folder. If anybody know a work around, I would appreciate it

I encountered this same issue and it can be avoided by launching the trial before replacing the binary.

You can also use this to remove the quarantine extended attribute from the .app if you replaced it first:

`xattr -d com.apple.quarantine /Applications/Aseprite.app`
