### ISSUE TITLE
Intuos Pro S long freeze after touching pen to tablet

### ISSUE THREAD

**Issue by IoriBranford** [aseprite/aseprite#2498]
When either end of the pen touches the tablet, Aseprite becomes unresponsive for about a minute. Inputs are queued until Aseprite is responsive again.

When it happens at the welcome screen, the mouse cursor can still move. It can't if a document is open.

This happens when the tablet interface is Wintab, with or without direct packet processing.
Setting it to "Windows 8/10 Pointer API (Windows Ink)" makes the tablet function as a mouse, avoiding the problem but losing pressure sensitivity.
Wacom pen setting "Use Windows Ink" makes no difference.

### Aseprite and System version

* Aseprite version: v1.2.25-x64 installer
* System: Windows 7 64bit Ultimate
* Tablet driver: 6.3.38-2 (latest)

[Aseprite-v1.2.25-x64-DebugOutput.txt](https://github.com/aseprite/aseprite/files/5113715/Aseprite-v1.2.25-x64-DebugOutput.txt)

**Comment by dacap** [comment]
Hi @IoriBranford! Just in case, what canvas size are you trying to edit, does it always happen (or just in the first stroke)? It's strange that it happens only in the sprite editor and not in other widget, does it happen in a text widget? E.g. does it present a delay if you try to select a range of text in Sprite > Properties > File name:

![image](https://user-images.githubusercontent.com/39654/91046550-01e5c000-e5ef-11ea-85fb-7b67d48c9001.png)

**Comment by IoriBranford** [comment]
The issue has stopped.
I remember now, the Windows Ink window was active when it occurred. I think the "Use Windows Ink" setting is not applied until next boot. Now, using the pen does not show the Windows Ink window and works perfectly.

**Comment by dacap** [comment]
Glad to hear that it's working now 👍  (in other case I was a little lost 😅 ), I'm going to close this issue now but future comments can be made.
