### ISSUE TITLE
Mirror selected pixel translations in Symmetry Mode.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#2509]
I would be amazed to discover that this has not been reported yet but it would be really great if Symmetry Mode would also mirror selection translations, if not all transformations.

There are probably going to be a lot of problems to solve with this one, even with something basic like mirrored translations (for instance, what happens when translated pixels cross an axis of symmetry, and what happens if they cross into selected pixels on the opposite side of the symmetry axis?), and this may be the reason why there has been no solution so far.

Still, since my admittedly shallow, cursory search for anything similar did not discover any open issues, I am posting it, that it may potentially be solved in the future. ;) 

Thanks for considering it! :D 
..using ASEprite 1.2.25-x86 on Win10.

**Comment by oceanhahn** [comment]
Incidentally, symmetry _transformations_ may require a considerable revision to the way transformations work in general (or at least in Symmetry Mode), since selections would require transform handles local to their Symmetry half/quadrant, and should reproduce a corresponding, mirrored change on the opposite side or sides.

Also, selections made **outside of Symmetry Mode** may have irregular or asymmetric geometry active when Symmetry Mode is activated, making it extremely difficult to simulate a correct mirrored change across lines of symmetry.

It gets even worse if symmetry options are ever expanded beyond the cardinal axes, as well! XD 
Potentially related to #1171 and #1885.

**Comment by dacap** [comment]
This is duplicated #1011 (I think)
