### ISSUE TITLE
Support jpeg Exif.Image.Orientation tag

### ISSUE THREAD

**Issue by ryandesign** [aseprite/aseprite#2525]
Aseprite doesn't appear to support the Exif.Image.Orientation tag. I took a photo of an object with my iPhone in order to import it into Aseprite as a reference layer. When opening the photo in Apple's Preview app, it shows right-side up, but in Aseprite, it's upside-down. In Preview, the Info window shows "Orientation: 3 (Rotated 180°)". Or from the command line:

```
$ exifprint IMG_7288.JPG | grep Orientation
Exif.Image.Orientation                       0x0112 Short       1  3
```

(`exifprint` is part of [exiv2](https://www.exiv2.org).)

I suspect the Orientation depends on which way I had rotated the phone when I took the photo.

### Aseprite and System version

* Aseprite version: 1.2.25 compiled from source
* System: macOS High Sierra 10.13.6

**Comment by dacap** [comment]
Hi @ryandesign, yeah, it's a known issue 😢

For references layer this is a must. For regular images (File > Open) I'm still not sure if the tag should be read and rotated in the decoding process on-the-fly, but after that, if the image is saved the tag is lost and the image data is saved in with the new/correct rotation.
