### ISSUE TITLE
Empty bin folder after compilation attempt

### ISSUE THREAD

**Issue by ArcZeroes** [aseprite/aseprite#2532]
As the headline says, the bin folder is simply empty after compiling.

**To give you the steps I took:**

1. Downloaded Visual Studio community, selected and added the C++ module and the Windows 10.0.18362.0 SDK addition.

2. Downloaded and installed CMake from the website.
To be more specific, it was:
Binary distributions
Platform:
Windows win64-x64 Installer: Installer tool has changed. Uninstall CMake 3.4 or lower first!
Files:
cmake-3.18.3-win64-x64.msi

3. Downloaded ninja-win.zip from here: https://github.com/ninja-build/ninja/releases

4. Downloaded Skia-Windows-Release-x64.zip from here: https://github.com/aseprite/skia/releases

5. Downloaded Aseprite 1.2.24 from here: https://github.com/aseprite/aseprite/releases

**With the downloaded files I did the following:**

1. Directly in c:\ I created the folder "aseprite" and dragged the files from the aseprite.zip into the newly created folder. Once all files have been dragged over I created inside c:\aseprite the folder "build"

2. Directly in c:\ I created the folder "deps" and inside deps I created the folder "skia" and added the contents of step 4 into it. (5 folders in the zip file to be exact)

3. I installed CMake and chose the second option to set the PATH to all users.

4. Into the folder c:\programs\CMake\bin I added the ninja.exe from the ninja zip file.

**Now the commands:**

1. Opened cmd

2. used the command
`call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" -arch=x64`

3. then used the command
`cd c:\aseprite\build`

4. then used the command
`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x64 -DSKIA_LIBRARY=C:\deps\skia\out\Release-x64\skia.lib -G Ninja ..`

**Errors I found in the cmd (+ some 'failures' and 'not found's that I took out)**

```
CMake Deprecation Warning at third_party/cmark/CMakeLists.txt:6 (cmake_policy):
  The OLD behavior for policy CMP0048 will be removed from a future version
  of CMake.
  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
-- Could NOT find EXPAT (missing: EXPAT_LIBRARY EXPAT_INCLUDE_DIR)
-- Could NOT find LIBGCC (missing: LIBGCC_LIBRARY)
-- Could NOT find PCREPOSIX (missing: PCREPOSIX_LIBRARY PCRE_INCLUDE_DIR)
-- Could NOT find PCRE (missing: PCRE_LIBRARY)
```

Anyone got any idea how to fix it, where to get those libraries from/what part I am missing and what's up with CMake?

**Comment by KashouC** [comment]
I just woke up, so forgive me if I'm missing something, but you seem to have stopped after the cmake step. You have to run ninja after that if it was successful, which it may have been even if it complained about some lines.

**Comment by ArcZeroes** [comment]
> I just woke up, so forgive me if I'm missing something, but you seem to have stopped after the cmake step. You have to run ninja after that if it was successful, which it may have been even if it complained about some lines.

Oh god, yeah I did indeed forget to run
`ninja aseprite`
at the very end.

Thanks for pointing that out!
