### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by nesper8** [aseprite/aseprite#2538]
Describe your bug report or feature request here

Unable to compile from source code

### Aseprite and System version

* Aseprite version: Aseprite-v1.2.25 from https://github.com/aseprite/aseprite/releases/download/v1.2.25/Aseprite-v1.2.25-Source.zip
* System: Linux 5.8.14, Arch Linux

[buildlog.txt](https://github.com/aseprite/aseprite/files/5361313/buildlog.txt)

**Comment by mttkay** [comment]
I ran into the same problem. I believe the issue is that `libwebp` is linked twice: once in `libskia.a` which is statically linked and again by linking it in the `aseprite` binary itself:

```shell
/usr/bin/c++  -Wall -Wno-switch -O2 -g -DNDEBUG [...]  ../path/to/skia/out/Release-x64/libskia.a  [...] lib/libwebp.a [...]
```
This leads to webp symbols being defined twice.

You can fix this by excluding the webp dependency:

```shell
cmake \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DWITH_WEBP_SUPPORT=0 \
 ...
  -G Ninja \
  ..
ninja aseprite
```

**Comment by mttkay** [comment]
PS: Happy to send a PR with updated build instructions if it helps -- but I wanted to check first that it is expected that skia is already compiled with WebP support? I used the binaries referenced by the build instructions here: https://github.com/aseprite/skia/releases/tag/m81-b607b32047

**Comment by Xtendera** [comment]
Can be closed as libwebp is now fixed

**Comment by nesper8** [comment]
Thank you
