### ISSUE TITLE
Compilation fails with a huge output

### ISSUE THREAD

**Issue by SilentStormm** [aseprite/aseprite#2540]
When compiling on Windows 10 following all of the installation steps, Ninja fails with a ridicoulusly huge amount of errors and warnings:
[CMake output](https://github.com/aseprite/aseprite/files/5362184/cmakeoutput.txt)
[Ninja output](https://github.com/aseprite/aseprite/files/5362185/ninjaoutput.txt)

**Comment by KashouC** [comment]
Did you call vsdevcmd.bat before running ninja? If you closed the command prompt window you have to recall it again.

**Comment by SilentStormm** [comment]
Yup, I followed the tutorial step by step, including that call. It printed out 
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.6
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
```
and (seemingly) returned to the normal command prompt, and I'm not sure if that's expected or not.

**Comment by SilentStormm** [comment]
Also, maybe it's possible to compile for Windows with WSL? Maybe Linux would do better.

**Comment by SilentStormm** [comment]
Dwnloading a newer version of skia (1 or 2 versions up max) helped. Still many type conversion data loss and other warnings, but at least the compilation was successful.
