### ISSUE TITLE
Naming Inconsistency in Layers with a Localization

### ISSUE THREAD

**Issue by yu-tang** [aseprite/aseprite#2549]
I am using Aseprite with a Japanese language extension. 
I can see that a new layer named like this:

## Expect:

1. I create a new sprite then new layer "レイヤー 1" is automatically created too.
    The word "レイヤー" means "Layer" in Japanese translation.
2. I  select a new layer menu command then new layer "レイヤー 2" is added.
3. I  select a new layer menu command again then new layer "レイヤー 3" is added.

Now I have three layers which has named "レイヤー 1", "レイヤー 2" and "レイヤー 3".

## Actual:

1. I create a new sprite then new layer "Layer 1" is automatically created too.  
2. I  select a new layer menu command then new layer "レイヤー 1" is added
3. I  select a new layer menu command again then new layer "レイヤー 2" is added.

Now I have three layers which has named "Layer 1", "レイヤー 1" and "レイヤー 2".

I know I can rename it or leave it as is without any technically problem, it's just kind a little annoying.

Aseprite v1.2.25

**Comment by dacap** [comment]
Thanks for the bug report @yu-tang, [the fix](https://github.com/aseprite/aseprite/commit/c0ac9208ff281c567a22f18d8312915f01337d1d) will be available in the next release (v1.2.26)
