### ISSUE TITLE
Clear Recent Files not working

### ISSUE THREAD

**Issue by DJLink** [aseprite/aseprite#2551]
Hi,
I have this slightly annoying bug for a while, so it didn't start on this version particularly, I just never reported before.
When I open Aseprite I see some Recent Files, but pressing to clear never clears all of them. There are 10 files that are always there regardless of pressing the button or not. So while some of them are clear not all of them get erased which leaves the "home" a bit cluttered 

### Aseprite and System version

* Aseprite version: v1.2.25-x64, Steam
* System: Windows 10

**Comment by DJLink** [comment]
Posting this made me mess around the settings a bit more and I discovered a fix for my particular case. 
Pressing "Clear" on this panel also didn't worked, however I reduced the "Recent Items" amount to 0 and voilá everything gone. Now those 10 stuck items are no longer there and clearing works are intended. 

Not sure if I should close this issue or not, in my case it's solved but I'm unsure if this behaviors indicates a bug somewhere or just a glitch on my system. Feel free to close if not required. 

![image](https://user-images.githubusercontent.com/423769/97102804-6af5bc80-16a0-11eb-8358-4053cf050da5.png)

**Comment by dacap** [comment]
Hi @DJLink, just in case, the clear option doesn't delete the pinned items (only the recent files):

![image](https://user-images.githubusercontent.com/39654/97208915-70cfc880-179a-11eb-9c83-e3fcd2d3b52c.png)

**Comment by DJLink** [comment]
ohhh ok now I feel silly,

So I'm using "than" theme, listed on the aseprite page => https://github.com/aseprite/themes#readme
But it looks like that theme doesn't show the pins, I tried switching to Default theme and the pins are there. So I must have clicked by accident and because the theme doesn't show I didn't even know that was a thing.

I'm sorry for the trouble.

**Comment by dacap** [comment]
Oh I understand, I have the same problem (invisible pins) using other custom themes. I glad it was related to that issue! closing this by now.
