### ISSUE TITLE
What does the tooltip_text color definition applies to?

### ISSUE THREAD

**Issue by yu-tang** [aseprite/aseprite#2554]
I am looking into a theme/skin feature now. Specifically, `theme.xml` in default theme.
I picked a tooltip up and change its color:

        <color id="tooltip_text" value="#000000" />
        <color id="tooltip_face" value="#ffff7d" />

to:

        <color id="tooltip_text" value="#ff0000" />
        <color id="tooltip_face" value="#0000ff" />

Tooltip face (i.e. background color of text) has changed as expected. But the text foreground color has not.
I tinkered with it and found the `textbox_text` color definition applies to a tooltip text color.
Yes, now I have the worst tooltip which is consists blue and red color!

Here is an unexplained one.
What does the `tooltip_text` color definition applies to?

Aseprite v1.2.25

**Comment by thkwznk** [comment]
The same issue can be observed in version 1.2.35-x64 (on Windows 11), the `tooltip_text` doesn't seem to be applied to the tooltips text.
