### ISSUE TITLE
"ninja aseprite" failure

### ISSUE THREAD

**Issue by yonderbread** [aseprite/aseprite#2556]
Describe your bug report or feature request here
Finally after like 3 months of attempting to compile Aseprite from source I actually got to the point where I can compile the actual program itself. When I run `ninja aseprite` it seems to compile all the files fine.. but then out of the blue this happens: 
https://pastebin.com/jATPWUUJ

Can someone help me fix clang or whatever the problem may be?

### Aseprite and System version

* Aseprite version: Latest Version
* System: Pop!_OS 20.10

**Comment by yonderbread** [comment]
Alright so after trying out a prebuilt skia package instead of my own I was able to almost finish the build up to the point where it was creating the `aseprite/build/bin/aseprite` executable, but I get another error.
https://pastebin.com/E0HhaAbm

**Comment by CodeDecodeDev** [comment]
i am on ubuntu 20.10 and im having same problem

**Comment by yonderbread** [comment]
Devs, any response to this?

**Comment by bernardo-dev** [comment]
i'm having problem with the ninja aseprite command too
https://pastebin.com/KchjyF4f

**Comment by dknight** [comment]
Same problem on Fedora 33 as here https://pastebin.com/KchjyF4f
Also tried to compile Skia manually - same result.

**Comment by dknight** [comment]
I think something wrong with WebP library.

`-DWITH_WEBP_SUPPORT=OFF`

Added flag  the compilation successful, but no webp support. I can live without it.

**Comment by yonderbread** [comment]
> I think something wrong with WebP library.
> 
> `-DWITH_WEBP_SUPPORT=OFF`
> 
> Added flag the compilation successful, but no webp support. I can live without it.

Could you send a paste of the commands you ran in order?

**Comment by dknight** [comment]
@yonderbread 
Here you go:
```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_WEBP_SUPPORT=OFF -DUSE_SHARED_FREETYPE=1 -DLAF_BACKEND=skia -DSKIA_DIR=$HOME/aseprite/skia/ -DSKIA_LIBRARY_DIR=$HOME/aseprite/skia/out/Release-x64/ -DSKIA_LIBRARY=$HOME/aseprite/skia/out/Release-x64/libskia.a -DCMAKE_INSTALL_PREFIX=${HOME}/.local -G Ninja ..
```

**Comment by yonderbread** [comment]
> @yonderbread
> Here you go:
> 
> ```
> cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_WEBP_SUPPORT=OFF -DUSE_SHARED_FREETYPE=1 -DLAF_BACKEND=skia -DSKIA_DIR=$HOME/aseprite/skia/ -DSKIA_LIBRARY_DIR=$HOME/aseprite/skia/out/Release-x64/ -DSKIA_LIBRARY=$HOME/aseprite/skia/out/Release-x64/libskia.a -DCMAKE_INSTALL_PREFIX=${HOME}/.local -G Ninja ..
> ```

Ty :) I'll lyk how it goes

**Comment by grian32** [comment]
> I think something wrong with WebP library.
> 
> `-DWITH_WEBP_SUPPORT=OFF`
> 
> Added flag the compilation successful, but no webp support. I can live without it.

Worked for me, thanks a bunch!

**Comment by yonderbread** [comment]
I actually have a ![build script](https://github.com/yonderbread/config/blob/master/src/scripts/comp/aseprite.sh) if any of you would like to try it out.
