### ISSUE TITLE
Enable panning and zooming with an opened window

### ISSUE THREAD

**Issue by lawrence-laz** [aseprite/aseprite#2563]
Enable panning and zooming (by pressing<kbd>mousewheel</kbd>) while replace color window is open.

This would be useful when previewing color changes before submitting them.

Gif below shows how you can pan and zoom while there no window, but cannot when window is open.
![kST3cpbb3j](https://user-images.githubusercontent.com/8823448/99834198-df226380-2b6b-11eb-9286-9c757ecb32c7.gif)

### Aseprite and System version

* Aseprite version: V.1.2.25-x64, Steam
* System: Windows

**Comment by Gasparoken** [comment]
Required a Non-modal Replace Color dialog.
Internal: https://igarastudio.zendesk.com/agent/tickets/4547
