### ISSUE TITLE
Export bug: not enough memory to resize gif on export

### ISSUE THREAD

**Issue by cartman343** [aseprite/aseprite#2569]
I tried to create a gif that consists of more than 200 frames. Everything worked on the first export. During the second export I set resize to 300% and I got an error message that the memory overflowed. After that, the project file was damaged and the first 152 frames were incomplete.

Console: There is not enough memory to complete the action
Okay but dont distroy my projectfile pls.

size: Width 130px Height 173px
Frames: 210 (all in one Layer)
Time; 100ms/21.00s

### Aseprite and System version

* Aseprite version: Aseprite v1.2.25-x64
* System: Windows 10 up to date // MSI GE73 7RC Raider // Samsung 1TB 970 Evo Plus

**Comment by KashouC** [comment]
Hmm that sounds not great. The file itself shouldn't be damaged unless you save the open file so reopening it would probably solve that (i hope). Otherwise there should be a recovery file in the second section of the Recover File list (It says Previous Sessions, it's below the crashed session files), if you click that button on the home menu.

**Comment by cartman343** [comment]
Hi, after I wanted to reproduce the error yesterday to get the error message for the report, Windows also crashed. When I started the Aseprite this morning, the recovery window was displayed. Not for this project but for another one which I closed yesterday without saving. But that way I was able to restore the project at issue here.

**Comment by KashouC** [comment]
Hmm, I'm wondering if this might be a hardware problem in that case. I would backup my work if I was you in case your harddrive is starting to act up. Could be a RAM issue as well but hard to tell either way. It could be Aseprite but it crashing Windows is something I rarely if ever hear of.
