### ISSUE TITLE
Pen Pressure + Symmetry bug

### ISSUE THREAD

**Issue by alexpandanet** [aseprite/aseprite#2584]
Some pixels will either be removed or added when using vertical symmetry and pen pressure in tandem. In particular, pen pressure affecting pen size.
![image](https://user-images.githubusercontent.com/75462439/101117510-58767900-35a4-11eb-8282-9a3270822cf2.png)

Aseprite v1.2.25-x64

Windows 10 Enterprise 10.0.18363

**Comment by dacap** [comment]
Maybe related to #1427

**Comment by dacap** [comment]
This should be fixed in v1.2.26 https://community.aseprite.org/t/aseprite-v1-2-26/8720
