### ISSUE TITLE
Wrong json with linked, trimmed cels

### ISSUE THREAD

**Issue by davidfrankel** [aseprite/aseprite#2600]
I'm exporting a sprite sheet and reading the json values into my game engine.  The json is wrong when I'm using linked cels *and* cels are being trimmed.

These sample files show what I'm talking about: [aseprite file](https://drive.google.com/file/d/1k-Vil5cQyjsLzyTwJxaBzlbPay4CaE-T/view?usp=sharing), [various exports](https://drive.google.com/file/d/178BW-GD9Gituto9K4Og2xgNT4IVfNr00/view?usp=sharing)

The json fields I'm looking at are `frame`, `spriteSourceSize`, and `sourceSize`.

Thanks!

### Aseprite and System version

* Aseprite version: v1.2.25, Steam
* System: macOS 11.1

**Comment by davidfrankel** [comment]
I'm also getting wrong json output when I have the same art in different layers and I'm merging duplicates on export.

Maybe this is part of the same issue?

**Comment by Gasparoken** [comment]
Thanks for this report @davidfrankel. I was able to reproduce it and it'll solved soon.
