### ISSUE TITLE
Shading Ink

### ISSUE THREAD

**Issue by SirCavalheiro** [aseprite/aseprite#2603]
Describe your bug report or feature request here
... I don't know exactly what that problem would be, but here's what happens: Every time I open aseprite, the selected ink is always shading, and it doesn't work as it should, in fact, it seems to work like normal ink. I can paint with it on top of any layer, even though it doesn't have any material and it still doesn't darken or whiten. As I said, it works like normal paint
...
...

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by dacap** [comment]
Hi @SirCavalheiro, just in case, could you please check the [shading ink guide](https://www.aseprite.org/docs/shading/)?
