### ISSUE TITLE
[BUG] HSV/HSL Color slider values randomly go down by 1 when changing other values

### ISSUE THREAD

**Issue by BloodRaven0** [aseprite/aseprite#2607]
To reproduce this bug, open the color sliders (F4), and select a color from your pallette to edit. Go to HSV or HSL sliders. Try inputting, for example, hue at 50, either by manually inputting the number by typing it in the box, or by precisely sliding with your mouse. Now click another color and go back to the first one. It might or might not have subtracted 1 from your original value. It also randomly subtracts 1 from other values which you have not touched. It doesn't seem to happen for RGB or Grayscale sliders.
See example gif below:
![Example](https://user-images.githubusercontent.com/42444745/103544904-72f48880-4ea9-11eb-9b5e-2e457bd64973.gif)

**Comment by dacap** [comment]
Duplicate #2245
