### ISSUE TITLE
Hey guys is there a functional difference between the aseprite open source version and aseprite on steam?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [aseprite/aseprite#2627]
Hey guys is there a functional difference between the aseprite open source version and aseprite on steam?

**Comment by KashouC** [comment]
The steam/humble/wherever else you bought it is the latest stable release while the latest github version might have additional bug fixes but usually no real additional features.

**Comment by Yakumo-Yukari** [comment]
> The steam/humble/wherever else you bought it is the latest stable release while the latest github version might have additional bug fixes but usually no real additional features.

Thank you for your answer,Have a good day!
