### ISSUE TITLE
为啥会出现这个问题

### ISSUE THREAD

**Issue by xingluowuxin** [aseprite/aseprite#2636]
ninja: error: 'D:/deps/skia/out/Release-x64/skia.lib', needed by 'bin/aseprite.exe', missing and no known rule to make it
应该都全的，怎么会出现这个情况

**Comment by Likenttt** [comment]
所以是为啥呢,类似的报错 

````
$ ninja aseprite 
ninja: error: '/home/xxxx/deps/skia/out/Release-x64/libskia.a', needed by 'bin/aseprite', missing and no known rule to make it

````

**Comment by Eternal-plasma** [comment]
因为你没有 libskia  (我的中文不太好)

**Comment by Eternal-plasma** [comment]
I am not quite sure but I think it is because of a missing library(s)
