### ISSUE TITLE
Crashing when saving jpg - outdated library

### ISSUE THREAD

**Issue by UltraBlackLinux** [aseprite/aseprite#2639]
Describe your bug report or feature request here
```
Wrong JPEG library version: library is 62, caller expects 80
terminate called without an active exception
[1]    120626 abort (core dumped)  aseprite --verbose --debug
```
My library is completely up-to-date - what is the approach here?

### Aseprite and System version

* Aseprite version: 1.2.25.r34.g3035a5713-1
* System: Linux

Thanks!

**Comment by KashouC** [comment]
Just a shot in the dark as I don't really know Linux but give this a try.

https://serverfault.com/questions/739363/wrong-jpeg-library-version-library-is-62-caller-expects-80#comment924212_739364

**Comment by UltraBlackLinux** [comment]
> Just a shot in the dark as I don't really know Linux but give this a try.
> 
> https://serverfault.com/questions/739363/wrong-jpeg-library-version-library-is-62-caller-expects-80#comment924212_739364

That seems to be exactly my problem, ty!
