### ISSUE TITLE
Saving palettes as .jpg/.jpeg crashes the program

### ISSUE THREAD

**Issue by marCOmics** [aseprite/aseprite#2654]
If you try to save the palette via the palette options as a .jpg/.jpeg file the program crashes, even if there are no transparent colors in the palette and image. If it shouldn't be possible to export palette in this format, an error message would be more appropriate.

Dump file: [Aseprite-crash-1.2.25-x64.zip](https://github.com/aseprite/aseprite/files/6090764/Aseprite-crash-1.2.25-x64.zip)

### Aseprite and System version
* Aseprite version: v1.2.25-x64 via Steam
* System: Windows 10

Thanks in advance! :)

**Comment by dacap** [comment]
Thanks for this bug report @marCOmics, the fix will be available in v1.2.29 👍
