### ISSUE TITLE
Export Sprite Sheet cannot differentiate between Layers with matching names

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#2656]
If multiple Layers have the same name, the Export Sprite Sheet pane only recognizes one of them regardless of which of the Layers (of the same name) is selected from the "Layers" pulldown box.
Layers with matching names can be in the same or different Layer Groups and the bug will still occur.

It seems as though layers are keyed to the string used to name them, regardless of Grouping, rather than the specific identity they have in the Layers selection pulldown box.

Thanks for looking into it! :D 

..using ASEprite 1.2.25-x64 on Win10.

**Comment by Gasparoken** [comment]
Thanks for this report @oceanhahn! I was able to reproduce it.

**Comment by iamOgunyinka** [comment]
Bringing this forward a bit, looks like there was a bug identical to this mentioned recently. I'll add a link if/when I find it.
