### ISSUE TITLE
Canvas Flip

### ISSUE THREAD

**Issue by nullbunny** [aseprite/aseprite#2657]
Currently I am "mis-using" Flip Horizontal to flip the canvas. It kind of works but it has some draw backs:

* It clutters up the Undo History
* The view doesn't stay on what I was working on after the flip

My "dream" canvas flip command would:

* Not count as an actual action, it just changes the view, and doesn't go into the Undo History. So I can Undo a bunch of steps without the canvas flipping back.
* When I work zoomed in and flip the canvas, the portion of the picture I was working on stays in the middle of the screen.

Thank you for considering this feature!

**Comment by Gasparoken** [comment]
Thanks for this report and advises.

- It clutters up the Undo History.
My first impression is to ask: why is it useful for you to exclude canvas flip from undo history (could you give me some use case?)
- The view doesn't stay on what I was working on after the flip
This feature sound good!

**Comment by nullbunny** [comment]
Thanks for considering this!

"why is it useful for you to exclude canvas flip from undo history (could
you give me some use case?)"

Flipping the canvas is helpful when working on things like portraits of
characters and anatomy. You flip the canvas to find mistakes and I do it a
lot during my work. Sometimes I'd like to flip the canvas, work on
corrections, flip back and forth to see how it looks and be able to undo my
correction to try a different one. I might do this after a string of flips
and pixeling. If I now wanted to undo the past couple of corrections to try
something else, I'd also have to ctrl-z through a whole bunch of flipping,
which is tedious and also very disorienting.

I hope that clears up my request for this feature.

**Comment by Gasparoken** [comment]
Thanks for the clarification! Interesting.
We'll evaluate the options:
- A check box in Preferences (something like "Exclude Canvas transformations") ?
- New normal behavior?
- Should other tools or commands have this undo exclusion property?
- Others?

**Comment by dacap** [comment]
Hi there 👋 Please @Gasparoken check that this is only a "viewport feature", here @nullbunny wants to flip the canvas viewport so we can see/edit the image flipped. This is a duplicate #1225 if I understand correctly.

This is like applying a transformation matrix to the output (and the input), but the internal pixels/data doesn't change, only the viewport/editor.

**Comment by Gasparoken** [comment]
Thanks @dacap David. Yes, I understood the original intention of @nullbunny. Now, I think it would be better to add some `Flip Canvas` option to the `View` editor menu, instead of using the actual `Sprite > Rotate Canvas > Flip Canvas` with an alternative behavior.

**Comment by dacap** [comment]
Closing as duplicate, refer to https://github.com/aseprite/aseprite/issues/1225
