### ISSUE TITLE
Typo on Homepage

### ISSUE THREAD

**Issue by DTRW919** [aseprite/aseprite#2662]
Hey there, it's me :) So I didn't see a repo for the website itself so I thought I'd put it here. On the home page, where it showcases the Aseprite features, it says "Recovery your sprites in case of crash." under the Data Recovery tab, but it should probably be changed to "Recover your sprites in case of a crash". Thanks for reading! You guys are awesome.

**Comment by dacap** [comment]
Thanks again @DTRW919, yeah, the website doesn't have a public repository, so any typo you find you can create an issue. I'll take a look to these ASAP.

**Comment by Gasparoken** [comment]
This was fixed in the website repository. Changes will be reflected in next website update.
