### ISSUE TITLE
Pressure sensitivity doesn't work in Manjaro

### ISSUE THREAD

**Issue by LavenderTheGreat** [aseprite/aseprite#2667]
For some reason my tablet does not have pressure in Manjaro, it works in windows just fine and on the Linux end it works with Krita perfectly. It was mentioned in https://github.com/aseprite/aseprite/issues/710#issuecomment-675039086 but that issue has since been closed, so I think its appropriate to open a new issue for it.

### Aseprite and System version

* Aseprite version: v1.2.25
* System: Manjaro KDE 5.9.16.1

**Comment by Anshorei** [comment]
Have you tried closing Aseprite, unplugging the tablet, re-plugging it and then restarting Aseprite? That got it to work for me.

**Comment by dacap** [comment]
@LavenderTheGreat Just in case you still have this issue, check #3176
