### ISSUE TITLE
In indexed colour mode, on selection, first colour is always transparent

### ISSUE THREAD

**Issue by lukesutton** [aseprite/aseprite#2672]
This occurs regardless of the palette selected. The first indexed colour will always be transparent on selection. Opening the colour editor will show the correct values — alpha is at 255 — yet the colour is completely transparent. Changing the alpha channel a little makes it respect the setting.

### Aseprite and System version

* Aseprite version: 1.2.25
* System: MacOS 11.1

**Comment by Gasparoken** [comment]
Thanks for this report @lukesutton. When you convert the Color Mode to INDEXED, the transparent color is always index 0 as default (index 0 color will have a dot in the center to make it clear that it's Transparent Color).

![Screen Shot 2021-11-22 at 09 08 33](https://user-images.githubusercontent.com/32165475/143287759-a1693259-4959-474c-93a2-07472f28c64d.png)

The color button at the bottom-left of the editor express the results on drawing.

This can be confusing at first, but in this way it gives us some more information to the user. For example, if you want to change the Transparent Color*, you will know that the current transparent color will turn black (index 0 in this example) before you actually make the change.

*To change Transparent Color in an INDEXED image you need go to Sprite > Properties... > Transparent Color
