### ISSUE TITLE
Please may you consider releasing Aseprite under a libre license?

### ISSUE THREAD

**Issue by throwaway1037** [aseprite/aseprite#2675]
Please may you consider releasing Aseprite under a libre license? I understand a lot of your misgivings originated from coordination with packaging in GNU+Linux distributions. We can work towards a solution without making the whole program proprietary.

I would be happy to help figure things out with you. :)

_Originally posted by @throwaway1037 in https://github.com/aseprite/aseprite/issues/2093#issuecomment-800715984_

**Comment by Amoo0001** [comment]
@throwaway1037,

Why did this need a whole new issue?  You already commented this exact message before in the other issue, begging the dev after they already replied to the other person that it wouldn't happen anytime soon, and now you just copy-pasted it to another new issue.  This is entirely unneeded and quite annoying (especially since I have opted-in to get Aseprite issues to my email).

If the developer of a piece of software wants it to be proprietary then that is their choice.  A single person suggesting an alternate license is one thing, but another person coming in to whine about the dev's license choice after they have made their stance clear is disrespectful.  Personally, I'm proud to have paid for Aseprite four times at full price to support development.

-- Amy

**Comment by throwaway1037** [comment]
@Amoo0001,

> Why did this need a whole new issue?

Freedom is important.

I support the free software movement. This movement was formed by Richard Stallman in 1983 to liberate all software; in other words, to eradicate proprietary software.

In a nutshell, free software is software which respects the users' freedom. Proprietary software does not, and as such is an injustice.

In 1984, Stallman started writing a completely free operating system called GNU, which millions of people use today in the form of GNU+Linux (GNU using a component called the Linux kernel). He also started the Free Software Foundation as a charity to support free software.

To get a better understanding of these topics, I would recommend watching some of Stallman's talks, reading Wikipedia about the topics I mentioned, as well as the GNU and FSF websites.

Suffice it to say, the issue of freedom is sufficiently important to deserve its own issue on this repository.

>  You already commented this exact message before in the other issue

I know; I thought the main developer would be more likely to spot it if it were made into its own issue.

> begging the dev

This demonstrates a very important point about free software; no proprietor has control over the users. The fact that I have to "beg" the developer to give the users of his program freedom demonstrates the injustice that is being done by it.

> after they already replied to the other person that it wouldn't happen anytime soon

Demonstrably false.

In #2093, @dacap stated on the 26 of Jun 2019, "there are no plans to change the license in the short-term, but I like that kind of dual licensing". That was over 2 years ago, which in this case I wouldn't class as "short-term". He even stated that he "like[s] that kind of dual licensing", showing that he may have changed his mind by now.

> and now you just copy-pasted it to another new issue

True. I explained why earlier in this message.

>  This is entirely unneeded

I disagree. I explained why earlier in this message.

> and quite annoying (especially since I have opted-in to get Aseprite issues to my email)

That's your opinion. I can't possibly predict what you will or won't find annoying, and quite frankly it wouldn't change what I would plan to do anyway.

You stated yourself that you "opted-in to get Aseprite issues to [your] email" so you should have known that it would be possible for a message you find annoying to be sent.

> If the developer of a piece of software wants it to be proprietary then that is their choice.

Legally, that is the case (at least in most countries), although that is not true ethically. Proprietary software is inherently unethcial because it puts the proprietor in a position of power over the users of the program.

Making a program proprietary only hurts the users of the program.

>  A single person suggesting an alternate license is one thing

I don't suggest an "alternate" license; I suggest adopting a free license as a *replacement*. Referring to a free license as an "alternative" of a proprietary license implies that the proprietary license is ethically valid, which it is not.

Please see this [GNU article](https://www.gnu.org/philosophy/words-to-avoid.en.html#Alternative) for a fuller explanation along with other similar confusing or ambiguous words.

> but another person coming in to whine

I do not understand how I am "whining". My comment, filing this issue, and this rebuttal are all very polite. I even begun the post with "please".

> about the dev's license choice after they have made their stance clear is disrespectful.

It's not "disrespectful". Challenging someone's ideas are the foundation of science and civilisation. You must think freely and be open to change to have evolved to this point, let alone survive on a day-to-day basis.

I would say that the proprietor is actually disrespecting the users by enforcing an unethical, proprietary license on the program, thereby unjustly controlling the users of the program.

It's also worth nothing that Aseprite actually used to be free software, using the GNU GPLv2 license -- the very same one written by Richard Stallman and published by the FSF (both parties I previously mentioned).

The blog post the main developer wrote after making Aseprite proprietary was hinged on his misgivings with the way distributions of GNU+Linux (the OS I previously mentioned) package and redistribute programs. Instead of trying to work towards a solution without making the program proprietary, as I suggested in my initial post (and then this issue), he made the program proprietary.

By doing this, he blocked hundreds of GNU+Linux distributions with policies about only packaging and distributing free software from doing so with Aseprite. The new EULA is a tool of unjust power over these GNU+Linux distributions.

I want to work with the main developer towards a positive solution and make Aseprite free software once again.

> Personally, I'm proud to have paid for Aseprite four times at full price to support development.

This is irrelevant to the discussion, but I'll respond nonetheless.

I congratulate you if you supported the development of Aseprite whilstit was free software, but I frown upon providing financial support to proprietors.

It's also worth noting that this statement feeds into the misconception and myth that software is only developed with a financial incentive in mind. This is demonstrably false also. Eg. GNU, Linux, TempleOS, most projects on this very website, etc...

This [GNU article](https://www.gnu.org/philosophy/fs-motives.en.html) lists some reasons why people write free software.

Thank you very much for reading, and I hope you may reply soon.

**Comment by ElaxDev** [comment]
@throwaway1037 ¿Cómo te poni a llorar por un chocmans?

**Comment by throwaway1037** [comment]
@ElaxDev I only speak/read/write English when it comes to human languages.

**Comment by dacap** [comment]
Sorry I'll close and lock this issue, there are no plans to change the license.
