### ISSUE TITLE
Please explain

### ISSUE THREAD

**Issue by throwaway1037** [aseprite/aseprite#2679]
Please explain why you closed #2675 without any explanation.

I want to work with the Aseprite team towards a positive solution to making Aseprite free software again. I really think we can make this happen together and fix the issues @dacap has with the way some GNU+Linux distributions package software.

Thank you.

**Comment by dacap** [comment]
Hi @throwaway1037. First of all, I would recommend you to avoid introducing yourself in anonymous ways (e.g. "throw away" account). That makes you look bad for this kind of business. We are not going to talk about this kind of changes in "anonymous ways." If you want to talk about this, send me a non-anonymous email to david@igarastudio.com

The second thing is that this was already discussed in the past several times, e.g. here https://community.aseprite.org/t/6508/5 so there are no more words to add.

And third, there are no plans to change the license, my post about the situation is still true and there are distros (e.g. Arch Linux) that have ignored completely the EULA bypassing it. Ignoring the goal of the license or the decision of the development team.

If you still think that you can make us change our mind, stop thinking that. This is not the moment. Please respect the decision of the developers. We are focused in improving Aseprite right now, and a license change is the last thing we can think of in this moment (and maybe in several years).

Thanks anyway about your concerns.

**Comment by throwaway1037** [comment]
You:
1. Used the [propaganda](http://torrentfreak.com/mpaa-banned-from-using-piracy-and-theft-terms-in-hotfile-trial-131129/) term "[piracy](https://www.gnu.org/philosophy/words-to-avoid.en.html#Piracy)". [**Copying is not theft**](https://www.youtube.com/watch?v=IeTybKL1pM4). To liken sharing to attacking ships, killing people, and stealing from them is perverse.
2. Used the term "Linux" to refer to the [GNU+Linux](https://gnu.org) operating system.
3. Seem to be confused. I am talking about [free software](https://www.gnu.org/philosophy/free-sw.en.html) and am referring to "free as in freedom", not "free as in price". Libre, not gratis. However much money you charge for Aseprite is (literally, in this case) your business and is irrelevant to whether Aseprite is free (libre) software or not.

If Arch GNU+Linux does something you don't like, that shouldn't stop you giving ***everyone else*** freedom. I'm only here talking about Aseprite because I want it to succeed, and I want to like it, but I cannot do either of these things in good faith unless Aseprite becomes free (libre) software. Arch GNU+Linux does not accurately represent the free software community -- they're not even *part* of it!

[Parabola GNU+Linux-libre](https://parabola.nu) is a fork of Arch GNU+Linux that is entirely free (libre) software and entirely free (libre) media (documentation, images, game files, etc...). This community would (I can only assume) embrace Aseprite with open arms if it were to become free (libre) software.

By making Aseprite proprietary, you block all the GNU+Linux distributions which have policies against proprietary software, and only distribute free (libre) software. In effect, you're blocking the good guys who follow the proprietary license and choose not to use Aseprite, whilst the distributions acting in bad faith will just ignore the license and distribute Aseprite anyway. Making Aseprite proprietary does not solve any problems.

I am under no obligation to "respect" the decision to make a program proprietary. This is an injustice, is unethical, and is something I'm actively trying to help change. I want to help turn this situation around and make Aseprite free (libre) software once again.

Side note: Aseprite was sold for years as free (libre) software, so you already know liberating it wouldn't change business plans in any way, so there are no financial downsides to chaning to a free software license, anyway.

**Comment by dacap** [comment]
> By making Aseprite proprietary, you block all the GNU+Linux distributions which have policies against proprietary software

Yes. It means that the EULA worked.

> I am under no obligation to "respect" the decision to make a program proprietary.

Actually yes, you are. There is a [code of conduct](https://github.com/aseprite/aseprite/blob/main/CODE_OF_CONDUCT.md). So in the same way we respect that you have a desire to see Aseprite adopt the GPL license again, you have to respect the decision of the developers.

> This is an injustice, is unethical

I know that this is the classic FSF discourse, and be aware that that kind of discourse is quite disrespectful with the decision of the developers. Personal decisions at the very end.

I'll lock this discussion and if you want to continue please send me an email to david@igarastudio.com
