### ISSUE TITLE
Selection move of the hidden layer

### ISSUE THREAD

**Issue by magickbirb** [aseprite/aseprite#2680]
Selected area of the hidden layer is moving if I'm moving all layers in one particular frame. The only way to prevent it is to lock the hidden layers, but it'd be much easier if hiding it was enough
I asked on Discord and they said it's a bug, though I thought it was meant this way
Anyway I hope it'll be fixed soon, or at least an option will be added to chose if I want hidden layers to be moved

Aseprite v1.2.25
Windows 10 x64

**Comment by dacap** [comment]
Thanks for reporting this @magickbirb, it will be fixed in the next release v1.2.26 ASAP
