### ISSUE TITLE
Mac Mouse Wheel Does Not Zoom

### ISSUE THREAD

**Issue by hk0i** [aseprite/aseprite#2695]
Using mouse wheel in Aseprite causes the window to scroll up and down, using ctrl + mouse wheel causes the window to zoom. My settings show mouse wheel to zoom is checked 
![image](https://user-images.githubusercontent.com/755669/114071140-a4d50c80-9855-11eb-85eb-1972eac57aed.png)

How can I use mouse wheel to zoom in without holding ctrl?  
On the windows version ctrl + mouse wheel changes brush size, how can I change brush size on OS X using the mouse wheel?

Is there another way to change brush size easily that I don't know about or some setting to change this behavior?

### Aseprite and System version
* OS X 10.15.7
* Aseprite 1.2.25 (Steam)

**Comment by djrain** [comment]
Same here, scroll wheel does not work to zoom :/

**Comment by nkoder** [comment]
I think I have same issues, but not sure. I was recently trying to assign whatever+wheel to change brush size, but all ctr/alt/cmd changed nothing. After studying Aseprite "Preferences" window and key shortcuts window I concluded default mouse wheel behaviour is different than should be.

**Comment by dacap** [comment]
Hi there 👋  actually the default behavior for the mouse wheel on macOS is zooming. What specific mouse are you using? (here a Razer DeathAdder Chroma).

**Comment by djrain** [comment]
I'm using a Logitech MX Master 3.

**Comment by dacap** [comment]
I've found these topics:

* https://www.reddit.com/r/MouseReview/comments/f9vfck/logitech_mx_master_3_scrolling_wheel_issues_macos/
* https://support.logi.com/hc/en-us/community/posts/360047249993-Logitech-MX-Master-3-Scrolling-problem-in-Viber-App-on-macOS-Catalina-10-15-5

Is it a common issue with other apps? What happen if you disable the permission to Logi Options Daemon?

**Comment by hk0i** [comment]
Looks like a different event name, I see `preciseWheel` instead of `wheel`:

![allevents preciseWheel](https://user-images.githubusercontent.com/755669/114088970-757cca80-986a-11eb-9774-171ca2fd8b7d.png)

**Comment by dacap** [comment]
In that case, check if enabling this option from *Edit > Keyboard Shortcuts > Mouse Wheel > Zoom sliding two fingers up or down* fix your issue:

<img width="573" alt="Screen Shot 2021-04-08 at 17 03 27" src="https://user-images.githubusercontent.com/39654/114089347-6b6bc380-988c-11eb-98cc-e7ddca7e8af3.png">

**Comment by dacap** [comment]
Glad to hear that! It's interesting because the "precise wheel" is reported from MacBook trackpads (that's because the option is called "sliding two fingers"). I'm not sure if we can detect if the event is from a mouse instead of trackpad (generally "two fingers motion" in the trackpad will just scroll, as a tablet).

**Comment by djrain** [comment]
I'm using Smooze app for smooth scrolling, and for some reason this doesn't play nicely with scroll to zoom in Aseprite (though panning works great). Guess I'll just have to disable it.

**Comment by hk0i** [comment]
Looks like the LogiOptions smooth scrolling it sends extra scroll events which can make it cumbersome to deal with. It's probably a similar implementation

**Comment by hk0i** [comment]
Actually the values seem to jump a lot for me... Brush size goes from 1px to 7px. Any ideas on how I could change that?

**Comment by nkoder** [comment]
@hk0i I managed to do +1 jump by both:
- enabling smooth scrolling (so it's no longer from 1 to 7, but smoothly through all values)
- enabling free rotation (whatever it's called) in my MX Master 3, which means I am able to move a wheel w/o "tick" just a little, making brush size go from 1 to 2

I am not saying it's a comfortable and reliable setup, but sharing this observation in case it helps you 🙂

**Comment by hk0i** [comment]
Looks like smooth scrolling causes issues in some other software so I may not be able to use this feature for now,  is there another work around? Even with smooth scrolling it is a bit uncomfortable.

**Comment by dacap** [comment]
At the moment there are no way to configure the wheel sensitiveness inside Aseprite, but we could offer something to do so. Maybe a multiplier would be enough (e.g. something to multiple the wheel value * factor, where factor = 0.01 to 10.0)

**Comment by dacap** [comment]
That could work, my only worry is when to reset the value. For example, I'm not sure how the precise mouse wheel works in these devices, but I guess they offer a continuous flow of values, instead of discrete events (-1, +1 as regular mouse wheels). So the issue is when the value should count as other wheel "tick".

**Comment by snave2** [comment]
I think I might have found a fix. The problem is with the Logitech options app for customizing their mouse. If you go to activity monitor and kill the Logitech Options Daemon and go into system preferences->security & privacy->accessibility and uncheck the Logitech Options Daemon, it should work after you turn the mouse off and on again.

**Comment by snave2** [comment]
I have a Logitech M510 if that makes it difference.
Aseprite v1.2.27
MacOs BigSur 11.3.1 (20E241)

**Comment by potofpie** [comment]
MOS was my issue another smooth scrolling Mac app.

**Comment by L33t-HAXXOR** [comment]
Same issue on macOS 10.14.6 (Mojave) Using a Logitech MX Vertical Advanced Ergonomic Mouse
(no smooth scrolling option for me :kek:)

**Comment by Morokiane** [comment]
Same issue on M1 with MacOS 11.6. Though enabling Two finger scroll fixes the issue even with scroll wheel to zoom does not need to be on...which just means that toggle does nothing on Mac.

**Comment by yakivmospan** [comment]
Hey @dacap, after updating to 1.2.33 (was somewhere under 1.2.30 before) scroll wheel on my MX Anywhere 3 (which uses the same software as MX Master) become very sensitive. Just unable to scroll or zoom with it. Is it possible to add some sort of sensitivity option for the scroll wheel to preferences, would be really handy? 

Meanwhile would be very thankful if you drop me some info about where to download an older version of the app, Humble Bundle provides only the latest build. Thanks

**Comment by hk0i** [comment]
Since I opened the ticket I'd like to note that my MX Master is working great right now (currently tested on v1.3-beta11-x64). Just so we have it marked for historical reasons that this was at some point working.

Thanks everyone!

**Comment by yakivmospan** [comment]
@dacap Looking forward to that new config param, thanks!

**Comment by yakivmospan** [comment]
Just to give you more hints here, I'm running Aseprite on Big Sur 11.6. And here are my Logi Options: 

![image](https://user-images.githubusercontent.com/1574033/153745589-55f8b527-d0cd-4703-a151-7d01a9fe07bd.png)

Just ping me if you need any other details.

**Comment by tuanddd** [comment]
Have anyone been successful in adjusting the zoom speed? I'm using a MX Mouse 3 too and even with just a slight touch of the wheel causes the zoom level to increase by at least 100% each time

**Comment by Gasparoken** [comment]
I'll try to add some sensitivity scheme soon.

**Comment by Gasparoken** [comment]
Please @yakivmospan, try this configuration in Logitech driver (Smooth scrolling = Disabled):

<img width="550" alt="Screen Shot 2022-02-16 at 16 52 52" src="https://user-images.githubusercontent.com/32165475/154347256-b405926d-5622-4875-9ab8-646c8580284f.png">

On the other hand, @tuanddd, each scroll wheel "tick" normal increment/decrement is 100% steps in the zoom range: 100% <= ZOOM <=600%.
Zoom <100% percentage sequence: 50%, 33.3%, 25%, 20%, 16.7% ....,....,  1.6%
Zoom >600% percentage sequence: 800%, 1200%, 1600%, 2400%, 3200%, 4800%, 6400%

**Comment by yakivmospan** [comment]
@Gasparoken hey, yeah disabling smooth scrolling only for Aseprite solves an issue with the scroll wheel, thanks.

But it feels like a workaround, as all other apps work well with it. Maybe it's possible for Aseprite to somehow convert events from "smooth scrolling" to "not smooth" ones. So users will not need to go to logi options and do it manually. If it's not possible, then maybe detect that it's a logi mouse and show some hint in options.

**Comment by dacap** [comment]
I want to add that I'm not sure what the other apps do, but probably they use the wheel information as a "smooth zoom" or "smooth scroll". The problem in our case is that Aseprite doesn't support smooth zoom yet (this requires a rewrite of the rendering code, which is planned in some future #835, #1225). So the wheel is used to zoom by "ticks"/"levels" (the smooth data is converted into "ticks", like a regular/discrete mouse wheel).
