### ISSUE TITLE
Crosshair disappears when switching from Eraser tool to other tools

### ISSUE THREAD

**Issue by arvz** [aseprite/aseprite#2696]
When you have Crosshair mode set to `Simple Crosshair` (because `Crosshair on Sprite` is horribly slow), if you have the Eraser tool activated, and then switch to other tools, e.g. Pencil or Marquee tool, your crosshair will disappear. You can get it back by mousing over UI elements that trigger a crosshair update, such as mousing over the preview window, or mousing over the Tools panel on the right. 

To repro:
1. Set Crosshair type to Simple Crosshair, Full Preview (Edit > Preferences > Cursor),
2. Switch tool to Eraser tool 
3. Switch to Pencil tool
4. Observe the Crosshair is not showing 
5. Move the mouse cursor outside of the drawing window (for example, up to the File/Edit/Sprite/etc menus), then move cursor back to the drawing window, and observe the crosshair is back

### Aseprite and System version
* Aseprite version: built from commit 5053443d21a5b80dd1f6a7159456a8e9e2027066
* System: Windows

**Comment by dacap** [comment]
Hi @arvz, this bug was fixed with ca41785f18ea70ccdad0f74b113739d7ebbe74ff (included in v1.2.27).
