### ISSUE TITLE
Problem with Compiling Aseprite (Big sur)

### ISSUE THREAD

**Issue by TheGamingDaily** [aseprite/aseprite#2701]
I get this error whenever I am building:

ninja: error: '/deps/skia/out/Release-x64/libskia.a', needed by 'bin/aseprite', missing and no known rule to make it

I checked that directory and that file is clearly there. I don't know what is happening and I have been struggling for a while now.
Here is an image: 
<img width="198" alt=":deps:skia:out:Release-x64:libskia a" src="https://user-images.githubusercontent.com/76263289/115131579-12580a00-9fc7-11eb-8119-ae4404f9dd4d.png">

I am using the medium tutorial (https://needoneapp.medium.com/create-an-auto-build-script-for-aseprite-on-mac-os-af8288b34f05) and the comment on this reddit post: https://www.reddit.com/r/PixelArt/comments/gbnb9x/how_to_compile_aseprite_macos/

Update: I am getting different error messages depending on what directory I use the command in terminal.

**Comment by OgGhostJelly** [comment]
> How did you fix it?!

I had the same error. For me it was a typo I made which caused it. So just make sure that `/deps/skia/out/Release-x64/libskia.a` is an actually valid path.

**Comment by BoneheadBreaker** [comment]
its not a path for me everything is there but not libskia.a please help
