### ISSUE TITLE
Unable to create a user-interface display.

### ISSUE THREAD

**Issue by yurivict** [aseprite/aseprite#2709]
Application fails at startup:
```
$ aseprite 
Unable to create a user-interface display.
Details: Unknown error
Error initializing module: gui
Error initializing module: gui $
```

(Please also note that the error message lacks the newline in the end of the last line).

### Aseprite and System version

* Aseprite version: 1.2.27
* System: FreeBSD 12.2

**Comment by lnslbrty** [comment]
Same issue here.

- Aseprite: b1203216beab85dbc1b1b195cfe50447953e12c8
- System: Debian 10.9

**Comment by dacap** [comment]
This problem means that Aseprite was compiled without Skia. `LAF_BACKEND` variable in the `CMakeCache.txt` file must be set to `skia` and the `SKIA_DIR` pointing to a Skia compilation. Please check the INSTALL guide:

  https://github.com/aseprite/aseprite/blob/main/INSTALL.md#linux-details

And the Skia compilation guide for Linux:

  https://github.com/aseprite/skia#skia-on-linux

**Comment by Xtendera** [comment]
Seems like a stale issue
