### ISSUE TITLE
Brush performance decreases over time

### ISSUE THREAD

**Issue by Enfyve** [aseprite/aseprite#2713]
When drawing with a brush, over time brush performance decreases to the point where there is considerable lag during strokes. This is most noticeable when drawing long arched strokes rapidly.  

The issue persists even after restarting the program. Restarting computer or not using the program for a long period resolves the issue. Restricting undo limit to 1MB and using old render engine do not resolve this

Below are examples of an 8 drawn at the same speed each about 2-5 minutes apart with normal usage in between: 

<div style="display:inline-block"><img src="https://user-images.githubusercontent.com/8909014/116634484-30f4c400-a92a-11eb-8f02-6a1f1d17603c.png" width="125" height="125">
<img src="https://user-images.githubusercontent.com/8909014/116634496-37833b80-a92a-11eb-8655-6153a6d9f471.png" width="125" height="125" >
<img src="https://user-images.githubusercontent.com/8909014/116634502-3e11b300-a92a-11eb-9f3d-450a5bde18d7.png" width="125" height="125">
<img src="https://user-images.githubusercontent.com/8909014/116634508-410ca380-a92a-11eb-91f5-41aea1af7187.png" width="125" height="125">
</div>

Issue persists across different programs (switching from portable to steam still results in laggy brush)

### Aseprite  and System version

* Aseprite version: 1.2.27 steam, 1.2.27 portable & d7a1c71 (latest) dev
* System: Windows 10

**Comment by dacap** [comment]
Hi @Enfyve, the most strange bit about this is that it's not solved re-starting Aseprite. Do you have a specific driver for a stylus/pen? (Wacom, XP-PEN, Huion, etc.)

**Comment by Enfyve** [comment]
Hi @dacap I do in fact have a wacom, These tests were done with mouse and keyboard though. I attempted to retest after unplugging my tablet and stopping the wacom tablet service (WTabletServicePro). The results were the same.

**Comment by dacap** [comment]
Thanks for the feedback @Enfyve, just in case, could you give a try to the 3 different modes in *[Edit > Preferences > Tablet](https://www.aseprite.org/docs/tablet/)*?

**Comment by Enfyve** [comment]
Same result across all 3, though it felt as though Wintab (direct packet processing) resulted in the most jagged lines.

Here is a demonstration of persistence after re-opening

https://user-images.githubusercontent.com/8909014/118203137-71276c80-b429-11eb-9fa8-9223bdb57b21.mp4

**Comment by dacap** [comment]
Reported for v1.3-beta too:
* https://community.aseprite.org/t/massive-drawing-lag-in-v1-3-beta3/9509
* https://community.aseprite.org/t/about-the-problem-of-slow-aseprite/9708

**Comment by dacap** [comment]
Developer info: Possible fix? (removing packet after WT_PROXIMITY and not processing WT_CSRCHANGE anymore)
https://github.com/aseprite/laf/commit/565e6bb6faa7ef33156cb4a94ecdafa6c9577004

Not sure but it might be a possibility.

**Comment by Enfyve** [comment]
@dacap I tested building with aseprite/laf@565e6bb but it seemed to have the same result. I did some basic profiling and it appears to be that upwards of 30% of frame-time is spent calling `onSetCursor` https://github.com/aseprite/aseprite/blob/6b2c296ef0c00a42d76d3f76ecf6efb50009a88a/src/app/ui/editor/editor.cpp#L2212

Removing that line results in working as expected with no performance loss. And upon restoring said line, the 'lag' is immediately present.

**Comment by dacap** [comment]
Hi @Enfyve, I've done the same profiling some weeks ago and reach the same conclusion. The issue is that [`CreateIconIndirect()` call](https://github.com/aseprite/laf/blob/11ffdbd9cc6232faaff5eecd8cc628bb5a2c706f/os/win/window.cpp#L777) is not a cheap operation.

I've some plans to improve this situation caching cursors.

**Comment by dacap** [comment]
I forgot to ask: it was originally reported that the stroke was slower and slower while using the program and only restarting solves the issue temporarily (?), and that doesn't make sense if the onSetCursor() is the issue. So I'm not sure if that is really this specific problem.

**Comment by Enfyve** [comment]
@dacap Yeah, restarting the program doesn't help, but restarting Windows does. So does changing the crosshair type. 

For me, removing the [call to SetCursor()](https://github.com/aseprite/laf/blob/55158abc7fc962498873d5a5a97f879cf62ba4fa/os/win/window.cpp#L648) resulted in no slowdown over time. But I haven't tested any alternatives to `CreateIconIndirect()`.

In either case, these are calls to user32, so I'd be optimistic in declaring these external calls as the culprit and why the issue persists despite restarting aseprite.

**Comment by dacap** [comment]
Thanks for the feedback @Enfyve.

It's really interesting that commenting out `SetCursor()` doesn't show the slowdown, so `CreateIconIndirect()` might not be the problem, but `SetCursor()`.

**Comment by dacap** [comment]
@Enfyve I've just pushed a possible fix for this issue (two commits, one in laf and other in aseprite). A new `os::Cursor` was introduced to cache mouse cursors. I hope it finally fixes this problem. Thanks for your help!

**Comment by Enfyve** [comment]
@dacap tested this for a good 20 minutes, no noticeable slowdown. Looks like we can close this as resolved. Thanks a ton! ;)

**Comment by dacap** [comment]
Thanks for your confirmation @Enfyve 🙌  I'm really happy to hear that!
