### ISSUE TITLE
Aseprite not opening in aseprite-git AUR package

### ISSUE THREAD

**Issue by MintMellowCat** [aseprite/aseprite#2717]
I am using arch linux. And I just installed the aseprite-git AUR package, but it wouldn't start. Error message:

`/usr/include/c++/10.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = long unsigned int; _Alloc = std::allocator<long unsigned int>; std::vector<_Tp, _Alloc>::reference = long unsigned int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
[1]    57780 abort (core dumped)  aseprite`

**Comment by dacap** [comment]
Hi, sorry but we are not distributing Aseprite through the AUR.
