### ISSUE TITLE
Aseprite is not installed on arch.

### ISSUE THREAD

**Issue by Maxython** [aseprite/aseprite#2718]
**Hello everyone**, a 404 error occurs during aseprite installation (one file is not installed).  There is no such file in the googlesource server.  
### Here are screenshots for full details.
![IMG_20210506_204500_184](https://user-images.githubusercontent.com/60917834/117364033-18565200-aec6-11eb-8e7d-3e65c2485afe.jpg)
![IMG_20210506_204504_221](https://user-images.githubusercontent.com/60917834/117364054-1e4c3300-aec6-11eb-8933-f60beb563cc2.jpg)
-----
What to do?

**Comment by dacap** [comment]
Hi @Maxython, please check the INSTALL guide in this repo in case that you want to compile Aseprite. We don’t support Arch distro method of distribution, and they are redistributing Aseprite illegally.

**Comment by Maxython** [comment]
Ok, thank.
