### ISSUE TITLE
Compilation error due to Missing file that I cant find in the github repositories

### ISSUE THREAD

**Issue by TroubleTruffle** [aseprite/aseprite#2726]
Describe your bug report or feature request here
...
**FAILED**: laf/gfx/CMakeFiles/laf-gfx.dir/packing_rects.cpp.obj
C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.299\bin\Hostx64\x64\cl.exe  /nologo /TP -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_WIN32 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -DUNICODE -DWINVER=0x0A00 -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0A00 -I..\third_party\zlib -Ithird_party\zlib -I..\third_party\libpng -Ithird_party\libpng -I..\third_party\libwebp\src -I..\third_party\tinyxml -I..\third_party\pixman\pixman -I. -I..\third_party\freetype2\include -I..\third_party\harfbuzz\src -I..\third_party\giflib\lib -I..\third_party\jpeg -I..\third_party\curl\include -I..\third_party\simpleini -I..\src -I..\laf -Ilaf -I..\laf\third_party\stringencoders\src -IC:\deps\skia -I..\laf\SKIA_CONFIG_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_CORE_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_UTILS_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_CODEC_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_GPU_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_GPU2_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_SKCMS_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_ANGLE_INCLUDE_DIR-NOTFOUND /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MT /Zi /O2 /Ob1 /D NDEBUG /showIncludes /Folaf\gfx\CMakeFiles\laf-gfx.dir\packing_rects.cpp.obj /Fdlaf\gfx\CMakeFiles\laf-gfx.dir\laf-gfx.pdb /FS -c ..\laf\gfx\packing_rects.cpp
c:\aseprite\laf\gfx/region_skia.h(17): fatal error C1083: Cannot open include file: 'SkRegion.h': No such file or directory

[587/1502] Building CXX object laf\gfx\CMakeFiles\laf-gfx.dir\region_skia.cpp.obj
**FAILED**: laf/gfx/CMakeFiles/laf-gfx.dir/region_skia.cpp.obj
C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.299\bin\Hostx64\x64\cl.exe  /nologo /TP -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_WIN32 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -DUNICODE -DWINVER=0x0A00 -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0A00 -I..\third_party\zlib -Ithird_party\zlib -I..\third_party\libpng -Ithird_party\libpng -I..\third_party\libwebp\src -I..\third_party\tinyxml -I..\third_party\pixman\pixman -I. -I..\third_party\freetype2\include -I..\third_party\harfbuzz\src -I..\third_party\giflib\lib -I..\third_party\jpeg -I..\third_party\curl\include -I..\third_party\simpleini -I..\src -I..\laf -Ilaf -I..\laf\third_party\stringencoders\src -IC:\deps\skia -I..\laf\SKIA_CONFIG_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_CORE_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_UTILS_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_CODEC_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_GPU_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_GPU2_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_SKCMS_INCLUDE_DIR-NOTFOUND -I..\laf\SKIA_ANGLE_INCLUDE_DIR-NOTFOUND /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MT /Zi /O2 /Ob1 /D NDEBUG /showIncludes /Folaf\gfx\CMakeFiles\laf-gfx.dir\region_skia.cpp.obj /Fdlaf\gfx\CMakeFiles\laf-gfx.dir\laf-gfx.pdb /FS -c ..\laf\gfx\region_skia.cpp

c:\aseprite\laf\gfx/region_skia.h(17): fatal error C1083: Cannot open include file: 'SkRegion.h': No such file or directory
[588/1502] Building CXX object third_party\fmt\CMakeFiles\fmt.dir\src\format.cc.obj
ninja: build stopped: subcommand failed.
...

### Aseprite and System version

* Aseprite version: Aseprite v1.2.27 source code
* System: Windows 10

**Comment by Enfyve** [comment]
@TroubleTruffle `SkRegion.h` is from the skia library. That needs to be included with your build

**Comment by TroubleTruffle** [comment]
> @TroubleTruffle `SkRegion.h` is from the skia library. That needs to be included with your build
I actually have Skia included in /deps/...  

I was actually looking for skregion in the wrong area. I had an error earlier about skia not being linked so I think I already linked it since the error no longer happens but it cant find skregion even if I see it in my file browser
