### ISSUE TITLE
180° Rotation inaccuracy

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#2738]
If you make an 8x8 image and select the whole canvas, then rotate it while holding the snap to angle action modifier it will lose a line of pixels when rotated to 180 degrees.

![dsaasd](https://user-images.githubusercontent.com/17066488/119906346-563b1900-bf4e-11eb-8e70-23f2457d50fd.gif)

Windows 10
Aseprite v1.3-beta1 (bug not present in 1.2.27)

**Comment by dacap** [comment]
Fixed in #3041
