### ISSUE TITLE
"Canvas size.." "Trim content outside the canvas" sometimes clears tilemap layer

### ISSUE THREAD

**Issue by not-surt** [aseprite/aseprite#2739]
Using the "Canvas size.." function with "Trim content outside the canvas" enables clears tilemap layers in certain circumstances.

What those precise circumstances are I haven't been able to figure, but the attached aseprite file ([test.zip](https://github.com/aseprite/aseprite/files/6560318/test.zip)) displays the problem when dividing width by two and using centre positioning, however it doesn't occur when using top-left positioning.

I thought it might be caused by the new image boundary not matching perfectly with tile boundaries but it has occurred for me in instances where they are matched, even when the canvas size remains unchanged.

### Aseprite and System version

* Aseprite version: v1.3 beta1 Steam
* System: Windows 10 Pro 10.0.18363 Build 18363

**Comment by iamOgunyinka** [comment]
I believe this bug has been fixed by @Gasparoken [here](https://github.com/aseprite/aseprite/commit/f32393bb3138bbee86e2f6d3dd448e67f2f96ed6).

**Comment by Gasparoken** [comment]
Thanks @not-surt and thanks @iamOgunyinka! Yes, this was solved on #2942 by https://github.com/aseprite/aseprite/commit/f32393bb3138bbee86e2f6d3dd448e67f2f96ed6
