### ISSUE TITLE
Pixel-perfect doesn't work in Manual tile mode

### ISSUE THREAD

**Issue by TaperingBirch** [aseprite/aseprite#2741]
Pixel-perfect is always off in manual tile mode, even if the toggle is turned on.

### Reproduce:
1. Make a tilemap layer and a tileset, filled with whatever tiles(doesn't matter what, as long as they have some filled pixels in them, not completely transparent)
2. Place one tile from the tileset on the tilemap with `space+tab` or the button all the way on the left above the color palate
3. Switch to manual mode using the button above the color palate or `space+1`
4. Turn Pixel-perfect on
5. Draw a circle on top of a tile using the brush tool
6. The circle looks as if pixel-perfect was turned off

### Aseprite and System version

* Aseprite version: v1.3-beta1-x64, Steam/beta
* System: Windows 10, 20H2, 19042.985

**Comment by dacap** [comment]
Hi @TaperingBirch, thanks for this bug report. Actually a known issue and it's something we are working on to fix ASAP in the following v1.3 betas.

**Comment by dacap** [comment]
This will be available in the next beta.
