### ISSUE TITLE
[Feature] Deluxe Paint-style brush selector tool

### ISSUE THREAD

**Issue by not-surt** [aseprite/aseprite#2747]
I really miss having a brush selector/grab tool in the style of Deluxe Paint, GrafX2, Pro Motion and other old-school pixel editors.

Essentially it works the same as the marquee tool followed by the new brush command.
It's only one extra action per invocation so it may not seem like much there's point, but it does make a difference when it's a core part of your pixeling workflow.

Doesn't even need a toolbar button, just hotkey invocation (even better if modeless by just holding hotkey, mouse click, drag and release, then return to previously selected tool with new brush active) would make me happy.

**Comment by dacap** [comment]
Hi @not-surt, actually when you use Ctrl+B (Edit > New Brush) without a selection, you can select a rectangular area and the new brush will be created. Not sure if that is the expected behavior in this issue.

**Comment by not-surt** [comment]
Awesome, that's exactly what I wanted!
Cheers!
