### ISSUE TITLE
Pixel-perfect not working on this regular layer

### ISSUE THREAD

**Issue by not-surt** [aseprite/aseprite#2748]
This file ([pixelperfect.zip](https://github.com/aseprite/aseprite/files/6565435/pixelperfect.zip)) contains a regular layer where pencil tool pixel-perfect option has no effect.
Pixel-perfect works as expected on newly created regular layers.
If I use the "Canvas size..." function with "Trim content outside the canvas" option enabled even without actually changing the canvas size pixel-perfect will then work as expected, but if "Trim content outside the canvas" option is not enable enabled pixel-perfect continues to have no effect.

Can't remember, but the history of the affected layer may possibly include a conversion from a tilemap layer so could possibly be related to #2741 and probably been cropped and moved.

### Aseprite and System version

* Aseprite version: v1.3 beta1 Steam
* System: Windows 10 Pro 10.0.18363 Build 18363

**Comment by dacap** [comment]
Hi @not-surt, today we've released [Aseprite v1.3-beta2](https://community.aseprite.org/t/aseprite-v1-3-beta1/9222/1) which should have this issue fixed thanks to @martincapello.
