### ISSUE TITLE
File dialogs come up huge

### ISSUE THREAD

**Issue by jimmac** [aseprite/aseprite#2756]
I'm using a super wide screen (5120x1440) and file dialog comes up super large. The size is not stored after I resize it and close and bring up the dialog again.

* Aseprite version: v1.3-beta1-x64 off of steam
* System: Fedora 34 Silverblue (Weston/Wayland).

![Screenshot from 2021-06-03 22-20-59](https://user-images.githubusercontent.com/14821/120706968-09a98d80-c4ba-11eb-9899-c7788de85832.png)

**Comment by jimmac** [comment]
Tested and reproduced in an X11 session. Unrelated to wayland/weston as I initially feared.

**Comment by dacap** [comment]
Hi 👋  this will be fixed saving/restoring the dialog position, so at least one time the dialog will need to be resized. But after that its position will be re-used.
