### ISSUE TITLE
I'm having an error compiling the aseprite

### ISSUE THREAD

**Issue by ck-linuxx** [aseprite/aseprite#2761]
![Captura de tela de 2021-06-08 13-37-55](https://user-images.githubusercontent.com/64222532/121224483-fd795380-c85e-11eb-92d3-80bca1e3d9b3.png)

**Comment by mohad12211** [comment]
Your cmake version is 3.12, the  minimum version required is 3.16. Update cmake.

**Comment by ck-linuxx** [comment]
thanks!!
