### ISSUE TITLE
Bugs with native windows on some Linux distros

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#2777]
- https://community.aseprite.org/t/menu-bar-appearing-in-separate-windows-in-v-1-3-beta-4-on-linux/9592
- ~~https://community.aseprite.org/t/new-windows-are-overly-large-linux-aseprite-1-3-beta1-4/9627~~ now in #3118 

Reported WM:
* Chrome OS
* KWin (KDE Plasma 5.22)
* XFCE (Manjaro Linux)

**Comment by twslankard** [comment]
I am affected by the separate windows issue (using XFCE 4.14, Xubuntu.) I have also observed crashes to desktop when closing the menu windows. Please let me know if I can be of any debugging assistance.

**Comment by dacap** [comment]
Closed with https://github.com/aseprite/laf-beta/commit/55f04ba7b04e2b75c6022913792c93ec334fe68e

**Comment by dacap** [comment]
Closed with https://github.com/aseprite/laf/commit/55f04ba7b04e2b75c6022913792c93ec334fe68e
