### ISSUE TITLE
Aseprite causes miscellaneous crashes to programs around it

### ISSUE THREAD

**Issue by LavenderTheGreat** [aseprite/aseprite#2785]
Been happening for a while now. Aseprite has a tendency to crash Blender and make Adobe Photoshop CS2 unbootable. None of these programs get far enough to do a crash log. Aseprite will eventually start crashing too. The Aseprite log shows no errors either. I tried to see if it was due to initialisation errors on the wintab driver or similar, but stopping my tablet drivers doesn't do anything. I've tried pausing my antivirus (Kaspersky) but that hasn't changed anything either. Medibang seems to work regardless so I'm not sure if its tablet specific.

None of the programs work even after giving it a bit after Aseprite has failed to open.

I'll update this thread as I try more fixes.

Command line log(s) from Blender: https://gist.github.com/LavenderTheGreat/004005a4715024e0195737118d85c1ef
Logs from Aseprite: https://gist.github.com/LavenderTheGreat/e0c53e2f43de51f08ac740c9a5e5fe4b

### Aseprite and System version

* Aseprite version: 1.2.27
* System: Windows 10

**Comment by dacap** [comment]
Hi @LavenderTheGreat, highly probable that it's an issue related with Wintab. Do you have the official version of Aseprite or a special build from the source code?

**Comment by LavenderTheGreat** [comment]
I'm using the official version from Steam.

**Comment by LavenderTheGreat** [comment]
Switched to Windows Ink, crashes on Aseprite and Blender are not happening anymore. Tried saving in Blender which usually invokes a crash (for some reason) and its going fine, closed and reopened it too and its fine. I'm guessing that it is most likely something happening prior to a second launch with Wintab, especially since its only happening with art programs and on Wintab.

**Comment by dacap** [comment]
Actually this might be related to some `wintab32.dll` crashes (problems using the API, bugs about how Aseprite uses a specific implementation of the the Wintab32 API by some vendors).

We've made some changes in the usage of the `wintab32.dll` API in v1.2.28 and v1.3-beta5, we're not sure if this is fixed, but we didn't receive a crash yet related to this. We'll see.

**Comment by dacap** [comment]
We can confirm that there are a lot of crashes related to buggy wintab32.dll, and it's even worse on v1.3 as it associates a wintab context (calling WTOpen) with each window (e.g. each combobox popup, or tooltip, or menu popup, etc.). The only solution to move forward and make v1.3 the new stable branch will be to make the Windows Pointer API the default option (in this way we avoid wintab as much as possible and the user still have the option to switch to wintab if it's required, which in most case it shouldn't). We'll give a try to this new default in the next release.
