### ISSUE TITLE
Aseprite fails to compile whether x64 or x86 version of skia is used 

### ISSUE THREAD

**Issue by daresom** [aseprite/aseprite#2795]
Hello, I am trying to compile aseprite to use for pixel art. Everything goes on fine until I try to run ``ninja aseprite`` When I use the x64 version I get

 ```LINK : warning LNK4044: unrecognized option '/LINK'; ignored
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification
D:\apps\vs\VC\Tools\MSVC\14.28.29333\lib\x64\wsetargv.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'
``` 

So I then try to compile aseprite with the x86 version of skia. But I still get an error 

``ninja: error: 'C:/deps/skia/out/Release-x64/skshaper.lib', needed by 'bin/aseprite.exe', missing and no known rule to make it``

I used the same command for ``cmake`` but I changed the ``x64`` to ``x86`` So now it looks like this

``cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x86 -DSKIA_LIBRARY=C:\deps\skia\out\Release-x86\skia.lib -G Ninja ..``

I am using a 64 bit laptop that runs on windows 10.

**Comment by Nhalrath** [comment]
Did you make sure that those directories exists?

`call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" -arch=x64` <- make sure this last argument matches your libraries and machine type.

**Comment by daresom** [comment]
> Did you make sure that those directories exists?
> 
> `call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" -arch=x64` <- make sure this last argument matches your libraries and machine type.

The bat file technically exists but is in a different folder because I customized my visual studio installation. On my computer I do this 

``call "D:\apps\vs\Common7\Tools\VsDevCmd.bat" -arch=x64`` @Nhalrath

**Comment by Nhalrath** [comment]
@daresom I'm referring to your Skia library whether it exists or not. Also, what version of Skia did you download? the x86 or x64 one?

**Comment by daresom** [comment]
@Nhalrath Oh Im sorry. The directories do exist. ``C:\deps\skia\out\Release-x86`` or ``C:\deps\skia\out\Release-x64`` exists. I downloaded the x64 version but after I got this error

```
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification
D:\apps\vs\VC\Tools\MSVC\14.28.29333\lib\x64\wsetargv.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'
```

Then I installed the x86 version.

**Comment by Nhalrath** [comment]
All right, let's go back to the basics as instructed [here](https://github.com/aseprite/aseprite/blob/main/INSTALL.md).
1. You either downloaded the source code from the latest release or cloned from the main branch.

    If you're cloning the repo, make sure to clone it recursively. I made that mistake too before, and wondered why the build always fail.

    Make sure that the build is passing as shown in the README.
![image](https://user-images.githubusercontent.com/69453927/123729478-9bdd5f80-d8c7-11eb-9f02-13fd567f15a9.png)

2. Make sure you have the prerequisites for Windows. `CMake 3.14+`, `Ninja`, `Visual Studio 2019`, and `Windows 10.0.18362.0 SDK`.

3. A build of Skia or the pre-built package(recommended).

    Let's assume that your target is x86 and the Skia library you have is also x86, so the path for Skia library should be in `C:\deps\skia\out\Release-x86`

4. Now everything's all settled, it's time to build Aseprite!

    Just open a regular cmd and call the Visual Studio command line. In your case, it should be `call "D:\apps\vs\Common7\Tools\VsDevCmd.bat" -arch=x86`.

    Make sure that your current directory is in the build folder of Aseprite. `C:/dev/Aseprite/build` or wherever your Aseprite folder is.

    Make sure that the arguments you passed to CMake is correct. `cmake -DCMAKE_BUILD_TYPE=Release -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x86 -DSKIA_LIBRARY=C:\deps\skia\out\Release-x86\skia.lib -G Ninja ..`

    And lastly, `ninja aseprite`.

If everything goes well, the following folders and files should be in your bin folder, like this:
![image](https://user-images.githubusercontent.com/69453927/123731746-5c187700-d8cb-11eb-89b3-e9bebc916ae2.png)
(the last 2 might be different for you tho.)

Please do tell me if they worked for you, @daresom.

**Comment by daresom** [comment]
Oh my god thank you, it worked this time. I think when compiling the x86 version I called ``"D:\apps\vs\Common7\Tools\VsDevCmd.bat" -arch=x64`` I tried it now and it works. I was also getting an error where aseprite.exe would not compile, I had to turn off my antivirus. Thank you very much!
