### ISSUE TITLE
Toolbar position

### ISSUE THREAD

**Issue by medanimations** [aseprite/aseprite#2805]
Hey, it would be cool if there is a toolbar-to-the-left function. This will be helpful for users who use Flash or Photoshop, because it will make it easier to them.
Also what about customizing the toolbar by adding non-added features like the Text tool ?

* Aseprite version: 1.3 beta4, Steam version
* System: Windows

**Comment by dacap** [comment]
Hi @medanimations, actually this is duplicated of #28 and #518
