### ISSUE TITLE
Regression saving certain GIF files when disposing frames

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#2806]
Reported here:
https://community.aseprite.org/t/transparent-gif-error-on-beta-v1-3-beta-version-preview-features-steam-windows-10/9784

Maybe some problems with the disposal method of the old frames (maybe the previous frame content is not cleared?)

**Comment by dacap** [comment]
Probably related report on Twitter: https://twitter.com/undeterminedgk/status/1410462239283290115

**Comment by Gasparoken** [comment]
I think I solved it. Tomorrow I'll test it with others GIFs.

**Comment by dacap** [comment]
There is a file attached in the community topic too: https://community.aseprite.org/t/transparent-gif-error-on-beta-v1-3-beta-version-preview-features-steam-windows-10/9784/4
