### ISSUE TITLE
Detect webp files by file content (e.g. sometimes a .gif can be a .webp)

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#2807]
Reported here: https://community.aseprite.org/t/error-loading-gif-header/9794 
The GIF file was sent to support: https://igarastudio.zendesk.com/agent/tickets/2433

**Comment by Gasparoken** [comment]
The GIF on https://igarastudio.zendesk.com/agent/tickets/2433 has some special issue. Safari and Discord cannot play it. Chrome can play it.

**Comment by dacap** [comment]
In this case the `DGifOpenFileHandle()` fails so it's something to solve in the giflib (or update the module). I'll see this issue later.

**Comment by dacap** [comment]
@Gasparoken Unrelated to this, I saw [this patch](https://github.com/aseprite/giflib/commit/59f36d528f9ef52de95a799872af7e956a024576) in the giflib but it was never used (main or beta). I think I'll rollback that patch or leave it in another branch of the giflib project.

**Comment by Gasparoken** [comment]
It's okay. Go ahead.

**Comment by dacap** [comment]
About this issue, the file has a `.gif` extension but it's a `.webp` file actually. So I'll solve this problem from [`detect_format_by_file_content_bytes()`](https://github.com/aseprite/aseprite/blob/f99b5218b9a8896c54e0d8e362b4824c33129036/src/dio/detect_format.cpp#L34).
