### ISSUE TITLE
Missing strings in language file

### ISSUE THREAD

**Issue by lufog** [aseprite/aseprite#2809]
The following strings are missing in the standard `en.ini` language file:

<details>
<summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/10379487/124368108-4eb21280-dc66-11eb-96b0-4e8d5031fead.png)

</details>

<details>
<summary>Screenshot 2</summary>
  
![image](https://user-images.githubusercontent.com/10379487/124368117-730def00-dc66-11eb-94de-5329bb106484.png)
  
</details>

<details>
<summary>Screenshot 3</summary>
  
![image](https://user-images.githubusercontent.com/10379487/124368122-9c2e7f80-dc66-11eb-81d2-99d4dbecef60.png)
  
</details>

<details>
<summary>Screenshot 4</summary>
  
![image](https://user-images.githubusercontent.com/10379487/124368133-b8cab780-dc66-11eb-8d3a-c903d6dae158.png)
  
</details>

<details>
<summary>Screenshot 5</summary>
  
![image](https://user-images.githubusercontent.com/10379487/124368142-f16a9100-dc66-11eb-9d7d-79ca24946632.png)
  
</details>

<details>
<summary>Screenshot 6</summary>
  
![image](https://user-images.githubusercontent.com/10379487/124368183-427a8500-dc67-11eb-8ca8-0c4bba801833.png)
  
</details>

<details>
<summary>Screenshot 7</summary>
  
![image](https://user-images.githubusercontent.com/10379487/124368195-532afb00-dc67-11eb-9776-9cdde5b329ab.png)
  
</details>

<details>
<summary>Screenshot 8</summary>
  
![image](https://user-images.githubusercontent.com/10379487/124368226-c6347180-dc67-11eb-8228-49cc6f036736.png)
  
</details>

What prevents them from being translated.

### Aseprite and System version

* Aseprite version: 1.2.27, portable dev
* System: Windows 11

**Comment by puddiCria** [comment]
Hi there 👋

I don't know if it was necessary but I took a lot of screenshots xD
![Screenshot 01](https://user-images.githubusercontent.com/87098595/125713517-2fe0a778-36ac-44b3-91bb-227e20cd9029.PNG)
![Screenshot 2](https://user-images.githubusercontent.com/87098595/125713546-0c4134e4-4ec0-4715-a29d-21b14a31112a.PNG)
![Screenshot 16 PNG](https://user-images.githubusercontent.com/87098595/125713574-63ecdb41-99be-4a79-ae50-cf9a872279f3.png)
![Screenshot 17 PNG](https://user-images.githubusercontent.com/87098595/125713575-67ff646f-b9ec-48d3-b738-278c427d96d0.png)
![Screenshot 03](https://user-images.githubusercontent.com/87098595/125713579-37f658a0-8f52-463c-b829-81a04a7cede6.PNG)
![Screenshot 04](https://user-images.githubusercontent.com/87098595/125713581-d8075ffe-5f39-4d8d-b861-0c346c37194e.PNG)
![Screenshot 05 - Workspace 01](https://user-images.githubusercontent.com/87098595/125713582-cd82925e-7e1e-420a-91c3-8439afbbd953.PNG)
![Screenshot 05 - Workspace 02](https://user-images.githubusercontent.com/87098595/125713584-f55b431c-b3d3-4b8b-8411-c2086f39c365.PNG)
![Screenshot 06](https://user-images.githubusercontent.com/87098595/125713587-29e5c0a7-6ff6-4fad-9c1f-c34b211f6cd2.PNG)
![Screenshot 07 PNG](https://user-images.githubusercontent.com/87098595/125713588-25d85d42-d64b-4daa-8642-683401ad5efe.png)
![Screenshot 08 PNG](https://user-images.githubusercontent.com/87098595/125713590-9cb99de2-a828-4a26-b2d0-07d4fdb60d93.png)
![Screenshot 08-3 PNG](https://user-images.githubusercontent.com/87098595/125713591-593d8933-85a3-47b9-b905-8305a5bf4d9e.png)
![Screenshot 09 PNG](https://user-images.githubusercontent.com/87098595/125713592-cba81125-5de9-421f-87ce-7ce742572bd1.png)
![Screenshot 10 PNG](https://user-images.githubusercontent.com/87098595/125713593-acba9bb7-260c-45d0-b404-191bf22b1c9b.png)
![Screenshot 11 PNG](https://user-images.githubusercontent.com/87098595/125713594-030324c6-bdc3-45a6-866f-5ef2615d1ff7.png)
![Screenshot 12 PNG](https://user-images.githubusercontent.com/87098595/125713595-7090af2e-856f-4e37-86b1-5b16c3ca32df.png)
![Screenshot 13 PNG](https://user-images.githubusercontent.com/87098595/125713597-eee131a7-a9e8-49f6-a4f6-a456a8296a98.png)
![Screenshot 14 PNG](https://user-images.githubusercontent.com/87098595/125713598-94820e97-dd76-45d6-bc65-5fe0329183f2.png)
![Screenshot 15 PNG](https://user-images.githubusercontent.com/87098595/125713600-6e97c62a-af56-40d1-8932-be1237b01be0.png)

**Comment by puddiCria** [comment]
If I find any more translation bugs, I comment here

**Comment by puddiCria** [comment]
![image](https://user-images.githubusercontent.com/87098595/125713815-e2f1a6c4-d003-4518-8c7d-02f48322c7f9.png)

**Comment by dacap** [comment]
Thanks for the help @puddiCria,  I'll try to take this issue in the near future and update the en.ini in the following v1.2 and v1.3 versions to include these missing strings. Any other text you find it would be really useful to have a record.

**Comment by iamOgunyinka** [comment]
One (unusual) behavior I have noticed is that if you switched from language `A` to language `B` at runtime, then go to the Keyboard Shortcuts window, the `Commands` subsection of the new window will contain mixture of words from language `A` and language `B`.

For example, if your last language before opening Aseprite is Dutch, then you switch from Dutch to English. Pressing `Shift` + `Ctrl` + `Alt` + `K` will open the Key shortcuts window. In the `Commands` section, the `Action` column of the subsection will contain a mix of Dutch and English (like in the picture below):

![image](https://user-images.githubusercontent.com/4146085/147648760-78f52b8d-9f92-47a6-a5e9-b7f97f5e1da0.png)
