### ISSUE TITLE
Price can be higher

### ISSUE THREAD

**Issue by tony** [aseprite/aseprite#2817]
Describe your bug report or feature request here

re: https://github.com/NickeManarin/ScreenToGif/issues/934

The price for the app is too low compared to the comprehensiveness / user friendliness

Similar apps are going for [twice the price](https://store.steampowered.com/app/671190/Pro_Motion_NG/)

Marking down the app/game doesn't necessarily make it more likely to sell in people's eyes. This application has been in development for years and is stable. Having a higher price and being firm on it (e.g. not doing -80% off or going from $50 -> $10) shows resilience and makes people value the app more

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by dacap** [comment]
Hi @tony, at the moment we don't have plans to change the price of Aseprite.

Just in case: nobody knows the "perfect price" for a product. Nobody knows what is the perfect price that will bring you most of the users/word-spreading/most profit at the same time.

**Comment by tony** [comment]
nice. maybe im feeling generous today. good luck on the project, David!
