### ISSUE TITLE
"Automating the process" seems not applicable to Steam edition

### ISSUE THREAD

**Issue by exoego** [aseprite/aseprite#2821]
I would like to save images in 2x and 3x scales.
I found ["Automating the process"](https://www.aseprite.org/docs/cli/#automating-the-process) for such scenario.

The document assumes that the binary of Aseprite is installed in `/Applications/Aseprite.app/Contents/MacOS/aseprite`.
However, I can only found `/Users/USER-NAME-HERE/Applications/Aseprite.app/Contents/MacOS/run.sh`, which seems just a Steam launcher and does not support automating.

Is it possible to automating the process when Aseprite is installed via Steam ?

### Aseprite and System version

* Aseprite version: 1.2.27, Steam
* System: macOS 11.4

**Comment by dacap** [comment]
Hi @exoego, in the case of Steam, you have to use the direct path to the executable file. This should work:

`~/Library/Application Support/Steam/steamapps/common/Aseprite/Aseprite.app/Contents/MacOS/aseprite`

**Comment by exoego** [comment]
Thanks !!
The binary was found there and automation works 👍 
I opened a PR to update documentation in https://github.com/aseprite/docs/pull/8
