### ISSUE TITLE
error: no visible @interface for 'WindowOSXObjc' declares the selector 'convertPointFromScreen:'

### ISSUE THREAD

**Issue by ryandesign** [aseprite/aseprite#2838]
Hi,

I'm using macOS 10.13.6 and Xcode 9.4.1 (which contains the 10.13.4 SDK). Aseprite 1.2.27 compiled and worked fine on this system but compiling Aseprite 1.2.28 failed with this error:

```
aseprite/laf/os/osx/window.mm:408:47: error: no visible @interface for 'WindowOSXObjc' declares the selector 'convertPointFromScreen:'
```

Apple claims that `convertPointFromScreen:` is [available on macOS 10.12](https://developer.apple.com/documentation/appkit/nswindow/2967180-convertpointfromscreen) and later but it does not appear to be in the SDK headers prior to the 10.14 SDK. (It seems to be fairly typical that Apple neglects to put some functions into the SDK headers until a version or two later.)

I was able to compile Aseprite 1.2.28 on this system by applying this patch:

```diff
--- aseprite/laf/os/osx/window.h.orig	2021-07-08 19:36:23.000000000 -0500
+++ aseprite/laf/os/osx/window.h	2021-07-16 00:30:51.000000000 -0500
@@ -52,6 +52,9 @@
 - (void)setMousePosition:(const gfx::Point&)position;
 - (BOOL)setNativeCursor:(os::NativeCursor)cursor;
 - (BOOL)canBecomeKeyWindow;
+#if MAC_OS_X_VERSION_MAX_ALLOWED < 101400
+- (NSPoint)convertPointFromScreen:(NSPoint)point NS_AVAILABLE_MAC(10_12);
+#endif
 @end
 
 using WindowOSXObjc_id = WindowOSXObjc*;
```

This simply adds the prototype for `convertPointFromScreen:` to your NSWindow subclass if the SDK version is less than 10.14. (I copied the line from the 10.14 SDK.)

I could not find any other similar code in Aseprite so I don't know if you want to add such code to maintain compatibility with older SDKs. I recognize that your [install instructions](https://github.com/aseprite/aseprite/blob/main/INSTALL.md) say:

> On macOS you will need macOS 10.15 SDK and Xcode 11.2.1 (older versions might work).

I recognize that Apple recommends compiling your app with the latest SDK, and that recommendation works well for an app that only the developer compiles. But since Aseprite is also intended to be compiled by its users, it can be nice not to impose too stringent requirements on them. For example, a user wishing to use Aseprite on macOS 10.12 might not have access to a newer system to compile it on that would be compatible with the newer Xcode version that has the 10.14 SDK.

As an additional note, the fact that you are now using `convertPointFromScreen:` in laf probably means that your program is incompatible with macOS versions earlier than 10.12. Your [skia compilation instructions](https://github.com/aseprite/skia#skia-on-macos) suggest adding the flag `-mmacosx-version-min=10.9` and your [aseprite compilation instructions](https://github.com/aseprite/aseprite/blob/main/INSTALL.md#macos-details) suggest using the flag `-DCMAKE_OSX_DEPLOYMENT_TARGET=10.9`. If the program cannot run prior to 10.12 now due to using `convertPointFromScreen:`, then those 10.9s could be changed to 10.12. Alternately, you could maintain compatibility with older systems by changing the code to use `convertPointFromScreen:` only on 10.12 or later, and using some alternative equivalent implementation using older OS functions on older systems (and there can be value in that since not all users wish to or are able to upgrade to newer OS versions).

### Aseprite and System version

* Aseprite version: 1.2.28 compiled from source
* System: macOS 10.13.6

**Comment by dacap** [comment]
Hi @ryandesign, thanks for reporting this. Actually this is not an issue in v1.2.28 (because the function is not used yet), but it's a problem in the beta version (because the function is used to start moving custom windows). I'll fix it.
