### ISSUE TITLE
libpng: Wrong palette index exceeding num_palette

### ISSUE THREAD

**Issue by metnias** [aseprite/aseprite#2842]
I was getting this same issue in v1.3 beta so I reverted back to v1.2
but as some of the features are backported to v1.2 now, this critical bug followed
and now I cannot export my work anymore.

As I draw, I change the palette with a multiple layered project,
and use the transparent colour of the current palette to erase which reliably causes the issue.
Exporting to PNG does not work at all,
and exporting to other formats also breaks the image cause some of the layers now are no longer transparent.

Now I have to screenshot the program and trim the image :(

### Aseprite and System version

* Aseprite version: 1.2.28-x64, Steam
* System: Windows 10

**Comment by dacap** [comment]
Hi @metnias, could you please share with us privately a .aseprite file that you use to export to .png to support@aseprite.org? So we can check this issue you are talking about (we didn't receive other bugs report about this).

**Comment by metnias** [comment]
Just sent the aseprite files that are causing issues to support@aseprite.org.
Thanks for the quick response!

**Comment by dacap** [comment]
@metnias I'm seeing your files and this was not caused because we back-ported some features from v1.3 to v1.2. Aseprite v1.2.27 already showed this message so I'm a little confused. What is the Aseprite version that you was previously using? Maybe you have been using an even older Aseprite version? (v1.2.9 or v1.1.13? which are still available on Steam)

We'll check if we can fix some of these use cases for the following versions. It looks like the Flatten command and Export should replace any index outside the palette range with the transparent index (or interpret it as transparent). The only problem could appear if the transparent index is really visible in the final render and the index is outside the palette range (probably in that only case we should expand the palette with an extra index to represent the transparent color).

> For developer reference, the ticket is: https://igarastudio.zendesk.com/agent/tickets/2497

**Comment by metnias** [comment]
For `029 reachout.aseprite`, that's an older project but also having a presumably similar issue so I wanted to include it in this report. For reference, it's made on June 12th, but I was testing v1.3 beta from time to time before so I don't remember which version I used for this project. I'm sorry for the confusion.

But `serverlogo 2107.aseprite` is created earlier today with the latest stable version on Steam (1.2.28-x64) and broken even more, which is why I've decided to report this.

I'd just assumed this is because of backporting because I hadn't seen `libpng: Wrong palette index exceeding num_palette` in earlier version v1.2 but only with v1.3beta, in my personal experiences.

**Comment by dacap** [comment]
I'll try to take this issue in a couple of weeks. My recommendation is that you should use one transparent index over all layers on indexed mode (at least Aseprite was made to work in that way) and the palette should be big enough to include the transparent index (so using indexes outside the range is not allowed). Anyway I'll try to see if some support for these use cases can be added.

**Comment by metnias** [comment]
Index 0 is usually the one and only transparent index for my projects.
I've never intended to use different transparent indexes for each layer, and I didn't know you can even set the transparent index for each layer differently.
As such, I need to look up how to revert that if that's the case. Thanks for the tip!

**Comment by dacap** [comment]
Actually the transparent color is global (for all layers), but if you use other index that is outside the range of the palette (e.g. 255, which I saw some layers with index 255) it will be used as a transparency color anyway (but it doesn't work in the export process, or flattening layers, something we'll try to fix in a future).

You can also set the transparent color from Sprite > Properties > Transparent Color

**Comment by metnias** [comment]
Hmm, I use the colour on the palette and I do often edit the palette before and after, but I have no idea how that would cause index 255 in the canvas. However, that also explains why `Paint Bucket Tool` not working properly with `refer visible layers` in this project (`serverlogo 2107.aseprite`).
`Wrong palette index exceeding num_palette` implied that's what's going on, but I don't know how to fix the project by myself without redrawing every layer with this problem. I expected those would be ironed out with the `Remap` button but `Save Palette` -> `Load Palette` (to enable the button) -> `Remap` doesn't work either.
So for now, screenshot to export.

**Comment by dacap** [comment]
I've sent you the `serverlogo 2107.aseprite` file fixed. I've done these steps:

1. Change the palette size to 256 colors
2. *Edit > Replace Color* and replace index 255 with index 15 to "All" cels:

    <img width="571" alt="Screen Shot 2021-07-17 at 11 55 26" src="https://user-images.githubusercontent.com/39654/126040847-16cbc427-a8a9-42bb-95d3-64045357c38c.png">

3. Change the palette size back to 16 colors.
