### ISSUE TITLE
Laggy dragging on Linux

### ISSUE THREAD

**Issue by ISebSej** [aseprite/aseprite#2849]
Describe your bug report or feature request here

When making a selection and dragging it around it lags extremely hard (https://imgur.com/a/MISaJRN)

I also tried it under Proton and that works perfectly fine, but than I can't really access the file system so that isn't an option

Aseprite 1.3
OS Pop!_OS 21.04
GNOME 3.38.5
WS X11

Hardware:
ryzen 5 2600
16GB ram
nvidia gtx 1650 (driver 470.52.02)

**Comment by mohad12211** [comment]
I tested this issue on my machine and I can confirm it exists.
exists on both aseprite 1.2.28 (official steam binary and compiled from source) and 1.3-beta-5 from steam
archlinux, dwm as a widnow manager 
also tested on linux mint (cinammon DE)

**Comment by dacap** [comment]
Hi @ISebSej, I'll close this and mark it as duplicate of #2089
