### ISSUE TITLE
Bucket Fill Tool is Referencing an Unselected Layer When Determining Where to Fill Color

### ISSUE THREAD

**Issue by MoreFoam** [aseprite/aseprite#2856]
### Summary

When using the bucket fill tool and clicking on an object in another, unselected layer, the fill tool is referencing that unselected layer to determine where to fill in with color. 

### Duplication steps

1. Download this file: [PlatformMockup.zip](https://github.com/aseprite/aseprite/files/6897707/PlatformMockup.zip)
2. Unzip and open the .ase file
3. Select the Ground layer
4. Select the bucket fill tool
5. Select a color
6. Click on position (50, 32)
7. Hide the tree layer and notice that the bucket fill tool has filled in the part of the tree we clicked on, even though the tree layer is not selected

Expected result: The entire background is filled with the color, because the ground layer is selected and we clicked on a position where the background is, in the context of the current layer

Actual result: The part of the tree that was clicked on was used to determine the fill boundaries, even though the tree layer is not selected.

### Aseprite and System version

* Aseprite version: Steam v1.2.288-x64
* System: Windows 10 v10.0.19043 

### Notes

Just wanted to say I am pretty new to Aseprite, so perhaps this is the expected functionality. If so, please let me know.

**Comment by dacap** [comment]
Hi @MoreFoam, I think you might have the "Refer visible layers" option selected, check if you can switch to "Refer only active layer":

![image](https://user-images.githubusercontent.com/39654/127574836-14965ccd-a983-4d58-a063-d7a77b2d1f83.png)

**Comment by MoreFoam** [comment]
@dacap That was it. Sorry about that, I did not realize that was a possible setting. Thank you for the help.

Closing this issue out.

**Comment by dacap** [comment]
No problem, you're welcome! ^^
