### ISSUE TITLE
Integrate sentry for crash reporting

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#2857]
We should investigate the possibility to replace the manual minidump/crash reporting via email with an automated way through sentry:

https://github.com/getsentry/sentry
https://github.com/getsentry/sentry-native

The general idea would be to:

1. Remove the red flag to report crashes manually (the red flag will be still available to reset the scale in case of panic)
2. When a new crash is detected, we should ask the user if she/he wants to share the crash information (and all future crashes automatically)
3. This confirmation could be a checkbox in the "Home" tab (e.g. in the area where "Aseprite is up to date" is displayed)
4. After the confirmation is approved then we start uploading crashes automatically to sentry

---

- [x] the crash helper should be named to something like `aseprite_crashpad_helper.exe`, etc.
- [x] upload release/symbols to Sentry on compilation
- [x] enable Sentry in the official release (Windows and macOS by default)

As a first step we've enabled TLS/SSL support for curl in Windows and macOS on Aseprite v1.2.30, the next step is to enable Sentry.

**Comment by dacap** [comment]
This is done but some work to do in the compilation/distribution process is still required.

**Comment by merwok** [comment]
Can I ask if this is opt-in?
Sending data to a third party without consent would be unexpected.

I have looked at the config file and not found anything (I did find some update check settings, which is also an unexpected practice outside of windows).

**Comment by dacap** [comment]
It's opt-in, when a crash is detected Aseprite will ask to share the information:

<img width="975" alt="Screen Shot 2022-01-12 at 19 26 48" src="https://user-images.githubusercontent.com/39654/149232867-98d8590d-d6bf-4615-b874-7bd793713158.png">

It can be enabled (and then disabled) from Preferences too:

<img width="817" alt="Screen Shot 2022-01-12 at 19 26 56" src="https://user-images.githubusercontent.com/39654/149232918-8de4a6ff-16a2-4347-9476-5270789b84b5.png">

**Comment by merwok** [comment]
Great, thanks for the reply (and all the work on the program!)
