### ISSUE TITLE
[Feature Request] Advanced Mode Preferences

### ISSUE THREAD

**Issue by MulfoK** [aseprite/aseprite#2859]
The default advanced mode layouts are very good, but I feel that a group in the preferences to customise the mode further would be great for the user.

Possibly:

Edit/Preferences/Editor/Advanced Mode/
- Show toolbar
- Toolbar location
- Show bottom info bar (Not sure what it's called)
- Maybe more?

This would be a big plus to display tablet users who are unable to make convenient use of a keyboard, as being able to run advanced mode with the toolbar visible would allow them to work more comfortably, and with the bigger working area that advanced mode boasts.

**Comment by dacap** [comment]
Duplicate to #518 

There are plans to add a set of layouts, so you could configure the screen in certain way and save that as a specific "workspace layout" and then restore/switch between the your different customized layouts.
