### ISSUE TITLE
JASC/GIMP palette does not load/save transparency

### ISSUE THREAD

**Issue by Mailaender** [aseprite/aseprite#2878]
https://github.com/OpenHV/OpenHV/blob/master/mods/hv/bits/shadows.pal is a simple palette with a gradient of blacks. Load it and you will get a pitch-black palette. Remap some entries with transparency and save: the 4th transparency entry will be completely erased.

### Aseprite and System version

* Aseprite version: v1.2.27-x64, Steam
* System: @openSUSE Linux

**Comment by dacap** [comment]
Fixed with https://github.com/aseprite/aseprite/pull/2922
