### ISSUE TITLE
The preview window lags behind when moving.

### ISSUE THREAD

**Issue by BrianComics** [aseprite/aseprite#2881]
The preview window in Aseprite lags behind when dragging it around. Near the end, I wasn't even moving the mouse around; the window was moving by itself.

https://user-images.githubusercontent.com/72044529/128887830-63bf8078-343e-426d-83bb-272c0f372a26.mp4

### Aseprite and System version
* Version: v1.2.28
* System: Windows

**Comment by Gasparoken** [comment]
Thanks for reporting. Does it happen in a particular conditions? I can't reproduce it.
Does it happens after a while of using Aseprite?

**Comment by dacap** [comment]
Hi @BrianComics, just in case, is it Aseprite v1.2.28 running on Windows? that issue looks like an old problem that was solved some years ago when we switched the back-end (from Allegro library to a custom back-end):

  https://github.com/aseprite/aseprite/issues/1006#issuecomment-218016539

**Comment by BrianComics** [comment]
Hi! Aseprite is running on Windows, and it happens any time I move the preview window regardless of how long I've been using the program.

**Comment by BrianComics** [comment]
I also found some weird cursor issues when hovering over any windows. The cursor flickers and leaves a trail. This does not happen when hovering over the timeline or drawing section.

https://user-images.githubusercontent.com/72044529/128918646-18e79e16-459b-4ed3-b754-7f15a708ee89.mp4

**Comment by dacap** [comment]
Hi @BrianComics, the version of Aseprite is displayed in the title bar of the program (you can take a screenshot of the whole window).
