### ISSUE TITLE
Windows 10 SDK 18362 not available

### ISSUE THREAD

**Issue by stblack** [aseprite/aseprite#2886]
Describe your bug report or feature request here
Unable to find Windows 10 SDK 18362 as required to compile. In the components that can be installed is no more available
There is only a Preview Version.

![2021-08-14 15_53_58-Visual Studio Installer](https://user-images.githubusercontent.com/5563231/129448948-6958565c-1554-4d39-9f39-dbf8563e4899.png)

...

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by dacap** [comment]
Hi @stblack, use the latest SDK available (maybe not the preview one). In your case 10.0.20348.0 should work (I guess). I'll update the INSTALL.md just to avoid naming a specific version if that is confusing.

**Comment by stblack** [comment]
I confirm that with 20348 I build successfully aseprite, thanks.
