### ISSUE TITLE
[regression] Marqueed selection gets some rows duplicated when moved left and right over left canvas edge with Ctrl still pressed

### ISSUE THREAD

**Issue by nkoder** [aseprite/aseprite#2891]
Steps to reproduce:

1. Download and open [this file (link)](https://www.icloud.com/iclouddrive/0Lbr7ujwxBoU0zgj0FyYlBMnw#Aseprite_issue__2891) in Aseprite 1.3-beta5 (please let me know if link don't work for you or I accidentally made it obsolete – I will provide you with a new one)
2. Hide "doors" layer
3. Select "items front" layer
4. Zoom to 400% with shortcut 3
5. Move viewport around to see bottom left group of bottles and left canvas edge
6. Press M for marquee tool
7. Select middle front bottle as on attached screenshot
8. Press Ctrl and **keep it pressed for issue to appear**, then press mouse on selected area and start moving it around. During movement cross left canvas boundary multiple times.
9. During such movement you should observe duplicated columns of pixels to appear, which is **not** as expected. Those artifacts does **not** disappear when movement is finished. See attached screenshot.

### Screenshots

Selection to reproduce an issue:

<img width="808" alt="Screen Shot 2021-08-17 at 09 12 54" src="https://user-images.githubusercontent.com/612936/129681644-78ad85d9-b3ec-4889-adf4-d81c29ed1e20.png">

Artifacts during/after movement:

<img width="722" alt="Screen Shot 2021-08-17 at 09 21 32" src="https://user-images.githubusercontent.com/612936/129681882-5c4d117f-6b7c-4449-afb7-bd3cdf1d1dd1.png">

### Additional info

- I guess issue can be reproduced in a more generic way than what I have written down above.
- I checked same reproduction steps in 1.2.28 from standalone installer and issue does **not** happen there, therefore I treat it as regression.

### Aseprite and System version

* Aseprite version: 1.3-beta5, Steam
* System: macOS Big Sur 11.5.1

**Comment by iamOgunyinka** [comment]
@Gasparoken could you please try reproducing this on a Mac? I can't seem to be able to do that on Windows. I've dragged this selected portion (as described in the report) around a lot and ... nothing.

**Comment by Gasparoken** [comment]
Hi @iamOgunyinka. Yes, I was able to reproduce it in MacOS and Windows. Only in the beta version.
