### ISSUE TITLE
Crash after modifying width and height in Despecke FX

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#2903]
This crash is frequent, but it doesn't always happen.
- New Sprite 100x100 RGBA
- draw something that takes up the whole canvas
- Edit > FX > Despeckle (median filter)
- Change to 100 width and height.
Crash (sometimes it doesn't crash)

I attach a crash report and a print screen of Xcode debugging
[aseprite_2021-08-19-145501_Gaspars-MacBook-Pro.crash.zip](https://github.com/aseprite/aseprite/files/7017251/aseprite_2021-08-19-145501_Gaspars-MacBook-Pro.crash.zip)
<img width="1431" alt="Screen Shot 2021-08-19 at 15 46 24" src="https://user-images.githubusercontent.com/32165475/130131426-d13b0585-1887-426e-9a34-bd77e07968c6.png">

* Aseprite version: 1.3-beta5
* System: macOS
* Reported on support ticket 2575 and 2602 too

**Comment by iamOgunyinka** [comment]
I could reproduce this, same procedure you used but a 256x256 canvas.
