### ISSUE TITLE
Aseprite filepicker select all files option

### ISSUE THREAD

**Issue by jestarray** [aseprite/aseprite#2905]
Version: Aseprite 1.x-dev (1.2.28+)
Platform: Linux

Motivation: So on linux, the setting `Preferences > Experimental > Use native file dialog` does not seem to register a qt/gtk one. In my case I had over 100 frames that I had to manually click through using the aseprite file picker because there's no way "Select All" files with ctrl+a or a dedicated button.. at least to my knowledge. 

Consider this issue resolved once this is fixed: 
https://github.com/aseprite/aseprite/issues/1410
Which is very unlikely... so I'll look into how to add a way to "Select All" in the meantime for the built in file picker

**Comment by iamOgunyinka** [comment]
Commenting here so I can keep track of this issue.

**Comment by merwok** [comment]
#1410 is fixed!

**Comment by jestarray** [comment]
I can confirm it works on linux, closing
