### ISSUE TITLE
e

### ISSUE THREAD

**Issue by gogochan** [aseprite/aseprite#2908]
Describe your bug report or feature request here
...
...
...

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by gogochan** [comment]
I apologize for creating this, I wasn't even aware that I did it.  🙏

**Comment by dacap** [comment]
No problem 👍 ☺️
