### ISSUE TITLE
Flatten Visible layers uses indices outside the palette range as opaque colors instead of transparent color

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#2912]
If we have a layer with an index outside the palette range, the editor shows that pixels as a transparent entry, but after Flatten Visible, the pixels will overwrite the pixels below it (just like any other opaque pixel, but the result will be like a transparent pixel). Example file: 
[index0123.aseprite.zip](https://github.com/aseprite/aseprite/files/7042379/index0123.aseprite.zip)

Before flatten:

<img width="534" alt="Screen Shot 2021-08-24 at 19 12 27" src="https://user-images.githubusercontent.com/39654/130697018-e593d5c5-6eac-4820-aa6b-8ee4793f51b9.png">

After flatten:

<img width="529" alt="Screen Shot 2021-08-24 at 19 12 30" src="https://user-images.githubusercontent.com/39654/130697024-5aeb940a-52f2-4b3c-983f-e466b4a2b56c.png">

**Comment by dacap** [comment]
Related to #2842

**Comment by iamOgunyinka** [comment]
@dacap with the attached file, I can see what you're talking about but w/o the attached file, how do I reproduce this?

**Comment by dacap** [comment]
@iamOgunyinka a similar file can be reproduced with these steps (it's a little complex to replicate but can be done):

1. Create an indexed image
2. draw something
3. create a new layer
4. draw something with a color with high index (e.g. if the palette contains 32 colors, you can draw something with index 31)
5. then resize the palette to something smaller (e.g. 16 colors):

    <img width="388" alt="Screen Shot 2021-08-30 at 09 41 58" src="https://user-images.githubusercontent.com/39654/131340640-1f3c0419-39f7-4041-958f-c4df86f8dd24.png">
