### ISSUE TITLE
Color index of individual color bigger than palette size

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#2928]
How to reproduce this bug:
- New file (color mode: Indexed, transparent background)
- Modify the color which index is 10, turn to RGBA(0, 0, 0, 0)
- Paint all the canvas with Paint Bucket Tool with color index 10 (you will see nothing, because index 10 is transparent)
- Resize the palette to 4 colors (dragging the end of palette in the color bar)
- Press the Remap button.
Finally, all the canvas is painted with color index 10 (transparent), but the maximum palette index is 3 (0, 1, 2, 3, four colors)
Then if you try to export this sprite to PNG, libpng error appears  and the png isn't saved.
And if you try to export this sprite to GIF, Aseprite will crash.

Issue originally reported on ticket 2650

Aseprite version: 1.2.29
OS: macOS 10.15.3 Catalina

**Comment by iamOgunyinka** [comment]
Sounds interesting, want me to take it on, @Gasparoken? it should be fun

**Comment by dacap** [comment]
Related to #2842 and #2912

**Comment by dacap** [comment]
I'm not 100% but probably part of this issue was fixed with https://github.com/aseprite/aseprite/commit/dd2d226264b0960145a7e04a97a4aa3669330ad3 too.
