### ISSUE TITLE
Beta 1.3: tablet pressure not working on Linux

### ISSUE THREAD

**Issue by est77** [aseprite/aseprite#2931]
After building the beta 1.3 version from source, tablet pen pressure is not working on Linux. Using aseprite 1.2, same computer, OS and same Wacom tablet pen pressure works correctly.

1.2:
![Screenshot_2021-09-01_20-52-51](https://user-images.githubusercontent.com/409013/131727879-e1411b12-7d98-40e3-b8f6-cf140b6a43af.png)

1.3:
![Screenshot_2021-09-01_20-53-26](https://user-images.githubusercontent.com/409013/131727900-5ea84c2d-a474-42d1-a5f7-c0b6c162e8e7.png)

**Comment by dacap** [comment]
Hi @est77, actually this is strange because both versions are using the same back-end (the same code to handle the pen pressure).

Did you try the official v1.3-beta6 version that is published?

**Comment by est77** [comment]
I tried the beta branch, 650ab7b8d655d54baa81843ffb07862c42e7bbbd commit.
I also noticed that the pressure feddback in the pressure widget is also not working.

**Comment by est77** [comment]
Using a newer Wacom tablet, I could not reproduce the issue. I think the issue can be closed

**Comment by dacap** [comment]
I'll close this issue but we've added some changes to detect more pen devices, more details in #3176
