### ISSUE TITLE
[bug] Canvas Size change makes tilemap layers disappear

### ISSUE THREAD

**Issue by nkoder** [aseprite/aseprite#2942]
I just wanted to crop my image created in Aseprite 1.3 but when I did it, I realized tilemap layers are no longer rendered.

👇  Here on a screenshot below you can see how I am preparing for a canvas size change. Numbers visible on the screenshot are chosen in a way to have all layers included, so you can see how only tilemap ones are not rendered.

<img width="971" alt="before canvas size change" src="https://user-images.githubusercontent.com/612936/132259462-e8103f09-28be-4042-b950-b83a794c4acc.png">

👇  And here is a screenshot with a canvas size change result, no tilemaps visible.

<img width="1019" alt="after canvas size change" src="https://user-images.githubusercontent.com/612936/132259530-3aeb69f9-0ebf-49d3-806e-b572bcd29450.png">

ℹ️  Let me know if you need a source file from me.

### Aseprite and System version

* Aseprite version: `v1.3-beta6`, from Steam
* System: macOS

**Comment by dacap** [comment]
Hi @nkoder, we might need the file to reproduce it, can you always reproduce it with your file?

You can send it to support@aseprite.org

**Comment by nkoder** [comment]
> we might need the file to reproduce it

OK, I sent it a minute ago

> can you always reproduce it with your file?

Yes. Yesterday I copied my source file after experiencing an issue (and probably without saving it) and repeated my steps in order to find best one for GitHub issue (initially I was resizing sprite x4 or x5 before cropping canvas, but issue appears without sprite resize too)

**Comment by nkoder** [comment]
one more piece of info: I finished that piece on 2021-07-18. Might be I created it in beta5 or beta4 etc., depending which one was the current one on Steam, while yesterday I opened it in beta6 in order to just create Lospec palette example image out of it. I mean might be the most of the work related to tilemaps was done and serialized to file in a version previous than the current one.

**Comment by iamOgunyinka** [comment]
Source of the bug has been found and a PR would be issued in few hours.
