### ISSUE TITLE
Can't clear recent files

### ISSUE THREAD

**Issue by bwiklund** [aseprite/aseprite#2958]
I can't clear recent files, even after I delete it, some are removed from the list but this very old set of files is still there and un-removable (the option is grayed out)

![image](https://user-images.githubusercontent.com/3586801/134070647-16186aef-5aad-4024-9e28-30827e6a636d.png)

Aseprite 1.2.29-x64
Windows 10

**Comment by dacap** [comment]
Hi @bwiklund, it's highly probable that you have your files pinned, try unpinning them or just removing them with a drag-and-drop:

![unpin](https://user-images.githubusercontent.com/39654/134071193-dcf47c9c-f93f-4dfd-a08c-6741819c8699.gif)

**Comment by bwiklund** [comment]
😩 yeah i did lol
