### ISSUE TITLE
The color palette UI doesn't show the corner triangle on current Fg and Bg colors

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#2961]
Reported here https://community.aseprite.org/t/ui-not-showing-any-signs-of-the-color-you-selected-when-your-alt-scrolling/10238

System: macOS Catalina 10.15.3
Aseprite version: 1.3-beta6

**Comment by dacap** [comment]
Is this issue different to #2956? Or is the same?

**Comment by Gasparoken** [comment]
#2956 is about mainly "tileset ALT+Mouse Wheel doesn't work as it did on the color palette", although is mentioned some behavior related with this issue "...doesn't update the selected thing..."  but, in my opinion, it's unclear.
This issue is linked to a more clear explained and can be treated like a different issue.

**Comment by Gasparoken** [comment]
Same issue as #3082. It was solved via https://github.com/aseprite/aseprite/commit/539e115b7dbdd080e65b33aa099572bc4c14d4c6.
