### ISSUE TITLE
Panning Canvas Out of View Clips Auto Guides

### ISSUE THREAD

**Issue by behreajj** [aseprite/aseprite#2994]
In the image below the line extending from the left edge of the layer edges (or cel image) should continue to the left edge of the sprite canvas with a label that says 48px.

![diagnosticInfoCutoff](https://user-images.githubusercontent.com/12038348/136830299-105b253b-d79a-46d1-9233-d512def23f90.png)

I'm using Aseprite v1.3-beta6-x64 on Windows 10.

To reproduce:
1. Move cursor to outside the layer edge (or cel image in scripting API terms).
2. Hold down `Ctrl` to display layer edges and auto guides.
3. Pan the view until the sprite canvas is partially out of view.
4. Pan the view so all of the sprite canvas is in view.

Thanks! Best,
Jeremy

**Comment by iamOgunyinka** [comment]
Not a native English speaker and a bit new to some Aseprite terminologies, so please how do you "pan a view..."? I'm trying to reproduce this bug.

**Comment by dacap** [comment]
"Panning the view" is like scrolling the view (e.g. using ctrl + scroll wheel). I tried to reproduce it on macOS and Aseprite v1.3-beta7 but wasn't able (using the trackpad here). I'm not sure if it's Windows-specific or related to the mouse wheel 🤔

**Comment by behreajj** [comment]
If this helps any: I click and hold down the middle mouse wheel, then move the mouse. The cursor turns into the hand tool. When I hold down Ctrl and scroll the wheel, the guides clipping problem doesn't happen.

The zoom level needs to be greater than 100%. At percentages less than or equal to that, the sprite canvas cannot be moved partially out of view.
