### ISSUE TITLE
Can't change git branches after submodules are updated on initial clone

### ISSUE THREAD

**Issue by brickviking** [aseprite/aseprite#2996]
### Description
I cloned the repo so I could compile it locally, as I don't have an Ubuntu install, a Windows install nor a Mac OS X install. I'm one of those lucky Fedora users. Anyhow, I checked out the main branch, and made sure I included the submodules.

After a `git submodule update --init --recursive` I'm unable to change branches, as git now complains that changes in untracked files in third_party/curl/ would be overwritten. I'm pretty sure this relates to issue #2989, but I don't actually know what to do to fix it aside from run two separate directories—one for main and one for beta branches. That does what I want (track both branches) but it doesn't seem ideal and takes up extra space.

### Steps and output
```
aseprite$ git submodule update --init --recursive
Submodule 'laf' (https://github.com/aseprite/laf.git) registered for path 'laf'
....
aseprite$ git --no-pager branch
  beta
* main
aseprite$ git checkout beta
error: The following untracked working tree files would be overwritten by checkout:
    third_party/curl/CMake/CMakeConfigurableFile.in
    ...
    third_party/curl/
Aborting.
aseprite$ 
```

**Comment by dacap** [comment]
Hi @brickviking, you can use `git checkout -f beta`, remove the third_party/curl and then use a `git reset --hard beta`. Anyway I'll try to merge `main` -> `beta` right now so this issue is solved.

**Comment by brickviking** [comment]
Thanks for that, that should solve it. I appreciate the work you're doing on this program.
