### ISSUE TITLE
Increase max resize factor beyond to 1000% in Export dialog

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3007]
Some users ask for greater resize factor (up to 10000%). If this is implemented, a warning prompt of "save your work before to proceed..." should be added. In certain scenarios, the computer could get stuck for several minutes doing a large unintentional resize on a large image.
Reported in: https://igarastudio.zendesk.com/agent/tickets/2843

**Comment by nkoder** [comment]
FYI For now I use https://github.com/david-fletcher/super-export to achieve that. It allows me to both upscale a lot and see real time what would be the output dimensions (before I click OK button). My case: for example I want to export to a size which has at least 1920 px on a longer side.
