### ISSUE TITLE
Normal map color wheel not working as intended

### ISSUE THREAD

**Issue by Louis-Julien** [aseprite/aseprite#3015]
**Problem:**
When selecting a color with the color picker on the image of a normal map sphere, produced outside of Aseprite, the colors selected do not match the one displayed on the color picker. The color selected on the color wheel seem to not match the desired orientation when tested in Unity with default 3D lights.
I tried to use the normal color wheel to select colors between 2 already known and working colors, but it doesn't work at all.

**Steps to reproduce:** 
- import a normal map sphere (the one from the wikipedia page for example) in aseprite
- select a color with the color picker, preferably not at the center
- with the normal map palette selected, try to select the same color by clicking at the spot highlighted with a small circle on the color wheel.
- The new color is different from the previous one.

This capture shows the difference between the 2 colors, the first one (in the red circle), actually on the image, and the second, produced with the color wheel:
https://gyazo.com/e115b949781c6c0b77a3ca19bfe563fb

As per my tests, the color produced with Aseprite normal color wheel **are not correct** when the texture is imported in a program to light them.

As an added request, while testing some other programs to edit normal map I found one that shows a wireframe 3D square around the color selected on the wheel, clearly giving the information of the direction of the normal. That would be very helpful to wrap your head around what a color will really do when lighted.

If you need any feedback or to test fixes, don't hesitate to contact me.

### Aseprite and System version

* Aseprite version: 1.2.29-x64, steam version
* System: W10

**Comment by Louis-Julien** [comment]
The issue is preventing us from making significant progress in our current project, but we could provide help to resolve it. With  some indications from your part, one of our dev @as_csauveur could look into the issue and see if there is a solution. Would that be okay with you?

**Comment by dacap** [comment]
I'm reassigning this issue to me, in case you @Louis-Julien can check some of the code, please check:

* https://github.com/aseprite/aseprite/blob/f6ba8d9ae0e75f2ecdf33cc1c8d95ff0b40b7820/src/app/ui/color_wheel.cpp#L108
* https://github.com/aseprite/aseprite/blob/f6ba8d9ae0e75f2ecdf33cc1c8d95ff0b40b7820/src/app/ui/color_wheel.cpp#L194

**Comment by Louis-Julien** [comment]
Thank you, I've forwarded the links to our dev, I'll keep you in touch.

**Comment by cs-altshift** [comment]
Thanks for the links into the codebase. I'm starting looking at this issue today.
