### ISSUE TITLE
Problem occured when I try to run python command skia on Linux 

### ISSUE THREAD

**Issue by shhubhamJain** [aseprite/aseprite#3028]
Python  - 2.7.5
When I try to build skia, I need to do this command :
python2 tools/git-sync-deps

Error :-
Skipping "../src".
Skipping "bin".
third_party/externals/brotli         @ e61745a6b7add50d380cfd7d3883dd6c62fc2c71
buildtools                           @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
third_party/externals/angle2         @ 421dbf200d361f661a7a79cb6d9cdc83df74ef6d
third_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
third_party/externals/abseil-cpp     @ 789af048b388657987c59d4da406859034fe310f
third_party/externals/egl-registry   @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
third_party/externals/dawn           @ 3c786cd418f692b5e0a12adfb35b7b250eb579ca
third_party/externals/expat          @ a28238bdeebc087071777001245df1876a11f5ee
third_party/externals/freetype       @ 12ef831fc314518bff45278008a568608501a8e4
third_party/externals/dng_sdk        @ c8d0c9b1d16bfda56f15165d39e0ffa360a11123
third_party/externals/harfbuzz       @ a52c6df38a38c4e36ff991dfb4b7d92e48a44553
third_party/externals/icu            @ a0718d4f121727e30b8d52c7a189ebf5ab52421f
third_party/externals/libgifcodec    @ fd59fa92a0c86788dcdd84d091e1ce81eda06a77
third_party/externals/libjpeg-turbo  @ 24e310554f07c0fdb8ee52e3e708e4f3e9eb6e20
third_party/externals/jinja2         @ a82a4944a7f2496639f34a89c9923be5908b80aa
third_party/externals/imgui          @ 9418dcb69355558f70de260483424412c5ca2fce
third_party/externals/zlib           @ c876c8f87101c5a75f6014b0f832499afeb65b73
third_party/externals/markupsafe     @ 0944e71f4b2cb9a871bcbe353f95e889b64a611a
third_party/externals/libpng         @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
third_party/externals/wuffs          @ 600cd96cf47788ee3a74b40a6028b035c9fd6a61
third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
third_party/externals/piex           @ bb217acdca1cc0c16b704669dd6f91a1b509c406
third_party/externals/spirv-cross    @ 0e2880ab990e79ce6cc8c79c219feda42d98b1e8
third_party/externals/spirv-tools    @ 11cd875ed88484f93943071083b4821b4c3d2193
third_party/externals/oboe           @ b02a12d1dd821118763debec6b83d00a8a0ee419
third_party/externals/libwebp        @ 9ce5843dbabcfd3f7c39ec7ceba9cbeb213cbfdf
third_party/externals/sfntly         @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
third_party/externals/tint           @ e7ca884b3d124ff04ca52f0c6024db4a61e4848c
third_party/externals/opengl-regi... @ 14b80ebeab022b2c78f84a573f01028c96075553
third_party/externals/swiftshader    @ d143249a93bc3d5fcb21f5b24f8aa2d86cfb37fc
third_party/externals/spirv-headers  @ cf653e4ca4858583802b0d1656bc934edff6bd7f
Traceback (most recent call last):
  File "bin/fetch-gn", line 31, in <module>
    f.write(urlopen(url).read())
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
Traceback (most recent call last):
  File "tools/git-sync-deps", line 266, in <module>
    exit(main(sys.argv[1:]))
  File "tools/git-sync-deps", line 261, in main
    os.path.join(os.path.dirname(deps_file_path), 'bin', 'fetch-gn')])
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python2', 'bin/fetch-gn']' returned non-zero exit status 1

-------------------------------------------------------------------------------------------------------------
Why i am getting connection reset by peer error ??

**Comment by heitor-ps** [comment]
subprocess.CalledProcessError: Command '['/usr/bin/python2', 'bin/fetch-gn']' returned non-zero exit status 1

First of all I'm running Ubuntu 20.04 and the build process used Python 2.7.18. Now for the problem: 

It looks like a problem with a python module. Try using a different version of python2.

I suggest you to configure the python command like in this tutorial https://linuxconfig.org/ubuntu-20-04-python-version-switch-manager

I was having some build problems with a module that checks Clang. Configuring the python command like in the tutorial fixed it.

**Comment by Xtendera** [comment]
Should be fixed as the code has moved to python3 and runs perfectly in most versions. We can close this issue.

**Comment by dacap** [comment]
Yes, I'm going to close this as the latest Skia we're using should work with python3.
