### ISSUE TITLE
Aseprite compile issues: Windows 10

### ISSUE THREAD

**Issue by xxKingCrashxx** [aseprite/aseprite#3031]
I have spent about a week on and off trying to get Aseprite to compile properly so I can build a working exe.  I have been having the exact same compiling issue even after trying things such as:

- update windows
- reinstall Visual studios 2019 with all necessary tools
- reinstall cmake, ninja, and skia
- redownload aseprite source files
- attempt to compile and build a older version of aseprite 

I have been following the steps in the INSTALL.md.

As of writing this, I have been using the latest versions of Visual studios, aseprite, Ninja, skia, and cmake.

### Compile Error
 
[aseprite_comp_error.txt](https://github.com/aseprite/aseprite/files/7446241/aseprite_comp_error.txt)

### Other Info
![VSConfiguration](https://user-images.githubusercontent.com/42157444/139529029-5b83977e-67c9-416f-b950-887934ff56cc.PNG)

![FileStructure](https://user-images.githubusercontent.com/42157444/139529051-24c79e5f-38fc-468c-a580-ae87de6e0b44.PNG)

![FileStructure2](https://user-images.githubusercontent.com/42157444/139529053-837477e9-d5f9-421e-9f8c-1498115e9424.PNG)

### Aseprite and System version

* Aseprite version: Aseprite Ver 1.3-beta7
* System: Windows 10

**Comment by dacap** [comment]
It looks like the MSVC cannot compile C++ files:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.
```

As you said that you tried *"to compile and build a older version of aseprite"*, I would recommend you to re-create the `build` folder for Aseprite from scratch. Microsoft tends to change the Visual Studio version on each update, so maybe `C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe` might be inexistent (the version `14.29.30133` might have changed several times).

Personally what I do in these cases to re-utilize an old compilation is just opening my `build/CMakeCache.txt` file and replacing the old MSVC version (e.g. `14.29.30133`) with the new one in the whole .txt file. You can find the new version in the `C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC` folder.

**Comment by xxKingCrashxx** [comment]
thanks, that helped.
