### ISSUE TITLE
Make script console dialog non-blocking

### ISSUE THREAD

**Issue by not-surt** [aseprite/aseprite#3043]
It'd be nice if the script console dialog could be made non-blocking so it can be left open while working in Aseprite and collect script output during use and also allow closing Aseprite without first closing the console dialog.

### Aseprite and System version

* Aseprite version: v1.3-beta7-x64, Steam
* System: Windows 10

**Comment by Gasparoken** [comment]
Hi not-surt, I guess I didn't get it. What do you mean by non-blocking?
Allow closing Aseprite without first closing the console dialog: Ok

**Comment by not-surt** [comment]
So you can just leave it open while using Aseprite to continually collect script output without having to close it before interacting with the Aseprite window.

**Comment by dacap** [comment]
Yes, it means that the window must be executed in background (non-foreground/modal/blocking).

In the latest release, if you open the debugger (File > Script > Debugger), all console output goes to the debugger window (which is a window that runs in the background). I'm still not sure if there was a reason to make the console modal, but I think we can change it.

**Comment by dacap** [comment]
This was implemented in cc7da166910e8be5eb29e4e84bf9aadc7cc7b22b
