### ISSUE TITLE
when changing the layer name to a number, aseprite API gets confused

### ISSUE THREAD

**Issue by GieziJo** [aseprite/aseprite#3045]
# Bug:
when running the following simple lua code:
```lua
for i, layer in ipairs(app.activeSprite.layers) do
    print(i..") "..layer.name)
end
```
which lists all layers and their index, Aseprite gets confused if you rename one of the layers to a single digit, and the enumeration doesn't work properly anymore:

https://user-images.githubusercontent.com/4385118/140664667-8fb017fb-312e-458f-a92f-a3c6539d1926.mp4

I have also experienced that sometimes layers don't get enumerated at all (can't reproduce).

### Steps to reproduce:
1. Create a new aseprite file.
2. Create several new layers.
3. Run the lua command
    -> everything should be fine
4. rename "Layer 3" to "1" and "Layer 4" to "2"
5. Run the lua command 
    -> "Layer 1" will be displayed as "1" and "Layer 2" as "2" (same name as the actual "1" and "2").
6. Continue adding layers
    -> added layers are displayed out of order

## Update:
1. If you rename a layer to a number which is higher than the layer count it will add an "artificial" layer which doesn't actually exist (7 layers on the left, 8 layers enumerated):

![image](https://user-images.githubusercontent.com/4385118/140666330-3f8cdc4f-fc7d-4e65-81af-5b7d262a7f0b.png)

2. Or just assign it a random name (8 present 3 times in the enumeration):

![image](https://user-images.githubusercontent.com/4385118/140666364-992c6762-01ca-4ff1-a685-6ae327c718cb.png)

### System
Aseprite 1.3 beta-7 on windows 10 installed from Steam

**Comment by Gasparoken** [comment]
Hi  GieziJo, thank you for this report. I was able to reproduce it.
