### ISSUE TITLE
pattern (not a bug)

### ISSUE THREAD

**Issue by Muaath6B** [aseprite/aseprite#3051]
Describe your bug report or feature request here
...make a brush like (paint bucket tool) but makes a pattern
...try (Pixely) for androind as an example
...

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by dacap** [comment]
Duplicate #175

Actually using custom brushes you can fill with patterns: https://imgur.com/2ke4Xgw
