### ISSUE TITLE
TileMap Layers Empty After Converting To A Color Profile

### ISSUE THREAD

**Issue by behreajj** [aseprite/aseprite#3052]
Hello,

I found a bug again. This is in version 1.3-beta7x64 on Windows 10. Converting to a color profile causes a tile map layer to become transparent (or empty). To reproduce, 

1. Select any layer with visual content.
2. Convert the layer to a tile map layer.
3. Go to `Sprite > Properties`.
4. Select a color profile other than the sprite's current profile.
5. Press the `Convert` button.
6. Switch to eye drop tool, sample layer; should match the `Empty` tile.

The visual result may be similar to the one in the issue https://github.com/aseprite/aseprite/issues/2739 (the most closely related issue I noticed), though the cause may be different.

So far as I tested, assigning a color profile does not cause this issue. However, the colors in the tile set do not alter in appearance, as the palette color bar and canvas do. While an `.icc` file is not needed to test the conversion problem, using an `.icc` that differs from `sRGB` can make the problem with assignment easier to see.

The issue is compounded if settings in `Edit > Preferences > Color` use conversion, or are set to `Ask` and the user chooses a conversion. A sprite with a tile map layer can be saved with the `.aseprite` extension, then opened with an empty tile map layer.

Thanks,
Jeremy

**Comment by Gasparoken** [comment]
Thanks for this report Jeremy! I was able to reproduce it. The #2739 is a different issue (related with re-mapping tiles coordinates in new canvas definition)
