### ISSUE TITLE
Crash on exit when the color profile in use is different from the system's default

### ISSUE THREAD

**Issue by iamOgunyinka** [aseprite/aseprite#3055]
A lingering issue that has been encountered [before](https://github.com/aseprite/laf/blob/726481f27c8258aa8fba577bf1529a5f40acec59/os/win/window.cpp#L303-L305) is what I may be describing here. In this case, I encountered this bug when I changed the color profile of my Windows 10 PC from the default sRGB to a random color profile. On exit, this [ASSERT](https://github.com/aseprite/laf/blob/726481f27c8258aa8fba577bf1529a5f40acec59/os/win/window.cpp#L306) always got triggered -- so I started digging.

My research showed that the problem has to do with how Aseprite [detects different color profiles](https://github.com/aseprite/laf/blob/726481f27c8258aa8fba577bf1529a5f40acec59/os/win/window.cpp#L2292) before redrawing the Windows. Right now, it compares pointers to color profiles, and while that may have worked in all cases till now, sometimes (and in this case) the same color profile may be created differently. So comparing their pointers would not be sufficient and Windows redraw events would be [scheduled](https://github.com/aseprite/laf/blob/726481f27c8258aa8fba577bf1529a5f40acec59/os/win/window.cpp#L2293) and added to the [global event queue](https://github.com/aseprite/laf/blob/726481f27c8258aa8fba577bf1529a5f40acec59/os/common/event_queue.cpp#L22). This is just the genesis of the problem.

The problem show up when the program exits and the cleanup "crew" starts their job -- the local `os::System` [object](https://github.com/aseprite/aseprite/blob/bed6a8d8b1fe026ec6ad24e7b765e36471cbcfc8/src/main/main.cpp#L95) is destroyed and it [nullifies](https://github.com/aseprite/laf/blob/726481f27c8258aa8fba577bf1529a5f40acec59/os/common/system.h#L40) the global `os::System`  -- all these local cleanup goes well.  Then the global/static variables starts to get cleaned up too, including the global event queue. In my case, because of the erroneous comparison of the color profiles and reissuing of redrawing event of the (Main?) Window, we usually have a redraw event lingering in the global event queue. The global event queue tries to clear its cache and destroy the events in the process but this fails as one of the events would try to destroy a reference to an already nullified Window. Thus, the assert.

Proposed solution
===
We can change how the color profile is being compared and in addition to (or rather total removal of) comparing their pointer values, the comparison can be done by using the [nearly equal](https://github.com/aseprite/laf/blob/726481f27c8258aa8fba577bf1529a5f40acec59/gfx/color_space.cpp#L142) member function in `gfx::ColorSpace`. However, one problem that _may_ arise (in the worst case scenario) from using this member function have to do with performance because of the constant [comparison of a possibly large vector](https://github.com/aseprite/laf/blob/726481f27c8258aa8fba577bf1529a5f40acec59/gfx/color_space.cpp#L177) (in the case of ICC profile), which would impede the performance. So I propose we calculate and cache the hash of the data and use the hash value comparison in this member function, as opposed to the vector-to-vector comparison.

* System: Windows OS.

**Comment by dacap** [comment]
Thanks a lot for the analysis @iamOgunyinka 🙏 

Personally I would prefer to keep some kind of comparison inside `checkColorSpaceChange()` to avoid creating unnecessary "change color space" events (as the function [is always called in WM_SHOWWINDOW](https://github.com/aseprite/laf/blob/d76cc1af5564ed510fb31270d06f36dc1e426f40/os/win/window.cpp#L870)). Maybe the pointer comparison can be kept.

I'm thinking about some possible solutions (but not sure if they might fix the issue):

* I never liked that global event queue, maybe we can move the event queue inside the `System` instance (`os::CommonSystem`). We can leave this for later if it's too complex to refactor.
* Maybe the `~CommonSystem` can clean the event queue, anyway I'm not sure why the event queue is still being processed or who [pumps it](https://github.com/aseprite/laf/blob/73ade80442828627599eaff0f9ca12ee1dc1b991/os/event_queue.h#L24)
* Could we just check if `os::instance()` is `nullptr` [before calling `onChangeColorSpace()`](https://github.com/aseprite/laf/blob/726481f27c8258aa8fba577bf1529a5f40acec59/os/win/window.cpp#L2292)?

Tell me what do you think about it.

**Comment by iamOgunyinka** [comment]
Thank you for taking your time to read through the issue. I'll start from your last bulletin and walk my way up.

> Could we just check if `os::instance()` is `nullptr` before calling `onChangeColorSpace()`?

Unfortunately, this would (and did) not work. The destruction and nullification of the global system object is done by the cleanup of the local `os::System` variable in main(). Before that destruction is hit, we already have the RedrawWindow event in the global queue. When the global event queue is destroyed, we would still hit the ASSERT.

> Maybe the `~CommonSystem` can clean the event queue, anyway I'm not sure why the event queue is still being processed or who pumps it

The pumping, I think, has occurred before exiting the program (I'm not sure about this because it's difficult to track "who" does it) and when you add breakpoints to the queue, you are always, always going to keep hitting it before getting anything done.

Also, the event queue at this point has stopped being processed. It is the destruction of an event that has a reference to the existing Window that caused the crash, not processing of event. 

Using the `~CommonSystem` to clear the queue may work, if it doesn't add more dependencies. 

> I never liked that global event queue, maybe we can move the event queue inside the System instance (`os::CommonSystem`). We can leave this for later if it's too complex to refactor.

I can look more into this refactoring if you want me to.

In the interim, the changes I proposed earlier in the issue looks a bit like so:
```
void WindowWin::checkColorSpaceChange()
{
  os::ColorSpaceRef oldColorSpace = m_lastColorProfile;
  os::ColorSpaceRef newColorSpace = colorSpace();
  if (oldColorSpace != newColorSpace) {
    if (oldColorSpace && newColorSpace) {
      const auto& oldCS = oldColorSpace->gfxColorSpace();
      const auto& newCS = newColorSpace->gfxColorSpace();
      if (oldCS->nearlyEqual(*newCS))
        return;
    }
    onChangeColorSpace();
  }
}
```

**Comment by dacap** [comment]
> Also, the event queue at this point has stopped being processed. It is the destruction of an event that has a reference to the existing Window that caused the crash, not processing of event.

OK now I understand. I think we had a similar issue in the past ([maybe this](https://github.com/aseprite/laf/commit/1e66d1d9d50cececb160f0fe37dec311107e2ded)).

Our main source of problems is that `os::Event` contains a `os::WindowRef` (a smart pointer). Here the problem is that the event queue contains several queued `os::Event`s, and when we destroy the global `EventQueue` the `~Event` of each one is called, and the last reference to all referenced windows is finally destroyed (the `Event::m_window` is destroyed).

I think one possible (workaround) solution would be to completely clear the event queue at the very beginning of `~System` (this would be the similar as a future refactor to move the event queue inside System, but I will do that myself in the future). In this way all windows are destroyed before we delete the `os::System`.

> In the interim, the changes I proposed earlier in the issue looks a bit like so:
> ```
> void WindowWin::checkColorSpaceChange() { [...]
> ```

I know that with this solution you're trying to avoid calling `onChangeColorSpace()`, but I don't know if this is a proper solution for this problem (or if this might give us to other future problems, e.g. the ASSERT() on `~Window` would still fail). I think we can prioritize fixing the order of destruction of objects first (destruct all `os::Window`s and then the `os::System`).

**Comment by iamOgunyinka** [comment]
> think one possible (workaround) solution would be to completely clear the event queue at the very beginning of `~System`

I'll create a PR that does this now.

**Comment by dacap** [comment]
I didn't remember but it looks like I already fixed this same issue one Linux 10 months ago (the comment says "displays" because an `os::Window` was called `os::Display`, but it was refactored):

https://github.com/aseprite/laf/blob/73ade80442828627599eaff0f9ca12ee1dc1b991/os/x11/x11.cpp#L49

I'll merge your PR + some other commits.
