### ISSUE TITLE
Update install instructions for Aseprite to m96

### ISSUE THREAD

**Issue by jusw85** [aseprite/aseprite#3062]
[INSTALL.md](https://github.com/aseprite/aseprite/blob/main/INSTALL.md#dependencies) for Aseprite
```
And a compiled version of the aseprite-m81 branch of the Skia library
```

[Skia](https://github.com/aseprite/skia#building-skia)
```
Aseprite and laf use the aseprite-m96 branch
```

[laf](https://github.com/aseprite/laf#dependencies)
```
laf requires a compiled version of the Skia library from branch aseprite-m96
```

INSTALL.md should probably be updated.

**Comment by dacap** [comment]
Thanks @jusw85, I've just updated the INSTALL guide.

**Comment by 210783jud** [comment]
Jud
