### ISSUE TITLE
Background Layer in RGB Mode Allows Alpha If Converted from Indexed

### ISSUE THREAD

**Issue by behreajj** [aseprite/aseprite#3073]
Hi,

This is a bug report. I'm using Aseprite v1.3beta7-x64 on Windows 10.

![afterRgbConversion](https://user-images.githubusercontent.com/12038348/143675910-503e8bc8-040a-4cb1-ae5f-62be688c56d0.png)

To reproduce:
1. Create a new sprite that is set to indexed color mode.
2. Ensure that the palette contains at least one element with alpha channel less than 255.
3. Apply translucent or transparent pixels to the layer cel image with a brush, fill, etc.
4. Right click on the first and only layer in the timeline.
5. Select `Convert To ... Background` in the context menu.
6. Observe that the layer is underlined in the timeline, and that its name may be changed to "Background."
7. Go to `Sprite > Color Mode > RGB Color` to convert to RGB.

I observed this in version 1.2.30 as well. The user interface for converting a layer to background in steps 4 to 5 was slightly different: right click `Background from Layer`.

Thanks,
Jeremy

**Comment by Gasparoken** [comment]
Thanks for this report. I was able to reproduce it.
