### ISSUE TITLE
Trying to compile Aseprite on Ubuntu

### ISSUE THREAD

**Issue by minhnguyenhoang** [aseprite/aseprite#3074]
I tried following the all the instructions in the INSTALL.md (incl. dependencies, git cloning/source code downloading and compiling itself). I seem to pull through just fine after cmake is run, but when I use ninja, it always fail. I tried both skia-m96/skia-m81, and GCC/Clang. It never does work. This is from my most recent attempt:

$ ninja aseprite
[610/1567] Building CXX object third_p...cket.dir/ixwebsocket/IXWebSocket.cpp.o
In file included from ../third_party/IXWebSocket/ixwebsocket/IXWebSocket.h:17,
                 from ../third_party/IXWebSocket/ixwebsocket/IXWebSocket.cpp:7:
../third_party/IXWebSocket/ixwebsocket/IXWebSocketMessage.h: In lambda function:
../third_party/IXWebSocket/ixwebsocket/IXWebSocketMessage.h:41:23: warning: ‘webSocketMessageType’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   41 |             , binary(b)
      |                       ^
../third_party/IXWebSocket/ixwebsocket/IXWebSocket.cpp:388:42: note: ‘webSocketMessageType’ was declared here
  388 |                     WebSocketMessageType webSocketMessageType;
      |                                          ^~~~~~~~~~~~~~~~~~~~
[630/1567] Building CXX object laf/base/CMakeFiles/laf-base.dir/fs.cpp.o
In file included from ../laf/base/fs.cpp:19:
../laf/base/fs_unix.h: In function ‘std::string base::get_canonical_path(const string&)’:
../laf/base/fs_unix.h:170:11: warning: ignoring return value of ‘char* realpath(const char*, char*)’, declared with attribute warn_unused_result [-Wunused-result]
  170 |   realpath(path.c_str(), buffer);
      |   ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
[666/1567] Building CXX object laf/os/...laf-os.dir/skia/skia_color_space.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o 
/usr/bin/c++  -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_FREETYPE -DLAF_LINUX -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SAMPLES_FOR_X -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src -I../laf -Ilaf -I../laf/third_party/stringencoders/src -I/home/glitch/deps/skia -I/usr/include/harfbuzz -Ithird_party/freetype2/include -O2 -g -DNDEBUG   -Werror=suggest-override -std=c++14 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o -c ../laf/os/skia/skia_color_space.cpp
../laf/os/skia/skia_color_space.cpp:18:10: fatal error: src/core/SkConvertPixels.h: No such file or directory
   18 | #include "src/core/SkConvertPixels.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[670/1567] Building CXX object laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o 
/usr/bin/c++  -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DLAF_FREETYPE -DLAF_LINUX -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SAMPLES_FOR_X -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/freetype2/include -I../third_party/giflib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../src -I../laf -Ilaf -I../laf/third_party/stringencoders/src -I/home/glitch/deps/skia -I/usr/include/harfbuzz -Ithird_party/freetype2/include -O2 -g -DNDEBUG   -Werror=suggest-override -std=c++14 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o -c ../laf/os/skia/os.cpp
In file included from ../laf/gfx/matrix.h:12,
                 from ../laf/os/skia/skia_surface.h:14,
                 from ../laf/os/skia/skia_system.h:17,
                 from ../laf/os/skia/os.cpp:12:
../laf/gfx/matrix_skia.h: In static member function ‘static gfx::Matrix gfx::Matrix::MakeScale(float, float)’:
../laf/gfx/matrix_skia.h:25:31: error: ‘Scale’ is not a member of ‘SkMatrix’
   25 |       return Matrix(SkMatrix::Scale(sx, sy));
      |                               ^~~~~
../laf/gfx/matrix_skia.h: In static member function ‘static gfx::Matrix gfx::Matrix::MakeScale(float)’:
../laf/gfx/matrix_skia.h:29:31: error: ‘Scale’ is not a member of ‘SkMatrix’
   29 |       return Matrix(SkMatrix::Scale(scale, scale));
      |                               ^~~~~
../laf/gfx/matrix_skia.h: In static member function ‘static gfx::Matrix gfx::Matrix::MakeTrans(float, float)’:
../laf/gfx/matrix_skia.h:33:31: error: ‘Translate’ is not a member of ‘SkMatrix’
   33 |       return Matrix(SkMatrix::Translate(x, y));
      |                               ^~~~~~~~~
In file included from ../laf/os/skia/skia_system.h:17,
                 from ../laf/os/skia/os.cpp:12:
../laf/os/skia/skia_surface.h: At global scope:
../laf/os/skia/skia_surface.h:704:3: error: ‘SkSamplingOptions’ does not name a type
  704 |   SkSamplingOptions DefaultSamplingOptions() {
      |   ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h: In member function ‘virtual void os::SkiaSurface::setDrawMode(os::DrawMode, int, gfx::Color, gfx::Color)’:
../laf/os/skia/skia_surface.h:219:31: error: ‘SkSamplingOptions’ was not declared in this scope
  219 |                               SkSamplingOptions()));
      |                               ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h: In member function ‘virtual void os::SkiaSurface::applyScale(int)’:
../laf/os/skia/skia_surface.h:259:44: error: ‘SkSamplingOptions’ was not declared in this scope
  259 |                          srcRect, dstRect, SkSamplingOptions(),
      |                                            ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h: In member function ‘virtual void os::SkiaSurface::putPixel(gfx::Color, int, int)’:
../laf/os/skia/skia_surface.h:375:11: error: no matching function for call to ‘SkPixmap::erase(SkColor4f, SkColorSpace*, SkIRect*)’
  375 |         &r);
      |           ^
In file included from /home/glitch/deps/skia/include/core/SkBitmap.h:14,
                 from ../laf/os/skia/skia_surface.h:20,
                 from ../laf/os/skia/skia_system.h:17,
                 from ../laf/os/skia/os.cpp:12:
/home/glitch/deps/skia/include/core/SkPixmap.h:697:10: note: candidate: ‘bool SkPixmap::erase(SkColor, const SkIRect&) const’
  697 |     bool erase(SkColor color, const SkIRect& subset) const;
      |          ^~~~~
/home/glitch/deps/skia/include/core/SkPixmap.h:697:10: note:   candidate expects 2 arguments, 3 provided
/home/glitch/deps/skia/include/core/SkPixmap.h:706:10: note: candidate: ‘bool SkPixmap::erase(SkColor) const’
  706 |     bool erase(SkColor color) const { return this->erase(color, this->bounds()); }
      |          ^~~~~
/home/glitch/deps/skia/include/core/SkPixmap.h:706:10: note:   candidate expects 1 argument, 3 provided
/home/glitch/deps/skia/include/core/SkPixmap.h:719:10: note: candidate: ‘bool SkPixmap::erase(const SkColor4f&, const SkIRect*) const’
  719 |     bool erase(const SkColor4f& color, const SkIRect* subset = nullptr) const;
      |          ^~~~~
/home/glitch/deps/skia/include/core/SkPixmap.h:719:10: note:   candidate expects 2 arguments, 3 provided
In file included from ../laf/os/skia/skia_system.h:17,
                 from ../laf/os/skia/os.cpp:12:
../laf/os/skia/skia_surface.h: In member function ‘virtual void os::SkiaSurface::blitTo(os::Surface*, int, int, int, int, int, int) const’:
../laf/os/skia/skia_surface.h:413:9: error: ‘SkSamplingOptions’ was not declared in this scope
  413 |         SkSamplingOptions(),
      |         ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h:421:9: error: ‘SkSamplingOptions’ was not declared in this scope
  421 |         SkSamplingOptions(),
      |         ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h: In member function ‘virtual void os::SkiaSurface::drawSurface(const os::Surface*, int, int)’:
../laf/os/skia/skia_surface.h:484:7: error: ‘SkSamplingOptions’ was not declared in this scope
  484 |       SkSamplingOptions(),
      |       ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h: In member function ‘virtual void os::SkiaSurface::drawSurface(const os::Surface*, const Rect&, const Rect&)’:
../laf/os/skia/skia_surface.h:496:5: error: ‘SkSamplingOptions’ was not declared in this scope
  496 |     SkSamplingOptions sampling;
      |     ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h:498:7: error: ‘sampling’ was not declared in this scope
  498 |       sampling = DefaultSamplingOptions();
      |       ^~~~~~~~
../laf/os/skia/skia_surface.h:498:18: error: ‘DefaultSamplingOptions’ was not declared in this scope
  498 |       sampling = DefaultSamplingOptions();
      |                  ^~~~~~~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h:503:7: error: ‘sampling’ was not declared in this scope
  503 |       sampling,
      |       ^~~~~~~~
../laf/os/skia/skia_surface.h: In member function ‘virtual void os::SkiaSurface::drawRgbaSurface(const os::Surface*, int, int)’:
../laf/os/skia/skia_surface.h:525:7: error: ‘SkSamplingOptions’ was not declared in this scope
  525 |       SkSamplingOptions(),
      |       ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h: In member function ‘virtual void os::SkiaSurface::drawRgbaSurface(const os::Surface*, int, int, int, int, int, int)’:
../laf/os/skia/skia_surface.h:544:7: error: ‘SkSamplingOptions’ was not declared in this scope
  544 |       SkSamplingOptions(),
      |       ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h: In member function ‘virtual void os::SkiaSurface::drawRgbaSurface(const os::Surface*, const Rect&, const Rect&)’:
../laf/os/skia/skia_surface.h:556:5: error: ‘SkSamplingOptions’ was not declared in this scope
  556 |     SkSamplingOptions sampling;
      |     ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h:558:7: error: ‘sampling’ was not declared in this scope
  558 |       sampling = DefaultSamplingOptions();
      |       ^~~~~~~~
../laf/os/skia/skia_surface.h:558:18: error: ‘DefaultSamplingOptions’ was not declared in this scope
  558 |       sampling = DefaultSamplingOptions();
      |                  ^~~~~~~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h:563:7: error: ‘sampling’ was not declared in this scope
  563 |       sampling,
      |       ^~~~~~~~
../laf/os/skia/skia_surface.h: In member function ‘virtual void os::SkiaSurface::drawColoredRgbaSurface(const os::Surface*, gfx::Color, gfx::Color, const Clip&)’:
../laf/os/skia/skia_surface.h:593:7: error: ‘SkSamplingOptions’ was not declared in this scope
  593 |       SkSamplingOptions(),
      |       ^~~~~~~~~~~~~~~~~
../laf/os/skia/skia_surface.h: In member function ‘virtual void os::SkiaSurface::drawSurfaceNine(os::Surface*, const Rect&, const Rect&, const Rect&, const os::Paint*)’:
../laf/os/skia/skia_surface.h:679:7: error: ‘SkFilterMode’ has not been declared
  679 |       SkFilterMode::kNearest,
      |       ^~~~~~~~~~~~
[671/1567] Building CXX object laf/os/CMakeFiles/laf-os.dir/x11/window.cpp.o
ninja: build stopped: subcommand failed.

Can anybody help?

### Aseprite and System version

* Aseprite version: v13-beta7
* System: Linux, Ubuntu 20.04 (custom build)

**Comment by bjorm** [comment]
Maybe this PR of mine could help you: https://github.com/aseprite/aseprite/pull/3070
I was able to build aseprite with this approach yesterday. Not sure whether the resulting binary would run on ubuntu, I am not too familiar with C/C++ builds.

**Comment by minhnguyenhoang** [comment]
Thanks for the help. Unfortunately I do not know how to run Dockerfiles, appreciate the help anyways, it could be useful.
I downloaded 1.2.30 and skia-m81, cmake using Clang 10 and it worked. Now I'm keeping everything the same except build ver (1.3-b7) and attempting to compile it again

**Comment by boxdox** [comment]
Did you find a solution @minhnguyenhoang ? I tried compiling v1.2.29 with skia m81-b607b32047, and it builds fine. Seems like there's some library incompatibility with the new version of aseprite that causes the build to fail.

**Comment by minhnguyenhoang** [comment]
@boxdox forgot to report back actually. I managed to compile v1.3b7 right afterwards (Clang 10, m81). Seems like a problem with either GCC or skia-m96 (probably skia, as I've seen tutorials online using a precompiled skia and GCC). Thanks for the help. The devs might want to have a look at skia-m96

**Comment by dacap** [comment]
From the error log (`error: ‘SkSamplingOptions’ was not declared in this scope`), it looks like (in your first post) you tried to compile the `main` branch of Aseprite (which now requires skia m91) with skia m81. But I'm not 100% sure.

Anyway now there is a new [note in our INSTALL.md guide about GCC](https://github.com/aseprite/aseprite/blob/main/INSTALL.md#gcc-compiler):

> In case that you are using the pre-compiled Skia version, you will need to use the Clang compiler to compile Aseprite. Only if you compile Skia with GCC, you will be able to compile Aseprite with GCC.

**Comment by minhnguyenhoang** [comment]
@dacap the error I took that from was skia-m96, Clang 10 and v1.3b7.
I have seen that note, hence why I purged GCC to force cmake to use Clang. Seems like it works fine on skia-m81 now.

**Comment by dacap** [comment]
@minhnguyenhoang if you are compiling v1.3b7 you will need skia-m81, if you are compiling `main` or `beta` branches (latest commits), you will need skia-m91.
