### ISSUE TITLE
Saving Sprite Close Prompt, Tab Focus

### ISSUE THREAD

**Issue by James-Getz** [aseprite/aseprite#3080]
When you close Aseprite and have multiple documents open.
If they are not saved, Aseprite will prompt you with
`[Warning] Saving changes to the sprite "SpriteName" before quitting?`

Problem is, it doesn't change the tab focus to the document it's asking to close.
So you can see and make sure that you want to close the document.

### Aseprite and System version

* Aseprite version: 1.3-beta7, Steam/beta
* System: Windows 10 x64

**Comment by Gasparoken** [comment]
Thanks for this report @James-Getz. We'll fix soon.
This happens on v1.2.30 too.

**Comment by dacap** [comment]
It looks duplicate of #2030, I'll take a look to the new PR, because I've already review a previous PR solving this but found [an issue in the past](https://github.com/aseprite/aseprite/pull/2727#issuecomment-852524240).
