### ISSUE TITLE
WebSocket not working

### ISSUE THREAD

**Issue by RedCocoon** [aseprite/aseprite#3084]
The WebSocket API for scirpting as described on [the api documentation page]( https://github.com/aseprite/api/blob/main/api/websocket.md) does not appears to function.
Attached below is the extension that is 99% copied from the documentation. The message type received is always 3 (error).

[websocket-demo.zip](https://github.com/aseprite/aseprite/files/7641158/websocket-demo.zip)

### Aseprite and System version

* Aseprite version: v1.3-beta7-64x , Steam/beta
* System: Linux, 21.04, Pop!_OS

**Comment by dacap** [comment]
Hi @RedCocoon, do you have a WebSocket server listening in `1.1.1.1` IP? Also you should use `http` (or at least `http` is the one I know is working).

You can find an example of the client and server here: https://github.com/lampysprites/aseprite-interprocessing-demo created by lampysprites.

**Comment by RedCocoon** [comment]
Apologize, upon further testing, it seems that my WebSocket server is just not setup correctly, I apologize for the mistake.
