### ISSUE TITLE
I want to ask that the version of Aseprite  on steam is contain arm64 for Mac?

### ISSUE THREAD

**Issue by cyako1999** [aseprite/aseprite#3086]

**Comment by dacap** [comment]
Hi @cyako1999, not at the moment, but we're working on it #2451 

Anyway I saw that Steam doesn't offer different packages between x64 and arm64 architectures (which is available on Windows for x86 vs x64), I'll have to investigate about it and maybe create an universal package (an .app bundle with both architectures) to fix that.
