### ISSUE TITLE
how to update complied aseprite?

### ISSUE THREAD

**Issue by qhqls07** [aseprite/aseprite#3095]
Describe your bug report or feature request here

last time, i download complied aseprite. Now, i know that aseprite is
update to 1.3v. I want to update my aseprite too.. But i don't what to do.
Can you tell me how to update my complied aseprite?
I'm sorry to my bad English. i'm Korean middle school student. 
I'm not good at English TT
please tell me how to update my aseprite in detail.

### Aseprite and System version

* Aseprite version: v1.2.28, dev
* System: Windows

**Comment by iamOgunyinka** [comment]
Hello, @qhqls07! There are two separate but related builds of Aseprite -- the `main` and the `beta`. The `main`, as at the time of writing this comment, is in version 1.2.30 and the `beta` is in 1.3-beta7. The `beta` is the public version of Aseprite where we implement tons of features and look for people's feedback on the features. If I remember correctly, you may upgrade your `main` to the latest `main` build but if you need the `beta`, you would need to buy/compile a separate `beta` build.

@Gasparoken is in a better position to point to you how (and/or if) you can update your build.
