### ISSUE TITLE
How to get the "Secondary Texture" from Sprite Editor

### ISSUE THREAD

**Issue by rekcah1986** [aseprite/aseprite#3110]
![image](https://user-images.githubusercontent.com/3055444/147567109-b05290c8-e06f-421f-bcaa-4143fcbd9878.png)

**Comment by rekcah1986** [comment]
I want to get the normal texture without the material properties.
Thanks every one.

**Comment by Gasparoken** [comment]
Hi @rekcah1986. Sorry, I didn't get the requirement for Aseprite. I'll need more info.

**Comment by rekcah1986** [comment]
https://www.gamedeveloper.com/design/how-to-create-2d-glow-effects-in-unity
The example in the shader graph (a little long, please locate to "secondary textures"), I want the same effect.
