### ISSUE TITLE
ninja error on pop!_os 21.10

### ISSUE THREAD

**Issue by Cellinnek** [aseprite/aseprite#3113]
Got this error while compiling with ninja:
https://pastebin.com/AZdBxggj
Also got some errors with cmake:
[CMakeError.log](https://github.com/aseprite/aseprite/files/7792963/CMakeError.log)
* Aseprite version: 1.3-beta7
* System: pop!_os 21.10

**Comment by ZZaccount1** [comment]
Did you resolve it?

**Comment by Cellinnek** [comment]
Managed to fix the issue by compiling skia myself

**Comment by AJ08Coder** [comment]
> Managed to fix the issue by compiling skia myself

I'm also having to same problem. Is there a guide to compiling skia somewhere or how did you compile skia?
