### ISSUE TITLE
Add support for QOI format

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#3121]
Add support to save/load .qoi files.

There are some other approach for faster file format (e.g. [fpng](https://github.com/richgel999/fpng)) which we might want to look before the .qoi format.

Possible library to use:
* https://github.com/phoboslab/qoi

Requested for first time in ticket 3109:
* https://igarastudio.zendesk.com/agent/tickets/3109

**Comment by druves5582** [comment]
<div class="position-absolute width-full color-bg-default" style="bottom: -4rem;">
  <div class="container-xl p-responsive">
    <div class="d-flex flex-justify-center flex-lg-justify-end color-bg-default">
      <div class="col-8 col-sm-7 col-md-6 col-lg-5 position-relative z-2 right-lg-n12 events-none">
        <picture>
          <source srcset="astro-mona.webp" type="image/webp">
          <img src="astro-mona.svg" width="960" height="967" class="home-astro-mona width-full position-absolute bottom-0 height-auto" alt="Mona looking at GitHub activity across the globe">
        </picture>
      </div>
    </div>
  </div>

**Comment by druves5582** [comment]
<div class="position-absolute width-full color-bg-default" style="bottom: -4rem;">
  <div class="container-xl p-responsive">
    <div class="d-flex flex-justify-center flex-lg-justify-end color-bg-default">
      <div class="col-8 col-sm-7 col-md-6 col-lg-5 position-relative z-2 right-lg-n12 events-none">
        <picture>
          <source srcset="astro-mona.webp" type="image/webp">
          <img src="astro-mona.svg" width="960" height="967" class="home-astro-mona width-full position-absolute bottom-0 height-auto" alt="Mona looking at GitHub activity across the globe">
        </picture>
      </div>
    </div>
  </div>
