### ISSUE TITLE
Creating Slice On Later Frame Then Saving File Leads to "Unsupported chunk" warning.

### ISSUE THREAD

**Issue by behreajj** [aseprite/aseprite#3122]
Hello,

This is a bug report.
I encountered the bug when using Aseprite v1.3-beta7-x64 on Windows 10.

Here are the steps I took. I included some observations; many may not be relevant.
1. Open a new sprite with a transparent background, RGB color mode.
2. Add new frames via the '+' button in the bottom right corner.
3. Observe that, given a discontinuous layer, the intersection of the layer and frames creates new cels. Turning on layer edges indicate transparent images the size of the sprite.
4. Switch to the slice tool.
5. On the final frame, add a slice.
6. Switch to previous frames; observe that the slice bounds persists across earlier frames.
7. Try to change the bounds with the slice tool. This did not work for me.
8. Save the sprite with the `.aseprite` extension.
9. Close and reopen Aseprite.
10. Open the file.
11. Observe error message, "Warning: Unsupported chunk type 0 (skipping)," written twice in the console.

![errorMessage](https://user-images.githubusercontent.com/12038348/148809304-95e5cb79-aceb-4075-87cc-60a1fac28da1.png)

There are a few issues that I found after searching which are potentially related. I posted this issue because I didn't see any with steps for reproduction related to saving and reopening a sprite, though there was mention of corrupted files. https://github.com/aseprite/aseprite/issues/2285 , https://github.com/aseprite/aseprite/issues/2284 .

Thanks for looking into this.
Best,
Jeremy

**Comment by iamOgunyinka** [comment]
@Gasparoken can you please access the severity of this? I tested and confirmed this.

**Comment by Gasparoken** [comment]
Thank you for this report! I was able to reproduce it.

**Comment by dacap** [comment]
Adding some information requested by @iamOgunyinka:

1. There are 3 concepts: slices (`doc::Slices`), a slice (`doc::Slice`), and slice key (`doc::SliceKey`). Each slice has several keys, the idea is that keys (`doc::SliceKey`) are useful to move the slice (`doc::Slice`) through the animation, but each slice (`doc::Slice`) is independent from other slices (you can get several slices for each frame, but just one key for a frame).
2. You can imagine a `doc::Slices` like a group of layers, each `doc::Slice` as a layer, and each `doc::SliceKey` as a cel, but:
3. A slice key is associated with one frame, but that frame is the “starting point frame” of the key, after that, if other key doesn’t appear in the [doc::Keyframes](https://github.com/aseprite/aseprite/blob/9e23d31d84a5bfdccc32aea065ffb60b02b57856/src/doc/keyframes.h#L18) collection (`doc::Slice` contains one), the slice key should be displayed in the screen until a new key appears. Some [tests about doc::Keyframes clear](https://github.com/aseprite/aseprite/blob/main/src/doc/keyframes_tests.cpp) make this more.
4. The slices feature is incomplete (in UI side and logic side), you can read some info in [#721](https://github.com/aseprite/aseprite/issues/721) and the [this comment in #1651](https://github.com/aseprite/aseprite/issues/1651#issuecomment-361919646).
5. Slices are not associated with cels, but only to frames, in a future we'll be able to see slices as one layer row in the Timeline with each keyframe change as a cel. But slices are not associated with cels: so moving/copying/removing only cels shouldn't affect slices at the moment (maybe something for the future).
6. On the other side, copying/removing frames should make some adjustments to the `doc::Slice::List` (a `doc::Keyframes<doc::SliceKey>`) structure (this is the incomplete logic side of the animation support for slices).
