### ISSUE TITLE
Multiple tileset layers  selection move is broken

### ISSUE THREAD

**Issue by m-colombo** [aseprite/aseprite#3144]
Hi all 👋 

I just found out that moving a selection in tileset mode having multiple tileset layers selected leads to loss of information. Only the last selected layers is moved, all the others are cleared (in the selection).

See an example here:
![Screen Recording 2022-01-21 at 13 38 42](https://user-images.githubusercontent.com/8291084/150528757-379bdd60-67da-4a89-83a6-a2e73e658805.gif)

### Aseprite and System version

* Aseprite version: v1.3-beta10-dev compiled from the release archive
* System: macOS 12.1

**Comment by Gasparoken** [comment]
Thanks for this report @m-colombo. I was able to reproduce it.

**Comment by Gasparoken** [comment]
Working on it.
