### ISSUE TITLE
Can't Compile Aseprite On Popos! and void linux

### ISSUE THREAD

**Issue by EMPTYNES** [aseprite/aseprite#3154]
I am trying to compile aseprite but it is giving me error(Attaching it below)
I tired it on void linux as well as on Pop OS,  tried GCC and Clang but still having the same error.
I Am Using main branch and skia-m96 prebuilt as well as self compiled one.

SYSTEM INFO
Linux(Pop!_OS 21.10, Void Linux rolling glibc)
[aseprite_error_log.txt](https://github.com/aseprite/aseprite/files/7969760/aseprite_error_log.txt)

**Comment by mmartinsthiago** [comment]
Me too!

**Comment by PrimaIVoid** [comment]
Exactly same error, on Debian 10 with the latest commit

**Comment by iamSkev** [comment]
Exactly the same error with mine too

**Comment by est77** [comment]
You need to build with clang (gcc does not work anymore with the new Skia binaries) and 
additionally pass the -stdlib=libc++ flag in CMAKE_CXX_FLAGS.
The default for clang on Linux is to use gcc's standard library.

**Comment by atchim** [comment]
> You need to build with clang (gcc does not work anymore with the new Skia binaries)

@est77, I'm also having undefined reference errors even compiling both Aseprite and Skia.

**Comment by EMPTYNES** [comment]
> You need to build with clang (gcc does not work anymore with the new Skia binaries)

Already tried clang , will try using the -stdlib=libc++ flag in CMAKE_CXX_FLAGS.

**Comment by EMPTYNES** [comment]
Thanks @est77 adding stdlib=libc++ flag in CMAKE_CXX_FLAGS worked. @dacap please add to use stdlib=libc++ flag in CMAKE_CXX_FLAGS along with clang when using prebuilt skia in the INSTALL.md too.
