### ISSUE TITLE
Aseprite does not build on Linux.

### ISSUE THREAD

**Issue by HotCoffee04** [aseprite/aseprite#3156]
I tried compiling Aseprite but it gives me a lot of errors when linking 

`
[631/1527] Building CXX object laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o 
/usr/bin/c++  -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_FREETYPE -DLAF_LINUX -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SAMPLES_FOR_X -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I../third_party/zlib -Ithird_party/zlib -I../third_party/libpng -Ithird_party/libpng -I../third_party/libwebp/src -I../third_party/tinyxml -I../third_party/pixman/pixman -I. -I../third_party/giflib -I../third_party/jpeg -I../third_party/curl/include -I../third_party/simpleini -I../laf -Ilaf -I../src -I../laf/third_party/stringencoders/src -I/root/deps/skia -I/root/deps/skia/third_party/externals/freetype/include -I/root/deps/skia/third_party/externals/harfbuzz/src -O2 -g -DNDEBUG   -Werror=suggest-override -std=c++14 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o -c ../laf/os/skia/os.cpp
`
I dowloaded Skia x64 and placed it in home/deps I also tried adding the parameter to disable webp image support but it still gives me this error.
I tried using this https://gist.github.com/yonderbread/b363035fd60fd87857f6d59b4d92c0e3
but it still does not work.

I have Ubuntu 20.04.3 LTS x86_64

**Comment by Himan10** [comment]
Hey, @HotCoffee04 anything you've got or found anywhere to solve this issue? 
I was trying the same recently but got a lot of errors from CPP source files. 

I have Manjaro 21.2.1

**Comment by dacap** [comment]
Hi @HotCoffee04, the script you included in this issue is downloading the main branch of Aseprite which requires the latest Skia build (m102) and the script is downloading m81. Please following the [INSTALL instructions](https://github.com/aseprite/aseprite/blob/main/INSTALL.md) to compile Aseprite.
