### ISSUE TITLE
Add a CLI warning if the file to be manipulated isn't found at the end of the command line.

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3157]
This was recommended here: https://github.com/aseprite/aseprite/issues/3101

### Aseprite and System version

* Aseprite version: 1.2.32-x64
* System: Windows/macOS

**Comment by dacap** [comment]
Please note that some arguments expect the sprite to be specified before (the document must be already opened for the argument to work correctly), e.g. [--color-mode](https://www.aseprite.org/docs/cli/#color-mode):

    aseprite input.aseprite -color-mode indexed -save-as output.aseprite

**Comment by Gasparoken** [comment]
Therefore, this problem is not applicable.
