### ISSUE TITLE
Add the ability to change a group's position

### ISSUE THREAD

**Issue by levilindsey** [aseprite/aseprite#3158]
It would be useful if a group had its own position, which would then be applied to all children layers.

I often find myself wanting to keep my art separated into multiple layers, but also wanting to be able to move those layers around together, as though they were a single unit.

**Comment by Gasparoken** [comment]
Hi there! You can move multiple drawing at the same time doing this:
- Marquee tool: select the area you want to move or just click CTRL+A (or ⌘A on Mac)
- Go to the Timeline and select the layers or group of cel you want to move.
- Move the drawing (this feature hasn't a realtime preview of the drawing while it's moved yet -pending implementation-)

Anyway, I think this feature you recommend is a good one to consider.

**Comment by levilindsey** [comment]
@Gasparoken Yeah, good point! I forgot about that multi-layer selection move. I've used it before, but I think I found it cumbersome to use.

**Comment by Gasparoken** [comment]
This feature will be treated by: https://github.com/aseprite/aseprite/issues/3224 (Possibility to move groups as a unit)
