### ISSUE TITLE
in Mac M1, Steam version, after slice, find no way to save all slices as separate files.

### ISSUE THREAD

**Issue by sloppydevil** [aseprite/aseprite#3167]
tried save as {slice}.png; 
try export including {slice};

it didn't work. Plz help to give quick hint, thx.

**Comment by dacap** [comment]
Hi @sloppydevil, did you try something like this?

    /Applications/Aseprite.app/Contents/MacOS/aseprite -b input.aseprite -save-as output-{slice}.png

**Comment by sloppydevil** [comment]
> Hi @sloppydevil, did you try something like this?
> 
> ```
> /Applications/Aseprite.app/Contents/MacOS/aseprite -b input.aseprite -save-as output-{slice}.png
> ```

## old way doesn't work
Thx so much for quick reply. My aseprite is a steam version. Under ***/MacOS, there is only a run.sh script.
And its content is "open steam://run/431730". 

## another try, it worked!
I use command "ps" to check running process, and found the aseprite is "/Users/Forest/Library/Application Support/Steam/steamapps/common/Aseprite/Aseprite.app/Contents/MacOS/aseprite". 😦

so one need to cd to that address, use this one:
/Users/Forest/Library/Application\ Support/Steam/steamapps/common/Aseprite/Aseprite.app/Contents/MacOS/aseprite -b input.aseprite -save-as output-{slice}.png

!!!: use your own user path, and pay attention to that "\" for path with spaces. Enjoy~😊 

## why not put it in UI version since only we coders can solve that :), while others can't.
another thinking is why not put this feature in "save as" UI versions, whenever user save as "{slice}.png", just trigger this feature. Using regular expression to parsing user's save-as content, makes it easy to identify. 😜

**Comment by sloppydevil** [comment]
> Hi @sloppydevil, did you try something like this?
> 
> ```
> /Applications/Aseprite.app/Contents/MacOS/aseprite -b input.aseprite -save-as output-{slice}.png
> ```

## old way doesn't work
Thx so much for quick reply. My aseprite is a steam version. Under ***/MacOS, there is only a run.sh script.
And its content is "open steam://run/431730". 

## another try, it worked!
I use command "ps" to check running process, and found the aseprite is "/Users/Forest/Library/Application Support/Steam/steamapps/common/Aseprite/Aseprite.app/Contents/MacOS/aseprite". 😦

so one need to cd to that address, use this one:
```bash
/Users/Forest/Library/Application\ Support/Steam/steamapps/common/Aseprite/Aseprite.app/Contents/MacOS/aseprite -b input.aseprite -save-as output-{slice}.png
```

!!!: use your own user path, and pay attention to that "\" for path with spaces. Enjoy~😊 

## why not put it in UI version since only we coders can solve that :), while others can't.
another thinking is why not put this feature in "save as" UI versions, whenever user save as "{slice}.png", just trigger this feature. Using regular expression to parsing user's save-as content, makes it easy to identify. 😜

**Comment by sloppydevil** [comment]
> Hi @sloppydevil, did you try something like this?
> 
> ```
> /Applications/Aseprite.app/Contents/MacOS/aseprite -b input.aseprite -save-as output-{slice}.png
> ```

> Hi @sloppydevil, did you try something like this?
> 
> ```
> /Applications/Aseprite.app/Contents/MacOS/aseprite -b input.aseprite -save-as output-{slice}.png
> ```

## old way doesn't work
Thx so much for quick reply. My aseprite is a steam version. Under ***/MacOS, there is only a run.sh script.
And its content is "open steam://run/431730". 

## another try, it worked!
I use command "ps" to check running process, and found the aseprite is "/Users/Forest/Library/Application Support/Steam/steamapps/common/Aseprite/Aseprite.app/Contents/MacOS/aseprite". 😦

so one need to cd to that address, use this one:
```bash
/Users/Forest/Library/Application\ Support/Steam/steamapps/common/Aseprite/Aseprite.app/Contents/MacOS/aseprite -b input.aseprite -save-as output-{slice}.png
```

!!!: use your own user path, and pay attention to that "\" for path with spaces. Enjoy~😊 

## why not put it in UI version since only we coders can solve that :), while others can't.
another thinking is why not put this feature in "save as" UI versions, whenever user save as "{slice}.png", just trigger this feature. Using regular expression to parsing user's save-as content, makes it easy to identify. 😜
