### ISSUE TITLE
Aseprite exporting incorrrect json data when using linked cells, split layers and trim

### ISSUE THREAD

**Issue by jestarray** [aseprite/aseprite#3168]
![bad](https://user-images.githubusercontent.com/34615798/153073142-e3e524a3-19ca-4fff-bae9-63b21c054e46.png)

![image](https://user-images.githubusercontent.com/34615798/153075004-df13ce1d-c0c0-4799-995b-e4f30f06918c.png)

My game requires sprites to consists of 2 parts/layers, a head and a body, and it seems aseprite exports the `spriteSourceSize` incorrectly.

The pink head has a `spriteSourceSize` of: 12x14, which is correct on the 1st frame but on the 2nd frame, you can see it's at 18x29 despite the cells being the exact same linked cels, and this causes it to render incorrectly in my game.

```
 {
    "filename": "head_idle_s_0_500",
    "frame": { "x": 0, "y": 0, "w": 12, "h": 14 },
    "rotated": false,
    "trimmed": true,
    "spriteSourceSize": { "x": 10, "y": 1, "w": 12, "h": 14 }, // CORRECT ✅
    "sourceSize": { "w": 32, "h": 32 },
    "duration": 500
   },
   {
    "filename": "head_idle_s_1_500",
    "frame": { "x": 0, "y": 0, "w": 12, "h": 14 },
    "rotated": false,
    "trimmed": true,
    "spriteSourceSize": { "x": 8, "y": 1, "w": 18, "h": 29 }, // WRONG ❌
    "sourceSize": { "w": 32, "h": 32 },
    "duration": 500
   },
```

Here is the ase file to reproduce: https://cdn.discordapp.com/attachments/219996127179702272/941860396632010893/bad.ase

and my export settings:
`{layer}_{tag}_{tagframe}_{duration}`
![image](https://user-images.githubusercontent.com/34615798/153076370-d7e716f6-c486-4cd8-ade8-1fa73c860d85.png)

### Aseprite and System version

Arch Linux
Aseprite latest build of master as of feb 02, 2022

Possibly related to: https://github.com/aseprite/aseprite/issues/2600

**Comment by Gasparoken** [comment]
Thanks for this report @jestarray. I was able to reproduce it and it'll solved soon.
I'll close this issue as it's duplicated with the one you mentioned #2600. Thank you again!
