### ISSUE TITLE
Problems opening the Aseprite executable

### ISSUE THREAD

**Issue by Bitzbytz** [aseprite/aseprite#3185]
## Problems opening the executable

When running cmake and compiling Aseprite, no major errors occurred. But when trying to open the Aseprite executable an error message opened in terminal. I'm not sure if I'm doing it right or if this is expected as I haven't seen any other issues about this.

### Error message:
```
dyld: Library not loaded: libdeflate.0.dylib
  Referenced from: /Users/jiaruichen/Desktop/Aseprite/build/bin/aseprite
  Reason: image not found
zsh: abort      /Users/jiaruichen/Desktop/Aseprite/build/bin/aseprite
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]
```

Hope someone can help!
Thanks in advance

### Aseprite and System version

* Aseprite version: v1.2.3.3
* System: macOS 11.4 (Apple Silicon M1)

**Comment by dacap** [comment]
Hi @Bitzbytz, it looks like your local copy of libdeflate.0.dylib (maybe installed with homebrew?) was used in the compilation process, could you share your `CMakeCache.txt` file?

**Comment by Bitzbytz** [comment]
Here is my [CMakeCache.txt](https://github.com/aseprite/aseprite/files/8128619/CMakeCache.txt) file.

**Comment by Bitzbytz** [comment]
When I tried removing the lines it didn't work, but I fiddled with it and tried different things. I ended up getting it working by changing it to:
```
//Path to a file.
DEFLATE_INCLUDE_DIRS:PATH=

//Path to a library.
DEFLATE_LIBRARY:FILEPATH=
```
I just removed the `VALUE` for the 2 file paths and reran `ninja aseprite`.

Thank you so much for helping me!!
