### ISSUE TITLE
Downloading from github causes many folders to be empty

### ISSUE THREAD

**Issue by DonaverBoxwood** [aseprite/aseprite#3186]
When downloading aseprite from github using the "download zip" option, some folders are completely empty upon unzipping the zip file (specifically, all folders that have an @ followed by a number. See attached image for details.) 

![observable is empty](https://user-images.githubusercontent.com/100310804/155385733-fd010051-4bf2-4952-b16e-30a3425dde8c.png)
![laf is empty](https://user-images.githubusercontent.com/100310804/155385736-6ca5550f-05c1-4d0a-a475-4f3c868254bd.png)
![pic of aseprite github page two](https://user-images.githubusercontent.com/100310804/155385737-b7252480-ed84-45bc-a732-3a5043dce955.png)
![pic of aseprite github page one](https://user-images.githubusercontent.com/100310804/155385740-83aeefa8-bee0-41b1-a230-735dcd7af7ff.png)

### Aseprite and System version

* Aseprite version: latest
* System: Windows 11

**Comment by dacap** [comment]
Hi there @DonaverBoxwood 👋 it's a known issue with GitHub. We use submodules, and the default/automatic .zip that GitHub offers doesn't include the source code of submodules (this is a problem with all repositories that use submodules), so you have to download the .zip that we distribute in the [Releases](https://github.com/aseprite/aseprite/releases) page.
