### ISSUE TITLE
Fix Full Preview and Edges setting on Cursors preferences

### ISSUE THREAD

**Issue by ProgrammingParadox** [aseprite/aseprite#3188]
It would be very nice if there was a preference to put an outline around the brush so it can still be seen when in a "blob" of it's own color. Just a thought.

### Aseprite and System version

* Aseprite version: version number, portable
* System: Windows

**Comment by Gasparoken** [comment]
The Preference 'Full Preview and Edges' doesn't draw the cursor edges.

- Aseprite version: 1.2.33 and 1.3-beta11
- System: tested on MacOS Catalina

**Comment by darthgrayter** [comment]
Update on this?
