### ISSUE TITLE
App is crashing when palette presets is open

### ISSUE THREAD

**Issue by GabrielModog** [aseprite/aseprite#3189]
The app is crashing when I click on _palette  presets_. 

![GIF 27-02-2022 13-15-47](https://user-images.githubusercontent.com/1420545/155890323-784529f7-f4ff-45fe-9e9b-8a8b1f34e952.gif)

### Aseprite and System version
* Aseprite version: Aseprite v1.x-dev (commit hash: 2bb93247aafdb0190139e00c5d991a5a5346c17f)
* System: Win 10 pro and Win 11 home

**Comment by justburner** [comment]
+1
Having same issue.

**Comment by lajawi** [comment]
Same problem, built Aseprite myself though.
(I don't know where to find the build #)

**Comment by Gasparoken** [comment]
It can be reproduced on Aseprite version 1.2.34 & 1.3beta12 (Windows and MacOS).
1.2.33 & 1.3beta11 is working fine for me.

**Comment by TufanMeric** [comment]
I'm having this issue. Completely uninstalled Aseprite along with its data and reinstalled, nothing changed. I did not have this issue a few months ago.
