### ISSUE TITLE
Exporting gif at 1000% causes aseprite to crash

### ISSUE THREAD

**Issue by CaptainOrigami** [aseprite/aseprite#3194]
I am working on a project where I am animating a 5 frame gif on a 480x270 pixel canvas. I have been posting updates of the gif to my friend as I have made progress on it and have been exporting the image for sharing to 1000% scale for my friends to see. Suddenly today, I have tried exporting the gif and cannot export it at 1000%, and when I try to, aseprite crashes. I don't understand why it is crashing as the file size and complexity isn't that crazy? Any ideas on how to fix?

I have attached the file that causes aseprite to crash then attempting to export it as a gif at 1000%

I have tried using Aseprite 1.3.b7-x64 on Win10.

[MenuUpscaledFinalrefrencedeleted.zip](https://github.com/aseprite/aseprite/files/8191911/MenuUpscaledFinalrefrencedeleted.zip)

**Comment by Gasparoken** [comment]
Thanks for this report. I used Aseprite 1.3-beta11 in a MacOS, it didn't crash, but I saw a huge amount of memory is used (25GB) and the upscale process takes 1 minute. We'll take a look.
The actual internal process is:
1. Resize the sprite
2. Convert the sprite to the desired output format

A better approach in this particular case (to keep the memory and process time to a minimum) would be:
1. Convert RGBA to Indexed Color Mode when Nearest-Neighbor resize method + GIF output format is used.
2. Resize the sprite
3. Convert the sprite to GIF

Also, implementing resizing "on the fly" https://github.com/aseprite/aseprite/issues/3008 might result in better performance.
