### ISSUE TITLE
Ctrl-Shift while in pencil tool creates extra line

### ISSUE THREAD

**Issue by lunathir** [aseprite/aseprite#3196]
### Aseprite and System version

* Aseprite Version: v1.3-beta11 on Steam
* System: Windows 11/Linux Mint: Debian Edition

### How to Reproduce

* Make new canvas, or open any image
* Select pencil tool
* Make a line with Ctrl-Shift, ensuring the crosshair is not over the line you are drawing. Easiest if you create a really long line, as the granularity makes it easy.

### Results
Expected: There should be a single line with a single transaction, no more pixels, no less.
Occurance: There are two lines, one snapping to where it should and another snapping directly to your cursor from where the previous line ended. Undo completely removes both lines, rather than just one of the created ones.

**Comment by Gasparoken** [comment]
Thanks @lunathir for this report. I was able to reproduce it.
