### ISSUE TITLE
Pivot point moves itself

### ISSUE THREAD

**Issue by turesiht** [aseprite/aseprite#3202]
When selecting the area and then clicking inside selection or moving it, the pivot point moves away for no reason

Below are imgur links to screenshots in the followng order:
1) Selected the area
2) Moved it and pivot point moved itself too
3) Rotated the are to show how it behaves itself with the pivot point off

https://imgur.com/gmZ88e5
https://imgur.com/rNrv0Qy
https://imgur.com/WvG0JBs

Aseprite Version: v1.3-beta13 on Steam

OS (sorry, I can only copy this in russian):
Выпуск	Windows 10 Домашняя для одного языка
Версия	21H1
Дата установки	‎02.‎02.‎2022
Сборка ОС	19043.1586
Взаимодействие	Windows Feature Experience Pack 120.2212.4170.0

**Comment by turesiht** [comment]
After testing around a bit I found that when first rotating the selected area and then moving it results in jumping of that area around

**Comment by Gasparoken** [comment]
Thanks for this report @turesiht. I was able to reproduce it. It'll solved soon.

**Comment by dacap** [comment]
I think it's related: https://steamcommunity.com/app/431730/discussions/2/4658416565943773518/

**Comment by dacap** [comment]
Also reported here: https://steamcommunity.com/app/431730/discussions/2/4658416565944248871/

@Gasparoken tell me how it goes the progress about it, I can test it too.
