### ISSUE TITLE
Incorrect detection of cel bounds

### ISSUE THREAD

**Issue by jestarray** [aseprite/aseprite#3206]
![bug_bounds](https://user-images.githubusercontent.com/34615798/158637831-6dadd985-3dcb-4959-baab-b939da30b346.png)

First frame, first layer(left side) cannot detect the cel bounding box but second frame(right side) can, when exporting packed atlas with trimming, it says they are the exact same. Can't find any pixels around it that would make a difference either.

Aseprite file: https://cdn.discordapp.com/attachments/527442731732041728/953682720238759956/bugcop-female.ase

### Aseprite and System version

* System: Windows(beta 13) and Linux(build of master as of feb 02, 2022)

**Comment by jestarray** [comment]
I think its related to me generating aseprite files from a packed texture atlas:
```lua
-- Image, Image, Rect, Rect, palette
local function draw_section(src_img, dest_img, src_rect, dest_rect, palette)
    local frame = src_rect
    local source = dest_rect
    for y = 0, frame.h - 1, 1 do
        for x = 0, frame.w - 1, 1 do
            local src_x = frame.x + x
            local src_y = frame.y + y
            local color_or_index = src_img:getPixel(src_x, src_y)
            local color;
            if src_img.colorMode == ColorMode.INDEXED then
                color = palette:getColor(color_or_index)
            else
                color = color_or_index
            end
            local dest_x = source.x + x
            local dest_y = source.y + y
            dest_img:drawPixel(dest_x, dest_y, color)
        end
    end
end
```
I use this custom drawing function to select a rectanglar region of pixels from the packed atlas and draw it on a cel since the docs doesnt seem to provide one iirc.

Here's the script
https://github.com/jestarray/aseprite-scripts/blob/master/jest_import_packed_atlas.lua#L475

**Comment by behreajj** [comment]
Hi @jestarray,

Does calling

```lua
app.command.CanvasSize {
    ui = false,
    left = 0, top = 0,
    right = 0, bottom = 0,
    trimOutside = true }
```

at the end of your script make a difference?

I might've had a similar issue: https://community.aseprite.org/t/crop-transparent-pixels-from-cel-images-for-imported-gifs/11259. (I didn't want to use `CanvasSize` for my case because it's possible for a cel image to extend beyond the canvas, and trimming a cel image to canvas is not the same as trimming its alpha.)
