### ISSUE TITLE
sprites are not loading

### ISSUE THREAD

**Issue by aleskuro** [aseprite/aseprite#3221]
Describe your bug report or feature request here
... sprites
... are
... not
... loading

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by dacap** [comment]
Hi @aleskuro, we'll need some extra information, how are you loading the files? from where? what operating system are you using? what version of Aseprite?
