### ISSUE TITLE
Compose groups separately from all other layers

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#3225]
The default way to composition should be to compose groups first, and then blend groups as a layer. This would allow to specify a blend mode for groups too (or [mask layers](https://github.com/aseprite/aseprite/issues/459)).

A first step was implemented (ffc3684b1bd0887b8d9ab803430c7082fb488a46) by @belchiorg and @gui-marc in #4507. It's an experimental implementation as it requires some extra memory allocations, but I think it's a good base to start improving it.

**Comment by belchiorg** [comment]
Hi!! I have some background in GC and think this feature is something I could help implementing. Would it be possible for me to work on this issue?
