### ISSUE TITLE
Eyedropper shortcut not working as expected in particular circumstances

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3236]
Unexpected behaviors:
1. Eyedropper shortcut (Alt+click) not pick up the color in one click in other non active sprite (two are needed)
2. When zoom tool is active, eyedropper shortcut (Alt+click) do a "zoom in" action on the first click in other non active sprite, instead picking the color.

How to reproduce the bug:

Common actions to both:
- New sprite RGBA. Paint something (sprite A). 
- New sprite RGBA. Paint something of different the color (sprite B).
- Drag the tab of sprite A, and drop between the color bar and the windows of sprite B, to see both sprites at the same time in the editor.
- Go to _View > Preview_

Particular actions to reproduce (1):
- Starting from sprite A as the active one.
- Press and hold 'Alt' (eyedropper quick tool) and hit just one time the left click on sprite B to pick up the color. You'll see current color doesn't update.
Expected:  one click should be enough to update the current color.

Particular actions to reproduce (2):
- Starting from sprite A as the active one.
- Select Zoom Tool
- Press and hold 'Alt' (eyedropper quick tool) and hit just one time the left click on sprite B to pick up the color. You'll see that a 'zoom in' command is done.
Expected:  one click should update the current color. No zoom action at all.

### Aseprite and System version

* Aseprite version: 1.3beta14
* System: Windows and macOS

Reported on ticket: https://igarastudio.zendesk.com/agent/tickets/3394

**Comment by dacap** [comment]
Probably related to https://community.aseprite.org/t/color-picker-defective-after-last-update-1-2-35/14904
Only reproducible in the Preview window is visible

**Comment by rabrant** [comment]
Still not fixed on RC4.

**Comment by Gasparoken** [comment]
> Still not fixed on RC4.

Hi @rabrant, I just tried the original steps which reproduce this bug in 1.3rc4 and it seems to be fixed. Could you list the steps to reproduce the case?
