### ISSUE TITLE
free tool

### ISSUE THREAD

**Issue by lonely-unicorn** [aseprite/aseprite#3238]
Hi

On the website I can read this tool is needed to be bought.
But here i find the source code.

So is there a free version too?
I don't understand

**Comment by lunathir** [comment]
So, paying is more for convenience and supporting the devs more than anything, but you can use it for free if, and only if, you compile it yourself and only for yourself.

**Comment by Gasparoken** [comment]
Hi @lonely-unicorn. Here are the instructions to compile Aseprite: https://github.com/aseprite/aseprite/blob/main/INSTALL.md
The drawback of getting Aseprite through this way: it cost time (more than 2 hours), GB of your HDD, and errors may appear during the build process.

**Comment by dacap** [comment]
Here some extra questions answered in the past about it:

* https://www.aseprite.org/faq/#if-aseprite-source-code-is-available-how-is-that-you-are-selling-it
* https://community.aseprite.org/t/eula-and-faq-confusion/9377

Basically making the source code available is a way to promote external contributions, get access to the program if you cannot afford it, and pay it when you can.

**Comment by lonely-unicorn** [comment]
Where can I see the full list of things I can put after "cmake"?
Because I don't really know the contents of CMakeLists.txt

cmake -G "Visual Studio 17 2022" is all I need just for visual studio on windows? (I don't need another platform)

**Comment by dacap** [comment]
You have to follow the INSTALL.md guide (and you will need to [compile or download Skia](https://github.com/aseprite/skia) first). The cmake command needs several extra parameters, you can check the details here:

https://github.com/aseprite/aseprite/blob/main/INSTALL.md#windows-details

Anyway these are not easy steps if you are not a programmer. So you will need to read the whole guide to avoid missing some step.

**Comment by lonely-unicorn** [comment]
What a piece of junk
