### ISSUE TITLE
[bug] Cels are not updating their UI after pasting them, mouse movement over them is required to update them

### ISSUE THREAD

**Issue by beetrootpaul** [aseprite/aseprite#3242]
Cels are not updating their UI after pasting them. I have to move mouse over them to see their updated state. It gets super misleading during work on a longer animation with repetitive parts.

Steps to reproduce:

1. Open Aseprite and create a new file, for example 32x32 px, RGBA, transparent background2. 
2. Open Timeline, create a new layer ("Layer 2") and add 7 more frames to have them 8 in total (you don't have to create so many of them to reproduce the error, I suppose, but I want to describe a flow which resembles my real world usage a little bit). All 16 cels of Layer 2 are supposed to be empty.
3. Draw something on Layer 2 frame 1. 
4. Draw something else on Layer 2 frame 4.
5. Turn on linked (continuous) mode for Layer 2. 
6. Copy cel from Layer 2' frame 1 into frame 3 (bug can be observed here too, but in this report I will explain it in next steps). 
7. Select cels of frames from 1 to 4 of Layer 2, press Cmd+C to copy them. 
8. Select Layer 2's cel of frame 5 and press Cmd+V to paste **and do NOT move your mouse cursor NOR move focus to another window**. 
9. Now move the cursor for example down from cel of frame 5, then avoid other Layer 2's cels while moving the cursor to enter cel of frame 7.
10. Now the bug is visible: Only cels wich mouse moving over them got updated, while others are not. Take a look at the screenshot below to see how cels of frames 5 and 7 are correct while 6 and 8 looks empty but shoudn't. Expected behavior is to have them updated too: cel 6 should show linkeage between cels 5 and 7 (because focus is on a linked cel 5) and cel 8 should show a separate drawing there (from the context of focused cel 5).

<img width="477" alt="screenshot 2022-04-08 at 12 37 58" src="https://user-images.githubusercontent.com/92947323/162420187-0a6ba525-53a7-47f1-9e8d-89c6cbc72536.png">

### Aseprite and System version

* Aseprite version:`Aseprite-v1.3-beta14-macOS.dmg` downloaded from www.humblebundle.com
* System: macOS Monterey 12.3 (21E230) on MacBook Pro (16-inch, 2021) with Apple M1 Max CPU

**Comment by dacap** [comment]
Hi @beetrootpaul, thanks for the bug report. I was able to reproduce (I think this is not present in v1.2.34.1, so it might be a regression).

**Comment by dacap** [comment]
I've already assigned this to myself :+1: to be fixed before the next release

**Comment by oceanhahn** [comment]
I meant to report this ages ago and I am glad someone got to it before me, so +1 more here! <3

**Comment by dacap** [comment]
I've noticed that renaming tags has a re-painting issue.

**Comment by Gasparoken** [comment]
Sorry, adding a new tag is fine. The update of the timeline is not performed when modifying tag ranges.

**Comment by dacap** [comment]
Oh nice, I'll fix that one too :+1:
