### ISSUE TITLE
ninja: error: unknown target 'aseprite'

### ISSUE THREAD

**Issue by UserDev987** [aseprite/aseprite#3244]
Describe your bug report or feature request here
After compiling successfully, I executed ninja aseprite, but I get the following error, ninja: error: unknown target 'aseprite', how could I solve this issue please

* System: Linux Mint 20.3 x86_64 
that's the latest asperite version

the command is being exected in this dir
/deps/skia/out/Release-x64

**Comment by AJ08Coder** [comment]
Since you closed it, I assume you solved it and i'm having the same problem so I am wondering how you did solve it
