### ISSUE TITLE
%150 Screen Scale

### ISSUE THREAD

**Issue by uykuda** [aseprite/aseprite#3247]
Describe your bug report or feature request here
...100% is too small
...200% too big
...so 150% can be added

### Aseprite and System version

* Aseprite version: 1.2.32x64, portable
* System: Windows

**Comment by dacap** [comment]
Hi @uykuda, it's duplicate from #2682, this scale was asked before, the only issue would be that the scaling is not pixel-perfect, so it will show some kind of distortion, but it might be minimal, we've to check if we can enable this kind of scaling in a near future.
