### ISSUE TITLE
No longer runs on Windows Server 2012 (?)

### ISSUE THREAD

**Issue by DDRKirbyISQ** [aseprite/aseprite#3248]
This is a strange issue that I'm scratching my head at -- Aseprite no longer runs (at all) on the Windows Server 2012 partition of my macbook air (2012) despite having fully functioned a while ago.

I am aware that WS2012 is an obscure OS, however most apps have run fine on this machine, **including Aseprite itself**, until some time ago (past few months?).

Behavior:
- Running the program has no visible result.  No window opens, no error message, nothing.
- Running the program via a command shell returns immediately with no visible output
- The windows explorer thumbnailer integration seems to work with no problems
- Attempting to open an .ase/.aseprite file directly causes an error "There was a problem sending the command to the program."

Log files:
- The AppData/Roaming/Aseprite folder IS created, with the following contents:
- `Aseprite.log` as an empty file
- `crashdb` folder with a small `settings.dat`, an empty `metadata` file, and two empty folders `attachments` and `reports`.
- There is also a hashed folder/file, e.g.`40d415ea-d195-4b6a-36fa-d1b4ed95349a.run` and `40d415ea-d195-4b6a-36fa-d1b4ed95349a.run.lock`.  The .lock file is empty and the folder doesn't seem to have much useful information...
- __sentry-event has `os„¤name§Windows®kernel_version®6.3.9600.20334§version¨6.3.9600¥build¥20337`
- session.json has `,"status":"ok","errors":0,`

Things I have tried:
- Uninstalling / reinstalling, including deleting the AppData/Roaming/Aseprite folder
- Enabling windows compatibility mode / running as administrator
- Installing 1.2.31 via Steam / installing 1.2.31 from the Humble bundle installer
- Installing 1.3 beta, 1.2.18, 1.1.13 via Steam "betas" feature
As far as I can tell all of these things result in the same above behavior.

Things I have not tried:
- Compiling via source...I haven't done this in a looooong time but could ostensibly try to look into getting it working on another machine.

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows Server 2012, Steam/installer

I'd love to give more info but honestly I'm not sure how I would short of adding some additional logging in source.  Let me know if there is something that I might be missing that would help me (or anyone else) diagnose the problem.

Are there perhaps some runtime dependencies I may be missing (MSVC redistributable...MS windows desktop runtime...) or....anything that you can think of?  =/

**Comment by dacap** [comment]
Hi @DDRKirbyISQ, could you please try the [troubleshooting guide](https://www.aseprite.org/docs/troubleshooting/)?

**Comment by DDRKirbyISQ** [comment]
> Hi @DDRKirbyISQ, could you please try the [troubleshooting guide](https://www.aseprite.org/docs/troubleshooting/)?

My apologies, I should have searched for that guide :x

After reading the guide and seeing that the -debug flag attempts to create a log file on your desktop, I immediately realized what the issue was:  **My desktop folder is currently invalid. =/**

I've changed my desktop folder to point to a network drive (technically, a folder within Google Drive's virtual drive) which currently is inactive (Google Drive is not open/has been reconfigured/etc) and thus invalid -- this causes Aseprite to fail silently.  As you might expect, moving my "Desktop" target to an actual valid folder restores functionality and there are no issues.

I'm closing this issue since I've diagnosed and solved it -- feel free to reopen if internally you think that the normal behavior should be improved here with some sort of error popup or similar.

Thank you!
