### ISSUE TITLE
Issue with copy/pasting on hidden layers

### ISSUE THREAD

**Issue by KrisysTheFool** [aseprite/aseprite#3254]
I've noticed over a hundred or so hours that ctrl+c / ctrl+v behaves in a weird and sometimes disturbing way when a hidden layer is selected. Whenever I have an area of the picture selected with the marquee tool, and I've picked a hidden layer in the layer list, pressing ctrl+c or ctrl+v (if I've noticed that correctly, still not entirely sure on the specifics of what happens) will erase whatever is in that area on the hidden layer without putting anything in the clipboard. It's usually not very problematic, but combined with a little bit of fatigue it sometimes leads to a huge load of mistakes :( I would love to see that fixed. Thanks!

**Comment by dacap** [comment]
Hi @KrisysTheFool, what specific version of Aseprite are you using? (You can check the version of Aseprite in the title bar)

Some bugs related to this were fixed in [v1.2.26](https://www.aseprite.org/release-notes/12/#aseprite-v1-2-26) like #2680
