### ISSUE TITLE
Plugin preferences are wiped after updating an extension

### ISSUE THREAD

**Issue by thkwznk** [aseprite/aseprite#3259]
Plugin preferences are wiped clean after updating an extension. I'm assuming this is a consequence of them being stored in the same folder as the extension, and just being removed with the other files when the old version is deleted.

It is very inconvenient for any extension that uses these preferences heavily, as the user will lose all of the data saved there, probably with very little understanding as to why because updating doesn't even warn about this in the UI.

### Aseprite and System version

* Aseprite version: 1.2.34-1-x64, installed from Itch.io but I'm suspecting that every version will behave this way
* System: Windows 11

**Comment by dacap** [comment]
Thanks for reporting this @thkwznk, I'll try to fix this ASAP for the next release.
