### ISSUE TITLE
Tilemap offset resets to 0 after exporting + resizing

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3267]
To reproduce this bug:

- New file
- Make tilemap layer grid 16x16 pixeles
- Draw a tile.
- Modify the canvas + 8 pixeles
- Go to _Files > Export_, output format: png, resize: 200%
- Output png is fine, but the tilemap offset is reset to 0.

### Aseprite and System version

* Aseprite version: 1.3beta14
* System: MacOS

**Comment by Gasparoken** [comment]
This error was probably resolved with the implementation of: https://github.com/aseprite/aseprite/commit/4aa5fedfec2b809619763eac68b95fca1e46f20c by @dacap.

**Comment by dacap** [comment]
What happen if we do the process manually? E.g resizing, save as, then undoing

**Comment by Gasparoken** [comment]
It's fine too. I'll see if it's possible to do this in CLI.

**Comment by dacap** [comment]
Check if it's reproducible exporting to .webp format as it's not using the "on the fly resizing" yet. (Or just exporting to .ase with resizing too). Both formats use the old method.

**Comment by Gasparoken** [comment]
Webp is ok too. Perhaps you are right about https://github.com/aseprite/aseprite/commit/9a3958278baa6d0f5e87070f1bb179dda3d8d9cf. 🙌🎉
