### ISSUE TITLE
Dependencies for other Linux distributions in INSTALL.md

### ISSUE THREAD

**Issue by kintrix007** [aseprite/aseprite#3269]
Describe your bug report or feature request here

I would like INSTALL.md to list the dependencies for more package managers of various Linux distributions.
My reason is that it is simply inconvenient having to try to figure out how given packages are named on other package managers.
Personally, I can add the install command with the names of the packages for Void Linux. I'm creating this issue before potentially making a pull request.

### Aseprite and System version

* Aseprite version: N/A
* System: Linux, N/A, distributions not already listed in INSTALL.md

**Comment by dacap** [comment]
Hi @kintrix007, unfortunately this is a situation that the authors of Linux distributions have created. Some time ago, we only offered the Ubuntu package names, and then we've added the Fedora ones. As you can see, we could add the package names/instructions for each Linux distribution, but that would be almost an infinite number of options to keep track.

My question is why they have decided to use different package names in different distributions? Creating a new problem (without mention the different packaging solutions, like .deb and .rpm, etc.). I would recommend you to ask these questions to the folks at Void Linux.

**Comment by kintrix007** [comment]
Oh, I mean it is definitely not only Void Linux, it is just one I know what the packages are for. Obviously the difference is not huge, but it is mostly a mix between the other three. One package is named like in Debian, another on like in Fedora etc. Just like they have an overlap and difference as well. NixOS, OpenSUSE and Gentoo, for example, would also have somewhat different package names but I think with Gentoo it wouldn't really be a problem

**Comment by kintrix007** [comment]
Also, I want to mention that this is due to the fact that these all use different package managers and not `apt`, `dnf` or `pacman`. My proposal was to find a way to include these in one way or another. I would take not more than half a screen, or maybe a screen at most to add most. Now if just one gets added then it really shouldn't be the Void Linux instructions, because very few people use it. But OpenSUSE is definitely different.

**Comment by dacap** [comment]
Exactly, that's when I wonder why all of them decided to use different package names. As you can see this is not an issue that should be addressed by each one of the app developers out there. But instead by Linux-distro authors.

I just cannot imagine how much time is spend just trying to find the correct package name on each distribution.

Anyway, there are no plans to include instructions for other Linux distros. Sorry about that.

**Comment by kintrix007** [comment]
Alright, thank you for explaining!
