### ISSUE TITLE
en.ini strings issue

### ISSUE THREAD

**Issue by pixelartgirl** [aseprite/aseprite#3284]
Hi

In the Edit -> preferences window -> General, there is an option "Expand menu bar items on mouseover"
In the file en.ini with all the UI strings, there are those 2 strings:

expand_menu_bar_items_on_mouseover = Expand menu bar items on mouseover
expand_menu_bar_items_on_mouseover_tooltip = <<<END
Check this option to get
this old menus behavior.
END

However, the tooltip is not used for the "Expand menu bar items on mouseover": see screenshot, but the same string "Expand menu bar items on mouseover" is displayed for the tooltip too.

![afbeelding](https://user-images.githubusercontent.com/105394924/167953571-784d0816-9762-4d5e-9efe-0c19c3867498.png)

Is this a bug or is this tooltip string not used anymore?

**Comment by lunathir** [comment]
I believe it's just a bug, but I could be wrong.

**Comment by martincapello** [comment]
Looks like a bug to me either. Thank you!
