### ISSUE TITLE
en.ini unused strings?

### ISSUE THREAD

**Issue by pixelartgirl** [aseprite/aseprite#3286]
Hi

I'm working on a Dutch translation for Aseprite but in the en.ini file under "[options]" section, I find some strings that are not used (at least, I can't find them in the "preferences" window):

gpu_acceleration
gpu_acceleration_tooltip
show_menu_bar
locate_crash_folder
slide_zoom

Can those be ignored in the file? So they can be deleted by somebody?

I'm testing my translation in version Aseprite v1.3-beta14

PixelArtGirl

**Comment by Gasparoken** [comment]
Thanks  @pixelartgirl for your collaboration!

**gpu_acceleration** = GPU acceleration <-- Edit > Preferences > General (If the platform does support GPU acceleration)

**gpu_acceleration_tooltip** = Check this option to enable hardware acceleration <-- idem

**show_menu_bar** = Show Aseprite menu bar    <-- Edit > Preferences > General (If the OS does support native menus)

**slide_zoom** = Zoom sliding two fingers up or down <-- Edit > Keybord Shortcuts > Mouse Wheel (second checkbox)

**locate_crash_folder** = Locate Crash Folder  <-- Edit > Preferences > General (appeared after a reboot of Aseprite which crashed previously, this is old behavior), I think it should be removed as we have an automatic system for sharing crash reports. @dacap do you agree?

**Comment by dacap** [comment]
About the GPU strings, they are not used yet, but [we're working on GPU acceleration](https://github.com/aseprite/aseprite/issues/960#issuecomment-912876179) for future versions, anyway probably the strings will change, e.g. to choose the GPU API, like OpenGL, Direct3D, Metal, etc.

> **locate_crash_folder** = Locate Crash Folder <-- Edit > Preferences > General (appeared after a reboot of Aseprite which crashed previously, this is old behavior), I think it should be removed as we have an automatic system for sharing crash reports. @dacap do you agree?

This is still used on debug versions (to locate a .dmp, can be used to double-click the .dmp and start the Visual Studio debugger), not sure if we should remove it yet.

**Comment by pixelartgirl** [comment]
I'll translate all strings, even if currently unused.

> **slide_zoom** = Zoom sliding two fingers up or down <-- Edit > Keybord Shortcuts > Mouse Wheel (second checkbox)

I can't find this second checkbox in v1.3-beta 14 (compiled from source code).

![afbeelding](https://user-images.githubusercontent.com/105394924/168325553-a638f31c-c2b7-4caa-bd49-0dd33b23b8f0.png)

**Comment by Gasparoken** [comment]
If you're confortable, that's ok. Personally, I use [(VSCODE and git)](https://www.digitalocean.com/community/tutorials/how-to-use-git-integration-in-visual-studio-code)

**Comment by dacap** [comment]
> I can't find this second checkbox in v1.3-beta 14 (compiled from source code).

This is an option only available on macOS.

**Comment by pixelartgirl** [comment]
I'm trying to make a program in C# that compares en.ini to any translation ini file and gives as a result the missing/unused/verified strings. In this way you immediately can see what's different between the 2 files.

- missing: Strings present in the English INI File but NOT in Your Translation INI File
- unused: Strings present in Your Translation INI File but NOT in the English INI File
- verified: Strings present in the English INI File AND in Your Translation INI File


See screenshot.

![afbeelding](https://user-images.githubusercontent.com/105394924/168338303-125e67eb-171b-455d-8aac-450ff66a3f8f.png)

If the program works correctly, I announce it on the community so translators can easily check their translation file.

**Comment by pixelartgirl** [comment]
I have a question about the INI translation file: is each string name unique in the entire INI file?
So the left hand side of the "="?

**Comment by dacap** [comment]
> I'm trying to make a program in C# that compares en.ini to any translation ini file and gives as a result the missing/unused/verified strings. In this way you immediately can see what's different between the 2 files.

Oh it looks great. In the past we were distributing some en.ini diff files (e.g. in v1.2.8 https://www.aseprite.org/release-notes/12/#aseprite-v128, the differences https://gist.github.com/dacap/c95cbcefd540795ed88d69b323ebdab6).

This can be calculated with git directly:

    git diff v1.2.7..v1.2.8 data/strings/en.ini

So basically, if you know the version (or commit) of the `en.ini` file which your own `.ini` translation is based on, you can reconstruct the differences of the `en.ini` from that commit to the latest one. I'd recommend you to put a note of the commit/number of version in your `.ini` header (lines starting with `#` are comments/ignored).

> I have a question about the INI translation file: is each string name unique in the entire INI file? So the left hand side of the "="?

It's unique when the anme of the string is combined with the section name `[cel_popup_menu] clear` and `[select_accelerator] clear` are two different strings (anyway might have the same text).

**Comment by pixelartgirl** [comment]
My program is ready. Let me know what you think :)

https://community.aseprite.org/t/aseprite-translation-manager/14253

**Comment by pixelartgirl** [comment]
I close this. Everything is clear for me!
