### ISSUE TITLE
Build failed on Windows.

### ISSUE THREAD

**Issue by AkashElnoorkar** [aseprite/aseprite#3289]
Hello, I have been having this issue repeatedly in the last step where we build it with the command "ninja aseprite".

The error is as follows : 
C:\aseprite\third_party\json11\json11.cpp : warning C4710: '__cdecl json11::Statics::~Statics(void) __ptr64': function not inlined
[398/1526] Building C object third_party\cmark\src\CMakeFiles\cmark_static.dir\utf8.c.obj
cl : Command line warning D9025 : overriding '/W3' with '/W4'
ninja: build stopped: subcommand failed.

Any help on the given issue would be much appreciated!

### Aseprite and System version
Aseprite v1.2.34.1
Windows 10 (64bit)
CMake-3.23.1-windows-x86_64
Ninja v1.11.0
Skia-m102
Visual Studio 2022 (SDK and the other requirements already installed)

**Comment by dacap** [comment]
Hi @AkashElnoorkar, it looks like that is not the specific error, but only a warning. Do you have the full console output of the "ninja aseprite" command?

**Comment by AkashElnoorkar** [comment]
Hello and thanks for replying.
Here's the full console output of the "ninja aseprite" command orderwise in the given screenshots :

![Screenshot (91)](https://user-images.githubusercontent.com/75521160/168824244-76806171-e781-41be-b165-f1cff13a9247.png)

![Screenshot (92)](https://user-images.githubusercontent.com/75521160/168824293-0c8a9283-2022-42f0-ba9f-9b3350ce9177.png)

![Screenshot (93)](https://user-images.githubusercontent.com/75521160/168824328-9b790c55-87f1-48ac-94b7-ea202e06e3aa.png)

![Screenshot (94)](https://user-images.githubusercontent.com/75521160/168824335-a7f7f0c4-0cfe-4709-8100-b6e85dff239e.png)

![Screenshot (95)](https://user-images.githubusercontent.com/75521160/168824339-6037bf34-7497-4153-8bf2-51fa0bdcbe5a.png)

![Screenshot (96)](https://user-images.githubusercontent.com/75521160/168824343-12ecb6ba-a290-4465-8dae-ecb59eea007c.png)

![Screenshot (97)](https://user-images.githubusercontent.com/75521160/168824347-c0f48f4b-887d-4884-81f1-37ca7b83b5a5.png)

![Screenshot (98)](https://user-images.githubusercontent.com/75521160/168824350-bb252dd3-c3e5-43fa-b11e-720a08ab87a6.png)

![Screenshot (99)](https://user-images.githubusercontent.com/75521160/168824739-0a9c9c6c-bd4a-45d4-a216-53f3f65a8a54.png)

**Comment by dacap** [comment]
It looks like there is a mix between MSVC and MinGW compiler. You should use MSVC only (starting the command prompt of Visual Studio), and in the best case removing MinGW from the PATH. We don't support MinGW.

**Comment by AkashElnoorkar** [comment]
Hello, I have removed MinGW compiler from the path and it has worked to some extent. 
But, now I have got a new error, please have a look into it : 

https://gist.github.com/AkashElnoorkar/a167e6a7802a9d561a8788b075323124

**Comment by pixelartgirl** [comment]
I remember when I compiled 1.3 beta 14, I had used skia-m102 and had some errors.
I used the older version of skia and all errors in ninja were gone.

I don't know if this is the case here.

**Comment by AkashElnoorkar** [comment]
This somehow worked successfully! Thanks @pixelartgirl and @dacap for the help!
Closing this issue with this comment.

**Comment by pixelartgirl** [comment]
I have a question for @dacap : how do we know what skia version to use when compiling a source code zip file (of version 1.2 or 1.3 beta) or from the current github source code ?

Thank you!

**Comment by rainlizard** [comment]
yeah I suggest in INSTALL.md you guys put emphasis on the importance of having the correct skia version. I failed both by having too recent of a version AND failed by having too old of a version, almost gave up entirely.

**Comment by dacap** [comment]
As a general rule the version to use of Skia is the one specified in the INSTALL.md guide of the specific commit or downloaded .zip file (e.g. when you want to compile from a Release source file, like 1.3.34.1 or 1.3-beta14 you have to take a look to the INSTALL.md file from that download). The INSTALL.md guide from the main/beta branches is useful only for that specific commit/branch.
