### ISSUE TITLE
beginning script programming: pixelate source image to aseprite canvas

### ISSUE THREAD

**Issue by ghost** [aseprite/aseprite#3291]
Hi everybody!

I know this is not a discussion forum but I wanted to ask a question to the developers themselves about a script idea and if it's possible to implement using aseprite lua scripts...

I made a program in C# that can "pixelate" a source image:

- read a JPG image, convert it to a bitmap image.

- Then the program generates 16 colors by taking 16 random pixels from the bitmap and take its color (it also adds black and white color to the color list)
To get the color from a pixel from the bitmap I use this function: 

https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.getpixel?view=netframework-4.8&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Drawing.Bitmap.GetPixel)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.8)%3Bk(DevLang-csharp)%26rd%3Dtrue

- the user chooses a "pixel spacing" which means how big the pixels are e.g. a square of 1 px, 2 px, 3 px, ...

- when this is done, the program draws rectangles with size "pixel spacing" by taking colors from (X,Y) coordinates of the original source image. In this way the pixelated image is drawn.

=> the goal is to take any input image and pixelate it so you directly work on this in the aseprite canvas (modify to result in pixel art).
I want to make a script that does this.

Please see below screenshots, source and destination image (of a sample run) and the program source code. The "Bin" folder contains the EXE so you can run it yourself.

screenshot:

![afbeelding](https://user-images.githubusercontent.com/105394924/169093023-0c347025-fa50-4665-853b-894beff60d51.png)

source:

![afbeelding](https://user-images.githubusercontent.com/105394924/169093079-134b931d-316c-4f07-abef-ce2b5e2a0a27.png)

destination:

![afbeelding](https://user-images.githubusercontent.com/105394924/169093166-68163b37-ab61-44a4-b162-12e0b8c9e977.png)

source code (visual studio 2022 C#):

[PIXELYZER.zip](https://github.com/aseprite/aseprite/files/8718228/PIXELYZER.zip)

My question is: can all this be made using aseprite lua script and what functions do I need for this?
How to read image (JPG or BMP), get color of image pixel, ...?

I need example scripts because the examples on github can't be used for anything of this.
If it's possible, I'm also looking for somebody to help. I don't know anything about Lua or aseprite scripting API

PixelArtGirl

**Comment by pixelartgirl** [comment]
I was also wondering: are there official tutorials (with some explanation) on how to make scripts? A "hello world" example and some others for UI and canvas specific examples?
For complete beginners it's very hard without such tutorials :(

**Comment by Gasparoken** [comment]
Yes. You can make that you described.
The important functions you will need are (among others like Point() constructor):
. [app.open()](https://www.aseprite.org/api/app#appopen) this returns a Sprite
. [Sprite() constructor](https://www.aseprite.org/api/sprite?l=Sprite&t=Sprite#sprite) new Sprite to put the result
. [Image() constructor](https://www.aseprite.org/api/image?l=Image&t=Image#image) future pixelated image
. [Sprite:newCel()](https://www.aseprite.org/api/sprite?l=Sprite&t=sprite#spritenewcel)
. double 'for' loop to travel the Image: read/search for some of [Lua documentation](https://www.lua.org/pil/contents.html#P1)
. [Image:getPixel()](https://www.aseprite.org/api/image#imagegetpixel) to read one pixel
. [Image:putPixel() or Image:drawPixel()](https://www.aseprite.org/api/image#imagedrawpixel) to write one pixel

Hello world in Lua (to write in the console):
- You need to make a text file 'helloworld.lua' and write:
- `print("Hello World")`
- This file should be moved to the [script folder](https://community.aseprite.org/t/locate-user-scripts-folder/2170) 
- On Aseprite go to _File > Scripts_
- Click on `helloworld`, if you don't see the option, press `Rescan Scripts Folders`, then `helloworld`.

A couple of sites with lua examples:
Script examples: https://community.aseprite.org/t/aseprite-script-examples/2611
Script Collection: https://community.aseprite.org/t/aseprite-scripts-collection/3599

**Comment by pixelart-girl** [comment]
Thanks for the explanation but as you can see I deleted my account.
It's too hard for me since don't know aseprite yet.
