### ISSUE TITLE
Can't compile on linux fatal error: clang-13: error: linker command failed with exit code 1 

### ISSUE THREAD

**Issue by NNeedlemouse** [aseprite/aseprite#3328]
After this new skia update, ive been having a hard time compiling aseprite on linux. Even on the official install.md. I used m96 for the latest version of aseprite but that wouldnt even compile right. idk if its really my clang. It should be working.

here is the full error i encountered
https://pastebin.com/gLnMneKU

* Aseprite version: 1.3, beta14
* System: Linux, Endeavoros(Arch based)

**Comment by dacap** [comment]
Hi @NeedlemouseBruh, if you are trying to compile the 1.3-beta14 .zip file you must use the previous m96 skia version (anyway on Linux I would recommend you to compile Skia yourself). If you are trying to compile the latest main/beta commit, you need m102.

**Comment by NeedlemouseBruh** [comment]
> Hi @NeedlemouseBruh, if you are trying to compile the 1.3-beta14 .zip file you must use the previous m96 skia version (anyway on Linux I would recommend you to compile Skia yourself). If you are trying to compile the latest main/beta commit, you need m102.

I am compiling the 1.3beta14. I compiled skiam96 but i still keep getting errors. I basically got the same error i put in the paste bin link. I still have the clang error too
![Screenshot_20220523_182757](https://user-images.githubusercontent.com/87540491/169920224-b3d7ba22-142a-412b-a0f4-ebf9b3180d09.png)

**Comment by dacap** [comment]
Just in case, remember to use:
```
cmake
  .....
  -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
  -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
  .....
```
When running cmake, or you can add these values in the CMakeCache.txt inside the build directory and run `ninja` again. It specifies to use the libc++ library (by Clang/LLVM devs) instead of the GNU one.

**Comment by NeedlemouseBruh** [comment]
>


> Just in case, remember to use:
> 
> ```
> cmake
>   .....
>   -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
>   -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
>   .....
> ```
> 
> When running cmake, or you can add these values in the CMakeCache.txt inside the build directory and run `ninja` again. It specifies to use the libc++ library (by Clang/LLVM devs) instead of the GNU one.

I did all the stuff you said and it still doesnt work. I have them in my cmakecache.txt and i did it with my cmake command. Ran ninja but it still gives me the damn clang-13 error

**Comment by jestarray** [comment]
I have this issue too for the latest v1.13 beta 15 and here's all that i've tried, my OS is Arch:
1. Compiling skia myself using the instructions
2. Using the precompiled skia binaries
3. Nuking my aseprite folder and pulling off of github again

always lead to ending up here:
```
Release-x64/libskia.a(libwebp.ssim.o):ssim.c:(.text.VP8SSIMDspInit+0x0): first defined here
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by jestarray** [comment]
Alright, thanks to martins mozeiko , if you have the same issue I'm having with compiling v1.13 beta 15, run: instead of `ninja aseprite` , or maybe run it after it:

```
/usr/bin/clang++ -stdlib=libc++ -Wall -Wno-switch -O2 -g -DNDEBUG -stdlib=libc++ src/CMakeFiles/aseprite.dir/main/main.cpp.o -o bin/aseprite  lib/libapp-lib.a  lib/libcfg-lib.a  lib/libclip.a  -lxcb  lib/libdio-lib.a  lib/libfilters-lib.a  lib/libflic-lib.a  lib/libtga-lib.a  lib/librender-lib.a  lib/libdoc-lib.a  lib/libfixmath-lib.a  lib/libui-lib.a  lib/liblaf-os.a  lib/liblaf-gfx.a  lib/liblaf-ft.a  /home/a/deps/skia/out/Release-x64/libfreetype2.a  /home/a/deps/skia/out/Release-x64/libharfbuzz.a  /home/a/deps/skia/out/Release-x64/libskia.a  /usr/lib/libGL.so  /usr/lib/libfontconfig.so  /usr/lib/libSM.so  /usr/lib/libICE.so  /usr/lib/libX11.so  /usr/lib/libXext.so  /usr/lib/libXcursor.so  /home/a/deps/skia/out/Release-x64/libskshaper.a  lib/libobs.a  lib/libundo.a  lib/libcmark.a  lib/libjpeg.a  lib/libgiflib.a  lib/libpng16.a  -lm -lm  lib/libjson11.a  lib/libarchive.a  /usr/lib/libcrypto.so  /usr/lib/libacl.so  /usr/lib/libssl.so  lib/libfmt.a  lib/libtinyexpr.a  lib/liblauxlib.a  lib/liblua.a  lib/liblualib.a  lib/libixwebsocket.a  lib/libz.a  lib/libupdater-lib.a  lib/libver-lib.a  lib/libtinyxml.a  lib/libnet-lib.a  lib/liblaf-base.a  lib/libmodpbase64.a  -lpthread  /usr/lib/libdl.so  lib/libcurl.a  -llber  -lldap  -ldl
```

In particular this removes `lib/libwebpdemux.a  lib/libwebpmux.a  lib/libwebp.a`

**Comment by dacap** [comment]
@jestarray did this error happen with skia-m102?

**Comment by jestarray** [comment]
> @jestarray did this error happen with skia-m102?

@dacap Yep, m102 pre compiled binaries and self compiled, got it working with pre-compiled after removing linking with libwebp libs.

> Martins: if you want quick & dirty fix, just copy & paste last linking command from ninja output and remove libwebp*.a libraries, so it uses stuff inside skia library

**Comment by jestarray** [comment]
So now I'm compiling beta branch and I run into the same linking issue, removing linking the webp libs fixes some of it but it still does not link fully:

```
[a@arch build]$ /usr/bin/clang++ -stdlib=libc++ -Wall -Wno-switch -O2 -g -DNDEBUG -stdlib=libc++ src/CMakeFiles/aseprite.dir/main/main.cpp.o -o bin/aseprite  lib/libapp-lib.a  lib/libcfg-lib.a  lib/libclip.a  -lxcb  lib/libdio-lib.a  lib/libfilters-lib.a  lib/libflic-lib.a  lib/libtga-lib.a  lib/librender-lib.a  lib/libdoc-lib.a  lib/libfixmath-lib.a  lib/libui-lib.a  lib/liblaf-os.a  lib/liblaf-gfx.a  lib/liblaf-ft.a  /home/a/deps/skia/out/Release-x64/libfreetype2.a  /home/a/deps/skia/out/Release-x64/libharfbuzz.a  /home/a/deps/skia/out/Release-x64/libskia.a  /usr/lib/libGL.so  /usr/lib/libfontconfig.so  /usr/lib/libSM.so  /usr/lib/libICE.so  /usr/lib/libX11.so  /usr/lib/libXext.so  /usr/lib/libXcursor.so  /home/a/deps/skia/out/Release-x64/libskshaper.a  lib/libobs.a  lib/libundo.a  lib/libcmark.a  lib/libjpeg.a  lib/libgiflib.a  lib/libpng16.a  -lm -lm  lib/libjson11.a  lib/libarchive.a  /usr/lib/libcrypto.so  /usr/lib/libacl.so  /usr/lib/libssl.so  lib/libfmt.a  lib/libtinyexpr.a  lib/liblauxlib.a  lib/liblua.a  lib/liblualib.a  lib/libixwebsocket.a  lib/libz.a  lib/libupdater-lib.a  lib/libver-lib.a  lib/libtinyxml.a  lib/libnet-lib.a  lib/liblaf-base.a  lib/libmodpbase64.a  -lpthread  /usr/lib/libdl.so  lib/libcurl.a  -llber  -lldap  -ldl
/usr/bin/ld: lib/libdoc-lib.a(primitives.cpp.o): in function `doc::calculate_image_hash(doc::Image const*, gfx::RectT<int> const&)':
/mnt/z/aseprite/laf/gfx/rect.h:(.text+0x1ad0): undefined reference to `CityHash64(char const*, unsigned long)'
/usr/bin/ld: lib/libdoc-lib.a(primitives.cpp.o): in function `unsigned int doc::calculate_image_hash_templ<doc::IndexedTraits, 255u>(doc::Image const*, gfx::RectT<int> const&)':
/mnt/z/aseprite/src/doc/primitives.cpp:476: undefined reference to `CityHash64(char const*, unsigned long)'
/usr/bin/ld: lib/libdoc-lib.a(primitives.cpp.o): in function `unsigned int doc::calculate_image_hash_templ<doc::BitmapTraits, 1u>(doc::Image const*, gfx::RectT<int> const&)':
/mnt/z/aseprite/src/doc/primitives.cpp:476: undefined reference to `CityHash64(char const*, unsigned long)'
/usr/bin/ld: lib/libdoc-lib.a(primitives.cpp.o): in function `unsigned int doc::calculate_image_hash_templ<doc::RgbTraits, 16777215u>(doc::Image const*, gfx::RectT<int> const&)':
/mnt/z/aseprite/src/doc/primitives.cpp:476: undefined reference to `CityHash64(char const*, unsigned long)'
/usr/bin/ld: lib/libdoc-lib.a(primitives.cpp.o): in function `unsigned int doc::calculate_image_hash_templ<doc::GrayscaleTraits, 255u>(doc::Image const*, gfx::RectT<int> const&)':
/mnt/z/aseprite/src/doc/primitives.cpp:476: undefined reference to `CityHash64(char const*, unsigned long)'
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Xtendera** [comment]
This can be closed as libwebp is now fixed

**Comment by Xtendera** [comment]
@dacap

**Comment by dacap** [comment]
Closing this now, thanks @Xtendera for bringing all these issues.
