### ISSUE TITLE
en.ini of beta branch not up-to-date

### ISSUE THREAD

**Issue by aseprite-girl** [aseprite/aseprite#3332]
Hi

The en.ini of beta branch is not up-to-date with the recent auto_show_selection_edges and auto_show_selection_edges_tooltip changes of the main branch.

thx

**Comment by Gasparoken** [comment]
Hi! The `en.ini `will be updated automatically when beta and main branch are merged. So, you can continue with the beta version. Thank you!

**Comment by aseprite-girl** [comment]
I'm not so familiar with github.
But does this mean when 1.3 will be officially released (no more beta) that the 1.2 and 1.3 branches merge into one?
Or is it something else you mean?

**Comment by dacap** [comment]
That's right @aseprite-girl, in practice, the content of the `beta` branch will become the `main` branch (as we merge `main -> beta` periodically, when we reach the point where the `beta` must be `main`, then the final `beta -> main` merge is just pointing `main=beta`).
