### ISSUE TITLE
Build errors due to C++ standard not being set to 17

### ISSUE THREAD

**Issue by KiviTK** [aseprite/aseprite#3333]
Building the project (tried with multiple build systems, see below) the C++ standard version does not appear to be correctly set.
I am using Visual Studio 17 2022 Community edition.
The build process produces the following and many similar errors:

```
'string_view': is not a member of 'std'
...
language feature 'nested-namespce-definition' required compiler flag '/std:c++17'
...
```

If I use the Visual Studio generator of CMake and check the aseprite project's settings the language standard is set to C++14 not 17.
The same errors occur with Ninja and NMake as well.
As a sanity check I looked at the CMakeLists.txt which sets the standard to 17 indeed. I suspect maybe some target compile flags override it later?

### Aseprite and System version

* Aseprite version: v1.X-dev (pulled from the repository before opening the issue)
* System: Windows 10, VS 2022 community, `cl` version: 19.32

**Comment by dacap** [comment]
Hi @KiviTK, what version of CMake are you using? this is strange because we're setting `set(CMAKE_CXX_STANDARD 17)` in CMakeLists.txt which should configure the right flags. What is the full output of cmake and ninja in the console?

**Comment by KiviTK** [comment]
Accidentally closed the issue, reopening.

**Comment by dacap** [comment]
It looks really strange, like a cmake bug checking `has_std_17_flag` 🤔  we'll leave this open but I'm not sure if this should be reported to cmake, maybe in the full log of cmake (`build-dir/CMakeFiles/CMakeOutput.log`) you might find the `Detecting CXX [-std=c++1z] compiler features compiled with the following output:` line and check what it says.

**Comment by aseprite-girl** [comment]
I just tried compile 1.3 beta 14 with visual studio 2022 community and I see my C++ is set to ISO C++14 Standard (/std:c++14) (I didn't change anything).
I don't have this problem but I do have some include file errors.

Did you update all your software including visual studio? There are updates all the time.
