### ISSUE TITLE
Visual Studio solution

### ISSUE THREAD

**Issue by aseprite-girl** [aseprite/aseprite#3336]
Hi

I know how to compile aseprite on windows but I was wondering: is there a way to make a visual studio solution or how can we do this ourselves? I saw other open source projects have a MAKE file that can generate a visual studio solution but I think it doesn't exist here.

So the goal is to have a visual studio solution that can compile everything with 1 click of a button. (but using pre-compiled Skia)

**Comment by dacap** [comment]
Hi @aseprite-girl, actually that is possible when calling cmake. Instead of using `cmake -G Ninja …` you can use `cmake -G "Visual Studio 17 2022" …`, some extra info [in the cmake docs](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html).

**Comment by aseprite-girl** [comment]
Thx! I'm trying.

- What exactly do the ".." mean at the end of the cmake command?

- Is  it correct I need to use  "Visual Studio 17 2022" -A Win32 when I use 
Skia-Windows-Release-x86.zip 
and "Visual Studio 17 2022" -A x64 when I use
Skia-Windows-Release-x64.zip

**Comment by aseprite-girl** [comment]
I think you should add this to compile docs because this issue is the same kind of question: https://github.com/aseprite/aseprite/issues/3329
