### ISSUE TITLE
Ninja compilation error on Windows

### ISSUE THREAD

**Issue by Dunxter** [aseprite/aseprite#3345]
Hi, I've been trying to compile Aseprite-v1.2.34.1 on my Win10 (64bit) machine, but it's failing every time when running `ninja aseprite`: `ninja: build stopped: subcommand failed.` 

[Here's the error](https://gist.github.com/Dunxter/73d9a19370ce63a918c477b80d38e207).

I've tried using an older version of Skia (m81) but I get a [diferent error. ](https://gist.github.com/Dunxter/dd26d864a90aced373192c6c1f4561d6)

- Skia-m96
- cmake-3.23.2-windows-x86_64
- Ninja v1.11.0
- Visual Studio Community 2019 / Desktop development with C++ item + Windows 10.0.18362.0 SDK

Thanks!

**Comment by dacap** [comment]
Hi @Dunxter, it looks like a bug in our gen.exe utility, it will not support paths with unicode characters (as the command is being executed from this path: `"C:\Users\Gerard\Desktop\Herramientas T├®cnicas\aseprite\build\src\app"`).

At the moment I would highly recommend you to move your build folder to something like `C:\builds\aseprite` (something without Unicode char and whitespaces in the path). I'll create a new issue related to this problem.

**Comment by Dunxter** [comment]
Thanks, that was it!
