### ISSUE TITLE
Converting RGBA to indexed should not change colors when less than 255 colors

### ISSUE THREAD

**Issue by jestarray** [aseprite/aseprite#3352]
Related: https://community.aseprite.org/t/rgb-to-indexed-mode-changes-colors/5293

Converting a sprite from RGBA to indexed color mode changes the colors of some areas despite being under the color limit of 255(for me I was using ~40 colors). It should behave more like `pngquant` where if its under 255, it won't change any of the colors. I couldn't find an issue filed for this, if so please link and close.

### Aseprite and System version

* Aseprite version: v1.13 beta 14
* System: Arch Linux

**Comment by jestarray** [comment]
Nevermind, I seem to be running an older version of aseprite, if I update it then it works.

**Comment by jestarray** [comment]
Alright so I updated to beta v1.13 beta 14 and this issue still crops up:

https://user-images.githubusercontent.com/34615798/171678500-59814879-e448-47a7-b7e9-2731ff4712d0.mp4

Here is the file:
![ltest](https://user-images.githubusercontent.com/34615798/171679192-6954d9b0-fbf9-45af-a0be-e31d2bb0717b.png)

Steps to reproduce:
1. `New Palette from Sprite -> Replace current palette` (on a side note, weirdly I don't get "Advanced Options"
2. `Sprite -> Color Mode -> Indexed`
3. It changes the colors when it shouldn't since I'm under 255 colors

I think this works in Aseprite stable versions? Since that's what I probably run on windows

**Comment by dacap** [comment]
From the video, it looks like you are running the v1.2 version (main branch). And not the beta branch (where this issue should be fixed):

<img width="501" alt="Screen Shot 2022-06-02 at 13 36 37" src="https://user-images.githubusercontent.com/39654/171680390-72364488-5912-4f21-80e9-aef25d5673c0.png">
