### ISSUE TITLE
Automatically saves files in font folder after using text

### ISSUE THREAD

**Issue by lesleyrs** [aseprite/aseprite#3367]
I almost got a heart attack after not being able to find my aseprite files. Didn't realise they would be saved where my font was from.

Maybe don't change save folder location after selecting which font to use when pressing T?

* Aseprite version: 1.2.34.1
* System: Windows 10

**Comment by dacap** [comment]
Thanks @return2monki. I think there is an issue related to this but wasn't able to find it. It's a good idea, mainly to keep a default folder/location for each file format (sprites, fonts, palettes) 👍
