### ISSUE TITLE
Ninja Asprite Error (I have compiled in the past but I cannot anymore?) Windows

### ISSUE THREAD

**Issue by Delamcode** [aseprite/aseprite#3372]
Describe your bug report or feature request here

Error Log: 
`FAILED: src/app/CMakeFiles/app-lib.dir/ui/color_selector.cpp.obj
C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\cl.exe  /nologo /TP -DCMARK_STATIC_DEFINE -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_NEWS -DENABLE_SAVE -DENABLE_SCRIPTING -DENABLE_UI -DENABLE_UPDATER -DENABLE_WEBP -DENABLE_WEBSOCKET -DFMT_LOCALE -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DIXWEBSOCKET_USE_ZLIB -DLAF_SKIA -DLAF_WINDOWS -DLAF_WITH_REGION -DLIBARCHIVE_STATIC -DLUA_FLOORN2I=1 -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_WIN -DSK_ENABLE_SKSL=1 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_GL=1 -DSK_INTERNAL -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=1 -DTIXML_USE_STL -DUNICODE -DWINVER=0x0A00 -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0A00 -IC:\aseprite\third_party\zlib -IC:\aseprite\build\third_party\zlib -IC:\aseprite\third_party\libpng -IC:\aseprite\build\third_party\libpng -IC:\aseprite\third_party\libwebp\src -IC:\aseprite\third_party\tinyxml -IC:\aseprite\third_party\pixman\pixman -IC:\aseprite\build -IC:\aseprite\third_party\giflib -IC:\aseprite\third_party\jpeg -IC:\aseprite\third_party\curl\include -IC:\aseprite\third_party\simpleini -IC:\aseprite\src\.. -IC:\aseprite\src\observable -IC:\aseprite\build\src\app -IC:\aseprite\laf -IC:\aseprite\build\laf -IC:\aseprite\src -IC:\aseprite\laf\third_party\stringencoders\src -IC:\aseprite\src\doc\.. -IC:\deps\skia -IC:\deps\skia\third_party\externals\freetype\include -IC:\deps\skia\third_party\externals\harfbuzz\src -IC:\aseprite\src\fixmath\.. -IC:\aseprite\third_party\cityhash\src -IC:\aseprite\src\dio\.. -IC:\aseprite\third_party\fmt\include -IC:\aseprite\src\observable\. -IC:\aseprite\third_party\cmark\src -IC:\aseprite\build\third_party\cmark\src -IC:\aseprite\third_party\giflib\lib -IC:\aseprite\third_party\json11 -IC:\aseprite\third_party\libarchive\libarchive -IC:\aseprite\third_party\tinyexpr -IC:\aseprite\third_party\lua -IC:\aseprite\third_party\IXWebSocket /DWIN32 /D_WINDOWS /GR /EHsc /MT /Zi /O2 /Ob1 /D NDEBUG -MT   -wd4267 -wd4244 -std:c++17 /showIncludes /Fosrc\app\CMakeFiles\app-lib.dir\ui\color_selector.cpp.obj /Fdsrc\app\CMakeFiles\app-lib.dir\app-lib.pdb /FS -c C:\aseprite\src\app\ui\color_selector.cpp
C:\aseprite\src\app\ui\color_selector.cpp(475): error C2660: 'SkRuntimeShaderBuilder::makeShader': function does not take 0 arguments
C:\deps\skia\include/effects/SkRuntimeEffect.h(452): note: see declaration of 'SkRuntimeShaderBuilder::makeShader'
C:\aseprite\src\app\ui\color_selector.cpp(490): error C2660: 'SkRuntimeShaderBuilder::makeShader': function does not take 0 arguments
C:\deps\skia\include/effects/SkRuntimeEffect.h(452): note: see declaration of 'SkRuntimeShaderBuilder::makeShader'
C:\aseprite\src\app\ui\color_selector.cpp(503): error C2660: 'SkRuntimeShaderBuilder::makeShader': function does not take 0 arguments
C:\deps\skia\include/effects/SkRuntimeEffect.h(452): note: see declaration of 'SkRuntimeShaderBuilder::makeShader'
[13/136] Building CXX object src\app\C...\ui\editor\moving_pixels_state.cpp.obj
ninja: build stopped: subcommand failed.`

### Aseprite and System version

Windows 10 21H1
Trying to compile Aseprite 1.3-beta 16

Any ideas? Thanks.

**Comment by Delamcode** [comment]
After more work, I got a much longer run, and I will paste in the failed part. `FAILED: src/app/CMakeFiles/app-lib.dir/ui/color_selector.cpp.obj
C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\cl.exe  /nologo /TP -DCMARK_STATIC_DEFINE -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_NEWS -DENABLE_SAVE -DENABLE_SCRIPTING -DENABLE_UI -DENABLE_UPDATER -DENABLE_WEBP -DENABLE_WEBSOCKET -DFMT_LOCALE -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DIXWEBSOCKET_USE_ZLIB -DLAF_SKIA -DLAF_WINDOWS -DLAF_WITH_REGION -DLIBARCHIVE_STATIC -DLUA_FLOORN2I=1 -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_WIN -DSK_ENABLE_SKSL=1 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_GL=1 -DSK_INTERNAL -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=1 -DTIXML_USE_STL -DUNICODE -DWINVER=0x0A00 -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0A00 -IC:\aseprite\third_party\zlib -IC:\aseprite\build\third_party\zlib -IC:\aseprite\third_party\libpng -IC:\aseprite\build\third_party\libpng -IC:\aseprite\third_party\libwebp\src -IC:\aseprite\third_party\tinyxml -IC:\aseprite\third_party\pixman\pixman -IC:\aseprite\build -IC:\aseprite\third_party\giflib -IC:\aseprite\third_party\jpeg -IC:\aseprite\third_party\curl\include -IC:\aseprite\third_party\simpleini -IC:\aseprite\src\.. -IC:\aseprite\src\observable -IC:\aseprite\build\src\app -IC:\aseprite\laf -IC:\aseprite\build\laf -IC:\aseprite\src -IC:\aseprite\laf\third_party\stringencoders\src -IC:\aseprite\src\doc\.. -IC:\deps\skia -IC:\deps\skia\third_party\externals\freetype\include -IC:\deps\skia\third_party\externals\harfbuzz\src -IC:\aseprite\src\fixmath\.. -IC:\aseprite\third_party\cityhash\src -IC:\aseprite\src\dio\.. -IC:\aseprite\third_party\fmt\include -IC:\aseprite\src\observable\. -IC:\aseprite\third_party\cmark\src -IC:\aseprite\build\third_party\cmark\src -IC:\aseprite\third_party\giflib\lib -IC:\aseprite\third_party\json11 -IC:\aseprite\third_party\libarchive\libarchive -IC:\aseprite\third_party\tinyexpr -IC:\aseprite\third_party\lua -IC:\aseprite\third_party\IXWebSocket /DWIN32 /D_WINDOWS /GR /EHsc /MT /Zi /O2 /Ob1 /D NDEBUG -MT   -wd4267 -wd4244 -std:c++17 /showIncludes /Fosrc\app\CMakeFiles\app-lib.dir\ui\color_selector.cpp.obj /Fdsrc\app\CMakeFiles\app-lib.dir\app-lib.pdb /FS -c C:\aseprite\src\app\ui\color_selector.cpp
C:\aseprite\src\app\ui\color_selector.cpp(475): error C2660: 'SkRuntimeShaderBuilder::makeShader': function does not take 0 arguments
C:\deps\skia\include/effects/SkRuntimeEffect.h(452): note: see declaration of 'SkRuntimeShaderBuilder::makeShader'
C:\aseprite\src\app\ui\color_selector.cpp(490): error C2660: 'SkRuntimeShaderBuilder::makeShader': function does not take 0 arguments
C:\deps\skia\include/effects/SkRuntimeEffect.h(452): note: see declaration of 'SkRuntimeShaderBuilder::makeShader'
C:\aseprite\src\app\ui\color_selector.cpp(503): error C2660: 'SkRuntimeShaderBuilder::makeShader': function does not take 0 arguments
C:\deps\skia\include/effects/SkRuntimeEffect.h(452): note: see declaration of 'SkRuntimeShaderBuilder::makeShader'
[1422/1567] Building CXX object src\ap...les\app-lib.dir\ui\color_wheel.cpp.objninja: build stopped: subcommand failed.`

**Comment by dacap** [comment]
Hi @Delamcode it looks like you are using the old Skia version, check that we've updated to [skia-m102](https://github.com/aseprite/skia/releases/tag/m102-861e4743af).

**Comment by Delamcode** [comment]
Thanks! That was it!
