### ISSUE TITLE
Error compiling Aseprite 1.2.35 on Xubuntu 22.04 LTS

### ISSUE THREAD

**Issue by Gabbinetto** [aseprite/aseprite#3382]
Describe your bug report or feature request here

So I installed all dependencies and got the source code. I downloaded Skia precompiled files and used the commands listed in INSTALL.md  
So far so good until it gives an error:
```
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/gabriele/aseprite/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/ninja cmTC_13f2d && [1/2] Building CXX object CMakeFiles/cmTC_13f2d.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_13f2d
    FAILED: cmTC_13f2d 
    : && /usr/bin/clang++ -stdlib=libc++ -stdlib=libc++ CMakeFiles/cmTC_13f2d.dir/testCXXCompiler.cxx.o -o cmTC_13f2d   && :
    /usr/bin/ld: impossibile trovare -lc++: File o directory non esistente
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:32 (project)
```
Also here's the [CMakeError.log](https://pastebin.com/yVRyuvpE)
I'm fairly new to Linux so I don't know what to do or what this all means.

### Aseprite and System version

* Aseprite version: 1.2.35, commit-hash
* System: Linux, Xubuntu 22.04 LTS

**Comment by dacap** [comment]
It looks like this issue continued here: https://community.aseprite.org/t/cant-compile-aseprite-on-xubuntu-22-04-lts-cmake-error/14728/2

Compiling with clang requires `libc++-10-dev` and `libc++abi-10-dev` packages.

**Comment by Dan-Gamin** [comment]
> It looks like this issue continued here: https://community.aseprite.org/t/cant-compile-aseprite-on-xubuntu-22-04-lts-cmake-error/14728/2
> 
> Compiling with clang requires `libc++-10-dev` and `libc++abi-10-dev` packages.

Thank you! Why isnt this mentioned in `INSTALL.md`?

**Comment by dacap** [comment]
Actually the `libc++-10-dev` dependency is already there, but `libc++abi-10-dev` is missing because the clang dependency on Linux is recent (https://github.com/aseprite/aseprite/commit/ff397fe425bb67b0d01989247f8b27f7bfcf6b4e).

Just added the dependency https://github.com/aseprite/aseprite/commit/59c6c06fa0fe222d1c74654b313f1d20701742ab but not sure how the packages are named on other like Fedora or Arch.
