### ISSUE TITLE
Uninstalling (or updating) an extensions that has subdirectories results in an error

### ISSUE THREAD

**Issue by thkwznk** [aseprite/aseprite#3385]
Uninstalling (or updating, I'm guessing it's an uninstall+install combo action) an extension that has subdirectories in its directory results in an error shown below.

![image](https://user-images.githubusercontent.com/10217876/174834148-3e4249d7-d4c7-416d-99cc-6c83a9a498ca.png)

It leaves the extension directory with empty subdirectories, there are zero files left.

### Aseprite and System version

* Aseprite version: 1.2.35-x64
* System: Windows 11

**Comment by Gasparoken** [comment]
To stay on the same page: I guess the correct behavior is:
- Delete the original content of the extension
- Do not delete the files inside custom folders
- Unstalling will be successful, even with custom folders.
- Perhaps add an Alert "Warning: Custom folders were found which were not deleted."

@dacap correct me or add a comment if I'm wrong.

**Comment by dacap** [comment]
There shouldn't be any new alert. It's only a thing of deleting subdirectories after deleting all files listed in __info.json (when the files are being deleted, we can create a list of subdirectories, and then delete them).

**Comment by dacap** [comment]
> I was able to reproduce it a couple of times as you described (adding extra subdirectory inside of the extension folder). But other attempts, the directories are removed successfully (even with the extra subdirectory added). Anyway, if "__info.json" matches the subdirectory structure of the extension, all is well.

In the past I think I was able to reproduce the problem without adding new files/subdirs manually after the installation. Now it looks like I cannot reproduce it, the only way to reproduce it is just adding new files/subdirs manually. In case someone has a test package to reproduce this with Install/Update without touching the installed folder manually, it would be great to attach it to a post here.

**Comment by thkwznk** [comment]
I just tried with extensions that produced this issue for me but all of them work correctly now in v1.2.39 and v1.3-beta20.

**Comment by Gasparoken** [comment]
I share the link to download the extension that I was testing to reproduce this error: https://community.aseprite.org/t/extension-animation-suite/13322 (nice extension @thkwznk 😄).
I was able to reproduce it by adding a new external folder within the extension's directory structure.

**Comment by Gasparoken** [comment]
@dacap something is to be fixed here?

As I said in [the first reply](https://github.com/aseprite/aseprite/issues/3385#issuecomment-1163390667):

 > Anyway, if "__info.json" matches the subdirectory structure of the extension, all is well.

But I found that if there is a new external folder present, the deletion of the directories will not complete (leaving empty folders as I said [here](https://github.com/aseprite/aseprite/issues/3385#issuecomment-1163390667)). I think [this PR](https://github.com/aseprite/aseprite/pull/3427) solve this case as much as possible (leaving external folders intact).

**Comment by dacap** [comment]
I was able to reproduce it creating new empty dirs. And the PR fixes the error message, I think that is enough.
