### ISSUE TITLE
Main toolbar steals focus from sub menus

### ISSUE THREAD

**Issue by stickynoteme** [aseprite/aseprite#3386]
If a sub menu like the scripts menu [likely the only one that can] gets big enough to expand over the top of the toolbar you can not click on the item that overlaps the toolbar. 

Trying to explain visually: You see the item in the screenshot that is highlighted? I click it to run it, because if I click on it the tool bar steals focus and the script is never clicked. 

![2022-06-19_183203](https://user-images.githubusercontent.com/43216581/174921755-70fc4caa-448d-4c64-9ff4-b2a1253bacb6.png)

**Comment by martincapello** [comment]
Hey thank you for reporting this! It would be great to have some additional details:
Which version of Aseprite you were/are using when this happened/happens?
OS looks like Windows, right? Which version?

**Comment by Gasparoken** [comment]
It's also reproducible on MacOS on 1.2.35 and 1.3beta16.

**Comment by martincapello** [comment]
Thank you both!
