### ISSUE TITLE
ninja error: FindFirstExA

### ISSUE THREAD

**Issue by Andre-pwn** [aseprite/aseprite#3390]
ninja aseprite
...
Nota: file incluso    C:\aseprite\Aseprite-v1.3-beta16-Source\src\ui/style.h
Nota: file incluso   C:\aseprite\Aseprite-v1.3-beta16-Source\build\src\app\theme.xml.h
Nota: file incluso   C:\aseprite\Aseprite-v1.3-beta16-Source\src\doc/keyframes.h
Nota: file incluso   C:\aseprite\Aseprite-v1.3-beta16-Source\third_party\fmt\include\fmt\core.h
Nota: file incluso    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\string_view
Nota: file incluso   C:\aseprite\Aseprite-v1.3-beta16-Source\laf\os/app_mode.h
Nota: file incluso   C:\aseprite\Aseprite-v1.3-beta16-Source\laf\os/capabilities.h
Nota: file incluso   C:\aseprite\Aseprite-v1.3-beta16-Source\laf\os/window_spec.h
Nota: file incluso   C:\aseprite\Aseprite-v1.3-beta16-Source\src\ui/slider.h
ninja: build stopped: subcommand failed.

here it try to execute again _ninja aseptire_ command but:
ninja: error: FindFirstFileExA(//Program Files (x86)/Windows Kits/10/include/10.0.19041.0/um): Impossibile trovare il percorso di rete

### Latest Aseprite Build for Windows x64

* System: Windows 10

**Comment by dacap** [comment]
Hi @AndreaCarosi-7, just in case, if Visual Studio was updated, you will need to create a new "build" folder and run the cmake command again. Before that you could check if "Program Files (x86)/Windows Kits/10/include/10.0.19041.0" folder exists, and check if that folder is named inside the CMakeCache.txt file in the build folder and update it according to the existent folder.
