### ISSUE TITLE
Bug using Moving tool, Flatten, and then undoing

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#3416]
There is a strange bug where moving a transparent layer, then flattening all layers (Layer > Flatten), and then undoing will undone the flattening+layer movement together in some strange way (or generate some extra layer movement).

Probably related to the issue reported in ticket 3710: https://igarastudio.zendesk.com/agent/tickets/3710

**Comment by Gasparoken** [comment]
I found some steps to reproduce something is related to this (Aseprite 1.2.35 and 1.3beta6 - MacOS):
- Select all (Alt+A)
- Select all cels in the timeline
- Move the image
- Flatten layer
- Undo

This particular behavior does not occur in Aseprite 1.2.34.1

https://user-images.githubusercontent.com/32165475/177899463-0c123fd7-8c84-4682-a730-992adfb4d26c.mov
