### ISSUE TITLE
Unable to compile Aseprite; Possible clang/libcxx error

### ISSUE THREAD

**Issue by dani31c** [aseprite/aseprite#3418]
Trying to install aseprite 1.2.35, fails with this; (full console log)

danigaming@debian:~/Aseprite v.1.2.35/build$ export CC=clang
export CXX=clang++
cmake \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
  -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
  -DLAF_BACKEND=skia \
  -DSKIA_DIR=$HOME/deps/skia \
  -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
  -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
  -G Ninja \
  ..
ninja aseprite
CMake Deprecation Warning at CMakeLists.txt:17 (cmake_policy):
  The OLD behavior for policy CMP0046 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- The CXX compiler identification is Clang 11.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ - broken
CMake Error at /usr/share/cmake-3.18/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/danigaming/Aseprite v.1.2.35/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/ninja cmTC_11278 && [1/2] Building CXX object CMakeFiles/cmTC_11278.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_11278
    FAILED: cmTC_11278 
    : && /usr/bin/clang++ -stdlib=libc++ -stdlib=libc++ CMakeFiles/cmTC_11278.dir/testCXXCompiler.cxx.o -o cmTC_11278   && :
    /usr/bin/ld: no se puede encontrar -lc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:32 (project)

-- Configuring incomplete, errors occurred!
See also "/home/danigaming/Aseprite v.1.2.35/build/CMakeFiles/CMakeOutput.log".
See also "/home/danigaming/Aseprite v.1.2.35/build/CMakeFiles/CMakeError.log".
ninja: error: loading 'build.ninja': No such file or directory
danigaming@debian:~/Aseprite v.1.2.35/build$ 

### Aseprite and System version
Aseprite1.2.35
Debian 11.3

**Comment by dani31c** [comment]
If you wonder, I installed all libs (i think), and installed prebuilt Skia.

**Comment by dani31c** [comment]
nevermind solved it

**Comment by ZZaccount1** [comment]
> nevermind solved it

I'm sorry, but how? I have the exact same issue.

**Comment by FreshMedlar** [comment]
How did you fixed it ?
