### ISSUE TITLE
Add slice tool toggle to transform content along with slice

### ISSUE THREAD

**Issue by rylydou** [aseprite/aseprite#3419]
Some times when I'm using slices I want to organize and move around the slices. It would be nice if the slice tool had a toggle to transform the currently selected layer's contents when the slice is being moved or scaled.

### Aseprite and System version

* Aseprite version: v1.3-beta16-x64, Steam beta
* System: Linux, 5.18.9, Fedora 36

**Comment by dacap** [comment]
It's a planned feature, with the possibility to transform 9-slices regions too. Related to #721

**Comment by dacap** [comment]
@martincapello I saw that you self-assigned you this issue, please share a mockup of how you was thinking to implement this feature at the UI level when you are back for iteration 10 (and this must go to the beta version).

**Comment by martincapello** [comment]
I was thinking in adding a new checkbox as:
![Image](https://github.com/aseprite/aseprite/assets/5520828/3f8f86d5-1a9c-4a67-895d-b9b4692b9901)


When it is not checked, the slice works as it currently does:
![Image](https://github.com/aseprite/aseprite/assets/5520828/7983fee5-c6a9-4232-ae31-d9f9a14a96e6)

If checked, the slice content is resized along the slice:
![Image](https://github.com/aseprite/aseprite/assets/5520828/477c8e8f-03d6-4e56-b649-80304b659c9d)

For 9-slices the idea is the same, each of the 9 parts should resize its content depending on the size of each part.

**Comment by dacap** [comment]
It looks good :+1:
