### ISSUE TITLE
Multi-layer selection transformation support

### ISSUE THREAD

**Issue by mount2010** [aseprite/aseprite#3422]
## Describe your bug report or feature request here

This is a feature request for better support for transforming selections (marquees) over multiple layers.
To demonstrate, I have a project with pixels on three layers. I would like to select a part of it, and move this part to another spot in the canvas, over all three layers.

![image](https://user-images.githubusercontent.com/13136505/178781067-7af0b24c-4f45-4d5a-bb41-a56c6628c23b.png)

I tried:
1. selecting the area with the pixels which I wanted to move with the Marquee tool
2. selecting the layers which I wanted to be affected, both by dragging across the cels  I wanted to select (I read [this](https://community.aseprite.org/t/how-to-select-from-more-layers/160) and #1172) and shift-clicking the cels and layers.
3. dragging the selection to move the pixels.
4. I also tried putting the layers in a group and selecting the group, which did not have any effect when attempting to drag the pixels.

Instead of doing this, Aseprite only moved the pixels on the last cel selected. I think better support for transforming like this would be useful when working on projects that use multiple layers.

![image](https://user-images.githubusercontent.com/13136505/178781909-fb5bf539-b1db-4ab0-9ea0-6b6ba40ef40a.png)

### Aseprite and System version

* Aseprite version: v1.3-beta16-x64 Steam
* System: Linux Ubuntu 18.04

**Comment by Gasparoken** [comment]
Thanks for this report @mount2010. Multi cel/layer movement is possible. The steps you did are fine, you need to do one extra step: press 'esc' or click on the unselected area to cancel the selection and drop the image, this action will move all the selected images to the new position.
At the moment, it is a known issue and we need to improve this feature, mainly the real-time preview of the movement (assignment 1 of https://github.com/aseprite/aseprite/issues/2144).

**Comment by mount2010** [comment]
Thanks for the information @Gasparoken! I gave your solution a try and it works. I agree that having the movement be instant will make this more intuitive to understand. I hope you have good luck fixing this!
