### ISSUE TITLE
Gif opening causes color reindexing when duplicate colors in color table

### ISSUE THREAD

**Issue by domgetter** [aseprite/aseprite#3426]
When Aseprite opens a gif which has a single global color table, it will re-index pixels in some of the frames when they share RGB values with other indices in the color table.

![black_test_aseprite](https://user-images.githubusercontent.com/971452/179128231-3d3ad17e-7304-48fe-adf1-ee049dd034fe.gif)

In this gif, the palette is 256 copies of black, but the 2 frames are indexed to color 240 in the table.  When Aseprite opens it, frame 1 is all indexed as 240, but in frame 2, all the pixels are re-indexed to 1 since it's also black.

Expected/preferred behavior: When Aseprite opens a gif with only a global color table, the colors are copied from the color table to the current palette, and the indices across all the frames are left alone and copied in as-is.

### Aseprite and System version

* Aseprite version: v1.2.34.1-x64, installer
* System: Windows 10 Home

**Comment by domgetter** [comment]
I understand things are more complicated when the gif has local color tables, and that Aseprite may from time to time be forced to convert everything to true color, but this issue is regarding a simpler case where the gif is almost just a list of indexed BMPs.

**Comment by Gasparoken** [comment]
Thanks @domgetter for this report. I was able to reproduce it.
