### ISSUE TITLE
ninja aseprite error: undefined reference to `std::__throw_bad_function_call()'

### ISSUE THREAD

**Issue by OnePieceJoker** [aseprite/aseprite#3437]
Describe your bug report or feature request here

**When compiling the source code with ninja aseprite, it prompts an error**
```shell
> $ ninja aseprite
```
## error log 

```text
GrAATriangulator.cpp:(.text._ZNSt10_HashtableIPN14GrTriangulator6VertexESt4pairIKS2_P8SSVertexESaIS7_ENSt8__detail10_Select1stESt8equal_toIS2_ESt4hashIS2_ENS9_18_Mod_range_hashingENS9_20_Default_ranged_hashENS9_20_Prime_rehash_policyENS9_17_Hashtable_traitsILb0ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNS9_10_Hash_nodeIS7_Lb0EEEm[_ZNSt10_HashtableIPN14GrTriangulator6VertexESt4pairIKS2_P8SSVertexESaIS7_ENSt8__detail10_Select1stESt8equal_toIS2_ESt4hashIS2_ENS9_18_Mod_range_hashingENS9_20_Default_ranged_hashENS9_20_Prime_rehash_policyENS9_17_Hashtable_traitsILb0ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNS9_10_Hash_nodeIS7_Lb0EEEm]+0x2a): undefined reference to `std::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned long, unsigned long, unsigned long) const'
/usr/bin/ld: /home/whoami/deps/skia/out/Release-x64/libskia.a(gpu.GrGradientBitmapCache.o): in function `GrGradientBitmapCache::fillGradient(SkRGBA4f<(SkAlphaType)2> const*, float const*, int, SkColorType, SkBitmap*)':
GrGradientBitmapCache.cpp:(.text._ZN21GrGradientBitmapCache12fillGradientEPK8SkRGBA4fIL11SkAlphaType2EEPKfi11SkColorTypeP8SkBitmap+0x21c): 

undefined reference to `std::__throw_bad_function_call()'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

### Aseprite and System version

* Aseprite version: v1.2.37 
* skia aseprite-m102
* System: Manjaro Linux x86_64

**Comment by OnePieceJoker** [comment]
I temporarily rolled back the version to v1.2.35

**Comment by beeryt** [comment]
When rolling back, don't forget to update git submodules. I bashed my head for too long on that one...

**Comment by OnePieceJoker** [comment]
> When rolling back, don't forget to update git submodules. I bashed my head for too long on that one...

Thank you for reminding me. I have returned the version smoothly.

**Comment by Xtendera** [comment]
Having same issue with v1.2.39 and main.

**Comment by Xtendera** [comment]
@dacap sorry for pinging but do you know anything abt this? I have tried EVERYTHING to try to get it to work but cant :(. Please, if you have a solution.

**Comment by dacap** [comment]
@Xtendera sorry but I have no idea, if you are using the pre-compiled Skia version, I highly recommend you to compile Skia yourself to avoid linking errors.

**Comment by Xtendera** [comment]
No problem! Great work on aseprite btw, it is amazing (I was able to build on windows so  was able to use it. I have a knack it is related to skia building with g++ instead of clang so i am testing my theory.

**Comment by Xtendera** [comment]
Well... didnt work. I got it to build by using gcc/g++ to build aseprite but that has a performance penality.

**Comment by Xtendera** [comment]
THIS ISSUE IS DRIVING ME CRAZY. sry for caps

**Comment by Xtendera** [comment]
Ok, I figured it out. You are most probably compiling Aseprite with libc++, but you need to compile skia with that too. So, run this command instead of the command written on the Skia README:

`gn gen out/Release-x64 --args='is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false cc="clang-10" cxx="clang++-10" extra_cflags_cc=["-stdlib=libc++"] extra_ldflags=["-stdlib=libc++"]' `
(It just compiles with clang and includes libc++)

**Comment by OnePieceJoker** [comment]
> Ok, I figured it out. You are most probably compiling Aseprite with libc++, but you need to compile skia with that too. So, run this command instead of the command written on the Skia README:
> 
> `gn gen out/Release-x64 --args='is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false cc="clang-10" cxx="clang++-10" extra_cflags_cc=["-stdlib=libc++"] extra_ldflags=["-stdlib=libc++"]' ` (It just compiles with clang and includes libc++)

Thank you. This also solved my problem. I successfully compiled version 1.2.39.

The only difference is that I replaced cc and cxx with my local version

**Comment by eazteregg** [comment]
Oh man, this solved the problem I have been running into for a few days!

**Comment by Ivan228-s** [comment]
> Ok, I figured it out. You are most probably compiling Aseprite with libc++, but you need to compile skia with that too. So, run this command instead of the command written on the Skia README:
> 
> `gn gen out/Release-x64 --args='is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false cc="clang-10" cxx="clang++-10" extra_cflags_cc=["-stdlib=libc++"] extra_ldflags=["-stdlib=libc++"]' ` (It just compiles with clang and includes libc++)

THANKS!!!
