### ISSUE TITLE
Script console blank/not rendering

### ISSUE THREAD

**Issue by pizzabladegames** [aseprite/aseprite#3442]
The output of a lua script is not visible in the console window. This is also the case when installing an extension.

Repro steps:

1. Copy a script into the scripts folder that prints or throws an exception
1. Rescan the scripts folder
1. Run the script

Observed results:
1. (A) Console window is blank (black). This is also the case when the console output is hosted in the debugger window.
3. (B) Console window appears clear (when UI with multiple windows disabled on beta version), contents "smears" when dragging the window

Expected results:
Console window renders visible text.

Notes:
* Aseprite on Mac OS does not have this issue. The bug makes writing non-trivial scripts impossible because errors or other logging information are invisible.
* The stack trace and local variables areas to render correctly, but console does not.

### Aseprite and System version

* Aseprite version: V1.3-beta19-x64 and V1.2.38-x64, installer and portable
* System: Windows, 11 Home 21H2 OS Build: 22000.832

![Screenshot 2022-07-27 203616](https://user-images.githubusercontent.com/102328941/181598183-6e2a4545-a3bf-4ded-9835-76d4952070e0.png)

**Comment by Gasparoken** [comment]
Thanks @pizzabladegames for this report. I was able to reproduce it. Fix on PR https://github.com/aseprite/aseprite/pull/3441.

**Comment by pizzabladegames** [comment]
Thanks @Gasparoken for the quick response!

Is the only way to get this fix before the 1.2.39 release to build from source?

**Comment by Gasparoken** [comment]
I guess next week we will implement this fix. Anyway, you can write to us at support@aseprite.org and we will give you an alternative (please use your email address linked to the Humble Bundle purchase).
