### ISSUE TITLE
Corrupted "Licenses" Tab

### ISSUE THREAD

**Issue by ElderyGlek** [aseprite/aseprite#3443]
Repro steps:
1. Open "Open Source Projects" tab in "About".

### Aseprite and System version

* Aseprite version: v1.3-beta18-dev
* System: Windows, 10 Pro 21H2, OS Build: 19044.1766
![Corrupted "Licenses" Tab](https://user-images.githubusercontent.com/69088106/181622069-4b3a51f8-1d73-4bbd-8ca0-89f2f32e2ae4.png)

**Comment by Gasparoken** [comment]
Thanks @ElderyGlek for this report. I was able to reproduce it and It'll be fixed next week via PR https://github.com/aseprite/aseprite/pull/3441. Related: https://github.com/aseprite/aseprite/issues/3442
