### ISSUE TITLE
RotSprite Transparency Bug

### ISSUE THREAD

**Issue by ElderyGlek** [aseprite/aseprite#3444]
Repro steps:
1. Create a transparent area.
2. Rotate part of this area.

### Aseprite and System version

* Aseprite version: v1.3-beta18-dev
* System: Windows, 10 Pro 21H2, OS Build: 19044.1766
![RotSprite Transparency Bug 1](https://user-images.githubusercontent.com/69088106/181642163-7b9db725-f4ca-4e00-b8d0-85e1c57b2002.png)
![RotSprite Transparency Bug 2](https://user-images.githubusercontent.com/69088106/181642165-8e145557-4f41-4bf0-8d5d-d1d4252a67fd.png)
![RotSprite Transparency Bug 3](https://user-images.githubusercontent.com/69088106/181642166-e77548d3-8787-4567-9c9b-23c658c65ed3.png)
![RotSprite Transparency Bug 4](https://user-images.githubusercontent.com/69088106/181642169-bc8de036-e437-42c9-a7f6-8f944ae52ef0.png)

**Comment by Gasparoken** [comment]
Thanks @ElderyGlek for this report. I was able to reproduce it. This happens in stable version too.
