### ISSUE TITLE
.ase thumbnails for macOS

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [aseprite/aseprite#3447]
Thumbnail preview seems to have been implemented on Windows and Linux in some capacity at https://www.aseprite.org/thumbnails/ and https://github.com/sebadorn/aseprite-thumbnailer respectively, but not for macOS. Without support for this, it can be really difficult to work on large projects.

**Comment by martincapello** [comment]
Hey there, this is actually part of a long standing feature that we want to achieve at some point. See https://github.com/aseprite/aseprite/issues/834
So closing this as duplicate of #834
