### ISSUE TITLE
Aseprite through Steam on MacOS Ventura Beta cannot be launched

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3450]
Some users reported that they are unable to launch Aseprite through Steam due to an error "Aseprite is corrupted and cannot be opened...

~~At the moment, a workaround is to downgrade MacOS OS version.~~ (see EDIT)

Reported: https://igarastudio.zendesk.com/agent/tickets/3760, https://igarastudio.zendesk.com/agent/tickets/3784, https://igarastudio.zendesk.com/agent/tickets/3805.

EDIT: 
Seems that the following steps worked for several users:
https://github.com/aseprite/aseprite/issues/3450#issuecomment-1292368256

**Comment by dacap** [comment]
Just in case the next release will include the latest Steam library from an updated Steamworks SDK v1.55 (anyway I'm not sure if this will solve this problem).

**Comment by Gasparoken** [comment]
It looks like an app trust issue.
Here something to test: https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/

**Comment by Gasparoken** [comment]
Internal:
New reported tickets:
https://igarastudio.zendesk.com/agent/tickets/3839
https://igarastudio.zendesk.com/agent/tickets/4104
https://igarastudio.zendesk.com/agent/tickets/4107

**Comment by Gasparoken** [comment]
Could anyone confirm if these steps fix this issue on MacOS Ventura?
- Try to `Launch` Aseprite from Steam
- The ‘Aseprite.app’ damage dialog appears, click `Cancel`
- Go to `System Preferences > Privacy & Security`
- Search for section `“Aseprite” was blocked from use…`, press `Open Anyway` button.
- Press `Open` in the dialog `macOS cannot verify the developer….`

**Comment by dacap** [comment]
It'd be nice to ask to the users with this issue if this option "Allow applications downloaded from App Store and identified developers" is checked:

<img width="783" alt="Screenshot 2022-10-26 at 15 07 00" src="https://user-images.githubusercontent.com/39654/198103191-cb0c649f-829d-40d4-8972-68ad363f1000.png">

**Comment by dypo** [comment]
> Could anyone confirm if these steps fix this issue on MacOS Ventura?
> 
> * Go to `System Preferences > Privacy & Security > Security`
> * Check `App Store and identified developers`
> * Try to `Launch` Aseprite from Steam
> * The ‘Aseprite.app’ damage dialog appears, click `Cancel`
> * Go to `System Preferences > Privacy & Security`
> * Search for section `“Aseprite” was blocked from use…`, press `Open Anyway` button.
> * Press `Open` in the dialog `macOS cannot verify the developer….`

Can confirm Aseprite successfully opens after following those steps. :)

**Comment by dacap** [comment]
Taking some notes here:

The Aseprite.app bundle is correctly signed:
```
$ codesign --verify --verbose /Applications/Aseprite.app 
/Applications/Aseprite.app: valid on disk
/Applications/Aseprite.app: satisfies its Designated Requirement
```
So probably this is a bug in macOS Ventura, or a temporal problem, i.e. if the Apple servers cannot check that the .app bundle is signed/notarized correctly. But it could be anything else (e.g. something missing in our side in the Info.plist file that is now required in Ventura, but we're not sure.)

**Comment by aluneed** [comment]
The same issue on Ventura 13.0
MacOS just give a wrong and misleading info
Solved by allowing aseprite.app in Security Settings

Thank @dacap for avoiding me waste more time on apple's fault

**Comment by samvieten** [comment]
Can confirm that the steps by @Gasparoken work.
- On Mac OS Ventura 13.0 
- since Update to Aseprite 1.3
- @dacap App Store and identified developers were already checked

**Comment by dacap** [comment]
Some extra information and work to be done about this issue:

1. macOS Gatekeeper has changed in a way that it checks all notarized apps every time they are launched (not just in the first launch), https://developer.apple.com/videos/play/wwdc2022/10096/?time=289 not sure if this changed/broke something
2. Some extra information here: https://mjtsai.com/blog/2022/08/18/gatekeeper-changes-in-macos-ventura/
3. If this is an issue only on Steam, I suspect that it might be related to the way we're distributing Aseprite on Steam specifically and our release process for Steam will need a change.

The details are tricky but in short: we are distributing on Steam the data/ directory as a platform-independent package (downloaded on all platforms) and the macOS package without the data/, but a symlink (`Aseprite.app/Contents/Resources/data`) is created to that data/ directory. In practice the content of the .app bundle is the same as the one distributed, but maybe now macOS Ventura is checking the existence of the symlink itself.

I'll be re-downloading all the packages of the current version of Aseprite, and re-adjusting the packages for Steam to check if this issue can be easily solved removing the symlink (probably this will lead to downloading two times the data/ directory, but that is a minor problem).

**Comment by dacap** [comment]
I was able to reproduce this problem locally, other problem is the `installscript_osx.vdf` script distributed (which is inside the .app bundle), it creates the symlink and adds the executable mode to `Aseprite.app/Contents/MacOS/aseprite` file. I think this shouldn't be necessary so we might be able to remove it.

**Comment by dacap** [comment]
One command that should fix this issue is removing all attributes from downloaded folder/files/subdirectories with:
```
xattr -cr Aseprite.app 
```
But after executing this, macOS shows:

<img width="336" alt="Screenshot 2022-11-09 at 13 43 28" src="https://user-images.githubusercontent.com/39654/200889557-3419c00c-599e-498f-a996-b661293e50fc.png">

Which is interesting, because it was the same message it appeared when Steam tried to install Aseprite for the first time. So it's probably that Steam is already trying to run `xattr -cr` but macOS is blocking it.

**Comment by dacap** [comment]
We've just published updated packages that should solve this issue, the announcement is here:

* https://community.aseprite.org/t/aseprite-update-for-steam-on-macos-ventura/16229
* https://store.steampowered.com/news/app/431730/view/6052302851596240888
