### ISSUE TITLE
Asesprite Bug Report: Unopenable bmp. Files

### ISSUE THREAD

**Issue by LucianTheGamer** [aseprite/aseprite#3469]
Describe your bug report or feature request here
Only one file I need to modify for a game as a mod but it will not open, other bmp files still work but not the one I was trying to open.
(Prototype Sonic Sprite Sheet for Sonic 3 A.I.R)

#### Aseprite and System version

* Aseprite version: Steam version V1.2.39
* System: Windows 11, Version 2022-7, Ideapad 3 by Lenovo

**Comment by KasumiArai** [comment]
I looked it up because I was curious. Here is one such file Aseprite does not open
[character_knuckles.zip](https://github.com/aseprite/aseprite/files/9286260/character_knuckles.zip)

**Comment by Gasparoken** [comment]
Thanks for this report. At the moment some bmp formats aren't supported. This was found in the past: https://github.com/aseprite/aseprite/issues/3277, and related (bmp missing alpha channel): https://github.com/aseprite/aseprite/issues/1495.

I'm closing this because it's duplicated.
