### ISSUE TITLE
Advanced Mode disables Tilemap tool

### ISSUE THREAD

**Issue by kaiiboraka** [aseprite/aseprite#3478]
Create and select a tilemap layer. Select a tile to paint with and be ready to place it. Enter advanced mode (where the UI hides). The brush will revert from Tile mode to pixel mode, and you can no longer place or interact with tiles properly. The Dropper tool only works on colors instead of tiles. Any drawing will edit tiles' pixels instead of painting with tiles. All you can do is move the tile layer itself. The current Space+Tab shortcut does nothing to fix this either. 

### Aseprite and System version

* Aseprite version: Aseprite v1.3-beta20-x64, Steam beta
* System: 
-- Edition:		Windows 10 Pro
-- Version:		21H1
-- Installed on:	‎6/‎19/‎2021
-- OS build:	19043.1889

**Comment by kaiiboraka** [comment]
Screenshots for reference.
Here I have this purple vine selected as my active tile.
![image](https://user-images.githubusercontent.com/7596816/185722764-33ae275d-0c6f-43ce-b77e-2f00342d48ca.png)

Here I have done nothing except enable Advanced Mode and as you can see, the tile disappears and reverts to my current round pixel brush.
![image](https://user-images.githubusercontent.com/7596816/185722786-96759dad-a025-4856-871c-ac78c855b889.png)

**Comment by martincapello** [comment]
Fixed by https://github.com/aseprite/aseprite/pull/3529
