### ISSUE TITLE
Creating a form of a certain size + pixelperfect

### ISSUE THREAD

**Issue by DULEONOS** [aseprite/aseprite#3480]
Good evening!
My question is: I have set up a 4x4 grid and I need to create a shape, let's say an ellipse, so that 4 pixels fit into each square of the grid. That is, it is like PixelPerfect, only not from 1 pixel, but from 4. How can I do this?
Here is an example of what I want and what I get when using the ellipse tool.
https://imgur.com/a/LNNN6OV - example.

Thx!

**Comment by Gasparoken** [comment]
Thank you @DULEONOS for this report. This was reported in the past https://github.com/aseprite/aseprite/issues/1268. This is still a pending feature. You can give your impression to the original issue to increase its priority.

**Comment by Gasparoken** [comment]
A workaround is:
- Create a new temporal sprite.
- Make the shape you wish with 1x1 pixels size.
- Upscale it 400%.
- Copy this new resized shape to your main sprite.

**Comment by DULEONOS** [comment]
Thank u for this!
