### ISSUE TITLE
error while git-sync-deps

### ISSUE THREAD

**Issue by fily-gif** [aseprite/aseprite#3482]
Describe your bug report or feature request here
Hello, when i do 
```
python3 tools/git-sync-deps
```
it gives me an error
```
  File "/home/fily/deps/skia/tools/git-sync-deps", line 209
    print 'Skipping "%s".' % directory
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```
### Aseprite and System version

* Aseprite version: 1.2.39, compiling
* System: Linux, 22.04, ubuntu

**Comment by dacap** [comment]
It looks like you are using an old version of the skia clone (not the aseprite-m102 branch clone). The line is completely different now (python3 compatible I guess): https://github.com/aseprite/skia/blob/861e4743af6d9bf6077ae6dda7274e5a136ee4e2/tools/git-sync-deps#L223

**Comment by fily-gif** [comment]
> It looks like you are using an old version of the skia clone (not the aseprite-m102 branch clone). The line is completely different now (python3 compatible I guess): https://github.com/aseprite/skia/blob/861e4743af6d9bf6077ae6dda7274e5a136ee4e2/tools/git-sync-deps#L223

after i do all the same things nut with m102 branch, it gives a huge error block [(click)](https://textbin.net/4406pg00bo)

**Comment by fily-gif** [comment]
> > It looks like you are using an old version of the skia clone (not the aseprite-m102 branch clone). The line is completely different now (python3 compatible I guess): https://github.com/aseprite/skia/blob/861e4743af6d9bf6077ae6dda7274e5a136ee4e2/tools/git-sync-deps#L223
> 
> after i do all the same things nut with m102 branch, it gives a huge error block [(click)](https://textbin.net/4406pg00bo)

okay so what happened is that it just crashes my network on a pc and says "who is github.com" :/

**Comment by wetbadger** [comment]
> 

I'm using that branch and I get this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/worryword/deps/skia/tools/git-sync-deps", line 134, in git_checkout_to_directory
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '--quiet', '--no-checkout', 'https://android.googlesource.com/platform/external/libmicrohttpd', '/home/worryword/deps/skia/third_party/externals/microhttpd']' returned non-zero exit status 128.
```

**Comment by fily-gif** [comment]
Same error

**Comment by dacap** [comment]
Just in case, if you have network problems running tools/git-sync-deps, you will need to run it until it doesn't fail (if it's related to network problems). Because it downloads a lot of dependencies for Skia.

**Comment by fily-gif** [comment]
> Just in case, if you have network problems running tools/git-sync-deps, you will need to run it until it doesn't fail (if it's related to network problems). Because it downloads a lot of dependencies for Skia.

It isn't completely network related

**Comment by dacap** [comment]
> It isn't completely network related

Just in case, what part is not related to a network problem? Did you try running the git-sync-deps command again? What is the output? From the log you have shared, it looks like it cannot clone some Git repositories because the network is not accessible. My personal recommendation would be to try running the command as many times as possible until it can clone all repositories (the command doesn't clone repositories that were already cloned, so it can make so progress on each call).

**Comment by wetbadger** [comment]
```
Skipping "../src".
Skipping "bin".
/home/worryword/deps/skia/buildtools @ b138e6ce86ae843c42a1a08f37903207bebcca75
...rd_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
...skia/third_party/externals/brotli @ e61745a6b7add50d380cfd7d3883dd6c62fc2c71
...kia/third_party/externals/dng_sdk @ c8d0c9b1d16bfda56f15165d39e0ffa360a11123
...skia/third_party/externals/angle2 @ 8718783526307a3fbb35d4c1ad4e8101262a0d73
.../third_party/externals/abseil-cpp @ c5a424a2a21005660b182516eb7a079cd8021699
...hird_party/externals/egl-registry @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
.../skia/third_party/externals/emsdk @ fc645b7626ebf86530dbd82fbece74d457e7ae07
...ia/third_party/externals/freetype @ f122349b937d7d2b0f8b72f46f60a082ca6006db
...ia/third_party/externals/harfbuzz @ 8d1b000a3edc90c12267b836b4ef3f81c0e53edc
.../skia/third_party/externals/expat @ a28238bdeebc087071777001245df1876a11f5ee
...third_party/externals/libgifcodec @ fd59fa92a0c86788dcdd84d091e1ce81eda06a77
.../skia/third_party/externals/imgui @ 55d35d8387c15bf0cfd71861df67af8cfbda7456
...kia/third_party/externals/highway @ 424360251cdcfc314cfc528f53c872ecd63af0f0
...ird_party/externals/libjpeg-turbo @ 22f1a22c99e9dde8cd3c72ead333f425c5a7aa77
...skia/third_party/externals/libjxl @ a205468bc5d3a353fb15dae2398a101dff52f2d3
...skia/third_party/externals/jinja2 @ ee69aa00ee8536f61db6a451f3858745cf587de6
...s/skia/third_party/externals/dawn @ 088a600b03679cd20991f145173a573ed9c03480
...ps/skia/third_party/externals/icu @ a0718d4f121727e30b8d52c7a189ebf5ab52421f
...skia/third_party/externals/libpng @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
.../third_party/externals/markupsafe @ 0944e71f4b2cb9a871bcbe353f95e889b64a611a
...kia/third_party/externals/libwebp @ 20ef03ee351d4ff03fc5ff3ec4804a879d1b9d5c
...d_party/externals/opengl-registry @ 14b80ebeab022b2c78f84a573f01028c96075553
...s/skia/third_party/externals/piex @ bb217acdca1cc0c16b704669dd6f91a1b509c406
.../third_party/externals/microhttpd @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
...s/skia/third_party/externals/oboe @ b02a12d1dd821118763debec6b83d00a8a0ee419
...skia/third_party/externals/sfntly @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
...hird_party/externals/vulkan-tools @ fa288188b574d9eee31cd52c5432780b6a46a412
...ird_party/externals/spirv-headers @ 82becc8a8a92e509d3d8d635889da0a3c17d0606
...third_party/externals/spirv-cross @ 6a67891418a3f08be63f92726e049dc788e46f5b
...rd_party/externals/vulkan-headers @ 76f00ef6cbb1886eb1162d1fa39bee8b51e22ee8
...third_party/externals/swiftshader @ 1d450ae99a0f4ade28dd55dac962f8b28d990376
...s/skia/third_party/externals/zlib @ c876c8f87101c5a75f6014b0f832499afeb65b73
...third_party/externals/spirv-tools @ cb96abbf7affd986016f17dd09f9f971138a922b
.../skia/third_party/externals/wuffs @ 600cd96cf47788ee3a74b40a6028b035c9fd6a61
...third_party/externals/vulkan-deps @ 565408992c44e7d969af8c417a0f72730a85c880
Resolving SDK version '3.1.3' to 'sdk-releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit'
Installing SDK 'sdk-releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit'..
Skipped installing node-14.18.2-64bit, already installed.
Skipped installing releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit, already installed.
All SDK components already installed: 'sdk-releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit'.
Resolving SDK version '3.1.3' to 'sdk-releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit'
Setting the following tools as active:
   node-14.18.2-64bit
   releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit

Next steps:
- To conveniently access emsdk tools from the command line,
  consider adding the following directories to your PATH:
    /home/worryword/deps/skia/third_party/externals/emsdk
    /home/worryword/deps/skia/third_party/externals/emsdk/node/14.18.2_64bit/bin
    /home/worryword/deps/skia/third_party/externals/emsdk/upstream/emscripten
- This can be done for the current shell by running:
    source "/home/worryword/deps/skia/third_party/externals/emsdk/emsdk_env.sh"
- Configure emsdk in your shell startup scripts by running:
    echo 'source "/home/worryword/deps/skia/third_party/externals/emsdk/emsdk_env.sh"' >> $HOME/.bash_profile

```

This is my whole output on each attempt.

**Comment by wetbadger** [comment]
But the build still fails.

```
ninja -C out/Release-x64 skia modules
ninja: Entering directory `out/Release-x64'
[1/859] link libexpat.a
FAILED: libexpat.a 
python "/home/worryword/deps/skia/gn/rm.py" "libexpat.a" && ar rcs libexpat.a @libexpat.a.rsp
/bin/sh: 1: python: not found
[8/859] compile ../../third_party/externals/freetype/src/psaux/psaux.c
ninja: build stopped: subcommand failed.

```

**Comment by fily-gif** [comment]
> > It isn't completely network related
> 
> Just in case, what part is not related to a network problem? Did you try running the git-sync-deps command again? What is the output? From the log you have shared, it looks like it cannot clone some Git repositories because the network is not accessible. My personal recommendation would be to try running the command as many times as possible until it can clone all repositories (the command doesn't clone repositories that were already cloned, so it can make so progress on each call).

https://github.com/aseprite/aseprite/issues/3482#issuecomment-1227496694 this one, i have the same error with the network-related errors, i think it might be because python 3.10 is still broken but im not sure

**Comment by wetbadger** [comment]
> > > It isn't completely network related
> > 
> > 
> > Just in case, what part is not related to a network problem? Did you try running the git-sync-deps command again? What is the output? From the log you have shared, it looks like it cannot clone some Git repositories because the network is not accessible. My personal recommendation would be to try running the command as many times as possible until it can clone all repositories (the command doesn't clone repositories that were already cloned, so it can make so progress on each call).
> 
> [#3482 (comment)](https://github.com/aseprite/aseprite/issues/3482#issuecomment-1227496694) this one, i have the same error with the network-related errors, i think it might be because python 3.10 is still broken but im not sure

You're right. Not sure this error was related to first one, but it seems happy with python 3.9.13.

**Comment by fily-gif** [comment]
> > > > It isn't completely network related
> > > 
> > > 
> > > Just in case, what part is not related to a network problem? Did you try running the git-sync-deps command again? What is the output? From the log you have shared, it looks like it cannot clone some Git repositories because the network is not accessible. My personal recommendation would be to try running the command as many times as possible until it can clone all repositories (the command doesn't clone repositories that were already cloned, so it can make so progress on each call).
> > 
> > 
> > [#3482 (comment)](https://github.com/aseprite/aseprite/issues/3482#issuecomment-1227496694) this one, i have the same error with the network-related errors, i think it might be because python 3.10 is still broken but im not sure
> 
> You're right. Not sure this error was related to first one, but it seems happy with python 3.9.13.

gonna install python3.9 and try to run it again (how did they even released python 3.10 when it breaks so many scripts)

**Comment by fily-gif** [comment]
> > > > > It isn't completely network related
> > > > 
> > > > 
> > > > Just in case, what part is not related to a network problem? Did you try running the git-sync-deps command again? What is the output? From the log you have shared, it looks like it cannot clone some Git repositories because the network is not accessible. My personal recommendation would be to try running the command as many times as possible until it can clone all repositories (the command doesn't clone repositories that were already cloned, so it can make so progress on each call).
> > > 
> > > 
> > > [#3482 (comment)](https://github.com/aseprite/aseprite/issues/3482#issuecomment-1227496694) this one, i have the same error with the network-related errors, i think it might be because python 3.10 is still broken but im not sure
> > 
> > 
> > You're right. Not sure this error was related to first one, but it seems happy with python 3.9.13.
> 
> gonna install python3.9 and try to run it again (how did they even released python 3.10 when it breaks so many scripts)

tried python3.9, same error :/

**Comment by dacap** [comment]
@fily-gif could you try running the following command in the terminal:
```
git clone --quiet --no-checkout https://android.googlesource.com/platform/external/libmicrohttpd /home/worryword/deps/skia/third_party/externals/microhttpd
```
Check what is the output, from what I saw it looks that python fails because running this command failed.

**Comment by fily-gif** [comment]
> 

when i tried that command it was working just fine

**Comment by fily-gif** [comment]
okay so i think i know why it fails, the reason is due to my pc being not able to process everything at once :/

i think i will have to run every git script manually.
