### ISSUE TITLE
Copying frames doesn't link them

### ISSUE THREAD

**Issue by thkwznk** [aseprite/aseprite#3483]
Documentation for [Copy Frames](https://www.aseprite.org/docs/copy-frames/) shows (but not describes) copied frames being linked to the original ones.

Is this a bug or an outdated part of documentation?

### Aseprite and System version

* Aseprite version: 1.2.39-x64 and 1.3-beta20-x64
* System: Windows 11

**Comment by martincapello** [comment]
Hey there, I've been looking a bit at this, and it seems that there is actually a bug when copying frames. I managed to copy frames as the docs shows, but not with the step described there, I had to first copy a cel in a continuous layer, undo it, and then copy the frames as the doc says, then I got the result described in the gif. 
So it seems to be a bug in the program and in the docs...

@dacap What do you think?

**Comment by dacap** [comment]
Sorry, but I wasn't able to reproduce this. It works as in the docs but maybe I'm doing something extra:

https://user-images.githubusercontent.com/39654/186179259-4f3d696e-da94-46e4-a282-db6aef2ed744.mp4

**Comment by dacap** [comment]
Just in case, the cels will be linked to the original ones if the layer is marked as continuous, maybe that is something to make a point in the docs.

**Comment by martincapello** [comment]
I made this video, hopefully it shows what I described:

https://user-images.githubusercontent.com/5520828/186200195-ebdc7c72-a30e-4d18-a86d-d5ac4b399cc3.mp4

Look that the first time it copies frames without linking. Then I press undo and copy a cel of the continuous layer, it links the copy. Finally I press undo again and try to copy frames, now it links cels.

**Comment by thkwznk** [comment]
Thanks, now it's clear - if a layer is continuous the copied cels are linked with the original ones. 👍

I'm closing this issue then, as it's not a bug and I'll create a PR for the docs to add a note about it.
