### ISSUE TITLE
Cannot bypass data loss warnings when Exporting a Frame with Layer or Cel opacity as a .jpg.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#3499]
I get this error pane when I try to export a complex Workspace (Cel opacity, layer opacity, multiple frames, etc.) as a .jpg, and it cannot be acknowledged and ignored. 🔻 
![image](https://user-images.githubusercontent.com/11544843/188278136-02130068-d738-494b-814a-0d9f7f66e57b.png)

In this case, the warning ought to appear, but with the option of going ahead and rasterizing the Workspace *as it appears* and then saving that image as a .jpg.

Of course, it is good and useful to tell the user that saving in this lossy, compressed, inarticulate format will compromise heavily the quality of their data, but I also feel that the whole purpose of Export is to be able to save the Workspace in formats *other than* the consistent one defined by Save As.
Therefore, Export (though possibly __not__ Save As) should allow the option to *ignore quality loss warnings* (it usually does, in fact!) and save out the Workspace as it appears, suffering whatever data loss along the way, whenever the user insists upon it, unless it is *strictly not possible* (attempting to save an *animation* as a .jpg, for instance, which I believe already gives the option of saving as a sequence of numbered Frames).

Anyway thank you for considering it! :D 

..using ASEprite v.1.3-b20-x64 on Win10.

**Comment by martincapello** [comment]
Thank you for your suggestion!

**Comment by dacap** [comment]
Just in case, this is related to #1343 (maybe duplicate) and #830. E.g. we should be able to convert an indexed image to RGB just for the export (just like right now we do the resize #3008)

**Comment by martincapello** [comment]
You are right! I'll close this.

**Comment by oceanhahn** [comment]
Not a duplicate of #1343 as that Issue does not address Copy/Pasting. More similar to #3116 but this Issue does not handle the Clipboard. 

> E.g. we should be able to convert an indexed image to RGB just for the export (just like right now we do the resize #3008)

This was what I was thinking as well, only it would be a lot of processing for Copy Merged in large Workspaces with many Frames. In that case, a more robust command solution might be something like:
 > (start) 
 > Delete every other Frame
 > Crop to Selection
 > Convert to RGB mode
 > Flatten
 > Move image to Clipboard
 > Undo to (start)

Conversion between modes can take several seconds per use already in many of my Workspaces for top the number of Layers and Frames involved, as well as, in some cases, resolution. Running through that for every Copy Merged operation for me would get old pretty fast, and I suspect it would for other users, too. 

That said I am not sure how long that solution would take to implement, and the dimensionality of my Workspaces can get a bit (uh) eccentric. 
If I could record command macros (as in Photoshop, for instance), I would just do it myself. ;3

Anyway, thanks again! Looking forward to whatever solution you find! :D

**Comment by oceanhahn** [comment]
Wait hold up. This is not a duplicate.
