### ISSUE TITLE
Dark mode for window decoration on windows

### ISSUE THREAD

**Issue by lampysprites** [aseprite/aseprite#3527]
So it seems windows disables the dark mode support by default, and leaves it to the application to enable. I think it only affects the inactive window border - instead of becoming dark gray in dark mode, it becomes bright white. It is not a disaster but stands out when there's other applications open.

Current behavior in both modes, active/inactive:
![ZUOQh67NTJ](https://user-images.githubusercontent.com/49268426/190867304-53d64093-8485-458b-a530-8b546003f9a9.png)

Desired dark mode:
![EsgYIrJebO](https://user-images.githubusercontent.com/49268426/190867317-2a0ac80f-1d6c-46cf-9304-44a33b564b77.png)

I tried to support that based on the second half of [microsoft's guide](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes)... however, now the exact opposite happens and the window uses dark mode always. It seems that that part of the API went through a series of changes, and it only works since win11 and i can't figure where older docs went (re: [DWMWA_USE_IMMERSIVE_DARK_MODE](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute)). 

Perhaps i could make it switch according to preferences? Although that is not native behavior, it at least will be an option.

[darkmode.patch.zip](https://github.com/aseprite/aseprite/files/9592173/darkmode.patch.zip)

### Aseprite and System version

* Aseprite version: 1.3-beta21 steam; and git
* System: Windows 10

**Comment by dacap** [comment]
We'll support the dark mode on Windows 11 but not on Windows 10.

Some extra discussion here: https://github.com/microsoft/WindowsAppSDK/issues/41
