### ISSUE TITLE
Merge selected cels to the same layer as the right-clicked cel.

### ISSUE THREAD

**Issue by kyrieru** [aseprite/aseprite#3536]
Currently there is no easy way to merge certain layers/cels while retaining others. I think it would be helpful to have the following option when right clicking on a cel,
https://i.gyazo.com/6d407f85ab5b3b37d7b40bead6b6c33b.png

After selecting multiple cels across multiple layers, the option would flatten them all onto the layer that the cel you right clicked is one.

**Comment by Gasparoken** [comment]
Thanks for this report. It would be great to include this feature. This has been reported in the past: https://github.com/aseprite/aseprite/issues/2075. I'll update the priority of this.
