### ISSUE TITLE
Thin transparent line between pixels when exporting to SVG.

### ISSUE THREAD

**Issue by GAZ082** [aseprite/aseprite#3561]
Hi.

When exporting to SVG there is a slim line between pixels.

![image](https://user-images.githubusercontent.com/100194/196055668-f1b8b02b-18fe-4169-aec6-2902636105a1.png)

See how the black object I put on the back is making those line black and the areas with no background,are white.

### Aseprite and System version

* Aseprite version: 1.2.40-dev
* System: Linux

**Comment by Gasparoken** [comment]
Thanks for this report. What editor are you using to open the SVG?

I tried an external editor to open an Aseprite's SVG and it looks like you described, but I think it's not an Aseprite issue because if I make a new drawing that looks similar in that external editor, I get the same result.

**Comment by GAZ082** [comment]
Thanks Gaspar for checking in. Inkscape!

**Comment by GAZ082** [comment]
@Gasparoken yeah, I did what you did, creating something similar in Inkscape, two adjacent blocks and they also get the thin line. I dont know if there is a fix for this in the SVG specs, but an idea would be to add a 0.5px border on each pixel with the same infill color? I think the issue here is not having a border overlap filling the gap.

**Comment by Gasparoken** [comment]
I need to do some test if an overlapping of rectangles is enough to solve this. However, a SVG feature is pending: _Draw a background rectangle to avoid drawing multiple rectangles of the predominant color_
This action may partially resolve this particular issue.

**Comment by Gasparoken** [comment]
Yes, you're right. The issue  https://github.com/aseprite/aseprite/issues/1911 will be perfect for tracking the feature: "Merge areas of the same color in one big connected shape: we could use something similar to the [MaskBoundaries algorithm](https://github.com/aseprite/aseprite/blob/master/src/doc/mask_boundaries.cpp#L17)"

So the "Thin transparent line between pixels when exporting to SVG" will be resolved by implementing #1911.
