### ISSUE TITLE
8 Connected Fill Escapes Grid With "Stop At Grid" Checked

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#3564]
Select the Fill Tool.
Turn on 8 Connected Fill and Stop at Grid for the fill tool.
Turn on the grid.
Occasionally filling will escape the grid.
![8 Connected Fill](https://user-images.githubusercontent.com/8582123/196842528-1e009148-e14b-485e-a243-6ebb6cbbac9a.gif)

Aseprite v1.3-beta21-x64 Steam
Windows 10

**Comment by Gasparoken** [comment]
Thank you for this report. You're right! This happens in the stable version too.
