### ISSUE TITLE
Tool sub-menu on Toolbox Menu doesn't show on first click (only for Windows, beta version)

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3572]
How to reproduce it:

- In version 1.3beta21, Windows OS, in any sprite, go to the toolbox
- Click on the pencil (for example)
- Tool submenu is not displayed

Note: The tool submenu is displayed if the cursor is moved to the left.

### Aseprite and system version

* Aseprite version: 1.3beta21
* System: Windows 11 Pro

**Comment by dacap** [comment]
Related to #3556 and #3501 (this is why the multiple windows will be disabled by default in the first v1.3.0)

**Comment by Gasparoken** [comment]
Duplicated https://github.com/aseprite/aseprite/issues/3552
