### ISSUE TITLE
Checkpoint in the Undo History

### ISSUE THREAD

**Issue by SaySayTakamura** [aseprite/aseprite#3578]
Hello, my sincere apologies for the bothering, i wanted to recommend something i tought it would be very useful for the Undo History.

I have been working those days (and as many other do) for longer periods and the constant save always got my head a bit messy because when i didn't liked a change i did in the sprite i didn't know which step in the Undo History was the one i saved last.

And if the `Undo History` showed where the last save occured, like this:

```
Initial State
|_Rectangular Tool
|_Clear
|_Paste
|_Deselect(Last Saved Here)
```

And if you undid the file to its `Initial State` and redid something it would show:

```
Initial State
|_Pencil Tool
--Last Saved Step Undone--
```

Sorry for the bothering and hope this is useful for someone.

**Comment by dacap** [comment]
Hi @SaySayTakamura, thanks for the idea, it looks quite simple to implement. I'll give a try later.

**Comment by SaySayTakamura** [comment]
> Hi @SaySayTakamura, thanks for the idea, it looks quite simple to implement. I'll give a try later.

Thanks for the answer Mr.Dacap, can't wait to see it in ;3

Good luck and sorry for the bothering.

**Comment by SaySayTakamura** [comment]
> As a suggestion, marking the first change after save in a different colour or placing a unique glyph before it (a square or an asterisk) might make it easier to find if you keep the Undo History pane narrow. :3
> It could also be useful for the Undo/Redo state popup that appears in the bottom right on change. 

Yeah, the text could go unnoticed by the user if the Undo/Redo Window is in its default size, so this would assist for the user to see that a change was made even in the Windows default size.

**Comment by dacap** [comment]
Some preview screenshots:

Initial state when an image is created:
![image](https://user-images.githubusercontent.com/39654/199349273-1de6c8be-6c3e-40e5-a368-7076f4fb008a.png)

Initial state when an image is loaded:
![image](https://user-images.githubusercontent.com/39654/199349093-799d19cc-e3f4-436a-9dc7-d3cb77ccdca6.png)

After drawing in the image:
![image](https://user-images.githubusercontent.com/39654/199349122-d8f7b3d7-4d6a-46c0-a1b6-c089215aaaca.png)

After saving:
![image](https://user-images.githubusercontent.com/39654/199349149-3db64c6d-071c-4bc1-b82f-d637282f4c43.png)

After undoing and modifying (the saved state was lost):
![image](https://user-images.githubusercontent.com/39654/199349193-427d8e76-3c3b-4bbc-9437-f4d1942c06bf.png)

**Comment by SaySayTakamura** [comment]
Looking great Mr.Capello.
