### ISSUE TITLE
Replace Color preview always previews 'selected' only

### ISSUE THREAD

**Issue by dogboydog** [aseprite/aseprite#3579]
Open the replace color window and choose a color to replace
The preview only ever shows the currently selected layers. Toggling selected/all doesn't make the preview apply to all layers or even to the current layer outside of the selection 
![image](https://user-images.githubusercontent.com/9920963/198859343-57a4e0ee-ec82-49e8-b7bd-6b5b8faa4d88.png)

### Aseprite and System version

* Aseprite version: 1.3 beta 20
* System: Windows

I've seen other people talk about this too but couldn't find an existing issue about it

**Comment by martincapello** [comment]
Thank you for reporting this! I was able to reproduce it.

**Comment by dacap** [comment]
This is a known limitation #841

**Comment by dacap** [comment]
Closing it as it's duplicated.
