### ISSUE TITLE
I can't get the second to last command for the compilation to work on windows

### ISSUE THREAD

**Issue by SkyeTheFoxyFox** [aseprite/aseprite#3589]
I've been trying for 2 hours no but no matter what I try, when I run `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x64 -DSKIA_LIBRARY=C:\deps\skia\out\Release-x64\skia.lib -G Ninja ..` it finishes and says this at the bottom

```-- laf freetype: FREETYPE_LIBRARY-NOTFOUND
-- laf harfbuzz: HARFBUZZ_LIBRARY-NOTFOUND
-- skia dir: C:/deps/skia
-- skia library: C:/deps/skia/out/Release-x64/skia.lib
-- skia library dir: C:/deps/skia/out/Release-x64
-- aseprite libwebp: WEBP_LIBRARIES-NOTFOUND
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WEBP_LIBRARIES
    linked by target "app-lib" in directory C:/aseprite/src/app

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
I've tried reinstalling everything, and I've followed the guide as well as I could, but I just can't get it to do anything else.

**Comment by Gasparoken** [comment]
You need to fill all third_party folders ([aseprite/third_party](https://github.com/aseprite/aseprite/tree/main/third_party))
Also [laf](https://github.com/aseprite/laf/tree/d96bd799c353841b92d25c297022154a5d18824a) folder which is a submodule too.

Try:

`git submodule update --init --recursive`

If any `third_party/*submodule*` folder is empty, clone it manually.

This is all like a patch, but under normal conditions the installation process should be as the instructions say.

I hope this helps!

**Comment by Dolyfin** [comment]
Having the same issue. all third_party folders are not empty and I have recloned/manually cloned them many times, including laf folder. I see no difference between what I have locally. I have even tried older release of aseprite and skia.

**Comment by sooxt98** [comment]
im getting the same error
![image](https://user-images.githubusercontent.com/13378059/204098641-9c8e7aea-4d0f-44a9-a6e9-b6de659ef6c9.png)

**Comment by sooxt98** [comment]
Issue solved with this skia version https://github.com/aseprite/skia/releases

**Comment by sooxt98** [comment]
Another new issue come out
![Uploading image.png…]()

**Comment by sooxt98** [comment]
Solved & build successfully:
1. Delete the build folder
2. 
```
call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" -arch=x64
```
3. follow the INSTALL.MD again

**Comment by Dolyfin** [comment]
> Issue solved with this skia version https://github.com/aseprite/skia/releases

Which skia version? you linked the latest releases page.

**Comment by Dolyfin** [comment]
Ok I seem to have solved my issue. My skia folder was in the C:/aseprite/deps, when it should have been in C:/deps.

**Comment by crovdoto** [comment]
Struggled with the exact same issue following the instructions. I solved it by using the Skia x64 rather than the x86 version.

I don't know WHY that works, but it has seemingly fixed the issue with regards to the penultimate step not working.

**Comment by AshwinC8** [comment]
> Struggled with the exact same issue following the instructions. I solved it by using the Skia x64 rather than the x86 version.
> 
> I don't know WHY that works, but it has seemingly fixed the issue with regards to the penultimate step not working.

This worked for me I had this problem when I compiled skia in Windows, but when i tried out the pre-built binary package, i.e downloaded the Skia x64 content and uncompressed them onto C:\deps\skia, and tried the instructions of INSTALL.MD it worked well for me
