### ISSUE TITLE
mac 1.3 beta performance issues

### ISSUE THREAD

**Issue by mrhelmut** [aseprite/aseprite#3592]
Hello!

It seems that the current 1.3 beta has memory/performances leaks. The program runs fine, but after some time of usage (varying, but more than an hour of work) it becomes increasingly slow to operate down to unusable.

This problem is not present on 1.2.4 (and as far as we can tell, it was present in all 1.3 betas and never in the 1.2 branch).

Thanks for aseprite, it's likely the tool that has the most enhanced our workflow.

Cheers!

### Aseprite and System version

* Aseprite version: 1.3 beta 21 x86 (dmg from Humble)
* System: macOS, 12.1, x64

**Comment by Gasparoken** [comment]
Thanks for your report! We'll look into it.

**Comment by Gasparoken** [comment]
Taking some notes on a particular action: opening and closing the `Preferences` dialog several times consumes more and more `VM: IOSurface` memory.
<img width="550" alt="Screenshot 2022-11-30 at 18 49 59" src="https://user-images.githubusercontent.com/32165475/204917271-b619fc9e-690b-4a5e-871b-2aa66972dc95.png">
OS: MacOS Ventura
Aseprite 1.3beta21-x64

**Comment by Gasparoken** [comment]
As a workaround until this is resolved: uncheck _Edit > Preferences > Experimental > UI with multiple windows_

**Comment by mrhelmut** [comment]
We tested the suggested workaround over a workday and it seems like that was it!

**Comment by dacap** [comment]
This is issue is almost fixed (still NSWindow objects are not deallocated, but it will need further debugging).

More info in the commit description: https://github.com/dacap/laf/commit/66935187061df0a42ef23a459ad7c0f78002cfde

**Comment by briankendall** [comment]
In case it helps, I can trigger the bug quickly by painting a couple of paint strokes and then repeatedly undoing them and redoing them. Basically I just quickly mash Cmd+Z Cmd+Z Cmd+Z Cmd+Shift+Z Cmd+Shift+Z Cmd+Shift+Z over and over again very quickly.

After I've done that around 30 or 40 times the app will be very laggy when I try to paint anything.

**Comment by mrhelmut** [comment]
On our end, we haven't been noticing performance issues since the main release of 1.3. (Not denying the previous comment, just saying that one of the scenarios seems clear.)
