### ISSUE TITLE
Change the license to GPL

### ISSUE THREAD

**Issue by goob256** [aseprite/aseprite#3612]
I posted the GUI that Allegro Sprite Editor is based on at www.allegro.cc along with meditor2, a tilemap editor. The code was GPL and I know you based Aseprite on it. So please change Aseprite to GPL. You must know that a binary of Aseprite posted on allegro.cc would easily be traceable to detect API usage?

**Comment by dacap** [comment]
Hi @goob256, that's not true. I don't even know what that meditor2 is.

>  I know you based Aseprite on it.

I know for a fact that it is not so. I have implemented the tilemap editor from scratch. So you might imagine how I can feel with such false allegation.

So there are some possibilities here: 1) You might be confused with other editor, or 2) your "trace tool" might be reporting you wrong results, or 3) you are just lying.

**Comment by goob256** [comment]
OK David I believe you my old friend.
