### ISSUE TITLE
Encountering bug while compiling aseprite on Ubuntu

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [aseprite/aseprite#3628]
# Describe your bug report or feature request here
I'm trying to compile aseprite on my Lubuntu system following the instructions. When I running these set of commands in the build directory of aseprite,

```
export CC=clang-10
export CXX=clang++-10
cmake \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
  -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
  -DLAF_BACKEND=skia \
  -DSKIA_DIR=$HOME/deps/skia \
  -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
  -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
  -G Ninja \
  ..

```

I'm getting this message in console

```

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WEBP_LIBRARIES
    linked by target "app-lib" in directory /home/gagan/Projects/games/temp/aseprite/src/app

-- Configuring incomplete, errors occurred!
See also "/home/gagan/Projects/games/temp/aseprite/build/CMakeFiles/CMakeOutput.log".
See also "/home/gagan/Projects/games/temp/aseprite/build/CMakeFiles/CMakeError.log".

```
### Aseprite and System version

* Aseprite version: v1.2.40
* System: Lubuntu, 20.04 LTS

**Comment by StarTech13** [comment]
Same problem with me on Ubuntu 22.10. Aseprite version v1.2.40

**Comment by pahaze** [comment]
Do you have `libwebp-dev` installed? Just encountered this myself and didn't have it installed, but even after installing `libwebp-devel` (I'm on openSUSE), I still get it and have to manually set the libraries.

**Comment by StarTech13** [comment]
Thanks! It worked. `libwebp-dev` should be added to the linux dependencies in the install.md.

**Comment by pahaze** [comment]
Will make a PR including the dependency for other distros later. Also happy New Years!

**Comment by dacap** [comment]
Hi there, sorry but I think main branch doesn’t need the dependency anymore because we are using the one included with skia.

**Comment by pahaze** [comment]
I'm getting the issue using the main branch... Unless I did something wrong with CMake configuration :thinking:
I followed the INSTALL file for SUSE and ended up with the same error. I'll make a gist showing output from cloning to running CMake incase I just missed something :shrug:

**Comment by pahaze** [comment]
Weird. After recloning, it now works fine. Welp... Thanks for the help there! :sweat_smile:
But now there's another issue, and that's that `ft2build.h` isn't found during build. `freetype2` gets cloned without issues, so I don't know why it's erroring out. [Here's the Gist](https://gist.github.com/pahaze/e9192b26506fa4332275b5293c94b44e).

**Comment by thego124** [comment]
Hello!
I am also having issues with `WEBP_LIBRARIES` not being found.
i was missing `libwebp-dev`, so i installed it and restarted, but i still get the same error message.
i'm on kubuntu 22.04, if it's worth mentioning

**Comment by aldencolerain** [comment]
@thego124 @pahaze 

I had this same problem.  In the [install directions](https://github.com/aseprite/aseprite/blob/main/INSTALL.md) is states you need to download their pre-compiled branch of the skia library to build aseprite:

> And a compiled version of the aseprite-m102 branch of the [Skia library](https://github.com/aseprite/skia#readme). There are [pre-built packages available](https://github.com/aseprite/skia/releases). You can get some extra information in the [laf dependencies](https://github.com/aseprite/laf#dependencies) page.

I had forgotten to [install their build of this library](https://github.com/aseprite/skia/releases).  I downloaded the `
Skia-Linux-Release-x64-libc++.zip` version. And unzipped them into a directory.  Then I updated the  `DSKIA_DIR`, `DSKIA_LIBRARY_DIR` and `DSKIA_LIBRARY` environment variables in the build command to to point to that directory.

On my first build attempt after getting the skia library I actually got compiler incompatibility error (maybe I should have downloaded the ` Skia-Linux-Release-x64-libstdc++.zip` version? However I fixed it by adding the following to the build command:
```
  -DCMAKE_CXX_FLAGS=-stdlib=libc++ \
  -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ \
```

Here was the final command I used, note that your DSKIA dirs will be different:
```
cmake \
  -DCMAKE_CXX_FLAGS=-stdlib=libc++ \
  -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_OSX_ARCHITECTURES=x86_64 \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
  -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
  -DLAF_BACKEND=skia \
  -DSKIA_DIR=$HOME/aseprite/deps/skia \
  -DSKIA_LIBRARY_DIR=$HOME/aseprite/deps/skia/out/Release-x64 \
  -DSKIA_LIBRARY=$HOME/aseprite/deps/skia/out/Release-x64/libskia.a \
  -G Ninja \
  ..
ninja aseprite
```

**Comment by sommerper** [comment]
Have the same problem on Pop_Os(ubuntu) and Fedora.
I did make sure to download the skia library from here https://github.com/aseprite/skia/releases/tag/m102-861e4743af

And I get
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WEBP_LIBRARIES
    linked by target "app-lib" in directory /home/myname/development/github/aseprite/src/app
```

I'm using this to build:

```
export CC=clang
export CXX=clang++
cmake \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
  -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
  -DLAF_BACKEND=skia \
  -DSKIA_DIR=/home/myname/github/aseprite/deps/skia \
  -DSKIA_LIBRARY_DIR=/home/myname/github/aseprite/deps/skia/out/Release-x64 \
  -DSKIA_LIBRARY=/home/myname/github/aseprite/deps/skia/out/Release-x64/libskia.a \
  -G Ninja \
  ..
ninja aseprite

```

**Comment by Laxystem** [comment]
Still having this issue on Fedora 40. 

<details><summary>Log with with `USE_SHARED_FREETYPE` toggled on manually.</summary>
<p>

[6/1281] Building CXX object laf/ft/CMakeFiles/laf-ft.dir/stream.cpp.o
FAILED: laf/ft/CMakeFiles/laf-ft.dir/stream.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DCMARK_STATIC_DEFINE -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_LINUX -DLAF_SKIA -DNDEBUG -DPNG_NO_MMX_CODE -I/home/danielle/Software/Aseprite/third_party/zlib -I/home/danielle/Software/Aseprite/build/third_party/zlib -I/home/danielle/Software/Aseprite/third_party/libpng -I/home/danielle/Software/Aseprite/build/third_party/libpng -I/home/danielle/Software/Aseprite/third_party/tinyxml2 -I/home/danielle/Software/Aseprite/third_party/pixman/pixman -I/home/danielle/Software/Aseprite/build -I/home/danielle/Software/Aseprite/third_party/giflib -I/home/danielle/Software/Aseprite/third_party/jpeg -I/home/danielle/Software/Aseprite/third_party/curl/include -I/home/danielle/Software/Aseprite/third_party/simpleini -I/home/danielle/deps/skia/third_party/externals/freetype/include -I/home/danielle/deps/skia/third_party/externals/harfbuzz/src -I/home/danielle/Software/Aseprite/laf -I/home/danielle/Software/Aseprite/build/laf -I/home/danielle/Software/Aseprite/src -stdlib=libc++ -O2 -g -DNDEBUG -std=c++17 -MD -MT laf/ft/CMakeFiles/laf-ft.dir/stream.cpp.o -MF laf/ft/CMakeFiles/laf-ft.dir/stream.cpp.o.d -o laf/ft/CMakeFiles/laf-ft.dir/stream.cpp.o -c /home/danielle/Software/Aseprite/laf/ft/stream.cpp
In file included from /home/danielle/Software/Aseprite/laf/ft/stream.cpp:8:
In file included from /home/danielle/Software/Aseprite/laf/ft/stream.h:11:
/home/danielle/Software/Aseprite/laf/ft/freetype_headers.h:11:10: fatal error: 'ft2build.h' file not found
   11 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
1 error generated.
[7/1281] Building CXX object laf/ft/CMakeFiles/laf-ft.dir/lib.cpp.o
FAILED: laf/ft/CMakeFiles/laf-ft.dir/lib.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DCMARK_STATIC_DEFINE -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_LINUX -DLAF_SKIA -DNDEBUG -DPNG_NO_MMX_CODE -I/home/danielle/Software/Aseprite/third_party/zlib -I/home/danielle/Software/Aseprite/build/third_party/zlib -I/home/danielle/Software/Aseprite/third_party/libpng -I/home/danielle/Software/Aseprite/build/third_party/libpng -I/home/danielle/Software/Aseprite/third_party/tinyxml2 -I/home/danielle/Software/Aseprite/third_party/pixman/pixman -I/home/danielle/Software/Aseprite/build -I/home/danielle/Software/Aseprite/third_party/giflib -I/home/danielle/Software/Aseprite/third_party/jpeg -I/home/danielle/Software/Aseprite/third_party/curl/include -I/home/danielle/Software/Aseprite/third_party/simpleini -I/home/danielle/deps/skia/third_party/externals/freetype/include -I/home/danielle/deps/skia/third_party/externals/harfbuzz/src -I/home/danielle/Software/Aseprite/laf -I/home/danielle/Software/Aseprite/build/laf -I/home/danielle/Software/Aseprite/src -stdlib=libc++ -O2 -g -DNDEBUG -std=c++17 -MD -MT laf/ft/CMakeFiles/laf-ft.dir/lib.cpp.o -MF laf/ft/CMakeFiles/laf-ft.dir/lib.cpp.o.d -o laf/ft/CMakeFiles/laf-ft.dir/lib.cpp.o -c /home/danielle/Software/Aseprite/laf/ft/lib.cpp
In file included from /home/danielle/Software/Aseprite/laf/ft/lib.cpp:8:
In file included from /home/danielle/Software/Aseprite/laf/ft/lib.h:12:
/home/danielle/Software/Aseprite/laf/ft/freetype_headers.h:11:10: fatal error: 'ft2build.h' file not found
   11 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
1 error generated.
[8/1281] Building CXX object laf/gfx/CMakeFiles/laf-gfx.dir/region_skia.cpp.o
FAILED: laf/gfx/CMakeFiles/laf-gfx.dir/region_skia.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DCMARK_STATIC_DEFINE -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_LINUX -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_UNIX -DSK_ENABLE_SKSL=1 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_GL=1 -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=1 -I/home/danielle/Software/Aseprite/third_party/zlib -I/home/danielle/Software/Aseprite/build/third_party/zlib -I/home/danielle/Software/Aseprite/third_party/libpng -I/home/danielle/Software/Aseprite/build/third_party/libpng -I/home/danielle/Software/Aseprite/third_party/tinyxml2 -I/home/danielle/Software/Aseprite/third_party/pixman/pixman -I/home/danielle/Software/Aseprite/build -I/home/danielle/Software/Aseprite/third_party/giflib -I/home/danielle/Software/Aseprite/third_party/jpeg -I/home/danielle/Software/Aseprite/third_party/curl/include -I/home/danielle/Software/Aseprite/third_party/simpleini -I/home/danielle/Software/Aseprite/laf -I/home/danielle/Software/Aseprite/build/laf -I/home/danielle/Software/Aseprite/src -I/home/danielle/deps/skia -I/home/danielle/deps/skia/third_party/externals/freetype/include -I/home/danielle/deps/skia/third_party/externals/harfbuzz/src -stdlib=libc++ -O2 -g -DNDEBUG -std=c++17 -MD -MT laf/gfx/CMakeFiles/laf-gfx.dir/region_skia.cpp.o -MF laf/gfx/CMakeFiles/laf-gfx.dir/region_skia.cpp.o.d -o laf/gfx/CMakeFiles/laf-gfx.dir/region_skia.cpp.o -c /home/danielle/Software/Aseprite/laf/gfx/region_skia.cpp
In file included from /home/danielle/Software/Aseprite/laf/gfx/region_skia.cpp:11:
In file included from /home/danielle/Software/Aseprite/laf/gfx/region.h:23:
/home/danielle/Software/Aseprite/laf/gfx/region_skia.h:16:10: fatal error: 'include/core/SkRegion.h' file not found
   16 | #include "include/core/SkRegion.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[9/1281] Building CXX object third_party/fmt/CMakeFiles/fmt.dir/src/os.cc.o
In file included from /home/danielle/Software/Aseprite/third_party/fmt/src/os.cc:13:
In file included from /home/danielle/Software/Aseprite/third_party/fmt/include/fmt/os.h:14:
In file included from /usr/bin/../include/c++/v1/system_error:150:
In file included from /usr/bin/../include/c++/v1/__system_error/error_category.h:15:
In file included from /usr/bin/../include/c++/v1/string:625:
In file included from /usr/bin/../include/c++/v1/string_view:213:
/usr/bin/../include/c++/v1/__fwd/string_view.h:22:41: warning: 'char_traits<fmt::detail::char8_type>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 19, so please migrate off of it. [-Wdeprecated-declarations]
   22 | template <class _CharT, class _Traits = char_traits<_CharT> >
      |                                         ^
/home/danielle/Software/Aseprite/third_party/fmt/include/fmt/core.h:361:26: note: in instantiation of default argument for 'basic_string_view<fmt::detail::char8_type>' required here
  361 | template <typename Char> using std_string_view = std::basic_string_view<Char>;
      |                          ^~~~~
/home/danielle/Software/Aseprite/third_party/fmt/include/fmt/core.h:452:50: note: in instantiation of template type alias 'std_string_view' requested here
  452 |                                       S, detail::std_string_view<Char>>::value)>
      |                                                  ^
/home/danielle/Software/Aseprite/third_party/fmt/include/fmt/format.h:737:57: note: in instantiation of template class 'fmt::basic_string_view<fmt::detail::char8_type>' requested here
  737 | inline auto compute_width(basic_string_view<char8_type> s) -> size_t {
      |                                                         ^
/usr/bin/../include/c++/v1/__string/char_traits.h:81:8: note: 'char_traits<fmt::detail::char8_type>' has been explicitly marked deprecated here
   81 | struct _LIBCPP_DEPRECATED_(
      |        ^
/usr/bin/../include/c++/v1/__config:975:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
  975 | #      define _LIBCPP_DEPRECATED_(m) __attribute__((__deprecated__(m)))
      |                                                     ^
1 warning generated.
[10/1281] Building CXX object laf/os/CMakeFiles/laf-os.dir/common/event_queue.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/common/event_queue.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DCLIP_ENABLE_IMAGE=1 -DCMARK_STATIC_DEFINE -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_FREETYPE -DLAF_LINUX -DLAF_SKIA -DLAF_WITH_CLIP -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_UNIX -DSK_ENABLE_SKSL=1 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_GL=1 -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=1 -I/home/danielle/Software/Aseprite/third_party/zlib -I/home/danielle/Software/Aseprite/build/third_party/zlib -I/home/danielle/Software/Aseprite/third_party/libpng -I/home/danielle/Software/Aseprite/build/third_party/libpng -I/home/danielle/Software/Aseprite/third_party/tinyxml2 -I/home/danielle/Software/Aseprite/third_party/pixman/pixman -I/home/danielle/Software/Aseprite/build -I/home/danielle/Software/Aseprite/third_party/giflib -I/home/danielle/Software/Aseprite/third_party/jpeg -I/home/danielle/Software/Aseprite/third_party/curl/include -I/home/danielle/Software/Aseprite/third_party/simpleini -I/home/danielle/Software/Aseprite/laf -I/home/danielle/Software/Aseprite/build/laf -I/home/danielle/Software/Aseprite/src -I/home/danielle/deps/skia -I/home/danielle/deps/skia/third_party/externals/freetype/include -I/home/danielle/deps/skia/third_party/externals/harfbuzz/src -stdlib=libc++ -O2 -g -DNDEBUG -std=c++17 -MD -MT laf/os/CMakeFiles/laf-os.dir/common/event_queue.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/common/event_queue.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/common/event_queue.cpp.o -c /home/danielle/Software/Aseprite/laf/os/common/event_queue.cpp
In file included from /home/danielle/Software/Aseprite/laf/os/common/event_queue.cpp:17:
In file included from /home/danielle/Software/Aseprite/laf/os/x11/event_queue.h:13:
In file included from /home/danielle/Software/Aseprite/laf/os/event.h:17:
In file included from /home/danielle/Software/Aseprite/laf/os/window.h:15:
In file included from /home/danielle/Software/Aseprite/laf/os/dnd.h:14:
In file included from /home/danielle/Software/Aseprite/laf/os/surface.h:18:
In file included from /home/danielle/Software/Aseprite/laf/os/paint.h:74:
/home/danielle/Software/Aseprite/laf/os/skia/paint.h:13:10: fatal error: 'include/core/SkPaint.h' file not found
   13 | #include "include/core/SkPaint.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[13/1281] Building CXX object laf/gfx/CMakeFiles/laf-gfx.dir/packing_rects.cpp.o
FAILED: laf/gfx/CMakeFiles/laf-gfx.dir/packing_rects.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DCMARK_STATIC_DEFINE -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_LINUX -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_UNIX -DSK_ENABLE_SKSL=1 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_GL=1 -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=1 -I/home/danielle/Software/Aseprite/third_party/zlib -I/home/danielle/Software/Aseprite/build/third_party/zlib -I/home/danielle/Software/Aseprite/third_party/libpng -I/home/danielle/Software/Aseprite/build/third_party/libpng -I/home/danielle/Software/Aseprite/third_party/tinyxml2 -I/home/danielle/Software/Aseprite/third_party/pixman/pixman -I/home/danielle/Software/Aseprite/build -I/home/danielle/Software/Aseprite/third_party/giflib -I/home/danielle/Software/Aseprite/third_party/jpeg -I/home/danielle/Software/Aseprite/third_party/curl/include -I/home/danielle/Software/Aseprite/third_party/simpleini -I/home/danielle/Software/Aseprite/laf -I/home/danielle/Software/Aseprite/build/laf -I/home/danielle/Software/Aseprite/src -I/home/danielle/deps/skia -I/home/danielle/deps/skia/third_party/externals/freetype/include -I/home/danielle/deps/skia/third_party/externals/harfbuzz/src -stdlib=libc++ -O2 -g -DNDEBUG -std=c++17 -MD -MT laf/gfx/CMakeFiles/laf-gfx.dir/packing_rects.cpp.o -MF laf/gfx/CMakeFiles/laf-gfx.dir/packing_rects.cpp.o.d -o laf/gfx/CMakeFiles/laf-gfx.dir/packing_rects.cpp.o -c /home/danielle/Software/Aseprite/laf/gfx/packing_rects.cpp
In file included from /home/danielle/Software/Aseprite/laf/gfx/packing_rects.cpp:14:
In file included from /home/danielle/Software/Aseprite/laf/gfx/region.h:23:
/home/danielle/Software/Aseprite/laf/gfx/region_skia.h:16:10: fatal error: 'include/core/SkRegion.h' file not found
   16 | #include "include/core/SkRegion.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[14/1281] Building CXX object laf/os/CMakeFiles/laf-os.dir/common/system.cpp.o
FAILED: laf/os/CMakeFiles/laf-os.dir/common/system.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DCLIP_ENABLE_IMAGE=1 -DCMARK_STATIC_DEFINE -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_FREETYPE -DLAF_LINUX -DLAF_SKIA -DLAF_WITH_CLIP -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_UNIX -DSK_ENABLE_SKSL=1 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_GL=1 -DSK_INTERNAL -DSK_R32_SHIFT=16 -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=1 -I/home/danielle/Software/Aseprite/third_party/zlib -I/home/danielle/Software/Aseprite/build/third_party/zlib -I/home/danielle/Software/Aseprite/third_party/libpng -I/home/danielle/Software/Aseprite/build/third_party/libpng -I/home/danielle/Software/Aseprite/third_party/tinyxml2 -I/home/danielle/Software/Aseprite/third_party/pixman/pixman -I/home/danielle/Software/Aseprite/build -I/home/danielle/Software/Aseprite/third_party/giflib -I/home/danielle/Software/Aseprite/third_party/jpeg -I/home/danielle/Software/Aseprite/third_party/curl/include -I/home/danielle/Software/Aseprite/third_party/simpleini -I/home/danielle/Software/Aseprite/laf -I/home/danielle/Software/Aseprite/build/laf -I/home/danielle/Software/Aseprite/src -I/home/danielle/deps/skia -I/home/danielle/deps/skia/third_party/externals/freetype/include -I/home/danielle/deps/skia/third_party/externals/harfbuzz/src -stdlib=libc++ -O2 -g -DNDEBUG -std=c++17 -MD -MT laf/os/CMakeFiles/laf-os.dir/common/system.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/common/system.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/common/system.cpp.o -c /home/danielle/Software/Aseprite/laf/os/common/system.cpp
In file included from /home/danielle/Software/Aseprite/laf/os/common/system.cpp:12:
In file included from /home/danielle/Software/Aseprite/laf/os/common/system.h:13:
In file included from /home/danielle/Software/Aseprite/laf/ft/lib.h:12:
/home/danielle/Software/Aseprite/laf/ft/freetype_headers.h:11:10: fatal error: 'ft2build.h' file not found
   11 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
1 error generated.
[15/1281] Building CXX object third_party/fmt/CMakeFiles/fmt.dir/src/format.cc.o
In file included from /home/danielle/Software/Aseprite/third_party/fmt/src/format.cc:8:
In file included from /home/danielle/Software/Aseprite/third_party/fmt/include/fmt/format-inl.h:18:
In file included from /usr/bin/../include/c++/v1/locale:202:
In file included from /usr/bin/../include/c++/v1/__locale:23:
In file included from /usr/bin/../include/c++/v1/string:625:
In file included from /usr/bin/../include/c++/v1/string_view:213:
/usr/bin/../include/c++/v1/__fwd/string_view.h:22:41: warning: 'char_traits<fmt::detail::char8_type>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 19, so please migrate off of it. [-Wdeprecated-declarations]
   22 | template <class _CharT, class _Traits = char_traits<_CharT> >
      |                                         ^
/home/danielle/Software/Aseprite/third_party/fmt/include/fmt/core.h:361:26: note: in instantiation of default argument for 'basic_string_view<fmt::detail::char8_type>' required here
  361 | template <typename Char> using std_string_view = std::basic_string_view<Char>;
      |                          ^~~~~
/home/danielle/Software/Aseprite/third_party/fmt/include/fmt/core.h:452:50: note: in instantiation of template type alias 'std_string_view' requested here
  452 |                                       S, detail::std_string_view<Char>>::value)>
      |                                                  ^
/home/danielle/Software/Aseprite/third_party/fmt/include/fmt/format.h:737:57: note: in instantiation of template class 'fmt::basic_string_view<fmt::detail::char8_type>' requested here
  737 | inline auto compute_width(basic_string_view<char8_type> s) -> size_t {
      |                                                         ^
/usr/bin/../include/c++/v1/__string/char_traits.h:81:8: note: 'char_traits<fmt::detail::char8_type>' has been explicitly marked deprecated here
   81 | struct _LIBCPP_DEPRECATED_(
      |        ^
/usr/bin/../include/c++/v1/__config:975:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
  975 | #      define _LIBCPP_DEPRECATED_(m) __attribute__((__deprecated__(m)))
      |                                                     ^
1 warning generated.

</p>
</details> 

The issue still arises with it being off.
