### ISSUE TITLE
Not Opening

### ISSUE THREAD

**Issue by mkimmj** [aseprite/aseprite#3634]
Describe your bug report or feature request here
Aseprite isn't opening/running, and it also does not register as open in task manager

### Aseprite and System version
[Aseprite-v1.2.34.1-DebugOutput.txt](https://github.com/aseprite/aseprite/files/10251531/Aseprite-v1.2.34.1-DebugOutput.txt)

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by dacap** [comment]
Hi @mkimmj, it looks like Aseprite.exe is running alone (without data/ directory), how did you install Aseprite?

**Comment by mkimmj** [comment]
Hi David, I'm pretty sure I downloaded Aseprite directly off aseprite.org

It was working previously, not sure what's going on with it.
