### ISSUE TITLE
Grid and background aren't aligned

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#3638]
Reported here: https://community.aseprite.org/t/zoom-grid-vs-checkered-background/16566

Create a new sprite with a checkered background and grid of 64x64, and then zoom out.

**Comment by Proggle** [comment]
at 33.3% the grid also diverges significantly from the underlying image - try setting a 128x128 grid on a 1024x1024 image.  

![image](https://user-images.githubusercontent.com/89282845/222219102-d40485be-948f-4eb4-8de7-bf6b7e613100.png)

If you're trying to lay down tiles or whatever it becomes a huge pain for the grid to diverge this far from the real location

**Comment by dacap** [comment]
Fixed with ff14066d1f141dd462b8fd5eb6cfdad335d908f6

@martincapello remember to include the (fix #issueNumber) in the commit description
