### ISSUE TITLE
Disable "Delete Layer" option when the sprite has only one layer

### ISSUE THREAD

**Issue by martincapello** [aseprite/aseprite#3649]
>Would it be possible if when there's just one layer, the "Delete" option is grayed out so the program doesn't scold you over it? A lot of other programs tend to have the Delete option unavailable if there's only one layer. I know it's a minor suggestion, but something to consider.

NOTE: Coming from https://igarastudio.zendesk.com/agent/tickets/4313

**Comment by The-Vector** [comment]
@martincapello Hi Martin, 

I'm a university student and one of my assignments is to work on an open source project.
I found this issue and I think that I can fix it. 
Would it be possible to assign it to me?

Thanks in advance

**Comment by martincapello** [comment]
Hey there, sure I'm assigning it to you. But first of all, please read the CONTRIBUTING.md document, and pay attention to this part: https://github.com/aseprite/aseprite/blob/main/CONTRIBUTING.md#forking--pull-requests
Basically it says that after you made your PR you will have to sign our CLA before we can merge it.

@dacap FYI

**Comment by dacap** [comment]
Just in case @The-Vector we are not an "open source" project in the [OSI definition of "open source"](https://opensource.org/osd/), people prefer to say that we are "[source-available software](https://en.wikipedia.org/wiki/Source-available_software)", and we prefer that way to avoid any controversy.

Please check with your teacher of the assignment will be fulfilled with this kind of project.
