### ISSUE TITLE
"E: Package 'clang-10' has no installation candidate..." while following the guide to building Aseprite on Ubuntu 22.04

### ISSUE THREAD

**Issue by buildbro** [aseprite/aseprite#3650]
I get the following error when I try to run the command to install dependencies.

`$ sudo apt-get install -y g++ clang-10 libc++-10-dev libc++abi-10-dev cmake ninja-build libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev`
`[sudo] password for ea: `
`Reading package lists... Done`
`Building dependency tree... Done`
`Reading state information... Done
Package clang-10 is not available, but is referred to by another package.`
`This may mean that the package is missing, has been obsoleted, or
is only available from another source`

`E: Package 'clang-10' has no installation candidate`
`E: Unable to locate package libc++-10-dev
E: Couldn't find any package by regex 'libc++-10-dev'
E: Unable to locate package libc++abi-10-dev`
`E: Couldn't find any package by regex 'libc++abi-10-dev'`

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Linux, 22.04, Ubuntu

**Comment by buildbro** [comment]
I managed to get around this issue by running the following command instead:

`sudo apt install -y clang libc++-dev libc++abi-dev cmake ninja-build`
Credits to [this Answer](https://unix.stackexchange.com/a/718699/539032) on StackExchange.

**Comment by dacap** [comment]
Hi @buildbro, this is a known issue given the number of distributions (our instructions are done for Ubuntu bionic, 18.0, but newer Ubuntu already have a newer clang version). I've just added a note in the INSTALL file.
