### ISSUE TITLE
Crashes when clicking on Dynamics

### ISSUE THREAD

**Issue by robertomorrison0** [aseprite/aseprite#3681]
Aseprite crashes when clicking on Dynamics with the following:

```
/usr/include/c++/12.2.1/bits/stl_algo.h:3623: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]: Assertion '!(__hi < __lo)' failed.
Aborted (core dumped)
```

* Aseprite version: 1.2.40-2, current fron Github Releases (Aseprite-v1.2.40-Source.zip ), (should be this commit:   c0a872ee51b09e877816e71eb5f3a98e73a3f8b7), installed from the AUR (https://aur.archlinux.org/packages/aseprite)
* System: Linux, Arch Linux (Linux 6.1.6-arch1-3)

I don't seem to be able to add tags to this issue...

Edit: Just wanted to add, that v1.3-beta21 works flawlessly.

**Comment by dacap** [comment]
Same as #3686, this is already fixed in main, with changes like: https://github.com/aseprite/aseprite/commit/f454d9a0af237660175e3b150237c497f87615e1
