### ISSUE TITLE
Crashed when dealing with stl 

### ISSUE THREAD

**Issue by fralonra** [aseprite/aseprite#3686]
Aseprite crashed when I clicked some buttons.
For example, the dynamic button of the pencil tool.

Below is the error shown on the terminal:
```
/usr/include/c++/12.2.1/bits/stl_algo.h:3623: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]: Assertion '!(__hi < __lo)' failed.
```

### Aseprite and System version

* Aseprite version: v1.2.40-dev via AUR
* System: ArchLinux

**Comment by dacap** [comment]
This is already fixed in main branch. To be released.
