### ISSUE TITLE
Scrolling too fast on Laptop.

### ISSUE THREAD

**Issue by TRC-Loop** [aseprite/aseprite#3687]
When i try zooming using my Trackpad it moves very fast and it would be also nice if you can make it so you can schroll up and down using the trackpad

### Aseprite and System version

* Aseprite version:v1.2.40-x64/Steam
* System: Windows

**Comment by Gasparoken** [comment]
Thanks for this report. This will be fixed via https://github.com/aseprite/aseprite/issues/3171.

**Comment by dacap** [comment]
Also related to #1196
