### ISSUE TITLE
Maltese Characters

### ISSUE THREAD

**Issue by DimensionalSpace** [aseprite/aseprite#3699]
Describe your bug report or feature request here
I am making a translation of Aseprite but it seems that the default font does not have the following characters: ċ, Ċ, Ġ, ġ, Ħ, ħ, ż, Ż

### Aseprite and System version

Any

Can you please add these 8 characters?

Thanks!

**Comment by DimensionalSpace** [comment]
It would give out this font instead:
![image](https://user-images.githubusercontent.com/118717619/220055225-c909e99e-1cc3-4db4-87eb-4fde8bcf562c.png)

**Comment by DimensionalSpace** [comment]
its a bug in the font

**Comment by DimensionalSpace** [comment]
it has no maltese characters

**Comment by ElderlyGlek** [comment]
Is the lack of Cyrillic in Aseprite's font considered a bug?

**Comment by dacap** [comment]
I have an extended version of the font with Cyrillic characters, but still a lot of Unicode chars to fix (or support for non-continuous range of Unicode chars must be added for the sprite sheet fonts). Something I have to work on in a near future.

**Comment by ElderlyGlek** [comment]
> I have an extended version of the font with Cyrillic characters, but still a lot of Unicode chars to fix (or support for non-continuous range of Unicode chars must be added for the sprite sheet fonts). Something I have to work on in a near future.

This is great news! Should we expect Cyrillic in release 1.3?

**Comment by DimensionalSpace** [comment]
So when will they be added?

**Comment by DimensionalSpace** [comment]
> I have an extended version of the font with Cyrillic characters, but still a lot of Unicode chars to fix (or support for non-continuous range of Unicode chars must be added for the sprite sheet fonts). Something I have to work on in a near future.

Can I do it? I know how to use fontforge

**Comment by ElderlyGlek** [comment]
> I have an extended version of the font with Cyrillic characters, but still a lot of Unicode chars to fix (or support for non-continuous range of Unicode chars must be added for the sprite sheet fonts). Something I have to work on in a near future.

@dacap and… Should we expect this in 1.3.0?

**Comment by dacap** [comment]
Hi there! This issue is always in my mind, recently I opened the font to continue working but wasn't able to make big progress. I'll try to make some progress today and tomorrow which was casually my plan.

**Comment by ElderlyGlek** [comment]
@dacap it seems to me that the Cyrillic alphabet looks unfinished in places, as an example, extra spaces, characters that are lower than others.

![1](https://user-images.githubusercontent.com/69088106/228991661-dff69c72-78ce-4663-8ee7-5e355ccfd452.png)

![2](https://user-images.githubusercontent.com/69088106/228991664-15505b62-5a0b-461b-9db6-4c843d86bdbd.png)

**Comment by dacap** [comment]
Hi @ElderlyGlek, the font is not yet finished and it will be a work-in-progress for some time, it'll take some iterations to do the adjustments. For other issues you find w/the font I'd highly recommend you to create a new issue specifically with all the problems.

About that some characters that look lower than others, it's because the 7px of height is not enough to fit, in your case, the alternative could be this:

![image](https://user-images.githubusercontent.com/39654/228997861-51339e79-3f8d-438f-85ce-a3defe662457.png)

If it looks good enough, I can update the font for the next release.

Anyway I recommend you to create a new issue if you find a set of problems with the font.
