### ISSUE TITLE
Custom theme does not apply

### ISSUE THREAD

**Issue by TheGhostHybrid** [aseprite/aseprite#3707]
I am simply trying to apply the Dracula theme, the same one that is available on both Dracula’s website and on the Aseprite theme list. The screen partially flashes but does not change the theme.

I can change between light and dark just fine. To demonstrate this in action, I recorded myself attempting (yet again) to change the theme:

![Aseprite Theme Attempt](https://user-images.githubusercontent.com/5500727/221392805-64e58ec3-fa75-4891-a8fa-f0df76d11821.gif)

### Aseprite and System version

* Aseprite version: 1.x-dev, aseprite-git from the AUR
* System: Linux, kernel 6.1.12-1-MANJARO, Manjaro KDE

**Comment by Gasparoken** [comment]
Thanks for this report @TheGhostHybrid. Please, press the "Select" button on _Preferences > Theme_ instead "Apply".

It would be nice to give the current function of the "Select" button to the "Apply" button to avoid confusion.

**Comment by TheGhostHybrid** [comment]
Oh gosh, I feel silly. That definitely worked, but yeah: normally UI quirks like that don’t trip me up, but I suppose there’s a first time for everyone and everything! 😅

**Comment by dacap** [comment]
Hi @TheGhostHybrid, actually this is a recurrent issue, we have to simplify the theme selection after an extension/theme is installed to avoid this kind of situation. Something to fix in a near future.
