### ISSUE TITLE
[Feature request] Faux merged layer selection

### ISSUE THREAD

**Issue by citrus3301** [aseprite/aseprite#3708]
I would like an option that if toggled, whenever you use the magic wand on a top layer that cuts into a continuous color of a bottom layer, treats it like one merged layer and selects by the color of the bottom layer while still respecting the top layer. For an example of this, IbispaintX does this by default

* Aseprite version: 1.2.4 steam
* System: Windows 11

**Comment by Gasparoken** [comment]
-If I understood correctly- Good news! That feature is already implemented. Try the following settings:
<img width="400" alt="Screenshot 2023-02-28 at 08 47 02" src="https://user-images.githubusercontent.com/32165475/221845614-c0efdf7a-a39d-4cbf-a7f2-a8f72e8a3fcb.png">

**Comment by Gasparoken** [comment]
Hi @citrus3301. If the feature you want is the same as described above, please close the issue; otherwise, we'll need more info.
