### ISSUE TITLE
Scrolling through tile entries without tilemap layer selected crashes the program

### ISSUE THREAD

**Issue by lunathir** [aseprite/aseprite#3712]
As title states, ctrl+alt+scroll crashes Aseprite every time a document is open
Aseprite 1.3-beta21
Windows 11

**Comment by dacap** [comment]
Hi @lunathir, when you said "+scroll", what specific action are you doing? (mouse wheel, clicking the middle button to scroll, moving a scrollbar, the sprite editor scrollbar? or the timeline one?, etc.)

If you can share a specific list of steps to reproduce it that would be great. (even more if you can take a screenshot moments before the crash, just to check how the sprite/color bar/active tool are configured).

**Comment by lunathir** [comment]
It seems to be a problem somewhere in my keybind configs, but:
I opened a sprite/made a new one, then did the ctrl+alt+scroll thing, and that's when it crashes

**Comment by lunathir** [comment]
[crash.zip](https://github.com/aseprite/aseprite/files/10950112/crash.zip)
Here's some of the crash log stuff found in AppData/Roaming/Aseprite/crashdb

**Comment by lunathir** [comment]
[crash.zip](https://github.com/aseprite/aseprite/files/10950119/crash.zip)
https://user-images.githubusercontent.com/18320914/224528318-ccb186a7-16c7-48ea-90c7-8c7c596991f0.mp4
Recording shows keybinds, everything's basically defaults. Crash.zip has the files marked with the time of a recent crash from exactly that circumstance in the crashdb folder in Appdata.

**Comment by lunathir** [comment]
@dacap I've given the best information I have at the moment, I've updated the title with relevant information to this issue as well. Apologies for not bringing attention earlier.
