### ISSUE TITLE
Palette From Sprite Bug

### ISSUE THREAD

**Issue by ElderlyGlek** [aseprite/aseprite#3715]
Palette from sprite does not see colors with alpha less than 16 on RGB to palette index mapping: Default (Octree).

### Aseprite and System version

* Aseprite version: v1.3-rc1-dev
* System: Windows, 10 Pro 21H2, OS Build: 19044.1766

**Comment by Gasparoken** [comment]
Thanks for this report. I was able to reproduce it.
