### ISSUE TITLE
Dark Theme Toolbar

### ISSUE THREAD

**Issue by ElderlyGlek** [aseprite/aseprite#3717]
The tools in the toolbar blend into the default dark theme, so I think the tools can be made white like in this example I made:

![Toolbar](https://user-images.githubusercontent.com/69088106/222484086-8225795a-19af-4e6d-b895-d2867d6ad7ef.png)

### Aseprite and System version

* Aseprite version: v1.3-rc1-dev
* System: Windows, 10 Pro 21H2, OS Build: 19044.1766

**Comment by martincapello** [comment]
Thank you for your suggestion! We will take a closer look at this when we have the chance.

**Comment by martincapello** [comment]
We took a look and decided to keep the icons as is. Thank you anyway!
Just remember that if you really want to use the different icons, you can always create a custom theme for Aseprite. In this case it shouldn't be that hard, just copy-pasting the default dark theme and modifiying the sheet.png should suffice.

**Comment by ElderlyGlek** [comment]
> We took a look and decided to keep the icons as is. Thank you anyway! Just remember that if you really want to use the different icons, you can always create a custom theme for Aseprite. In this case it shouldn't be that hard, just copy-pasting the default dark theme and modifiying the sheet.png should suffice.

No problem. I'm not bad at creating custom themes, just thought I'd offer an idea.
