### ISSUE TITLE
Saved Undo History

### ISSUE THREAD

**Issue by ElderlyGlek** [aseprite/aseprite#3718]
I would like the undo history to be stored in .aseprite files, for example, this may be needed for creating timelapses. This idea turned out to be too short, I have nothing more to add.

**Comment by dacap** [comment]
Hi @ElderlyGlek, actually this feature was requested several times in the past:

* https://github.com/aseprite/aseprite/issues/738
* https://github.com/aseprite/aseprite/issues/1324 (as a [separated .undo file](https://github.com/aseprite/aseprite/issues/1324#issuecomment-260881123) too)
* https://github.com/aseprite/aseprite/issues/183#issuecomment-236030642
* https://community.aseprite.org/t/save-undo-history-of-project/4642
* https://community.aseprite.org/t/undo-history-save-restore/14247

**Comment by ElderlyGlek** [comment]
> Hi @ElderlyGlek, actually this feature was requested several times in the past:
> 
>     * [History of all things - Buffing up the Undo feature #738](https://github.com/aseprite/aseprite/issues/738)
> 
>     * [Save/restore the whole session (+undo information) automatically #1324](https://github.com/aseprite/aseprite/issues/1324) (as a [separated .undo file](https://github.com/aseprite/aseprite/issues/1324#issuecomment-260881123) too)
> 
>     * [Redesign .aseprite file format (it might be a .zip file) #183 (comment)](https://github.com/aseprite/aseprite/issues/183#issuecomment-236030642)
> 
>     * https://community.aseprite.org/t/save-undo-history-of-project/4642
> 
>     * https://community.aseprite.org/t/undo-history-save-restore/14247

And… do you have plans for this?

**Comment by dacap** [comment]
Reopening this issue just to be the tracking issue of the "save undo history" in some way. There are plans to save the undo history in a separate file first, and then inside .aseprite files if possible.
