### ISSUE TITLE
Cannot recover sessions from previous versions

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3727]
Sessions of 1.3beta21 cannot be recovered on 1.3.0rc1

* Aseprite version: 1.3.0rc1
* System: MacOS/Windows

**Comment by Gasparoken** [comment]
Internal use:
Reported: https://igarastudio.zendesk.com/agent/tickets/4540 (test file available)
and here: https://igarastudio.zendesk.com/agent/tickets/4546

**Comment by dacap** [comment]
Reported in Steam too: https://steamcommunity.com/app/431730/discussions/0/3783624583052997831/

**Comment by dacap** [comment]
As a side note something to take care: ability to load v1.2.40 sessions, because when we make the transition from v1.2.40 to v1.3, a lot of users might need to recover files from v1.2.40.
