### ISSUE TITLE
Dragging & dropping doesn't function as intended

### ISSUE THREAD

**Issue by LunaByter** [aseprite/aseprite#3737]
I recently made the switch to Linux and noticed that dragging & dropping any type of supported file does not work the way it should. Upon launching Aseprite, dragging & dropping seems to work fine, it will work with single or multiple files. However, attempting to drop another file after that does nothing. The only time this behavior works as intended is on initial launch of a new instance. If the file is closed and you attempt to drag/drop another file, the other file previously closed will be opened. 

https://user-images.githubusercontent.com/108190570/223527790-bafb2381-4e1e-4319-bdeb-667f1856c0af.mp4

### Aseprite and System version

* Aseprite version: 1.2.40-64x (portable/steam), 1.3-rc1-64x (beta)
* System: Arch Linux, 6.1.12-1-MANJARO (64-bit)

**Comment by dacap** [comment]
Hi @LunaByter, it looks like a specific problem in Arch Linux Manjaro (cannot reproduce it on PopOS). I'll give a try to a VM later to try to reproduce it.

**Comment by dacap** [comment]
I was able to reproduce this problem with Manjaro/Dolphin file manager, and it looks like the Xdnd mechanism keep sending us the first file (even after we send a XdndFinished back). So it's something to investigate.

**Comment by LunaByter** [comment]
As of now I've just been using the work around of copying the file location and using the Open option. It's much slower, but I haven't had too much complication with it.

**Comment by LunaByter** [comment]
To confirm as epic0421 stated, yes, this is exclusive to X11. When using Wayland the first file opens as expected, however subsequent files will be opened immediately when hovered over the Aseprite window (not dropped) and seems to cause a lot of bugginess, so much so that it caused Dolphin to crash. This also isn't exclusive to Manjaro, but rather the Dolphin file manager, I just tested it out on a live USB of Kubuntu which also uses the KDE Plasma desktop environment + Dolphin by default. As a workaround, I found another file manager called Nemo and it seems to work perfectly fine.

**Comment by kirikarma** [comment]
> Does it work fine with Nemo on X11?

I've been using Nemo on X11 since switching to Arch a couple of weeks ago because of the drag and drop issue  on Dolphin, and it has been working fine for me, though I’d prefer to be using Dolphin as it integrates better with Plasma. I’d appreciate if this was fixed!.

**Comment by LunaByter** [comment]
Same, I've been having to work around this bug since I started using Linux all the way back in March, and to be honest I miss being able to drag and drop files. It's extremely tedious to open multiple files because I have to open each one. One. At. A. Time. It's been months, has their been any progress on getting this patched? I'd honestly try and do it myself if this app was open source.
