### ISSUE TITLE
Aseprite export sprite sheet incorrect JSON value for meta.scale

### ISSUE THREAD

**Issue by dogunbound** [aseprite/aseprite#3738]
When exporting sprite sheets with these settings:
![image](https://user-images.githubusercontent.com/64436119/223621115-f9f353b0-6ca9-4f9c-b48f-fc76a85fe0d9.png)

Output json incorrectly uses string for scale:

```
{ "frames": [
   ...
 ],
 "meta": {
  "app": "http://www.aseprite.org/",
  "version": "1.3-beta21-x64",
  "image": "check_box_button.png",
  "format": "RGBA8888",
  "size": { "w": 96, "h": 16 },
  "scale": "1",                          <--- Currently string. Should not be a string
  "frameTags": [
   ...
  ],
  "slices": [
  ...
  ]
 }
}
```

This is messing with my rust parser (serde_json).

Desired behavior would be to output a float / double instead of a string.

### Aseprite and System version

* Aseprite version: v1.3-rc1-x64
* System: Arch Linux

**Comment by Gasparoken** [comment]
The JSON format comes from TexturePacker, and the scale value is a string.
[Examples of use](https://github.com/search?q=https%3A%2F%2Fwww.codeandweb.com%2Ftexturepacker+language%3AJSON&type=code&l=JSON)
