### ISSUE TITLE
Onion Skin Loop through tag frames not working correctly

### ISSUE THREAD

**Issue by JovannyLB** [aseprite/aseprite#3739]
The onion skin option "Loop through tag frames" has stopped working recently. While having the setup to onion skin the last and next frames, when at the start of a tagged group of frames, it will show the last frame out of the tag, and when at the end of a tagged group of frames, it will show the first two frames

https://user-images.githubusercontent.com/43629991/223775023-844c28a0-1b85-49fa-8703-a900b9bfda90.mp4

### Aseprite and System version

* Aseprite version: Aseprite v1.3-rc1-x64 Steam [Beta]
* System: Windows 10 Pro 10.0.19044 Build 19044 x64

**Comment by Gasparoken** [comment]
Thanks for this report! I was able to reproduce it.
