### ISSUE TITLE
UI Elements Scaling doesn't apply to the canvas

### ISSUE THREAD

**Issue by thkwznk** [aseprite/aseprite#3748]
The Preferences option `UI Element Scaling` doesn't apply to the canvas, leaving it to the script developer to multiply all values/sizes by the scaling value. Without it, elements drawn on the canvas will be misaligned after changing the scale of UI elements.

### Aseprite and System version

* Aseprite version: 1.3-rc1-x64, Steam
* System: Windows/macOS/Linux, version, distribution

**Comment by dacap** [comment]
Hi @thkwznk! Thinking about this and you are right, probably to simplify the user side, the canvas could be scaled by default with the UI Scaling, but a flag could be provided for `Dialog:canvas{}` to disable the ui scaling (so all screen pixels are available for the canvas if the script takes care of it).

Also the UI scale is not easily accessible (only under `app.preferences.general.ui_scale`, probably we can add `app.uiScale`)
