### ISSUE TITLE
[Feature Request/Bug Fix] Closing Preview Window in Full-Screen Preview Mode.

### ISSUE THREAD

**Issue by SaySayTakamura** [aseprite/aseprite#3762]
My sincere apologies for the bothering once again, but i came today to suggest something that felt... Weird for me i don't know for how much.

When going into Full-Screen Preview Mode (F8), everything's alright, perfect even, but the lil Preview Window is still there (if you had it on during your session) and the problem is that the Preview Window captures the mouse.

So even if you can move freely with the mouse, the Preview Window can and WILL capture its input.

Also, isn't a bit redundant to have a Preview Window inside another? haha

Yet again, my sincere apologies for the bothering, and hope this is useful.

Aseprite Version: Latest(v1.3-rc1-dev)
OS: Windows 10 - Latest Update

**Comment by martincapello** [comment]
NOTE: To reproduce this make sure to have the "UI with multiple windows" option enabled.

**Comment by SaySayTakamura** [comment]
Oh my god, my deepest apologies Mr.Capello, i was out to the Medic, so i couldn't answer you.

Also sorry, i should've described the steps and my Configs for reproducing this, again, my sincere apologies.

**Comment by martincapello** [comment]
No worries, there was no rush!
