### ISSUE TITLE
Aseprite freezes on start on the M2 Mac

### ISSUE THREAD

**Issue by TheEnbyWitch** [aseprite/aseprite#3765]
It was working just fine last time I tried it, but now it launches with a black screen and is completely frozen and unusable. Not even reinstalling and resetting the config helped.

I tried both stable and beta versions, including running them with Rosetta

[Aseprite-v1.2.40-x64-DebugOutput.txt](https://github.com/aseprite/aseprite/files/11023433/Aseprite-v1.2.40-x64-DebugOutput.txt)
[Aseprite-v1.3-rc1-arm64-DebugOutput.txt](https://github.com/aseprite/aseprite/files/11023430/Aseprite-v1.3-rc1-arm64-DebugOutput.txt)
![Screenshot 2023-03-20 at 22 07 54](https://user-images.githubusercontent.com/10626859/226476274-eadc1239-c720-4657-9143-a5e29083b5c9.png)

### Aseprite and System version

* Aseprite version: latest Steam (v1.2.40 and v1.3-rc1)
* System: macOS Ventura 13.2.1, M2 Mac mini

**Comment by TheEnbyWitch** [comment]
Compiling aseprite from source did work at least, I tried both main and the v1.2.40 tag and they work just fine.

God damn, I wish I had a repro of this issue there though.

**Comment by livcoding2** [comment]
Temporary Solution.
Delete all these files!

<img width="591" alt="Screenshot 2023-03-21 at 13 08 36" src="https://user-images.githubusercontent.com/119439757/226588845-84eed150-fbe3-4ac4-857f-86d38ee0d804.png">

**Comment by dacap** [comment]
Hi there @TheEnbyWitch, thanks for giving a try to the compilation, it's really strange that the compiled one works and the official one not.

Some things you can try:

1. Resizing the window to check what happen
2. Switching to full screen mode (pressing <kbd>Command+Ctrl+F</kbd> on macOS)

**Comment by TheEnbyWitch** [comment]
I tried it again today and it worked just fine, so maybe the restart is what did it.

**Comment by dacap** [comment]
Glad to hear that, not sure why it needed a restart, but probably because it's the Steam version, we'll see if we get similar reports in the future 👍
