### ISSUE TITLE
Crash when pasting large sprite into smaller one

### ISSUE THREAD

**Issue by 3elDU** [aseprite/aseprite#3781]
Crash when pasting large sprite (e.g. 20x10) into smaller sprite (e.g. 10x10)

### Aseprite and System version
* Aseprite version: 1.2.40-dev, built from [AUR](https://aur.archlinux.org/packages/aseprite)
* System: Arch Linux

Error message:
```
/usr/include/c++/12.2.1/bits/stl_algo.h:3623: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]: Assertion '!(__hi < __lo)' failed.
[1]    684944 IOT instruction (core dumped)  aseprite
```

Steps to reproduce:
1. Create first sprite
2. Create second sprite, larger in size
3. Draw something on second sprite
4. Select All (Ctrl+A)
5. Copy (Ctrl+C)
6. Go back to first sprite and paste
7. Crash!

**Comment by foxpy** [comment]
> Also it's quite strange that Arch Linux compile the Debug version of Aseprite, that makes things a lot slower on runtime.

Well, first of all, that's not an official Archlinux package, it is just a user-provided AUR build script.
I see them using `-DCMAKE_BUILD_TYPE=None` here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aseprite#n115
While this sure disables cmake built-in (or project-specific, if you use them in your CMakeLists) optimizations, this also enables cmake to bypass external `CFLAGS`, `LDFLAGS` and/or other environment variables to C and C++ compilers. As far as I remember, Arch uses `-O2` by default, so this AUR package is probably not as slow as you could imagine (but we will have to check manually if we are concerned about it).

**Comment by 3elDU** [comment]
Alright, I cloned the aseprite repository, downloaded submodules, downloaded [prebuilt skia library](https://github.com/aseprite/skia/releases), and configured aseprite as follows:
```bash
cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_UI=on -DLAF_BACKEND=skia -DSKIA_DIR=~/dl/Skia-Linux-Release-x64-libstdc++/ -DSKIA_LIBRARY_DIR=/home/zakhar/dl/Skia-Linux-Release-x64-libstdc++/out/Release-x64 -DSKIA_LIBRARY=/home/zakhar/dl/Skia-Linux-Release-x64-libstdc++/out/Release-x64/libskia.a
```

Repeating the steps as described in the issue, it doesn't crash.

I am not sure, but I think [this line](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aseprite#n119) means that aseprite will use libraries present in the system. If that's the case, versions of system libraries may be incompatible with aseprite.
Or there may be other issue(s) with [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aseprite)

As the crash is not reproducible on the main branch, closing this.
