### ISSUE TITLE
Problem with compiling Aseprite on macOS

### ISSUE THREAD

**Issue by robism05** [aseprite/aseprite#3785]
Describe your bug report or feature request here
Used:
```
cmake \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_OSX_ARCHITECTURES=x86_64 \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
  -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
  -DLAF_BACKEND=skia \
  -DSKIA_DIR=$HOME/deps/skia \
  -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
  -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
  -G Ninja \
```

I do not have the app Xcode installed. 

<img width="814" alt="Screenshot 2023-03-31 at 17 35 25" src="https://user-images.githubusercontent.com/86170100/229179127-3f2423be-fa3a-4c45-983e-817829401d1d.png">

### Aseprite and System version

* Aseprite version: Aseprite v1.3-rc2 source code
* System: macOS 12.6.3

**Comment by livcoding2** [comment]
Hello.
Please don't be upset, am also very new to using aseprite, but this is a section intended for reporting bugs, not for compilation guidance. The program compiles very well on all platforms without any bugs.

look at this:
https://github.com/aseprite/aseprite/blob/main/INSTALL.md
