### ISSUE TITLE
The rounded rectangle of GraphicsContext is a little off at the bottom side

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#3795]
Something I've noticed a couple of weeks ago, is that the [GraphicsContext:roundedRect()](https://www.aseprite.org/api/graphicscontext#graphicscontextroundedrect) is not quite right at the bottom:

![image](https://user-images.githubusercontent.com/39654/230254626-c51538d2-46f2-4e3c-8294-20ddf563108c.png)

This is strange because we're using the Skia functions directly (a Skia bug?), probably we are not using the Skia API right.

**Comment by oceanhahn** [comment]
Woah, is this new to 1.3-rc2?
Also it looks like the curves are treating the `bottom` and `right` positions as one pixel beyond the edge of the rectangle, which is why the top left corner is smaller than the bottom right, and the top right and bottom left are lopsided.
