### ISSUE TITLE
Font Issues

### ISSUE THREAD

**Issue by ElderlyGlek** [aseprite/aseprite#3797]
I don’t think it’s worth listing the changed characters, so I’m attaching a file in which I fixed some font flaws, namely extra spaces and characters that are lower than others:

![aseprite_font](https://user-images.githubusercontent.com/69088106/233085345-4e1620e4-9fb3-48dc-b486-9475a1b1de93.png)

Only changed symbols:

![aseprite_font_changed_only](https://user-images.githubusercontent.com/69088106/233085382-ccdb1363-282f-4f02-a1b4-db5251e2c961.png)

In my version "Ё" and "ё" look the same as "Е" and "е" to be at the same height with other characters, "Й" looks the same as "И" for the same reason. As a native speaker of Russian and Ukrainian, I can say that this will not spoil the readability of the text.

**Comment by ElderlyGlek** [comment]
You also need to add the characters "Ґ" and "ґ" from Ukrainian language:

![G](https://user-images.githubusercontent.com/69088106/230705515-146465b6-52a9-4ac2-961d-9ada52a29b02.png)

**Comment by dacap** [comment]
Hi @ElderlyGlek, thanks a lot for the help! I'll try to review these changes and integrate it for the next release (probably next week)! I'll make any comment later if it's required.

**Comment by ElderlyGlek** [comment]
> Hi @ElderlyGlek, thanks a lot for the help! I'll try to review these changes and integrate it for the next release (probably next week)! I'll make any comment later if it's required.

I'm happy to help you, @dacap! By the way, I just edited the post because I forgot to change the "Є" character.

**Comment by ElderlyGlek** [comment]
I also changed the symbols "Ф" and "ф".

**Comment by dacap** [comment]
Thanks a lot @ElderlyGlek, I've just integrated the changes to the font. You can find the updated font here: https://raw.githubusercontent.com/aseprite/aseprite/b5f262f4237c7fded6798bd5956f30b4f56d27a7/data/fonts/aseprite_font.png

**Comment by ElderlyGlek** [comment]
> Thanks a lot @ElderlyGlek, I've just integrated the changes to the font. You can find the updated font here: https://raw.githubusercontent.com/aseprite/aseprite/b5f262f4237c7fded6798bd5956f30b4f56d27a7/data/fonts/aseprite_font.png

Hi, @dacap! I looked at the changes, and noticed that the characters "в", "л", "о" had extra spaces, so here is another corrected file:

![aseprite_font](https://user-images.githubusercontent.com/69088106/235786811-0c1d9732-205a-4654-8031-d624f3341cfe.png)

I also didn't like that the character "Ґ" looks lower than the other characters, so I made it the same as the "Г" (similar to "Й" and "И").

**Comment by dacap** [comment]
@ElderlyGlek I'd prefer to wait to incorporate new changes to the font until we receive more feedback from other users (or probably you find new improvements), because changing a binary file on the Git repository several times is something we try to avoid.

**Comment by ElderlyGlek** [comment]
> @ElderlyGlek I'd prefer to wait to incorporate new changes to the font until we receive more feedback from other users (or probably you find new improvements), because changing a binary file on the Git repository several times is something we try to avoid.

Well, I personally did not notice any problems with the font, the only thing I changed was the characters "У", "у" and "х":

![aseprite_font](https://github.com/aseprite/aseprite/assets/69088106/b4cb5ac4-7ff9-4a10-a694-75c141188c80)

**Comment by ElderlyGlek** [comment]
> > @ElderlyGlek I'd prefer to wait to incorporate new changes to the font until we receive more feedback from other users (or probably you find new improvements), because changing a binary file on the Git repository several times is something we try to avoid.
> 
> Well, I personally did not notice any problems with the font, the only thing I changed was the characters "У", "у" and "х":
> 
> ![aseprite_font](https://user-images.githubusercontent.com/69088106/253824309-b4cb5ac4-7ff9-4a10-a694-75c141188c80.png)

@dacap I forgot to mention you so you probably didn't notice this post.

**Comment by dacap** [comment]
Thanks @ElderlyGlek! Sorry for my late response, probably you could take a look to this PR: https://github.com/aseprite/aseprite/pull/3975 there are some extra change that we'd like to introduce too. What do you think?

**Comment by ElderlyGlek** [comment]
> Thanks @ElderlyGlek! Sorry for my late response, probably you could take a look to this PR: #3975 there are some extra change that we'd like to introduce too. What do you think?

@dacap I already wrote about extra spaces above, and my corrected version of the font does not have this problem.

**Comment by dacap** [comment]
I've just updated the font with your changes @ElderlyGlek in https://github.com/aseprite/aseprite/commit/392dbd130349e9b175ed520e4387ef6b2a84ed1f, thanks to @EricKotato for the help too! :+1:
