### ISSUE TITLE
Regression {slice} format on CLI doesn't work 

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3801]
Reported: https://community.aseprite.org/t/saving-slices-via-cli/17692

 `aseprite -b sheet.aseprite --save-as {slice}.png`

It does not save any files (regression source on commit:  4dc579c386f1d1e034293d77408cc2356b21b53d)

**Comment by dacap** [comment]
It's strange that the report says that it was working on rc1 and not in rc2, but https://github.com/aseprite/aseprite/commit/4dc579c386f1d1e034293d77408cc2356b21b53d was included in rc1.
