### ISSUE TITLE
Ninja Error: build stopped, subcommand failed.

### ISSUE THREAD

**Issue by LubeyGTC** [aseprite/aseprite#3817]
I tried this with Aseprite rc2, 12.4, Ninja 1.11.1 and 1.11.0, Skia m102 and m96, and nothing changes.
I can execute the cmake command successfully, and when I type ninja aseprite I get this with every possible configuration of the versions above. I saw a few other people getting the same error, but none of the solutions there worked for me. It was mostly like wrong skia version, but I tried both m102 and m96 and neither worked:

`FAILED: third_party/json11/CMakeFiles/json11.dir/json11.cpp.obj
C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe  /nologo /TP -DCMARK_STATIC_DEFINE -DNDEBUG -DPNG_NO_MMX_CODE -D_CRT_SECURE_NO_WARNINGS -IC:\aseprite\third_party\zlib -IC:\aseprite\build\third_party\zlib -IC:\aseprite\third_party\libpng -IC:\aseprite\build\third_party\libpng -IC:\aseprite\third_party\tinyxml -IC:\aseprite\third_party\pixman\pixman -IC:\aseprite\build -IC:\aseprite\third_party\giflib -IC:\aseprite\third_party\jpeg -IC:\aseprite\third_party\curl\include -IC:\aseprite\third_party\simpleini -IC:\aseprite\third_party\. -IC:\aseprite\third_party\json11 /DWIN32 /D_WINDOWS /GR /EHsc /MT /Zi /O2 /Ob1 /D NDEBUG -MT -fPIC -fno-rtti -fno-exceptions -Wall /showIncludes /Fothird_party\json11\CMakeFiles\json11.dir\json11.cpp.obj /Fdthird_party\json11\CMakeFiles\json11.dir\json11.pdb /FS -c C:\aseprite\third_party\json11\json11.cpp
cl : Befehlszeile warning D9002 : Unbekannte Option "-fPIC" wird ignoriert.
cl : Befehlszeile warning D9002 : Unbekannte Option "-fno-rtti" wird ignoriert.
cl : Befehlszeile warning D9002 : Unbekannte Option "-fno-exceptions" wird ignoriert.
C:\aseprite\third_party\json11\json11.cpp(171): warning C4626: "json11::Value<json11::Json::NUMBER,double>": Der Zuweisungsoperator wurde implizit als gelöscht definiert.
C:\aseprite\third_party\json11\json11.cpp(173): note: Siehe Verweis auf die gerade kompilierte Klasse Vorlage-Instanziierung "json11::Value<json11::Json::NUMBER,double>".
C:\aseprite\third_party\json11\json11.cpp(171): warning C5027: "json11::Value<json11::Json::NUMBER,double>": Der Operator zum Verschieben einer Zuweisung wurde implizit als gelöscht definiert.
C:\aseprite\third_party\json11\json11.cpp(180): warning C4626: "json11::JsonDouble": Der Zuweisungsoperator wurde implizit als gelöscht definiert.
C:\aseprite\third_party\json11\json11.cpp(180): warning C5027: "json11::JsonDouble": Der Operator zum Verschieben einer Zuweisung wurde implizit als gelöscht definiert.
INTERNER COMPILERFEHLER in "C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe"
    Klicken Sie im Menü "Hilfe" von Visual C++ auf "Technischer Support",
    oder öffnen Sie die Hilfe zum technischen Support, um weitere Informationen zu erhalten.
[350/1453] Building CXX object third_party\fmt\CMakeFiles\fmt.dir\src\format.cc.obj
ninja: build stopped: subcommand failed.`

### Aseprite and System version

* Aseprite version: Tried with Aseprite rc2 and 12.4, Source Code
* System: Windows 11
* VS2022
* CMake 3.26.3

**Comment by GStudiosX2** [comment]
same kinda this is what i get ```
/aseprite/third_party/cityhash/src/city.cc:92:10: fatal error: byteswap.h: No such file or directory
   92 | #include <byteswap.h>
      |          ^~~~~~~~~~~~
compilation terminated.
[6/1130] Building CXX object third_party/IXWeb...t.dir/ixwebsocket/IXWebSocketHandshake.cpp.obj
ninja: build stopped: subcommand failed.
``` im on windows 10 though
