### ISSUE TITLE
Cannot make: scoped_value.h:16:9: note: candidate constructor (the implicit copy constructor) not viable

### ISSUE THREAD

**Issue by psg2002** [aseprite/aseprite#3830]
Hi,

i compiled aseprite some weeks ago with no problem. 

Now, since 2 weeks or so, i cannot compile anymore. I get those constructor not viable errors.

> aseprite/laf/base/scoped_value.h:16:9: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
>   class ScopedValue {

Any ideas what i did wrong? What i remember i updated macOS from 13.3 to 13.3.1. 

Thanks Stefan

Build log:

> -- Generating done
-- Build files have been written to: /Users/stefan/github/aseprite/build
[6/557] Building CXX object src/ui/CMakeFiles/ui-lib.dir/int_entry.cpp.o
FAILED: src/ui/CMakeFiles/ui-lib.dir/int_entry.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DCMARK_STATIC_DEFINE -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_NEWS -DENABLE_SAVE -DENABLE_SCRIPTING -DENABLE_UI -DENABLE_UPDATER -DENABLE_WEBSOCKET -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_MACOS -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_MAC -DSK_ENABLE_SKSL=1 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_GL=1 -DSK_INTERNAL -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=1 -I/Users/stefan/github/aseprite/third_party/zlib -I/Users/stefan/github/aseprite/build/third_party/zlib -I/Users/stefan/github/aseprite/third_party/libpng -I/Users/stefan/github/aseprite/build/third_party/libpng -I/Users/stefan/github/aseprite/third_party/tinyxml -I/Users/stefan/github/aseprite/third_party/pixman/pixman -I/Users/stefan/github/aseprite/build -I/Users/stefan/github/aseprite/third_party/giflib -I/Users/stefan/github/aseprite/third_party/jpeg -I/Users/stefan/github/aseprite/third_party/curl/include -I/Users/stefan/github/aseprite/third_party/simpleini -I/Users/stefan/github/skia/third_party/externals/libwebp/src -I/Users/stefan/github/aseprite/src/observable -I/Users/stefan/github/aseprite/laf -I/Users/stefan/github/aseprite/build/laf -I/Users/stefan/github/aseprite/src -I/Users/stefan/github/skia -I/Users/stefan/github/skia/third_party/externals/freetype/include -I/Users/stefan/github/skia/third_party/externals/harfbuzz/src -I/Users/stefan/github/aseprite/src/observable/. -Wall -Wno-switch -Wimplicit-fallthrough -O2 -g -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=13.3   -Wno-sign-compare -std=c++17 -MD -MT src/ui/CMakeFiles/ui-lib.dir/int_entry.cpp.o -MF src/ui/CMakeFiles/ui-lib.dir/int_entry.cpp.o.d -o src/ui/CMakeFiles/ui-lib.dir/int_entry.cpp.o -c /Users/stefan/github/aseprite/src/ui/int_entry.cpp
/Users/stefan/github/aseprite/src/ui/int_entry.cpp:224:21: error: no viable constructor or deduction guide for deduction of template arguments of 'ScopedValue'
  base::ScopedValue lockFlag(m_changeFromSlider, true);
                    ^
/Users/stefan/github/aseprite/laf/base/scoped_value.h:16:9: note: candidate function template not viable: requires 1 argument, but 2 were provided
  class ScopedValue {
        ^
/Users/stefan/github/aseprite/laf/base/scoped_value.h:18:5: note: candidate function template not viable: requires 3 arguments, but 2 were provided
    ScopedValue(T& instance, const U& inScopeValue, const U& outScopeValue)
    ^
1 error generated.
[9/557] Building CXX object src/ui/CMakeFiles/ui-lib.dir/manager.cpp.o
FAILED: src/ui/CMakeFiles/ui-lib.dir/manager.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DCMARK_STATIC_DEFINE -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_NEWS -DENABLE_SAVE -DENABLE_SCRIPTING -DENABLE_UI -DENABLE_UPDATER -DENABLE_WEBSOCKET -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_MACOS -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_MAC -DSK_ENABLE_SKSL=1 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_GL=1 -DSK_INTERNAL -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=1 -I/Users/stefan/github/aseprite/third_party/zlib -I/Users/stefan/github/aseprite/build/third_party/zlib -I/Users/stefan/github/aseprite/third_party/libpng -I/Users/stefan/github/aseprite/build/third_party/libpng -I/Users/stefan/github/aseprite/third_party/tinyxml -I/Users/stefan/github/aseprite/third_party/pixman/pixman -I/Users/stefan/github/aseprite/build -I/Users/stefan/github/aseprite/third_party/giflib -I/Users/stefan/github/aseprite/third_party/jpeg -I/Users/stefan/github/aseprite/third_party/curl/include -I/Users/stefan/github/aseprite/third_party/simpleini -I/Users/stefan/github/skia/third_party/externals/libwebp/src -I/Users/stefan/github/aseprite/src/observable -I/Users/stefan/github/aseprite/laf -I/Users/stefan/github/aseprite/build/laf -I/Users/stefan/github/aseprite/src -I/Users/stefan/github/skia -I/Users/stefan/github/skia/third_party/externals/freetype/include -I/Users/stefan/github/skia/third_party/externals/harfbuzz/src -I/Users/stefan/github/aseprite/src/observable/. -Wall -Wno-switch -Wimplicit-fallthrough -O2 -g -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=13.3   -Wno-sign-compare -std=c++17 -MD -MT src/ui/CMakeFiles/ui-lib.dir/manager.cpp.o -MF src/ui/CMakeFiles/ui-lib.dir/manager.cpp.o.d -o src/ui/CMakeFiles/ui-lib.dir/manager.cpp.o -c /Users/stefan/github/aseprite/src/ui/manager.cpp
/Users/stefan/github/aseprite/src/ui/manager.cpp:751:32: error: no matching constructor for initialization of 'base::ScopedValue<Widget *>'
    base::ScopedValue<Widget*> scoped(m_lockedWindow, window);
                               ^      ~~~~~~~~~~~~~~~~~~~~~~
/Users/stefan/github/aseprite/laf/base/scoped_value.h:16:9: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
  class ScopedValue {
        ^
/Users/stefan/github/aseprite/laf/base/scoped_value.h:18:5: note: candidate constructor not viable: requires 3 arguments, but 2 were provided
    ScopedValue(T& instance, const U& inScopeValue, const U& outScopeValue)
    ^
1 error generated.
[11/557] Building CXX object src/ui/CMakeFiles/ui-lib.dir/menu.cpp.o
FAILED: src/ui/CMakeFiles/ui-lib.dir/menu.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DCMARK_STATIC_DEFINE -DCURL_STATICLIB -DENABLE_DATA_RECOVERY -DENABLE_NEWS -DENABLE_SAVE -DENABLE_SCRIPTING -DENABLE_UI -DENABLE_UPDATER -DENABLE_WEBSOCKET -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_MACOS -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_MAC -DSK_ENABLE_SKSL=1 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_GL=1 -DSK_INTERNAL -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=1 -I/Users/stefan/github/aseprite/third_party/zlib -I/Users/stefan/github/aseprite/build/third_party/zlib -I/Users/stefan/github/aseprite/third_party/libpng -I/Users/stefan/github/aseprite/build/third_party/libpng -I/Users/stefan/github/aseprite/third_party/tinyxml -I/Users/stefan/github/aseprite/third_party/pixman/pixman -I/Users/stefan/github/aseprite/build -I/Users/stefan/github/aseprite/third_party/giflib -I/Users/stefan/github/aseprite/third_party/jpeg -I/Users/stefan/github/aseprite/third_party/curl/include -I/Users/stefan/github/aseprite/third_party/simpleini -I/Users/stefan/github/skia/third_party/externals/libwebp/src -I/Users/stefan/github/aseprite/src/observable -I/Users/stefan/github/aseprite/laf -I/Users/stefan/github/aseprite/build/laf -I/Users/stefan/github/aseprite/src -I/Users/stefan/github/skia -I/Users/stefan/github/skia/third_party/externals/freetype/include -I/Users/stefan/github/skia/third_party/externals/harfbuzz/src -I/Users/stefan/github/aseprite/src/observable/. -Wall -Wno-switch -Wimplicit-fallthrough -O2 -g -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=13.3   -Wno-sign-compare -std=c++17 -MD -MT src/ui/CMakeFiles/ui-lib.dir/menu.cpp.o -MF src/ui/CMakeFiles/ui-lib.dir/menu.cpp.o.d -o src/ui/CMakeFiles/ui-lib.dir/menu.cpp.o -c /Users/stefan/github/aseprite/src/ui/menu.cpp
/Users/stefan/github/aseprite/src/ui/menu.cpp:351:32: error: no matching constructor for initialization of 'base::ScopedValue<MenuItem *>'
  base::ScopedValue<MenuItem*> restoreOwner(m_menuitem, nullptr);
                               ^            ~~~~~~~~~~~~~~~~~~~
/Users/stefan/github/aseprite/laf/base/scoped_value.h:16:9: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
  class ScopedValue {
        ^
/Users/stefan/github/aseprite/laf/base/scoped_value.h:18:5: note: candidate constructor not viable: requires 3 arguments, but 2 were provided
    ScopedValue(T& instance, const U& inScopeValue, const U& outScopeValue)
    ^
1 error generated.
[16/557] Building CXX object src/ui/CMakeFiles/ui-lib.dir/widget.cpp.o
/Users/stefan/github/aseprite/src/ui/widget.cpp:147:5: warning: 'vsprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use vsnprintf(3) instead. [-Wdeprecated-declarations]
    vsprintf(buf, format, ap);
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:207:1: note: 'vsprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use vsnprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))

### Aseprite and System version

* Aseprite version: commit "1c75092e1383040cd24c5557120fb5bf413730a7" as of 26.04.2023
* System: macOS intel 13.3.1
* cmake version 3.25.2

**Comment by martincapello** [comment]
Hi there, have you tried updating the submodules before compiling? Seems that the laf submodules might be outdated.
Try running this before compiling:
```
git submodule update --recursive
````

**Comment by psg2002** [comment]
Hi martin,

thanks for quick response. That was indeed the problem! I thought a git pull is sufficient. Now i know better!

Many thanks again! Stefan
