### ISSUE TITLE
Scripting API app.activeFrame returns frame object instead of frame number

### ISSUE THREAD

**Issue by Tsukina-7mochi** [aseprite/aseprite#3836]
In [API document](https://www.aseprite.org/api/app#appactiveframe), `app.activeSprite` is stated that it gets of sets the active frame number. However, the getter is defined to return frame object at [src/app/script/app_object.cpp: L547](https://github.com/aseprite/aseprite/blob/main/src/app/script/app_object.cpp#L547)

```cpp
int App_get_frame(lua_State* L)
{
  app::Context* ctx = App::instance()->context();
  Site site = ctx->activeSite();
  if (site.sprite())
    push_sprite_frame(L, site.sprite(), site.frame());
  else
    lua_pushnil(L);
  return 1;
}
```

Reference: 
https://www.aseprite.org/api/app#appactiveframe
https://github.com/aseprite/aseprite/blob/main/src/app/script/app_object.cpp#L547
https://github.com/aseprite/aseprite/blob/main/src/app/script/app_object.cpp#L720

**Comment by dacap** [comment]
Hi @Tsukina-7mochi, actually the problem is in the documentation. It should say that a Frame object is returned.

In a future we have plans to add extra information to frames (user data, etc.) so it will make more sense this kind of object.
