### ISSUE TITLE
CMake Error: Found relative path while evaluating include directories of "app-lib"

### ISSUE THREAD

**Issue by feois** [aseprite/aseprite#3838]
Describe your bug report or feature request here
Fail to compile aseprite
[stdout.log](https://github.com/aseprite/aseprite/files/11394167/stdout.log)
[stderr.log](https://github.com/aseprite/aseprite/files/11394166/stderr.log)

### Aseprite and System version

* Aseprite version: 1.20.40-8, [AUR](https://aur.archlinux.org/packages/aseprite)
* System: Linux, 6.2.12, Manjaro 22.1.0

**Comment by dacap** [comment]
@feois it looks like you tried to compile Aseprite without submodules, please follow the [INSTALL](https://github.com/aseprite/aseprite/blob/main/INSTALL.md) guide, mainly the [Get the source code](https://github.com/aseprite/aseprite/blob/main/INSTALL.md#get-the-source-code) section.

**Comment by feois** [comment]
> @feois it looks like you tried to compile Aseprite without submodules, please follow the [INSTALL](https://github.com/aseprite/aseprite/blob/main/INSTALL.md) guide, mainly the [Get the source code](https://github.com/aseprite/aseprite/blob/main/INSTALL.md#get-the-source-code) section.

For AUR users, add `(cd aseprite; git submodule update --init --recursive)` under the line `bsdtar -xf "${noextract[0]}" -C aseprite` in `PKGBUILD` under `prepare()` section
