### ISSUE TITLE
Eraser tool preview

### ISSUE THREAD

**Issue by berarma** [aseprite/aseprite#3840]
This is an idea for a possible improvement although it's subjective.

With the Pencil tool I can see immediately the pixel painted in the editor and preview views just hovering the pointer over it without actually painting it. When the eraser tool is selected I can't see the effects on the pixel the pointer is over at the moment. 

I think this is useful to see the result of painting the pixel before clicking and I think it would be useful too to see the pixel erased before actually clicking on it. Instead of having to click, see the result and maybe undo the operation and repeat on another pixel.

I don't know if the way it works now is done on purpose, I'm somewhat new to Aseprite and pixel art.

Thanks!

### Aseprite and System version

* Aseprite version: 1.2.40
* System: Debian GNU/Linux 11.6

**Comment by dacap** [comment]
Hi @berarma actually this is already possible but it's not enabled by default, select this option in *Edit > Preferences > Cursors*:

![image](https://user-images.githubusercontent.com/39654/236483628-0e5997c7-e65b-49b6-a48f-ad10b65072f8.png)

**Comment by berarma** [comment]
Perfect. I knew I might be missing something. Thanks!
