### ISSUE TITLE
Menu items that don't respect UI scale

### ISSUE THREAD

**Issue by chaosdrop** [aseprite/aseprite#3843]
1.3RC2 Windows 11 

![image](https://user-images.githubusercontent.com/3247343/236581347-6f30140f-d90a-4bec-8d6b-c02836927acd.png)

I also notice that the size of each menu item group is wildly different.

https://user-images.githubusercontent.com/3247343/236581559-163e92eb-b530-47e4-abe4-151aee406af7.mp4

**Comment by dacap** [comment]
@chaosdrop this is a known issue when the Edit > Preferences > General > UI Elements Scale is changed without restarting. You can try restarting Aseprite and the issue should be fixed.

Anyway it's a bug to be fixed in a near future.

**Comment by dacap** [comment]
@chaosdrop I’ll reopen this issue if you don’t mind, because it’s an unsolved problem (i.e. the menus font should be updated without the need of restarting), and it’s nice to have the issue now to keep track about it.

**Comment by chaosdrop** [comment]
Yeah that's fine. I had just closed it since it sounded like it was already a well known issue and I had just missed the info about it somewhere.

**Comment by martincapello** [comment]
Maybe related https://github.com/aseprite/aseprite/issues/2571
