### ISSUE TITLE
Detachable and movable UI  objects, please?

### ISSUE THREAD

**Issue by KiriBulka** [aseprite/aseprite#3845]
Unless i have missed it somehow in preferences and timeline settings. I would love to be able to have Both Palette/color wheel and the timeline as movable separate windows when in fullscreen mode, or in general.

**Comment by ElderlyGlek** [comment]
Well, I thought about that too, but forgot to suggest an idea, so I'm upvoting this possible feature. Yes, it would definitely be cool to have separate timeline windows, palettes, etc.

**Comment by dacap** [comment]
Somework already in progress in #3485, dup of #518

**Comment by dacap** [comment]
Closing this issue as it's duplicated.
