### ISSUE TITLE
Gen: Bad CPU type in executable

### ISSUE THREAD

**Issue by pegvin** [aseprite/aseprite#3848]
### Aseprite and System version

* Aseprite version: main-branch
* System: macOS Monterey (v12) x86_64

### Issue
when trying to cross-compile for arm64 on a x86_64 macos machine i'm getting the following error:

```
[998/1543] Generating check-translations.txt
FAILED: src/app/check-translations.txt build/src/app/check-translations.txt 
cd build/src/app && build/bin/gen --widgets-dir data/widgets/ --strings-dir data/strings/ --gui-file data/gui.xml >build/src/app/check-translations.txt
/bin/sh: build/bin/gen: Bad CPU type in executable
[999/1543] Generating about.xml.h
FAILED: src/app/about.xml.h build/src/app/about.xml.h 
cd build/src/app && build/bin/gen --input data/widgets/about.xml --widgetid about > build/src/app/about.xml.h.tmp && /usr/local/Cellar/cmake/3.26.3/bin/cmake -E copy_if_different build/src/app/about.xml.h.tmp build/src/app/about.xml.h
/bin/sh: build/bin/gen: Bad CPU type in executable
[1000/1543] Generating advanced_mode.xml.h
FAILED: src/app/advanced_mode.xml.h build/src/app/advanced_mode.xml.h 
cd build/src/app && build/bin/gen --input data/widgets/advanced_mode.xml --widgetid advanced_mode > build/src/app/advanced_mode.xml.h.tmp && /usr/local/Cellar/cmake/3.26.3/bin/cmake -E copy_if_different build/src/app/advanced_mode.xml.h.tmp build/src/app/advanced_mode.xml.h
/bin/sh: build/bin/gen: Bad CPU type in executable
ninja: build stopped: subcommand failed.
```

it seems like the `gen` subdirectory is being built for the `arm64` too but is trying to be executed on `x86_64` cpu.

**Comment by dacap** [comment]
Hi @pegvin, it's a known issue that the gen tool is compiled for the target cpu arch (instead of the host cpu arch). A GEN_EXE variable can defined in cmake to point to gen utility compiled for the host cpu arch in case that that is necessary.

In a future I'd like to change that to automatically compile gen with the host cpu.

**Comment by pegvin** [comment]
shall i keep the issue open as an reminder?

**Comment by dacap** [comment]
We can keep the issue open, but I'm not sure if it's possible to solve with cmake, something I have to dedicate some time to investigate :+1:
