### ISSUE TITLE
Font selector antialiasing color issue

### ISSUE THREAD

**Issue by lunathir** [aseprite/aseprite#3851]
Text antialiasing is wrong in the font selector used in the text tool
![image](https://github.com/aseprite/aseprite/assets/18320914/7f9785a6-e27b-4ab2-9cf5-8b3481a6e5dc)
![image](https://github.com/aseprite/aseprite/assets/18320914/327480c4-84ca-4c08-9151-701fe48e98ca)

Maybe for light mode, make the text black and antialias based on that

### Aseprite and System version

* Aseprite version: Aseprite v1.3-rc2, Steam
* System: Windows 11

**Comment by dacap** [comment]
Thanks @lunathir for reporting this. Something to investigate is when this situation happens:

E.g.

![image](https://github.com/aseprite/aseprite/assets/39654/8f22bc4a-3a13-4810-9def-924ce4493e08)

![image](https://github.com/aseprite/aseprite/assets/39654/57cf37a9-9941-419d-a357-11bdfe6b3d75)

**Comment by lunathir** [comment]
I think I've figured out exactly how the issue crops up: it has to do with trying to calculate the antialiasing colors based on what color the text is, and it's assuming it's a straight black at #000000

**Comment by dacap** [comment]
This is already fixed to be released in the beta branch:

![text-render-bug](https://github.com/user-attachments/assets/4c7759da-c4be-4965-bdc6-eeb9a9c2ae0c)
