### ISSUE TITLE
question:: title bar text

### ISSUE THREAD

**Issue by retroarch-girl** [aseprite/aseprite#3856]
Hi

I'm compiling aseprite for windows and I want to add an extra string in the window's title bar of aseprite (for personal use).

Can somebody tell me what source code file in what folder has the window's title bar text of aseprite assigned?

**Comment by retroarch-girl** [comment]
I also want to ask (for windows). After compiling, can we delete files aseprite.pdb and gen.pdb in the "bin" folder?

**Comment by dacap** [comment]
Hi @retroarch-girl, about the title bar check the [App::updateDisplayTitleBar()](https://github.com/aseprite/aseprite/blob/72d518c5e23c07d7c8030f0d58eda1421d14ef38/src/app/app.cpp#L760) function.

> After compiling, can we delete files aseprite.pdb and gen.pdb in the "bin" folder?

Yes you can remove those files if you are not planning to debug Aseprite 👍

**Comment by retroarch-girl** [comment]
Thanks a lot!
