### ISSUE TITLE
KAK

### ISSUE THREAD

**Issue by retroarch-girl** [aseprite/aseprite#3866]
Describe your bug report or feature request here
...
...
...

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by lunathir** [comment]
Oh my fucking god just leave the devs alone, you don’t need to spew fucking useless harassment at them for literally no god-damn reason

**Comment by lunathir** [comment]
Oh my god leave the devs alone already, your temper tantrums don’t warrant you literally trying to slam Github issues with your stupid unwarranted anger for absolutely no reason and I know you’ve done this before
