### ISSUE TITLE
Im getting this error when trying to build aseprite on windows

### ISSUE THREAD

**Issue by Blackmagic290** [aseprite/aseprite#3874]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WEBP_LIBRARIES
    linked by target "app-lib" in directory C:/aseprite/src/app

Windows 11
Visual Studio Community 2022
cmake-3.26.3
Aseprite-v1.3-rc2-Source.zip
Skia-m102
ninja v1.11.1

**Comment by Gasparoken** [comment]
Please try some action described in https://github.com/aseprite/aseprite/issues/3589
