### ISSUE TITLE
When a sprite contains tilemap layers, the sprite properties dialog should show a section of "tilesets"

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#3875]
We need a way to reorganize tilesets (delete tilesets/duplicate them) in the Sprite Properties dialog.

**Comment by martincapello** [comment]
I was thinking in something like this:
![sprite_props_mockup](https://github.com/aseprite/aseprite/assets/5520828/6199ebb5-9243-44b5-be90-29dea4579620)

The box next to the "Tilemaps" label would be actually a listbox, so it would show the list of tilemaps that are using the selected tileset.

What do you think?

**Comment by dacap** [comment]
Probably I'd not show the Tilemaps combox at the moment. As a first version we might be able to simplify a little (eg show tilemap layer names between `(...)`), and in a future improve this (eg showing the tiles for each tileset).

**Comment by dacap** [comment]
Just as a side note, generally tilesets don't have name (as the name is not visible in the UI yet and can be only entered in the layer/tileset properties, I think it's not generally used).

**Comment by martincapello** [comment]
Okay...do you think that something like this would work?
```
#n (999x999): [name or empty] (Tilemap 1, Tilemap 2, ...)
```

**Comment by dacap** [comment]
Yes, or we can adjust it later eg. the most common (?) case might be one tilemap with one tileset without name, so maybe just showing the layer name is enough in this case, etc. We might have a standard way/one utility function to create this label for tilesets.
