### ISSUE TITLE
Brush and copied area doesn't visible on empty frame

### ISSUE THREAD

**Issue by YoukaiDrawing** [aseprite/aseprite#3882]
If I copy the selection to a new frame, it is invisible until I deselect it.

![image](https://github.com/aseprite/aseprite/assets/104730018/2a2f4bb8-5408-41da-a61b-693501863712)
![image](https://github.com/aseprite/aseprite/assets/104730018/b6efb0dc-9a6f-4751-a510-821bedcdfb0d)

* Aseprite version: v1.3-rc3
* System: Windows 10

**Comment by Gasparoken** [comment]
Thanks for this report! When the image is pasted into an empty cell it is actually floating within the selection, when it's is deselected the image is dropped into the cell and the cell eventually fills.

This is not a bug, it was just intended that way. If this behavior causes any problems in your workflow, please write to us again.

**Comment by Gasparoken** [comment]
Thanks for this report! I was able to reproduce it and we will fix it soon.
