### ISSUE TITLE
Unexpected behavior during multiple cel selection + Cel Properties changes

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3886]
Issue 1: 
- New Sprite
- Add a couple of frames.
- Draw something on frame 2
- Delete the cel on frame 1
- Double click on cel of frame 2 to open Cel Properties, don't close it.
- Select the cel range 1 to 3
- On Cel Properties modify the Color or Z-index or User data.
- Select the cel 2 (non-empty cel).
- Result: the properties were not modified. Expected: the modified fields would be modified in the non-empty cel.

Issue 2: unmodified fields are overwritten.
- New Sprite
- Add a couple of frames.
- Draw something on frame 1 and 2
- Double click on cel of frame 1 to open Cel Properties, don't close it.
- Add some user data for example "first frame"
- Select the cel range 1 to 3
- On Cel Properties modify just the Color.
- Select the cel 1 (non-empty cel).
- Result: user data was modified in all cels. Expected: Modify only cel colors. User data must be kept intact

### Aseprite and System version

* Aseprite version: 1.3rc4
* System: macOS Ventura

**Comment by shanianickel** [comment]
I have a related problem where altering the Z-index with a bunch of cels in a selection also updates all of their color data, which is not my intention.
Does the linked fix also prevent this situation from happening?
![Aseprite_eDLkkWLFpc](https://github.com/aseprite/aseprite/assets/23511351/0b651cb5-32c1-4813-82bd-7b051dbd08ae)

**Comment by dacap** [comment]
That's right @shanianickel, it's related to this issue. We'll merge the fix for the next release.
