### ISSUE TITLE
Clarification: Aseprite File Format Specifications

### ISSUE THREAD

**Issue by mathewmariani** [aseprite/aseprite#3897]
When looking at the [Aseprite File Format Specifications](https://github.com/aseprite/aseprite/blob/main/docs/ase-file-specs.md) I noticed that there is an inconsistency in the specs for compressed data.

All references of compressed data use `BYTE[]` with a comment specifying the compression method (ZLIB) except the Tileset Chunk (0x2023) which uses `PIXEL[]` which is only used for uncompressed data.

Tileset Chunk (0x2023) specifies:
```
DWORD     Compressed data length
PIXEL[]      Compressed Tileset image (see NOTE.3):
                     (Tile Width) x (Tile Height x Number of Tiles)
```

Where Cel Chunk (0x2005) specifies:
(Raw Image Data):
```
WORD      Width in pixels
WORD      Height in pixels
PIXEL[]    Raw pixel data: row by row from top to bottom,
                 for each scanline read pixels from left to right.
```

(Compressed Image):
```
WORD      Width in pixels
WORD      Height in pixels
BYTE[]     "Raw Cel" data compressed with ZLIB method (see NOTE.3)
```

**Comment by dacap** [comment]
Thanks @mathewmariani for the note, I've pushed a change to fix this situation. Basically when you read/write compressed data it's just a stream of bytes, but those bytes represent something when they are uncompressed, I've kept the `PIXEL[]/TILE[]` notation to know what the data is when it's uncompressed.
