### ISSUE TITLE
Scripting Problem: Dialog.bounds doesn't work as expected

### ISSUE THREAD

**Issue by NolifeM** [aseprite/aseprite#3898]
```
local dlg = Dialog("Hello World!")
dlg.bounds = Rectangle(64,64,128,128)
dlg:show{wait=false}
```
A simple script test trying to change dlg bounds and here's the result:
![image](https://github.com/aseprite/aseprite/assets/10100253/a9ef0db9-e4ec-4cf0-a291-d8f7f6a04d46)

I have been test on both stable version and beta version on steam.So it seems to be a little bug.

And here's another thing:
```
local dlg = Dialog("Hello World!")
dlg:label{text="Hello World!"}
dlg:show{wait=false}

```
These code will show a dialog in the middle of screen.
![image](https://github.com/aseprite/aseprite/assets/10100253/fcd6e4cd-384f-49f0-8a13-73e782925110)

But with these:

```
local dlg = Dialog("Hello World!")
dlg:label{text="Hello World!"}
local bounds = dlg.bounds
dlg:show{wait=false}
```

Dialog goes to the left-top corner again.Even we were just trying to access the bounds without doing anythings.
![image](https://github.com/aseprite/aseprite/assets/10100253/c9043a00-c0db-40de-b0c3-a2691f02699d)

### Aseprite and System version

* Aseprite version: v1.3-rc4-x64, steam beta test
* System: Win10

**Comment by Gasparoken** [comment]
Thanks for this report! I was able to reproduce it.
