### ISSUE TITLE
Using simple math for color input

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3900]
Example:
<img width="450" alt="Screenshot 2023-05-30 at 09 02 54" src="https://github.com/aseprite/aseprite/assets/32165475/ea41dd46-3d9e-4c80-a7cd-8e5d844e3b7b">

**Comment by LuckyTigerr** [comment]
Hello, i want to try make this issue, can you please give more information about what need to do and about file location?

**Comment by Gasparoken** [comment]
Hi @LuckyTigerr, thank you in advance!
If you push a PR to the Aseprite project, we will ask for your consent regarding our [Igara Studio Contributor License Agreements](https://github.com/igarastudio/cla).
You can start in `color_sliders.h` in the `struct item` declaration. The `ui::Entry` correspond to the 'entry' on the old way:
```cpp
    struct Item {
      bool show = false;
      ui::Label* label = nullptr;
      ui::Box* box = nullptr;
      ui::Slider* absSlider = nullptr;
      ui::Slider* relSlider = nullptr;
      ui::Entry* entry = nullptr;
    };
```
Some reference can be taken in the following commit (when the input expressions were implemented): https://github.com/aseprite/aseprite/commit/f595ceea7f60a14d53c0fa086cb6c45cb738d323

**Comment by Akylzhan** [comment]
Hey @LuckyTigerr, are you still working on it? If not, I would like to do it
