### ISSUE TITLE
Selected image is modified just moving the pivot point in certain positions

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3901]
Steps to reproduce it:
1- Select a drawn area.
2- Visibilize Pivot Point.
3- Move the Pivot Point until the image is modified.

https://github.com/aseprite/aseprite/assets/32165475/c4f2238a-6093-4b64-a9a1-6dd900f25a15

### Aseprite and System version

* Aseprite version: 1.3rc4
* System: macOS

**Comment by dacap** [comment]
It looks like the problem only appears when the pivot has negative coordinates and there is no rotation (if we rotate the image or skew it, the problem doesn't appear). And it's correct that it appears in some specific zoom levels.
