### ISSUE TITLE
Gestural animation scrubbing

### ISSUE THREAD

**Issue by anaanook** [aseprite/aseprite#3907]
In other software packages there are modifier hotkeys available that let you scrub your animation gesturally while keeping your mouse over the viewer/canvas. This can save time and prevent RSI by letting you flip drawings without having to shift your focus to the timeline or repeatedly pressing next/prev keyframe buttons.

Description of desired workflow:
- Position mouse anywhere over canvas (possibly any editor pane?)
- Press and hold "Scrubbing Modifier" key
- Move mouse Left and Right to scrub animation
- When modifier released either (via pref?):
    - Return to original frame
    - Stay on current frame

I love Aseprite, thanks for all the great work!

**Comment by dacap** [comment]
Hi @anaanook, there is an option available in the *Edit > Keyboard Shortcuts > Drag Value > Change Frame* which might be what you are looking for:

![image](https://github.com/aseprite/aseprite/assets/39654/f2082ea3-5a39-4abc-ad00-08c8c3b45c19)

In this case pressing <kbd>Shift</kbd> and moving the mouse from left to right will move the animation forward, and moving it from right to left will move it backward.

**Comment by anaanook** [comment]
Oh wow, I swear I looked there for this.  This is totally it, thank you!

Amazing!
