### ISSUE TITLE
Destructor"~scoped" may throw an exception

### ISSUE THREAD

**Issue by megumin9** [aseprite/aseprite#3949]
In src/app/commands/cmd_new_layer.cpp 'void NewLayerCommand::onExecute (Context * context)', the destructor of Scoped will be called, then the constructor of DocDestroyer will be executed, which may throw CannotWriteDocException. This will cause a crash, is this intended? If not intended, exceptions can be caught to prevent crash as follows：

DocDestroyer destroyer(context, pasteDoc, 100);
destroyer.destroyDocument();

--->

try {
  DocDestroyer destroyer(context, pasteDoc, 100);
  destroyer.destroyDocument();
} catch (const CannotWriteDocException& e){
  // log...
}

 Aseprite version: Aseprite v1.3-rc4
 System: Linux

**Comment by dacap** [comment]
Hi @megumin9, this is not intended. Actually I've plans to remove exceptions in the document lock/unlock logic from some time
https://github.com/aseprite/aseprite/blob/2f6655f57ec218500f341bd230b37f6c6a59656b/src/app/doc_access.h#L21
to avoid this kind of situations.

The worst we can do is to throw an exception from a destructor on stack unwinding (it can lead to a crash or just `std::terminate()` as you saw). I'll take a closer look to this code later (there are several places where DocDestroyer is used but generally not inside a destructor).

**Comment by martincapello** [comment]
I just want to ask/propose if would it make sense to handle any exception that m_func could throw like this:
```c++
~Scoped() { 
  try {
    m_func();
  } catch (...) {
    if (m_exceptionFunc)
      m_exceptionFunc(std::current_exception()); // Give a chance to the caller to handle the exception
  } 
}
```
Of course this would need the addition of the m_exceptionFunc member to Scope. The m_exceptionFunc call could still throw (or rethrow) an exception though...

**Comment by megumin9** [comment]
Thanks for your response！

**Comment by megumin9** [comment]
I think it can indeed solve the problem, but if the exception is removed as mentioned above, it may not be necessary to catch it.
