### ISSUE TITLE
Alt + scroll doesn't scroll through foreground palette linux

### ISSUE THREAD

**Issue by Motionless-bottle** [aseprite/aseprite#3965]
On windows(11) when i press alt and scroll it scrubs through the foreground palette but on Fedora 37 when I do the same then it doesn't scrub through the foreground palette.

* Aseprite version: 1.29 steam

* System: Fedora 37 with tiling window manager (sway)

**Comment by martincapello** [comment]
Hi there. I wasn't able to reproduce this on Ubuntu, so it might be specific for your system configuration. You can try to use the latest version (1.2.40 at the moment, or try our latest release candidate 1.3-rc4) to see if it helps. 
Also check your keyboard shortcuts:
<img width="1047" alt="Screen Shot 2023-07-13 at 09 25 27" src="https://github.com/aseprite/aseprite/assets/5520828/ee89f7a7-f4a2-45c9-8abf-8c7db7d29b7c">

If you have this same shortcuts, then I'm not sure what could be happening...

@dacap any idea?

**Comment by dacap** [comment]
I think the best would be to update Aseprite first and then give it a try 👍 (I think v1.2.9 is quite old because it was still using the Allegro backend on Linux, in [v1.2.10-beta1 we updated it to Skia](https://www.aseprite.org/release-notes/12/#aseprite-v1-2-10-beta1), as Linux was the latest platform to switch to Skia)

**Comment by Motionless-bottle** [comment]
ok so i am using the latest steam aseprite version, but when i try alt + scroll i just zoom in and out. My keybinds are set properly. In libresprite it works perfectly fine.

**Comment by martincapello** [comment]
Could it be that Sway is swallowing the Alt key? As far as I have researched, the Alt key is the primary modifier in Sway by default...but maybe you changed it, just asking to make sure.

**Comment by Motionless-bottle** [comment]
I am using 1.3 beta now, and i tried to increase brush size with ctrl + scroll and that works but changing foreground or background palette with alt + scroll and alt + shift +scroll don't work.

**Comment by Motionless-bottle** [comment]
> Could it be that Sway is swallowing the Alt key? As far as I have researched, the Alt key is the primary modifier in Sway by default...but maybe you changed it, just asking to make sure.

well i changed that to the windows key but when i tried it on gnome (not a tiling window manager) then it worked without any problems. I will try to change the sway settings and update if i fixed it.

**Comment by Motionless-bottle** [comment]
Ok i am very confused

alt scroll works on libresprite not on aseprite (in sway)
alt scroll works on aseprite on gnome

**Comment by Motionless-bottle** [comment]
so is it sways problem, steams problem, or aseprites problem?

**Comment by Motionless-bottle** [comment]
Ok so i install qtile (another tiling window manager) and tried to alt scroll and it worked so i think it is a sway problem. I might as well just switch to qtile if i am unable to fix it in sway or maybe even just for a change.
