### ISSUE TITLE
Freshly compiled aseprite in Arch on WSL2 gives segmentation error upon opening the build.

### ISSUE THREAD

**Issue by wildkatt-2007** [aseprite/aseprite#3968]
I just compiled aseprite from source by following INSTALL.md but when I try to open it it gives `segmentation fault`.
I dont know where the problem is.

heres the complete log of getting the folders ready, compiling and trying to run it: 
[aseprite-log.txt](https://github.com/aseprite/aseprite/files/12045683/aseprite-log.txt)

### Aseprite and System version
Aseprite source obtained from github releases - https://github.com/aseprite/aseprite/releases/download/v1.3-rc4/Aseprite-v1.3-rc4-Source.zip
Skia obtained from github - https://github.com/aseprite/aseprite/releases/download/v1.3-rc4/Aseprite-v1.3-rc4-Source.zip

OS - Arch on WSL in Windows 11 (ArchWSL by yuk7)
RAM - 16gb
RAM allocated to wsl - 8gb (default)
CPU cores - 8
WSL version - wsl2

[all packages were upgraded before building]

* Aseprite version: Aseprite-v1.3-rc4
* System: Windows 11 with Arch on WSL2

**Comment by dacap** [comment]
Hi @wildkatt-2007, in this case I'd test compiling Aseprite in debug mode (`-DCMAKE_BUILD_TYPE=Debug`) and then running the aseprite with the debugger (`gdb -ex run ./bin/aseprite`)

We didn't test Aseprite on WSL2 yet so I'm not sure if this will work.

**Comment by wildkatt-2007** [comment]
```
Thread 1 "aseprite" received signal SIGSEGV, Segmentation fault.
0x00007ffff7da2854 in XDefaultScreen () from /usr/lib/libX11.so.6
```

This is what I get when I run the gdb command

**Comment by dacap** [comment]
@wildkatt-2007 could you please point me to the specific Arch WSL2 distribution you are using on the Microsoft Store?

**Comment by wildkatt-2007** [comment]
@dacap Im using the preinstalled wsl2 (later updated as per the docs) with my windows 11 and ArchWSL by yuk7 on github - https://github.com/yuk7/ArchWSL/

I haven't used any wsl related things from the store.

**Comment by wildkatt-2007** [comment]
@dacap I'm sorry to interrupt you but I tried compiling the newer release of v1.3-rc5. Which also gives segmentation fault. I think aseprite's access to wsl's allocated resources was considered an unprivileged act for aseprite.

**Comment by wildkatt-2007** [comment]
Also tried v1.2.40 and still the same fault. So it must be a problem in my setup and usage of my wsl and may be not in the code. But still I dont know how to fix it

**Comment by wildkatt-2007** [comment]
Atlast, I have found the issue.

I had to install xorg and x11 libraries and packages and also use a windows x11 server (i used vcxsrv) so that the app can show up.

Also had to turn off firewall (mcafee the bad boy prevents vcxsrv) to make the apps show up.
