### ISSUE TITLE
Glitch with Selection Tool + Alt (Beta 1.3 rc5)

### ISSUE THREAD

**Issue by ReffPixels** [aseprite/aseprite#3976]
When using the rectangular selection tool there's a few keyboard shortcuts to modify the selection. Holding shift allows you to add more rectangles, and holding alt allows you to crop rectangles from the selection.
However, in the latest version of the beta alt seems to break as soon as your mouse touches the UI, and the selection starts rotating randomly.

I have attatched a video showing the problem. Note that the rotations are not intentional / undesirable.

Thank you for the amazing work you do! I have been using Aseprite for many years and it has become my favorite tool for pixel art.

**Aseprite version: Steam Beta 1.3 rc5
System: Windows 11 x64**

https://github.com/aseprite/aseprite/assets/108590573/a3e6a3cf-9a77-4886-9d75-33a898afd481

**Comment by Gasparoken** [comment]
Thanks for reporting this. i was able to reproduce it. We'll fix it soon.
