### ISSUE TITLE
Folder Directory Issue

### ISSUE THREAD

**Issue by RACon87** [aseprite/aseprite#3979]
Despite saving or opening files in my Aseprite folder, the Documents folder became my default folder directory. Normally, the folder with the last saved or opened file will take you to that folder when reopened, but that doesn't work for me anymore.

Aseprite v1.3-rc5-x64
Windows 10

**Comment by dacap** [comment]
@RACon87 I've noticed that too recently, probably a regression in rc5, I'll take a look ASAP.
