### ISSUE TITLE
Aseprite sometimes incorrectly handles paddings between sprites and whole sheet when packing sprite sheets

### ISSUE THREAD

**Issue by nklbdev** [aseprite/aseprite#3993]
Aseprite sometimes has bugs when packing the sprite sheets, related to spacings between the sprites and the edges of the atlas.

For example, a free set of template animations by the author [Zeggy](https://zegley.itch.io), which can be downloaded from [itch.io](https://zegley.itch.io/2d-platformermetroidvania-asset-pack), Aseprite packs the sprite sheet incorrectly if you specify options:

- Sheet Type: Packed
- Trim Cels: True
- Border Padding: 1
- Spacing (Shape Padding): 1

![image](https://github.com/nklbdev/godot-4-importality/assets/7024016/927c22fd-7523-4590-bcfd-b44a037ef449)

In the picture below, I filled the entire area not used by the sprites with blue, and the places where the sprites are in contact with each other and with the borders of the atlas became visible.

![ASEPRITE_BUG](https://github.com/nklbdev/godot-4-importality/assets/7024016/a8de8240-1db4-425c-b269-75f6506cd23a)

### Aseprite and System version
Aseprite: v1.3-rc4-x64, installer (from Humble Bundle)
System:
- OS: Windows 10 Pro 21H2
- Processor: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
- RAM: 64,0 GB
- Graphics: NVIDIA GeForce GTX 760

**Comment by Gasparoken** [comment]
Thanks for this report. I was able to reproduce it.

**Comment by nklbdev** [comment]
If it helps you, please see how the sprite packers are made in my [import plugin for Godot](https://github.com/nklbdev/godot-4-importality/tree/main/addons/nklbdev.importality/sprite_sheet_builder)
