### ISSUE TITLE
Cursor disappearing on hover Preview Window buttons

### ISSUE THREAD

**Issue by SaySayTakamura** [aseprite/aseprite#3995]
When going from inside out of the preview window with the cursor, it may disappear.

Aseprite Version: 1.3 RC6
Windows Version: Latest

Sorry for the bothering and thanks in advance.

**Comment by SaySayTakamura** [comment]
If you know where in the preview window your cursor is and you click, the cursor goes back to normal.

Also while doing some work, i tried to resize the window but it would noy receive input to do so, the cursor was bugged when this happened, i went out of the window and resized from its top corner.

**Comment by martincapello** [comment]
Hi there, just to make sure, are you using the default Aseprite theme? If not, which theme are you using?

**Comment by SaySayTakamura** [comment]
> Hi there, just to make sure, are you using the default Aseprite theme? If not, which theme are you using?
> 
> Also, which UI mode are you using? Single window UI or multiple windows UI?:
> <img width="253" alt="Screen Shot 2023-08-07 at 10 55 15" src="https://github.com/aseprite/aseprite/assets/5520828/37840f66-9f50-49e5-810a-c7f944664a74">
> 
> 

Oh heavens, my sincere apologies for the delayed answer.

Well, i am using Aseprite Built-In Dark Theme and Single Window UI Mode.

Screen Scaling at 200% and UI Element Scaling at 100%

In Experimental "UI with Multiple Windows" is Unchecked and i am using the new Render Engine.

**Comment by martincapello** [comment]
Thank you!

**Comment by martincapello** [comment]
I'm trying to reproduce this without success...some more questions:
1) Are you using some different settings in the Cursors section rather than the following?
<img width="835" alt="Screen Shot 2023-08-09 at 09 54 45" src="https://github.com/aseprite/aseprite/assets/5520828/d6e5c4b5-c416-4247-aec7-91479b55386b">

2) Are you using a Tablet?

3) If you don't mind, could you please send to support@aseprite.org your aseprite.ini file? 

Thank you and sorry for the back and forth.

**Comment by SaySayTakamura** [comment]
> I'm trying to reproduce this without success...some more questions:
> 1) Are you using some different settings in the Cursors section rather than the following?
> <img width="835" alt="Screen Shot 2023-08-09 at 09 54 45" src="https://github.com/aseprite/aseprite/assets/5520828/d6e5c4b5-c416-4247-aec7-91479b55386b">
> 
> 2) Are you using a Tablet?
> 
> 3) If you don't mind, could you please send to support@aseprite.org your aseprite.ini file? 
> 
> Thank you and sorry for the back and forth.

Oh, i am currently not using a tablet.

Also my cursor settings are the same as in the image.

I will send you my INI file as soon as possible.

Currently i reproduced an even worse bug, the preview window stays locked(not its location, i can still move it) the cursor disappears when hovering over it and only if i click i can see the Hand(when you try to move anything, space/middle mouse) but the preview does not move no matter how i move the mouse, also the preview does not change stays the same even in other files, pretty weird.

Also the bug that i reported on this issue does not happen again, but i will send my .ini file, just in case

**Comment by SaySayTakamura** [comment]
> > I'm trying to reproduce this without success...some more questions:
> > 1) Are you using some different settings in the Cursors section rather than the following?
> > <img width="835" alt="Screen Shot 2023-08-09 at 09 54 45" src="https://github.com/aseprite/aseprite/assets/5520828/d6e5c4b5-c416-4247-aec7-91479b55386b">
> > 
> > 2) Are you using a Tablet?
> > 
> > 3) If you don't mind, could you please send to support@aseprite.org your aseprite.ini file? 
> > 
> > Thank you and sorry for the back and forth.
> 
> Oh, i am currently not using a tablet.
> 
> Also my cursor settings are the same as in the image.
> 
> I will send you my INI file as soon as possible.
> 
> Currently i reproduced an even worse bug, the preview window stays locked(not its location, i can still move it) the cursor disappears when hovering over it and only if i click i can see the Hand(when you try to move anything, space/middle mouse) but the preview does not move no matter how i move the mouse, also the preview does not change stays the same even in other files, pretty weird.
> 
> Also the bug that i reported on this issue does not happen again, but i will send my .ini file, just in case

This other bug that i saw, happened just when i changed the Window mode you mentioned before, i did that just to check, since the bug i reported was not happening anymore but this other behavior happened.

My sincere apologies, i should've recorded a video.

**Comment by martincapello** [comment]
Alright, I'm actually glad that the bug didn't happen again. Please, feel free to reopen this whenever you want.
