### ISSUE TITLE
Image files open in new window instead of existing window

### ISSUE THREAD

**Issue by muno777** [aseprite/aseprite#3999]
When opening a .aseprite project file while Aseprite is already running (e.g. opening it from File Explorer), it opens as a tab in the existing window. This is the behavior I'd expect / hope for.

When opening another file such as a .png or a .jpg, it opens a new Aseprite window instead.

### Aseprite and System version

* Aseprite version: 1.3-rc6
* System: Windows 11

**Comment by Gasparoken** [comment]
Thanks for this report. i was able to reproduce it.

It affects Windows, macOS is ok. Linux not tested yet.

**Comment by dacap** [comment]
This is duplicated of #477, can be fixed changing the class associated to png/jpg files: https://github.com/aseprite/aseprite/issues/477#issuecomment-455031959

Anyway we should provide a way to associate files from the same Edit > Preferences > Files probably (it would make things easier for Windows users because the file association is a mess on Windows).

**Comment by dacap** [comment]
The details of required registry entries here: https://github.com/aseprite/aseprite/issues/1070#issuecomment-236999510

**Comment by muno777** [comment]
Thanks for the link - it worked to achieve this behavior but ended up being undesirable due to other reasons. (aseprite files and png files are no longer grouped separately when grouping by file type in explorer, and explorer seems to not show image thumbnails sometimes)

I'm having trouble undoing the regedit changes though. I changed the values back to what I believe are the defaults, but (after a reboot) it's still behaving like the edits are in place. Would you happen to have any guidance for that? Thanks!

![image](https://github.com/aseprite/aseprite/assets/37985497/99100d68-d5eb-469f-b31f-6d53821fe960)
