### ISSUE TITLE
Gradient Dither Pattern dropdown menu is smaller than necessary

### ISSUE THREAD

**Issue by HeyItsLollie** [aseprite/aseprite#4001]
It seems as though the height/width calculation for the gradient dither pattern dropdown is off by a few pixels, possibly not accounting for the UI border, which results in scrollbars appearing unnecessarily.

I primarily use Screen Scaling 100% + UI Elements Scaling 200%, but this issue exists while using Aseprite's default scaling as well.
Aseprite v1.3-rc6-x64, Windows 11

![Aseprite - 2023-08-15 - 14-12-03](https://github.com/aseprite/aseprite/assets/30498581/63135ca5-05c3-43dd-99d2-4ebd45da9638)

**Comment by Gasparoken** [comment]
Thanks for this report. You're right, this dropdown/combobox would be better if the scrollbars don't show up due to a few pixels.
However, the vertical scroll bar will eventually appear if more dithering matrices are installed.
