### ISSUE TITLE
Add check box "Same in all Tools" in the Dynamics options window

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#4003]
It would be great to add option to memorize the dynamics options "per tool" or "same for all tools".
Consider saving these preferences between sessions.

Related: https://github.com/aseprite/aseprite/pull/3986

**Comment by Gasparoken** [comment]
The new feature `Same in all tools` for dynamics options won't work for `maxSize` and `maxAngle` since they are taken from brush properties.
Possible solution: If `Dynamics` and `Same in all tools` are active --> `maxSize` and `maxAngle` are modified in a shared way along all tools.

What's you do think @dacap?

**Comment by dacap** [comment]
@Gasparoken probably we can leave this as it is to match the current behavior (where the max size is not shared). In a future we could include a "Same in all tools" for brush size if users ask for it.
