### ISSUE TITLE
Moving cel action does not respect 'Snap To Grid'

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#4027]
The moving cel action via `MovingCelState::onCommitMouseMove`, does not respect `Snap To Grid` in any case.

Aseprite version: 1.3rc6

**Comment by Liebranca** [comment]
Quick test -- borrowing (or rather pasting in) some bits from `PixelsMovement::moveImage` seems to work fine in the basic case:

```cpp
bool snapToGrid = (Preferences::instance().selection.snapToGrid() &&
                   editor->docPref().grid.snap());

celBounds.x += intOffset.x;
celBounds.y += intOffset.y;

if (snapToGrid) {
  gfx::Rect gridBounds = editor->getSite().gridBounds();
  gfx::PointF gridOffset(
    snap_to_grid(
      gridBounds,
      gfx::Point(celBounds.origin()),
      PreferSnapTo::ClosestGridVertex));

  celBounds.setOrigin(gridOffset);
}

cel->setBounds(gfx::Rect(celBounds));
```

Repeating this operation almost verbatim for `MovingCelState::onMouseUp` was needed to make the cel stay in place after letting go of the mouse, so perhaps this can be it's own function, if only to avoid duplication.

I'm not entirely sure if what I'm doing here is correct, however, but it looks like a place to start.

**Comment by dacap** [comment]
I'm testing #4646 and I'm still not sure if the cel movement should snap to grid with the cel origin, or relative to the cel current position:

![snap-cel](https://github.com/user-attachments/assets/f19aa4bd-ef70-47a5-bbce-61f8874cf2ad)

@Gasparoken do you remember what user reported this problem? (just to check their use case)

**Comment by dacap** [comment]
I'm not sure if it'd make sense to have some kind of pivot option to snap cels to that pivot position:

![image](https://github.com/user-attachments/assets/783e315b-785b-4b4d-99a7-0ad26dae42f6)

There are future plans to include a pivot for cels (#1357) but it's not planned yet.

**Comment by Liebranca** [comment]
Just as an idea, we can make it "magnetic" too. For example:
```C++
void MovingCelState::calcPivot()
{
  // Make a union of all cel bounds
  gfx::RectF bounds;
  for (size_t i=0; i<m_celList.size(); ++i)
    bounds |= m_celStarts[i];

  // Consider all nine points
  float midw = bounds.w * 0.5;
  float midh = bounds.h * 0.5;
  gfx::PointF pivot;
  const gfx::PointF candidates[] = {
    // Center
    gfx::PointF(bounds.x+midw, bounds.y+midh),
    // Corners
    gfx::PointF(bounds.x,      bounds.y),
    gfx::PointF(bounds.x,      bounds.y2()),
    gfx::PointF(bounds.x2(),   bounds.y),
    gfx::PointF(bounds.x2(),   bounds.y2()),
    // Sides
    gfx::PointF(bounds.x+midw, bounds.y),
    gfx::PointF(bounds.x,      bounds.y),
    gfx::PointF(bounds.x+midw, bounds.y2()),
    gfx::PointF(bounds.x2(),   bounds.y+midh),
  };

  // Get closest point to cursor
  double minDist = double((unsigned long)-1);
  for (auto p : candidates) {
    double dist = euclidean_distance(p, m_cursorStart);
    if (dist < minDist) {
      minDist = dist;
      pivot = p;
    }
  }

  // Get grid displacement from closest point
  const gfx::RectF& gridBounds = m_editor->getSite().gridBounds();
  m_pivotOffset = gfx::PointF(gridBounds.size()) - (pivot-bounds.origin());
}
```

Where `euclidean_distance` is vector length after substraction (`sqrt(x*x + y*y)`). I think there is already a function for this formula but I can't find it.

Anyway, selecting a pivot point through a widget would replace the distance calculation. The idea is the same, one simply shifts the grid origin by the resulting offset:

```C++
newOrigin = snap_to_grid(
  gfx::RectF(gridBounds.origin() + m_pivotOffset,
             gridBounds.size()),
  point,
  PreferSnapTo::ClosestGridVertex);
```

But modifying the delta directly doesn't work so well, I'm trying to find a better approach for having multiple cels move together.
