### ISSUE TITLE
YY-CHR Copy/Paste Bug

### ISSUE THREAD

**Issue by SexySpai** [aseprite/aseprite#4029]
When copy/pasting a sprite from YY-CHR into Aseprite, the image shows up as a black square. YY-CHR is a tool used to edit and rip graphics from video game ROMs

Steps to reproduce:
1. Open YY-CHR and drag the Example ROM (example.nes) onto the window. This will open the ROM in the program, you should see a 16x16 Kirby sprite in the top left corner of the left window.
2. Right click and drag over the Kirby sprite, this will select the sprite, indicated by the selection square turning cyan.
3. Press Ctrl+C to copy the image and paste it into Aseprite.
4. The resulting image should be the Kirby sprite, but instead is a black square.

I believe this bug is caused due to how Aseprite interprets clipboard data from YY-CHR, as pasting the image into any other program (i.e. paint.net) results in the correct image being displayed

Link to YY-CHR: https://www.romhacking.net/utilities/958/
Link to the Example ROM: https://drive.google.com/file/d/19OekvgWWBfa4i3vfYPXU_S0IU-otOKbE/view?usp=sharing
Note that I created the Example ROM, it contains no copyrighted game data or code and does not work on an emulator or real hardware.

Aseprite version: v1.3-rc6-x64
System: Windows 10

**Comment by dacap** [comment]
This should be fixed for the next release, related to https://community.aseprite.org/t/6842
