### ISSUE TITLE
{tag} as folder name in "Export As" creating nested folders after first Export

### ISSUE THREAD

**Issue by Brandelan** [aseprite/aseprite#4059]
Describe your bug report or feature request here
If you go to "Export As" and use {tag}/0001.png for example as your file name, it works as expected, creating a folder w/ the name of whatever the tag is.

However, if you export again, the original {tag}/ you wrote is no longer there in the autofilled export name, but it seems like aseprite still treats it as if it is there. So if you then write {tag}/0001.png again, it will export to {tag}/{tag}/0001.png.

All subsequent exports will be exported in this manner, and isn't able to be changed. Even closing and re-opening the project does not fix it.

### Aseprite and System version

* Aseprite version: v1.3-rc6-x64 Steam/beta/
* System: Windows

**Comment by Gasparoken** [comment]
Thanks for reporting this. I was able to reproduce it.

**Comment by gui-marc** [comment]
Hello guys. I want to solve this bug, can I be assigned to this issue?

**Comment by dacap** [comment]
hi @gui-marc, sure, I can assign you this issue, remember to sign the CLA document you might have received in your email address (from signNow).

**Comment by gui-marc** [comment]
Hi guys! Can someone please review my PR for this issue? This fix would be useful for me :)
