### ISSUE TITLE
Lack of clarity in INSTALL.md leading to build issues (Win11)

### ISSUE THREAD

**Issue by CodeGordon** [aseprite/aseprite#4074]
I've followed the instructions in [INSTALL.md](https://github.com/aseprite/aseprite/blob/v1.3-rc6/INSTALL.md). I cloned the repo with the various submodules, made sure to download the Skia package, and got the Ninja binary. I used the commands for Windows in the instructions, and they just do not work.

### Aseprite and System version

* Aseprite version: v13-rc6
* System: Windows 11, VS2022 17.7.4, CMake 3.27.6

[aseprite-build.log](https://github.com/aseprite/aseprite/files/12748106/aseprite-build.log)

**Comment by Xtendera** [comment]
Seems like you have not properly compiled/downloaded the skia library. I'm not really the windows person, as I have only compiled aseprite on linux as of now, but maybe some kind of linking/compile error? It is obvoius that Skia is the issue looking at the unresolved externals, but not sure how to fix it.

**Comment by CodeGordon** [comment]
I got the m102 version of Skia as referenced in the instructions, from the link given (https://github.com/aseprite/skia/releases), so if that's the wrong version, then the install doc needs to be updated. If you're expected to manually compile it instead and not use the pre-built package, then the doc needs to be updated to say that.

**Comment by Xtendera** [comment]
Nope, the prebuilt packages should be fine, and the version is good too. That is super wierd. Did you open the Visual Studio command prompt with the command given in INSTALL.md, or by the shortcut in windows? Some people in an old issue say that running the command launches a 64 bit instance, and since the prebuilt skia is only done for 64 bit, you need that for it to work:

` call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" -arch=x64 `

**Comment by CodeGordon** [comment]
Shouldn't matter, because Windows 11 is exclusively 64-bit, but I'll try it.

**Comment by Xtendera** [comment]
> Shouldn't matter, because Windows 11 is exclusively 64-bit, but I'll try it.

The issue is not of the host architechure, it is of the compile architechure. 64 bit windows can still run/compile 32 bit programs

**Comment by CodeGordon** [comment]
I completely get that, but what I'm saying is that the command line ought to be running in 64-bit mode by default by nature of the host architecture.

**Comment by Xtendera** [comment]
> I completely get that, but what I'm saying is that the command line ought to be running in 64-bit mode by default by nature of the host architecture.

Your right. Maybe even more since Visual Studio 2022 is nativly 64 bit. But, honestly Windows (or Visual Studio) is wierd. Even the issue I linked to, it was assumed that a 64 bit verion of windows was running. Still, the command prompt defaulted to a 32 bit toolset. But you could very much me right.

**Comment by CodeGordon** [comment]
> Nope, the prebuilt packages should be fine, and the version is good too. That is super wierd. Did you open the Visual Studio command prompt with the command given in INSTALL.md, or by the shortcut in windows? Some people in an old issue say that running the command launches a 64 bit instance, and since the prebuilt skia is only done for 64 bit, you need that for it to work:
> 
> `call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" -arch=x64`
> 
> EDIT: [#2501 (comment)](https://github.com/aseprite/aseprite/issues/2501#issuecomment-789988118)

So we're looking at a failure in clarity within the documentation. This was apparently the solution, and absolutely needs to be specified within the install doc. Because it currently has a link to the Microsoft docs, which state being able to use the link in the Start menu. Even if the link remains, the install doc needs to be explicit that opening the dev prompt via the above command is the only way to make it work.

![image](https://github.com/aseprite/aseprite/assets/7526525/0fa6d299-9fcd-4eba-b50a-7b0705ab5b25)

**Comment by Xtendera** [comment]
Go

> > Nope, the prebuilt packages should be fine, and the version is good too. That is super wierd. Did you open the Visual Studio command prompt with the command given in INSTALL.md, or by the shortcut in windows? Some people in an old issue say that running the command launches a 64 bit instance, and since the prebuilt skia is only done for 64 bit, you need that for it to work:
> > `call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" -arch=x64`
> > EDIT: [#2501 (comment)](https://github.com/aseprite/aseprite/issues/2501#issuecomment-789988118)
> 
> So we're looking at a failure in clarity within the documentation. This was apparently the solution, and absolutely needs to be specified within the install doc. Because it currently has a link to the Microsoft docs, which state being able to use the link in the Start menu. Even if the link remains, the install doc needs to be explicit that opening the dev prompt via the above command is the only way to make it work.
> 
> ![image](https://user-images.githubusercontent.com/7526525/271314829-0fa6d299-9fcd-4eba-b50a-7b0705ab5b25.png)

Got it, glad I could help.  @dacap I will make a PR clarifying (I have signed the license agreement already) so that this doesn't happen again.

**Comment by dacap** [comment]
> Got it, glad I could help. @dacap I will make a PR clarifying so that this doesn't happen again.

Anything that can help users to compile in the guide is welcome. Probably the best would be an error from the cmake if it can detect the incompatibility (there is already some work to [detect clang / gcc](https://github.com/aseprite/laf/blob/cbb157c9dc021bf8474e8d00a3145ae7a322528c/cmake/FindSkia.cmake#L76) incompatibilities)

> I have signed the license agreement already

We don't have a signed CLA from your user @Xtendera, probably you can try again the [new CLA process](https://github.com/igarastudio/cla#readme) (which is simplified from the previous steps).

Anyway I'd like to move the INSTALL.md guide to other repository to make it easier to contribute to this specific guide (e.g. without signing a CLA). And probably have more detailed sections/files for specific platforms.

**Comment by Xtendera** [comment]
> > Got it, glad I could help. @dacap I will make a PR clarifying so that this doesn't happen again.
> 
> Anything that can help users to compile in the guide is welcome. Probably the best would be an error from the cmake if it can detect the incompatibility (there is already some work to [detect clang / gcc](https://github.com/aseprite/laf/blob/cbb157c9dc021bf8474e8d00a3145ae7a322528c/cmake/FindSkia.cmake#L76) incompatibilities)
> 
> > I have signed the license agreement already
> 
> We don't have a signed CLA from your user @Xtendera, probably you can try again the [new CLA process](https://github.com/igarastudio/cla#readme) (which is simplified from the previous steps).
> 
> Anyway I'd like to move the INSTALL.md guide to other repository to make it easier to contribute to this specific guide (e.g. without signing a CLA). And probably have more detailed sections/files for specific platforms.

Ok, I signed it again, but I believed I had already done it. I will submit a PR very soon. Yes, and I like the idea of a seperate repo with install/compile guides.

**Comment by dacap** [comment]
> Ok, I signed it again, but I believed I had already done it. 

@Xtendera After you fill the form, you will receive an email from signNow to sign the CLA.

**Comment by Xtendera** [comment]
> > Ok, I signed it again, but I believed I had already done it.
> 
> @Xtendera After you fill the form, you will receive an email from signNow to sign the CLA.

Hello, I currently don't have access to the email in the form, can you send it to the email I filled out the form from? Thank you. I can fill it out again if I need to.
