### ISSUE TITLE
Add button to switch the timeline visibility

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4081]
From a long time ago (~2013) I wanted a button to show the timeline (right now it's only accessible via *View > Timeline*, <kbd>Tab</kbd>, or automatically displayed when a new layer or frame is added).

Found the original mockup ( also in https://github.com/aseprite/aseprite/issues/1731#issuecomment-546699948 ):

![image](https://github.com/aseprite/aseprite/assets/39654/8e4cd697-24e8-4e2b-aeb5-810d91c77a86)

We have a filmstrip icon in the theme too:

![image](https://github.com/aseprite/aseprite/assets/39654/bab8328a-de1e-49e1-89d9-7d0ed899d5dc)

**Comment by Akylzhan** [comment]
I would like to work on this but I don't see filmstrip icon in the theme. Also seems like some big chunk of code will be duplicated (e.g [drawing icon](https://github.com/aseprite/aseprite/blob/27ec013f8b4bd10e64e7c0437939c69c3d614ccf/src/app/ui/toolbar.cpp#L331-L347C1)) should I move them to separate function or lambda?

**Comment by dacap** [comment]
Hi @Akylzhan, it would be great if you can take this one.

About the theme, check the `icon_frame` slice, I think we can use that one:

![image](https://github.com/aseprite/aseprite/assets/39654/ef51af28-d08c-46de-ab01-5b8ae419564d)

About the duplicated code, probably a private member function in `ToolBar` would do the job (we prefer member functions instead of lambdas if possible).

**Comment by Akylzhan** [comment]
Should I reuse `icon_frame` and invert the color or draw a similar one near preview icon?
