### ISSUE TITLE
Deleting layer in group shows error message

### ISSUE THREAD

**Issue by The-Vector** [aseprite/aseprite#4083]
I've been using the development/main branch of aseprite (v1.x-dev), and I noticed that when two layers are in a group, which is the root layer, if a layer is right clicked without being highlighted, it gives the "You cannot delete all layers" popup, but if highlighted by shift clicking, it can be deleted. I've added a gif below to show this behaviour more easily.

![asepriteLayerBug](https://github.com/aseprite/aseprite/assets/50102922/231ad37d-7caf-4dc9-9922-5a839bd77f7f)

I found the potential [issue](https://github.com/aseprite/aseprite/blob/5a59ed32c17dad20e8339fc111df14dbcfd69a20/src/app/commands/cmd_remove_layer.cpp#L164), and have made a working fix in my fork, so I can potentially make a pull request with the changes.

**Comment by dacap** [comment]
Nice catch @The-Vector 👍

**Comment by dacap** [comment]
@The-Vector just in case that you are working on another PR, please check [this comment](https://github.com/aseprite/aseprite/pull/4070#discussion_r1337859317) first.

**Comment by The-Vector** [comment]
I believe the issue has been fixed in the pull request.
