### ISSUE TITLE
Pasting an image from Browser changes colors

### ISSUE THREAD

**Issue by DJLink** [aseprite/aseprite#4102]
If I paste an image from memory from a broser into Aseprite the colors get all "corrupted", almost like it's converting it to another color mode (or from a wrong one), I have the image set to RGB. 
This happens copying from a browser (Edge and Safari are the ones I tested), however, when copying from another program, for example Krita, the image is ok. In the video I copy from browser and then copy from Krita, the second one is ok.

### Aseprite and System version

* Aseprite version: 1.2.40-arm64, Steam
* System: macOS, 14.0, Sonoma

https://github.com/aseprite/aseprite/assets/423769/80dac832-f371-48c3-9c80-03550ac0bc7d

**Comment by dacap** [comment]
Thanks @DJLink for reporting this bug, it looks like now web browsers are copying images with 10 bits per each RGB component (instead of 8 bits) when it's possible. We're going to fix this for the next release.

**Comment by DJLink** [comment]
wow that was fast, thanks for checking it. Appreciate the hard work.

**Comment by dacap** [comment]
It looks like the problem was simpler, I was miscalculating the number of bits per component, macOS uses 8-bit per RGB channel but I was incorrectly dividing `bits per pixel / channels = 32 / 3 = 10 = bits per channel` for images without alpha channel.
