### ISSUE TITLE
"Change Layer" scroll wheel shortcut can misbehave or crash when adding / removing layers

### ISSUE THREAD

**Issue by muno777** [aseprite/aseprite#4114]
The "Change Layer" shortcut for the scroll wheel doesn't seem to properly recognize when a layer is added or removed to the active sprite. It behaves as if the layer list hasn't changed, which causes undesired effects.

If a layer is added while editing the sprite, it'll be "skipped over" when changing layers.

If a layer is removed, trying to select it with the shortcut will crash Aseprite (force close).

Both of these are fixed by first closing and reopening the sprite. It should be reproducible by just opening a sprite and then adding or removing a layer; the adding effect seems a little inconsistent, but I can very consistently reproduce the error from removing a layer.

### Aseprite and System version

* Aseprite version: v1.3-rc6-x64
* System: Windows 11

**Comment by dacap** [comment]
Hi @muno777! thanks for this bug report, a fix will be available in the next release 👍
