### ISSUE TITLE
Palette is not generated from RGB sprite sheet file after Export Sprite Sheet

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4127]
Related to: https://github.com/aseprite/aseprite/pull/3943#issuecomment-1804027247

![export-sprite-sheet](https://github.com/aseprite/aseprite/assets/39654/77def828-8885-4e2d-9bbe-23eeaab1400a)

**Comment by Akylzhan** [comment]
Seems like the problem is that `FileOp::postLoad()` is responsible for generating a palette and the opening of exported spritesheet just changes the context to generated document. One solution could be requesting the opening of generated file instead of changing the context to generated document
