### ISSUE TITLE
Make error "Undefined symbols"

### ISSUE THREAD

**Issue by ivkraft** [aseprite/aseprite#4132]
Describe your bug report or feature request here
[build] : && /usr/bin/clang++ -O2 -std=c++14 -stdlib=libc++ -Wall -Wno-switch -std=gnu++17 -Os -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -O2 src/CMakeFiles/libresprite.dir/main/main.cpp.o -o bin/libresprite  -all_load  lib/libapp-lib.a  -Xlinker -framework -Xlinker Cocoa  -Xlinker -framework -Xlinker Carbon  -Xlinker -framework -Xlinker IOKit  lib/libcfg-lib.a  lib/libcss-lib.a  lib/libfilters-lib.a  lib/libflic-lib.a  lib/libnet-lib.a  /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/lib/libcurl.tbd  lib/librender-lib.a  lib/libdoc-lib.a  lib/libfixmath-lib.a  lib/libscript-lib.a  lib/libduktape.a  -lm  lib/libui-lib.a  lib/libclip.a  -Xlinker -framework -Xlinker Cocoa  lib/libshe.a  lib/libbase-lib.a  lib/libobs.a  lib/libmodp_b64.a  /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/lib/libdl.tbd  lib/libgfx-lib.a  -L/opt/homebrew/lib  -L/opt/homebrew/Cellar/sdl2_image/2.6.3_2/lib  -lSDL2  -lSDL2_image  -lSDL2  -lSDL2_image  /opt/homebrew/lib/libpixman-1.dylib  lib/libundo.a  /opt/homebrew/lib/libtinyxml.dylib  /opt/homebrew/lib/libjpeg.dylib  /opt/homebrew/lib/libgif.dylib  /opt/homebrew/lib/libpng.dylib  /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/lib/libz.tbd  /opt/homebrew/lib/liblua5.4.dylib  /opt/homebrew/lib/libfreetype.dylib && :
[build] ld: warning: ignoring duplicate libraries: '-lSDL2', '-lSDL2_image'
[build] ld: Undefined symbols:
[build]   _BitSize, referenced from:
[build]       app::GifEncoder::GifEncoder(app::FileOp*, GifFileType*) in libapp-lib.a[216](gif_format.cpp.o)
[build]       app::GifEncoder::GifEncoder(app::FileOp*, GifFileType*) in libapp-lib.a[216](gif_format.cpp.o)
[build]       app::GifEncoder::createColorMap(doc::Palette const*) in libapp-lib.a[216](gif_format.cpp.o)
[build]       app::GifEncoder::createColorMap(doc::Palette const*) in libapp-lib.a[216](gif_format.cpp.o)
[build]   _EGifPutExtensionFirst, referenced from:
[build]       app::GifEncoder::writeLoopExtension() in libapp-lib.a[216](gif_format.cpp.o)
[build]   _EGifPutExtensionLast, referenced from:
[build]       app::GifEncoder::writeLoopExtension() in libapp-lib.a[216](gif_format.cpp.o)
[build]   _EGifPutExtensionNext, referenced from:
[build]       app::GifEncoder::writeLoopExtension() in libapp-lib.a[216](gif_format.cpp.o)
[build]   _FreeMapObject, referenced from:
[build]       app::GifDecoder::~GifDecoder() in libapp-lib.a[216](gif_format.cpp.o)
[build]       app::GifEncoder::writeImage(int, gfx::RectT<int> const&, app::DisposalMethod) in libapp-lib.a[216](gif_format.cpp.o)
[build]       app::GifEncoder::~GifEncoder() in libapp-lib.a[216](gif_format.cpp.o)
[build]   _GifLastError, referenced from:
[build]       app::GifDecoder::readFrameIndexedImage(gfx::RectT<int> const&) in libapp-lib.a[216](gif_format.cpp.o)
[build]   _MakeMapObject, referenced from:
[build]       app::GifDecoder::getFrameColormap() in libapp-lib.a[216](gif_format.cpp.o)
[build]       app::GifEncoder::createColorMap(doc::Palette const*) in libapp-lib.a[216](gif_format.cpp.o)
[build]       app::GifEncoder::createColorMap(doc::Palette const*) in libapp-lib.a[216](gif_format.cpp.o)
[build] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[build] ninja: build stopped: subcommand failed.
[proc] The command: /opt/homebrew/bin/cmake --build /Users/wizz/Downloads/art/LibreSprite/build --config MinSizeRel --target all -- exited with code: 1

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash

* System: Windows/macOS/Linux, version, distribution
*MacOS Sonoma 14.0 M1 Pro

**Comment by dacap** [comment]
`bin/libresprite`? wrong repo, closing this issue
