### ISSUE TITLE
Add option to disable snapping brush preview

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4137]
With #3743 now the brush preview is snapped to the grid which might be confusing. We should have an option to disable that behavior (and probably that option should be enabled by default, to have the previous behavior by default, snap when we click).

**Comment by Gasparoken** [comment]
I've been thinking about this and I should mention that some confusion can occur when:
- `Snap to Grid` is on and
- `Edges only` or `Full Preview and Edges` is active in _Preferences > Cursors_
In this way, the cursor is a tiny pixel that is difficult to track with the naked eye.

**Comment by dacap** [comment]
Requested by one user today too: https://steamcommunity.com/app/431730/discussions/0/3975051032841934719/?tscn=1700065907

I'm thinking about a *Edit > Preferences > Cursor > Respect Snap to Grid option* (disable by default)

**Comment by berarma** [comment]
I was going to open an issue because the brush preview doesn't snap. It's counter-intuitive and confusing, I'd expect the brush to paint where the preview is shown. I thought I would leave a comment here instead, in case you want to consider changing the default in the future.
