### ISSUE TITLE
Tons of compiler warnings, but build successful

### ISSUE THREAD

**Issue by tilkinsc** [aseprite/aseprite#4138]
Describe your bug report or feature request here

Tons of warnings are emitted for compiling aseprite using MSVS.

```batch
git clone --recurse-submodules https://github.com/aseprite/aseprite
cmake -DCMAKE_BUILD_TYPE=Release -DLAF_BACKEND=skia -DSKIA_DIR=C:\code\skia -DSKIA_LIBRARY_DIR=C:
\code\skia\out\Release-x64 -DSKIA_LIBRARY=C:\code\skia\out\Release-x64\skia.lib -G Ninja ..
ninja -j24 aseprite
```
[warnings.txt](https://github.com/aseprite/aseprite/files/13352091/warnings.txt)

### Aseprite and System version

* Aseprite version: https://github.com/aseprite/aseprite/commit/f92f14f261814f89638763359ceb3d8855c75027
* System: Windows 10
* Compiler: MSVS

**Comment by dacap** [comment]
Hi @tilkinsc, this is a known issue. Most warnings are from third party libraries, but some warnings are still from our side. They are fixed gradually in the same development process.
