### ISSUE TITLE
strings typo?

### ISSUE THREAD

**Issue by TakWolf** [aseprite/aseprite#4148]
https://github.com/aseprite/aseprite/blob/1311944667c4ceb8338278b8817e3a5928a6c465/data/strings/en.ini#L62
 
```
||&OK||&Cancel"
```

**Comment by dacap** [comment]
Hi @TakWolf, actually this syntax gives the chance to create two buttons (`"||first button||second button"`), one with the "OK" label (with the <kbd>O</kbd> key as a shortcut, that's why it says `"&O"`), and other button with the "Cancel" label (with the <kbd>C</kbd> shortcut due `"&C"`).

**Comment by TakWolf** [comment]
I am referring to the double quotation mark on the far right, which seems redundant.

Because all third-party translations retain this character, I am not sure. Like:
https://github.com/FabianoIlCapo/aseprite_italian/blob/master/data/it.ini#L57C1

**Comment by dacap** [comment]
Oh you are right @TakWolf, I'll fix that 👍  thanks for pointing it out.
