### ISSUE TITLE
Unable to build aseprite on win 10

### ISSUE THREAD

**Issue by fullceyy** [aseprite/aseprite#4149]
C:\aseprite\build>cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x64 -DSKIA_LIBRARY=C:\deps\skia\out\Release-x64\skia.lib -G Ninja ..
CMake Deprecation Warning at CMakeLists.txt:19 (cmake_policy):
  The OLD behavior for policy CMP0046 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- The CXX compiler identification is MSVC 19.38.33130.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:60 (message):
  The C++ compiler

    "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: 'C:/aseprite/build/CMakeFiles/CMakeScratch/TryCompile-getjkk'

    Run Build Command(s): C:/PROGRA~1/CMake/bin/ninja.exe -v cmTC_10813
    [1/2] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /GR /EHsc  /D_DEBUG /MTd /Zi /Ob0 /Od /RTC1 -std:c++17 -MTd /showIncludes /FoCMakeFiles\cmTC_10813.dir\testCXXCompiler.cxx.obj /FdCMakeFiles\cmTC_10813.dir\ /FS -c C:\aseprite\build\CMakeFiles\CMakeScratch\TryCompile-getjkk\testCXXCompiler.cxx
    [2/2] C:\Windows\system32\cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_10813.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x86\mt.exe --manifests  -- C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx86\x86\link.exe /nologo CMakeFiles\cmTC_10813.dir\testCXXCompiler.cxx.obj  /out:cmTC_10813.exe /implib:cmTC_10813.lib /pdb:cmTC_10813.pdb /version:0.0 /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    FAILED: cmTC_10813.exe
    C:\Windows\system32\cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_10813.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x86\mt.exe --manifests  -- C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx86\x86\link.exe /nologo CMakeFiles\cmTC_10813.dir\testCXXCompiler.cxx.obj  /out:cmTC_10813.exe /implib:cmTC_10813.lib /pdb:cmTC_10813.pdb /version:0.0 /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx86\x86\link.exe /nologo CMakeFiles\cmTC_10813.dir\testCXXCompiler.cxx.obj /out:cmTC_10813.exe /implib:cmTC_10813.lib /pdb:cmTC_10813.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_10813.dir/intermediate.manifest CMakeFiles\cmTC_10813.dir/manifest.res" failed (exit code 1112) with the following output:
    CMakeFiles\cmTC_10813.dir\testCXXCompiler.cxx.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:34 (project)

-- Configuring incomplete, errors occurred!

Windows 10, I would be grateful if someone helps me out!

**Comment by TakWolf** [comment]
>  fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'

Do you compile on x86 machines？

**Comment by Tampa-26** [comment]
I am on x64 machine and am having the same problem.

**Comment by fullceyy** [comment]
> > fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'
> 
> Do you compile on x86 machines？

no I did it on x64

**Comment by fullceyy** [comment]
> I am on x64 machine and am having the same problem.

Hey Tampa-26 did you manage to fix it? I fixed it by just deleting aseprite and redoing steps like call for msvc and then "cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x64 -DSKIA_LIBRARY=C:\deps\skia\out\Release-x64\skia.lib -G Ninja .." I don't know what was wrong the last time but know everything works.
