### ISSUE TITLE
Option to change in-progress selection outline

### ISSUE THREAD

**Issue by lunathir** [aseprite/aseprite#4155]
As title states, an option to change in-progress selection from the following when selecting something to a marching ants-style selection thing. Image below is using selection tool but I feel as if it gives bad feedback.
![image](https://github.com/aseprite/aseprite/assets/18320914/e842942c-b73f-4eb9-b6fc-40200bce5c0b)

**Comment by dacap** [comment]
Hi @lunathir, probably duplicated of #2852?

**Comment by lunathir** [comment]
Seems to be at least a partial duplicate, yeah. Apologies for that.

**Comment by dacap** [comment]
No problem 👍
