### ISSUE TITLE
Incorrect GUI button measurement.

### ISSUE THREAD

**Issue by TakWolf** [aseprite/aseprite#4160]
Most noticeable when using Russian (Русский) language.

Language download from:
https://github.com/aseprite-quest/aseprite-unified-languages/releases/tag/0.0.1
or
https://github.com/lufog/aseprite-language-russian/releases/tag/v1.3-rc8

-----------------------------

The theme basically uses the default theme, but replaces the fonts.

## Unified Pixel Theme

https://github.com/aseprite-quest/aseprite-unified-pixel-theme/releases/tag/0.0.2

![image](https://github.com/aseprite/aseprite/assets/6064962/35e3bd91-0c34-4fc7-ae54-26e415bcbd75)

## Default Theme but replace fonts that gets from here

https://github.com/lufog/aseprite-language-russian/tree/1.2/data/fonts

[aseprite-theme-ru.aseprite-extension.zip](https://github.com/aseprite/aseprite/files/13421227/aseprite-theme-ru.aseprite-extension.zip)

![image](https://github.com/aseprite/aseprite/assets/6064962/3b9d7abc-b536-4c8b-8f1b-4a9ca8c7fc22)

**Comment by dacap** [comment]
Thanks for this bug report @TakWolf, there are several instances of this same problem, I'll push a fix just in a moment.
