### ISSUE TITLE
Crash starting Aseprite on macOS

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4162]
It's highly probable that if we receive a bug report/user support request about Aseprite not starting on macOS it's due some incompatibilities between Xcode/SDK/last macOS supported version. We should ask about the macOS/Mac OS X version that they are running, because it looks like Xcode 14 removed support for macOS 10.9:

https://developer.apple.com/forums/thread/714572

Or it can be related to a new linker introduced in Xcode 15:

https://developer.apple.com/forums/thread/736203

EDIT: Related tickets/posts:
* https://igarastudio.zendesk.com/agent/tickets/5417
* https://igarastudio.zendesk.com/agent/tickets/5424
* https://igarastudio.zendesk.com/agent/tickets/5428
* https://steamcommunity.com/app/431730/discussions/0/3975051032839700063/

**Comment by joshbackstein** [comment]
Not sure if it's helpful or not, but it's crashing on startup for me.
- macOS 11.7.10
- Aseprite v1.3 rc8 from Humble Bundle

**Comment by dacap** [comment]
Hi @joshbackstein, could you please try running Aseprite from a Terminal with the following command:

    open -a Aseprite

And see what is the output in the Terminal. If that doesn't work, you could try:

    /Applications/Aseprite.app/Contents/MacOS/aseprite

**Comment by joshbackstein** [comment]
@dacap I just get a segfault:

`zsh: segmentation fault  /Applications/Aseprite.app/Contents/MacOS/aseprite`

**Comment by dacap** [comment]
@joshbackstein would you mind to check if there is a crash report related to aseprite in the macos console: https://support.apple.com/guide/console/reports-cnsl664be99a/mac

**Comment by joshbackstein** [comment]
@dacap Here you go: [aseprite-crash-dump-2023-11-21.txt](https://github.com/aseprite/aseprite/files/13432484/aseprite-crash-dump-2023-11-21.txt)

**Comment by dacap** [comment]
Thanks for the report @joshbackstein, we've received similar bug reports and it might be possible that it's related to this: https://developer.apple.com/forums/thread/736203

Would you mind to contact me at support@aseprite.org (name this issue 4162), we might be able to send you a fix.

**Comment by joshbackstein** [comment]
@dacap Just sent the email

**Comment by dacap** [comment]
Thanks for the help @joshbackstein!

Closing this issue as it was confirmed that we've found the fix and it's related to https://developer.apple.com/forums/thread/736203 (internal note: adding `-Wl,-ld_classic` to the linker fixed it)
