### ISSUE TITLE
Error in .ase file spec

### ISSUE THREAD

**Issue by EmperorPenguin18** [aseprite/aseprite#4169]
I'm writing some code to load .aseprite files in my game engine, and I've found an error in the spec. The header does not actually have 84 bytes at the end for future, it has 80.

**Comment by dacap** [comment]
Hi @EmperorPenguin18, actually the header has 128 bytes. At the end 84 extra padding bytes.

```
4 DWORD
2 WORD
2 WORD
2 WORD
2 WORD
2 WORD
4 DWORD
2 WORD
4 DWORD
4 DWORD
1 BYTE
3 BYTE[3]
2 WORD
1 BYTE
1 BYTE
2 SHORT
2 SHORT
2 WORD
2 WORD
84 BYTE[84]

128 = 4+2+2+2+2+2+4+2+4+4+1+3+2+1+1+2+2+2+2+84
```
