### ISSUE TITLE
Cursor offset when moving the selection depending on the initial point of drag

### ISSUE THREAD

**Issue by martincapello** [aseprite/aseprite#4175]
When moving a selection we can see that the mouse pointer has an offset when the position of the cursor is minor than the initial position where the pixel was dragged.

To reproduce:
1) Zoom in to like 1600% to make things easier to see.
2) Select one pixel at position (x,y).
3) Drag the pixel in a point closer to the top left corner (if you drag it from the oposite corner, the following behavior is inverted). Remember that we are at 1600% zoom, so the pixel is a big square that you can drag from any point inside it. With "closer to the top left corner" I mean that it can be any point on the top left quadrant of the selected pixel. 
4) Try to move the selection to (x-1,y) or (x,y-1), you will see that the selection moves after the cursor passed half the pixel in the intended new positions. Compare this trying to move the selection to (x+1,y) or (x, y+1), you will the selection going to the new position immediately when the cursor is hovering the new position.

Reference: https://discord.com/channels/324979738533822464/348146938530496513/1178993923167895574

### Aseprite and System version
* Aseprite version: 1.3 any flavor (checked also that this happens in 1.3-rc9)

**Comment by dacap** [comment]
From the discord discussion I'm copying my message:

there is a commit from @gasparoken that might have fixed this, but was later reverted (the commit fixed two things and both things then were reverted): https://github.com/aseprite/aseprite/commit/456113d015d57c2916e833ee5a1bfee09c0e8739, reverted here https://github.com/aseprite/aseprite/commit/a27ea04f7d84fff7b23dbe5e09fb21094186cca3, one of the fixes (about fine control) was re-implemented https://github.com/aseprite/aseprite/commit/cbe14089afb89cb0c33869334a891f6d8995b597
but I'm not sure if the other fix was related to this issue
