### ISSUE TITLE
Some positions cannot be translated locally

### ISSUE THREAD

**Issue by 66six11** [aseprite/aseprite#4189]
This is a translation of en.ini with reference to aseprite1.3.1, used in aseprite1.3.1

1.preference 》》edit
<img width="491" alt="屏幕截图 2023-12-01 133142" src="https://github.com/aseprite/aseprite/assets/142090288/89aada22-a334-42c7-8b56-a0e95f41643b">

2.tool
parameters to save
<img width="335" alt="屏幕截图 2023-12-01 124655" src="https://github.com/aseprite/aseprite/assets/142090288/3e8e6b64-8733-4874-a675-2033c2b0b513">

perfect-pixel tip（Perfect-Pixel   This can be translated locally, I just didn't translate it）
<img width="192" alt="屏幕截图 2023-12-01 130251" src="https://github.com/aseprite/aseprite/assets/142090288/1ad4d67f-e285-457b-acbb-edda08f172cd">

Rectangle Marquee tool
tip
<img width="126" alt="屏幕截图 2023-12-01 130337" src="https://github.com/aseprite/aseprite/assets/142090288/8d071da0-525d-470b-b74f-66fade74dcc7">
<img width="169" alt="屏幕截图 2023-12-01 130330" src="https://github.com/aseprite/aseprite/assets/142090288/3c488dc2-7cdf-47cf-91b9-091c618e9368">
<img width="137" alt="屏幕截图 2023-12-01 130319" src="https://github.com/aseprite/aseprite/assets/142090288/588dc52c-f4d4-4998-85ad-4980664a77aa">
<img width="158" alt="屏幕截图 2023-12-01 130312" src="https://github.com/aseprite/aseprite/assets/142090288/06b2aadd-f544-4fa2-acf2-c2eb364d7af7">

Paint Bucket tool
tolerence
<img width="138" alt="屏幕截图 2023-12-01 130914" src="https://github.com/aseprite/aseprite/assets/142090288/6da9fe0d-2380-4e26-a6c0-5010c9e13305">

opacity
<img width="205" alt="屏幕截图 2023-12-01 125122" src="https://github.com/aseprite/aseprite/assets/142090288/1317daa2-c2fd-464d-8489-1aa7285eb4dd">

**Comment by 66six11** [comment]
When using Windows Chinese input method can not input text, hope to fix this problem in the later version, this is very important to us, thank you very much

**Comment by dacap** [comment]
Hi @66six11 thanks for reporting this, I think all these issues were fixed with e87fdbb3af86680553a348b9a55c217fef8c7d55, sorry that I missed this one and implemented the fix as #4237 (both list the same problems).
