### ISSUE TITLE
[Weblate] Some sentences cannot be searched

### ISSUE THREAD

**Issue by TakWolf** [aseprite/aseprite#4208]
The total number of sentences should be: 1614 (include '[_]display_name')
Actual statistics on weblate: 1606

Missing sentences count is: 8

```
[color_bar]
remap_palette = Remap Palette
remap_palette_tooltip = Matches old indexes with new indexes
remap_tiles = Remap Tiles
remap_tiles_tooltip = Matches old tiles with new tiles

[commands]
RemoveFrame = Remove Frame
RemoveFrameTag = Remove Tag
RemoveLayer = Remove Layer
RemoveSlice = Remove Slice
```

But these 8 sentences do exist in strings.

Raise to: https://github.com/WeblateOrg/weblate/issues/10561

**Comment by dacap** [comment]
It looks like this is finally fixed, e.g. https://hosted.weblate.org/translate/aseprite/aseprite/en/?q=remap_palette+&sort_by=-priority%2Cposition&checksum= thanks for reporting this to weblate @TakWolf 👍
