### ISSUE TITLE
Linux Arch, native file dialog feature doesnt use native file dialog

### ISSUE THREAD

**Issue by IThundxr** [aseprite/aseprite#4209]
Describe your bug report or feature request here
Currently enabling the use native file dialog feature doesn't work, would it be possible for it to be fixed/a way to force aseprite to use the native file dialog? I usually have to go through multiple directories to get to where my art stuff is stored so being able to just paste the location to my holder really helps ^^

### Aseprite and System version

* Aseprite version: latest steam version
* System: Linux, Arch latest, gnome

**Comment by dacap** [comment]
Hi @IThundxr, to use the native file dialog on Linux you need the `zenity` CLI utility installed.

**Comment by IThundxr** [comment]
> Hi @IThundxr, to use the native file dialog on Linux you need the `zenity` CLI utility installed.

Thanks, Installed zenity however now im getting a pretty weird error

```
❯ /home/ithundxr/.local/share/Steam/steamapps/common/Aseprite/aseprite
fish: Job 1, '/home/ithundxr/.local/share/Ste…' terminated by signal SIGSEGV (Address boundary error)
```

seems aseprite doesnt wanna open at all, is there any debug flag i can enable to make it output some more info?

**Comment by IThundxr** [comment]
[Aseprite-v1.3.2-x64-DebugOutput.txt](https://github.com/aseprite/aseprite/files/13655402/Aseprite-v1.3.2-x64-DebugOutput.txt) The debug log from adding -debug

**Comment by Goury** [comment]
@dacap open it back.
Ubuntu 24.04, every library and utility required is installed, aseprite just ignores the setting

**Comment by SeniorMatt** [comment]
> [@dacap](https://github.com/dacap) open it back. Ubuntu 24.04, every library and utility required is installed, aseprite just ignores the setting

Same goes for me on Arch.
