### ISSUE TITLE
Improving the Cyrillic font

### ISSUE THREAD

**Issue by ElderlyGlek** [aseprite/aseprite#4212]
A few months ago, in #3797, I improved the Cyrillic font a bit, but I was still not satisfied with the final result… So my friend and I (this time I asked my friend for help to achieve a better result) improved the Cyrillic font to make it look better and more readable:

![aseprite_font](https://github.com/aseprite/aseprite/assets/69088106/3ab34aa8-339a-44a9-8884-81a89415c956)

I also fixed the spaces in the following characters: "," ":" "?" "»" "˲".

And I hope you will add these changes in the next versions of Aseprite, the improved Cyrillic font will look good with future translations.

**Comment by dacap** [comment]
Thanks @ElderlyGlek, I'll integrate these changes, I can see that some chars are wider now 👍
