### ISSUE TITLE
Stabilizer should be off when freehand drawing + Shift key pressed

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#4217]
While creating a straight line from the last point to the cursor position, the stabilizer must be disabled.

Reported: https://community.aseprite.org/t/stabilizer-stabilizing-things-it-shouldnt/20889

### Aseprite and System version

* Aseprite version: 1.3.2

**Comment by belchiorg** [comment]
Hello guys! I'd like to help solving this bug, could I be assigned to this issue?

**Comment by dacap** [comment]
Hi @belchiorg, sure, it'd be great if you can give a try to this :+1:
