### ISSUE TITLE
theme.xml，the text contact id is incorrect

### ISSUE THREAD

**Issue by 66six11** [aseprite/aseprite#4225]
aseprite 1.3.2
<img width="237" alt="image" src="https://github.com/aseprite/aseprite/assets/142090288/2a73cedb-4ae7-496b-ba91-5e340e41fdcc">
Change its color should be
<img width="247" alt="image" src="https://github.com/aseprite/aseprite/assets/142090288/80e0fd34-006a-452a-9a48-f89d9b4f1d94">
But the truth is
<img width="259" alt="屏幕截图 2023-12-14 222142" src="https://github.com/aseprite/aseprite/assets/142090288/b4ecb529-6e6c-44c0-ac48-24f099589561">
Causes the color to change elsewhere

**Comment by dacap** [comment]
Hi @66six11, at the moment we are using `editor_face` as background and `face` as foreground but probably we might require a new style for this widget (so a theme can specify new colors for these elements).

**Comment by 66six11** [comment]
face，It will change here
<img width="985" alt="屏幕截图 2023-12-14 224544" src="https://github.com/aseprite/aseprite/assets/142090288/1bf984ad-6c42-4713-b24a-6eb2dd1a28b8">

**Comment by dacap** [comment]
@66six11 we've [just added](https://github.com/aseprite/aseprite/commit/96ef977311a678f0e34f43fecd38b381721ce336) a new "shade_empty" style (in the default light theme will use the "face" color for text, but in dark theme "status_bar_text" will be used, anyway each theme will be able to use any color here).
