### ISSUE TITLE
In en.ini strings, inconsistent use of  single and double quotation marks

### ISSUE THREAD

**Issue by TakWolf** [aseprite/aseprite#4233]
https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/data/strings/en.ini#L36

https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/data/strings/en.ini#L75

https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/data/strings/en.ini#L106

**Comment by dacap** [comment]
Thanks @TakWolf, just fixed, we'll use "..." in English, but the quotes can be changed depending on the specific language.
