### ISSUE TITLE
Add i18n support for hardcoded strings

### ISSUE THREAD

**Issue by Cetaceaqua** [aseprite/aseprite#4237]
The current version of Aseprite still has a lot of hardcoded strings which cannot be translated in localization, please consider fixing these issues.

The screenshot shows Aseprite with 100% translated Simplified Chinese localization, making it easy to spot English strings that cannot be translated.

## Exist ini keys and values, but not used

The corresponding i18n ini keys and values exist for text displayed in the following user interface, but are not shown.

1. Tool tip of Pixel-Perfect option in context bar.

   ![image](https://github.com/aseprite/aseprite/assets/46396590/9977879e-03da-4f67-a44b-797a6bb28c40)

   https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/ui/context_bar.cpp#L2607-L2609

   

   Correct code should be:

   ```cpp
   tooltipManager->addTooltipFor(m_freehandAlgo, key_tooltip(Strings::context_bar_freehand_trace_algorithm().c_str(), CommandId::PixelPerfectMode()), BOTTOM);
   ```

2. Tool tip of Contiguous option in context bar.

   ![image](https://github.com/aseprite/aseprite/assets/46396590/bfbd58a9-8563-4c08-bbe1-2b69919f8ccc)

   https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/ui/context_bar.cpp#L2610-L2612

   Correct code should be:

   ```cpp
   tooltipManager->addTooltipFor(m_contiguous, key_tooltip(Strings::context_bar_contiguous_fill().c_str(), CommandId::ContiguousFill()), BOTTOM);
   ```

## Ini key and value do not exist, need to be added

The text displayed in following user interface does not have corresponding i18n ini keys and values, and need to be added.

1. ![image](https://github.com/aseprite/aseprite/assets/46396590/773efa3f-d997-4f9b-8e97-2e8c1dbaf27a)

   https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/ui/context_bar.cpp#L414-L415

2. ![image](https://github.com/aseprite/aseprite/assets/46396590/4ececa93-b7b3-456e-977c-e122d13a6a4e)

   https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/ui/context_bar.cpp#L1857

3. ![image](https://github.com/aseprite/aseprite/assets/46396590/24f689cc-e2df-4d4a-af65-c0fdb9cfbd6b)

   https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/ui/context_bar.cpp#L1866

4. ![image](https://github.com/aseprite/aseprite/assets/46396590/0b930e9a-935d-412e-b795-4dd8b25031ea)

   https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/ui/context_bar.cpp#L1875

5. ![image](https://github.com/aseprite/aseprite/assets/46396590/b28f8325-f5c3-40db-b21f-664dad77c76d)

   https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/ui/context_bar.cpp#L1435-L1445

6. ![image](https://github.com/aseprite/aseprite/assets/46396590/7d6d160a-362d-4a01-84bd-b5e0fef91522)

   https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/ui/selection_mode_field.cpp#L38-L48

7. ![image](https://github.com/aseprite/aseprite/assets/46396590/d56816e6-6906-423b-9cdf-e430fd2b8e5b)

   https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/ui/brush_popup.cpp#L293

8. ![image](https://github.com/aseprite/aseprite/assets/46396590/9f07f922-7707-4eb4-87bf-e78ca9b9ccb2)

   https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/ui/sampling_selector.cpp#L21-L29

9. ![image](https://github.com/aseprite/aseprite/assets/46396590/b278f116-9130-4d9b-9cd0-450cf5d286bb)

   https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/commands/cmd_new_frame.cpp#L183-L186

**Comment by dacap** [comment]
Thanks @Cetaceaqua to find out these ones, I'll try to push a fix today 👍

**Comment by Cetaceaqua** [comment]
I'm embarrassed to find that issue [#4189](https://github.com/aseprite/aseprite/issues/4189) contains almost the same content as the current issue, please close it too, thanks! ❤ @dacap

**Comment by dacap** [comment]
No problem @Cetaceaqua, I forgot about #4189, I'll take a look to that issue too just to check if something is missing.
