### ISSUE TITLE
Lagging on macOS, possible memory leak

### ISSUE THREAD

**Issue by bejd** [aseprite/aseprite#4251]
Aseprite lags after being open a long time (a few days). Tool use becomes extremely laggy, in particular marquee, pencil, and eraser tools. Closing and re-opening the app fixes.

Seems to be a memory leak, may be related to #3592. I only have one simple project open: canvas size 256x144, 6 layers (regular and tilemaps).

Shortly after opening:
<img width="1072" alt="Screenshot 2023-12-26 at 17 59 25-r" src="https://github.com/aseprite/aseprite/assets/55742919/b9dcb764-cbda-476b-97b3-de967b33d670">

4 days of being open, light usage:
<img width="1072" alt="Screenshot 2023-12-30 at 10 58 16-r" src="https://github.com/aseprite/aseprite/assets/55742919/a72c3555-1fd5-4250-a413-e0764d1b1727">

### Aseprite and System version

* Aseprite v1.3.2-arm64 (via Steam)
* System: macOS Sonoma 14.2 (23C64)

**Comment by dacap** [comment]
Possible fix for this memory leak after including this change: https://github.com/dacap/clip/commit/1d5d20cefbe388b3cde285a4ec61114238d3fa70

**Comment by dacap** [comment]
The fix should be already available in v1.3.7, closing this issue but feel free to reopen or comment if you or other users are experiencing this lag/memory leak.
