### ISSUE TITLE
WEBP_LIBRARIES set to NOTFOUND (Linux)

### ISSUE THREAD

**Issue by GogiBoy102** [aseprite/aseprite#4255]
Everything goes well from cloning aseprite to downloading the pre-compiled Skia m-102.
However whenever i try to compile it with 
`cd aseprite
mkdir build
cd build
export CC=clang
export CXX=clang++
cmake \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
  -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
  -DLAF_BACKEND=skia \
  -DSKIA_DIR=$HOME/deps/skia \
  -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
  -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
  -G Ninja \
  ..
ninja aseprite`  
it just doesn't work and instead shows 
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WEBP_LIBRARIES
    linked by target "app-lib" in directory /home/jeebak/aseprite/src/app

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
`
I cant give the full output as it says that the body is too long

### Aseprite and System version

* Aseprite version: m-102
* System:  Linux Mint 21.2 x86_64

**Comment by yathxyz** [comment]
Since you closed this, have you solved it?
