### ISSUE TITLE
Countour Tool: pixel perfect doesnt work after a straight line

### ISSUE THREAD

**Issue by EthanHunt404** [aseprite/aseprite#4256]
this is an old issue regarding the countour tool, Its quite simple if you try doing a straight line with the shift key and continue after the pixel perfect feature stops working

Steps to recreate:
- create a new document, any size, any color mode;
- select the coutour tool(shortcut D);
- draw a pixel anywere in the canvas, thats point A;
- hold shift, aseprite will preview the line from point A to whatever other pixel your mouse in hovering;
- press to confirm whenever you want but dont stop, immediatly start dragging it to continue drawing with the countour tool, you can stop holding shift now, it doesnt change whats happening
its at this point the bug shows itself.

### Aseprite and System version

* Aseprite version: 1.3.2, Steam version
* System: Windows 10 amd graphics card.

**Comment by EthanHunt404** [comment]
1.3.2 behavior
https://www.loom.com/share/2588d1d2563c41a893680bef38944743
1.2.40 behavior
https://www.loom.com/share/aff49720730845aab15ac66b78ce32c0

i believe this happens ever since the start of 1.3 betas on steam too.

**Comment by Gasparoken** [comment]
Thanks for reporting this. I was able to reproduce it.

**Comment by EthanHunt404** [comment]
i just wanna say that the fix mister @Gasparoken proposed is working wonders, i compiled aseprite myself with the changes he proposed and it absolutely worked, not only countour tool, but the Pen and Eraser also were fixed.

**Comment by EthanHunt404** [comment]
why did you reopen this @dacap?

**Comment by EthanHunt404** [comment]
hey i want to comment on this again, im not sure why this has been moved to another milestone, the fix was suitable and it didnt seen to cause any other unintended effects, im relly invested on this specifically, cause its one of the main reasons i bought aseprite way back when, and it heavily hinders work, so i wanted to hear a reason to not implement what mr. @Gasparoken proposed.
