### ISSUE TITLE
Error while trying to Compile aseprite and execute "cmake" command

### ISSUE THREAD

**Issue by JoeMcFlow** [aseprite/aseprite#4267]
### -Issue
I am fairly new to compiling source code into something readable for the computer and am having trouble compiling aseprite. My issue is that after downloading the dependencies (CMake) (Ninja) (aseprite-m102). I try to compile aseprite using cmake. I have various different subdirectories in my Home (main directory). Including an aseprite directory, cmake directory, ninja directory, and skia directory. 

These are all downloaded seperate from one another and are not connected in any way. I am including this piece of information in case this might be useful.

### -Folder Structure
My folder structure looks something like this-

Home (main)-
|-aseprite |    | -cmake  |  | -ninja |  |  -skia |
--build

As you can see all of these subdirectories are located in the home directory. Although they are not connected. Besides "aseprite" and "build"

--(back to the issue)--
Now inside of the aseprite directory I have created an additional directory called "build" as per the recommendations in the docs. Upon executing the command below in the empty subdirectory "build":

`       cmake -G Ninja -DLAF_BACKEND=skia ..      `

I recieve this error message:

`CMake Error at laf/CMakeLists.txt:86 (message):
  set SKIA_DIR/SKIA_LIBRARY/SKIA_LIBRARY_DIR to compile w/skia backend  `

as well as the message: "Configuring incomplete, errors occurred!"
How do i solve this problem and compile aseprite?

### System version
* System: Trying to compile on a Fedora (workstation 39) based linux system.

**Comment by AndreiSva** [comment]
same issue here

**Comment by AndreiSva** [comment]
I think this is supposed to fix it: https://github.com/aseprite/skia#skia-on-linux

**Comment by JoeMcFlow** [comment]
The solution in that thread did not work for me. Did it work for you? Or do you still have the issue?

**Comment by JoeMcFlow** [comment]
Yeaaa, nevermind the solution in that github thread is correct. It worked for me, I just implemented the steps wrong. Thanks!
