### ISSUE TITLE
Nested tag with "Ping-Pong" repeat mode causes weird behaviors in Parent tag with any repeat mode

### ISSUE THREAD

**Issue by HeyItsLollie** [aseprite/aseprite#4271]
[Tag Repeat Bug.zip](https://github.com/aseprite/aseprite/files/13973733/Tag.Repeat.Bug.zip)

In the gif below, I have two animations built out of nested tags. In the first animation, both tags have "Forward" repeat. In the second animation, the parent tag has "Forward" repeat, while the nested tag has "Ping-Pong" repeat.

The first animation repeats correctly, but the second animation skips the first frame.
![2024-01-18 - 19-02-07](https://github.com/aseprite/aseprite/assets/30498581/906fca60-8e0c-43dd-96d3-dbd983f627ba)

A Nested tag with "Ping-Pong" repeat will also cause a Parent tag with "Ping-Pong" or "Ping-Pong Reverse" repeat to break.
(Curiously, a Parent tag with "Reverse" repeat will play without issue.)

### Aseprite and System version
Aseprite v1.3.2-x64, Windows 11.

**Comment by Gasparoken** [comment]
Thanks for this report @HeyItsLollie! I was able to reproduce it easily thanks to your attachment.
