### ISSUE TITLE
Delete this repository or relicense to not be a trap

### ISSUE THREAD

**Issue by keiyakins** [aseprite/aseprite#4283]
The "EULA.txt" file prohibits reverse engineering it, which would include reading the source. Putting up a repository which *even reading* is a crime is, frankly, evil. I'm assuming it was done in ignorance, not malice,  but please rectify the situation immediately.

**Comment by tomdoeslinux** [comment]
Where does it say this? Reading something does not equal 'reverse engineering'. Reverse engineering usually involves replicate its functionality, it's not the same as reading which involves understanding and gaining knowledge from existing content.

And, there's nothing evil about EULAs. If a developer has spent lots of time working on a piece of software and they want to protect it, that's fine by me.

**Comment by keiyakins** [comment]
> You may not reverse engineer, decompile, or disassemble the SOFTWARE PRODUCT, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation.

Reading and understanding the code is literally what reverse engineering means. Sure, you usually have to start from a binary, but forming a picture of how the thing works is the defining aspect, not the specific tools and methods.

**Comment by dacap** [comment]
The reverse engineering clause is for the official binaries only, this is to protect in some way some keys that might be included in the official release (and not in the source code), e.g. Sentry API keys.
