### ISSUE TITLE
Export tags issues

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4297]
To continue the work from #4211 to fix #4173, there are some missing tasks to implement/fix:

- [x] Add CLI argument to save playing subtags/repeats
   - [x] Add tests 
- [x] Add new parameter to SaveFile command to enable/disable the subtags/repeats field
- [x] Fix exporting one tag without "play/repeats" and changing its anidir

**Comment by martincapello** [comment]
Do you have any name in mind for the parameter to play subtags and repetitions?
--subtags-repeats
--play-subtags-repeats
--with-subtags-repeats
--include-subtags-repeats
--play-subtags-and-repetitions
--play-subtags (and clarify in the description that it also includes repetitions)

Any other?
