### ISSUE TITLE
Invalid chunk ASE_FILE_CHUNK_FLI_COLOR2

### ISSUE THREAD

**Issue by redbug26** [aseprite/aseprite#4322]
Chunk ASE_FILE_CHUNK_FLI_COLOR2 is invalid when palette > 256

https://github.com/aseprite/aseprite/blob/d70801e88b997831abd16d7d4e58e9d39ee66aa3/src/app/file/ase_format.cpp#L679

**Comment by dacap** [comment]
Thanks for reporting this bug @redbug26, I think the best thing to do in this case is not to write the color2 chunk at all (as it's only there for backward compatibility with older versions of Aseprite and we generally use the palette chunk that does't have this issue).
