### ISSUE TITLE
Mouse scroll zoom sensitivity is off

### ISSUE THREAD

**Issue by nuclearsecrecy** [aseprite/aseprite#4327]
When I use a mouse with a scroll wheel to zoom, it jumps in massive increments. One "click" of the zoom goes from 8.3% to to 6400% and vice versa. System settings for mouse wheel sensitivity have no impact (setting them to lowest does not change this behavior).

### Aseprite and System version

* Aseprite version: v1.3-rc4-arm64
* System: Mac 14.3

I have tried this with two different USB mice from two different vendors, with identical behavior. The mice otherwise behave as expected.

**Comment by Gasparoken** [comment]
Thanks @nuclearsecrecy. This is a known issue: https://github.com/aseprite/aseprite/issues/3171.
