### ISSUE TITLE
Some JPG files are loaded with incorrect orientation

### ISSUE THREAD

**Issue by JDoucette** [aseprite/aseprite#4332]
Repro:
- take pictures with your phone, be sure to take some at angles that may cause the orientation settings in JPG to be set abnormally
- load JPG in Aseprite and in a normal image loading app
- note that Aseprite will not respect the orientation flag, and show the image rotated 180° or other.

### Aseprite and System version

* v1.3.4
* Windows 11

**Comment by JDoucette** [comment]
![alienware_m18_r2_keyboard](https://github.com/aseprite/aseprite/assets/1381969/f3921dc2-f877-4a12-b005-7ca5ea8be283)

Example image.

**Comment by JDoucette** [comment]
Result:

![aseprite_1 3 4_180_degrees](https://github.com/aseprite/aseprite/assets/1381969/604ce91f-7d42-4347-8757-cebbf138e0bd)

**Comment by Gasparoken** [comment]
Thanks for reporting this. I was able to reproduce it.

**Comment by Gasparoken** [comment]
It will be closed as it is a duplicate of https://github.com/aseprite/aseprite/issues/2525
