### ISSUE TITLE
Crashing segfault when calling: app.command.CloseFile() or app.command.GotoPreviousTab() , in --batch mode

### ISSUE THREAD

**Issue by jestarray** [aseprite/aseprite#4352]
https://github.com/aseprite/aseprite/assets/34615798/ce986c7d-aaba-45fb-a850-30ab0bf3b827

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
    - v1.3 master branch
    - commit: `73fe8099d96479364f92ff6317a5687498d43d36`
* System: Arch Linux

lua script:
```lua
-- these aren't the problem but are included to simulate my big script that has this issue in case.
--app.open(app.activeSprite.filename)
--app.open(app.activeSprite.filename)

-- running either of these in batch mode segfaults!
--app.command.GotoPreviousTab()
app.command.CloseFile()
--app.command.GotoNextTab()
--app.command.CloseAllFiles()
```

command:
```
aseprite image.png --script "test_crash.lua" --batch
```

NOTE: It crashes even without the `app.open()` calls but I included it in there because I have a big script that opens 3-4 tabs so I thought it was a memory limit issue.

**Comment by Gasparoken** [comment]
Thank you @jestarray. I was able to reproduce it easily with your files and clear explanation.
