### ISSUE TITLE
Scripting app.command.Cut() and app.command.Paste() does not work in --batch mode

### ISSUE THREAD

**Issue by jestarray** [aseprite/aseprite#4354]
I'm trying to do a magic wand pixel selection on 1 layer and cut and paste to a new layer. 

This is the minimum reproducible version because my real script is more complicated than this.

https://github.com/aseprite/aseprite/assets/34615798/744ebd07-3c03-45df-8aa5-64fe026e92af

```lua
local sprite = app.activeSprite
local from_layer = sprite.layers[1]
local frame_num = 1
local from_cel = from_layer:cel(frame_num)

app.useTool {
    tool = "magic_wand",
    layer = from_layer,
    cel = from_cel,
    button = MouseButton.LEFT,
    points = {from_cel.position},
    selection = SelectionMode.REPLACE
}
app.command.Cut()
local to_layer = sprite:newLayer()
app.activeLayer = to_layer
app.activeFrame = to_layer.sprite.frames[1]
app.activeLayer = to_layer
app.command.Paste()

local without_ext = app.fs.filePathAndTitle(app.activeSprite.filename)
app.command.SaveFile {
    ["filename"] = without_ext .. ".ase",
    ["filename-format"] = ".ase",
}
```

### How to reproduce:

Extract folder and open command prompt in directory and run:
[one_pixel_paste.zip](https://github.com/aseprite/aseprite/files/14457020/one_pixel_paste.zip)
```
aseprite.exe ./one_pixel.png ./test_cut.lua
```

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
    - v1.3 master branch
    - commit: `73fe8099d96479364f92ff6317a5687498d43d36`
* System: Arch Linux

**Comment by Gasparoken** [comment]
Thanks for this report @jestarray. I was able to reproduce it.
