### ISSUE TITLE
Downloaded PNG in RGB mode fails to support transparency: erase uses secondary color and export PNG replaces transparent color with black

### ISSUE THREAD

**Issue by hsandt** [aseprite/aseprite#4370]
I often have this issue on images downloaded directly from the Internet, typically on The Spriters Resource. This happens when opening the PNG directly in Aseprite (not creating a new file then copying image rectangles). Note that opening a PNG sets the Color mode to **RGB** by default, so this is not an issue related to using Indexed Color mode (and even then, behavior differs from real Indexed Color mode).

Since spritesheets are often distributed with a transparency index color, I must manually remove the background color (by either using the magic wand + delete, paint bucket with transparent color or, when some background pixels are inside the sprites, the eraser + right-click to replace background color to transparent color (added myself to the palette).

However, I noticed the following:
- the eraser, bucket fill with transparent color and delete actions **replace the color with the secondary color**, as mentioned in https://github.com/aseprite/aseprite/issues/196 (very old but same symptom) and https://community.aseprite.org/t/bug-using-erase-causes-secondary-color-to-be-applied/4076
- the eraser + right-click to replace is the only way I found to actually replace background color with transparent color
- after using eraser + right-click to get actual transparency, the editor will show the "transparent grid" properly, but on export to PNG, it will generate **black instead of transparent color**

It seems that somewhat the PNG metadata cannot be changed even after saving the file as an .aseprite file.

Switching to Indexed Color mode and back to RGB doesn't help. Switching to Indexed Color mode and defining background color as the index color doesn't work either. All 3 color modes have the issue.

**Repro steps**

1. Download a spritesheet from the net, such as https://www.spriters-resource.com/master_system/sonicthehedgehog/sheet/5859/
2. Open in directly in Aseprite (Open with... or drag and drop)
3. Verify that it is RGB mode
4. Try the eraser or bucket fill with transparent color => fills with secondary color
5. Select background color as primary color. Add transparent color to palette, select as secondary color. Use the eraser + right-click with big brush size to replace background with transparency => it works
6. Export PNG => background is now black
7. Try different Color modes and repeat

**Workaround**

Create a brand new file in Aseprite in RGB mode, and copy image content from the PNG into that file, instead of opening the PNG itself in Aseprite.

Here is an example with a standard export on the left, and creating a new RGB file and copying content then exporting on the right:

![image](https://github.com/aseprite/aseprite/assets/1067772/7adc1096-6eff-496b-9c19-5bc61ab158ad)

### Aseprite and System version

* Aseprite version: v1.3.2 (official)
* System: Linux Ubuntu 22.04

### Other related threads

https://community.aseprite.org/t/my-eraser-draws-black-color-instead-of-erasing/2556/4

**Comment by Gasparoken** [comment]
Thanks for this report. Some comments:
Some PNG images were loaded with a __Background__ layer (instead a regular transparent layer) according how the images were encoded.

When you have a __Backgroud__ layer, all pixels on your canvas will be non transparent and the eraser tool will 'paint':
- left click: the secondary color (bg color)
- right click: only the primary color will be replaced with secondary color within applied eraser area.

To work with pixels with alpha values, convert the 'Background Layer' to 'Layer': right click on Layer name, _Convert to... > Layer_
![Screenshot 2024-03-19 at 08 05 57](https://github.com/aseprite/aseprite/assets/32165475/929b8389-875b-4633-9467-9731c90f8fe9)

Just in case: to select all the color you need to remove, the best tool is 'Magic Wand' with 0 Tolerance and __Continuos unchecked__  on the context bar ('continuos unchecked' will remove isolated areas of color too).

More info about Background Layer: https://aseprite.org/docs/layers#background-layer

**Comment by Gasparoken** [comment]
Based on your __Repro steps__, I see the inconsistency: there may be transparent pixels on a Background Layer, which should be prohibited.
