### ISSUE TITLE
`brush_type` popup window icons use incorrect scaling ratio

### ISSUE THREAD

**Issue by TakWolf** [aseprite/aseprite#4386]
version: main branch after 1.3.5

## Settings 1: 

<img width="262" alt="image" src="https://github.com/aseprite/aseprite/assets/6064962/f378d80d-b208-456b-a27a-2106944c69db">
<img width="505" alt="image" src="https://github.com/aseprite/aseprite/assets/6064962/f1e19735-6f48-4148-85e7-6f330f2966c3">

## Settings 2:

<img width="242" alt="image" src="https://github.com/aseprite/aseprite/assets/6064962/cf4cd9ce-cd7f-479f-9fd6-9ff928f2794a">
<img width="506" alt="image" src="https://github.com/aseprite/aseprite/assets/6064962/1527ea9f-1289-48c5-8a85-87b36748b27d">

It seems that the scaling ratio of these three icons is related to the font size, which is a bit strange. They should load according to the value of `uiscaling`.

By the way, for the default theme, should the following two be equivalent (In terms of display effect)?

```xml
<theme name="" screenscaling="2" uiscaling="1">
```

```xml
<theme name="" screenscaling="1" uiscaling="2">
```

**Comment by dacap** [comment]
Thanks for reporrting this bug  @TakWolf!

> By the way, for the default theme, should the following two be equivalent (In terms of display effect)?

Probably yes, not sure if it would be better to have a `scaling="2"` or something like that that can match any `screenscaling*uiscaling=2=scaling` combination.
