### ISSUE TITLE
 ninja: error: build.ninja:5158: multiple rules generate lib/cmark.lib

### ISSUE THREAD

**Issue by Sudence** [aseprite/aseprite#4390]
It's for windows.

It's a duplicate rule generation problem like the rest of them, but I couldn't find what was causing the cmark.lib problem

INPUT:
`ninja aseprite`

it does it everytime ninja is used.

OUTPUT:
`CMake Error:
  Running

   'C:/Ninja/ninja.exe' '-C' 'C:/aseprite/build' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:5158: multiple rules generate lib/cmark.lib

CMake Generate step failed.  Build files cannot be regenerated correctly.`

**Comment by dacap** [comment]
Hi @Sudence, could you try compiling a fresh copy of Aseprite downloading this zip file: https://github.com/aseprite/aseprite/releases/download/v1.3.6/Aseprite-v1.3.6-Source.zip

**Comment by Sudence** [comment]
Oh thanks man!
I actually built it the next day. Should've closed this, I'm sorry for that, but I have the solution.
It's just better to use the pre compiled ninja build and follow this video exactly step by step in order.
