### ISSUE TITLE
Alt to use Eyedropper does not work (but regular eyedropper does)

### ISSUE THREAD

**Issue by oskarkv** [aseprite/aseprite#4405]
Alt (with the default keybindings) to use the Eyedropper tool, for example while using the brush tool, does not work: it does not set the color when clicking on something. Using the Eyedropper tool by itself (not Alt) works.

![eye4](https://github.com/aseprite/aseprite/assets/861064/a3fbadcd-c29f-4952-abc3-181e4941ba0b)

### Aseprite and System version

* Aseprite version: 1.3.5-x64
* System: Linux Mint

**Comment by dacap** [comment]
Hi @oskarkv, generally on several Linux desktop/window managers the `Alt` key is used as a way to resize windows, so the key is captured by the window manager. Probably some configuration in Linux Mint to disable the `Alt` key as a modifier to resize windows might fix the Alt+click to pick colors.

**Comment by oskarkv** [comment]
Ah, yes, that solved it. Thanks @dacap!
