### ISSUE TITLE
Add simple "reset to defaults" button of all Aseprite settings

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#4432]
UI elements "reset to factory" requested here (internal ticket): https://igarastudio.zendesk.com/agent/tickets/6089

This can be fixed by using a simple global button to reset all settings (same effect as deleting preferences folders).

Or a better idea (in my opinion): have a centralized "Reset" item in Preferences that contains all Aseprite "reset to default" sectors.

**Comment by ckaiser** [comment]
I've been tinkering with the idea, made a small prototype of what an advanced reset window could look like: (WIP text)
![image](https://github.com/user-attachments/assets/b3af746b-9c9e-4ecd-80c4-22d48c9a5971)

This might be over-complicating things, but i do like the granularity of choosing specifically what you want to remove, although it does cross a bit into the realm of just deleting preferences vs "resetting" them to their defaults, any opinions @dacap ?

Ideally the more complicated ones (sessions and per-file settings) will have tooltips explaining what exactly you're removing.

**Comment by dacap** [comment]
> any opinions @dacap?

It looks like a nice idea, some thoughts about it:

1. The "Reset to Defaults" button at the bottom might be confused by "reset only the options in this section", I'd probably create the new "Reset" section as @Gasparoken said (along a separator at the bottom of the sections list) and move these checkbox and the button there:

   ![image](https://github.com/user-attachments/assets/c6a64f5f-18e0-4fb1-b203-34d5c24f35ad)

   ```
        <listbox id="section_listbox">
          ...
          <listitem text="@.section_experimental" value="section_experimental" />
          <separator horizontal="true" style="separator_in_view" />
          <listitem text="@general.reset" />
        </listbox>
   ```

2. I'd avoid the "remove saved sessions" item, as the user might lose information by mistake.
