### ISSUE TITLE
Issue with Compiling Aseprite

### ISSUE THREAD

**Issue by NoobSorcery** [aseprite/aseprite#4448]
Attempting to build Aseprite and ran into an issue with compiling the build.

After running the cmake promt in CMD this is what it says:

-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.45.0.windows.1")
-- Configuring done (212.7s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WEBP_LIBRARIES
    linked by target "app-lib" in directory C:/aseprite/src/app

-- Generating done (1.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

Aseprite v1.3.6 cloned through GitHub and Windows 11

**Comment by partisani** [comment]
go into CMakeLists.txt and press Ctrl+f _(or use the search feature in your editor, i used notepad)_ "WEBP", it is going to take you to a line where you can just disable webp support by replacing "on" with "off"

**Comment by partisani** [comment]
This _may_ not work, as these comments were written while i was compiling

**Comment by NoobSorcery** [comment]
> go into CMakeLists.txt and press Ctrl+f _(or use the search feature in your editor, i used notepad)_ "WEBP", it is going to take you to a line where you can just disable webp support by replacing "on" with "off"

Thank you so much this fixed the problem.
