### ISSUE TITLE
Double click an aseprite file always opens a new window instead of a new tab. 

### ISSUE THREAD

**Issue by crayonape** [aseprite/aseprite#4458]
I want the logic to be:
If the application is not open, open the application to launch the file.
If the application is open, open a new tab to launch the file.

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
v1.3.6  Steam
* System: Windows/macOS/Linux, version, distribution
PopOS 22.04

**Comment by martincapello** [comment]
Hi there, I will close this because it is duplicated of https://github.com/aseprite/aseprite/issues/477

Also, thumbs up https://github.com/aseprite/aseprite/issues/477#issuecomment-2111416221 to add traction.
