### ISSUE TITLE
Isometric perspective guide lines

### ISSUE THREAD

**Issue by enrib4** [aseprite/aseprite#4472]
![IMG_20240515_040451](https://github.com/aseprite/aseprite/assets/22949645/fb9c2fe1-016e-4917-93ab-a26d370eb489)
Would it be possible to include a layer with 3 thin guide lines (at 126º or other) to be able to draw sprites in isometric/dimetric perspective? 

I know that you can draw "lines" with a certain angle, that there are scripts to draw isometric boxes, transparent layers, etc. but they are the size of a pixel, very large and staggered.
In the end, today in 2024, we have to appeal to sticking a phisical transparency with the lines painted on top of the monitor, as was done in the 80s. Please, seriously is not enough time?

Thanks.

### Aseprite and System version
Aseprite version: 1.3.x
System: all

**Comment by dacap** [comment]
Duplicate from #720, probably as a workaround you could create a big image and import it as a reference layer (Layer > New > New Reference Layer from File). Reference layers can have a bigger resolution than the canvas pixels.
