### ISSUE TITLE
German localization breaks some buttons (for example when overriding files)

### ISSUE THREAD

**Issue by jvliaaaaan** [aseprite/aseprite#4482]
![bugreport](https://github.com/aseprite/aseprite/assets/121964524/f5bb5f3e-d4af-40b4-96de-3ee79a777e90)

When you switch the language to german and you export a file that already exists, it shows the "Do you really want to override the file?" Dialoge as it should, but the "Yes" or "Ja" Button is missing. I underlined where that "Ja" went.

Looks like some character was forgotten, so that it would be added as a button.

This also makes the "Nein" or "No" Button work like the "Yes" button. So you can still export, but you have to press "Nein" / "No".

Not sure if this happens with every dialogue window with that style, but I think it does.

Using Aseprite on Steam with v1.3.7-x64 (stable)

Not sure if this is relevant, but I'll add it:
App-ID: 431730
Build-ID: 14440584

System: Windows 11

**Comment by dacap** [comment]
@jvliaaaaan you can copy the updated [de.ini](https://raw.githubusercontent.com/aseprite/strings/main/de.ini) file in your `[Aseprite folder]/data/strings/de.ini` to give a try.

**Comment by jvliaaaaan** [comment]
Works perfectly, thank you for the quick fix!
