### ISSUE TITLE
Add option to not clone `aseprite/strings.git` during the build

### ISSUE THREAD

**Issue by vigress8** [aseprite/aseprite#4489]
If Aseprite finds git during the build, it tries to clone the `strings` repo, which is undesirable if it's e.g. already cloned manually. I maintain a build script which runs in an environment without an internet connection by default, so I had to patch out this behaviour:
https://github.com/pacstall/pacstall-programs/blob/30d70ece43b0bca6048bd774b517e25e5e849a6a/packages/aseprite/dont-clone-strings.patch

Adding a cmake flag for this would be useful

**Comment by dacap** [comment]
Hi @vigress8, could you test if using `FETCHCONTENT_FULLY_DISCONNECTED:BOOL=OFF` option does fix your issue?

**Comment by vigress8** [comment]
> Hi @vigress8, could you test if using `FETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON` option does fix your issue?

Yep, it does. Thanks, not very knowledgeable on CMake. You're free to close this if you wish

**Comment by kevinforrestconnors** [comment]
I'm not sure why this is happening on my machine, but I would support some way to not clone this from git in the install script, or if I could clone it manually separately and then link it.

```
[1/9] Creating directories for 'clone_strings-populate'
[1/9] Performing download step (git clone) for 'clone_strings-populate'
Cloning into 'strings.git'...
HEAD is now at fff711e Update credits
[2/9] Performing update step for 'clone_strings-populate'
fatal: unable to access 'https://github.com/aseprite/strings.git/': Failed to connect to github.com port 443 after 134395 ms: Connection timed out

```

**Comment by vigress8** [comment]
@kevinforrestconnors add `-DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON` to your `cmake` invocation or apply the patch from my original comment. But yes, this would still be nice to be able to configure explicitly

**Comment by dacap** [comment]
Yeah, I agree that this "close strings repo" thing in the compilation process makes things more complex. I'll add an option (CLONE_STRINGS_REPO) disabled by default so it doesn't add more complexity to the process.
