### ISSUE TITLE
Magic Wand tool doesn’t deselect a current selection when clicking outside of the canvas or when clicking on a selection again

### ISSUE THREAD

**Issue by PacketLauncher** [aseprite/aseprite#4490]
Aseprite installer, v1.3.6-x64 in Windows and installer, v1.3.6-arm64 on MacOS.

Originally reported here: https://community.aseprite.org/t/magic-wand-tool-doesnt-deselect-a-current-selection-when-clicking-outside-of-the-canvas-or-when-clicking-on-a-selection-again/22171

I found that when using the Magic Wand tool, if you click outside of the canvas in attempt to deselect a current selection, it doesn’t deselect but actually re-select the closest pixel to the mouse cursor on the X axis. Unlike when using the the Marquee tool which deselects correctly. I found that double clicking outside of the canvas with the Magic Wand sometimes deselect a current selection, but it is not very stable as it sometimes works and sometimes doesn’t (perhaps it depends on how fast you double-click). So you’d need to use the ESC key to deselect, which isn’t very convenient when using a stylus.
![Magic_Wand_Deselection_Issue](https://github.com/aseprite/aseprite/assets/36102054/bd1718d0-4f64-4409-a380-27cd42ca1644)
The correct behavior should be that you could either click outside of the canvas to deselect a current selection, or to left-click again on the current selection to deselect it, just like in Photoshop.

**Comment by dacap** [comment]
Hi @PacketLauncher, it looks pretty easy to fix, we'll try to include the fix in the next release.
