### ISSUE TITLE
Eyedropper Tool (quick) not working on Aseprite v1.3.7 on Linux Mint 21.3

### ISSUE THREAD

**Issue by Notnasiul** [aseprite/aseprite#4509]
Using the Eyedropper Tool (i by default) works, but the Eyedropper Tool (quick) (Alt - left mouse by default) doesn't.

* Aseprite version: v1.3.7, both Steam and ApppImage versions
* System: Linux Mint 21.3

**Comment by Notnasiul** [comment]
Yes, indeed, that was it! Sorry for reopening a closed issue. Maybe it would be nice for Aseprite to warn the user? Anyways, it's working now, thanks!

**Comment by dacap** [comment]
@Notnasiul it's not a bad idea, I'll see if this is possible in a near future.
