### ISSUE TITLE
== casting issue & math.floor internal optimization are breaking lua

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [aseprite/aseprite#4516]
math.floor seams to be internally optimized to return an int which lua does not have and is breaking lua:

zero = math.floor(0.5) -- probably returning int
if zero == 0.5 then print('a: error: ' .. tostring(zero) .. ' == ' .. tostring(0.5)) end -- Error: probably is incorrectly doing int comparison
zero = math.floor(0.5) + 0.1 - 0.1 -- cast to float
if zero == 0.5 then print('b: error: ' .. tostring(zero) .. ' == ' .. tostring(0.5)) end -- Okay: probably is correctly doing float comparison

The above code works without error in `https://www.mycompiler.io/new/lua` (5.3.6) and `https://onecompiler.com/lua` but has error "a:" in `aseprite v1.3.7-x64`.

`https://www.jdoodle.com/execute-lua-online` has no errors running lua 5.3.2 to 5.4.6

Expectation:
Lua should not be doing any int comparisons, causing these subtle bugs.
`int == float` seams to incorrectly `int == float as int` when it should `int as float == float`

`value // 1` is working correctly:

zero = 0.5 // 1 -- also floors numbers yet sets as float (`// 1` also sometimes breaks so use `// 1.0`)
if zero == 0.5 then log('a: error: ' .. tostring(zero) .. ' == ' .. tostring(0.5)) end -- Okay: probably is correctly doing float comparison
zero = 0.5 // 1 + 0.1 - 0.1 -- cast to float
if zero == 0.5 then log('b: error: ' .. tostring(zero) .. ' == ' .. tostring(0.5)) end -- Okay: probably is correctly doing float comparison

### Aseprite and System version

appimage v1.3.7-x64

**Comment by dacap** [comment]
Hi @RefinedSoftwareLLC, we're compiling Lua with `LUA_FLOORN2I=F2Ifloor` and it's highly probable that that is the issue you are experiencing. I'll see if we can find a better approach for this: e13d424ced3d0ad2a1c421edbec65628e67f2cd2

**Comment by RefinedSoftwareLLC** [comment]
Prefixing your code with:
```lua
__floor = math.floor
math.floor = function(x)
  return __floor(x) + 0.1 - 0.1
end
```
then restarting aseprite is a temporary workaround.

**Comment by RefinedSoftwareLLC** [comment]
> Hi @RefinedSoftwareLLC, we're compiling Lua with `LUA_FLOORN2I=F2Ifloor` and it's highly probable that that is the issue you are experiencing. I'll see if we can find a better approach for this: [e13d424](https://github.com/aseprite/aseprite/commit/e13d424ced3d0ad2a1c421edbec65628e67f2cd2)

If you can solve the `int == float` and `float == int` bug then having int mingled about is no longer an issue here.
