### ISSUE TITLE
Color picker dialog shows in home tab

### ISSUE THREAD

**Issue by Gnumaru** [aseprite/aseprite#4546]
When you open up aseprite, open any document and open up the color picker dialog (with F4), if you switch back to the home tab the "visuals" of the color picker are still there, but it seems just some sort of uncleared buffer because it is not interactable and as soon as you hover your mouse over anything that portion of the image is cleared

![image](https://github.com/aseprite/aseprite/assets/5783414/d9020170-77a2-4121-9892-80a79514c34b)

![image](https://github.com/aseprite/aseprite/assets/5783414/2019e4d4-a192-4c4c-bec3-ab56e1034362)

When you hover over the links that part of the screen gets cleared

![image](https://github.com/aseprite/aseprite/assets/5783414/09eb83d5-aa5a-4127-937d-5a4f75ba8da3)

![image](https://github.com/aseprite/aseprite/assets/5783414/c7ad57e9-02f2-4ba4-97f1-2b499b83210f)

If instead of changing tabs you close the tab only the part of the dialog right in the bottom of the window shows up.

![image](https://github.com/aseprite/aseprite/assets/5783414/62ae9a86-4327-46ad-b447-946889bf88fd)

### Aseprite and System version

* Aseprite version: 1.3.7 steam
* System: Windows 10 64 bit

**Comment by seanballais** [comment]
Hey, @dacap! Would it be okay if I try fixing this up? I have time to spare at the moment, and this seems like a good issue for me to start with.

**Comment by dacap** [comment]
Hi @seanballais, that would be great, I can assign this issue to you in case you want to give a try 👍

**Comment by seanballais** [comment]
Thanks, @dacap! I'm still trying to familiarize with the code base at the moment.

**Comment by seanballais** [comment]
@dacap Is the colour picker supposed to show up in the Home tab in the first place?

https://github.com/user-attachments/assets/ddbb5697-6bc8-43e1-8fa6-31c8f3c9b18c

**Comment by seanballais** [comment]
I dug into this issue a little deeper, and found out that the Layer Properties window is also affected by this bug, but not as bad as the colour picker. I think this may have to do with one of the subclasses of `ui::Window`.

https://github.com/user-attachments/assets/2e8be284-b6a8-4f32-a9c8-f3541e3020a8

**Comment by dacap** [comment]
@seanballais I think all these windows that depends on the sprite (preview, color selector, layer properties, etc.) should be hidden when the Home tab is selected, and restored just exactly as they were when we go back to a sprite.

**Comment by seanballais** [comment]
Noted, @dacap. Thanks. Will try to fix the colour picker first, but I'll see if I can solve the related bugs as well.

**Comment by dacap** [comment]
Thanks a lot @seanballais, any fix of these windows will be really appreciated 🙏

**Comment by seanballais** [comment]
Hey, @dacap! I think I need a bit of help. 😅 I have a few questions:

1. In `PopupWindow`, what does the hot region mean?
2. Which module is responsible for painting widgets? And how are windows to be rendered sent to it? The UI part resembles Qt's signals and slots and uses the observer pattern, but I'm struggling to trace how the rendering works.

Any pointers would be of great help. Thanks!

**Comment by dacap** [comment]
> 2\. Which module is responsible for painting widgets? And how are windows to be rendered sent to it? The UI part resembles Qt's signals and slots and uses the observer pattern, but I'm struggling to trace how the rendering works.

Widgets are painted when a `kPaintMessage` is processed by the `ui::Manager`: https://github.com/aseprite/aseprite/blob/3c4483183150f4adeb898013ae0a45a33f8058ac/src/ui/manager.cpp#L1973

Here the message is sent to the `Widget`: https://github.com/aseprite/aseprite/blob/3c4483183150f4adeb898013ae0a45a33f8058ac/src/ui/manager.cpp#L2017

And here the `kPaintMessage` message is processed: https://github.com/aseprite/aseprite/blob/3c4483183150f4adeb898013ae0a45a33f8058ac/src/ui/widget.cpp#L1567

Two important steps:

1. A `Graphics` is created with `getGraphics()`: https://github.com/aseprite/aseprite/blob/3c4483183150f4adeb898013ae0a45a33f8058ac/src/ui/widget.cpp#L1308 (which will use the Display surface, or a back-buffer is needed)
2. And a `paintEvent()`/`onPaint()` call: https://github.com/aseprite/aseprite/blob/3c4483183150f4adeb898013ae0a45a33f8058ac/src/ui/widget.cpp#L1175

Finally the `onPaint()` call to the specific widget: https://github.com/aseprite/aseprite/blob/3c4483183150f4adeb898013ae0a45a33f8058ac/src/ui/widget.cpp#L1232

**Comment by dacap** [comment]
Hi @seanballais, probably you weren't able to dedicate some time to this issue, I'll unassign this one so another developer can take it.

**Comment by seanballais** [comment]
Hey, @dacap! Sure, please do. I am currently unable to dedicate some time for the time being because of a higher priority project.

**Comment by martincapello** [comment]
I've started working on this one and just found out that this only happens when running Aseprite in single window UI mode. Also this same bug happens in macOs as well (I believe it should happen on linux too, but didn't test it).

**Comment by martincapello** [comment]
Thanks @seanballais! Will try my best, wish me luck!
