### ISSUE TITLE
Trouble Compiling

### ISSUE THREAD

**Issue by musashihumar09** [aseprite/aseprite#4547]
I am having issues compiling. I have tried every tutorial and followed every direction to the letter, but for some reason things do not seem to be going as they should. Any help would be appreciated greatly.

The following is the error text I get when I try to compile:

C:\aseprite\build>cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x64 -DSKIA_LIBRARY=C:\deps\skia\out\Release-x64\skia.lib -G Ninja ..
-- Could NOT find CCache (missing: CCache_EXECUTABLE)
CMake Deprecation Warning at third_party/zlib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at third_party/libpng/CMakeLists.txt:33 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at third_party/libpng/CMakeLists.txt:34 (cmake_policy):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- curl version=[7.79.1-DEV]
-- Could NOT find Perl (missing: PERL_EXECUTABLE)
-- Enabled features: SSL IPv6 unixsockets libz AsynchDNS Largefile SSPI alt-svc HSTS SPNEGO Kerberos NTLM
-- Enabled protocols: DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS LDAP MQTT POP3 POP3S RTSP SMB SMBS SMTP SMTPS TELNET TFTP
-- Enabled SSL backends: Schannel
-- Version: 10.0.0
-- Build type: RelWithDebInfo
CMake Deprecation Warning at third_party/libarchive/CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:441 (message):
  The package name passed to `find_package_handle_standard_args` (LIBGCC)
  does not match the name of the calling package (LibGCC).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  third_party/libarchive/build/cmake/FindLibGCC.cmake:17 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  third_party/libarchive/CMakeLists.txt:1258 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find LIBGCC (missing: LIBGCC_LIBRARY)
-- Could NOT find PCREPOSIX (missing: PCREPOSIX_LIBRARY PCRE_INCLUDE_DIR)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:441 (message):
  The package name passed to `find_package_handle_standard_args` (PCRE) does
  not match the name of the calling package (PCREPOSIX).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  third_party/libarchive/build/cmake/FindPCREPOSIX.cmake:23 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  third_party/libarchive/CMakeLists.txt:1263 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find PCRE (missing: PCRE_LIBRARY)
-- Extended attributes support: none
-- ACL support: none
CMake Deprecation Warning at laf/clip/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- laf backend: skia
-- laf zlib: zlibstatic
-- laf pixman: pixman
-- laf freetype: FREETYPE_LIBRARY-NOTFOUND
-- laf harfbuzz: HARFBUZZ_LIBRARY-NOTFOUND
-- skia dir: C:/deps/skia
-- skia library: C:/deps/skia/out/Release-x64/skia.lib
-- skia library dir: C:/deps/skia/out/Release-x64
-- aseprite libwebp: WEBP_LIBRARIES-NOTFOUND
CMake Deprecation Warning at src/observable/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at src/undo/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Could NOT find Git (missing: GIT_EXECUTABLE)
-- Configuring done (1.2s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WEBP_LIBRARIES
    linked by target "app-lib" in directory C:/aseprite/src/app

-- Generating done (0.8s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

C:\aseprite\build>

### Aseprite and System version

* Aseprite version: v1.3.7
* System: Windows 10

**Comment by notabirb1** [comment]
I also have this issue on Fedora Linux with Aseprite v1.3.7, following the build guide. I can upload the rest of my log file if needed, but I believe the issue is this part here:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WEBP_LIBRARIES
    linked by target "app-lib" in directory /home/notabirb1/Downloads/Aseprite-v1.3.7-Source/src/app
```

**Comment by srosato** [comment]
I dug a bit on the issues created here and I was able to see that there is a missing dependency:

```
sudo apt install libwebp-dev
```

I then stumbled on this [commit](https://github.com/Bang1338/aseprite/commit/27027f9b1ea1b5b4cfa3e9efb2e8fb76a6a1c1af) and saw we need to add a flag: `-DWEBP_LIBRARIES=$HOME/deps/skia/out/Release-x64/libwebp.a` in order for the build command to become something like this:

```
cmake \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
  -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
  -DLAF_BACKEND=skia \
  -DSKIA_DIR=$HOME/deps/skia \
  -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
  -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
  -DWEBP_LIBRARIES=$HOME/deps/skia/out/Release-x64/libwebp.a \
  -G Ninja \
  ..
  ```

**Comment by milosmml7777** [comment]
The comment from @srosato gave me a little insight.
If we want to build aseprite on windows we have to add the **-DWEBP_LIBRARIES=$HOME/deps/skia/out/Release-x64/libwebp.a** version of linux and convert it to windows just like **DSKIA_LIBRARY=C:\deps\skia\out\Release-x64\skia.lib -DWEBP_LIBRARIES=C:\deps\skia\out\Release-x64\libwebp.lib**

For windows users this worked for me.
When compiling change it to:
`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\deps\skia -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x64 -DSKIA_LIBRARY=C:\deps\skia\out\Release-x64\skia.lib -DWEBP_LIBRARIES=C:\deps\skia\out\Release-x64\libwebp.lib -G Ninja ..`

Hope this helps.
Nice eye @srosato

**Comment by Alemar5** [comment]
It may be a bit late but this may be useful to someone, so download this specific version of Cmake, this worked for me: https://github.com/Kitware/CMake/releases/tag/v3.28.1
