### ISSUE TITLE
JSON : errors in keys name when exporting a sheet

### ISSUE THREAD

**Issue by jeangit** [aseprite/aseprite#4603]
Hello, when exporting a tilesheet from two files , i get correct graphic export, but wrong JSON file.
The JSON file keys are duplicate.

With this two files: `sol1.png` and `sol2.png` , i get:

```
{ "frames": {
   "sol1.png": {
    "frame": { "x": 0, "y": 0, "w": 64, "h": 64 },
    (snip)
   },
   "sol1.png": {
    "frame": { "x": 64, "y": 0, "w": 64, "h": 64 },
    (snip)
   }
 },
 "meta": {
  "app": "http://www.aseprite.org/",
  "version": "1.3.7-dev",
  "image": "test_sheet.png",
  "format": "RGBA8888",
  "size": { "w": 256, "h": 128 },
  "scale": "1"
 }
}
```
Command used:
`aseprite -b --data test_aseprite.json --sheet test_sheet.png --filename-format {name} --sheet-width 256 --sheet-height 128 sol1.png sol2.png`

Attached, you will find an archive with two PNG (made from me, no © problems) and a script for getting this result.

### Aseprite and System version

* Aseprite version: 1.3.7-2 (dev) (from AUR)
* System: archlinux

Thank  you.
[test_sheet_aseprite.zip](https://github.com/user-attachments/files/16660934/test_sheet_aseprite.zip)

**Comment by dacap** [comment]
Hi @jeangit, I guess Aseprite is loading your `sol1.png` as a sequence of frames (sol1+sol2 as one sprite with two frames), could you try adding `-oneframe` argument in the CLI before `sol1.png`?

**Comment by jeangit** [comment]
Thank you @dacap , of course you are right. I had missed that from the manual.
