### ISSUE TITLE
Can't use Export as when .aseprite file is in a different drive than the output folder

### ISSUE THREAD

**Issue by VindSole** [aseprite/aseprite#4607]
When I try to export an .aseprite file, it shows me an error, but only when trying to export to a different drive than the original file. all worked well before version 1.3.8.

![image](https://github.com/user-attachments/assets/faae89bc-5f5e-4076-8fcf-a4097fb60037)

It seems to be forcing the original file location right behind the export location, can't change this.

Edit: confirmed the issue not present in 1.3.7.

### Aseprite and System version

* Aseprite v1.3.8
* Windows 11 Pro

**Comment by dacap** [comment]
Thanks for reporting this regression @VindSole, we'll try to release a fix ASAP.
