### ISSUE TITLE
Broken themes with new plus sign

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4609]
The new "plus" sign introduced in #4582 broke other themes:

![image](https://github.com/user-attachments/assets/6d7976d6-f308-45bb-9218-086eaaea3c29)

This might because we copy missing styles to the selected theme from the default one, but we're not copying inexistent sprite sheet parts.

**Comment by ckaiser** [comment]
Huh, I added a fallback for the case where there was no add icon, it should be drawing a normal plus sign, so either setting the text fallback is failing, or it's still trying to draw it even if it's not there and overriding the text property.

**Comment by dacap** [comment]
I was just checking that. As the default theme is loaded first, the `m_parts_by_id["icon_add"]` contains a `SkinPart`, but I'm still trying to figure out what that part contains after the new theme is loaded 🤔

**Comment by dacap** [comment]
The issue is that the `new_frame_button` is an existing style in previous themes as:
```
 <style id="new_frame_button" extends="mini_button" />
```
without the part, we cannot do this. I'll revert part of this change in the theme and the status bar to go back to the previous implementation with the "+" character.
