### ISSUE TITLE
Add feedback to "Recover Files" option when there are a lot of files/sessions to recover

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4610]
This requires some testing, but I think there is a "little" hang of the UI when we press the Recover Files button (probably a `base::list_files()` blocking the whole UI or something like that).

Reports:
- https://steamcommunity.com/app/431730/discussions/0/4427688158474122991/
- https://steamcommunity.com/app/431730/discussions/2/4758703722109585564/
- https://steamcommunity.com/app/431730/discussions/2/4757578099471857947/

**Comment by dacap** [comment]
Seeing several reports recently where the "Recover Files" option is taking time/freezes the program, not sure if there is a regression of some kind (?)

**Comment by ckaiser** [comment]
I've been doing some investigating and it's a bit of a maze but hopefully I'll have something concrete soon, I've already found some optimizations for the raw crawling of files but I'm still unclear on how and why it's doing some of the work since it's a bit inconsistent

**Comment by dacap** [comment]
At the moment we've fixed this issue with #4660 and #4672 improving the performance to list/display files/items. If further performance issues are reported we can reopen this.
