### ISSUE TITLE
Should we remove ENABLE_UI?

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4619]
The `ENABLE_UI` flag makes the development a little more complex because generally we always compile with this option enabled. It was originated for #1279 but we have never released a CLI-only version of the program. Even more, probably we can solve the CLI-only problem with other easier approach instead of `#ifdef/#endif`'ing the whole code.

I think we have some options:

1. Remove `ENABLE_UI` and suppose we always have the GUI functions available, with a `LAF_BACKEND=none` the creation of the main window will fail anyway (and this could be the CLI-only version).
2. Sometimes the `ENABLE_UI` helps to think about the CLI-only situation where the GUI is not available (i.e. we're running with the `-batch` parameter) and we try to use some widget at runtime but it fails because it's uninitialized. Anyway sometimes the compilation with `ENABLE_UI=off` doesn't catch all possible errors.

**Comment by ckaiser** [comment]
The less conditional compilation stuff that exists in general, the better, IMO. Especially when it's not 100% guaranteed to catch stuff.
