### ISSUE TITLE
Import - PNG, GIF, BMP Sequences

### ISSUE THREAD

**Issue by VetNovice** [aseprite/aseprite#463]
Would be nice to be able to be able to import .png, .gif, .bmp image sequences into Aseprite. Reason I ask for this feature is programs like Flash or other animation softwares don't usually export animations into sprite sheets.

Hopefully it's not too tedious to implement.

**Comment by ChildishGiant** [comment]
> Hi there! Currently you can load (File > Open) a sequence of images. For example, if they are named `image00.png`, `image01.png`, `image02.png`, etc. Also you can load a .gif file. Anyway there is no easy way to import the sequence to your own animation in v1.0.2, but v1.0.3 will include an option to copy and paste frames between animations, so the "import" will be possible. (I'm not quite sure if this satisfied the issue 😄)

I have files named `image(number)` but they're still all loading as separate images. The bulk renamer I use puts the numbers in brackets and I can't change that. Do I need to manually rename all of them for this to work? Would it be possible to add an option to import any given selection of images into a single sheet?
