### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#464]
Add a special fullscreen mode (F11 or Alt+Enter on Windows). To support fullscreen in Mac OS X, we need a more recent Mac OS X SDK, which we already need for the next OS X Yosemite release.

**Comment by dacap** [comment]
There are some comments about possible extra settings for the full-screen mode here: http://steamcommunity.com/app/431730/discussions/1/357284767254601886/

**Comment by ClementineAccount** [comment]
Using this u can get pretty close to 'full screen' as you can get https://github.com/CrypticButter/ButteryTaskbar however an actual implementation should still be considered

**Comment by dacap** [comment]
I'll take this one for next week. At least for Windows.

**Comment by dacap** [comment]
This feature will be available in the first v1.3
