### ISSUE TITLE
Magic Wand doesn't work correctly in Tiled Mode

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4659]
In Tiled Mode, Magic Wand works only when we click in the top-left ninth:

![Peek 2024-09-12 19-20](https://github.com/user-attachments/assets/efde5b68-2e8b-413d-9f21-6be7e18c65e7)

From: https://community.aseprite.org/t/i-cant-select-with-the-magic-wand-tool/23399/6?u=dacap

**Comment by Kayladillo** [comment]
Is it also a bug or intended that when grabbing a tiled sprite, the pivot automatically aligns to the top-left ninth?
![image](https://github.com/user-attachments/assets/37743061-df01-4eec-9876-56b33d22ab66)
