### ISSUE TITLE
Duplicate Sprite & Duplicate Layer don't duplicate z-indexes

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4665]
Just duplicating a sprite (Sprite > Duplicate) or a layer (Layer > Duplicate) will not duplicate the z-index of each cel of that sprite layers/specific layer.

EDIT: @Gasparoken wasn't able to reproduce this bug so it looks like other kind of problem, maybe related to a specific file/combination with other thing. Duplicating this sprite: [duplicate-sprite-bug.zip](https://github.com/user-attachments/files/17317517/duplicate-sprite-bug.zip) fails.

**Comment by Gasparoken** [comment]
During debugging, I realize that the main issue is: 'z-order' can be modified in a linked cel, but this z-order isn't replicated to its linked cels.

**Comment by Gasparoken** [comment]
What do you think @dacap?
Given the current implementation of `m_zIndex`, it appears that the original intention was to be independent of `m_data` binding. I need confirmation of this to go ahead.

**Comment by dacap** [comment]
> Given the current implementation of `m_zIndex`, it appears that the original intention was to be independent of `m_data` binding.

Yes, that is the intention of the z-index (a different value per cel, linked or not). Basically the idea of the "Duplicate Sprite" is to create the exact same sprite without any difference.

**Comment by Gasparoken** [comment]
Thank you!
