### ISSUE TITLE
Some improvements to the portable version

### ISSUE THREAD

**Issue by ElderlyGlek** [aseprite/aseprite#4675]
I think it should be possible to associate .ase, .aseprite, .aseprite-extension files with the portable version. Although it is possible to associate .ase and .aseprite files via "Open with", but the icon of the documents will be the same as the Aseprite logo, although the icon for the documents is different. I also think that the portable version should include the aseprite-thumbnailer, because many people may not be able to find [this](https://aseprite.org/thumbnails) page.

### Aseprite and System version

* Aseprite version: Aseprite-v1.3.8.1-x64-Portable
* System: Windows 11 Pro, 23H2

**Comment by ElderlyGlek** [comment]
By the way, aseprite-thumbnailer is not working for me… It was working, then I clicked "Open with" on the .aseprite file and for some reason after a couple of minutes only the program logo remained instead of the thumbnail (reinstalling aseprite-thumbnailer didn't help, although the thumbnails through the installer work fine):

![](https://github.com/user-attachments/assets/b15ef2e8-b123-42bb-b60c-f82f11a28b77)

Also, here's what happens when you try to open .aseprite-extension via "Open with":

![](https://github.com/user-attachments/assets/e6437598-8aad-4106-b4df-a279ab97358d)

**Comment by ElderlyGlek** [comment]
@dacap Is it worth waiting for a solution? aseprite-thumbnailer still doesn't work with Aseprite-v1.3.9.2-x64-Portable even after a clean reinstall of Windows 11 (24H2).

**Comment by ElderlyGlek** [comment]
@Gasparoken 

> @dacap Is it worth waiting for a solution? aseprite-thumbnailer still doesn't work with Aseprite-v1.3.9.2-x64-Portable even after a clean reinstall of Windows 11 (24H2).

@Gasparoken It seems David is very busy, could you answer my question?

**Comment by dacap** [comment]
See #1179
