### ISSUE TITLE
CIE LAB Palette Matching Transparency Issue

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#4686]
Reported: https://community.aseprite.org/t/cie-lab-palette-matching-transparency-issue/23585/2

### Aseprite and System version

* Aseprite version: 1.3.9
* System: all

**Comment by dacap** [comment]
Just in case, the bug is reproducible in CIE XYZ, RGB, doesn't depend on the criteria:

![Peek 2024-10-03 17-50](https://github.com/user-attachments/assets/6ffafb8b-9b88-46ab-9eba-0756c78af916)
