### ISSUE TITLE
Windows 7 incompatibility in latest version, is C runtime time() using GetSystemTimePreciseAsFileTime()?

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4691]
Bug reported in:

  https://community.aseprite.org/t/1-3-9-refuses-to-start-with-entry-point-not-found-error/23610

Probably the `time()` function (or other function) is using `GetSystemTimePreciseAsFileTime()`, although in the past it was changed to `GetSystemTimeAsFileTime()`:

  https://developercommunity.visualstudio.com/t/ucrtbases-implementation-of-time-unnecessarily-use/184829#T-N556730

Google compiles libc++ with Windows 7 support only (?):

https://source.chromium.org/chromium/chromium/src/+/main:buildtools/third_party/libc++/BUILD.gn;drc=7fb5af390b016c60c493871e7d327cba142dcdc5;l=34
https://groups.google.com/a/chromium.org/g/chromium-dev/c/QP4cZtF7B0E

We're compiling [with Windows 10 definitions](https://github.com/aseprite/laf/blob/b7f5b4ba321ff9746391374b6e24d8420dae108c/base/CMakeLists.txt#L89) and loading DLL functions at runtime. But it might be possible that these macros now changes the C++ library implementation (?).

**Comment by dacap** [comment]
Probably we should compile our own STL?

https://github.com/microsoft/STL
https://github.com/microsoft/STL/blob/faccf0084ed9b8b58df103358174537233b178c7/stl/src/winapisupp.cpp#L161

**Comment by ckaiser** [comment]
It's also worth considering dropping support for an OS that's fully EOL'd and has been for more than 4 years 😅

**Comment by dacap** [comment]
I was able to reproduce this issue on a VM:

![image](https://github.com/user-attachments/assets/3510aa85-9bfe-4a70-bd72-39c742498961)

This is strange because compiling a regular aseprite.exe was able to run the binary on Windows 7, so probably there is a flag in our internal build scripts that is making this fail. I'll report any news soon.

> It's also worth considering dropping support for an OS that's fully EOL'd and has been for more than 4 years 😅

Yeah, we'd love that, it's a shame that there are some users still with Windows 7 (something similar happened with Windows XP, at least once a year we receive a request to download the latest working version on Windows XP 😭).

**Comment by dacap** [comment]
More information: When compiling/linking with [sentry-native](https://github.com/getsentry/sentry-native/) is when this incompatibility appears.

**Comment by dacap** [comment]
This was fixed with https://github.com/aseprite/sentry-native/commit/978cb60f0d15ca73cc49840fa0cecf4cae1d4531
