### ISSUE TITLE
Paint bucket-like tools should take care of grid

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#473]
If the grid is visible, the paint bucket tool (or magic wand) should take care of the limit of the current grid cell. In this way we can paint in a grid cell in a isolated mode.

**Comment by masondesu** [comment]
Sorry to comment on such an old issue! It seems that only filling the grid-tile when the grid is visible can be bewildering if you're on a 1x1 grid, especially using the app for the first time. Perhaps an "Obey Grid" option on the paint bucket could make this less confusing?

**Comment by Async0x42** [comment]
While I haven't run into this issue before since I didn't use the grid yet, I can agree that this would've been really confusing on a small grid without reading this first

**Comment by derloopkat** [comment]
Masondesu is right. This "feature" made the software more difficult to use. When someone use the bucket, the expected behaviour is filling with paint. Currently nothing happens and you end up having no clue on what went wrong. Misleading and over complicated behaviour. This cannot be the default.

**Comment by dacap** [comment]
hi @derloopkat, ok, I'll change the "stop at grid" unchecked by default which is the common behavior on common painting programs

![screen shot 2016-09-19 at 1 28 59 pm](https://cloud.githubusercontent.com/assets/39654/18640108/11419512-7e6d-11e6-908c-6603a68c9c5e.png)
