### ISSUE TITLE
"For n loop" property in Tag Properties

### ISSUE THREAD

**Issue by FrankenGFX** [aseprite/aseprite#4732]
### feature request
(_3rd and last (i promise) feature request this day. Bear with me, these ideas have been bottled up for a couple years_). 

One thing i've always enjoued in Aseprite is that you can nest tags. that makes it possible to preview a subportion of a cycle. 

However, one thing i've been wanting for a long time is to change a tags' loop behaviour from "while (true)" to "for n repeats".
This would make it possible to have a few frames in a nested tag loop a number of times before continuing on to the encompassing tag.

To visualize the use case, let's say i have a flag on a flagpole. Outer while tag begins. The wind is still, then wind picks up, (start of inner tag), makes the flag wave 7 times (end of inner tag), then fall, be still, and loop again (end of outer tag). 

With a "for loop" property of the inner tag, i could edit those frames just once and see them play back 7 times as intended, instead of having to duplicate them and edit each an every one repeat of that mini cycle. 

### Aseprite and System version
* Aseprite version: 1.2.16-x64
* System: Windows 10

**Comment by dacap** [comment]
Hi @FrankenGFX, I think you are looking for the new "Repeat" field in tags added in Aseprite v1.3-rc1: https://www.aseprite.org/release-notes/#aseprite-v1-3-rc1, PR #3563

**Comment by dacap** [comment]
![image](https://github.com/user-attachments/assets/88b89a21-2866-494a-8e43-9e49bd4039a6)
