### ISSUE TITLE
Add some of the GraphicsContext functions to Image

### ISSUE THREAD

**Issue by MapleGecko** [aseprite/aseprite#4738]
(Made for [v1.3.x (features for extensions)](https://github.com/aseprite/aseprite/milestone/59) milestone)

The [Image](https://www.aseprite.org/api/image#image) API is kinda lacking compared to what [GraphicsContext](https://www.aseprite.org/api/graphicscontext#graphicscontext) is now capable of doing, it would be great to have more shared functions between them.

Typically, having access - from an Image object - to functions like **drawThemeRect**, **drawThemeImage**, **fillText**, **measureText**, and 
 a rectangle-based **[Image:drawImage()](https://www.aseprite.org/api/image#imagedrawimage)** (right now I believe you can only pass a Point as a position)

Similarly, it would be nice to have a GraphicsContext:export() function to get the contents of a canvas as an Image object, but it might be hard to do depending on the current implementation of GraphicsContext. However it might be the best way to tackle this issue and make GraphicsContext the most optimal way to do Image drawing operations, without having to implement any new Image function.

### Aseprite and System version

* Aseprite version: v1.3.9.2
* System: Windows

**Comment by dacap** [comment]
Hi @MapleGecko, actually it's already implemented for the next beta (we hope to have something next week if possible): with #4330 and #4605
