### ISSUE TITLE
1.3.8 and later versions are missing the "strings.git" file after compilation from source.

### ISSUE THREAD

**Issue by 66six11** [aseprite/aseprite#4747]
Describe your bug report or feature request here

Hi！I have a problem.
Starting from version 1.3.8, I noticed that the "strings.git" file was missing from the "build/bin/data" directory after compiling, which resulted in Aseprite not having other language options when built.

I can be successful by cloning the repository at https://github.com/aseprite/strings.git

this is 1.3.7
![image](https://github.com/user-attachments/assets/3b299e7c-4033-426a-b0ff-ba4d6b46479b)

this is 1.3.8 and later
![image](https://github.com/user-attachments/assets/3d5713b8-e029-473a-81f8-6db8f2bbf991)

system·：Windows11

**Comment by dacap** [comment]
Hi @66six11, we've switched off the automatic `strings.git` cloning process by default:

  https://github.com/aseprite/aseprite/issues/4489#issuecomment-2194437831

You can re-enable it with `ENABLE_I18N_STRINGS=ON` cmake option.
