### ISSUE TITLE
MacOS 15 build errors

### ISSUE THREAD

**Issue by Yonodactyl** [aseprite/aseprite#4751]
I’m encountering a build error when attempting to compile Aseprite on macOS 15.0. The error indicates that the function `CGDisplayCreateImageForRect` is deprecated and recommends using `ScreenCaptureKit` instead.

I am able to get the initial install of Aseprite done using code, but when going in to work on a fix for a Github Issue, the compiler fails when doing a second `ninja aseprite` call. This is the direct error (with some redaction of my folders):

```cpp
...../aseprite/laf/os/osx/system.mm:118:22: error: 'CGDisplayCreateImageForRect' is unavailable: obsoleted in macOS 15.0 - Please use ScreenCaptureKit instead.
118 |   CGImageRef image = CGDisplayCreateImageForRect(CGMainDisplayID(),
    |                      ^
```

### Aseprite and System version

* Aseprite version: compiling from **main** branch following `INSTALL.md` instructions
* System: **macOS 15**

**Comment by Yonodactyl** [comment]
Looks like this is a duplicate of an issue in another repo: https://github.com/aseprite/laf/issues/108#issue-2541167521 

Sorry for cross posting.

**Comment by dacap** [comment]
Hi @Yonodactyl, in our instructions we use:
```
      -DCMAKE_OSX_ARCHITECTURES=x86_64 \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
```
when running cmake, probably if you are on Apple Silicon you will want to use 11.0:
```
      -DCMAKE_OSX_ARCHITECTURES=arm64 \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
```
does this fixes your problem?

**Comment by Yonodactyl** [comment]
Here is what I was using:
```bash
cmake \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_OSX_ARCHITECTURES=arm64 \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
  -DCMAKE_OSX_SYSROOT=$(xcrun --sdk macosx --show-sdk-path) \
  -DLAF_BACKEND=skia \
  -DSKIA_DIR=$HOME/deps/skia \
  -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-arm64 \
  -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-arm64/libskia.a \
  -DPNG_ARM_NEON=on \
  -G Ninja \
  ..
  ```
---
I am currently on macOS 15, and it doesn't allow you to use a version of Xcode less than 16.0. So when I run `ninja aseprite` after making a minor code change in the `src` folder, the compilation fails and returns the error I mentioned above. I believe Apple deprecated some screen capture stuff and its causing the issues when you use the latest SDK.
