### ISSUE TITLE
Pattern Fill

### ISSUE THREAD

**Issue by ConspiracyCat** [aseprite/aseprite#479]
What do you want to do?
Have a pattern fill bucket along with the solid and gradient fill options.

How would it work?
Pretty much like the photoshop pattern fill, it would use primary and secondary selected colours to create the effect. For starters, to avoid having to save custom patterns, you could start with the 4 or so patterns that are commonly recognised as the generic "gradient" steps to dither from one colour to another. I have attached an image showing the different patterns below.

![dither2](https://cloud.githubusercontent.com/assets/8640641/4132737/178e4b96-3355-11e4-8cac-b88a53e46e1d.png)

**Comment by dacap** [comment]
Fixed with 0bab4e7ae7224181500b183d0c820248f3a3c949 and 2a15c58b5b78f0695a9651e599bbf8393809bf28
