### ISSUE TITLE
Edit Tab Snap Issue at Screen Edge

### ISSUE THREAD

**Issue by martincapello** [aseprite/aseprite#4796]
・When an Edit tab (e.g., Hue/Saturation) is positioned at the screen edge, the click position lags, resulting in off-target interactions.
・This problem is resolved if the tab is moved away from the screen edge.

https://github.com/user-attachments/assets/8493e003-c79c-4ced-b2d5-d8bdb370efb6

### Aseprite and System version

* Aseprite version: v1.3.9.2-arm64, Steam
* System: 16-inch MacBook Pro (2021) Specs: 64GB RAM, 8TB storage, macOS Sequoia version 15.1

**Comment by martincapello** [comment]
According to the user that reported this issue, it is already fixed.
Reference: https://github.com/aseprite/aseprite/issues/4787#issuecomment-2563237787

**Comment by dacap** [comment]
I was searching for the aseprite (laf) commit that fixed this issue but I wasn't able to found it. @martincapello do you remember?

**Comment by martincapello** [comment]
There is no commit actually. I was saying that it is fixed because the user said (in the comment I mentioned):
> The issue [#4796](https://github.com/aseprite/aseprite/issues/4796) seems to be resolved on my environment as well.
It might have been caused by interference with other program issues that you resolved recently. In any case, I’m glad it’s fixed!

But I actually didn't do anything. I wasn't able to reproduce it as well...
