### ISSUE TITLE
Clicking "Disable Snap to Grid" resizes the main window (using multiple windows)

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4805]
Strange regression in v1.3.10 reported in: https://community.aseprite.org/t/23912

**Comment by dacap** [comment]
@martincapello would you mind to take this one? it looks like a regression with 2e17f27237d175911412f4747e23c822d79c75b6

**Comment by dacap** [comment]
At least on Windows this does work:
```diff
diff --git a/src/ui/window.cpp b/src/ui/window.cpp
index 5d08d6232..c8385ddff 100644
--- a/src/ui/window.cpp
+++ b/src/ui/window.cpp
@@ -717,8 +717,13 @@ void Window::onSetText()
 void Window::onVisible(bool visible)
 {
   Widget::onVisible(visible);
-  if (get_multiple_displays() && m_display) {
-    display()->nativeWindow()->setVisible(visible);
+
+  Display* display = this->display();
+  if (ownDisplay() &&
+      display &&
+      display->nativeWindow() &&
+      display->nativeWindow()->isVisible() != visible) {
+    display->nativeWindow()->setVisible(visible);
   }
 }
 
```
There is another issue which I'm not sure if it's related: https://community.aseprite.org/t/dialog-show-bounds-rectangle-is-broken-in-1-3-10/23917/1

**Comment by martincapello** [comment]
I have tried this slight variation:
```c++
void Window::onVisible(bool visible)
{
  Widget::onVisible(visible);
  Display* display = this->display();
  if (ownDisplay() &&
      display &&
      display->nativeWindow()) {
    display->nativeWindow()->setVisible(visible);
  }
}
```
And it works as well. 

The fix also works on macOS (this issue is seen as a flickering effect on the main window).

Will see https://community.aseprite.org/t/dialog-show-bounds-rectangle-is-broken-in-1-3-10/23917/1 now

**Comment by martincapello** [comment]
Seems related to d32fc4c70483e19ebf6ec0f960f36e748976f789 
I have a fix already that I will push soon
