### ISSUE TITLE
Issue with app.command.FlattenLayers when running a script in batch mode

### ISSUE THREAD

**Issue by safernan121** [aseprite/aseprite#4807]
There is an issue when calling the function `app.command.FlattenLayers()` in a script when running it on batch mode.
The expected behavior (which work when Aseprite isn't in headless mode) is that `app.command.FlattenLayers()` will only flatten all selected layers in `app.range.layers`. When doing it in batch mode, it will flatten ALL layers, regardless of what `app.range.layers` contains.

I created a small script that can prove this. If you run this script with the command `-b` it will flatten all layers, but if ran without it it will only flatten a subset of them.

[example_script.zip](https://github.com/user-attachments/files/17845265/example_script.zip)

### Aseprite and System version

* Aseprite version: 1.3.9.2
* System: MacOS Sonoma 14.6.1

**Comment by dacap** [comment]
Hi @safernan121, could you test the beta vesion ([released yesterday](https://bsky.app/profile/aseprite.org/post/3lbfvjsdgzc2s))? not sure if you have Steam installed.

I've just tested `aseprite -b example.aseprite -script  example.lua` and it worked:
```
Initial layers:
Layers: Layer 1, Layer 2, Layer 3, Layer 4, Group 1
Selected layers: Layer 2, Layer 4
After flattening:
Layers: Layer 1, Flattened, Layer 3, Group 1
```

This is thanks that to the beta branch which includes some changes to handle ranges when the UI is not fully available.

**Comment by safernan121** [comment]
Yes! @dacap ! The beta version does address this issue! Thanks a ton!
