### ISSUE TITLE
question: compile on Windows 11

### ISSUE THREAD

**Issue by divoomgirl** [aseprite/aseprite#4829]
Hi

Is it possible to compile on Windows 11 since in the readme there is specific needed Windows 10 SDK?
Can we install  Windows 10 SDK on Windows 11?

**Comment by dacap** [comment]
Hi @divoomgirl, you can use Windows 11 and the latest Windows 11 SDK to compile Aseprite.

**Comment by divoomgirl** [comment]
Thanks!
Maybe it can be changed inthe readme? Because there it looks like only Windows 10 SDK can be used.
