### ISSUE TITLE
CMake Path error

### ISSUE THREAD

**Issue by 74P3** [aseprite/aseprite#4831]
While doing the cmake command, This error happened...

CMake Error in src/app/CMakeLists.txt:
  Imported target "libjpeg-turbo" includes non-existent path

    "C:\deps\skia/third_party/externals/libjpeg-turbo"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

-- Generating done (1.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

### Aseprite and System version

* Aseprite version: v1.3.11-beta2
* System: Windows 11 Pro

**Comment by dacap** [comment]
Hi @74P3, it looks like you are using the [skia-m102](https://github.com/aseprite/skia/releases/tag/m102-861e4743af) (for the `main` branch) and not the [skia-m124](https://github.com/aseprite/skia/releases/tag/m124-08a5439a6b) (for the `beta` branch).

**Comment by 74P3** [comment]
Oh, didn't know I was supposed
