### ISSUE TITLE
feature request: move existing layer into group

### ISSUE THREAD

**Issue by ghost** [aseprite/aseprite#4844]
Describe your bug report or feature request here
There is a limitation in aseprite: you can't put existing layers in a group (or I don't find how to do it).
Example: existing layer 1 can't be put in group 1 (see below)
I would like to request a feature to drag-and-drop any layer into a group (or outside a group).

![afbeelding](https://github.com/user-attachments/assets/b9267bb9-1aee-4342-81ca-d9cbca839e4a)

### Aseprite and System version

* Aseprite version: 1.3.10
* System: Windows

**Comment by MapleGecko** [comment]
@divoomgirl You can do it, simply drag and drop a layer into a group (or a layer belonging to that group) using the blue outline you see when selecting one :)

![layer_drag_n_drop](https://github.com/user-attachments/assets/7869272f-61a3-4842-ab1f-87704c06ec96)
