### ISSUE TITLE
Feature Request: Add frame groups/rework frame tagging

### ISSUE THREAD

**Issue by Skibichi** [aseprite/aseprite#4848]
Describe your bug report or feature request here
So i've been doing like a big anim project and with alot of frames and sections and i just realised there should be like a way to group frames or make it so when you tag a group of frames there's an option to hide/reveal it's contents like how it is when you hide/reveal a group of layers

**Comment by dacap** [comment]
Hi @Skibichi, actually this was requested several times in the past in #920, https://community.aseprite.org/t/request-collapse-tags/3349, and https://community.aseprite.org/t/animation-folders-collapsible-loops/6582.
