### ISSUE TITLE
Shouldn't ZLIB_FOUND be set to ON instead of unset?

### ISSUE THREAD

**Issue by ryandesign** [aseprite/aseprite#4854]
When using bundled zlib instead of shared zlib, the CMake variable `ZLIB_FOUND` is unset:

https://github.com/aseprite/aseprite/blob/f710603f9903679f48622185fec4bc937bd6d1d1/CMakeLists.txt#L200-L203

([CMake documentation](https://cmake.org/cmake/help/latest/command/set.html) says when no value is given, `SET` unsets the variable.)

Shouldn't it be set to a truthy value like `ON` instead?

```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -202,7 +202,7 @@ endif()
 if(USE_SHARED_ZLIB)
   find_package(ZLIB REQUIRED)
 else()
-  set(ZLIB_FOUND)
+  set(ZLIB_FOUND ON)
   set(ZLIB_LIBRARY zlibstatic)
   set(ZLIB_LIBRARIES ${ZLIB_LIBRARY})
   set(ZLIB_INCLUDE_DIRS
```

That's what's done for other bundled libraries when the shared library would have been found with `find_package`, like libpng:

https://github.com/aseprite/aseprite/blob/f710603f9903679f48622185fec4bc937bd6d1d1/CMakeLists.txt#L214-L218

and freetype:

https://github.com/aseprite/aseprite/blob/f710603f9903679f48622185fec4bc937bd6d1d1/CMakeLists.txt#L253-L256

and harfbuzz:

https://github.com/aseprite/aseprite/blob/f710603f9903679f48622185fec4bc937bd6d1d1/CMakeLists.txt#L263-L266

and jpeg:

https://github.com/aseprite/aseprite/blob/f710603f9903679f48622185fec4bc937bd6d1d1/CMakeLists.txt#L281-L284

**Comment by dacap** [comment]
Hi @ryandesign, if you send a PR, the GitHub actions/CI can test the change. Would you mind to create a PR?
