### ISSUE TITLE
Can't Update Compiled Aseprite to 1.3.10.1. 

### ISSUE THREAD

**Issue by NandoBroquiGames** [aseprite/aseprite#4866]
**Description:**

So, I decided to update my aseprite so I had the recent version, but something weird is happening.

At first, I decided to install through the 1.3.10.1 zip file called Aseprite-v1.3.10.1-Source.zip, but my computer was detecting it as a virus and refusing to download, so, I decided I would try to download the other source code, the only called source code. This other one wasn't detected as a virus, but when I tried to compile it, it only was giving errors about missing files from a folder called laf (which I verified and was empty).

To finalize, I decided to disable the Windows protection to download the "original" source code to test it on VirusTotal, and it was really detecting this following virus[...]:

![Captura de tela 2024-12-04 144111](https://github.com/user-attachments/assets/2f5983fd-6094-4379-9339-17483aad300b)

I don't know what's happening as this never happened with any other build I've download. Do you guys have any suggestions on what can I do to override this error?

**Aseprite and System:**

Aseprite Version: 1.3.10.1 Source Code (the virus problem also happens with 1.3.11 beta 2, but I haven't tested if it can compile)
System: Windows 11

**Comment by dacap** [comment]
This is a false positive. In case your antivirus doesn't trust a `.zip` file with text only files, you can clone the Git repository, that should avoid the virus detection at all.

**Comment by NandoBroquiGames** [comment]
> This is a false positive. In case your antivirus doesn't trust a `.zip` file with text only files, you can clone the Git repository, that should avoid the virus detection at all.

Then why this virus doesn't exist in the other sources?

**Comment by dacap** [comment]
> Then why this virus doesn't exist in the other sources?

I don't know. This is something you should ask to Jianmin antivirus developers. There are two reasons I think this is a false positive:
1) This is a .zip file (not an executable), and it contains text only files (so basically there is nothing in the file that could crash/hack your computer, only a bad .zip decoder could do that)
2) This is the only antivirus that is detecting it as a virus.

And I repeat, if you don't trust the file, you can clone the repository.

**Comment by NandoBroquiGames** [comment]
> > Then why this virus doesn't exist in the other sources?
> 
> I don't know. This is something you should ask to Jianmin antivirus developers. There are two reasons I think this is a false positive:
> 
> 1. This is a .zip file (not an executable), and it contains text only files (so basically there is nothing in the file that could crash/hack your computer, only a bad .zip decoder could do that)
> 2. This is the only antivirus that is detecting it as a virus.
> 
> And I repeat, if you don't trust the file, you can clone the repository.

Bro, have you actually read the full post? Not only there's a virus but the source code is incomplete. Here's what it shows:

```Your Aseprite repository is incomplete, initialize submodules using:

    git submodule update --init --recursive```

**Comment by dacap** [comment]
> but the source code is incomplete

This is a problem with GitHub Download ZIP to get the source code, the instructions say the only two ways to get the source code: https://github.com/aseprite/aseprite/blob/main/INSTALL.md#get-the-source-code

Anyway you give me an idea to avoid this kind of situation, I'll add some extra information in the error message about the source code.

**Comment by NandoBroquiGames** [comment]
> > but the source code is incomplete
> 
> This is a problem with GitHub Download ZIP to get the source code, the instructions say the only two ways to get the source code: https://github.com/aseprite/aseprite/blob/main/INSTALL.md#get-the-source-code
> 
> Anyway you give me an idea to avoid this kind of situation, I'll add some extra information in the error message about the source code.

No problem, man, I was able to update it. Thank you for helping!
