### ISSUE TITLE
Some tools leaving unwanted trails 

### ISSUE THREAD

**Issue by Joshirostar** [aseprite/aseprite#4881]
Whenever I use a tool it leaves a trail with the tool shape in the drawing, this gets fixed by zooming in or out and noticed it happening as soon as I tried using the diagonal mirror features, im using the default dark theme if that helps for something.

 Aseprite v1.3.11-beta2 and System version 10.0.22631 compilación 22631

* Aseprite version: 1.3.11-beta2 steam 
* System: Microsoft Windows 11 Pro, x64-based PC

https://github.com/user-attachments/assets/93fb1589-46ed-4aa5-8881-2a2e22be4006

I hope the video is visible, had to compress it to make it fit the file size. also apologies for the music, forgot to turn it off.

**Comment by dacap** [comment]
Hi @Joshirostar, this issue is already fixed for the next beta release with #4802 / #4825
