### ISSUE TITLE
[Suggestion] Add a way to toggle old text tool system

### ISSUE THREAD

**Issue by oliviathevampire** [aseprite/aseprite#4906]
Describe your bug report or feature request here
Currently in the new betas there is a new text tool, but personally I hate it so much as it's a lot more work than before

### Aseprite and System version

* Aseprite version: v1.3.11-beta2-x64
* System: Windows 11

**Comment by dacap** [comment]
The previous behavior is still available from the Edit > Insert Text option. You can associate the T key with this menu option from Edit > Keyboard Shortcuts > Menus if you wish.
