### ISSUE TITLE
Timeline Markers for Multiple Animations

### ISSUE THREAD

**Issue by davidfrankel** [aseprite/aseprite#500]
Feature request:

User can insert markers between frames on timeline.  If there is a marker before the currently selected frame -- and/or a marker after the selected frame, Aseprite treats that frame range (from first marker or beginning of timeline to second marker or end of timeline) as a Loop Section.

This way, if your timeline contains several animations, you can quickly preview any one simply by selecting a frame inside it and hitting PLAY.

Setting a Loop Section manually would override markers.

**Comment by dacap** [comment]
Already available in master branch
