### ISSUE TITLE
Nearest neighbor resize algorithm relies on undefined behavior

### ISSUE THREAD

**Issue by tobihan** [aseprite/aseprite#502]
The test TEST(ResizeImage, NearestNeighborInterp) fails on Debian on i386 architectures [1].

The image gets resized to this:

000011100
000011100
000011100
111111111
111111111
111111111
000011100
000011100
000011100

instead of the expected

000111000
000111000
000111000
111111111
111111111
111111111
000111000
000111000
000111000

I suspect that's because of the undefined result of floor(3./3.) that is called in resize_image(). Maybe you should add some small shifts to make this well-defined.

Best,
Tobias

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=765291

**Comment by dacap** [comment]
Hi @tobihan, could you please check if 97d42de6962d370a8880dc65e60896b37851b8a5 fixes this issue.

**Comment by tobihan** [comment]
Hi. Yes, that fixes it, thanks!
