### ISSUE TITLE
Requesting more options for Onion Skinning

### ISSUE THREAD

**Issue by makapixel** [aseprite/aseprite#526]
Please please please make an option to place the onion skin alpha behind the image of the editable frame when onion skin is enabled. This can work with large 2D traditional animation because of the large dimensions but it's detrimental to animating with pixels. It just becomes to visually noisy. 

I have pasted an example of what the onion skin looks like behind the editable image.
![onion skin example](https://cloud.githubusercontent.com/assets/9758581/5056190/00ab7f12-6c2a-11e4-9091-ee37aa7ba30a.gif)

This is how it currently works(I realize you can turn the opacity and stepping up/down) As you can see it's very hard to edit
![onion skin example aseprite](https://cloud.githubusercontent.com/assets/9758581/5056213/b54309da-6c2b-11e4-9e3a-94c05bf7c74d.gif)

If I try to draw on top of this my actual pen is drawing behind the onion skin layer. In order to get a clear picture of what I'm drawing I have to turn off the onion skin.

**Comment by DragonDePlatino** [comment]
I was going to consider posting this issue myself, but makapixel summed it up very nicely. The old method of onion skinning (like in v0.9.5) was very easy to use, but the newer method is cluttered and unusable. Please add some options that will allow us to replicate the old onion skinning!

**Comment by dacap** [comment]
If someone want to give a try to this change before the next release, please contact me at support@aseprite.org and I'll package a special build for you.
