### ISSUE TITLE
1.0.6 make - missing files - Ubuntu 14.04

### ISSUE THREAD

**Issue by keizgon** [aseprite/aseprite#534]
I use to use this tool in Ubuntu 14.04 (older prepackaged .deb install), but am interested in compiling this version (1.0.6). I have followed the install.md, but I cannot run make and get a proper build.

Error:

[ 0%] Building CXX object app/CMakeFiles/app-lib.dir/app.o

In file included from /home/keizgon/Applications/aseprite-1.0.6/src/app/app.cpp:20:0:

/home/keizgon/Applications/aseprite-1.0.6/src/./config.h:56:26: fatal error: allegro/base.h: No such file or directory

#include <allegro/base.h>

^

compilation terminated.

make[2]: *** [app/CMakeFiles/app-lib.dir/app.o] Error 1

make[1]: *** [app/CMakeFiles/app-lib.dir/all] Error 2

make: *** [all] Error 2

**Comment by dacap** [comment]
No more feedback given.
