### ISSUE TITLE
--ignore-empty doesn't work with --save-as

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#551]
The `--ignore-empty` flag was done for `--sheet`, but if we want to save a sequence of .png files, it could be useful to avoid saving empty frames when `--save-as` is used.

EDIT: reported here too https://community.aseprite.org/t/command-ignore-empty-frames-when-saving/2096

**Comment by bfloch** [comment]
That answers my question. I was under the impression using a palette was the problem but this seems to be more logical.
