### ISSUE TITLE
Remap/match colors between old palette -> new one

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#563]
Add a way to remap/match colors from the previous palette to the new one when:

* We load a new palette
* We change one (or several) palette color entries
* The palette change in some other way (e.g. we create an optimized palette with Quantize button)

The dialog to "match" colors should have options to easily change how the remap will be done. E.g. it could contain wires from the old palette to the new one and we can re-wire these "old palette entry" <-> "new palette entry" connections.

**Comment by dacap** [comment]
There are situations that the automatic-remap cannot be done and should popup a manual remap dialog. For example, now palettes can contain (e.g.) 16 colors, if we've used all those colors in the image, and then we remove the color with index 1, we've 15 colors, ¿where should we remap that index 1 to?

**Comment by metaphore** [comment]
Hey @dacap,
So, can I somehow interchange palettes with automatic color remapping?
I use one indexed palette with 6 colors for all game assets and let's say want to see how they will look with different palette on separated temporary collage document.
