### ISSUE TITLE
Add support for double-wide pixels

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#567]
We should be able to specify pixel ratio for the image. (E.g. to draw images like [these ones](https://twitter.com/notch/status/405699793629880320))

**Comment by DragonDePlatino** [comment]
Hey, that's a really great idea! It would certainly help with working with C64 images.

If I could make a suggestion, perhaps you could preview the double-sized image by holding a key? Or maybe pressing a key could toggle between normal and double-pixels?

**Comment by wiebow** [comment]
Has this ever been followed up? Or is it a lost feature? I for one would REALLY like to have this.

**Comment by dacap** [comment]
Hi @wiebow, actually this feature doesn't have a high priority. Anyway you can :+1: it so we can keep track of how much interest there is about it.

**Comment by wiebow** [comment]
It will be a blessing for C64 pixelers who use Linux, as the majority of pixelling tools for the C64 are on Windows. :(

**Comment by ewenig** [comment]
Seconding this, I recently switched from Grafx2 to Aseprite, and wide pixel editing is an indispensable tool for C64 multicolor graphics editing.

**Comment by dacap** [comment]
I'll start working on this.

**Comment by DragonDePlatino** [comment]
Great! This'll definitely help out us C64 spriters. I occasionally do C64
work in ASEprite so this'll be an immense help.

**Comment by wiebow** [comment]
That is great to hear!!!! Thanks so very much!

**Comment by dacap** [comment]
Some progress in this feature: https://twitter.com/aseprite/status/734869697896845312/photo/1

**Comment by wiebow** [comment]
That's great. So happy :)

**Comment by dacap** [comment]
This will be released in v1.2-beta1 in a couple of weeks
