### ISSUE TITLE
Option to export only visible layers

### ISSUE THREAD

**Issue by davidfrankel** [aseprite/aseprite#570]
**What do you need to do?**

When exporting sprite sheet, have option to either export all layers (as it is now) or only export visible layers.

**How would you like to do it?**

In the Export Sprite Sheet dialog, there would be a checkbox labeled "Include Hidden Layers."

**Comment by dacap** [comment]
From v1.1 the rendering code (used in the Editor and in save/export) was integrated and the *Export Sprite Sheet* exports only visible layers. Anyway an option to select which layers to export would be great. Something like:

1. Visible layers
2. Selected layers
3. All layers
