### ISSUE TITLE
No arguments to 'rgba'

### ISSUE THREAD

**Issue by rfajfar** [aseprite/aseprite#573]
Getting this at the `make aseprite` step.

`[ 24%] Building CXX object src/render/CMakeFiles/render-lib.dir/quantization.cpp.o`

![aseprite-error](https://cloud.githubusercontent.com/assets/2836852/5593518/856e6548-9213-11e4-8166-1100cbb4b5ee.png)

Every other error after that (`'rgba' was not declared in this scope`) seems to be chained to the first one.

**Comment by dacap** [comment]
Should be fixed with #572
