### ISSUE TITLE
Cannot specify default Grid Size setting

### ISSUE THREAD

**Issue by DragonDePlatino** [aseprite/aseprite#577]
In previous versions of ASEprite, whenever you change the grid size, the program would remember the size and apply it to newly opened images. But in the newest version, the grid size is set to 16x16 every single time you open an image. I'm currently working with many, many tilesheet images with 24x24 graphics, so it is inconvenient having to change this setting every time I open the file.

An option in aseprite.ini to set the default grid size or toggle grid size memory would be nice.

**Comment by dacap** [comment]
Hi @DragonDePlatino! That's true. Now grid settings are saved in a per-file basis and we cannot set the default grid size. At this moment, my recommendation is that you could create a `template.ase` with a 24x24 grid (the settings will be kept for that specific file). And then, when you want to create a new file, open `template.ase` and then you can use `Save As...`.

**Comment by dacap** [comment]
Actually this is already working again using View > Grid > Grid Settings when there is no other document opened (e.g. on the Home tab).
