### ISSUE TITLE
Unix compile 1.10 fails

### ISSUE THREAD

**Issue by GRRRRRRRRRR** [aseprite/aseprite#581]
Using GCC 4.7 I get a bunch of errors when compiling.

Compile log: pastebin.com/dKgSt14T

I didn't get any errors when compiling the same source on Windows using MSVC.

Tried looking it up a little, apparently MSVC isn't working 100% truthfully to the C++11 standard when it comes to string expressions and allows a little more liberal use of those expressions.

I know OSX/Unix compiles aren't the norm but I might as well ask.

Am I missing something?

Edit: Using GCC47 on Linux Mint

**Comment by aaptel** [comment]
I can confirm as of dc5fcd625ab it still doesn't work. It compiles fine for me if I checkout v1.0.8.
I will try to bisect.
gcc 4.9.2 20141224 on archlinux.

**Comment by aaptel** [comment]
I've used a simple `make` to bisect.

    $ git bisect start master v1.0.8
    $ bit bisect run sh -c '( cd build ; make -j8 aseprite )'
    e55865843e20d42bca3b3505ba49e529ee25193a is the first bad commit
    commit e55865843e20d42bca3b3505ba49e529ee25193a
    Author: David Capello <davidcapello@gmail.com>
    Date:   Sun Jan 18 22:05:33 2015 -0300
     
        Replace undo impl: replace undoers with cmds

**Comment by aaptel** [comment]
The error comes from stream swap in src/app/cmd/copy_region.cpp. I have a similar error compiling the code from [this question on stackoverflow](http://stackoverflow.com/questions/12015899/why-are-move-semantics-for-a-class-containing-a-stdstringstream-causing-compil) which means GCC doesn't implement the move constructor for std::stringstream. This [bug report on the GCC bugtracker](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54316) says it's fixed and it should be in the next GCC release (v5).

The simplest solution is to try clang or wait, I guess. There is a workaround in the SO answers involving pointers, if anyone wants to try.

**Comment by GRRRRRRRRRR** [comment]
Alright, thanks for taking the time to investigate and confirm. Guess I'll have to make do with 1.0.8.

**Comment by aaptel** [comment]
David commited a workaround, master branch now builds successfully for me.

**Comment by GRRRRRRRRRR** [comment]
I'll give it a shot tomorrow and let you know if it works for me.

**Comment by GRRRRRRRRRR** [comment]
Can confirm, master branch now compiles just fine. Thanks David and aaptel!

**Comment by dacap** [comment]
You're welcome @GRRRRRRRRRR and thanks to @aaptel for the help!
