### ISSUE TITLE
Cel position at 0xffff, 0xffff (-1,-1) in .ase file + cell property window

### ISSUE THREAD

**Issue by aaptel** [aseprite/aseprite#582]
While writing a basic ASE file reader python module I found a cell with a position at -1, -1.
I'm not sure if it's a bug or an undocumented feature. 

![](http://diobla.info/stuff/star-aseprite-issue.png)

I can't test on the latest master (see issue #581) but this is true on at least v1.0.8.

The following diff shows how you can check for it while loading a file.

    diff --git a/src/app/file/ase_format.cpp b/src/app/file/ase_format.cpp
    index 9eb443c..8e2704e 100644
    --- a/src/app/file/ase_format.cpp
    +++ b/src/app/file/ase_format.cpp
    @@ -1001,6 +1001,7 @@ static Cel* ase_file_read_cel_chunk(FILE* f, Sprite* sprite, FrameNumber frame,
       LayerIndex layer_index = LayerIndex(fgetw(f));
       int x = ((short)fgetw(f));
       int y = ((short)fgetw(f));
    +  printf("XY %d %d\n", x, y);
       int opacity = fgetc(f);
       int cel_type = fgetw(f);
       Layer* layer;

The cast to short turns the unsigned value (0xffff) to -1 and I could not find where this edgecase is handled (or if it's even handled).

The ASE file is a regular file made from the editor. You can find it here: http://diobla.info/stuff/star-aseprite-issue.ase

**Comment by dacap** [comment]
Hi there! This is possible. Cels can be moved outside the sprite bounds. It's an expected behavior. So basically a Cel position can be in the `-32767 <= x  <= 32767` range.

**Comment by aaptel** [comment]
The ASE File Format description is wrong then. Also there are no sections about palettes, I had to look in aseprite source to find out about them.

I'll try to contribute some info about that and release my python reader.

Thanks for your time and for aseprite! :)

**Comment by dacap** [comment]
Don't worry, I'll add more information about the Cel position (`SIGNED WORD`) in `ase.txt` file. About the palettes, from the `Introduction` section:

    Color palettes are in FLI color chunks (it could be type=11 or type=4). For color
    depths more than 8bpp, palettes are optional. See fli.txt for details.

I think it would be better if we've the palette chunk in the same `ase.txt` just to avoid confusion or the need of `fli.txt` file. Thanks for your help.
