### ISSUE TITLE
export layers (for adventure game)

### ISSUE THREAD

**Issue by gcmartijn** [aseprite/aseprite#583]
H! all,

I'm busy with a classic retro (c64/amiga) adventure game, and now i'm trying to export the layers as .png files like this.

First I draw the full game inside aseprite, including some minimal background animations (like a flying bird in the sky)

layers in asprite
[football][*]
[tree][*]
[bird with animation][*][*][*][*][*]
[background][*]
** short note below

Then I want to export all visible layers to this
/directory/football.png
/directory/tree.png
/directory/bird_with_animation.png (the full animation)
/directory/background.png
** short note below

Then in my game I load everything and fix the initial x,y coordinates (because I don't have them)

Or the export must give me a extra file like this
/directory/export.txt
football.png;40,45
tree.png;34,64
bird_with_animation.png;0,2
background.png;0,0

** I hope that the other feature request is almost ready to create folder layer groups.
then the export is like this.
[animals][bird with animation]
/directory/animals/bird_with_animation.png

**Comment by dacap** [comment]
Hi @gcmartijn! Have you try the [Command Line Interface](http://www.aseprite.org/cli/)? I think that you could [create a .bat/.sh file](http://www.aseprite.org/cli/#Automating-the-process-(-bat-or-sh-files)) to [export each layer](http://www.aseprite.org/cli/#Export-one-layers-to-PNG/GIF-files). Let me know if it does help.

**Comment by gcmartijn** [comment]
@dacap I think that's what I need, will test it later.

**Comment by dacap** [comment]
:+1: I'll close this issue. You can create then a new one if you need some improvement.
