### ISSUE TITLE
Set animation not loop on export gif

### ISSUE THREAD

**Issue by alivegames** [aseprite/aseprite#585]
now export gif is looped by default,please add a option to make it not loop.
BTW,I really wanted v1.1!!

**Comment by dacap** [comment]
Hi! I'll try to add this new option in v1.0. About v1.1, would you like to try a beta? Send me an email to support@aseprite.org ;)

**Comment by bberak** [comment]
Hi @dacap,

I know this issue is really old - but I can't find a way to remove the loop when exporting a .gif (both via the UI and the CLI).

Is this feature still available?

Cheers!

**Comment by dacap** [comment]
Hi @bberak, via the UI you can specify it in the GIF alert just after selecting the gif file:

![screen shot 2018-03-20 at 08 39 24](https://user-images.githubusercontent.com/39654/37652436-47acdb64-2c1a-11e8-8cd0-cb10aa9a9956.png)

There is no option via CLI at the moment 😢 I'll take note about this in my to-do list.

A possible workaround would be to indicate a long delay in the last frame.

**Comment by bberak** [comment]
Thanks for the quick reply @dacap - that'll work just fine indeed :)

CLI option (for me personally) is just a nice to have..

Cheers!
