### ISSUE TITLE
Ubuntu 12.04 make fails cc1plus error: unrecognized command line option ‘-std=gnu++11’

### ISSUE THREAD

**Issue by Bloodyaugust** [aseprite/aseprite#588]
As above. I have a sneaking feeling this isn't solvable by any issues with the source... but an hour of fruitless searching on the '-std=gnu++11' option have led me to ask here.

cmake version 2.8.7

**Comment by dacap** [comment]
Hi! Maybe that flag is wrong. What `gcc --version` does Ubuntu include? Could you try -std=c++11 or -std=c++0x [here](https://github.com/aseprite/aseprite/blob/master/src/CMakeLists.txt#L154)?

**Comment by Bloodyaugust** [comment]
I'm on 4.6.3.
I did use cmake with the "Unix Makefiles" option... perhaps I should try another?

**Comment by dacap** [comment]
`Unix Makefiles` should be fine. Did you try to change `-std=gnu++11` with `-std=c++11` or `-std=c++0x`?

[https://github.com/aseprite/aseprite/blob/master/src/CMakeLists.txt#L154](https://github.com/aseprite/aseprite/blob/master/src/CMakeLists.txt#L154)

    if(UNIX)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wno-switch -std=gnu++11")
    endif()

**Comment by dacap** [comment]
Hi @Bloodyaugust. I've see this issue and as the C++11 support in 4.6 is not as complete as gcc 4.8, you should use gcc 4.8. You can install gcc-4.8 package:

    sudo apt-get install g++-4.8

And then, *before* you run cmake:

    export CXX="g++-4.8"
