### ISSUE TITLE
Compiled version doesn't work on Retina OS X

### ISSUE THREAD

**Issue by blackmiaool** [aseprite/aseprite#589]
![image](https://cloud.githubusercontent.com/assets/5674588/6013132/6c7b1676-ab8b-11e4-9a22-1a0cf6ea5920.png)
I changed third_party/gtest/include/gtest/internal/gtest-internal.h and src/undo/undo_tests.cpp to finish make.It works,but seems not support retina(rmbp).

**Comment by dacap** [comment]
Thanks for reporting this. I don't have a retina display to test it, so I will need some help in this one. Would you like to contact me at support@aseprite.org?

**Comment by dacap** [comment]
Another thing, could you try to change `Edit > Preferences > Screen Scale` to `1:1` just to test how it works?

**Comment by dacap** [comment]
It's probable that if the application is not inside a bundle with a Info.plist, OS X thinks that the app is high-DPI aware (supports retina display). And if it has a Info.plist, it isn't high-DPI aware (there is [a special Info.plist property](https://github.com/LaurentGomila/SFML/issues/353#issuecomment-17574344) to specify this explicitly).

I don't know if there is a possibility to specify a Info.plist outside an app bundle. Anyway I'm thinking that the next version v1.1 should be high-DPI aware. At the moment my recommendation for you is to do a "post compilation" process, copying the generated Aseprite binary inside the trial app bundle.

**Comment by CharlesLillo** [comment]
I'm on retina, and by copying over the data file in the build folder as well as the Aseprite binary to the trial version, I was able to get it working. Just copying the binary caused it to seg fault - in case anyone else is also looking for a workaround.

**Comment by dacap** [comment]
Thanks for the extra info @CharlesLillo

**Comment by monodevx** [comment]
Error: In file included from /home/mono/aseprite/third_party/IXWebSocket/ixwebsocket/IXWebSocket.cpp:11
So many errors
I tried to resolve

**Comment by kotx** [comment]
> I'm on retina, and by copying over the data file from the build folder as well as the Aseprite binary to the trial version, I was able to get it working. Just copying the binary caused it to seg fault - in case anyone else is also looking for a workaround.

If anybody gets the "X is damaged and can't be opened" popup, just run `xattr -cr /Applications/Aseprite.app` to clear attributes on the folder recursively.
