### ISSUE TITLE
Eyedropper/pick colors from desktop

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#594]
Eyedropper should work for the whole desktop/other windows (to pick colors from other programs).

EDIT: requested in the community site too: https://community.aseprite.org/t/implement-eyedropper-tool-that-you-can-use-outside-aseprite/2431

**Comment by ElnuDev** [comment]
@dacap What is the status of this? It would be really nice to see this as feature, it would save a lot of time when picking color palettes.

**Comment by dacap** [comment]
This will be available in the next release v1.3 (at least for Windows and macOS)

**Comment by ThomasMoonKang** [comment]
If this had a keyboard shortcut and/or worked with the normal/quick eyedropper, i.e. by holding Right Click, that would be amazing
