### ISSUE TITLE
Build error on Linux

### ISSUE THREAD

**Issue by gerroon** [aseprite/aseprite#604]
Hi

I am getting make error

[  0%] Built target simpleini
[  0%] Built target scripting-lib
[  1%] Built target she
[  3%] Built target zlib
[  3%] Built target cfg-lib
[  3%] Building CXX object src/base/CMakeFiles/base-lib.dir/exception.cpp.o
/SRC/_temp/aseprite/src/base/exception.cpp: In constructor ‘base::Exception::Exception(const char*, ...)’:
/SRC/_temp/aseprite/src/base/exception.cpp:27:28: error: ‘strchr’ was not declared in this scope
     if (!strchr(format, '%')) {
                            ^
src/base/CMakeFiles/base-lib.dir/build.make:192: recipe for target 'src/base/CMakeFiles/base-lib.dir/exception.cpp.o' failed
make[2]: *** [src/base/CMakeFiles/base-lib.dir/exception.cpp.o] Error 1
CMakeFiles/Makefile2:3159: recipe for target 'src/base/CMakeFiles/base-lib.dir/all' failed
make[1]: *** [src/base/CMakeFiles/base-lib.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Bobhostern** [comment]
I'm getting similar errors.
Going through an replacing them with my shoddy "standard" functions seems a bit iffy.
I gave up on the TinyXML error, though...
![screenshot - 03022015 - 10 07 45 pm](https://cloud.githubusercontent.com/assets/1479994/6456426/a9c13738-c128-11e4-9e57-3557227f3055.png)

**Comment by iPhysicX** [comment]
There are a lot of missing libs (mostly <climits>, <string.h>, <iostream>). I add them manually in my clone-dir. Google the function, where your error occurs. You will find the necessary lib.

**Comment by Bobhostern** [comment]
Found a solution:
I basically went through the codebase, and replaced all instances of the cstring header with one of my own design:
    #include "stddef.h"
	#include "stdlib.h"

	int strcmp ( const char * str1, const char * str2 )
	{
		int counter = 0;
		while(str1[counter] != NULL && str2[counter] != NULL)
		{
			if(str1[counter] > str2[counter])
				return -1;
			else if(str1[counter] < str2[counter])
				return 1;
			counter++;
		}

		if(str1[counter] > str2[counter])
				return -1;
		else if(str1[counter] < str2[counter])
			return 1;
		else
			return 0;
	}

	size_t strlen ( const char * str )
	{
		size_t counter = 0;
		while(str[counter] != NULL)
			counter++;
		return counter;
	}

	void * memcpy ( void * destination, const void * source, size_t num )
	{
		for(int i = 0; i < num; i++)
		{
			((char*)destination)[i] = ((char*)source)[i];
		}

		return destination;
	}

	int memcmp ( const void * ptr1, const void * ptr2, size_t num )
	{
		int counter = 0;
		for(int i = 0; i < num; i++)
		{
			if(((char*)ptr1)[i] > ((char*)ptr2)[i])
				return -1;
			else if(((char*)ptr1)[i] < ((char*)ptr2)[i])
				return 1;
		}
		return 0;
	}

	void * memset ( void * ptr, int value, size_t num )
	{
		for(int i = 0; i < num; i++)
		{
			((char*)ptr)[i] = (char)value;
		}

		return ptr;
	}

	void * memmove ( void * destination, const void * source, size_t num )
	{
		void* tmp = calloc(1, num);
		for(int i = 0; i < num; i++)
		{
			((char*)tmp)[i] = ((char*)source)[i];
		}

		for(int i = 0; i < num; i++)
		{
			((char*)destination)[i] = ((char*)tmp)[i];
		}

		free(tmp);

		return destination;
	}

	const char * strchr ( const char * str, int character ) {
		const char* res = NULL;
		int counter = 0;
		while(str[counter] != NULL) {
			if(str[counter] == (char)character) {
				res = &str[counter];
				break;
			}
			counter++;
		}

		return res;
	}

	char * strchr ( char * str, int character ) {
		char* res = NULL;
		int counter = 0;
		while(str[counter] != NULL) {
			if(str[counter] == (char)character) {
				res = &str[counter];
				break;
			}
			counter++;
		}

		return res;
	}

	const char * strpbrk ( const char * str1, const char * str2 )
	{
		const char* ptr = NULL;
		int counter = 0;
		while(str2[counter] != NULL) {
			const char* tmpptr = strchr(str1, (int)str2[counter]);
			if(ptr == NULL || (tmpptr < ptr && tmpptr != NULL)) ptr = tmpptr;
			counter++;
		}

		return ptr;
	}

	char * strpbrk ( char * str1, const char * str2 )
	{
		char* ptr = NULL;
		int counter = 0;
		while(str2[counter] != NULL) {
			char* tmpptr = strchr(str1, (int)str2[counter]);
			if(ptr == NULL || (tmpptr < ptr && tmpptr != NULL)) ptr = tmpptr;
			counter++;
		}

		return ptr;
	}

**Comment by Bobhostern** [comment]
Found one of the problems:
There are two files in the "base" directory named string.h and time.h, which interfere with the includes of cstring and fnctl.h. A solution is to rename string.h and time.h to string.hpp and time.hpp, and changing all instances of the reference to them to their hpp form.

**Comment by dacap** [comment]
The current master is compiling on Ubuntu, are you getting some error?

**Comment by Bobhostern** [comment]
Yes, I was getting errors about strstr, memcpy, and various string.h (and thus cstring) methods not being declared. Turns out that, at least for me, <cstring> was including "base/string.h" rather than the system's "string.h", due to include paths.

**Comment by dacap** [comment]
I'll check later just in case. The whole base/ library should include <cstring> instead of <string.h>

**Comment by Bobhostern** [comment]
The files that are affected are:
  * signal.h -> signal.hpp (wait.h)
  * time.h -> time.hpp (fnctl.h)
  * string.h -> string.hpp (cstring)

**Comment by dacap** [comment]
What Linux distro and specific gcc version are you using?

**Comment by gerroon** [comment]
@dacap 
I am on Debian Jessie 64, gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by dacap** [comment]
Hi @gerroon, could you try the latest commit in master branch? I think it should work in that distro, anyway I'll create a VM tomorrow with Debian to give it a try.
