### ISSUE TITLE
More integration with OS X features

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#605]
Drag and drop of files into the app window, and an option into Open With menu.

**Comment by bitinn** [comment]
casting my vote on this, especially file drag-and-drop :)

**Comment by dacap** [comment]
At the moment you can drag-and-drop files to the Aseprite icon in the dock bar and it should be open on Aseprite.

**Comment by trollworkout** [comment]
i support this drag and drop to app

**Comment by trollworkout** [comment]
another feature would be adding a finder component that previews .ase files

**Comment by dacap** [comment]
Integration with Finder will be implemented in #834
