### ISSUE TITLE
Script error?

### ISSUE THREAD

**Issue by AsukaLangleyfag** [aseprite/aseprite#608]
With cmake generating of solution for VS 2013/2015 while compilation I met a strange bug: Error cannot open file '..\lib\..\libcurl.lib' so it can't pass tests and build an aseprite.exe. Workaround: just copy libcurl.lib to ..\build and it works, but...

**Comment by dacap** [comment]
Hi @AsukaLangleyfag, there is a fix for this issue already in the master branch (commit 2c408e4c98b9cc0d775309f17100cd0b882f4671). See #606 for more information.
