### ISSUE TITLE
Tablet Pen Eraser

### ISSUE THREAD

**Issue by gra0009** [aseprite/aseprite#610]
I don't know if its already added or solved but so far, Aseprite doesn't detect the eraser side of my Cintiq Pen. When i flip my pen, it treats the eraser as a standard left mouse click. Does it lack Pen flipping or is there some setting that I'm missing which allows this?

**Comment by dacap** [comment]
Hi @gra0009, thanks to report this issue. I'll be testing it soon. (I've a intuos pen to test it.)

**Comment by dacap** [comment]
Finally fixed with 56e663bca437c39e463e21d3bbcc0493bcfbf783

**Comment by Xodetaetl** [comment]
> Linux will be supported in a near future

Do you have it on your roadmap or I should open a new issue?

**Comment by dacap** [comment]
Hi @Xodetaetl, I'll leave a note on #139 about this.

**Comment by dudewithgames** [comment]
Aseprite doesn't recognize my tablet pen eraser as well... and my model I'm using is the intuos pro 2017 edition with the "new" 2.0 pen

**Comment by dacap** [comment]
@dudewithgames if you are on Windows or macOS, the eraser tip should be recognized, are you on Linux?

**Comment by Blathers** [comment]
Hello, I'm on Windows 10 using a Cintiq Companion 2, and Aseprite doesn't recognize my eraser either. I'm using the latest version.

**Comment by dacap** [comment]
hi @Blathers, could you please try the `--debug` parameter? [Check this](https://www.aseprite.org/docs/debug/) then send me the Output.txt file to support@aseprite.org

**Comment by 0DeltaWaves** [comment]
I'm on Windows 10. Going into Wacom tablet properties and adding Aseprite to the list of programs and making sure the eraser is set to "erase" fixed the issue for me.

![image](https://user-images.githubusercontent.com/82335536/187488170-90766038-1ec6-45dd-8fa1-b47351570eeb.png)
