### ISSUE TITLE
Can't resize window in Xubuntu.

### ISSUE THREAD

**Issue by Nsheppard01** [aseprite/aseprite#611]
The version of Aseprite in the ubuntu package manager can't be resized, and the window defaults to unusably tiny. I was able to fix this by editing the config file, but it would be nice if this didn't happen in the first place.

**Comment by dacap** [comment]
Hi @Nsheppard01, know issue about prepackaged Linux version on Debian-based distros. [More info](http://www.aseprite.org/faq/#I-cannot-resize-or-maximize-the-window-on-Linux-why)

**Comment by jsaak** [comment]
workaround, set window dimensions in config file:
edit ~/.config/aseprite/aseprite.ini

```
[GfxMode]
Maximized = no
Width = 1695
Height = 951
Depth = 32
ScreenScale = 1
```
