### ISSUE TITLE
--split-layers 'bug' fixed width and height

### ISSUE THREAD

**Issue by gcmartijn** [aseprite/aseprite#612]
I'm trying to use aseprite as program to creating my game and creating (atlas) sheets using --split-layers --sheet but there is a 'bug' so I can't use it :(

Because every layer is using a fixed width and height (the asprite document width and height).
So the sheet is way to big with many transparent gaps.

I was trying to solve this by using a external program to create the final sheet.
So only using --split-layers, without --sheet. But then I get the same problem, a fixed w and h for each layer.

What I (and probably more users) need is that every layer export using --split-layers have there own width and height, calculated by the first and last pixel width and height.
After that is fixed, we can use --sheet to make the atlas output way smaller.

:)
Thanks

**Comment by dacap** [comment]
Hi @gcmartijn, have you tried using `--trim` option? It might be useful to compact your data (anyway you will need the `--data file.json` to know the trimmed rectangles).

**Comment by gcmartijn** [comment]
@dacap ow din't know about the --trim (and --help) option, I thought the docs where up to date ;)
Trim does the job.
