### ISSUE TITLE
Could NOT find V8 (missing:  V8_BASE V8_SNAPSHOT) on Fedora 21

### ISSUE THREAD

**Issue by martinkg** [aseprite/aseprite#615]
get this error on Fedora 21:

-- Could NOT find V8 (missing:  V8_BASE V8_SNAPSHOT) 
CMake Warning at src/scripting/CMakeLists.txt:14 (message):
  V8 not found, compiling without JS scripting support

v8-devel package is installed

# rpm -ql v8-devel
/usr/include/v8
/usr/include/v8-debug.h
/usr/include/v8-preparser.h
/usr/include/v8-profiler.h
/usr/include/v8-testing.h
/usr/include/v8.h
/usr/include/v8/extensions
/usr/include/v8/extensions/externalize-string-extension.h
/usr/include/v8/extensions/gc-extension.h
/usr/include/v8/extensions/statistics-extension.h
/usr/include/v8stdint.h
/usr/lib/python2.7/site-packages/js2c.py
/usr/lib/python2.7/site-packages/js2c.pyc
/usr/lib/python2.7/site-packages/js2c.pyo
/usr/lib/python2.7/site-packages/jsmin.py
/usr/lib/python2.7/site-packages/jsmin.pyc
/usr/lib/python2.7/site-packages/jsmin.pyo
/usr/lib64/libv8.so
/usr/lib64/libv8preparser.so

rpm -ql v8
/usr/bin/d8
/usr/lib64/libv8.so.3
/usr/lib64/libv8.so.3.14
/usr/lib64/libv8.so.3.14.5
/usr/lib64/libv8preparser.so.3
/usr/lib64/libv8preparser.so.3.14
/usr/lib64/libv8preparser.so.3.14.5
/usr/share/doc/v8
/usr/share/doc/v8/AUTHORS
/usr/share/doc/v8/ChangeLog
/usr/share/doc/v8/LICENSE

**Comment by dacap** [comment]
Hi @martinkg, Aseprite doesn't use V8 at this moment (this was added just for testing scripting capabilities). You can (and should) ignore this warning. (Also I'm planning to remove V8 completely and start testing mruby for scripting.)
