### ISSUE TITLE
fatal error: SimpleIni.h: No such file or directory on Fedora 21

### ISSUE THREAD

**Issue by martinkg** [aseprite/aseprite#616]
get this error when compiling the recent version from today on Fedora 21

Building CXX object src/base/CMakeFiles/base-lib.dir/cfile.cpp.o
cd /home/martin/rpmbuild/BUILD/aseprite-e506387dad10d616b7c2103e5da5698680e9818a/build/src/base && /usr/bin/c++   -DENABLE_SAVE -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG -I/home/martin/rpmbuild/BUILD/aseprite-e506387dad10d616b7c2103e5da5698680e9818a/build/third_party/zlib -I/home/martin/rpmbuild/BUILD/aseprite-e506387dad10d616b7c2103e5da5698680e9818a/third_party/libpng -I/home/martin/rpmbuild/BUILD/aseprite-e506387dad10d616b7c2103e5da5698680e9818a/src/. -I/home/martin/rpmbuild/BUILD/aseprite-e506387dad10d616b7c2103e5da5698680e9818a/src/.. -I/home/martin/rpmbuild/BUILD/aseprite-e506387dad10d616b7c2103e5da5698680e9818a/src/../third_party -I/usr/include/pixman-1 -I/home/martin/rpmbuild/BUILD/aseprite-e506387dad10d616b7c2103e5da5698680e9818a/third_party/simpleini -I/home/martin/rpmbuild/BUILD/aseprite-e506387dad10d616b7c2103e5da5698680e9818a/build/src/base    -o CMakeFiles/base-lib.dir/cfile.cpp.o -c /home/martin/rpmbuild/BUILD/aseprite-e506387dad10d616b7c2103e5da5698680e9818a/src/base/cfile.cpp
/home/martin/rpmbuild/BUILD/aseprite-e506387dad10d616b7c2103e5da5698680e9818a/src/cfg/cfg.cpp:16:23: fatal error: SimpleIni.h: No such file or directory
 #include "SimpleIni.h"
                       ^
compilation terminated.
/usr/bin/cmake -E cmake_progress_report /home/martin/rpmbuild/BUILD/aseprite-e506387dad10d616b7c2103e5da5698680e9818a/build/CMakeFiles 
[ 14%] Building CXX object src/base/CMakeFiles/base-lib.dir/chrono.cpp.o

**Comment by dacap** [comment]
Hi @martinkg, see #550, it's the same problem.
