### ISSUE TITLE
fatal error: SimpleIni.h: No such file or directory on Fedora 21

### ISSUE THREAD

**Issue by martinkg** [aseprite/aseprite#617]
I get the same error message even though I checked out with the following commands:

# git clone --recursive https://github.com/aseprite/aseprite.git aseprite-1.0.9-e506387
# cd aseprite-1.0.9-e506387
# git submodule init
# git submodule update

[ 13%] Building CXX object src/cfg/CMakeFiles/cfg-lib.dir/cfg.cpp.o
cd /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/src/cfg && /usr/bin/c++   -DENABLE_SAVE -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -Dcfg_lib_EXPORTS -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG -fPIC -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/third_party/zlib -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/third_party/libpng -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src/. -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src/.. -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src/../third_party -I/usr/include/pixman-1 -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/third_party/simpleini -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/src/base    -o CMakeFiles/cfg-lib.dir/cfg.cpp.o -c /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src/cfg/cfg.cpp
/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src/cfg/cfg.cpp:16:23: fatal error: SimpleIni.h: No such file or directory
 #include "SimpleIni.h"
                       ^
compilation terminated.
/usr/bin/cmake -E cmake_progress_report /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/CMakeFiles 
[ 13%] Building CXX object src/doc/CMakeFiles/doc-lib.dir/algorithm/flip_image.cpp.o
cd /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/src/doc && /usr/bin/c++   -DENABLE_SAVE -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -Ddoc_lib_EXPORTS -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG -fPIC -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/third_party/zlib -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/third_party/libpng -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src/. -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src/.. -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src/../third_party -I/usr/include/pixman-1 -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/third_party/simpleini -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/src/base    -o CMakeFiles/doc-lib.dir/algorithm/flip_image.cpp.o -c /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src/doc/algorithm/flip_image.cpp
src/cfg/CMakeFiles/cfg-lib.dir/build.make:57: recipe for target 'src/cfg/CMakeFiles/cfg-lib.dir/cfg.cpp.o' failed
make[2]: *** [src/cfg/CMakeFiles/cfg-lib.dir/cfg.cpp.o] Error 1
make[2]: Leaving directory '/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build'
CMakeFiles/Makefile2:2942: recipe for target 'src/cfg/CMakeFiles/cfg-lib.dir/all' failed
make[1]: *** [src/cfg/CMakeFiles/cfg-lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/cmake -E cmake_progress_report /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/CMakeFiles 
[ 13%] Building CXX object src/doc/CMakeFiles/doc-lib.dir/algorithm/floodfill.cpp.o

**Comment by martinkg** [comment]
the file SimpleIni.h is located in the folder aseprite-1.0.9-e506387/third_party/simpleini/SimpleIni.h
but in my package.spec (rpm package) the third_party directory is deleted before the cmake command, this is the cause for error message.

**Comment by dacap** [comment]
Sorry, what is that `package.spec` thing? (I'm not familiar with Fedora) and how does it affect an unrelated Git clone/directory?

**Comment by martinkg** [comment]
to build a binary package file under Fedora you can write a file aseprite.spec, with this file you
can build the binary package.
e.q. such a file looks like this: https://www.dropbox.com/s/adb1y7h689zvssy/aseprite.spec?dl=0

**Comment by martinkg** [comment]
And in my aseprite.spec i removed the third_party folder, because Fedora does not allow bundled library in the package.

**Comment by dacap** [comment]
OK. I'll close this issue as it looks like a specific problem packing Aseprite for Fedora.

**Comment by Mailaender** [comment]
I get the same error on openSUSE.

```
aseprite-1.1-beta1/src/cfg/cfg.cpp:16:23: fatal error: SimpleIni.h: No such file or directory
#include "SimpleIni.h"
         ^
compilation terminated.
```

It also doesn't matter if you delete `third_party` or not from the released tar-balls as the directory is empty:

![image](https://cloud.githubusercontent.com/assets/756669/7100425/726328c4-e021-11e4-8088-b0c93a60b9bd.png)

Your source tar-balls are busted. This is not a Fedora problem.

**Comment by martinkg** [comment]
Am Freitag, den 10.04.2015, 23:06 -0700 schrieb Matthias Mailänder:
> I get the same error on openSUSE.
> 
> aseprite-1.1-beta1/src/cfg/cfg.cpp:16:23: fatal error: SimpleIni.h: No such file or directory
> #include "SimpleIni.h"
>          ^
> compilation terminated.
> 
> It also doesn't matter if you delete third_party or not from the
> released tar-balls as the directory is empty:
> 
> image
> 
> Your source tar-balls are busted. This is not a Fedora problem.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

i use the following command to check out the source code:

git clone --recursive https://github.com/aseprite/aseprite.git \
aseprite-1.0.9-b4d97a4

this error only happens if i don't delete the directory third_party.
when i delete the directory third_party, the code compiles 92 % with the
following error message:
( already reported https://github.com/aseprite/aseprite/issues/618 )

[ 92%] Building CXX object
src/app/CMakeFiles/app-lib.dir/ui/main_menu_bar.cpp.o
cd /home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/build/src/app
&& /usr/bin/c++   -DENABLE_SAVE -DHAVE_CONFIG_H -DNDEBUG
-DPNG_NO_MMX_CODE -Dapp_lib_EXPORTS -O2 -g -pipe -Wall
-Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions
-fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches
-m64 -mtune=generic -pthread -Wall -Wno-switch -std=gnu++11 -O2 -g
-DNDEBUG -fPIC
-I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/build/third_party/zlib -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/third_party/libpng -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/src/. -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/src/.. -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/src/../third_party -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/third_party/giflib/lib -I/usr/include/pixman-1 -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/third_party/simpleini -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/build/src/base -I/home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/build/src/app    -o CMakeFiles/app-lib.dir/ui/main_menu_bar.cpp.o -c /home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/src/app/ui/main_menu_bar.cpp
/home/martin/rpmbuild/BUILD/aseprite-1.0.9-b4d97a4/src/app/ui/home_view.cpp:139:34: error: no 'void app::HomeView::onCheckingUpdates()' member function declared in class 'app::HomeView'
 void HomeView::onCheckingUpdates()


Fedora Distribution Policies for unbundled Libraries
http://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries

**Comment by Mailaender** [comment]
Have you already packaged https://github.com/brofield/simpleini for Fedora?

**Comment by martinkg** [comment]
Am Samstag, den 11.04.2015, 01:19 -0700 schrieb Matthias Mailänder:
> Have you already packaged https://github.com/brofield/simpleini for
> Fedora?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

not yet, but if have time to do this.

**Comment by Mailaender** [comment]
Your bug report makes little sense then. You delete the bundled library you don't have any replacement yet and wonder why it fails to build. ;)
