### ISSUE TITLE
Linking CXX executable ../bin/thread_tests fails on Fedora 21

### ISSUE THREAD

**Issue by martinkg** [aseprite/aseprite#618]
linking fails on Fedora 21:

Linking CXX executable ../bin/thread_tests
cd /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/thread_tests.dir/link.txt --verbose=1
/usr/bin/c++   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pthread -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG   -Wl,-z,relro  CMakeFiles/thread_tests.dir/base/thread_tests.cpp.o  -o ../bin/thread_tests -rdynamic -lgtest ../lib/libbase-lib.so -L/usr/lib64 -lalleg -Wl,-rpath,/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/lib 
make[2]: Leaving directory '/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build'
/usr/bin/cmake -E cmake_progress_report /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/CMakeFiles 
[ 42%] Built target thread_tests
make -f src/CMakeFiles/unique_ptr_tests.dir/build.make src/CMakeFiles/unique_ptr_tests.dir/depend
make[2]: Entering directory '/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build'
cd /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387 /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/src /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/src/CMakeFiles/unique_ptr_tests.dir/DependInfo.cmake --color=
In file included from /usr/include/c++/4.9.2/tr1/functional:39:0,
                 from /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src/undo/undo_tests.cpp:20:
/usr/include/c++/4.9.2/tr1/tuple:130:11: error: redefinition of 'class std::tuple< <template-parameter-1-1> >'
     class tuple : public _Tuple_impl<0, _Elements...>
           ^
Dependee "/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/src/CMakeFiles/unique_ptr_tests.dir/DependInfo.cmake" is newer than depender "/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/src/CMakeFiles/unique_ptr_tests.dir/depend.internal".
Dependee "/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/src/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/build/src/CMakeFiles/unique_ptr_tests.dir/depend.internal".
Scanning dependencies of target unique_ptr_tests
In file included from /usr/include/gtest/internal/gtest-port.h:548:0,
                 from /usr/include/gtest/internal/gtest-internal.h:40,
                 from /usr/include/gtest/gtest.h:58,
                 from /home/martin/rpmbuild/BUILD/aseprite-1.0.9-e506387/src/undo/undo_tests.cpp:11:
/usr/include/c++/4.9.2/tuple:390:11: error: previous definition of 'class std::tuple< <template-parameter-1-1> >'
     class tuple : public _Tuple_impl<0, _Elements...>

**Comment by dacap** [comment]
Hi @martinkg. I would prefer just one issue for all these problems related to Fedora :smile: (at least I think that you can comment on closed issues anyway and I can reopen them if it's needed).

I don't compile on Linux regularly (I compile on Ubuntu from time to time), so I will try to do my best guessing this problem: It looks like google test library doesn't work with that specific gcc version, I can recommend you to just compile aseprite (`make aseprite`) so you can avoid compiling tests.

**Comment by martinkg** [comment]
ok, i compiled now with:
make aseprite %{?_smp_mflags} VERBOSE=1

but the compilation fails now with this error message:

[ 77%] Building CXX object src/app/CMakeFiles/app-lib.dir/document_location.cpp.o
cd /home/martin/rpmbuild/BUILD/aseprite-e506387/build/src/app && /usr/bin/c++   -DENABLE_SAVE -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -Dapp_lib_EXPORTS -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pthread -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG -fPIC -I/home/martin/rpmbuild/BUILD/aseprite-e506387/build/third_party/zlib -I/home/martin/rpmbuild/BUILD/aseprite-e506387/third_party/libpng -I/home/martin/rpmbuild/BUILD/aseprite-e506387/src/. -I/home/martin/rpmbuild/BUILD/aseprite-e506387/src/.. -I/home/martin/rpmbuild/BUILD/aseprite-e506387/src/../third_party -I/usr/include/pixman-1 -I/home/martin/rpmbuild/BUILD/aseprite-e506387/third_party/simpleini -I/home/martin/rpmbuild/BUILD/aseprite-e506387/build/src/base -I/home/martin/rpmbuild/BUILD/aseprite-e506387/build/src/app    -o CMakeFiles/app-lib.dir/document_location.cpp.o -c /home/martin/rpmbuild/BUILD/aseprite-e506387/src/app/document_location.cpp
In file included from /home/martin/rpmbuild/BUILD/aseprite-e506387/src/./gfx/clip.h:12:0,
                 from /home/martin/rpmbuild/BUILD/aseprite-e506387/src/./doc/image.h:16,
                 from /home/martin/rpmbuild/BUILD/aseprite-e506387/src/./doc/image_ref.h:12,
                 from /home/martin/rpmbuild/BUILD/aseprite-e506387/src/./doc/cel_data.h:12,
                 from /home/martin/rpmbuild/BUILD/aseprite-e506387/src/./doc/sprite.h:12,
                 from /home/martin/rpmbuild/BUILD/aseprite-e506387/src/./doc/sprites.h:15,
                 from /home/martin/rpmbuild/BUILD/aseprite-e506387/src/./doc/document.h:17,
                 from /home/martin/rpmbuild/BUILD/aseprite-e506387/src/./app/document.h:18,
                 from /home/martin/rpmbuild/BUILD/aseprite-e506387/src/app/document_exporter.cpp:16:
/home/martin/rpmbuild/BUILD/aseprite-e506387/src/./gfx/rect.h: In instantiation of 'const gfx::RectT<T>& gfx::RectT<T>::operator|=(const gfx::RectT<T>&) [with T = int]':
/home/martin/rpmbuild/BUILD/aseprite-e506387/src/app/document_exporter.cpp:440:23:   required from here
/home/martin/rpmbuild/BUILD/aseprite-e506387/src/./gfx/rect.h:257:30: error: 'operator=' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
     operator=(createUnion(rc));
                              ^
/home/martin/rpmbuild/BUILD/aseprite-e506387/src/./gfx/rect.h:257:30: note: declarations in dependent base 'gfx::RectT<int>' are not found by unqualified lookup
/home/martin/rpmbuild/BUILD/aseprite-e506387/src/./gfx/rect.h:257:30: note: use 'this->operator=' instead
/usr/bin/cmake -E cmake_progress_report /home/martin/rpmbuild/BUILD/aseprite-e506387/build/CMakeFiles

**Comment by martinkg** [comment]
i could solve this error message with the following patch.

--- aseprite-e506387/src/gfx/rect.h.orig	2015-03-25 16:35:43.330639244 +0100
+++ aseprite-e506387/src/gfx/rect.h	2015-03-25 16:37:35.760627479 +0100
@@ -254,7 +254,7 @@
   }
 
   const RectT& operator|=(const RectT& rc) {
-    operator=(createUnion(rc));
+    this->operator=(createUnion(rc));
     return *this;
   }
 
but then, the next problem occurs:

[ 92%] Building CXX object src/app/CMakeFiles/app-lib.dir/ui/main_menu_bar.cpp.o
cd /home/martin/rpmbuild/BUILD/aseprite-e506387/build/src/app && /usr/bin/c++   -DENABLE_SAVE -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -Dapp_lib_EXPORTS -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pthread -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG -fPIC -I/home/martin/rpmbuild/BUILD/aseprite-e506387/build/third_party/zlib -I/home/martin/rpmbuild/BUILD/aseprite-e506387/third_party/libpng -I/home/martin/rpmbuild/BUILD/aseprite-e506387/src/. -I/home/martin/rpmbuild/BUILD/aseprite-e506387/src/.. -I/home/martin/rpmbuild/BUILD/aseprite-e506387/src/../third_party -I/home/martin/rpmbuild/BUILD/aseprite-e506387/third_party/giflib/lib -I/usr/include/pixman-1 -I/home/martin/rpmbuild/BUILD/aseprite-e506387/third_party/simpleini -I/home/martin/rpmbuild/BUILD/aseprite-e506387/build/src/base -I/home/martin/rpmbuild/BUILD/aseprite-e506387/build/src/app    -o CMakeFiles/app-lib.dir/ui/main_menu_bar.cpp.o -c /home/martin/rpmbuild/BUILD/aseprite-e506387/src/app/ui/main_menu_bar.cpp
/home/martin/rpmbuild/BUILD/aseprite-e506387/src/app/ui/home_view.cpp:110:34: error: no 'void app::HomeView::onCheckingUpdates()' member function declared in class 'app::HomeView'
 void HomeView::onCheckingUpdates()
                                  ^
/home/martin/rpmbuild/BUILD/aseprite-e506387/src/app/ui/home_view.cpp:118:27: error: no 'void app::HomeView::onUpToDate()' member function declared in class app::HomeView'
 void HomeView::onUpToDate()
                           ^
/home/martin/rpmbuild/BUILD/aseprite-e506387/src/app/ui/home_view.cpp:126:78: error: no 'void app::HomeView::onNewUpdate(const string&, const string&)' member function declared in class 'app::HomeView'
 void HomeView::onNewUpdate(const std::string& url, const std::string& version)
                                                                              ^
/usr/bin/cmake -E cmake_progress_report /home/martin/rpmbuild/BUILD/aseprite-e506387/build/CMakeFiles 
src/app/CMakeFiles/app-lib.dir/build.make:6241: recipe for target 'src/app/CMakeFiles/app-lib.dir/ui/home_view.cpp.o' failed
make[3]: *** [src/app/CMakeFiles/app-lib.dir/ui/home_view.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....

**Comment by martinkg** [comment]
new problem with recent sources:
....
../lib/libapp-lib.so: undefined reference to `net::HttpRequest::HttpRequest(std::string const&)'
../lib/libapp-lib.so: undefined reference to `net::HttpRequest::send(net::HttpResponse&)'
../lib/libapp-lib.so: undefined reference to `net::HttpRequest::~HttpRequest()'
....

[100%] [100%] Building C object src/CMakeFiles/aseprite.dir/main/xpm_icon.c.o
cd /home/martin/rpmbuild/BUILD/aseprite-73fa7b2/build/src && /usr/bin/cc  -DENABLE_SAVE -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pthread -O2 -g -DNDEBUG -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/build/third_party/zlib -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/third_party/libpng -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/src/. -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/src/.. -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/src/../third_party -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/third_party/giflib/lib -I/usr/include/pixman-1 -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/third_party/simpleini -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/build/src/base    -o CMakeFiles/aseprite.dir/main/xpm_icon.c.o   -c /home/martin/rpmbuild/BUILD/aseprite-73fa7b2/src/main/xpm_icon.c
Building CXX object src/CMakeFiles/aseprite.dir/main/main.cpp.o
cd /home/martin/rpmbuild/BUILD/aseprite-73fa7b2/build/src && /usr/bin/c++   -DENABLE_SAVE -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pthread -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/build/third_party/zlib -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/third_party/libpng -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/src/. -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/src/.. -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/src/../third_party -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/third_party/giflib/lib -I/usr/include/pixman-1 -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/third_party/simpleini -I/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/build/src/base    -o CMakeFiles/aseprite.dir/main/main.cpp.o -c /home/martin/rpmbuild/BUILD/aseprite-73fa7b2/src/main/main.cpp
Linking CXX executable ../bin/aseprite
cd /home/martin/rpmbuild/BUILD/aseprite-73fa7b2/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/aseprite.dir/link.txt --verbose=1
/usr/bin/c++   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pthread -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG   -Wl,-z,relro  CMakeFiles/aseprite.dir/main/main.cpp.o CMakeFiles/aseprite.dir/main/xpm_icon.c.o  -o ../bin/aseprite -rdynamic ../lib/libapp-lib.so ../lib/libfixmath-lib.so ../lib/libcfg-lib.so ../lib/libcss-lib.so ../lib/libdoc-lib.so ../lib/librender-lib.so ../lib/libscripting-lib.so ../lib/libundo-lib.so ../lib/libfilters-lib.so ../lib/libui-lib.so ../lib/libshe.so ../lib/libgfx-lib.so ../lib/libbase-lib.so ../lib/libsimpleini.so -ljpeg -lz -lpng -lz ../lib/libgiflib.so -ltinyxml -lloadpng -lpixman-1 -lcurl -L/usr/lib64 -lalleg -lpng -ltinyxml -lloadpng -lpixman-1 -lcurl -Wl,-rpath,/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/build/lib: 
../lib/libapp-lib.so: undefined reference to `net::HttpRequest::HttpRequest(std::string const&)'
../lib/libapp-lib.so: undefined reference to `net::HttpRequest::send(net::HttpResponse&)'
../lib/libapp-lib.so: undefined reference to `net::HttpRequest::~HttpRequest()'
collect2: error: ld returned 1 exit status
src/CMakeFiles/aseprite.dir/build.make:141: recipe for target 'bin/aseprite' failed
make[3]: *** [bin/aseprite] Error 1
make[3]: Leaving directory '/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/build'
CMakeFiles/Makefile2:245: recipe for target 'src/CMakeFiles/aseprite.dir/all' failed
make[2]: *** [src/CMakeFiles/aseprite.dir/all] Error 2
make[2]: Leaving directory '/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/build'
CMakeFiles/Makefile2:257: recipe for target 'src/CMakeFiles/aseprite.dir/rule' failed
make[1]: *** [src/CMakeFiles/aseprite.dir/rule] Error 2
make[1]: Leaving directory '/home/martin/rpmbuild/BUILD/aseprite-73fa7b2/build'
Makefile:154: recipe for target 'aseprite' failed
make: *** [aseprite] Error 2

**Comment by martinkg** [comment]
used cmake flag -DUSE_SHARED_GIFLIB=ON to use the systemwide giflib from Fedora 21,
but this fails with the following error message:

[ 78%] Building CXX object src/app/CMakeFiles/app-lib.dir/file/jpeg_format.cpp.o
cd /home/martin/rpmbuild/BUILD/aseprite-9bf11e0/build/src/app && /usr/bin/c++   -DENABLE_SAVE -DHAVE_CONFIG_H -DNDEBUG -DPNG_NO_MMX_CODE -Dapp_lib_EXPORTS -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pthread -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG -fPIC -I/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/build/third_party/zlib -I/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/third_party/libpng -I/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/src/. -I/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/src/.. -I/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/src/../third_party -I/usr/include/pixman-1 -I/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/third_party/simpleini -I/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/build/src/base -I/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/build/src/app    -o CMakeFiles/app-lib.dir/file/jpeg_format.cpp.o -c /home/martin/rpmbuild/BUILD/aseprite-9bf11e0/src/app/file/jpeg_format.cpp
/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/src/app/file/ico_format.cpp: In member function 'virtual bool app::IcoFormat::onLoad(app::FileOp*)':
/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/src/app/file/ico_format.cpp:142:20: warning: variable 'bmpHeader' set but not used [-Wunused-but-set-variable]
   BITMAPINFOHEADER bmpHeader;
                    ^
/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/src/app/file/gif_format.cpp: In member function 'virtual bool app::GifFormat::onLoad(app::FileOp*)':
/home/martin/rpmbuild/BUILD/aseprite-9bf11e0/src/app/file/gif_format.cpp:136:108: error: too many arguments to function 'GifFileType* DGifOpenFileHandle(int)'
   GifFilePtr gif_file(DGifOpenFileHandle(open_file_descriptor_with_exception(fop->filename, "rb"), &errCode), &DGifCloseFile);
                                                                                                            ^
In file included from /home/martin/rpmbuild/BUILD/aseprite-9bf11e0/src/app/file/gif_format.cpp:32:0:
/usr/include/gif_lib.h:185:14: note: declared here
 GifFileType *DGifOpenFileHandle(int GifFileHandle);

**Comment by Mailaender** [comment]
@martinkg You will need `BuildRequires:  giflib-devel >= 5.1.0`. See https://build.opensuse.org/package/show/games:tools/giflib for a .spec file.

**Comment by Mailaender** [comment]
How did you solve the HttpRequest linking error?

```
Linking CXX executable ../bin/aseprite
cd /home/abuild/rpmbuild/BUILD/aseprite-1.1beta3/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/aseprite.dir/link.txt --verbose=1
/usr/bin/c++   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG    CMakeFiles/aseprite.dir/main/main.cpp.o CMakeFiles/aseprite.dir/main/xpm_icon.c.o  -o ../bin/aseprite -rdynamic ../lib/libapp-lib.a ../lib/libfixmath-lib.a ../lib/libcfg-lib.a ../lib/libcss-lib.a ../lib/libdoc-lib.a ../lib/librender-lib.a ../lib/libscripting-lib.a ../lib/libundo-lib.a ../lib/libfilters-lib.a ../lib/libui-lib.a ../lib/libshe.a ../lib/libgfx-lib.a ../lib/libbase-lib.a ../lib/libsimpleini.a ../lib/liballeg.a -ljpeg -lz -lpng -lz -lgif -ltinyxml -lloadpng -lpixman-1 -lcurl -lpthread -lm -lX11 -lXext -lXcursor -lXpm -lXxf86vm -lXxf86dga -lrt -lX11 -lXext -lXcursor -lXpm -lXxf86vm -lXxf86dga -lrt -lpng -lgif -ltinyxml -lloadpng -lpixman-1 -lcurl -lpthread 
../lib/libapp-lib.a(http_loader.cpp.o): In function `app::HttpLoader::threadHttpRequest()':
/home/abuild/rpmbuild/BUILD/aseprite-1.1beta3/src/app/res/http_loader.cpp:67: undefined reference to `net::HttpRequest::HttpRequest(std::string const&)'
/home/abuild/rpmbuild/BUILD/aseprite-1.1beta3/src/app/res/http_loader.cpp:69: undefined reference to `net::HttpRequest::send(net::HttpResponse&)'
/home/abuild/rpmbuild/BUILD/aseprite-1.1beta3/src/app/res/http_loader.cpp:67: undefined reference to `net::HttpRequest::~HttpRequest()'
/home/abuild/rpmbuild/BUILD/aseprite-1.1beta3/src/app/res/http_loader.cpp:67: undefined reference to `net::HttpRequest::~HttpRequest()'
collect2: error: ld returned 1 exit status
```

**Comment by martinkg** [comment]
Am Sonntag, den 17.05.2015, 05:21 -0700 schrieb Matthias Mailänder:
> @martinkg You will need BuildRequires: giflib-devel >= 5.1.0. See
> https://build.opensuse.org/package/show/games:tools/giflib for a .spec
> file.
> 
> —
> Reply to this email directly or view it on GitHub.

I know this, but it's not available for Fedora.
https://bugzilla.redhat.com/show_bug.cgi?id=822844

**Comment by martinkg** [comment]
Am Sonntag, den 17.05.2015, 05:22 -0700 schrieb Matthias Mailänder:
> How did you solve the HttpRequest linking error?
> 
> Linking CXX executable ../bin/aseprite
> cd /home/abuild/rpmbuild/BUILD/aseprite-1.1beta3/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/aseprite.dir/link.txt --verbose=1
> /usr/bin/c++   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG    CMakeFiles/aseprite.dir/main/main.cpp.o CMakeFiles/aseprite.dir/main/xpm_icon.c.o  -o ../bin/aseprite -rdynamic ../lib/libapp-lib.a ../lib/libfixmath-lib.a ../lib/libcfg-lib.a ../lib/libcss-lib.a ../lib/libdoc-lib.a ../lib/librender-lib.a ../lib/libscripting-lib.a ../lib/libundo-lib.a ../lib/libfilters-lib.a ../lib/libui-lib.a ../lib/libshe.a ../lib/libgfx-lib.a ../lib/libbase-lib.a ../lib/libsimpleini.a ../lib/liballeg.a -ljpeg -lz -lpng -lz -lgif -ltinyxml -lloadpng -lpixman-1 -lcurl -lpthread -lm -lX11 -lXext -lXcursor -lXpm -lXxf86vm -lXxf86dga -lrt -lX11 -lXext -lXcursor -lXpm -lXxf86vm -lXxf86dga -lrt -lpng -lgif -ltinyxml -lloadpng -lpixman-1 -lcurl -lpthread 
> ../lib/libapp-lib.a(http_loader.cpp.o): In function `app::HttpLoader::threadHttpRequest()':
> /home/abuild/rpmbuild/BUILD/aseprite-1.1beta3/src/app/res/http_loader.cpp:67: undefined reference to `net::HttpRequest::HttpRequest(std::string const&)'
> /home/abuild/rpmbuild/BUILD/aseprite-1.1beta3/src/app/res/http_loader.cpp:69: undefined reference to `net::HttpRequest::send(net::HttpResponse&)'
> /home/abuild/rpmbuild/BUILD/aseprite-1.1beta3/src/app/res/http_loader.cpp:67: undefined reference to `net::HttpRequest::~HttpRequest()'
> /home/abuild/rpmbuild/BUILD/aseprite-1.1beta3/src/app/res/http_loader.cpp:67: undefined reference to `net::HttpRequest::~HttpRequest()'
> collect2: error: ld returned 1 exit status
> 
> —
> Reply to this email directly or view it on GitHub.


Unfortunately not.

**Comment by Mailaender** [comment]
I split it into an individual ticket as this conversation is junked up too much. https://github.com/aseprite/aseprite/issues/696

**Comment by dacap** [comment]
I'll try to compile Aseprite on Fedora today, so I'll see this issue and #696.
