### ISSUE TITLE
Unable to start during Win7 remote desktop session

### ISSUE THREAD

**Issue by PixelBangs** [aseprite/aseprite#619]
Version:
aseprite 1.0.9 (Paid Gumroad installer)

Machine:
Windows 7 Pro x64
Xeon W3550
12 GB DDR3 ECC

Issue:
-I have the above version installed on the above machine.
-I start a remote desktop session and connect to the above machine.
-I then launch aseprite (Known working when used in a normal windows session)
-I immediately receive the following pop-up:
    ![image](https://cloud.githubusercontent.com/assets/11654775/6836319/f35ff620-d30e-11e4-96a9-b35308ab10a5.png)
-After clicking 'Okay' I get the following pop-up:
    ![image](https://cloud.githubusercontent.com/assets/11654775/6836347/108d5a9e-d30f-11e4-85d3-9e20cb622dcd.png)

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Aseprite.exe
  Application Version:	1.0.9.0
  Application Timestamp:	54cf941a
  Fault Module Name:	Aseprite.exe
  Fault Module Version:	1.0.9.0
  Fault Module Timestamp:	54cf941a
  Exception Code:	c0000005
  Exception Offset:	00010318
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

- Then I am sad :(

**Comment by dacap** [comment]
Hi @PixelBangs, I've tested this in a Win8 -> Win8 remote desktop session and it works.
What screen configuration (width, height, bits per pixel) are you using for the remote session?

**Comment by dacap** [comment]
Please comment this issue if you are able to reproduce this problem with the latest version (v1.1.6).
