### ISSUE TITLE
Select, Color Range should give some kind of feedback when it is not allowed

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#627]
If you attempt to use select, Color Range on a frame/layer without a cel, nothing happens. It took me a little while to figure out an empty cel was the reason. (At first I thought it was a bug where it only worked on the first frame, because that frame happened to have cels for both layers, while all other frames had no cel in the second layer)

Aseprite 1.1 beta on Windows Vista 32bit

**Comment by dacap** [comment]
Nice catch. I'll disable that command when there is no cel. (And I'll try to add some kind of feedback to show why each command is disabled.)

**Comment by dacap** [comment]
I've added #631 related to this issue
