### ISSUE TITLE
Compilation issues using visual studio

### ISSUE THREAD

**Issue by wighawag** [aseprite/aseprite#630]
Hi got error of the following types

Error	1	error C2894: templates cannot be declared to have 'C' linkage	C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtr1common	15	1	base-lib

Error	69	error C2733: 'cos' : second C linkage of overloaded function not allowed	C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtgmath.h	96	1	base-lib

Error	138	error C2873: 'strstr' : symbol cannot be used in a using-declaration	C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\cstring	24	1	base-lib

Error	152	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xstring	315	1	base-lib

and some more.

I did "cmake ." in teh aseprite directory and just launch the run button in visual studio (RelWidthDebInfo selected)

any idea what could fix this ?

**Comment by wighawag** [comment]
By the way using the tag v1.0.9 I got it compiling and running without problem

**Comment by dacap** [comment]
I think this should be already fixed in master branch
