### ISSUE TITLE
Request: Holding Ctrl while dragging a tab creates a duplicate view

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#634]
Reading twitter: https://twitter.com/aseprite/status/588711851677995008

I realized it'd be neat if we could just hold ctrl to duplicate a view for a tab. It would somewhat match the behavior where if you ctrl+drag a cel or layer it will duplicate it where it's dragged.

A mockup: 
![duplicatetabmockup](https://cloud.githubusercontent.com/assets/8582123/7192798/e7dcb45a-e466-11e4-9bb3-ed139fc1b7b1.gif)

**Comment by dacap** [comment]
Hi there! It's planned :smile: it didn't make the first betas, but it will be included in the next beta for sure!

(And Alt+drag and drop for Mac OS X)
