### ISSUE TITLE
Feature Request: 1:1 scale zoom.

### ISSUE THREAD

**Issue by Nsheppard01** [aseprite/aseprite#638]
Being able to zoom out to 1:1 would be helpful for editing large images (such as maps) and getting a feel for the actual size of the image. I keep having to switch between editing the picture in Aesprite and previewing it in an external image viewer.

**Comment by dacap** [comment]
I think you could try to change the *screen scale* option to 1:1 from Edit > Preferences: http://www.aseprite.org/faq/#Why-do-I-see-double-sized-pixels

**Comment by Nsheppard01** [comment]
That option doesn't appear in my built. Is this another one of those "We don't support the ubuntu repository." things?

**Comment by KasumiArai** [comment]
Nsheppard01, you did not specify which version of the program you are using. (I assume 0.9.5?) If you locate your Aseprite settings file (~/.asepriterc on linux?) you should find a setting "ScreenScale = 2" which you can edit and save as "ScreenScale = 1" Reload the program and you will get 1:1 pixels.

**Comment by Nsheppard01** [comment]
Yeah it's 0.9.5 and I just found that option in ~/.aespriterc the same place I had to go to fix the screen size issue on ubuntu. 

What's the best way to get the newest version? Are there any other improved features?

**Comment by dacap** [comment]
If you are on Linux the only (official) way to get the new version is compiling it ([we don't distribute official packages for Linux, sorry](http://www.aseprite.org/faq/#Is-there-an-official-package-for-Linux)). The improvements are listed in the [release notes page](http://www.aseprite.org/release-notes/) (you can start looking from the bottom of the page to see what was introduced in v1.0)

**Comment by vegeta897** [comment]
Is there any chance the preview window could get the ability to zoom out to 1:1 screen pixels *without* changing the UI scale to 100%? I prefer using 200% UI scale, but I'd also like to see what my sprite will look like when viewed outside of the program at actual size. I understand this would probably mean the preview window would need to be rendered separately from the rest of the UI (or however that works).

**Comment by Nsheppard01** [comment]
You can change the pixel scale, and then change the UI scale to 200%
separately. That's what I do now.

**Comment by dacap** [comment]
@vegeta897 hi there! I don't have plans to remove the UI Elements Scaling option, also I've two things to say about this: 1) I'd like to improve it a little bit (there are some UI elements that don't look 100% accurate/same as in 100% scaling), and 2) I've plans for a new skin/theme for bigger resolutions/non-pixelated.

**Comment by vegeta897** [comment]
@dacap Thanks for the info, I'm looking forward to the new skin.
