### ISSUE TITLE
atlas export request feature

### ISSUE THREAD

**Issue by gcmartijn** [aseprite/aseprite#641]
As I mention in other posts, I'm creating a game editor using your atlas-files and its working oke.
Except what I don't like is that I need to re-create your atlas files, by using a script before I can use them.

This is because the game framework that handle the JSON files do sort the keys by alphabet.
One way you can say it is that you never can be sure that a JSON file parser, loads the frames list in the exact order.

A small example say more than many words.
{"frames":{
 "ground": {
    "frame": { "x": 0, "y": 0, "w": 2048, "h": 417 },
    "rotated": false,
    "trimmed": true,
    "spriteSourceSize": { "x": 0, "y": 351, "w": 2048, "h": 417 },
    "sourceSize": { "w": 2048, "h": 768 },
    "duration": 100
   },
   "air": {
    "frame": { "x": 0, "y": 417, "w": 2048, "h": 376 },
    "rotated": false,
    "trimmed": true,
    "spriteSourceSize": { "x": 0, "y": 0, "w": 2048, "h": 376 },
    "sourceSize": { "w": 2048, "h": 768 },
    "duration": 100
   }
 }
}

Multiple json parsers output
- air
- ground

How to fix this, if you change or give a option that the output is a array like this.
--use-array-output

{"frames":[
  { "ground": {
    "frame": { "x": 0, "y": 0, "w": 2048, "h": 417 },
    "rotated": false,
    "trimmed": true,
    "spriteSourceSize": { "x": 0, "y": 351, "w": 2048, "h": 417 },
    "sourceSize": { "w": 2048, "h": 768 },
    "duration": 100
   }},
   {"air": {
    "frame": { "x": 0, "y": 417, "w": 2048, "h": 376 },
    "rotated": false,
    "trimmed": true,
    "spriteSourceSize": { "x": 0, "y": 0, "w": 2048, "h": 376 },
    "sourceSize": { "w": 2048, "h": 768 },
    "duration": 100
   }}
 ]
}

This is how other atlas creators do it, and that the load order is 100% safe.
And I guess easy to create for your ;)

Thanks !

**Comment by dacap** [comment]
Hi there! In your example you have used an array of dictionaries with one key <-> value. I see JSON files like [these](https://github.com/HaxeFlixel/flixel-demos/blob/master/Editors/TexturePackerAtlas/assets/anim-trim.json) where it's an array of objects (with a "filename" to identify each item).

As there are so many formats as possible, I'm thinking that a template system could be the best option. (I don't know the most common texture atlas formats, Unity 2D, cocos 2d, haxeflixel, etc. I'd need to find some reference.)

**Comment by gcmartijn** [comment]
There is one program which have all options (to many) a atlas file can have.
There is not a rule how to create atlas files, the only problem are the json parsers.

https://www.codeandweb.com/texturepacker/documentation
(there is a free version)

But the main essence when you start TexturePacker is to choose your framework.
The generic options is
- JSON (array)
- JSON (Hash)
- XML (generic)

http://imgur.com/ctl78bl

I think you cover all json parsers when you support array and hash.

**Comment by dacap** [comment]
I'll add the json array format, but as in my previous comment: an array of objects with `filename` attribute. For your example, the output would be something like this:
```
{"frames":[
{
"filename":"ground",
"frame": { "x": 0, "y": 0, "w": 2048, "h": 417 },
"rotated": false,
"trimmed": true,
"spriteSourceSize": { "x": 0, "y": 351, "w": 2048, "h": 417 },
"sourceSize": { "w": 2048, "h": 768 },
"duration": 100
},
{
"filename": "air",
"frame": { "x": 0, "y": 417, "w": 2048, "h": 376 },
"rotated": false,
"trimmed": true,
"spriteSourceSize": { "x": 0, "y": 0, "w": 2048, "h": 376 },
"sourceSize": { "w": 2048, "h": 768 },
"duration": 100
}
]}
```

**Comment by gcmartijn** [comment]
Ah I maybe I had to say that in my example 
Air and ground are the layer names, because they are going to live in the game editor with the same name (as a layer, with options)

I'm going to use it like this:

{"frames":[
{
"layername":"ground",
"frame": { "x": 0, "y": 0, "w": 2048, "h": 417 },
"rotated": false,
"trimmed": true,
"spriteSourceSize": { "x": 0, "y": 351, "w": 2048, "h": 417 },
"sourceSize": { "w": 2048, "h": 768 },
"duration": 100
},
{
"layername": "air",
"frame": { "x": 0, "y": 417, "w": 2048, "h": 376 },
"rotated": false,
"trimmed": true,
"spriteSourceSize": { "x": 0, "y": 0, "w": 2048, "h": 376 },
"sourceSize": { "w": 2048, "h": 768 },
"duration": 100
}
]}

Or better to use your options and make it nicer.

{"frames":[
{
"name":"ground",
"frame": { "x": 0, "y": 0, "w": 2048, "h": 417 },
"rotated": false,
"trimmed": true,
"spriteSourceSize": { "x": 0, "y": 351, "w": 2048, "h": 417 },
"sourceSize": { "w": 2048, "h": 768 },
"duration": 100
},
{
"name": "air",
"frame": { "x": 0, "y": 417, "w": 2048, "h": 376 },
"rotated": false,
"trimmed": true,
"spriteSourceSize": { "x": 0, "y": 0, "w": 2048, "h": 376 },
"sourceSize": { "w": 2048, "h": 768 },
"duration": 100
}
]}

Default the name is what you want, but you can change it for example.
--filename-format {layer} 

Now the "name" is the layername

**Comment by dacap** [comment]
But it looks like the "standard" attribute is called `filename` (not `name` or `layername`). I would like to implement this in the most generic way. Then we can use the `filename` as the layer name (`--filename-format {layer}`, or `{layer}-{frame}` or whatever we need.

I'll add a `--format` option. It'll be `json-hash` by default, but we can use `json-array`. The format will be almost the same. The expected output for a [--format json-hash](https://github.com/photonstorm/phaser-examples/blob/master/examples/assets/sprites/atlas_json_hash_no_trim.json) and [--format json-array](https://github.com/photonstorm/phaser-examples/blob/master/examples/assets/sprites/atlas_json_array_no_trim.json) output.

**Comment by gcmartijn** [comment]
oke cool ! can't wait
Op 30 apr. 2015 16:55 schreef "David Capello" <notifications@github.com>:
