### ISSUE TITLE
Suggestion for paste behaviour, regarding the initial location of pasted pixels.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#642]
When segments of copied pixels are pasted into a document, they are pasted first to a location corresponding to where those pixels were copied from (if they were copied from a selection within ASEprite). This is correct and helpful and works perfectly.
A problem arises when the viewport is over a part of a document that including zero pixels corresponding to the copied segment's original location; that is, no pixel in the copy-source's selection is visible. In this case, the new pixels are pasted at the corner or edge closest to its starting point, frequently leaving only a single pixel of the selection visible and requiring the user to move the viewport in order to drag the selection easily. This is more a nuisance than a 'bug' but does cause some problems, especially because it makes it easy to click transformation/rotation handles instead of the single visible pixel.

My suggestion is to have ASEprite ignore its source-location-alignment tendency if exactly zero pixels from the original copying location are contained by the destination viewport (aligning as normal if one or more pixels are present) and centering the selection in the viewport instead, or aligning it to the top-left (or some other corner/edge) if the selection bounds are larger than the current viewport's range.

The alignment behaviour is very useful for copying pixels between frames, between edits, or between file versions, especially if the whole document area is visible in the editor viewport. But it can be a little troublesome when the user is looking at a part of a document substantially distant from the ideal alignment point and is zoomed out  or working with a high screen resolution that makes the selection difficult to drag.

Forgive me if my nomenclature doesn't match up correctly; this is my first comment here.
By 'viewport', I'm referring to the range of pixels shown in the editor's active/target window.

**Comment by dacap** [comment]
Hi there! The original/expected behavior was (9db66ce6b246acd19d6986c0643dac273da1dae4) this:
* Paste in the original location if that location is visible.
* In other case center to the viewport.

But it was buggy. Now I've a new implementation.
