### ISSUE TITLE
Suggestion for the Open File pane's file type pull-down menu.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#643]
In the Open File pane, there is a file name extension selector to the left of the file name text field. If a file type is selected in this menu after a file has been selected from the files list, it will change the file extension as it does in the Save File pane. I feel like this is could be more useful as a selector that causes the file list to filter for only files of the selected type.

Current behaviour:
> Open File Pane: 
- files list lists all files of recognized types; file type selector is set to "ase" by default.
- on select file from files list: places filename in the filename text field.
- on select file type from extensions menu: replaces file extension in text field with selected extension.

Suggested behaviour:
> Open File Pane:
- files list lists all files of recognized types; <b>file type selector is set to "loadable types"* by default.</b>
- on select file from files list: places filename in the filename text field.
- on select file type from extensions menu: <b>files list displays only files with the selected extension; file name field unchanged.</b>

* I'm using "loadable types" here as a stand-in for "all" or ".*" for reason that this option still only shows file formats ASEprite is <i>actually capable of loading</a>. The actual wording is less important than that it does.

**Comment by dacap** [comment]
Hi @oceanhahn, if you are on Windows, you can get this behavior from v1.1-beta2 using the native dialog to select files (activate it from *Edit > Preferences > Experimental > Use native file dialog*)

**Comment by oceanhahn** [comment]
Great, I'll take a look! I'm still using 1.0.9, so I'll have to update.
Thanks!

**Comment by dacap** [comment]
![Screenshot](http://i.imgur.com/uzxQbDa.png)

**Comment by oceanhahn** [comment]
Brilliant! Thanks!
