### ISSUE TITLE
Export selection

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#645]
_File > Save As_ and _File > Export Sprite Sheet_ should have an option to export only the selected part of the sprite.

Requested in other places too:
* https://community.aseprite.org/t/export-only-selection/216

**Comment by jack27121** [comment]
yes please

**Comment by nkoder** [comment]
> Just wanted to add the "Export" dialogue as another area where this would be useful.

yes, this was the place where I was looking for when I wanted to export only selected area of a picture

**Comment by Gasparoken** [comment]
Requested this feature too on ticket: https://igarastudio.zendesk.com/agent/tickets/2916

**Comment by beetrootpaul** [comment]
FYI For those who ended up here while googling for a selection export in Aseprite. In [super-export](https://fletchmakesstuff.itch.io/super-export) extension we just added such feature. You can export selected portion of an image and upscale it at the same time, even over 1000%.

**Comment by Haddicus** [comment]
> 

Would be nice to be able to sprite sheet export of an animation by frame - that's my biggest desire here.
