### ISSUE TITLE
open .ase file in cli cause recent file repetition

### ISSUE THREAD

**Issue by blackmiaool** [aseprite/aseprite#654]
![l bu bo51dhch4 ur rj4qc](https://cloud.githubusercontent.com/assets/5674588/7448354/68769532-f1cc-11e4-93e5-400382c3d099.jpg)

**Comment by blackmiaool** [comment]
![9q 1a7ppw7 rk nsy_ g8](https://cloud.githubusercontent.com/assets/5674588/7448361/9c16b9bc-f1cc-11e4-8ff3-bac0f12e6cce.jpg)

**Comment by dacap** [comment]
It's low priority, but if you want to fix it, go for it :sweat_smile:

**Comment by dacap** [comment]
Fixed
