### ISSUE TITLE
error: ‘class app::Command’ has no member named ‘short_name’

### ISSUE THREAD

**Issue by RadicalRaccoon** [aseprite/aseprite#659]
Attempting to compile on Elementary OS (based on Ubuntu).

![Error](http://pix.toile-libre.org/upload/original/1430767214.png)

**Comment by dacap** [comment]
I think that commit 4f33bef43ce33b008c0ab55b3259eb2e15874680 should fix that problem (pull from master branch)

**Comment by RadicalRaccoon** [comment]
Yep, that did the trick. Everything compiled just fine after pulling from the master branch again. Thank you.
