### ISSUE TITLE
Bug: The Palette Area can be negatively resized

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#663]
In Aseprite 1.1 beta2, one can drag the palette area left beyond the left edge of the window. 
![negativeresize](https://cloud.githubusercontent.com/assets/8582123/7505977/8c508370-f427-11e4-94f5-1e6573a5d847.gif)

On Windows Vista 32bit.

Update: It can also be moved beyond the right window edge.

**Comment by dacap** [comment]
Thanks to report this. In some way I've found this bug a couple of times and never remembered to add it in my personal TODO list.

**Comment by dacap** [comment]
Fixed
