### ISSUE TITLE
Compiled linux version slower than the one in the ubuntu repositories.

### ISSUE THREAD

**Issue by Nsheppard01** [aseprite/aseprite#670]
I finally compiled Aseprite on linux, but it seems that the new version is moving noticeably slower than the outdaited version in the Ubuntu repositories. This is most noticeable with large files with multiple layers, files take a while to load, and scrolling around lags. But the same files had no problems in the old version.

Is there something wrong, or is the new version just more feature rich/bloated?

**Comment by dacap** [comment]
Hi @Nsheppard01, just in case, did you compile the debug or release version? You can check this in your build directory, there is a `CMakeCache.txt` file. If you have this line:

    CMAKE_BUILD_TYPE:STRING=Debug

In that file, you have compiled the debug version (which is much slower than the official version). Change that to:

    CMAKE_BUILD_TYPE:STRING=RelWithDebInfo

If you have compiled the release version it's related to other issue that we can start look at.

**Comment by Nsheppard01** [comment]
Didn't find anything like that, closest would be 

`CMAKE_BUILD_TYPE:STRING=ProfileCMAKE_BUILD_TYPE:STRING=Profile

**Comment by Nsheppard01** [comment]
Although the about window in Aesprite says v1.1.0-dev if that helps.

**Comment by dacap** [comment]
Yeah, you should change that line to:

    CMAKE_BUILD_TYPE:STRING=RelWithDebInfo

(It's strange that it's in `Profile`, anyway, the `RelWithDebInfo` should be faster.)

**Comment by Nsheppard01** [comment]
Then what? Recompile?

**Comment by dacap** [comment]
Yes.

**Comment by Nsheppard01** [comment]
Works now, thanks! I'll buy the windows version now that I've successfully built the Linux one. I was holding off because I didn't want two different versions running on my two computers.

**Comment by dacap** [comment]
:+1: I'm glad it worked. And sorry for the compiling process. In these days I'm trying to see how to create a Linux package (it will take some time).

**Comment by Nsheppard01** [comment]
Oh man, Deja-vu. Recompiling the new version, and all the same things happened.

I should probably make some kind of compiling on ubuntu guide, if only for myself.
