### ISSUE TITLE
Changing brush size with - or + keys leaves white pixels on screen (regression bug)

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#671]
This didn't happen in v1.1-beta2 (the brush cleaning/drawing algorithm has changed a little because custom brushes).

**Comment by vegeta897** [comment]
Not sure if this is what you're describing or just related:

http://imgur.com/tNTLp1e

v1.1-beta3

Using eraser tool, changing brush size leaves behind the outline of the previous size. Stays while panning, but disappears as soon as you zoom in or out one step.

**Comment by dacap** [comment]
Yes, it's exactly this problem.

**Comment by dacap** [comment]
Fixed
