### ISSUE TITLE
Change program title on save

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#675]
The program title's format is FILENAME - Aseprite VERSION

If you save, FILENAME is not updated, even if one saved the file with a different filename. I'd like this fixed because I typically save things as OBJECTNAME ANIMATION VERSION. The title not being updated makes me paranoid I'll overwrite an old version after saving a new version from the old file, so I have to switch to a new tab and back which properly updates the program title.

Aseprite v1.1-beta3 on Windows Vista 32 Bit

**Comment by dacap** [comment]
Fixed
