### ISSUE TITLE
Wrong palette displayed with multiple tabs

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#676]
Open two animated files with different palettes in the same tab group. Begin playing one. Click the other tab. Begin playing the other. The palette window will flash between the two. Stop playing the animation in the current tab. The palette window now displays the palette for the image not currently being edited. 

![paletteanimationbug2](https://cloud.githubusercontent.com/assets/8582123/7670560/bea114b8-fc77-11e4-9869-0a040816f5cc.gif)

This is admittedly a pretty weird one. I noticed the palette window flipping out a while ago, but couldn't figure out the cause. 

Edit: Okay, found some interesting related bugs. If you then close the not visible and playing tab, the current sprite will have the closed tab's palette displayed until a new frame is displayed in that tab. If you then edit the palette, the current sprite inherits the closed tab's palette. 

New Image, because why not?

![inheritpalette](https://cloud.githubusercontent.com/assets/8582123/7670621/6e911a84-fc79-11e4-8fb2-841a6be98410.gif)

Aseprite 1.1-beta3 on Windows Vista 32bit

**Comment by dacap** [comment]
Fixed
