### ISSUE TITLE
Customize 'palette cycle' mouse wheel modifier.

### ISSUE THREAD

**Issue by rcorre** [aseprite/aseprite#680]
I'd like to choose which modifier key I hold to enable cycling through the palette with the mouse wheel.
Right now you cycle through the palette with <alt+wheel>, I'd like to use <ctrl+wheel>.
It seems like this could fit in the 'Action Modifiers' category.

**Comment by dacap** [comment]
Hi @rcorre, at this moment keyboard modifiers with mouse wheel are not configurable. I think 'Action Modifiers' is a good place too. Planned for v1.1

**Comment by rcorre** [comment]
Looking forward to it!
The existing keyboard customization has already been a great productivity booster.

**Comment by dacap** [comment]
Other possibility: key+mouse wheel to change tool alpha value (or maybe alpha component of current foreground color)

https://twitter.com/Skaz_/status/930806961053904896
