### ISSUE TITLE
Custom Onion Skin

### ISSUE THREAD

**Issue by saint11** [aseprite/aseprite#683]
Adding some options for the onion skin, specially:
-Only show back frame
-Only show next frame
-Onion skin loops animation

And, if possible:
-Show X next frames
-Show X previous frames

**Comment by dacap** [comment]
Hi @saint11, actually you can configure the onion skin range dragging the onion skin range indicators: http://www.aseprite.org/assets/images/frames-and-layers.gif

About "onion skin loops animation", see the issue #555

**Comment by saint11** [comment]
Awesome didn't know that! Can you make the onion skin loop?

**Comment by dacap** [comment]
Yeah, I'll keep issue #555 open, and I'll try to take a look to that one tomorrow :wink:
