### ISSUE TITLE
Save Copy As... image size

### ISSUE THREAD

**Issue by saint11** [aseprite/aseprite#685]
When saving a copy of the file there could be an "image size" option. Ideally there could be a way to quickly select 100%, 200%, 300%, etc... since those sizes are the most common sizes for saving previews.

**Comment by dacap** [comment]
Note for dev: if we add a custom item in the file selector, remember to customize native dialogs #321

**Comment by dacap** [comment]
![Preview](http://i.imgur.com/fm3Xfi0.png)
