### ISSUE TITLE
Bug: Select colour/Eyedropper does not work on pixels in 'Tiled' views.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#687]
If 'Tiled' is selected in Tools Configuration, instance views of the graphic are shown on the relevant edges of the canvas. I can edit these views as though they were the normal workspace, but the eyedropper cannot collect pixel data from these instances and always returns the 'Mask' value, regardless of the pixel they're over. I suspect that the eyedropper is ignoring these surfaces and assumes it's over the 'edge' of the workspace, where it always returns 'Mask'. The central 'home' workspace still sends pixel data to the eyedropper as normal; only the tiled instances behave abnormally.

**Comment by dacap** [comment]
Duplicated #529
