### ISSUE TITLE
Save grid parameters to .ase files

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#688]
It would be pretty useful to have the grid spacing and centring specs treated as local to each workspace, rather than global across all files. Perhaps the grid parameters could even be saved to ase files, as well?

When new files are created (or old files without this data), just use the parameters from the last active workspace? What do you think?

**Comment by dacap** [comment]
Hi @oceanhahn, this is something I thought about it. There is a "projects" feature (#126) that should save all this information and more. Anyway as we could save grid settings inside .ase files I'll leave this issue open to be reviewed for v1.1 milestone.

**Comment by dacap** [comment]
We'll try to save the grid bounds inside `.aseprite` files on v1.2.16 (so if you move the file or rename it or make a copy the grid bounds will be stay, other information like grid color will not be copied, that will be left in the `.ini` configuration associated with the file in the preferences folder)

**Comment by oceanhahn** [comment]
Bwoahshit, at long last, it is done! :0
Thanks for this, @dacap! Great work out there! <3
