### ISSUE TITLE
Updating the compiled version.

### ISSUE THREAD

**Issue by Nsheppard01** [aseprite/aseprite#692]
The version of Aseprite I have on my linux machine (v1.1.0-dev) says it's up to date but it dosn't have the cool resize while saving feature from the 1.1-beta4 release I have on my windows machine.

Will I have to recompile to get that?

**Comment by dacap** [comment]
Hi @Nsheppard01. If a compiled version (dev) matches a beta version, (in this case both are v1.1.0), the compiled version will say it's updated. You have to compile it regularly to keep it updated.

**Comment by Nsheppard01** [comment]
Is there anything I should be aware of when re-compiling? Can I just do everything again and it will be over-written?

**Comment by dacap** [comment]
To recompile you can update your copy source code:

    git pull origin master
    git submodule update --init

And run `make` from your `build` directory.

Or you can just start the whole process again recloning the repository as in [INSTALL.md](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#get-the-source-code)

**Comment by dacap** [comment]
And after the compilation the result will be in your `build/bin/` directory (the old `aseprite` will be overwritten)
