### ISSUE TITLE
CMake Error: find_library called with incorrect number of arguments

### ISSUE THREAD

**Issue by Mailaender** [aseprite/aseprite#695]
A new build system regression introduced in 1.1beta5:

```
CMake Error at third_party/CMakeLists.txt:39 (find_library):
find_library called with incorrect number of arguments
```

**Comment by dacap** [comment]
It looks like a wrong call to find the shared version of gtest library in https://github.com/aseprite/aseprite/blob/master/third_party/CMakeLists.txt#L39

I'll fix this later, anyway you should be able to compile it without the shared version. As gtest was converted to a submodule, try to do:

    git submodule update --init

After that, `third_party/gtest/CMakeLists.txt` should exist ([as this line requires](https://github.com/aseprite/aseprite/blob/master/third_party/CMakeLists.txt#L33))

Thanks to report the issue!

**Comment by Mailaender** [comment]
Okay, finally got it to build, but you amassed quite a lot of regressions since 0.8 in the build system. https://build.opensuse.org/request/show/310818 Maybe continuous integration with @travis-ci might help.

**Comment by dacap** [comment]
Hi @Mailaender, I'm testing travis in [ci](https://github.com/aseprite/aseprite/tree/ci) branch, maybe it will be merged to master today if everything goes right. Hope it helps.

**Comment by Mailaender** [comment]
Only if you build with system dependencies (maybe only on the GCC branch so Clang still tests the bundled ones).

**Comment by dacap** [comment]
Done. Travis is already configured in master to build four configurations: gcc/clang and shared/not-shared libraries. Hope it helps!
