### ISSUE TITLE
"sort by" on palettes seems to blank out palettes

### ISSUE THREAD

**Issue by Ragzouken** [aseprite/aseprite#697]
for any palette, when i sort by hue the palette turns to all black - not just visually - trying to use those colours will just give me black. if i then reverse the palette in the same menu, the palette is restored, and with the correct sorting too.

**Comment by dacap** [comment]
Hi @Ragzouken, actually Aseprite handles palettes of 256 colors only (even when you see 16 colors in the palette, so all the black entries are part of the palette too). So when there isn't a selected color range, the whole palette (256 colors) is sorted.

To temporally fix this situation you can select the first (e.g.) 16 colors and then use "Sort by" to sort the selected range only (and not all those black entries in the 256 color palette). Anyway I'll leave this issue open to fix this problem and finally add support for palettes with less than 256 colors.

**Comment by dacap** [comment]
This will be fixed with #668

**Comment by dacap** [comment]
This is fixed for the next release v1.1
