### ISSUE TITLE
undefined reference to `app_main(int, char**)' on Fedora 22

### ISSUE THREAD

**Issue by martinkg** [aseprite/aseprite#698]
compiling the recent git checkout, that fails on Fedora 22 with the following error:

Linking CXX executable ../bin/errno_tests
cd /home/martin/rpmbuild/BUILD/aseprite-f310a51/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/errno_tests.dir/link.txt --verbose=1
/usr/bin/c++   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pthread -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG   -Wl,-z,relro  CMakeFiles/errno_tests.dir/app/errno_tests.cpp.o  -o ../bin/errno_tests -rdynamic ../lib/libgtest.so ../lib/libapp-lib.so ../lib/libfixmath-lib.so ../lib/libcfg-lib.so ../lib/libcss-lib.so ../lib/libdoc-lib.so ../lib/librender-lib.so ../lib/libscripting-lib.so ../lib/libundo-lib.so ../lib/libfilters-lib.so ../lib/libui-lib.so ../lib/libshe.so ../lib/libgfx-lib.so ../lib/libbase-lib.so ../lib/libupdater-lib.so ../lib/libsimpleini.so -ljpeg -lz -lpng -lz ../lib/libgiflib.so -ltinyxml -lloadpng -lpixman-1 -lcurl -L/usr/lib64 -lalleg -L/usr/lib64 -lalleg ../lib/libnet-lib.so -lpng -ltinyxml -lloadpng -lpixman-1 -lcurl -Wl,-rpath,/home/martin/rpmbuild/BUILD/aseprite-f310a51/build/lib 
../lib/libshe.so: undefined reference to `app_main(int, char**)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/errno_tests.dir/build.make:119: recipe for target 'bin/errno_tests' failed
make[2]: *** [bin/errno_tests] Error 1

**Comment by dacap** [comment]
Hi @martinkg, I've marked this issue as fixed. But if you find it's not fixed yet, you can reopen it.

**Comment by martinkg** [comment]
have again the problem that this error occurs, on Fedora 22 with recent git.

[ 88%] Linking CXX executable ../bin/context_tests
cd /home/martin/rpmbuild/BUILD/aseprite-d5fea43/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/context_tests.dir/link.txt --verbose=1
/usr/bin/c++   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pthread -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG   -Wl,-z,relro  CMakeFiles/context_tests.dir/doc/context_tests.cpp.o  -o ../bin/context_tests -rdynamic ../lib/libgtest.so ../lib/libdoc-lib.so -lm -lSM -lICE -lX11 -lXext -lXext -lXcursor -lXpm -lXxf86vm -lXxf86dga -lSM -lICE -lX11 -lXext ../lib/libshe.so -lloadpng -L/usr/lib64 -lalleg ../lib/libgfx-lib.so -lpixman-1 ../lib/libfixmath-lib.so ../lib/libbase-lib.so -lXcursor -lXpm -lXxf86vm -lXxf86dga -Wl,-rpath,/home/martin/rpmbuild/BUILD/aseprite-d5fea43/build/lib 
../lib/libshe.so: undefined reference to `app_main(int, char**)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/context_tests.dir/build.make:120: recipe for target 'bin/context_tests' failed
make[2]: *** [bin/context_tests] Error 1
make[2]: Leaving directory '/home/martin/rpmbuild/BUILD/aseprite-d5fea43/build'
CMakeFiles/Makefile2:409: recipe for target 'src/CMakeFiles/context_tests.dir/all' failed
make[1]: *** [src/CMakeFiles/context_tests.dir/all] Error 2
make[1]: Leaving directory '/home/martin/rpmbuild/BUILD/aseprite-d5fea43/build'
Makefile:163: recipe for target 'all' failed

**Comment by sirblackheart** [comment]
Hi @martinkg ,
i could not reproduce this error with a clean docker F22 image, can you retry to build aseprite without rpmbuild, so we can make sure the error does not come from that:
```shell
git clone --recursive https://github.com/aseprite/aseprite
mkdir aseprite/build && cd aseprite/build
cmake .. && make
```
and could you post a link to the spec file you are using for rmpbuild?

**Comment by martinkg** [comment]
ok, aseprite could be compiled without rpmbuild.
this is my rpm spec file: http://fpaste.org/271468/44319089/

**Comment by sirblackheart** [comment]
the fpaste is password protected

**Comment by martinkg** [comment]
the rpm spec file:
http://pastebin.ca/3176892

**Comment by sirblackheart** [comment]
Ok i tested it and it really seems to be related how rpmbuild works. i could not reproduce the error outside of its build environment so it is probably some variable it passes or some path it sets. I noticed that the %build part works without problems as it does not compile the tests. The error is reported the moment make install is called in the %install part as it re compiles all targets for the installation, including the test part.

If you really need a rpm maybe you can try to use CPack: https://schneide.wordpress.com/2013/02/11/build-a-rpm-package-using-cmake/

**Comment by dacap** [comment]
We cannot reproduce the issue.
