### ISSUE TITLE
Crash when trying to load a GPL file.

### ISSUE THREAD

**Issue by Nsheppard01** [aseprite/aseprite#700]
I tried to add a new GPL file to the palettes directory, but Aseprite crashes when I try to boot it with that file present. Removing the file fixes this, but I am unable to get it to load properly. The gpl file and full crashdump has been emailed to support@aseprite.org, but i'm putting an issue here as well because this is also a feature request.

It would be nice if Aseprite included an ability to easily import and export gpl files.

**Comment by dacap** [comment]
I'm pretty sure this could be related to the bug fixed in this commit 59cdae77159683f7662f405f1cf2450a6920599f

From your email, I saw that your file has .txt extension. If you rename it to .gpl it should work.

**Comment by Nsheppard01** [comment]
Oh dear, that will teach me to trust file extensions in windows.

**Comment by Nsheppard01** [comment]
Yeah, it was solarized.gpl.txt I fixed the file extension in a proper operating system, and it loads properly now.

I also added the solarized palette to the repository as a pull request, it's just copy pasted from the one in the solarized repository.
