### ISSUE TITLE
Cmake is missing pref.xml and skin.xml

### ISSUE THREAD

**Issue by ericalbers** [aseprite/aseprite#704]
I get two errors from cmake when building.

Cannot find source file:
c:/aseprite/src/data/pref.xml 
and
c:/aseprite/src/data/skins/default/skin.xml

Cmake output:

C:\aseprite\src\build>cmake .. -G "Visual Studio 12 2013" 
CMake Warning at scripting/CMakeLists.txt:4 (find_package):
  By not providing "FindV8.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "V8", but CMake did
  not find one.

  Could not find a package configuration file provided by "V8" with any of
  the following names:

    V8Config.cmake
    v8-config.cmake

  Add the installation prefix of "V8" to CMAKE_PREFIX_PATH or set "V8_DIR" to
  a directory containing one of the above files.  If "V8" provides a separate
  development package or SDK, be sure it has been installed.

CMake Warning at scripting/CMakeLists.txt:14 (message):
  V8 not found, compiling without JS scripting support

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.3)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error in app/CMakeLists.txt:
  Cannot find source file:

    C:/aseprite/src/data/pref.xml

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error in app/CMakeLists.txt:
  Cannot find source file:

    C:/aseprite/src/data/skins/default/skin.xml

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Warning (dev) at CMakeLists.txt:310 (add_executable):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "resize_image_tests" links to some libraries for which the
  linker must search:

    gtest, simpleini, jpeg, zlib, libpng, giflib, tinyxml, pixman, libcurl
    dbghelp, shlwapi

  and other libraries with known full path:

    C:/aseprite/src/build/doc/Debug/doc-lib.lib
    C:/aseprite/src/build/gfx/Debug/gfx-lib.lib
    C:/aseprite/src/build/base/Debug/base-lib.lib

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
Call Stack (most recent call first):
  CMakeLists.txt:346 (find_tests)
This warning is for project developers.  Use -Wno-dev to suppress it.

C:\aseprite\src\build>

**Comment by dacap** [comment]
Hi Eric, it looks like you have run `cmake` for the `aseprite\src` folder instead of `aseprite` folder:

    C:\aseprite\src\build

should be

    C:\aseprite\build

If you ran `cmake ..`
