### ISSUE TITLE
Pen pressure

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#710]
Add support for Wacom pens and tablets. The pressure could control the brush size, opacity, shading color, etc. With a new real-time dithering of RGB images to indexed (#703), it makes sense to have this kind of functionality.

Related to #610

**Comment by Nsheppard01** [comment]
Will it be possible to make Aseprite ignore pen pressure? I tried using it
before it was kind of funky.

**Comment by dacap** [comment]
Hi @Nsheppard01, by default Aseprite should ignore the pen pressure. If you've tried to use a pen with v1.0.9 or v1.1 on Windows, it should work ok (without detecting pen pressure anyway). There are some know issues associated with [Wacom driver and Windows Ink](http://www.aseprite.org/faq/#I-have-a-lag-using-my-pen-is-there-any-solution)

**Comment by maanemann** [comment]
I know it's an old thread, but I hope you get to add this feature one day, I miss the pressure sensitivity when drawing. There isn't any support for it now is there? I don't get any and can't find it anywhere, maybe AkashaRepo got it universally from a driver or so? Except for size/opacity, controlling the palette or one or more colour values with pressure would be really cool, it's an idea I've thought of before. You could use it for shade/highligt, as you said dacap, or colour temperature, saturation etc. or several combined!

I gotta add that I'm very impressed with Aseprite, there's really put a lot of effort into all the details in both functionality and design. You've rethought a lot of the aspects of digital drawing, really cool!

**Comment by RyanJEC** [comment]
It would be so nice to get this.

**Comment by dacap** [comment]
Requested here too:
* https://community.aseprite.org/t/does-or-will-aseprite-support-pressure-sensitivity/1077

and several other places.

**Comment by golddotasksquestions** [comment]
I'm about to start drawing cutscene animations and work on some bosses, and in those few tests I've made, I really missed my pen pressure. So much so I try to postpone this work for even longer hoping Aseprite will add it soon.
Setting brush size to pen pressure is the most needed feature. Anything else I could do without for now. But as soon as my sprite is larger than 50 pixels, I need brush size pressure sensitivity not just for stylistic reasons, but for efficiency.  Changing brush-size constantly of erasing halve your own strokes to draw details and shapes of all sizes is a productivity trainwreck.

**Comment by hepari** [comment]
This is actually the biggest and possibly the only drawback of using Aseprite. Too bad...

**Comment by dacap** [comment]
This feature is available right now in v1.2.18  😊 

https://twitter.com/aseprite/status/1253770784708886533

**Comment by hepari** [comment]
You've pulled it off! Thank you so much, David.😁

**Comment by ArvivrA** [comment]
Hi there,

I just updated to 1.2.18 and pen pressure doesn't work :(
I see the "Dynamics" option for brush but nothing works
Have any ideas?

**Comment by dacap** [comment]
Hi @ArvivrA, we are working on a fix for some special cases, to be ready on v1.2.19, please contact us to support@aseprite.org and we can send you a fix if you are on Windows 10 (64 bits). In other case next week we will release v1.2.19

**Comment by ArvivrA** [comment]
Thanks, Yes I'm on windows 10 (64 bits). Ok then I'll wait for the v1.2.19 and se if it is fixed. if not I'll contact you through support@aseprite.org

Thank you

**Comment by hepari** [comment]
Hello,
here are some important suggestions:
1. Turning pen pressure off and on resets it to default value. Can you instead make it revert to the last configured value? Of course it would be the best if we could create brushes like in Photoshop or Clip Studio, but I guess it's asking too much.

2. It would also be helpful if pen pressure was applied to the eraser.

**Comment by dacap** [comment]
Hi there @hepari, actually we have some changes to be released in the next version:

![image](https://user-images.githubusercontent.com/39654/82886856-84da7a00-9f1d-11ea-84f4-9e986086395b.png)

The "brush size" will be the max value instead of the min value in the next release (changing the max value <-> changes the brush size). I think that will mitigate both issues a little. This week I'll release v1.2.19.

**Comment by hepari** [comment]
Nice! I think this will make life a lot easier for now.
It feels counter-intuitive to be in control of the min value instead of the
max value.
Some things you just don't appreciate until you have to live without them XD

Thank you for your hard work!

**Comment by ArvivrA** [comment]
Awesome! 
With 1.2.19 now my pressure options are working. Thank you! 
But there is only one issue. It would be great if when alpha of background's color is set to 0, brush would have transparency as well.
Or is it a bug for me?

Thank you!

**Comment by jeduden** [comment]
I tried the pen pressure on my HP Spectre x360 with a HP Tilt Pen. 
Aseprite's pressure detection works fine on Windows. However, if I use Aseprite 1.2.24-1 on Manjaro, it doesn't detect pressure using the same hardware. I also tried Xournal++ on that system and it was able to detect pressure. Any idea, what the problem could be ?

**Comment by Bindinglegend** [comment]
Hi,
This is probably the most important feature for me when drawing environments, I really appreciate you taking the time to add it, however there is one significant problem, that being that the feature fails when I set alpha of the BG color to 0. This is a major issue as it makes it impossible to draw over existing work and flesh out shapes. Is there any chance this functionality could be added soon?
