### ISSUE TITLE
Request: Reverse Frames to act on all frames when none are selected

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#711]
I request for frame, Reverse Frames (alt+i) to reverse the order of all frames if none are selected. Alternatively, grey out the option when none are selected so it's clear there will be no action.

It's a small thing, but I keep getting confused by it.

**Comment by dacap** [comment]
I think I'll gray out the option, because it can be confusing if there are tags in frames  (E.g. should it reverse the whole animation or just the tagged frames?

**Comment by dacap** [comment]
Fixed
