### ISSUE TITLE
Why did I failed build aseprite in windows?

### ISSUE THREAD

**Issue by guawoo** [aseprite/aseprite#725]
I installed vs2013 Community edition and DirectX SDK, then fellow the install.md requirement, but I failed build it.

**Comment by huwpascoe** [comment]
There's an error with the dependency paths in the vs solution, I can't remember what exactly but a quick workaround I found was copying some of the dependencies to a sub/parent directory. You'll have to check the build log to see which files are the problem. (If you're not going to contribute to development though it's sooo much easier shelling out for the 10$ license!)

**Comment by dacap** [comment]
Hi @guawoo, if you have some log or build output I might give you a hand with this issue.

**Comment by guawoo** [comment]
@dacap Thanks, I think I will buy a license. :)
