### ISSUE TITLE
Color issues after converting multi palette images to RGB

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#726]
Large (27MB) GIF warning: http://i.imgur.com/j88oux3.gif

1. Open that image.
2. Sprite, Color Mode, RGB Color

Most of the frames end up looking totally different. This also affects export sprite sheet. 

Aseprite 1.1-alpha8

**Comment by dacap** [comment]
Note: There are bugs opening .gif files generated with LICEcap too.
