### ISSUE TITLE
Line brush can leave gaps

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#728]
A GIF:

![linetoolgaps](https://cloud.githubusercontent.com/assets/8582123/8665570/4d184eec-29b3-11e5-972e-a94bfd2a0133.gif)

If the gif does not show up, it was very easy to make this happen with 25px line brush at 48 degrees.

The eraser is also affected.

Aseprite 1.1-alpha8 on Windows Vista 32bit.

**Comment by dacap** [comment]
This issue is related to #245 and #175
