### ISSUE TITLE
Transparent index is added to selection corrupting it when mask type is an index

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#730]
1. Open this image: 
![testimage](https://cloud.githubusercontent.com/assets/8582123/8675201/8dccf4e4-2a10-11e5-91e4-eacf5f5a16d9.gif)
2. Select a piece of it that contains both colors (the green and the tan)
3. Change the mask color to index 27
4. Remove a piece of the selection
5. Drag it. 
You'll notice the transparent color is now in the area that was removed.
6. Deselect it. 
The transparent color is even pasted to the image. Therefore it is not solely a visual bug.

GIF illustrating the steps:
![selectioncorruption](https://cloud.githubusercontent.com/assets/8582123/8675311/21290d90-2a11-11e5-982f-ad41bff942f9.gif)

Aseprite v1.1-alpha8 on Windows Vista 32bit

**Comment by dacap** [comment]
Hi @KasumiArai! Thanks for reporting this issue. I'm aware to some issues related to the combination between different sprite transparent colors and selection transparent colors (e.g. #546, which maybe it's already fixed). It's good to have this well documented.
