### ISSUE TITLE
Moving multiple frames: only shows first layer selected until mouse release

### ISSUE THREAD

**Issue by enol** [aseprite/aseprite#731]
When you pick multiple frames and displace them to other position you can only see the first layer selected at the moment. When you release the mouse they suddenly appear in the next position.

---

Cuando desplazas varios frames a la vez a una nueva posición con la herramienta move solo previsualizas el desplazamiento de la primera capa seleccionada. Al soltar el ratón aparecen de repente todas las capas reposicionadas en el nuevo punto. Deberían poder verse todas para controlar mejor la posición.

![1pic](https://cloud.githubusercontent.com/assets/10049471/8697660/2eb9cc7e-2af7-11e5-871a-9321f1cadabb.png)

![2pic](https://cloud.githubusercontent.com/assets/10049471/8697665/335e1190-2af7-11e5-85ab-3991e6c76f38.png)

**Comment by TheKK** [comment]
Hi, @dacap. Have you started working on this bug?
I'm interested in this and would like to give this a try :)

**Comment by dacap** [comment]
Hi @TheKK, you can go for it! You can start looking at [MovingCelState::onMouseUp](https://github.com/aseprite/aseprite/blob/master/src/app/ui/editor/moving_cel_state.cpp#L68)
