### ISSUE TITLE
Including color cells / tint frames on the timeline to highlight important frames

### ISSUE THREAD

**Issue by enol** [aseprite/aseprite#733]
An interesting improvement could be the possibility to assign color to certain cells (by a right-clicking option) on the timeline to remember/highlight important spots without creating new layers with empty frames.

---

Una funcionalidad interesante sería la inclusión de marcadores de color asignados a las celdas en la línea de tiempo para poder recordar puntos importantes de la animación sin tener que generar una nueva capa vacía con un fotograma que marque dicho spot.

**Comment by dacap** [comment]
Fixed with addddf78a5a59ca385ea0bfccb2e08489cc0419c and 868376380f019cb90fed1db48bc22a0e52712767 (the whole [user-data](8698ac5f573c0836383739ee717dc876fb50fdbb) merge)
