### ISSUE TITLE
Preserve linked frames copying a layer from one document to another

### ISSUE THREAD

**Issue by enol** [aseprite/aseprite#734]
Right now Aseprite doesn't maintain the linked functionality when you copy & paste a layer into another in a different file. The cells are splitted in the new file.

---

Ahora mismo Aseprite no permite mantener fotogramas enlazados / continuos cuando se copia una capa de un documento a otro. En el archivo de destino aparece con las celdas separadas, aunque este marcado el icono de celdas unidas.

**Comment by Nsheppard01** [comment]
It would also be nice if you could copy paste a selection from more than one layer at once.

**Comment by dacap** [comment]
Preview:
![linkedcels](https://cloud.githubusercontent.com/assets/39654/9144210/db2b0266-3d21-11e5-946f-474f9c09e48a.gif)

**Comment by dacap** [comment]
@Nsheppard01 hi there! do you mean the selection in the canvas? e.g. select a rectangle with Marquee tool, select a set of cels in the Timeline, and copy/paste only the selected rectangle of selected cels.
