### ISSUE TITLE
implement possibility of "copy cel in next frame" in multiple layers at the same time

### ISSUE THREAD

**Issue by enol** [aseprite/aseprite#735]
It will improve the workflow if you have lot of layers and need to extend some of them but not all.

---

Mejoraría el flujo de trabajo si tienes muchas capas y necesitas extender la longitud de algunas de ellas al mismo tiempo, eludiendo tener que ir una a una.

**Comment by dacap** [comment]
Preview:
![copycels](https://cloud.githubusercontent.com/assets/39654/9085771/2a2fbbc2-3b56-11e5-9de8-2f1bb88b3d02.gif)
