### ISSUE TITLE
Save progress bar can be modified

### ISSUE THREAD

**Issue by Async0x42** [aseprite/aseprite#743]
If the "Saving file" dialog with progress bar gets stuck open (removing / reinserting a USB with the project for me), the progress bar value can be dragged with the mouse to change the value (shouldn't be able to)

**Comment by dacap** [comment]
Hi @Async0x42, a minor known-issue (the progress bar is a slider really). Anyway it's a strange behavior, I'll fix this.

**Comment by dacap** [comment]
Fixed with 77d8024026b28cfbdcdc5adf906387594cd46bb0
