### ISSUE TITLE
Add a 'pixel perfect drawing' option for the pen

### ISSUE THREAD

**Issue by Async0x42** [aseprite/aseprite#744]
I read and saw an implementation about an algorithm which when drawing, removes the extra pixels that make pixel-art lines not smooth. This would be nice to have when drawing, saves a lot of time fixing those extra pixels.

Reference here: http://deepnight.net/pixel-perfect-drawing/ , unfortunately they don't provide the algorithm they used, but the idea is great.

**Comment by vegeta897** [comment]
This is already in. #315

![image](https://cloud.githubusercontent.com/assets/1789096/9155607/da6c03ce-3e8a-11e5-8c33-d481d3146adb.png)

**Comment by Async0x42** [comment]
Oh thanks, this can be closed then. I was looking in the documentation about this and didn't see it, that tooltip slipped my mind since I only checked the option my first time launching Aseprite.
