### ISSUE TITLE
Improving the linked properties without the linked icon in the timeline

### ISSUE THREAD

**Issue by enol** [aseprite/aseprite#746]
You had to link/unlink a layer if you need to duplicate a cell and use the shortcut "Copy Cel in Next Frame" which is a little inconvenient when you work with constant linked/unlinked layers (which is the case almost every time). I think that this property could be improved simplifying the way it works:

Adding two shortcuts -one to copy linked and other to copy unlinked cells- and eliminating the linked layer icon in the timeline its easier and it won't be necessary to keep an eye on the linked panel... if something is attached in the timeline you know it visually. I'll add those properties in the right click menu inside the timeline below the "clear" and "unlink" properties for people that are not used to shortcuts too.

____________________

Para poder duplicar una celda de manera independiente dentro de una capa enlazada con el atajo "Copy Cel in Next Frame" se debe activar/desactivar el icono de enlace de la timeline constantemente, lo cual resulta algo incómodo si estas trabajando constantemente con capas que requieren de frames enlazados e independientes en intervalos constantes (lo que suele ser bastante frecuente).
Creo que se puede simplificar la manera en la que funciona esta propiedad sin depender del icono de capas enlazadas de la timeline:

Si se tienen dos shortcuts en "Frame" -uno para copiar enlazado y otro para copiar sin enlace- se podría eliminar el icono de capa enlazada, ya que es algo engorroso (además de redundante con esta idea) y con el simple hecho de duplicar con uno u otro atajo (o con clic derecho sobre los frames) sería más que suficiente.
Creo que este sistema a la larga es más beneficioso porque simplifica el funcionamiento del programa y no requiere que estés pendiente de dicha propiedad de manera constante... si algo está enlazado ya se ve visualmente porque las celdas están unidas.

**Comment by dacap** [comment]
The linked icon was added to avoid linked cels by default and to keep compatibility with v1.0 behavior. There are several commands affected by the icon. For example when a new frame is added (Frame > New Frame), or copying cels (or frames) using drag-and-drop, or "Copy Cel in Next Frame".

In case we remove the icon, copying cels/frames with drag-and-drop could keep the same link/unlink state of the original cels. But the problematic commands are 'New Frame' and 'Copy Cel in Next Frame'. I'm not quite sure to have these commands available:
* *New Frame*
* *New Linked Frame*
* *Copy Cel in Next Frame*
* *Link Cel in Next Frame*

For example, without the icon, if we have a static background layer, we lost the functionality to keep it always linked whatever command we use (*New Frame* or *New Linked Frame*).

Probably, you just need a new command (*Link Cel in Next Frame*) to copy all cels forcing links (ignoring the layer icon).

**Comment by enol** [comment]
You are right. A lot of things are connected to the new linked frames system to get rid of it, so probably a new shortcut to copy previous frame unlinked would be more than enough  :)

**Comment by Async0x42** [comment]
Somewhat related to this I think, but it'd be great to select a range of cells, right click, and choose "link these cells", and it'll link them all based on the first cell. I like the linking system, but linking it frame by frame for an existing animation feels clunky since there's no bulk way to do this.

Also, for the hot keys mentioned above, could they also be placed in the right click context menu on the cell? (Copy cell linked to next frame, copy cell unlinked to next frame). Hot keys are great at times, but context menus should reflect available actions I think.

**Comment by dacap** [comment]
@enol Here a mockup of how this new command (Alt+Shift+M?) could work (please make comments about it):
![copyblock](https://cloud.githubusercontent.com/assets/39654/9249536/17c2d13a-419c-11e5-8912-2188c8de6c8c.gif)

I'm not quite sure how this command should be called (*Copy Cel Block*? *Copy Cel in Next Frame* and rename the current one to *Link Cel in Next Frame*? what about non-continuous/unlink layers when *Link Cel in Next Frame* is used?).

@Async0x42 I'll add that option in the popup menu. And see how it works with the other options in the popup too.

**Comment by Async0x42** [comment]
New option works great, thanks! Looking forward to more commands being added to the context menus if they fit in (Glad I switched from the betas to compiling it, the new features are really nice!)

My opinion for the new command referenced above, and actually the old ones, how about "Duplicate Cell Block" (and maybe renaming the old ones to Duplicate Cell in Next Frame). When you say 'copy' it sounds to me like you'll be manually pasting it (inserting) wherever, but duplicate cell block sounds like it'll happen immediately.

Thinking on that a bit more, is there a need for separate commands? I think ideally, if you have a block range of cells selected and call the command, it should duplicate the range, but if you have a single cell selected, and call the same command, it should duplicate just that cell.

**Comment by enol** [comment]
It works great!
@Async0x42 @dacap a mixture of your ideas for the commands?
- duplicate cell in next frame
- duplicate linked cell in next frame
(or remove "in next frame" to have it shorter)

About the need of both shortcuts, I think that it's clearer for new & forgetful users, but @dacap has the last word.

**Comment by dacap** [comment]
Let's make a summary about these commands just to avoid confusion and see how they differ:

* *Duplicate Cels* (Alt+D)
![copyblock](https://cloud.githubusercontent.com/assets/39654/9249536/17c2d13a-419c-11e5-8912-2188c8de6c8c.gif)

* *Duplicate Linked Cels* (Alt+Shift+D and Alt+M) (it's the old *Copy Cel in Next Frame*)
![dupcels](https://cloud.githubusercontent.com/assets/39654/9272785/429c0744-425c-11e5-92d0-ff65a620ac56.gif)

> is there a need for separate commands? I think ideally, if you have a block range of cells selected and call the command, it should duplicate the range, but if you have a single cell selected, and call the same command, it should duplicate just that cell.

Both commands works in that way. But they differ in how the copy is made.

**Comment by Async0x42** [comment]
Both of those command names look good to me at least (though duplicate cells or duplicate cell block for multiple)

About the separate commands, I think I misunderstood @dacap when he said rename the old function. A separate command for duplicating LINKED vs unlinked, I totally agree with!

I had thought the intention was to keep a command for duplicating a single cell, and have a totally separate command for duplicating multiple cells. I had meant those two functions should be merged, not linked vs unlinked though.

**Comment by dacap** [comment]
> A separate command for duplicating LINKED vs unlinked, I totally agree with!

:+1: :smile:
