### ISSUE TITLE
Edit menu options aren't always enabled after copy/pasting selection

### ISSUE THREAD

**Issue by Async0x42** [aseprite/aseprite#750]
If I make a selection box, copy/paste it, and then go to flip it H/V, the edit menu options aren't enabled until I right click anywhere on the canvas. Even if I move the newly pasted pixels, the edit menu still doesn't enable the options.

Screenshot of the issue: http://imgur.com/ypWWukH

**Comment by vegeta897** [comment]
I was a bit perplexed by this as well. If I just draw a selection, I can use that menu to manipulate it. But if I move it or paste it, those functions become disabled.

**Comment by dacap** [comment]
Duplicated #275 

I'll try to fix this today. It's a long standing bug and the most confusing. You can use Shift+V and Shift+H to flip the selection.

**Comment by dacap** [comment]
Related issue #690
