### ISSUE TITLE
Replace image colors when creating palette from sprite (with less colors)

### ISSUE THREAD

**Issue by Async0x42** [aseprite/aseprite#751]
When creating a palette from sprite, please add an option to replace colors that don't get added t the palette, with the closest match (i.e, if I have a sprite with 16 colors, and I create a new palette from that, but choose to create a palette with 8 colors, the sprite will only have those 8 colors after creating the palette)

Or an alternative, a separate menu option to clamp the current image to the current palette colors (without even needing to create a new palette). I like this option better actually, but both work.

(This is the palette reducing thing I originally emailed about)
Some refs: http://2dwillneverdie.com/tutorial/so-you-want-your-sprites-to-be-16-colors/ and https://www.fastgraph.com/colors.html

**Comment by dacap** [comment]
Actually the "Remap" button (in the latest in-development version) does that: It tries to match colors finding which one fit best:

![remap](https://cloud.githubusercontent.com/assets/39654/9284326/722f89ae-42b1-11e5-94b6-8b3a38737066.gif)

I think the "Create Palette from Current Sprite" option (which is only available on RGBA images) could be available for Indexed images too (to create a reduced version of the palette and Remap):

![reducecolors](https://cloud.githubusercontent.com/assets/39654/9284397/e2805c6a-42b1-11e5-9079-0fa576342df2.gif)

Related to #563 and #552

**Comment by Async0x42** [comment]
Looks great for both indexed and rgb! (What do you use for recording Aseprite and then to a gif by the way?)

**Comment by dacap** [comment]
I'm using [LiCEcap](http://www.cockos.com/licecap/), a great little utility.
