### ISSUE TITLE
Easier minute palette size adjustment

### ISSUE THREAD

**Issue by Bobhostern** [aseprite/aseprite#754]
This may be a complete non-issue, but adjusting the palette size can be a pain. I commonly increase the palette size by 1 or 4 at a time, and having to type in the number is a bit...disruptive. I think it would be nice for maybe a set of buttons to increase (or decrease) the number of palette slots by 1, or maybe have an input field, anything so that I don't have to think "32 + x = y" every time I want to add a new color to an indexed image.

**Comment by Async0x42** [comment]
Maybe a right-click "insert empty palette cell" and "remove cell from palette" in the context menu?

**Comment by dacap** [comment]
Actually we can add new colors:
* clicking the warning icon http://imgur.com/g444Ho2
* or with drag-and-drop http://imgur.com/2eiZceh

And we can delete colors selecting a color (or several colors) and then *Edit > Clear* (or pressing Delete or Backspace keys).

Anyway I've asked several times for this, so I'll see if we can have a more intuitive way.

**Comment by dacap** [comment]
![resize](https://cloud.githubusercontent.com/assets/39654/9386812/ab9351b8-4733-11e5-8fb7-34df5d0bfbd2.gif)
