### ISSUE TITLE
Show palettes in aseprite\palette dir, not just in data\palettes

### ISSUE THREAD

**Issue by Async0x42** [aseprite/aseprite#757]
After first launch, a palettes folder is created with the default palette, but if you add palettes to that folder they don't display in the presets drop-down.

Also (related), the palette preset list is only loaded one time, if you remove or add palette files from the folder, it isn't refreshed, until you close the application and relaunch. It should quickly do a check on the folder to see if there are any new or missing palettes.

**Comment by eevee** [comment]
I'm not sure if this is the same problem you're talking about, but I just created a `~/.config/aseprite/data/palettes` directory to add an extra palette, and now the dropdown _only_ shows that palette — not any of the builtin ones.

**Comment by dacap** [comment]
I'll try to fix this for the next version.

**Comment by rantonels** [comment]
This as described by @eevee is still an issue in the latest version.
