### ISSUE TITLE
Build linking to libX11 on 64-bit Linux fails

### ISSUE THREAD

**Issue by wesleywerner** [aseprite/aseprite#760]
**System:** `Debian GNU/Linux 8.1 (jessie)`
**Architechture:** `Linux multivac 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux`

**Build Log**
    Scanning dependencies of target aseprite
    [ 94%] Building CXX object src/CMakeFiles/aseprite.dir/main/main.cpp.o
    [ 94%] Building C object src/CMakeFiles/aseprite.dir/main/xpm_icon.c.o
    make[2]: *** No rule to make target '/usr/lib/i386-linux-gnu/libX11.so', needed by 'bin/aseprite'.  Stop.
    CMakeFiles/Makefile2:258: recipe for target 'src/CMakeFiles/aseprite.dir/all' failed
    make[1]: *** [src/CMakeFiles/aseprite.dir/all] Error 2
    Makefile:117: recipe for target 'all' failed
    make: *** [all] Error 2

**Temporary Fix**
    $ sudo mkdir /usr/lib/i386-linux-gnu
    $ sudo ln -s /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/i386-linux-gnu/

Hope this helps :)

**Comment by sirblackheart** [comment]
I could not reproduce this on arch 64 bit, and also not in a docker debian container which is debian:jessie. What cmake switches do you use?

**Comment by wesleywerner** [comment]
I used the suggested switches in `INSTALL.md`: `cmake .. -G "Unix Makefiles"`.

I think this issue can be closed as it might just be an oddity on my system. It is a newly installed Debian Jessie system, I copied the source over from a previous i686 system. Even though I ran a `make clean` prior to building, perhaps a remnant setting caused this dependency snafu.

Closing this issue.
