### ISSUE TITLE
Unusual transparent pixels when copying between views.

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#764]
All steps may not be important of course.

1. Open an RGB image that is a "background" not a "layer."
2. Open an indexed image with a transparent index of 0. (Preferably index 0 is a color that's easily visible. Not black in an image that also used black as another palette entry.)
3. Make the selected foreground color index 3 and the selected background color index 1
4. Click and drag the RGB image's tab to create a new view on the right. The indexed image should be visible at the same time on the left.
5. Zoom both images to 800%
6. Press M. (Marquee select tool)
7. Click and drag on the RGB image to create a selection. 
8. Shift Click and drag to begin scaling it. (Make it smaller.)
9. Release left click.
10. Press Ctrl+C (Copy)
11. Hold down space (Pan) and click the indexed image's view.
12. Press Ctrl+V (Paste)
13. Hold Control and click the selection without moving it. (to create a duplication on the canvas)
14. Drag the still active selection somewhere on the canvas that does not overlap the copy.
15. Press B (select brush tool.)
16. Press ctrl+d (deselect)
17. Left click and drag on the pixels that used to be part of the selection. 

You should see both index 0 AND index 3 being drawn. They behave almost like the contour tool. It's very strange. Gif: 
![weirdtransparentpixels](https://cloud.githubusercontent.com/assets/8582123/9321635/1d29a240-4537-11e5-8d0a-acc84b342254.gif)
Note: Gif  contains slightly different steps. I first recorded it because I was unsure if I'd be able to reproduce it after restarting the program. But I was able to reproduce it by following the steps above.
Aseprite v1.1-alpha17 on Windows Vista 32bit

**Comment by dacap** [comment]
Really strange bug. Nice catch. I'll take care of this now. Other way to reproduce it:
1. Create an RGB image and an Indexed image
2. Drag one tab to a side
3. Make a selection in one sprite and move it
4. Middle-click the other sprite to select/scroll it
5. Select Pencil tool (with B shortcut) and start drawing

Note for dev: The problem appears when other (visible) editor is in MovingPixelsState.

**Comment by dacap** [comment]
It was really hard to find this bug. Thanks for the report!
