### ISSUE TITLE
'Select > Color Range' should respect the current selection (if any).

### ISSUE THREAD

**Issue by ghost** [aseprite/aseprite#765]

**Comment by dacap** [comment]
Other feature (including this one) is that the *Select > Color Range* option should have the Union/Subtract/Intersect options.

**Comment by jpnk** [comment]
interesting.

**Comment by dacap** [comment]
Add different selection modes (replace/add/subtract/intersection) to Select > Color Range command:

<img width="449" alt="screen shot 2018-10-26 at 16 17 34" src="https://user-images.githubusercontent.com/39654/47587868-ac7cf100-d93a-11e8-8a58-888dd9649a68.png">
