### ISSUE TITLE
Remap palette button stays after undo

### ISSUE THREAD

**Issue by Async0x42** [aseprite/aseprite#766]
If you switch to indexed, reduce the colours, and then undo all actions until the image is RGB again, the remap button stays.

Also, I think that if you reduce colours first, then switch to Indexed, the remap button should show up (if there are colours in the image, that don't exist in the palette)

![1](https://cloud.githubusercontent.com/assets/3268854/9392468/e5451be6-474a-11e5-9a11-5ea72e7151f7.gif)

**Comment by dacap** [comment]
> Also, I think that if you reduce colours first, then switch to Indexed, the remap button should show up (if there are colours in the image, that don't exist in the palette)

When a RGB sprite is converted to Indexed the "remap" is done automatically with the current palette. So I think there is no need for the "Remap" button in that case.

**Comment by Async0x42** [comment]
Ah right, that makes sense not to need a remap when switching to indexed.

If you reduce the palette size while in indexed, the remap shows, but if you then CTRL+Z to undo the palette change, the Remap button still exists, even though the undo made it so there was no palette change. (as seen in the original post gif) This wasn't actually fixed by the last commit, so the issue should still be open
