### ISSUE TITLE
Westwood Studios SHP file format support

### ISSUE THREAD

**Issue by Mailaender** [aseprite/aseprite#773]
See http://vladan.bato.net/cnc/ccfiles4.txt for specifications. Would a contribution be welcome or are proprietary game file formats out of scope for this project?

**Comment by dacap** [comment]
Hi @Mailaender, I'd prefer to avoid specific proprietary file formats inside Aseprite code, anyway I think that this kind of situations could be solved with a plugin API/SDK (related to #54). So you could have your own .dll to load/save in this SHP format.

Maybe we can discuss the API here. It should be a SDK with stable ABI (e.g. C functions/structs). Could be this enough for your requirement?

**Comment by Mailaender** [comment]
That sounds like a sane design decision. I am more like dreaming at the moment and probably also lacking skill a bit, but there is lot's of pre-existing code https://code.google.com/p/xcc/ and the file formats have been fully reverse engineered already.

**Comment by Phrohdoh** [comment]
Are all of your third party format parsers written in C/C++?

**Comment by dacap** [comment]
Hi @Phrohdoh, yes, all parsers are written in C++ (https://github.com/aseprite/aseprite/tree/master/src/app/file). Anyway these parsers use a unstable/internal API (which I'm planning to modify #379).

I think that we have these possible ways to implement a plugin API:
* A stable plugin SDK so anyone can compile its own C (or C++) DLL to load/save custom file formats. (portable between Win/Mac/Linux)
* A COM API (typelib interfaces) so Aseprite can consume COM objects to load/save custom formats (DLLs could be done in C, C++ or C#) (Windows only, or maybe portable with mono, I'm not sure)
* With a JavaScript API (https://github.com/aseprite/api-draft)

**Comment by Async0x42** [comment]
If COM would allow non-windows platforms with mono, I think that'd be a good bet to open up plugin development to a wider variety of developers (C#), but it may not be good if it restricts the feature to a specific platform.
