### ISSUE TITLE
Auto-detect file format from data, not extension

### ISSUE THREAD

**Issue by Async0x42** [aseprite/aseprite#776]
Currently if you try to load a .png (say from the web), but it was actually a gif image, aseprite gives an error.

It would be better if it would totally ignore the file extension and determine what kind of image it is to load by itself (possibly display the format somewhere that the user is able to see?)

Totally minor issue, but it does save people guessing what extension it is and renaming multiple times to find out what works, in the event that it was saved incorrectly

**Comment by TheKK** [comment]
I think adding a new interface to app::FileFormat for checking specified file header would be one of the proper solution, what do you think @dacap?

**Comment by dacap** [comment]
This will be the first step to create a library (`docio`) to move all the code to load/save files in different formats.
