### ISSUE TITLE
Improve the keyboard shortcuts dialog

### ISSUE THREAD

**Issue by jpnk** [aseprite/aseprite#777]
the other day i was looking for a way to change the shortcuts for a couple of tools and at first i assumed there was no way to do that because i didn't notice that the section field is actually a combobox. so here's a mockup with better discoverability:

    +-----------+-----------------------+
    | Section 1    Section 1 shortcuts  |
    +-----------+  ...                  |
    | Section 2 |  ...                  |
    +-----------+  ...                  |
    | Section 3 |  ...                  |
    +-----------+  ...                  |
    | Section 4 |  ...                  |
    +-----------+                       |
    |           |                       |
    |           |                       |
    | +-------+ |                       |
    | | Ok    | |                       |
    | +-------+ |                       |
    | +-------+ |                       |
    | | Cancel| |                       |
    | +-------+ |                       |
    +-----------+-----------------------+

**Comment by dacap** [comment]
It's a good idea :+1:

**Comment by dacap** [comment]
![newkeyconf](https://cloud.githubusercontent.com/assets/39654/9473493/7f6549be-4b31-11e5-9e04-024f792e3774.png)

**Comment by jpnk** [comment]
i think the buttons should go in this order:

    Import
    Export
    Reset
    -------
    Cancel
    Ok

**Comment by dacap** [comment]
Sorry, I didn't think about it too well. Maybe in this way:

![keyconf2](https://cloud.githubusercontent.com/assets/39654/9477825/7caafed0-4b4a-11e5-953b-567d312af103.png)

**Comment by Async0x42** [comment]
This last image looks good, with OK and Cancel on the bottom of the dialog

**Comment by jpnk** [comment]
another variant

![7caafed0-4b4a-11e5-953b-567d312af103](https://cloud.githubusercontent.com/assets/1309437/9478238/313d73bc-4b7f-11e5-8787-8ceb22597413.png)

**Comment by Async0x42** [comment]
Both are good, but I think this one causes a little too much white-space in the left box (since it's unlikely to be filled with categories I think), and the buttons being lower the the main list box causes the Reset button to draw my eye to it too much. I'm not an artist though, just my personal thought!
