### ISSUE TITLE
Sort numbers within names in order

### ISSUE THREAD

**Issue by Async0x42** [aseprite/aseprite#782]
For example, in the keybindings window (the new one is really slick by the way!), it goes:

Zoom 100%
Zoom 1600%
Zoom 200%
<snip>
Zoom 50%
Zoom 800%

It'd be much better if when sorting, and numbers are the only differing aspect, to sort those the way we would in our head (I can't remember the proper term for this kind of sorting, alphanumeric sorting?)

->
Zoom 50%
Zoom 100%
Zoom 200%
And so on

**Comment by dacap** [comment]
Fixed
