### ISSUE TITLE
Image sequence not detected in a folder with Japanese characters

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#784]
I've got a folder called: 44616410_ugoira600x600 by ちぃま
with images inside named:
000000.jpg
000001.jpg
etc. 

If I click and drag 000000.jpg to the Aseprite window it will load properly, but not detect the image sequence. If I remove the Japanese characters from the folder the images are contained in, the image sequence will be detected by Aseprite. 

Related issue: I can open one of the images in the 44616410_ugoira600x600 by ちぃま multiple times in one Aseprite window, which is not allowed for files in folders without such characters.

Aseprite v1.1 on Windows Vista

**Comment by dacap** [comment]
Fixed
