### ISSUE TITLE
Aseprite does not detect an image sequence when using Windows "open with"

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#785]
I have files in the same folder named momo1.png, momo2.png etc.
I click and drag momo1.png over Aseprite.exe and release. Aseprite.exe opens and loads Momo1.png without displaying the "Possible animation with:" notice. If I then close momo1.png and drag it over the Aseprite window, it will display the notice.

Aseprite v1.1 on Windows Vista 32bit

**Comment by dacap** [comment]
Also, this problem happens when we "pin" a file in the Aseprite's task bar icon and click that file from the Aseprite's task bar menu

**Comment by dacap** [comment]
Fixed
