### ISSUE TITLE
Request: Tooltips for "do operation across frames" icons.

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#786]
These: 
![tooltipstheseicons](https://cloud.githubusercontent.com/assets/8582123/9532924/a1e90f82-4cdc-11e5-87f5-1958bef7eab3.gif)
They don't appear very often in the program, but they're something where the icons aren't quite enough.

**Comment by dacap** [comment]
I've a personal "to-do" item to do this. This is the weirdest widget and maybe the most important one to have tooltips. Also I'd like to change the buttons style. Something like this:

![targetbuttons](https://cloud.githubusercontent.com/assets/39654/9547400/961684d4-4d70-11e5-9495-76f58d0de994.png)

**Comment by dacap** [comment]
Fixed
