### ISSUE TITLE
Libcurl linking broke in VS2015 again

### ISSUE THREAD

**Issue by salmelo** [aseprite/aseprite#788]
Looks like same problem as #606 and #608 is back. Got it to compile fine using fd920eb, when the last fix was merged into master.

**Comment by lendrick** [comment]
Quick work-around for this:  Copy libcurl.lib from build/lib into build.

**Comment by sarcasmloading** [comment]
Yeah, close this issue. @lendrick 's workaround works on VS15: move libcurl.lib from build/lib into build.
