### ISSUE TITLE
Autosize new image to best-fitting zoom level for canvas size

### ISSUE THREAD

**Issue by Async0x42** [aseprite/aseprite#789]
When creating a new image, it's 1:1 size, it'd be better to scale that to the canvas so you can see everything, then zoom in where you want. (or for smaller images, zoom in on create so you see more)

i.e., an 8x8 image should zoom in on creation, a 2555x2555 image should zoom out until you see the full thing in whatever canvas size Aseprite is at the moment.

I think most people zoom out initially on large images to find where they want, and on small images people zoom in, so defaulting to that would save a tedious (but trivial) task on every new image.

(Default, currently)
![01](https://cloud.githubusercontent.com/assets/3268854/9537154/24882254-4d03-11e5-8c6b-57030679b02e.png)

(How it should look, on new document, for a really small image)
![02](https://cloud.githubusercontent.com/assets/3268854/9537155/248a637a-4d03-11e5-9229-a6d19d3e2bce.png)

(How it should look, on new document, for a really large image)
![3](https://cloud.githubusercontent.com/assets/3268854/9537156/248d3898-4d03-11e5-8ae2-22490412378a.png)

**Comment by dacap** [comment]
This is a good idea. Anyway I'd like to avoid confusion when the user creates a new image so we have to be careful here.

For example, if I create a 8x8 image and see the huge canvas, I could think that I missed the width x height numbers. In other words, it must be really clear that I'm seeing a 8x8 pixels and not something bigger. Some solution for this problem, could be to show the tiny image and auto-zoom-in it with some kind of animation.

**Comment by Async0x42** [comment]
That makes sense, and an animation to zoom in or out sounds like it'd solve the issue well.

**Comment by vegeta897** [comment]
Other alternatives to consider:

  * An option in the new image dialog to auto-zoom upon creation
  * An option in the program settings that is off by default, so a user knows what's happening since they intentionally enabled this behavior

**Comment by Async0x42** [comment]
I think an option to autozoom in the settings would be best, it's not likely an option people will change often, so better not clutter the new image dialog.

Then, if enabled, has a zoom in or out effect (depending on image size), like you mentioned earlier.

**Comment by dacap** [comment]
We've just added this option, it will be turned off by default, but there are plans to turn it on by default in the future (we need to do some changes in the render engine and provide some extra feedback when the image is displayed):

<img width="833" alt="Screen Shot 2020-03-30 at 11 06 32" src="https://user-images.githubusercontent.com/39654/77921755-903f5b00-7276-11ea-9917-567851cb78bf.png">
