### ISSUE TITLE
Option to disable "brush preview" under cursor.

### ISSUE THREAD

**Issue by kyrieru** [aseprite/aseprite#792]
I think there should be an option to disable the "brush preview" that displays under your cursor. It makes things feel a bit jerky, especially when zoomed in. It can also be confusing since you can't always see if you drew a pixel or if it's just the preview. This goes for the other tools as well, such as the box select.

It would be ideal if there were a shortkey option for it, since it's still useful in some situations, even for someone like me who doesn't want to use it most of the time. For example it's useful when drawing on flat colors when you can't see or "count" pixels.

**Comment by dacap** [comment]
Related to #861 in some way
