### ISSUE TITLE
Disappearing background on RGB sprites saved as gif

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#800]
Basically the first color encountered becomes index 0 which is made transparent if the image is a "layer" not a background.

1. Open this image: 
![mario](https://cloud.githubusercontent.com/assets/8582123/9650043/3bff03cc-51cb-11e5-8273-1572a53fb96e.png)
2. File, save as .gif.
This is the result: 
![mario](https://cloud.githubusercontent.com/assets/8582123/9650048/495ec6f6-51cb-11e5-9824-9abde1b65c35.gif)

Aseprite v1.1.0.1 on Windows Vista 32 bit

**Comment by dacap** [comment]
I was contacted for the same bug. A temporal solution is converting the layer to Background (`Edit > Background from Layer`)
