### ISSUE TITLE
1.0.9 Crashes on startup in windows 10

### ISSUE THREAD

**Issue by Nsheppard01** [aseprite/aseprite#802]
I don't remember if I've used Aseprite since upgrading to windows 10, but now when I try to run it it crashes. Error message is.

	Aseprite 
	
	Unable to create a user-interface display.

and then

	Microsoft Visual C++ Runtime Library
	
	Runtime Error!
	
	Program: C:\Program Files (x86)\Aseprite\Aseprite.exe
	
	R6025
	- pure virtual function call

**Comment by dacap** [comment]
This is strange, I'm running v1.0.9 on Windows 10, 64-bit.

Could you send me your configuration file? http://imgur.com/PRZ4AaZ

**Comment by dacap** [comment]
Probably related to a broken internal state in the driver or Windows. Re-starting Windows should fix the problem.
