### ISSUE TITLE
Error building from source on linux

### ISSUE THREAD

**Issue by ImbaKnugel** [aseprite/aseprite#803]
Building the programm from source causes numerous include errors on linux. They seem to be connected to some wierd linking problems with the files `string.h/cpp` `time.h/cpp` and `signal.h`. Renaming those files and all their ocurances fixes those issues

**Comment by sirblackheart** [comment]
Telling your linux distribution and compiler when having problems compiling/linking helps a lot to reproduce your error and find a possible solution.

**Comment by ImbaKnugel** [comment]
My distro is Arch Linux and my compiler is gcc 5.2.0

**Comment by sirblackheart** [comment]
I could not reproduce those errors on a minimal arch docker image.  I also had no problem building aseprite on my personal system, which is also arch linux. Neither gcc nor clang did throw a linking error for the current master. Could the errors be related to some personal settings or environment variables? Did you pass some specific cmake parameters?

Following are the commands i used after starting a base/devel docker container, which is the same as a minimal arch installation. It compiled and linked without errors.
```shell
pacman-key --refresh-keys
pacman --noconfirm -Syu
pacman-db-upgrade
pacman --noconfirm -needed  -S base-devel cmake git libx11

git clone https://github.com/aseprite/aseprite
mkdir aseprite/build && cd aseprite/build
git submodule update --init --recursive
cmake .. && make -j4
```

**Comment by sirblackheart** [comment]
A sorry i forgot to ask. Which version of the source are you trying to compile?

**Comment by dacap** [comment]
Hi there! Also if @ImbaKnugel could [include/upload](https://gist.github.com/) the complete output/log of the compilation process that would be great. Something like:
```
git clone --recursive https://github.com/aseprite/aseprite
mkdir aseprite/build && cd aseprite/build
cmake .. && make > compilation-log.txt
```

**Comment by dacap** [comment]
(needs more info)
