### ISSUE TITLE
SplitFrameTags batch option

### ISSUE THREAD

**Issue by bfloch** [aseprite/aseprite#807]
Currently we need to use layers for animations if we want to separate them as export through batch.
Ideally there was a SplitFrameTags options similar to the SplitLayers option.

The workflow I use is ASE -> sequences of pngs per Layer -> TexturePacker.
Since most texture packers can't deal with spritesheets, but generate them from file sequences there is a need for exporting sequences.

For now it should be either export split per Layer or split ber Tag until someone comes up with a use case where you want to export all layers for each frame tag.

Just as a thought as alternative workaround: If there was a way to simply list all the tags in a ASE file into the console we could script our ways around the limitation.

**Comment by dacap** [comment]
I think the [`--list-tags` option](https://www.aseprite.org/docs/cli/#list-tags) already fixed this issue.
