### ISSUE TITLE
Zoom using mouse wheel on Macbook

### ISSUE THREAD

**Issue by HugoLamarche** [aseprite/aseprite#810]
# Initial Condition
- Macbook Pro under Yosemite with external Mouse connected
- Aseprite version v1.1.0.1

# Expected Behaviour
On Mouse scroll the view should zoom

# Result
On trackpad the zoom is okay, but on the mouse the zoom doesn't if I scroll slowly

# Why
I know it came from the wheel acceleration system on the mac enable by default. The scroll is non linear on a macbook (maybe on imac too ?) So when I scroll too slowly the zoom doesn't happen because of some kind of threshold I guess.

**Comment by dacap** [comment]
This must be reviewed with the new back-end for v1.2 #139

**Comment by Scellow** [comment]
Related: http://steamcommunity.com/app/431730/discussions/2/405692758701307787/

**Comment by dacap** [comment]
This should be fixed in v1.1.9 with 2d2fb0038afe8e57280aff21d5f65ddce10c2e2e
