### ISSUE TITLE
Show first frame in onion skin when on last frame

### ISSUE THREAD

**Issue by noxoc** [aseprite/aseprite#813]
When animating I usually have 3 frames visible through onion skinning: the previous, the current and the next (and red/blue tinting). However when I'm on the last frame I currently can't see the next - which in that case would be the first of the animation. 

Am I missing something? Otherwise consider this a feature request.

**Comment by dacap** [comment]
Hi @noxoc, you should be able to see the first frame when you are in the last one if you activate a loop section (e.g. select all frames and press F2 key or `View > Set Loop Section`). It's available since v1.1.

Related to issue #555
