### ISSUE TITLE
undefined reference to `fixmath::radtofix_r'

### ISSUE THREAD

**Issue by martinkg** [aseprite/aseprite#817]
tried to compile the recent version of aseprite on Fedora 22, but this fails with the following error message:

[ 15%] Linking CXX executable ../bin/accelerator_ui_tests
cd /home/martin/rpmbuild/BUILD/aseprite-e15b9ac/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/accelerator_ui_tests.dir/link.txt --verbose=1
/usr/bin/c++   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pthread -Wall -Wno-switch -std=gnu++11 -O2 -g -DNDEBUG   -Wl,-z,relro  CMakeFiles/accelerator_ui_tests.dir/ui/accelerator_ui_tests.cpp.o  -o ../bin/accelerator_ui_tests -rdynamic ../lib/libgtest.so ../lib/libui-lib.so -lm -lSM -lICE -lX11 -lXext -lXext -lXcursor -lXpm -lXxf86vm -lXxf86dga -lSM -lICE -lX11 -lXext ../lib/libshe.so -lloadpng -L/usr/lib64 -lalleg ../lib/libgfx-lib.so ../lib/libbase-lib.so -lpixman-1 -lXcursor -lXpm -lXxf86vm -lXxf86dga -Wl,-rpath,/home/martin/rpmbuild/BUILD/aseprite-e15b9ac/build/lib 
../lib/libgfx-lib.so: undefined reference to `fixmath::radtofix_r'
../lib/libgfx-lib.so: undefined reference to `fixmath::_cos_tbl'
collect2: error: ld returned 1 exit status
src/CMakeFiles/accelerator_ui_tests.dir/build.make:119: recipe for target 'bin/accelerator_ui_tests' failed
make[2]: *** [bin/accelerator_ui_tests] Error 1
make[2]: Leaving directory '/home/martin/rpmbuild/BUILD/aseprite-e15b9ac/build'
CMakeFiles/Makefile2:215: recipe for target 'src/CMakeFiles/accelerator_ui_tests.dir/all' failed
make[1]: *** [src/CMakeFiles/accelerator_ui_tests.dir/all] Error 2
make[1]: Leaving directory '/home/martin/rpmbuild/BUILD/aseprite-e15b9ac/build'
Makefile:141: recipe for target 'all' failed

**Comment by dacap** [comment]
Hi there, I think 1bb0bca361b8eed4350df9ee8ec544a2eb8e4bd9 should fix this problem.
