### ISSUE TITLE
"make install" also install built freetype2 lib and headers

### ISSUE THREAD

**Issue by sirblackheart** [aseprite/aseprite#822]
on current master: cc8b8cf52e205db9ef6e9aea66905aac4fa20515
It seems the defined install commands from the freetype2 [CMakeLists.txt]https://github.com/aseprite/freetype2/blob/master/CMakeLists.txt)
 inside third_party/freelib2 are added to the global make install instructions. Using a sudo make install would result in overwriting any currently installed freetype2 installation.

**Comment by dacap** [comment]
I think this shouldn't happen anymore because we're using [a patched freetype2 version](https://github.com/aseprite/freetype2/commit/27e2f011ebef85144724c30f63285852612aafa0)
