### ISSUE TITLE
Bug: Selection edges do not impede flood fill.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#823]
I seem to remember old versions, as recently as 1.1, treating selection edges as barriers to flood filling, but this no longer seems to be so. Did this change intentionally in 1.1.0.1? It's a bit of a hassle to have to either outline the entire selection up to internal blockages (that is, a pattern of pixels that 'dams the flood')...

I've tried a number of things in an attempt to find the source of the problem (if indeed it is one)-- playing with 'contiguous' and 'stop at grid' -- nothing seems to solve it. Was this a deliberate change? If not, something's broken.

Thanks!

**Comment by dacap** [comment]
Hi @oceanhahn! Flood fill should work as previous Aseprite versions by default (with `Contiguous` option checked). Are you working with one layer or multiple layers? The edge detection works only for the current layer (detecting edges in the current layer). If you are working with one layer, it's probable that you've found a bug.

**Comment by oceanhahn** [comment]
Oh, I found what's happening.
The flood fill tool seems to be filling all of the valid pixels it can see from the <i>unselected layer</i>, then <i>only filling the pixels within the selection.</i> When the flood fill tool determines which pixels to change, it looks at everything it can "see" <i>not including the selection boundaries</i>.
This is different from what I would expect (and it may just be me), which is that it would evaluate only the 'flood-able' pixels within the selection-- that is, the edges of a selected area, as well as any pixels within it, act as barriers to flood-fill.

Attached are two screencaptures of flood-fill in action: the lefthand one shows a flood within a selection within a closed shape (behaving as expected): the fill only floods the interior space of the closed shape. The righthand figure shows a flood within a selection, within an <i>open</i> shape. When the flood evaluates which pixels to fill, it looks at the <i> whole image</i> and not just the pixels in the marquee. When it actually fills pixels, though, it only changes the ones in the selection. I would have expected it to stop flooding at the edge of the selection, rather than to compute <i>every pixel</i> and only alter the selected ones. :kissing: 

Anyway, I don't know how hard that would be to fix, or if that's even what's going on. I hope this helps! :D 
(For reference, I have multiple layers, but the fill and enclosure are both on the same one.)

![11012](https://cloud.githubusercontent.com/assets/11544843/10298797/a7af3ac0-6bb0-11e5-8e70-7cef4be2057e.png)

**Comment by oceanhahn** [comment]
In short, it looks like it's flooding the unselected image, then applying just the selected portion to the view. I would have expected it to flood the selection only, ignoring all other pixels in this operation.

**Comment by dacap** [comment]
Thanks for the great explanation! The selection should act like another edge for the flood fill. (I've checked Photoshop just out of curiosity and it works correctly :smile: )
