### ISSUE TITLE
Feature request: "Copy Flattened"

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#824]
This is kind of a third-string request, but it would be really handy to have an Edit option that temporarily flattens the visible layers, copies the selected area to the clipboard, and then undoes the flatten.
Obviously, this is easy enough to do manually, but would be nice to have a macro for.

Thanks for considering it! :thought_balloon:

**Comment by huwpascoe** [comment]
:+1: :+1: :+1: to this feature

**Comment by Cerno-b** [comment]
Sorely missing this feature. I come from photoshop and use Aseprite for pixel art because it's so much better suited for the task, but man copying "what you see" is really handy if you keep character parts on separate layers and want to move some of them to a separate image to try out some things. 

In Photoshop it's Ctrl-Shift-C which is not yet taken in Aseprite as far as I know.

**Comment by dacap** [comment]
`Ctrl+Shift+C` is `Save Copy As` on Aseprite, I'm not sure if we should change the shortcut to other thing and make `Ctrl+Shift+C` execute this `Copy Merged` action. What do you think people?

**Comment by dacap** [comment]
A possibility:

* `Ctrl+Shift+A`: It's *File > Save Copy As*
* `Ctrl+Shift+C`: The new *Edit > Copy Merged*

**Comment by Cerno-b** [comment]
Not on my PC right now, but is there some combination with S still free? Like CTRL+Shift+S? I think having all save options mapped to various combinations of S might be intuitive. 

The important part is that the feature exists, the keymapping may be changed indiviually (although I advocate sensible default mappings of course)

**Comment by dacap** [comment]
It might be `Ctrl+Alt+Shift+S`

**Comment by Cerno-b** [comment]
Hm, that seems a little inconvenient. :/

Maybe that function doesn't really need a default shortcut after all? 
Don't know how often people use it though.

**Comment by dacap** [comment]
I suppose *Save Copy As* is used quite often to export an `.ase` image as a `.gif` file (and e.g. with a automatic 200% resize)

**Comment by Cerno-b** [comment]
I see. Then Ctrl+Alt+Shift+S would be too complex I guess. I'll think about this some more when I can look at the tool again, but as I said, it's probably not an issue I would lose any sleep over.

**Comment by dacap** [comment]
Actually there is already `Ctrl+Alt+Shift+K` to change keyboard shortcuts, and it looks like `Ctrl+Alt+Shift+S` is even easier to press in the keyboard.

**Comment by oceanhahn** [comment]
I use _Save Copy As_ for a bunch of different things, but I don't usually use the hotkey to get there. For copy-saves I used often, I generally use _Export_ instead.

I'm glad this has gained traction, though! :D Looking forward to it!
