### ISSUE TITLE
VS13 looking for `libcurl.lib` in a wrong folder 

### ISSUE THREAD

**Issue by grisevg** [aseprite/aseprite#825]
Latest master: f38fd4eb5e8395d1525d67cdd27a9ab60680b35a
It looks for it in `build/` not `build/lib/` (where it's actually is). If I manually move the file it successfully links.

**Comment by dacap** [comment]
Hi @grisevg, actually I'm not sure what would be the final solution to this problem. It is related to the Visual Studio project which cmake generates (for NMake or Ninja makefiles it should work correctly). I'll try to update the libcurl code to finally fix this issue (reported in #606, #608, and #788).

**Comment by Daypeak** [comment]
same here
if i manually move it in the directory or change `../lib/../libcurl.lib` to `../lib/libcurl.lib` in the project properties it compiles fine
