### ISSUE TITLE
Middle-clicking tab without moving mouse only closes one tab

### ISSUE THREAD

**Issue by numanair** [aseprite/aseprite#826]
Clicking the middle mouse button to close a tab only works once.Until the mouse is moved slightly it will not close the next tab that is under the cursor.

1. file>new. Ensure there are at least two tabs open
2. middle mouse click on the left most tab to close it. Do not move the mouse or send any other inputs.
3. middle click again.

Expected result:
each tab closes on each click of the middle mouse button.

Actual result: second tab does not close. Moving the mouse a little and then clicking the MMB on the tab will close it.

1.1.1-dev, Windows

**Comment by dacap** [comment]
Confirmed, thanks to report it @numanair :+1:
