### ISSUE TITLE
Global background settings not being remembered after closing program

### ISSUE THREAD

**Issue by ryleigh** [aseprite/aseprite#828]
Changing the Checked Background color in Global settings causes new documents to use the new setting, as expected.

But closing and restarting the program leads to the Global background color returning to black.

(v1.1.0.1, OS X 10.10.5)

**Comment by dacap** [comment]
Hi @ryleigh, I'm giving a try here and it's working, it might be possible that the program is crashing when it's being closed. Could you please check if other settings are saved? You could see the settings in `$HOME/.config/aseprite/aseprite.ini`file (*Edit > Preferences > Locate Configuration File*).

**Comment by ryleigh** [comment]
Is there a log file that'd let me know if it's crashing or not? I don't get an OS message saying anything about a crash.

It seems like it's only the background color that's getting reset. I tried to reproduce it when changing the grid color as well, but I couldn't.

Here's exactly what happens:

- start aseprite, create new Indexed/Transparent document
- check config file
```
[bg]
type = 3
color1 = gray{0,255}
color2 = gray{0,255}
zoom = false
```
- open preferences, go to Global Grid & Background, change Checked Background colors to something like Gry-200 & Gry-225, hit OK
```
[bg]
type = 3
color1 = gray{200,255}
color2 = gray{225,255}
zoom = false
```
- create new document, confirm the changes worked (and both Global & Current Document show the new colors)
- quit aseprite (config unchanged)
- open aseprite
- create new document, the background is black, but the .ini still shows the non-black colors
- open preferences, background colors for both Global & Current Document are black
- hit cancel on preferences
- quit aseprite, and at this point the config changes again:
```
[bg]
type = 3
color1 = gray{0,255}
color2 = gray{0,255}
zoom = false
```

The main issue seems to be that it's ignoring the background color config settings when I re-open the program.

I'm also not sure why it resets the config values when I close the program again, but maybe it's always set to save preferences changes to file on quit.

**Comment by dacap** [comment]
Could you please check if selecting RGB or HSV color does work? I think there is a problem saving/loading gray colors.

**Comment by ryleigh** [comment]
Yup, you're right!

When using 2 RGB colors, neither of them get ignored or reset.
When using 1 RGB color and one gray color, only the gray color is ignored & reset.
