### ISSUE TITLE
Issue building source on linux (32-bit)

### ISSUE THREAD

**Issue by Ashedragon** [aseprite/aseprite#831]
I'm currently running the ubuntu fork elementary OS 32-bit and when I attempt to build I get:
http://pastebin.com/NpckMMeH

**Comment by dacap** [comment]
Hi @Ashedragon, it looks like pthread library is not found. I think that `your-cmake-build-dir/CMakeFiles/CMakeError.log` file should contain the exact C program that is failing. Could you please attach the file to this issue?

**Comment by dacap** [comment]
More info needed.
