### ISSUE TITLE
Spray tool fails with a spray width of 6 or less

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#838]
1. Select the spray tool
2. Change spray width to 7
3. Spray. It works as intended.
4. Change spray width to 6.
5. Spray. No pixels are changed.
![spraytoolfails](https://cloud.githubusercontent.com/assets/8582123/10710880/ac1de1ba-7a38-11e5-8d11-e6c8c2c0e32b.gif)

Aseprite v1.1.1-beta8 on Windows Vista 32bit

**Comment by Fojar** [comment]
This happens for several combinations of small values of spray width and speed, when the calculation for how many pixels to spray rounds down to zero. @dacap, I have a fix for this that handles the number of pixels to spray as a fraction; can I submit a pull request?

**Comment by dacap** [comment]
Hi @Fojar, a PR would be great as I didn't see this issue yet.
