### ISSUE TITLE
Text tool steals copy buffer

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#839]
1. Open Aseprite
2. Copy a part of a sprite.
3. Paste it. The part of the sprite that was copied is pasted.
4. Open the text box tool and place some text.
5. Paste.
6. You'll get the text instead of the part of the sprite initially copied.

![texttoolstealcopybuffer](https://cloud.githubusercontent.com/assets/8582123/10710954/621264fe-7a3a-11e5-9a0f-3d52a62c90bb.gif)

Aseprite v1.1.1-beta8 on Windows Vista 32bit. It's probably known, but it's been this way for a few versions so I figured I'd make an issue.

**Comment by dacap** [comment]
Hi! Actually "Insert Text" copies the text into the clipboard and then uses the same "Paste" behavior. I'll try to fix this because as you noticed, it's not expected to the user to lost its previous clipboard content.
