### ISSUE TITLE
Asynchronous cells

### ISSUE THREAD

**Issue by Nsheppard01** [aseprite/aseprite#840]
I'm not sure if this feature exists already and I just can't find it. But is there any way to have layers with different frames?

For instance a background layer which has two frames flickering back and forth, while the other layers have more complex animations happening at a slower framerate?

**Comment by dacap** [comment]
Hi @Nsheppard01, at the moment this is not possible. There is an issue which includes something similar: #593 (in #767 something similar was requested)
