### ISSUE TITLE
Suggestion: Quick Switch key for Brush modes

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#844]
I love the new Shading brush, but there are times when I need the Simple Ink brush for just a stroke or two, to fix a change or touch up an edge, then immediately go back to Shading. A hotkey that toggles brush modes would work, but what might be more practical is having the Control or Shift key switch to the Simple Ink mode (while the Brush Tool is selected) while it's depressed, then return to the previous mode when released. If the Brush Tool is in Simple Ink mode when the key is pressed, no mode change takes place.
This behaviour would be similar to the way the Selection tools switch to Append-Selection mode when the Shift key is pressed, then return to New-Selection mode when it's released.

Thank you for considering it!

**Comment by dacap** [comment]
Hi @oceanhahn, I think you are looking for something like #787
Anyway you add the possibility to select different inks with modifiers like Control or Shift.
