### ISSUE TITLE
Running app is not associated with an icon [Linux related]

### ISSUE THREAD

**Issue by allkhor** [aseprite/aseprite#846]
Hello devs! Thanks for your work! Aseprite is getting better and better!
Maybe is not Aseprite issue, sorry for this.
As you know linux has pinning icon with .desktop files.
When we run the program, Aseprite displayed on the panel as an unknown application (icon question mark in Ubuntu 14.04). It's because xprop(linux console app) show WM_CLASS = "allegro", "Allegro". 
Workaround is add "StartupWMClass=allegro" in .desktop file.

My aseprite.desktop:
[Desktop Entry]
Name=Aseprite
Comment=Animated sprite editor & pixel art tool
Exec=/home/allkhor/app/aseprite/aseprite
Terminal=false
StartupNotify=false
Type=Application
Icon=aseprite
StartupWMClass=allegro
Categories=Graphics
MimeType=image/bmp;image/gif;image/jpeg;image/png;image/x-pcx;image/x-tga;image/vnd.microsoft.icon;video/x-flic;

**Comment by dacap** [comment]
Dup #127
