### ISSUE TITLE
Request: odd number of pixels symmetry

### ISSUE THREAD

**Issue by unaunagi** [aseprite/aseprite#853]
I wish a symmetrical image of odd numbers pixels.

![symmetry](https://cloud.githubusercontent.com/assets/4647956/11016359/a9a2ce2e-85c2-11e5-9793-66bcf2c11d4a.png)

**Comment by dacap** [comment]
I though about it when I was testing the symmetry tool, and I decided to wait some user feedback while I see how to create the UI for this even/odd symmetry switching. This should be included in the next version.

**Comment by KasumiArai** [comment]
One suggestion I might have is a checkbox to do it based on the image's resolution. (3 pixels would make the center draw one pixel, 4 pixels would make the center draw 2)

Admittedly things get weird once you move the symmetry line from the center... Maybe a radio box. one pix center, two pix center, resolution based.

**Comment by dacap** [comment]
I'm thinking that the symmetry rule might snap at the start of each pixel and in the middle of each pixel. The problem with this is that to create the "odd number" symmetry you have to zoom in.

**Comment by Async0x42** [comment]
The tool snapping at both the pixel and half pixel sounds the most intuitive to me, without adding more options and cluttering things.

Would there be a way to have a small zoomed in preview box, showing a range of pixels around the the splitter while adjusting it? Then you can avoid be user zooming in first to do half pixels.

**Comment by jpnk** [comment]
@Async0x42 a preview box would be fine for visual feedback but you still need to adjust the axis with enough accuracy - for that you need to zoom in.

alternatively the snap modes could be mapped to mouse buttons:
- the left one snaps to pixel borders,
- the right one to their centers.

you only need to add a tooltip describing this to axis handles

**Comment by ROFISH** [comment]
I think that snapping to the middle of a pixel makes sense; it's obvious that it becomes the single center line of the whole thing.
