### ISSUE TITLE
Feature request: "Reverse palette" option for shading ink brush.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#854]
It would be great to have a checkable, toggle-able option in the tool options (next to "Pixel-perfect") that inverts the index increment direction of the shading ink brush (effectively swapping the right and left mouse buttons with that tool).
The tool is perfectly functional as-is, but it would make tablet life a lot easier, and drawing with the right mouse button held seems clumsier for me than with the left one held.

Just a small thing; thanks for considering it!

**Comment by dacap** [comment]
Related to #85 item, `X` key should reverse the gradient.
