### ISSUE TITLE
Could not build on Ubuntu 15.04

### ISSUE THREAD

**Issue by TeddyDD** [aseprite/aseprite#857]
While using ```cmake .. -G "Unix Makefiles"``` on ```v1.1.1``` tag I got this errors:

```
-- Could NOT find ZLIB (missing:  ZLIB_INCLUDE_DIR) 
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Could NOT find ZLIB (missing:  ZLIB_INCLUDE_DIR) 
-- Could NOT find PNG (missing:  PNG_LIBRARY PNG_PNG_INCLUDE_DIR) 
-- Checking for module 'harfbuzz>=0.9.7'
--   Found harfbuzz, version 0.9.37
-- Checking for module 'harfbuzz-icu>=0.9.18'
--   Package 'harfbuzz-icu>=0.9.18' not found
CMake Error at /home/teddy/Programy/cmake-3.3.1-Linux-x86_64/share/cmake-3.4/Modules/FindPkgConfig.cmake:360 (message):
  A required package was not found
Call Stack (most recent call first):
  /home/teddy/Programy/cmake-3.3.1-Linux-x86_64/share/cmake-3.4/Modules/FindPkgConfig.cmake:522 (_pkg_check_modules_internal)
  third_party/freetype2/builds/FindHarfBuzz.cmake:47 (pkg_check_modules)
  third_party/freetype2/CMakeLists.txt:156 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/teddy/src/aseprite/build/CMakeFiles/CMakeOutput.log".
See also "/home/teddy/src/aseprite/build/CMakeFiles/CMakeError.log".
```
I'm using cmake version 3.4.0-rc2.

**Comment by TheKK** [comment]
Have you installed pacakge `libharfbuzz` in your system?

**Comment by TeddyDD** [comment]
I'v got both ```libharfbuzz-bin``` and ```libharfbuzz-dev``` (version 0.9.37-1)

**Comment by TheKK** [comment]
My bad, the package you miss is `harfbuzz-icu`, you can check if you've installed first.

**Comment by TeddyDD** [comment]
I'v got package ```libharfbuzz-icu0``` installed :(

**Comment by dacap** [comment]
Hi @TeddyDD, just in case, the error says that you need package `harfbuzz-icu` with version >= `0.9.18'. Could you check your `libharfbuzz-icu0` package version?

**Comment by TeddyDD** [comment]
It's ``` 0.9.37-1```

**Comment by TheKK** [comment]
Another possible problem is that pkg-config can't find out the corresponded `.pc` files. You can try `pkg-config --list-all | grep harfbuzz` to see if pkg-config works without problem, here's my output:

```shell
$ pkg-config --list-all | grep harfbuzz
harfbuzz                    harfbuzz - HarfBuzz text shaping library
harfbuzz-icu                harfbuzz - HarfBuzz text shaping library ICU integration
harfbuzz-gobject            harfbuzz - HarfBuzz text shaping library GObject integration
```

To fix this (if this is what you need), simply run `export PKG_CONFIG_PATH=SOME_WHERE`. In my case (Ubuntu 14.04), I set this value to `/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig`. Or you could find where the .pc file located in your box and use that value.

Hope this would work for you :)

**Comment by TeddyDD** [comment]
pkg+config gives me the same output as yours :(
I don't know if is this worth of more debugging. It might be something specific to my box (it's quiet tweaked Ubuntu Gnome). I'll be reloading my box this weekend then I'll try.

**Comment by TeddyDD** [comment]
I'm compiling right now on Arch and works like a charm :)

**Comment by oriceemple** [comment]
On Ubuntu 16.04, this can be solved by doing `sudo apt install libicu-dev`, I suspect this will also work on 15.04.
