### ISSUE TITLE
Aseprite occasionally forgets the UI zoom settings

### ISSUE THREAD

**Issue by Taschenschieber** [aseprite/aseprite#860]
When starting Aseprite, I'm occasionally greeted by this image:

![image](https://cloud.githubusercontent.com/assets/5377412/11153030/747b5f18-8a36-11e5-9ef9-bdf26a644f5b.png)

Going into the options dialog then looks like this:

![image](https://cloud.githubusercontent.com/assets/5377412/11152978/246518f2-8a36-11e5-98fc-13841694bade.png)

The UI scale was set to 100% before this happened, as was the screen scale. As you can see, this is a bit problematic because it's hard to revert to the previous settings because the UI is getting bigger than my screen.

**Comment by KasumiArai** [comment]
This happens to me occasionally as well, but I've never come up with a repeatable way to make it happen.

**Comment by dacap** [comment]
I'll add a check/way to revert/reset the UI scaling if it's too small to see the whole settings dialog. Also this problem is related with other one: If the main window is too small (or the scale is too big), the context bar could be to narrow to show all options. We need an adaptative/responsive layout for UI controls.

**Comment by Taschenschieber** [comment]
That would work for me, but options changing on their own should probably still be considered a different bug.

**Comment by dacap** [comment]
Yes, I wasn't able to reproduce this bug yet. The only thing I can think of is that as the UI Scaling doesn't change until we restart the program, if we modify its value and then we forgot about it, restarting the program will show the new UI Scaling factor. So it can be confusing. But as you said, it's highly probable that the value is changed automatically by some problem in the code.

**Comment by desult** [comment]
I have made to UI too big and now the software is unusable. It's too big to even get to preferences to change it.

**Comment by dacap** [comment]
Hi @desult, in v1.1.8 or v1.2-beta2, you should see a red flag at the top-right corner to reset the UI screen scaling settings. Anyway, if you don't see it, you can reset the preferences with this method:  http://www.aseprite.org/docs/reset-preferences/

**Comment by desult** [comment]
@decap Thanks! I decided to search Windows and delete everything with "Aseprite", then reinstalled. Just uninstalling didn't work; the preferences still lingered.
