### ISSUE TITLE
Possibility to change angle in rectangles and ellipses

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#868]
So we can create ovals with any angle and rotated rectangles. This might be related to #818 

EDIT: Check #1665, #1649, and [this tweet](https://twitter.com/retronator/status/966619431668502533).

**Comment by Hammster** [comment]
You've already commented on the tweet but i think its not bad for people to have some reference image :) https://twitter.com/retronator/status/966619431668502533
