### ISSUE TITLE
I am getting an error while opening aseprite

### ISSUE THREAD

**Issue by sanvishal** [aseprite/aseprite#869]
![untitled](https://cloud.githubusercontent.com/assets/15110377/11301459/5465a710-8fbd-11e5-82f6-1bbae78cf42f.png)

please help me out as soon as possible!! I was not able to draw my sprites. reply ASAP!!!!! 

thanks for Aseprite :)

**Comment by dacap** [comment]
Hi @sanvishal, are you using the official version v1.1.1?

**Comment by dacap** [comment]
Contact us at support@aseprite.org in case you are getting this problem with the official version v1.1.1. If it's your own compilation, you can share with us the compilation log.

**Comment by sanvishal** [comment]
I am having version 1.0. Do I have to install microsoft c runtime library? if it is. I have installed it already. still I am getting this. I found aseprite link somewhere on the internet. please help me!! I was not able to buy aseprite (money problem ):(

**Comment by dacap** [comment]
First result on Google says that it could be related to a virus: https://www.reddit.com/r/TPPcrack/comments/3k86cl/error_idcodecvtddhstd2volocale2a_not_found_in_dll/

**Comment by dacap** [comment]
Did it work before? The first thing I thought about is the a C runtime.

**Comment by sanvishal** [comment]
nope It did'nt work this is the first time I am opening aseprite.

**Comment by dacap** [comment]
I think you should contact the person who compiled it. He/she might help you with this issue. Anyway it's highly probable that it's related to a missing runtime dll (e.g. `MSVCP110.dll`)

**Comment by sanvishal** [comment]
I am actually having a touch enabled tablet and I am trying to draw with my hands. I was not able to draw. why? can you fix it?
