### ISSUE TITLE
Feature request: option to rearrange palette colors without changing colors in image

### ISSUE THREAD

**Issue by bfod** [aseprite/aseprite#871]
Now that we have this nice shading mode, you often need to reorder your palette so that the nice ramps are sitting together - there's no single 'correct' arrangement of colors for the shading mode, it depends what you're shading.

But when you go to drag a color to a different position, the image keeps the same indexes for all pixels, which means the colors change in the image. It would be great to have the option to move the colors around without changing the image at all. Maybe a checkbox for 'remap palette'?

**Comment by vegeta897** [comment]
I find myself running into this issue all the time. Right now my workaround is to change the image mode to RGB, fix my palette, then change back to indexed. It'd be great if there was an easy toggle option that automatically re-mapped indexes when moving colors so the image remains unchanged.

**Comment by dacap** [comment]
Related to an task item in #85, we should be able to drag-and-drop colors in the shading field. (Also it should be a combobox, so we have an history of used shades.)

**Comment by bfod** [comment]
Oh cool, yeah that would work fine

**Comment by dacap** [comment]
Implemented in 0f8997b3df1572a2e6bd6ea17ad35e949c3d9567
