### ISSUE TITLE
New Sprite dialog polish

### ISSUE THREAD

**Issue by jpnk** [aseprite/aseprite#875]
i think 'Width' and 'Height' should have a 'px' suffix (`Entry::setSuffix`) and maybe they don't need their tooltips because those are largely redundant.

**Comment by dacap** [comment]
I thought the same thing (as the brush size already has a `px` suffix) but then forgot to implement :sweat_smile:

**Comment by dacap** [comment]
A "little" problem, as by default the `Width` field is focused, the prefix is now being shown:
![newsprite](https://cloud.githubusercontent.com/assets/39654/11380321/10f119be-92d4-11e5-80fe-ecd9ebe3e09b.png)

Maybe the `px` suffix should be right-aligned and always-visible.

**Comment by jpnk** [comment]
maybe the numbers should also be right-aligned. so that they're always right next to the suffix.

**Comment by dacap** [comment]
I left the `px` suffix in the same position but it's always visible. Anyway I'm not 100% sure about this change.
