### ISSUE TITLE
Request: starting with 0 index when saving a series of PNGs

### ISSUE THREAD

**Issue by ryleigh** [aseprite/aseprite#876]
This is a pretty minor gripe, but I wish when saving out `image_.png` it would create `image_0.png, image_1.png, image_2.png` instead of `image_1.png, image_2.png, image_3.png`.

It almost seems too insignificant to have a menu option, but currently I can't help renaming the images every time I export them, for consistency.

I'm not sure how much of Aseprite's userbase are programmers... maybe most users like starting with 1? Maybe lots would prefer 0 as well?

**Comment by dacap** [comment]
Hi @ryleigh, you should be able to specify `image_1.png` as filename and it will start from `1`.

**Comment by ryleigh** [comment]
Ah I should have thought of that, thanks!!

**Comment by bedarasfandiyar-debug** [comment]
Make this guy on somewhere up and take him in para shoot and slowly come down
