### ISSUE TITLE
Bug: Spacebar-pan key input is ignored immediately after clicking in the frames/layers bar.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#877]
Pressing the spacebar immediately after clicking anywhere in the frames/layers bar does not trigger pan image mode. My guess is that the frames/layers bar has focus and that the image editor doesn't know the input is "for it," but I'm not sure if that's how ASEprite works. ;)

In any case, if I switch layers and then go to pan using spacebar, whatever tool I currently have selected (not pan) is invoked instead, so often I'll switch layers and then go to pan the image, but get a nice, long brush streak over my graphic when I wanted to scroll it instead. After any click or (probably any) non-spacebar hotkey invoke in the editor window, spacebar-pan works as normal.

**Comment by oceanhahn** [comment]
Hey again, just wondering if there was any view of this bug getting sorted out on the horizon. ^^;

**Comment by dacap** [comment]
Hi @oceanhahn, thanks for bring this back. I've just tested and it's quite annoying, I'll try to fix this for the next v1.1 version.

**Comment by oceanhahn** [comment]
Thanks for taking care of this for me! :D
