### ISSUE TITLE
Feature Request: Auto-export Capability

### ISSUE THREAD

**Issue by SolarLune** [aseprite/aseprite#880]
Hey, there! 

I think it'd be a nice feature to add to have an ability to have an ASE file auto-export on save. This way, you could automatically export to a sprite-sheet or a single file of whatever format whenever you save, rather than having to work on the ASE file, and then export again for actual use in your game engine.

I guess a way to do this would be to have "Automatically Do This On Save" in the Export and Save Copy As dialog boxes. Checking it would be saved when you save the ASE file, and unchecking it would disable it for that "export mode".

I noticed the Repeat Last Export option, which should help me out, but isn't quite the same as an automatic function.

**Comment by dacap** [comment]
Dup #138
