### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by tony** [aseprite/aseprite#889]
This application is fantastic. It took a lot of talent, skill and dedication to make this.

I have been able to get this running on aseprite after a few minor tweaks (recompiling openssl port without OpenSSL v2, #888).

![aseprite](https://cloud.githubusercontent.com/assets/26336/11608667/a07f5500-9b35-11e5-86e1-3bda5d3ce41f.png)

I am able to get it running if I open it from ./build/bin. However, trying to access it any other way, such as /usr/local/bin/aseprite (after make install), gives the gui.xml error.

![2015-12-05-094740_240x65_scrot](https://cloud.githubusercontent.com/assets/26336/11608668/a63a18d6-9b35-11e5-9ca1-872d6ef9455e.png)

I see a similar error at https://code.google.com/p/aseprite/issues/detail?id=84.  Before I dig too deep into it, is ./aseprite only executing when cwd'd inside ./build/bin by design (for the purpose of development)?

**Comment by tony** [comment]
(By the way, using a tiled window manager, works great tiled and untiled.)

**Comment by TheKK** [comment]
I think it a good start looking at [resource_finder.cpp](https://github.com/aseprite/aseprite/blob/master/src/app/resource_finder.cpp#L82). The problem you found might be caused by different directory tree naming or the implementation of finding/reading file by aseprite.
