### ISSUE TITLE
Mac Retina Support

### ISSUE THREAD

**Issue by amadeus** [aseprite/aseprite#903]
I know it's kind of a small thing, but it would be nice if the native Mac controls could support retina.

An example of what I am talking about can be seen here:

![example](https://dl.dropboxusercontent.com/s/c4e6g74mvgs512t/Aseprite_v1.1.1_2015-12-15_19-10-49.png?dl=0)

As you can see, on a Retina iMac the Close/Minimize/Maximize buttons are pixellated.

The rest of the custom UI looks great however.

**Comment by jameszaghini** [comment]
I notice the same on v1.1.11-trial.  I complied from source and it looks to be fixed on v1.1.12-dev
<img width="268" alt="screen shot 2017-01-05 at 11 21 38 am" src="https://cloud.githubusercontent.com/assets/596101/21665753/82a60578-d339-11e6-9a2c-3802866d2e7e.png">
<img width="248" alt="screen shot 2017-01-05 at 11 20 56 am" src="https://cloud.githubusercontent.com/assets/596101/21665755/82f3349c-d339-11e6-913b-4c172a58f09d.png">
Open those images in their own tab as it looks like they've been scaled here.

**Comment by grauw** [comment]
Hmm, not in the 1.2 beta I’ve downloaded from steam.

An additional benefit would be that zoom levels < 100% would be sharper.

**Comment by nathanhornby** [comment]
I just picked up Aseprite and this issue is still present even on the latest beta.

**Comment by dacap** [comment]
Next version will have this issue fixed.
