### ISSUE TITLE
Selection line isn't accurate on some zooms with magic wand

### ISSUE THREAD

**Issue by Async0x42** [aseprite/aseprite#905]
Sometimes the selection line is offset a little bit, when it shouldn't be, but depends on the zoom (and functions normally regardless)

This was on a 500px image, using 1.1.2-dev

![error](https://cloud.githubusercontent.com/assets/3268854/11860732/e68ea12c-a445-11e5-89b2-e0203cb91ebe.gif)

**Comment by TheKK** [comment]
I think the is caused by casting from double to integer without round (or some have but the others aren't).
