### ISSUE TITLE
Paint bucket bug with symmetry

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#906]
Paint bucket is not filling the other symmetry side correctly. Example:
https://twitter.com/vine2D/status/677349036991512578

**Comment by vncastanheira** [comment]
Is this still persist on 1..1.2?

**Comment by dacap** [comment]
It looks like it's fixed. But I don't remember when I fixed it :sweat_smile:

**Comment by dacap** [comment]
I'll close this issue as I wasn't able to reproduce it anymore.
