### ISSUE TITLE
Selection box disappears when you press delete

### ISSUE THREAD

**Issue by kyrieru** [aseprite/aseprite#907]
If you select stuff (rectangle, wand, etc), and then delete whatever is within the selection, it also gets rid of the selection.

This is unwanted behavior sometimes, since there have been  multiple times were I've wanted to select an area, and then use that selection to delete stuff across multiple frames.

**Comment by dacap** [comment]
Hi @kyrieru, you can use *Edit > Reselect* menu to show the selection again (`Ctrl+Shift+R` shortcut). I know it isn't optimal to delete the same area in several frames, but it a good option.

**Comment by kyrieru** [comment]
Thanks for the response. (It's select > reselect, btw)

True while it isn't optimal, it's still a good option for now. I've remapped it next to my delete hotkey, so it should be pretty fast.

Thanks for the help.

**Comment by dacap** [comment]
> It's select > reselect, btw

Oh yeah, sorry :sweat_smile:

**Comment by Async0x42** [comment]
Just for further input, I actually ran into the same issue yesterday and was confused, expecting the selection to persist through deletes

**Comment by dacap** [comment]
I think the current behavior is more MS Paint-like, and the persistent selection is more Photoshop-like. Maybe an option in Preferences to change this behavior would be enough.

**Comment by Async0x42** [comment]
I think that'd be a good solution
