### ISSUE TITLE
Cannot run aseprite due to missing user brush file

### ISSUE THREAD

**Issue by Bobhostern** [aseprite/aseprite#911]
Whenever I attempt to run aseprite, I just get a commandline error:
`Error loading file: /home/****/.config/aseprite/user.aseprite-brushes`

It seems to be related to the saving and loading of brushes, and it comes from src/app/xml_document.cpp.

It can be fixed by manually creating the file, then creating a top-level XML element, but I don't believe that is an optimal solution.

**Comment by dacap** [comment]
Thanks @Bobhostern for reporting this issue!
