### ISSUE TITLE
Feature request: Double click vacant tab space for new file.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#912]
Hey, this is another kind of trivial feature request, but it might be fun to have a new file prompt open if the vacant space to the right of active tabs (in the tab space under the menu bar) is double-clicked. 
The same behaviour exists in Notepad++, if you're familiar with it.

Perhaps, additionally, when the tab bar is "full" (the width of all open tabs is greater than the width of the window), scrolling the whole way to the right would reveal a smallish vacant gap reserved for this purpose. (Notepad++ also does this.)

Thanks for considering it!

**Comment by Async0x42** [comment]
Actually, to me this'd be a nice little feature as well. I use Notepad++ and it's really convenient.

**Comment by dacap** [comment]
In someway related to https://github.com/aseprite/aseprite/issues/1024#issuecomment-200535172

**Comment by oceanhahn** [comment]
Just want to give this thought a bump! :D

**Comment by oceanhahn** [comment]
Aw. Well! Still looking forward to this! :D

**Comment by dacap** [comment]
I'll add this today in v1.2.2 (but the `when the tab bar is "full"` part will be for other version)

**Comment by dacap** [comment]
@oceanhahn it was a long wait, today you have this feature in v1.2.2 👴 😄

**Comment by oceanhahn** [comment]
Well worth the wait! Thanks! 🎉
