### ISSUE TITLE
Hardware mouse cursor displayed above application's cursor

### ISSUE THREAD

**Issue by akciom** [aseprite/aseprite#913]
On Ubuntu 15.04, somewhere between v1.1.0.1 and v1.1.1 releases (still a problem with the most recent git version) the hardware cursor started appearing over the application's cursor like in the image below. Is there anything that might have been modified between those two versions that could have caused this issue? I'd be more than happy to investigate further but not really sure where to look in the 200+ commits between releases. Any ideas?

![cursor_over_cursor](https://cloud.githubusercontent.com/assets/126106/12007745/b3f8ffa8-abe0-11e5-9d4e-670c173f64c5.png)

**Comment by dacap** [comment]
Don't worry. I'm going to review this issue for v1.1.2 next week.

**Comment by trentg** [comment]
This issue affects other versions of Ubuntu also. I'm on 14.04.

**Comment by GeertJohan** [comment]
Ubuntu 15.10 here, have the same.

**Comment by GeertJohan** [comment]
Just built from master and noticed that this issue is fixed there.

**Comment by dacap** [comment]
Hi @GeertJohan, could you please check if this is fixed? I'm compiling master in a virtual machine and it doesn't look fixed :sweat_smile:

**Comment by dacap** [comment]
@GeertJohan I think that you might have "Edit > Preferences > Experimental > Use native mouse cursor" enabled and that's why you don't see the software cursor below the hardware one.

**Comment by akciom** [comment]
I just built from master and the cursor issue appears to be solved... kinda. Not sure if this is related or not, but now the mouse doesn't work at all\*. When I scroll with the mouse wheel or click, the cursor changes from say the finger or cross pointer to the default pointer. Using the scroll wheel or clicking repeatedly, occasionally the hardware cursor flashes on the screen briefly.

\* The mouse sometimes recognizes input but only when I'm spamming the buttons or wheel and moving the cursor around.

**Comment by dacap** [comment]
This bug can be fixed installing libxcursor-dev in your system. I'll make a note in INSTALL.md that this dependency is necessary to avoid this issue.
