### ISSUE TITLE
Copy & Paste from Photoshop doesn't work (mac OSX)

### ISSUE THREAD

**Issue by HawkenKing** [aseprite/aseprite#925]
This would improve workflow efficiency 10,000%

**Comment by Cerno-b** [comment]
What do you mean exactly? I can copy paste from Photoshop without problems (Windows 7, Photoshop CS2). Care to elaborate what doesn't work for you?

**Comment by HawkenKing** [comment]
Copy & paste from photoshop doesn't work on OSX version.

**Comment by dacap** [comment]
Related to #172

**Comment by dacap** [comment]
For Linux clipboard support see #1100
