### ISSUE TITLE
Resizing selection = lag?

### ISSUE THREAD

**Issue by iUltimateLP** [aseprite/aseprite#929]
Hey, If I try to resize a selection with only 10 pixels or so, it laggs really terrible even If I only hover on one of the resize anchors..
My specs:
i5-4670K @3.4 GHz
8 GB RAM
GTX 960 - 4GB VRAM

**Comment by dacap** [comment]
Hi @iUltimateLP, are you using the `master` branch version or the latest official one (v1.1.1)? I'll push a fix right now on `master` branch in case you can test it. (I'm working in some modifications in the scrolling code so it's unstable at the moment, e.g. the whole sprite editor is redrawn when we scroll.)

**Comment by iUltimateLP** [comment]
Yep, fixes it, thanks :+1:
