### ISSUE TITLE
Compiling on windows 7 using VC 2013 cmake config generate error: DirectX required for Windows port

### ISSUE THREAD

**Issue by meiry** [aseprite/aseprite#931]
Im using windows 7 64bit , VC 2013 community version 
installed dx 11 and cmake 3.3 
when running cmake to generate VS project files im getting :
```
G:\dev\cpp\Editors\Aseprite\aseprite\build>cmake .. -G "Visual Studio 12 2013"
-- The C compiler identification is MSVC 18.0.31101.0
-- The CXX compiler identification is MSVC 18.0.31101.0
-- Check for working C compiler using: Visual Studio 12 2013
-- Check for working C compiler using: Visual Studio 12 2013 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 12 2013
-- Check for working CXX compiler using: Visual Studio 12 2013 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Performing Test HAVE_STDINT_H
-- Performing Test HAVE_STDINT_H - Success
-- Performing Test HAVE_SCHED_YIELD
-- Performing Test HAVE_SCHED_YIELD - Failed
-- Performing Test ASEPRITE_LITTLE_ENDIAN
-- Performing Test ASEPRITE_LITTLE_ENDIAN - Success
-- Could NOT find DXGUID (missing:  DXGUID_LIBRARY)
CMake Error at src/she/CMakeLists.txt:15 (message):
  DirectX required for Windows port.  You might need to add DirectX include
  and lib directories to your INCLUDE and LIB environment variables.


-- Configuring incomplete, errors occurred!
See also "G:/dev/cpp/Editors/Aseprite/aseprite/build/CMakeFiles/CMakeOutput.log".
See also "G:/dev/cpp/Editors/Aseprite/aseprite/build/CMakeFiles/CMakeError.log".

G:\dev\cpp\Editors\Aseprite\aseprite\build>cmake -version
cmake version 3.2.2
```

**Comment by dacap** [comment]
You need a DirectX SDK or Windows SDK 8.1 with `dxguid.lib`. I have the `DXGUID_LIBRARY` variable with this value on `CMakeCache.txt`:

    DXGUID_LIBRARY:FILEPATH=C:/Program Files (x86)/Windows Kits/8.1/Lib/winv6.3/um/x86/dxguid.lib

I'm not sure but I think VS2013 should include this SDK. Please find `dxguid.lib` in your file system and see if you can configure the path manually in your `G:\dev\cpp\Editors\Aseprite\aseprite\build\CMakeCache.txt` file.

**Comment by meiry** [comment]
I have the same path , what should i run after i add it to the CMakeCache.txt?

**Comment by dacap** [comment]
But does `C:/Program Files (x86)/Windows Kits/8.1/Lib/winv6.3/um/x86/dxguid.lib` exist in your file system?

**Comment by meiry** [comment]
Yes 



‫ב-5 בינו׳ 2016, בשעה 17:29, ‏‏David Capello ‏<notifications@github.com> כתב/ה:‬

But does C:/Program Files (x86)/Windows Kits/8.1/Lib/winv6.3/um/x86/dxguid.lib exist in your file system?

**Comment by TimothyWrightSoftware** [comment]
I am having the same problem.  I tried to install an older DirectX SDK but windows 10 does not allow it.  It just has an error that "Windows XP is no longer supported".  And I do not have a Windows Kits/8.1, just Windows Kits/10

**Comment by orlando2bjr** [comment]
In the FindDXGuid.cmake file, I just renamed the path to "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.10586.0/um/x86"

**Comment by bantonioch** [comment]
Hi, folks-
Is it normal the compilation stops/freezes with no apparently progress at this point?
```
The C compiler identification is MSVC 19.0.23506.0
The CXX compiler identification is MSVC 19.0.23506.0
Check for working C compiler using: Visual Studio 14 2015
Check for working C compiler using: Visual Studio 14 2015 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 14 2015
Check for working CXX compiler using: Visual Studio 14 2015 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
Looking for include file stdint.h
Looking for include file stdint.h - found
Performing Test HAVE_STDINT_H
Performing Test HAVE_STDINT_H - Success
Performing Test HAVE_SCHED_YIELD
Performing Test HAVE_SCHED_YIELD - Failed
Performing Test HAVE_DLFCN_H
Performing Test HAVE_DLFCN_H - Failed
Performing Test ASEPRITE_LITTLE_ENDIAN
```
I dont know if i must find a workaround to that or if i just must wait a lot of time. Btw I have Msvs 2015 ; directx sdk 2010 and cmake 3.5

**Comment by dacap** [comment]
Hi @bantonioch, that's not common. When it reaches that point a little C program is compiled to know the CPU endianness. I think you might try to see the cmake logs in the build directory to know what it's doing. I'll install cmake 3.5 just in case this is a new issue with cmake.

**Comment by bigolpete** [comment]
The below from dacap worked for me. One thing I would note when adding the path: Make sure to use "/" and not "\" in the script or it will fail. As long as you have dxguid.lib in that location, you should be good to go.

I ran into issues building the solution in VS 14 2015, but I'm working through it. 

> You need a DirectX SDK or Windows SDK 8.1 with dxguid.lib. I have the DXGUID_LIBRARY variable with this value on CMakeCache.txt:

> DXGUID_LIBRARY:FILEPATH=C:/Program Files (x86)/Windows Kits/8.1/Lib/winv6.3/um/x86/dxguid.lib
I'm not sure but I think VS2013 should include this SDK. Please find dxguid.lib in your file system and see if you can configure the path manually in your G:\dev\cpp\Editors\Aseprite\aseprite\build\CMakeCache.txt file.
