### ISSUE TITLE
Support save to vector SVG format

### ISSUE THREAD

**Issue by cheeaun** [aseprite/aseprite#934]
This feature request might not work for frames and animation. I know that I can save to PNG with various resize percentages but would be great if I can save to SVG, so basically pixel art but in (resizable) vector form :heart_eyes: 

A little googling shows that this could be similar to [pixel2svg](http://florian-berger.de/en/software/pixel2svg/).

**Comment by laserbeak** [comment]
Would love to see this!

**Comment by Codecomp** [comment]
Thirded, Would be extremely useful for bringing sprites onto websites with crystal clear scaling. Found this while checking to see if this was doable as one of our designers is designing a gaming charity website having issues with existing vector software and "Pixels"

**Comment by dacap** [comment]
I guess there are two opportunities for "to a SVG" conversion:

1. Export pixels like squares (easy to be done)
2. Create a vectorized version of the image (using an [image tracing algorithm](https://en.wikipedia.org/wiki/Image_tracing))

**Comment by boaromayo** [comment]
I like this idea too!

**Comment by markthewolf90** [comment]
This would be a very welcome addition, as pixel2svg outputs corrupt files so I'm stuck with a simplistic conversion python script that's usable but highly limited.

**Comment by dacap** [comment]
@markthewolf90 if you want, you can share an example of png -> expected svg output and I'll try to do something about this.

**Comment by its-kyle-yo** [comment]
Adding a +1 to this 👍. For many people trying to make stuff for web apps an SVG would be great! 

Is this still being investigated @dacap ?

**Comment by dacap** [comment]
@its-kyle-yo I'm not working on this one, but I'll try to add something for v1.2.10.
