### ISSUE TITLE
Can't compile on OS X 10.11

### ISSUE THREAD

**Issue by 3rr3s3v3n** [aseprite/aseprite#935]
Hi everyone,
as the title says, I can't compile Aseprite on OS X 10.11.
The problem is that I can't install the 10.4 SDK (the install procedure fails).
Thank you in advance!

**Comment by dacap** [comment]
Hi @3rr3s3v3n 

> the install procedure fails

Do you have some kind of log or screenshot about this problem? Did you find the `MacOSX10.4.Universal.pkg` file?

**Comment by 3rr3s3v3n** [comment]
Maybe I tried to install the wrong pkg.
Where can I find that package? I didn't managed to find it via Apple Developer portal...
Only one question: why use 10.4 SDK?

**Comment by tony** [comment]
@3rr3s3v3n Try these instructions:

 Tested Jan 2nd, 2016 on El Capitan (10.11):

Download ``xcode314_2809_developerdvd.dmg`` from https://developer.apple.com/downloads/. The title is *Xcode 3.1.4 Developer Tools*.  Then, Ctrl-click ``MacOSX10.4.Universal.pkg``, open, open.

**Comment by dacap** [comment]
@3rr3s3v3n as @tony said, you can find `MacOSX10.4.Universal.pkg` inside "Xcode 3.1 Developer Tools" as it's described in [INSTALL.md](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#mac-os-x-details)

> why use 10.4 SDK

Because Allegro 4 needs 10.4 to be compiled. Future versions (1.2) will use the latest SDK.

**Comment by 3rr3s3v3n** [comment]
Ok, understood, thank you, I'll try in the near future...
... or maybe I'll just wait 'till the latest SDK will be used :D

**Comment by 3rr3s3v3n** [comment]
Compiled, thank you! ^.^
