### ISSUE TITLE
Color Match issue

### ISSUE THREAD

**Issue by MoVoDesign** [aseprite/aseprite#936]
Hi,
When I open a dirt texture I created, load as .gif, .png or .jpg
the color matching to the palette is off, looking a bit dull
ie for pix (0,0) #AF7F62 for my original / #AC815E for the one loaded in aseprite.
I tried to put everything on RGB mode, reload... but same result.

see screen capt. below for reference

![issue](https://cloud.githubusercontent.com/assets/16720798/12355492/55baba5e-bb9d-11e5-9b3b-f425c75a5b7b.png)

**Comment by not-surt** [comment]
Sounds like the PNG gamma correction problem: https://hsivonen.fi/png-gamma/

**Comment by dacap** [comment]
This should be fixed in v1.2.10-beta2 which includes color management: https://community.aseprite.org/t/aseprite-v1-2-10-beta2/2171
