### ISSUE TITLE
Multiresolution export support

### ISSUE THREAD

**Issue by Secretmapper** [aseprite/aseprite#937]
Export at 2x/4x/8x size

**Comment by dacap** [comment]
Hi @Secretmapper, I think what you are looking for is the *Resize* field inside *File > Save Copy As* menu option. Please confirm if this is enough (and then we close this issue).

Other option is to [export automatically from a .bat file](http://www.aseprite.org/docs/cli/#automating-the-process).

**Comment by Secretmapper** [comment]
Thanks @dacap, should have looked more closely! Indeed this can be closed :)

Just a note though, but the option doesn't seem to be present when exporting sprite sheet (and the reason why I didn't see it at first). Might be a little addition, but it's fine as it is!

Thanks

**Comment by dacap** [comment]
You're welcome!
And +1 for a scale factor in Export Sprite Sheet (it will be implemented in #493)
