### ISSUE TITLE
Feature request: Grow/shrink selection area

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#942]
Might be handy to have an option in the Select menu that lets us grow or shrink selection area. Photoshop, among others, have this kind of function, and it would be super-useful here, I think. Great for adding and (to a lesser degree) removing outlines.

For clarity's sake, the behaviour I'm thinking of is a menu option that lets us enter a positive or negative value, which, once committed, adds every pixel within that distance (in px) of an initially-selected pixel (for positive) or deselects every pixel within that distance of an unselected/perimeter pixel (for negative).
Instead of using a positive/negative distance, it might be clearer to have an option that toggles between Grow and Shrink.

Food for thought.
Thanks for considering it!

**Comment by dacap** [comment]
Already added. It will be available in v1.1.2 (5dc149d30834c417280f4285136cc67bb0ebbed6) :wink:

**Comment by dacap** [comment]
![modify-sel](https://cloud.githubusercontent.com/assets/39654/12589702/db4e43c2-c43d-11e5-9713-842e590c56c0.png)

**Comment by oceanhahn** [comment]
Great, thanks! Sorry to repeat it if this was already open somewhere else. :D
