### ISSUE TITLE
Ink controls not working correctly with custom brush

### ISSUE THREAD

**Issue by not-surt** [aseprite/aseprite#945]
When using a custom bitmap brush the ink selector is not visible and so cannot be changed though the previously selected ink mode remain in effect.

**Comment by dacap** [comment]
Internal note: This issue will need some redesign of the "ink processing" classes. We need a mix between the [BrushInkProcessing](https://github.com/aseprite/aseprite/blob/08a04fcb64faf1f3a7ae267260ac8e9561b9bda3/src/app/tools/ink_processing.h#L898) and other inks (e.g. the [TransparentInkProcessing](https://github.com/aseprite/aseprite/blob/08a04fcb64faf1f3a7ae267260ac8e9561b9bda3/src/app/tools/ink_processing.h#L208) or [ShadingInkProcessing](https://github.com/aseprite/aseprite/blob/08a04fcb64faf1f3a7ae267260ac8e9561b9bda3/src/app/tools/ink_processing.h#L706)). It's like the `BrushInkProcessing` should act as a source of colors for the other inks. So by default we have a "solid color" source (the foreground color) for other inks, and with a custom brush we have a "multiple color source".

**Comment by dacap** [comment]
The ink selector is now available, but it's not working 100% right. We'll left this issue open to check that the behavior of the context bar is correct for custom brushes too.
