### ISSUE TITLE
Crash when resizing palette editor

### ISSUE THREAD

**Issue by not-surt** [aseprite/aseprite#949]
Current git.

When shrinking the width of the palette editor window aseprite crashes.
If I quickly drag it to minimum size it doesn't crash, but if I drag slowly it crashes at about the point that the colour component sliders become zero width.

Terminal output:
> Shutting down Allegro due to signal #8
> Floating point exception (core dumped)

**Comment by KasumiArai** [comment]
Can confirm it happens on Windows as well.
