### ISSUE TITLE
Moving selection with spacebar fails in beta9

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#954]
In Aseprite v1.1.2-beta9, I cannot move the selection while it is being created by holding spacebar.
In Aseprite v1.1.2-rc9, I can. This is the behavior I'm talking about: 
![selectionmoving](https://cloud.githubusercontent.com/assets/8582123/12837785/c9c2f05a-cb93-11e5-9359-d7bec52e5be4.gif)

The configuration files should be shared between rc/beta9, so I don't think it's a key configuration difference.

On Windows Vista 32 bit.

**Comment by dacap** [comment]
Nice catch :+1:

**Comment by KasumiArai** [comment]
Probably related, but if not I'll create a new issue. You also can't lock creation of shapes to "square" by holding shift if the action was started without holding shift, nor stop them from being "square" by releaseing shift if they were started while holding shift.. Same with control (start from center). 

Whatever's held down when the selection (or shape drawing) starts is locked regardless of pressing or releasing the keys mid action.

**Comment by dacap** [comment]
It's a related issue. I'll push a fix now and release a beta on Steam today. Thanks for your help! :wink:
