### ISSUE TITLE
New onionskin config icon isn't very clear

### ISSUE THREAD

**Issue by Async0x42** [aseprite/aseprite#956]
I'm not sure what others thing, but personally I feel like the old layer window config icon for onionskin was more obvious than the newest, for what the button does. The other icons haven't changed too drastically, but this one has.

i.e. -> This is a fairly standard config icon
![image](https://cloud.githubusercontent.com/assets/3268854/12878461/59ca97a0-cdf3-11e5-9b5f-33176131037b.png)

Whereas this doesn't seem obvious to me at all what it might be for:
![image](https://cloud.githubusercontent.com/assets/3268854/12878441/ef9049c0-cdf2-11e5-8336-933d40893ab4.png)

Also, the old eye icon felt a bit more subtle/smooth in the interface, or less 'in my face' than the newest change.

Any thoughts on these, or on the other icons from anyone else?

**Comment by dacap** [comment]
Hi @Async0x42, actually the old cog icon was a little confusing (the icon area is too small to draw a cog). I'm not 100% sure about the new eye icon, so I'm open to new ideas.

**Comment by sirblackheart** [comment]
maybe something in this direction?
![onionconfig_inverse](https://cloud.githubusercontent.com/assets/1131371/13446269/4111aa42-e012-11e5-9481-8e6293aa1600.png)
![onionconfig](https://cloud.githubusercontent.com/assets/1131371/13446268/4107430e-e012-11e5-8598-58ea87add7cb.png)

**Comment by Async0x42** [comment]
I think these are really clear as to the function of them. Personally, I think the second one might be better than the first, the first one the 3 slider rectangles might stick out a little too much because of that colour, but it could just be me (and I'm not totally sure I like #2 more than #1!)

**Comment by KasumiArai** [comment]
I actually really like that idea for settings.

**Comment by dacap** [comment]
I like it, I prefer the first one.

**Comment by Viomi** [comment]
I'm going to agree with @dacap , the first one is nicer.
