### ISSUE TITLE
Preview Window in second screen

### ISSUE THREAD

**Issue by pennaverde** [aseprite/aseprite#962]
Hi, I have a suggestion for Aseprite, can you ad support for multiscreen? Because I work with more than one screen and when I try to grab the preview window outside the main Aseprite window, it disappear.

**Comment by dacap** [comment]
Hi @pennaverde, it's already planned in #250, but it needs #139 first (which is a work-in-progress) to support multiple windows on the screen. It's something I'd love to have soon.
