### ISSUE TITLE
Bug: Frame Timing Undo Bug

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#965]
![frameundobug](https://cloud.githubusercontent.com/assets/8582123/13044360/c65aae2a-d39b-11e5-9ce4-39dc1d8852c6.gif)
1. Open the above image.
2. Remove frame 3 (200 msecs) using alt+r, r.
3. Remove frame 3 (60 msecs) using alt+r, r.
4. Remove frame 3 (60 msecs) using alt+r, r.
5. Remove frame 3 (180 msecs) using alt+r, r.
6. Undo all actions until you are at the starting state. 

All frames in the file except frame 1 now have 200 msecs of exposure, instead of what they had before they were removed. 

Edit: I checked and just selecting 3-6 and right clicking, removing them gives the same result. I only reported what I doing when it first happened. 

Aseprite v1.1.2-beta12 on Windows Vista 32bit

**Comment by dacap** [comment]
Thanks @KasumiArai for reporting this problem. I'll try to fix it right now.
