### ISSUE TITLE
Increase/decrease brush size with mouse wheel

### ISSUE THREAD

**Issue by chuiu** [aseprite/aseprite#970]
I would love to make a modifier key that I can hold down to control brush size with my mouse wheel.  I realize you can do it with +/- but those are far out of the way and its nice to be able to make quick adjustments.

Ideally I would hold down shift button to let me do that, but that is use for panning the canvas left/right.  I would like it if we could configure these ourselves though so I can still use shift and not have one to pan the canvas since I don't find that useful.

**Comment by dacap** [comment]
Related issues #177 (the same feature is requested in the comments) and #680 (customization of key modifier + mouse wheel)

**Comment by Ericloth** [comment]
Mousewheel is nice, but if you're drawing with a tablet, keys and dragging the pen is SUPER-nice. Photoshop and Tiled both support this. On Mac, it's Option+Control+ drag pen and a brush resizes on your screen. I think it's alt+right-click and drag on PC?

**Comment by dacap** [comment]
Related to https://community.aseprite.org/t/changing-brush-size-using-keyb-mouse/668

**Comment by astraldata** [comment]
I would prefer to use the mouse-wheel roll to change between animation frames -- please allow the option to pick between the two. I rather enjoy the hands-free pixeling workflow this option gives me when animating -- it's a little-known workflow over the masses, but it's very comfortable to roll the wheel to swap frames back and forth, then RMB-drag a rectangle selection to shift parts of a sprite around in Graphics Gale -- why shouldn't this be possible in Aseprite too?
