### ISSUE TITLE
Mouse button input isn't recognized

### ISSUE THREAD

**Issue by Busimus** [aseprite/aseprite#971]
OS: Arch Linux, 64 bit, nothing crazy. Tested on two machines.

Mouse clicks are not recognized at all. Native cursor setting doesn't fix anything.
The commit that introduced this bug is 3400cdba8bb8dfb41cc8b626fe64f7074d990606. The build from the preceding commit (7b8b2dae53e8fd374a426f3b7ace6a1746713d82) doesn't have this issue.

**Comment by dacap** [comment]
Hi @Busimus, are you using the Allegro library included in the Github repository or the Allegro (shared) library installed on your system version? (You can check this resizing the Aseprite window, if you can resize the window, you are using the one included in the Github repo.)

**Comment by Busimus** [comment]
The window resizes just fine, so I guess it's the one in the repo.

**Comment by kaerhon** [comment]
Same here, running it on Xubuntu 15.04, window resizes, but click won't work (mouse or wacom tablet equally)

**Comment by Viomi** [comment]
Same issue, but I figured out how to click.

If you hold down right click, then you can tap left click to left click. If you hold down left click, then you can tap right click a few times and it'll start right clicking.

I'm running ArchLinux with only Openbox as a window manager because I'm a minimalist.

**Comment by dacap** [comment]
I'll be seeing this issue today so I can release the Linux version.

**Comment by Derpford** [comment]
Same issue, Arch 64bit, window manager is both Awesome (in X11) and Sway (in Wayland, it's an i3 clone).

Right-clicking sometimes behaves like left-click, and sometimes does not. Holding right-mouse and clicking left-mouse behaves as Viomi described.
