### ISSUE TITLE
Color picker improvement

### ISSUE THREAD

**Issue by saint11** [aseprite/aseprite#972]
Pyxel Edit has this really cool feature in the color picker and I think this would help Aseprite a lot!
The image is pretty self explanatory :)
![img](http://i.imgur.com/mPxuoF6.png)

**Comment by dacap** [comment]
Hi @saint11! Some work is already in progress to improve the color picker is in #707, something like this should be included (also I'm thinking about a possible scripting API for customized color pickers, but maybe too much).
