### ISSUE TITLE
Save and eyedropper bugged after the program is left open for 8h+ (OS X)

### ISSUE THREAD

**Issue by alfredbaudisch** [aseprite/aseprite#981]
I opened Aseprite and put the computer to sleep. After 8 hours I awakened the computer and I tried to use Aseprite: the save dialog got stuck on the middle of the screen saying "0%" (the save worked, but the dialog is never dismissed, also the cancel button worked). Every time I tried to save again, the same happened.

Also the eyedropper didn't display information about the color on the status bar anymore.

After restarting it, everything worked again. OS X 10.10.5, Aseprite 1.1.2 Steam.

**Comment by dacap** [comment]
This issue should be fixed in v1.1.4 with 0605166cc6e5c5631add77ba1246ab9f9e1b3434
