### ISSUE TITLE
Smoother/incremental levels of zoom with the mouse wheel

### ISSUE THREAD

**Issue by alfredbaudisch** [aseprite/aseprite#982]
The zoom with the mouse wheel (USB Mouse in a Macbook) most of the time jumps extreme levels instead of being incremental. I.e. if I am at 50% and I try to increment with the wheel it jumps to 200% or even more. It's very hard to get to desired levels with the mouse wheel, the increments are really random.

PS: With the trackpad it works fine.

Consider GIMP, which increments proportionally:
- If you are at 50%, it jumps to 100%. 
- 100 -> 150
- 150 -> 200
- 200 -> 300
- and so on incrementing by 100

**GIFs showing the zooms:**
**Aseprite** (notice how it goes from 100 to 500 in a single scroll or vice versa):
![aseprite-wheel](https://cloud.githubusercontent.com/assets/248383/13372917/83aae810-dd37-11e5-9cb7-946615e360ae.gif)
![ase-nocontrol](https://cloud.githubusercontent.com/assets/248383/13372942/1a8da1a0-dd38-11e5-87f8-12fe08e057fa.gif)

**GIMP (notice the transition through all levels):**
![gimp-wheel](https://cloud.githubusercontent.com/assets/248383/13372918/87c41f70-dd37-11e5-8396-a7c5bfa0349b.gif)
![gimp-bettercontrol](https://cloud.githubusercontent.com/assets/248383/13372943/21c318ce-dd38-11e5-89f4-dc3d1209a936.gif)

**Comment by dacap** [comment]
Related to #810

**Comment by dacap** [comment]
This should be fixed in v1.1.9 with 2d2fb0038afe8e57280aff21d5f65ddce10c2e2e
