### ISSUE TITLE
Bug: ASEprite taskbar entry vanishing in Win7

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#984]
I haven't been able to isolate why and I'm not sure if it's something entirely on my side, but I recently updated to v1.1.2, and now ASEprite's entry on my Windows taskbar vanishes after a while. I haven't been able to isolate when or why this happens, but it's happening. Not sure if other people are having this issue.

I can still reach ASEprite via [ALT] + Tab, clicking on its window directly, and "Switch To" in Task Manager. The only issue seems to be that it's not appearing on the taskbar and it's a bit of a nuisance.
ASEprite appears as normal on the taskbar if I exit and restart it.
ASEprite reappears on the taskbar if I terminate Explorer and restart it.

ASEprite 1.1.2
Win7 Home SP1

I'll add details as I learn more.
Thanks for looking into it!

**Comment by dacap** [comment]
I'll close this issue as there are not reproducible steps and there weren't other bug reports about this same issue. I suspect it might be related to some random problem/bug in the Windows Explorer (as the Windows Explorer is the one that controls the taskbar).
