### ISSUE TITLE
freetype2 fails to build on Linux

### ISSUE THREAD

**Issue by Viomi** [aseprite/aseprite#987]
The commands I ran:

`git clone --recursive https://github.com/aseprite/aseprite.git`
`cd aseprite`
`cmake -G "Unix Makefiles" ~/aseprite`

Aseprite itself seems to build just fine, but when it's trying to build the submodules, freetype2 throws this error:

> CMake Error at third_party/freetype2/CMakeLists.txt:123 (message):
>   
> 
>   In-source builds are not permitted! Make a separate folder for building,
>   e.g.,
> 
>     mkdir build; cd build; cmake ..
> 
>   Before that, remove the files created by this failed run with
> 
>     rm -rf CMakeCache.txt CMakeFiles
> 
> 
> -- Configuring incomplete, errors occurred!

I'm running ArchLinux x64bit. I'm not using https://aur.archlinux.org/packages/aseprite-git in order to make sure this is an error with aseprite's building rather than the AUR PKGBUILD. (Though trying to use that yields the same result after fixing the 'git submodule update --init --recursive' related issue.)

Using it's suggestion (mkdir build; cd build; cmake ..) doesn't fix the issue, in fact it throws an identical one.

**Comment by Viomi** [comment]
Please close/trash this. I realized after submitting my mistake- This is definitely a user error (mostly because I was trying to do it the same way the aur package does it). Sorry! :P

**Comment by dacap** [comment]
Hi @Viomi, ok, I'll close this issue and take a look at the INSTALL.md which need a rewrite.
