### ISSUE TITLE
Can't press anything

### ISSUE THREAD

**Issue by Brottweiler** [aseprite/aseprite#988]
`v1.1.3` fixed the mouse lag! But I can't press anything. Hovering over the menus (File, Edit etc) highlights it, but pressing just unhighlights it but doesn't do anything else. I can't even press the X to close the "Home tab", I can't use the application.

I installed it via [AUR](https://aur.archlinux.org/packages/aseprite/).

**Comment by dacap** [comment]
Follow  #971 I'll be working on this today.
