### ISSUE TITLE
Alt-click eyedropper doesn't work

### ISSUE THREAD

**Issue by Viomi** [aseprite/aseprite#991]
The eyedropper tool works just fine if I hit "I" or go click on it in my tools. It -doesn't- work when I hold alt and then click somewhere on my picture. The symbol for my pencil changes to an eyedropper, and the eyedropper options show up on the top, but clicking does nothing.

ArchLinux 64bit, building from git

**Comment by dacap** [comment]
Thanks @sirblackheart for your help. Yes, it's a problem with some Linux window manager. I'll leave #796 open and mark this and #205 as duplicate.

**Comment by nenodias** [comment]
For lubuntu (lxde)
https://stackoverflow.com/questions/29198864/lubuntu-disable-alt-drag-move-window?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
